export const R240_SCHEMA='OMEGA_RECURSIVE_SELFBUILD_FABRIC_R240' as const;
export const R240_REVISION='R240' as const;
export const R240_CONTINUITY_OPERATOR='PARTITION → EXCHANGE/TRANSFORM → INVARIANT CARRY → SCAR/RESIDUAL CARRY → RE-CONTEXTUALIZE/REPARTITION' as const;
export const R240_RESOLUTION=Object.freeze({organs:12,branches:144,cells:1728,lanes:20736,deepAddress:248832});
export const R240_ORGANS=Object.freeze(['CANON_KERNEL','STATE_MEMORY','APPLIED_CALCULUS','EVIDENCE_WORLD','HYBRID_COMPUTE','CLOUD_FABRIC','INTELLIGENCE','SWARM_ORGANISM','PROOF_GOVERNANCE','RENDER_PROJECTION','OPERATOR_INTERFACE','EVOLUTION_BUILD'] as const);
export type R240Organ=typeof R240_ORGANS[number];
export type R240Risk='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export type R240CellState='DORMANT'|'READY'|'ACTIVE'|'RETURNED'|'VERIFIED'|'BLOCKED'|'REJECTED';
export type R240Orientation=-1|0|1;
export type R240PressureInput={contradiction:number;burden:number;residual:number;userValueDeficit:number;bottleneck:number;continuity:number};
export type R240WorkCell={id:string;address:number;laneStart:number;laneEnd:number;organ:R240Organ;branch:number;cell:number;objective:string;dependencies:string[];invariants:string[];files:string[];tests:string[];expectedGain:number;complexity:number;contradictionRisk:number;risk:R240Risk;orientation:R240Orientation;state:R240CellState;pressure:R240PressureInput;canonicalMutation:false};
export type R240PromotionReceipt={cellId:string;baseSha:string;candidateSha:string;invariantsPreserved:boolean;tests:Record<string,boolean>;residualGate:'PASS'|'BLOCK'|'UNPROVEN';returned:boolean;verified:boolean;sourcePromoted:boolean;productionProven:boolean;canonicalAdmission:false};
const clamp01=(n:number)=>Math.max(0,Math.min(1,Number.isFinite(n)?n:0));
export function r240CellAddress(organ:number,branch:number,cell:number){if(!Number.isInteger(organ)||organ<0||organ>=12)throw new Error('R240 organ index must be 0..11');if(!Number.isInteger(branch)||branch<0||branch>=12)throw new Error('R240 branch index must be 0..11');if(!Number.isInteger(cell)||cell<0||cell>=12)throw new Error('R240 cell index must be 0..11');return organ*144+branch*12+cell}
export function r240LaneRange(cellAddress:number){if(!Number.isInteger(cellAddress)||cellAddress<0||cellAddress>=1728)throw new Error('R240 cell address must be 0..1727');const laneStart=cellAddress*12;return{laneStart,laneEnd:laneStart+11}}
export function r240Pressure(x:R240PressureInput){const q=clamp01(x.contradiction),burden=clamp01(x.burden),residual=clamp01(x.residual),value=clamp01(x.userValueDeficit),bottleneck=clamp01(x.bottleneck),continuity=clamp01(x.continuity);return clamp01(.22*q+.16*burden+.22*residual+.14*value+.18*bottleneck+.08*(1-continuity))}
export function r240PromotionComplete(receipt:R240PromotionReceipt){return Boolean(receipt.baseSha&&receipt.candidateSha&&receipt.invariantsPreserved&&receipt.residualGate==='PASS'&&receipt.returned&&receipt.verified&&receipt.sourcePromoted&&receipt.productionProven&&Object.values(receipt.tests).length>0&&Object.values(receipt.tests).every(Boolean)&&receipt.canonicalAdmission===false)}
export function recursiveSelfBuildR240(cells:R240WorkCell[],completed:Iterable<string>,maxParallel=12){const done=new Set(completed);const width=Math.max(1,Math.min(144,Math.floor(maxParallel)||1));const frontier=cells.filter(cell=>cell.state!=='REJECTED'&&cell.state!=='BLOCKED'&&cell.dependencies.every(dep=>done.has(dep))).slice(0,width);return{schema:R240_SCHEMA,revision:R240_REVISION,continuityOperator:R240_CONTINUITY_OPERATOR,resolution:R240_RESOLUTION,organs:R240_ORGANS,sparseActivation:true,frontier,admissionLaw:'MAXIMUM INTERNAL EVOLUTION + STRICT EXTERNAL ADMISSION',truthLaw:'GENERATED != PROVED != SOURCE_PROMOTED != DEPLOYED != LIVE_VERIFIED != CANON_ADMITTED',schedulerAuthority:'R240_SCHEDULING_ONLY',sourcePromotionAuthority:'R240_BOUNDED_INSIDE_R170',productionWriter:'.github/workflows/ci.yml',canonicalAdmissionAuthority:'R125',dispatchAuthority:'R147',hybridReturnAuthority:'R141',durableHistoryAuthority:'R146',inheritsHybridResourceGovernor:'R239'}}
