import assert from'node:assert/strict';
import fs from'node:fs';
import{compileCanonicalTypedFieldR349}from'../src/system/wovenHardwareFieldR349';
import{compileProofBoundTemporalTraversalR355,R355_BOUNDARY,R355_SCHEMA,selectTemporalSceneR355}from'../src/system/proofBoundTemporalTraversalR355';

const currentSha='8b7153d95c8f055705c6ba76b58e8191a50dc251',worker='r354-worker-proof',receipt='d'.repeat(64);
const evidence={releaseEvidence:{source:{sha:currentSha},promotionLineage:{promotedMergeSha:currentSha},packageReceipt:{receiptSha256:receipt},runtimeVersion:{id:worker}},runtimeAttestation:{source:{sha:currentSha},bindings:{sourceSha:currentSha,packageReceiptSha256:receipt,cloudflareVersionId:worker},packageReceipt:{receiptSha256:receipt},runtimeVersion:{id:worker}},buildReceipt:{receiptSha256:receipt}};
const source=compileCanonicalTypedFieldR349(0,(a:number)=>({continuity:(a%144)/143,plasticity:(a%12)/11,burden:((a>>1)%12)/11,contradiction:((a>>2)%12)/11,scar:(a%5)/20,evidence:.8,invariantCarry:.25+(a%17)/68,motionRate:(a%9)/8,support:.5,orientation:1 as const}));
const traversal=await compileProofBoundTemporalTraversalR355({sourceField:source,evidence,steps:4,checkpointEvery:2,nowTick:2});
assert.equal(traversal.schema,R355_SCHEMA);assert.equal(traversal.nodes.length,5);assert.equal(traversal.scenes.length,5);assert.equal(traversal.proof.ordered,true);assert.equal(traversal.proof.lineageStable,true);assert.equal(traversal.proof.linkIntegrity,true);assert.equal(traversal.proof.allTimelineDeterministic,true);assert.equal(traversal.proof.allPacketExact,true);
assert.deepEqual(traversal.nodes.map(n=>n.relation),['HISTORY','HISTORY','NOW','FORECAST','FORECAST']);
assert.equal(traversal.nodes[0].previousLinkDigest,'R355-GENESIS');assert.match(traversal.traversalDigest,/^[0-9a-f]{64}$/);assert.equal(new Set(traversal.nodes.map(n=>n.linkDigest)).size,5);
const selected=selectTemporalSceneR355(traversal,3);assert.equal(selected.scene.tick,3);assert.equal(selected.scene.relation,'FORECAST');assert.equal(selected.node.sceneDigest,selected.scene.sceneDigest);
assert.equal(traversal.proof.canonicalMutation,false);assert.equal(traversal.proof.observedHistoryClaimed,false);assert.equal(traversal.proof.physicalTimeClaimed,false);assert.equal(traversal.proof.durableHistoryClaimed,false);
const core=fs.readFileSync('src/system/proofBoundTemporalTraversalR355.ts','utf8'),surface=fs.readFileSync('src/OmegaProofBoundTemporalTraversalR355.tsx','utf8'),suite=fs.readFileSync('src/OmegaSpecialistSuite.tsx','utf8'),pkg=fs.readFileSync('package.json','utf8'),doc=fs.readFileSync('R355_PROOF_BOUND_TEMPORAL_SCENE_TRAVERSAL.md','utf8');
for(const token of['R354','HISTORY','NOW','FORECAST','NO_NEW_PHYSICAL_PRIMITIVE','traversalDigest'])assert.ok(core.includes(token),`R355 core missing ${token}`);
for(const token of['OmegaProofBoundTemporalTraversalR355','R355 model-time address'])assert.ok((surface+suite).includes(token),`R355 integration missing ${token}`);
assert.ok(pkg.includes('"test:r355"'));assert.ok(pkg.includes('npm run test:r354 && npm run test:r355'));
for(const forbidden of['canonicalMutation:true','observedHistoryClaimed:true','physicalTimeClaimed:true','durableHistoryClaimed:true'])assert.ok(!(core+surface+doc).includes(forbidden),`R355 forbidden claim ${forbidden}`);
assert.ok(R355_BOUNDARY.includes('R125')&&R355_BOUNDARY.includes('R141')&&R355_BOUNDARY.includes('ci.yml'));
console.log('R355 PROOF-BOUND TEMPORAL SCENE TRAVERSAL PASS · every integer model-time address is an R354 scene receipt, digest-chained in temporal order with stable release lineage and explicit HISTORY/NOW/FORECAST relations · no new Canon/observation/physical-time/history/dispatch/production authority');
