import {SWARM_CELL_COUNT,capabilityProfile,decodeCell,stableSeed} from './swarmCoreR121.js';
import {allocateRelativeCompute} from '../causalInteractionRelativityR126.mjs';

export const CORTEX_REVISION='R127';
export const CORTEX_RUNTIME='OMEGA_R127_SYNAPTIC_ORGANISM_CORTEX';
export const CORTEX_ROLES=['ORCHESTRATION','SOFTWARE','RESEARCH','MATHEMATICS','PHYSICS','VISUAL','DATA','FORECAST','TOOLS','SOVEREIGN','PROOF','COORDINATION'];
export const CORTEX_LAWS=Object.freeze([
 'ONE_BODY_MANY_SPECIALISTS',
 'EVERY_TASK_HAS_AN_ADDRESS',
 'EVERY_RESULT_HAS_LINEAGE',
 'BLACKBOARD_MEMORY_IS_CANDIDATE_MEMORY_NOT_CANON',
 'SYNAPTIC_EXCHANGE_PRESERVES_EVIDENCE_AUTHORITY',
 'FAILURES_BECOME_SCARS_NOT_SILENT_DELETIONS',
 'QUORUM_IS_EXECUTION_AGREEMENT_NOT_TRUTH',
 'FULL_1728_REQUIRES_EXPLICIT_OPERATOR_INTENT_OR_EXPLICIT_FULL_AUTO',
 'MODEL_AND_MACHINE_BUDGETS_ARE_BOUNDED',
 'RETURNED_CORTEX_WORK_IS_NOT_CANONICAL_ADMISSION'
]);

const clip=(v,n=12000)=>String(v??'').trim().slice(0,n);
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Math.trunc(num(v,a))));
const c01=v=>Math.max(0,Math.min(1,num(v,0)));
const pad=v=>String(v).padStart(2,'0');
const taskKey=(missionId,id)=>`cortex:${missionId}:task:${id}`;
const missionKey=id=>`cortex:mission:${id}`;
const memoryKey=(missionId,id)=>`cortex:${missionId}:memory:${id}`;
const json=(v,s=200)=>new Response(JSON.stringify(v,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-cortex-runtime':CORTEX_REVISION,'x-omega-autonomic-runtime':'R125','x-omega-organism-runtime':'R123','x-omega-swarm-runtime':'R121'}});
async function sha(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof v==='string'?v:JSON.stringify(v)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function merkle(leaves=[]){let level=leaves.filter(Boolean).map(String).sort();if(!level.length)return sha('OMEGA_EMPTY_CORTEX_R127');while(level.length>1){const next=[];for(let i=0;i<level.length;i+=2)next.push(await sha(`${level[i]}|${level[i+1]||level[i]}`));level=next}return level[0]}
function evidence(input){return(Array.isArray(input)?input:[]).slice(0,16).map((x,i)=>({id:clip(x?.id||`evidence-${i+1}`,100),type:clip(x?.type||'OPERATOR_CONTEXT',80),sha256:/^[a-f0-9]{64}$/i.test(String(x?.sha256||''))?String(x.sha256).toLowerCase():null,summary:clip(x?.summary||x?.text||'',1200),authority:clip(x?.authority||'OPERATOR_SUPPLIED_NOT_INDEPENDENTLY_VERIFIED',140)}))}
function metrics(m={}){return{novelty:c01(m.novelty??m.plasticity??.5),uncertainty:c01(m.uncertainty??.5),contradiction:c01(m.contradiction??.2),proofUrgency:c01(m.proofUrgency??(1-c01(m.evidence??.4))),motion:c01(m.motion??.3),observerRelevance:c01(m.observerRelevance??.6),expectedInformationGain:c01(m.expectedInformationGain??.6),cost:c01(m.cost??m.burden??.3)}}
function modeCount(mode,relative,allowFullAuto){const m=String(mode||'ADAPTIVE').toUpperCase();if(m==='SOLO')return 1;if(m==='ORGAN')return 12;if(m==='BRANCH')return 144;if(m==='FLOCK')return 288;if(m==='BODY'||m==='FULL')return 1728;const proposed=relative.lanes<=1?1:relative.lanes<=12?12:relative.lanes<=144?144:relative.lanes<=1728?1728:1728;return proposed===1728&&!allowFullAuto?288:proposed}
function distributedIndices(count,seed){if(count>=SWARM_CELL_COUNT)return Array.from({length:SWARM_CELL_COUNT},(_,i)=>i);const offset=stableSeed(`cortex|${seed}`)%SWARM_CELL_COUNT,out=[],seen=new Set();for(let k=0;k<count;k++){let i=(offset+Math.floor(k*SWARM_CELL_COUNT/count))%SWARM_CELL_COUNT;while(seen.has(i))i=(i+1)%SWARM_CELL_COUNT;seen.add(i);out.push(i)}return out}
function cellId(index){const a=decodeCell(index);return`omega-cell-${pad(a.domain)}-${pad(a.phase)}-${pad(a.regulation)}`}
function proofIndex(domain,phase){return 10*144+domain*12+phase}
function coordinationIndex(domain){return 11*144+domain*12}
export function synapticNeighborsR127(index){const a=decodeCell(index),neighbors=new Set(),add=(d,p,r)=>neighbors.add(d*144+p*12+r);add(a.domain,a.phase,(a.regulation+11)%12);add(a.domain,a.phase,(a.regulation+1)%12);add(a.domain,(a.phase+11)%12,a.regulation);add(a.domain,(a.phase+1)%12,a.regulation);add((a.domain+11)%12,a.phase,a.regulation);add((a.domain+1)%12,a.phase,a.regulation);add(10,a.domain,a.phase);add(11,a.domain,0);neighbors.delete(index);return[...neighbors].slice(0,8).map(i=>({index:i,id:cellId(i),address:decodeCell(i)}))}
function connect(tasks,parent,child){const p=tasks.get(parent),c=tasks.get(child);if(!p||!c)return;if(!p.children.includes(child))p.children.push(child);if(!c.dependencies.includes(parent)){c.dependencies.push(parent);c.remainingDeps=c.dependencies.length}}
function publicTask(t){return{id:t.id,kind:t.kind,wave:t.wave,cellId:t.cellId,index:t.index,status:t.status,executor:t.executor,remainingDeps:t.remainingDeps,dependencyCount:t.dependencies.length,childCount:t.children.length,address:t.address,role:t.role}}
function taskObjective(t,intent){const role=t.role||t.kind;if(t.kind==='FRAME')return`Frame the whole mission without solving it prematurely. Preserve constraints, evidence authority, truth boundaries, and an explicit work decomposition for the body. Mission: ${intent}`;if(t.kind==='CELL')return`Work as one independent cell inside a larger organism. Produce a bounded specialist contribution from role ${role}. Preserve disagreement and missing proof. Do not synthesize the entire mission. Mission: ${intent}`;if(t.kind==='BRANCH_CHECK')return`Cross-check the completed branch contributions for contradictions, duplicated assumptions, missing evidence, and invariant carry. This is branch-level error correction, not canonical judgment. Mission: ${intent}`;if(t.kind==='ORGAN_SYNTHESIS')return`Synthesize the branch checks for organ ${role}. Preserve minority findings, scar history, evidence authority, unresolved contradictions, and actionable handoffs to other organs. Mission: ${intent}`;return`Reconverge the organ syntheses into one proof-bounded return packet. Distinguish evidence, inference, disagreement, missing proof, and proposed next actions. Execution agreement is not truth. Mission: ${intent}`}
function assignExecutors(tasks,input){const total=clamp(input.providerBudget??8,0,12),finalAi=total>0?1:0,organAi=Math.max(0,total-finalAi),organs=[...tasks.values()].filter(t=>t.kind==='ORGAN_SYNTHESIS').sort((a,b)=>a.address.domain-b.address.domain);for(let i=0;i<Math.min(organAi,organs.length);i++)organs[i].executor='WORKERS_AI';const final=tasks.get('proof:return');if(final&&finalAi)final.executor='WORKERS_AI';const projection=String(input.projection||'').toUpperCase();if(projection==='BUILD'){const candidate=[...tasks.values()].find(t=>t.kind==='CELL'&&t.address.domain===0&&t.address.phase===0);if(candidate&&clamp(input.genesisBudget??1,0,2)>0)candidate.executor='GENESIS'}if(projection==='OPTICAL'){const candidate=[...tasks.values()].find(t=>t.kind==='CELL'&&t.address.domain===4&&t.address.phase===3);if(candidate&&clamp(input.opticalBudget??1,0,2)>0)candidate.executor='OPTICAL_CHAIN'}return{providerTotal:total,providerOrgan:Math.min(organAi,organs.length),providerReconvergence:finalAi,genesis:projection==='BUILD'?clamp(input.genesisBudget??1,0,2):0,optical:projection==='OPTICAL'?clamp(input.opticalBudget??1,0,2):0}}

export function planCortexMissionR127(input={}){
 const intent=clip(input.intent||input.text,8000);if(!intent)throw new Error('INTENT_REQUIRED');
 const m=metrics(input.metrics),relative=allocateRelativeCompute(m),mode=String(input.mode||'ADAPTIVE').toUpperCase(),explicitFull=mode==='FULL'||mode==='BODY',allowFullAuto=input.allowFullAuto===true||explicitFull,count=modeCount(mode,relative,allowFullAuto),seed=stableSeed(`${intent}|${input.projection||'FIELD'}|${mode}|${input.seed||''}`),selected=distributedIndices(count,seed),tasks=new Map();
 const root={id:'seed:frame',kind:'FRAME',wave:0,index:0,cellId:cellId(0),address:decodeCell(0),role:CORTEX_ROLES[0],dependencies:[],children:[],remainingDeps:0,status:'READY',executor:'DETERMINISTIC',attempts:0};tasks.set(root.id,root);
 const branchMembers=new Map(),organBranches=new Map();
 for(const index of selected){const a=decodeCell(index),profile=capabilityProfile(a),id=`cell:${profile.cellId}`,t={id,kind:'CELL',wave:1,index,cellId:profile.cellId,address:a,role:profile.domainRole,dependencies:[],children:[],remainingDeps:0,status:'WAITING',executor:'DETERMINISTIC',attempts:0};tasks.set(id,t);connect(tasks,'seed:frame',id);const bk=`${a.domain}:${a.phase}`;if(!branchMembers.has(bk))branchMembers.set(bk,[]);branchMembers.get(bk).push(id)}
 for(const[bk,members]of branchMembers){const[d,p]=bk.split(':').map(Number),index=proofIndex(d,p),id=`branch:${pad(d)}:${pad(p)}:check`,t={id,kind:'BRANCH_CHECK',wave:2,index,cellId:cellId(index),address:decodeCell(index),role:`${CORTEX_ROLES[d]} branch ${pad(p)}`,dependencies:[],children:[],remainingDeps:0,status:'WAITING',executor:'DETERMINISTIC',attempts:0};tasks.set(id,t);for(const member of members)connect(tasks,member,id);if(!organBranches.has(d))organBranches.set(d,[]);organBranches.get(d).push(id)}
 for(const[d,branches]of organBranches){const index=coordinationIndex(d),id=`organ:${pad(d)}:synthesis`,t={id,kind:'ORGAN_SYNTHESIS',wave:3,index,cellId:cellId(index),address:decodeCell(index),role:CORTEX_ROLES[d],dependencies:[],children:[],remainingDeps:0,status:'WAITING',executor:'DETERMINISTIC',attempts:0};tasks.set(id,t);for(const branch of branches)connect(tasks,branch,id)}
 const finalIndex=10*144+11*12+11,final={id:'proof:return',kind:'PROOF_RETURN',wave:4,index:finalIndex,cellId:cellId(finalIndex),address:decodeCell(finalIndex),role:'PROOF + COORDINATION',dependencies:[],children:[],remainingDeps:0,status:'WAITING',executor:'DETERMINISTIC',attempts:0};tasks.set(final.id,final);for(const t of tasks.values())if(t.kind==='ORGAN_SYNTHESIS')connect(tasks,t.id,final.id);
 const budgets=assignExecutors(tasks,input),taskList=[...tasks.values()],waves=[0,1,2,3,4].map(w=>({wave:w,tasks:taskList.filter(t=>t.wave===w).length}));
 return{schema:'OMEGA_CORTEX_PLAN_R127',runtime:CORTEX_RUNTIME,revision:CORTEX_REVISION,intent,projection:clip(input.projection||'FIELD',40).toUpperCase(),mode,explicitFull,allowFullAuto,relativeCompute:relative,selectedCellCount:selected.length,totalTaskCount:taskList.length,totalBranchChecks:taskList.filter(t=>t.kind==='BRANCH_CHECK').length,totalOrganSyntheses:taskList.filter(t=>t.kind==='ORGAN_SYNTHESIS').length,waves,budgets,evidence:evidence(input.evidence),seed,tasks:taskList,hierarchy:{seed:1,organs:12,branches:144,cells:1728,lanes:20736},authority:'CORTEX_EXECUTION_FABRIC_NOT_CANON',truthBoundary:'R127 makes the 1→12→144→1,728 body interact through causal dependencies, shared candidate memory, synaptic routing and staged reconvergence. The graph is computation, not empirical truth. Returned work remains unadmitted until normal OMEGAv6 proof/admission.'}
}
export function publicCortexPlanR127(plan){return{...plan,tasks:undefined,taskSample:plan.tasks.slice(0,24).map(publicTask)}}

export class OmegaSwarmCortex{
 constructor(state,env){this.storage=state.storage;this.env=env}
 async ids(){return(await this.storage.get('cortex:ids'))||[]}
 async mission(id){return this.storage.get(missionKey(id))}
 async saveMission(m){await this.storage.put(missionKey(m.id),m);const ids=await this.ids();if(!ids.includes(m.id))await this.storage.put('cortex:ids',[m.id,...ids].slice(0,48));return m}
 async putTasks(missionId,tasks){for(let i=0;i<tasks.length;i+=64){const batch={};for(const t of tasks.slice(i,i+64))batch[taskKey(missionId,t.id)]=t;await this.storage.put(batch)}}
 async getTask(missionId,id){return this.storage.get(taskKey(missionId,id))}
 async saveTask(missionId,t){await this.storage.put(taskKey(missionId,t.id),t);return t}
 event(m,type,detail={}){m.events=[...(m.events||[]),{seq:Number(m.eventSeq||0)+1,at:Date.now(),type,...detail}].slice(-160);m.eventSeq=Number(m.eventSeq||0)+1}
 async create(body){const plan=planCortexMissionR127(body),id=`cortex_${Date.now().toString(36)}_${(await sha(`${plan.seed}|${Date.now()}`)).slice(0,10)}`,now=Date.now(),m={schema:'OMEGA_CORTEX_MISSION_R127',runtime:CORTEX_RUNTIME,revision:CORTEX_REVISION,id,status:'QUEUED',intent:plan.intent,projection:plan.projection,mode:plan.mode,createdAt:now,updatedAt:now,selectedCellCount:plan.selectedCellCount,totalTaskCount:plan.totalTaskCount,totalBranchChecks:plan.totalBranchChecks,totalOrganSyntheses:plan.totalOrganSyntheses,completedTasks:0,failedTasks:0,readyQueue:['seed:frame'],runningTasks:0,memoryCount:0,scarCount:0,receiptHashes:[],evidence:plan.evidence,budgets:plan.budgets,relativeCompute:plan.relativeCompute,waves:plan.waves,events:[],eventSeq:0,canonicalMutation:false,proofState:'QUEUED_NOT_ADMITTED',authority:'CORTEX_EXECUTION_FABRIC_NOT_CANON'};this.event(m,'MISSION_CREATED',{tasks:m.totalTaskCount,cells:m.selectedCellCount});await this.putTasks(id,plan.tasks);await this.saveMission(m);await this.storage.setAlarm(Date.now()+100);return{mission:m,plan:publicCortexPlanR127(plan)}}
 async contextFor(m,t){const deps=[];for(const id of t.dependencies.slice(0,16)){const d=await this.getTask(m.id,id);if(d?.resultSummary)deps.push(`[${d.id} ${d.status}] ${clip(d.resultSummary,700)}`)}return deps.join('\n').slice(0,7000)}
 async runTask(m,t){if(!this.env?.OMEGA_SWARM_CELL)throw new Error('SWARM_CELL_BINDING_UNAVAILABLE');const context=await this.contextFor(m,t),objective=taskObjective(t,m.intent),payload={missionId:m.id,taskId:t.id,cellId:t.cellId,index:t.index,intent:`${objective}${context?`\n\nUPSTREAM CANDIDATE RESULTS (not canonical evidence):\n${context}`:''}`,executor:t.executor,evidence:m.evidence,lineage:[`omega-v6:cortex:${m.id}`,`wave:${t.wave}`,`task:${t.id}`,`role:${t.role}`]};const stub=this.env.OMEGA_SWARM_CELL.get(this.env.OMEGA_SWARM_CELL.idFromName(t.cellId)),response=await stub.fetch(new Request('https://cell.internal/task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})),data=await response.json().catch(()=>null);if(!response.ok||!data?.receipt)throw new Error(data?.error||data?.code||`CELL_${response.status}`);return data}
 async releaseChildren(m,t){for(const childId of t.children){const child=await this.getTask(m.id,childId);if(!child||!['WAITING','READY'].includes(child.status))continue;child.remainingDeps=Math.max(0,Number(child.remainingDeps||0)-1);if(child.remainingDeps===0&&child.status!=='READY'){child.status='READY';m.readyQueue.push(child.id);this.event(m,'TASK_READY',{taskId:child.id,wave:child.wave})}await this.saveTask(m.id,child)}}
 async completeTask(m,t,data){t.status='COMPLETE';t.completedAt=Date.now();t.receiptHash=await sha(data.receipt);t.resultSummary=clip(data?.result?.summary||data?.result?.truthBoundary||data?.cell?.lastResultPreview?.summary||'Task completed without a textual summary.',1800);t.resultKind=clip(data?.result?.kind||'UNKNOWN',100);t.canonicalMutation=false;m.completedTasks++;m.receiptHashes.push(t.receiptHash);m.receiptHashes=m.receiptHashes.slice(-2200);const memory={schema:'OMEGA_CORTEX_MEMORY_R127',missionId:m.id,taskId:t.id,cellId:t.cellId,address:t.address,role:t.role,wave:t.wave,summary:t.resultSummary,resultKind:t.resultKind,receiptHash:t.receiptHash,synapses:synapticNeighborsR127(t.index),createdAt:t.completedAt,authority:'SWARM_CANDIDATE_MEMORY_NOT_CANON',canonicalMutation:false};await this.storage.put(memoryKey(m.id,t.id),memory);m.memoryCount++;this.event(m,'TASK_COMPLETE',{taskId:t.id,cellId:t.cellId,wave:t.wave});await this.saveTask(m.id,t);await this.releaseChildren(m,t)}
 async failTask(m,t,error){t.attempts=Number(t.attempts||0)+1;t.lastError=clip(error instanceof Error?error.message:String(error),900);if(t.executor==='DETERMINISTIC'&&t.attempts<=1){t.status='READY';m.readyQueue.push(t.id);this.event(m,'TASK_RETRY',{taskId:t.id,error:t.lastError});await this.saveTask(m.id,t);return}t.status='FAILED';t.completedAt=Date.now();m.failedTasks++;m.scarCount++;this.event(m,'TASK_SCAR',{taskId:t.id,error:t.lastError});await this.saveTask(m.id,t);await this.releaseChildren(m,t)}
 async finalize(m){m.status=m.completedTasks>0?'COMPLETE':'FAILED';m.completedAt=Date.now();m.updatedAt=m.completedAt;m.proofState='RETURNED_NOT_ADMITTED';m.merkleRoot=await merkle(m.receiptHashes);m.quorum={schema:'OMEGA_CORTEX_EXECUTION_QUORUM_R127',taskSuccess:m.totalTaskCount?m.completedTasks/m.totalTaskCount:0,taskFailure:m.totalTaskCount?m.failedTasks/m.totalTaskCount:0,memoryCoverage:m.totalTaskCount?m.memoryCount/m.totalTaskCount:0,scarCount:m.scarCount,authority:'EXECUTION_QUORUM_NOT_TRUTH'};m.receipt={schema:'OMEGA_CORTEX_RECEIPT_R127',missionId:m.id,projection:m.projection,mode:m.mode,selectedCellCount:m.selectedCellCount,totalTaskCount:m.totalTaskCount,completedTasks:m.completedTasks,failedTasks:m.failedTasks,memoryCount:m.memoryCount,scarCount:m.scarCount,merkleRoot:m.merkleRoot,quorum:m.quorum,createdAt:m.createdAt,completedAt:m.completedAt,canonicalMutation:false,authority:'CORTEX_RECEIPT_RETURNED_NOT_ADMITTED'};m.checkpointSha256=await sha(m.receipt);this.event(m,'MISSION_COMPLETE',{proofState:m.proofState,merkleRoot:m.merkleRoot});return this.saveMission(m)}
 async advance(id,batchSize=12){const m=await this.mission(id);if(!m)return null;if(!['QUEUED','RUNNING'].includes(m.status))return m;m.status='RUNNING';const batch=clamp(batchSize,1,24),run=m.readyQueue.splice(0,batch);for(const taskId of run){const t=await this.getTask(id,taskId);if(!t||t.status!=='READY')continue;t.status='RUNNING';t.startedAt=Date.now();await this.saveTask(id,t);try{const data=await this.runTask(m,t);await this.completeTask(m,t,data)}catch(error){await this.failTask(m,t,error)}}m.updatedAt=Date.now();const terminal=m.completedTasks+m.failedTasks;if(terminal>=m.totalTaskCount)await this.finalize(m);else{await this.saveMission(m);if(m.status==='RUNNING'&&m.readyQueue.length)await this.storage.setAlarm(Date.now()+120)}return m}
 async checkpoint(m){const body={missionId:m.id,status:m.status,projection:m.projection,mode:m.mode,completedTasks:m.completedTasks,failedTasks:m.failedTasks,ready:m.readyQueue.length,memoryCount:m.memoryCount,scarCount:m.scarCount,eventSeq:m.eventSeq,updatedAt:m.updatedAt,canonicalMutation:false};return{...body,sha256:await sha(body),authority:'CORTEX_CHECKPOINT_NOT_CANON'}}
 async memory(m,limit=48){const prefix=`cortex:${m.id}:memory:`,map=await this.storage.list({prefix,limit:clamp(limit,1,96),reverse:true});return[...map.values()]}
 async status(){const ids=await this.ids(),missions=[];for(const id of ids.slice(0,12)){const m=await this.mission(id);if(m)missions.push(this.pub(m))}return{ok:true,schema:'OMEGA_CORTEX_STATUS_R127',runtime:CORTEX_RUNTIME,revision:CORTEX_REVISION,missions,canonicalMutation:false,truthBoundary:'Cortex mission status is execution state. It is not CanonState or external-world truth.'}}
 pub(m){if(!m)return null;const{evidence,receiptHashes,readyQueue,events,...x}=m;return{...x,ready:readyQueue?.length||0,evidenceCount:evidence?.length||0,eventCount:events?.length||0,progress:m.totalTaskCount?Math.round(((m.completedTasks+m.failedTasks)/m.totalTaskCount)*1000)/10:0}}
 async fetch(request){const u=new URL(request.url),path=u.pathname;if(request.method==='GET'&&path==='/status')return json(await this.status());if(request.method==='POST'&&path==='/plan'){try{return json({ok:true,plan:publicCortexPlanR127(planCortexMissionR127(await request.json().catch(()=>({}))))})}catch(error){return json({ok:false,code:error instanceof Error?error.message:String(error)},400)}}if(request.method==='POST'&&path==='/missions'){try{const r=await this.create(await request.json().catch(()=>({})));return json({ok:true,...r},202)}catch(error){return json({ok:false,code:error instanceof Error?error.message:String(error)},400)}}const m=path.match(/^\/missions\/([^/]+)(?:\/(advance|pause|resume|cancel|checkpoint|memory|events|rejoin))?$/);if(!m)return json({ok:false,code:'CORTEX_ROUTE_NOT_FOUND'},404);const id=decodeURIComponent(m[1]),action=m[2],mission=await this.mission(id);if(!mission)return json({ok:false,code:'CORTEX_MISSION_NOT_FOUND'},404);if(!action&&request.method==='GET')return json({ok:true,mission:this.pub(mission)});if(action==='advance'&&request.method==='POST')return json({ok:true,mission:this.pub(await this.advance(id,(await request.json().catch(()=>({})))?.batchSize||12))});if(action==='pause'&&request.method==='POST'){mission.status='PAUSED';this.event(mission,'MISSION_PAUSED');await this.saveMission(mission);return json({ok:true,mission:this.pub(mission)})}if(action==='resume'&&request.method==='POST'){if(mission.status==='PAUSED'){mission.status='RUNNING';this.event(mission,'MISSION_RESUMED');await this.saveMission(mission);if(mission.readyQueue.length)await this.storage.setAlarm(Date.now()+80)}return json({ok:true,mission:this.pub(mission)})}if(action==='cancel'&&request.method==='POST'){mission.status='CANCELLED';mission.proofState='CANCELLED_NOT_ADMITTED';this.event(mission,'MISSION_CANCELLED');await this.saveMission(mission);return json({ok:true,mission:this.pub(mission)})}if(action==='checkpoint'&&request.method==='GET')return json({ok:true,checkpoint:await this.checkpoint(mission)});if(action==='memory'&&request.method==='GET')return json({ok:true,memory:await this.memory(mission,Number(u.searchParams.get('limit')||48))});if(action==='events'&&request.method==='GET')return json({ok:true,events:mission.events||[],eventSeq:mission.eventSeq||0});if(action==='rejoin'&&request.method==='POST'){if(mission.status!=='COMPLETE')return json({ok:false,code:'CORTEX_NOT_COMPLETE',mission:this.pub(mission)},409);mission.rejoinedAt=Date.now();mission.proofState='RETURNED_NOT_ADMITTED';this.event(mission,'CORTEX_REJOINED_TO_OPERATOR_BODY',{authority:'CORTEX_RECEIPT_RETURNED_NOT_ADMITTED'});await this.saveMission(mission);return json({ok:true,receipt:mission.receipt,checkpointSha256:mission.checkpointSha256,authority:'CORTEX_RECEIPT_RETURNED_NOT_ADMITTED',canonicalMutation:false})}return json({ok:false,code:'CORTEX_METHOD_NOT_ALLOWED'},405)}
 async alarm(){const ids=await this.ids();for(const id of ids){const m=await this.mission(id);if(m&&m.status==='RUNNING'&&m.readyQueue?.length){await this.advance(id,12);return}if(m&&m.status==='QUEUED'){await this.advance(id,12);return}}}
}
