import {SWARM_CELL_COUNT,SWARM_DOMAIN_ROLES,SWARM_LANE_COUNT,compactPlanR121,planMissionR121} from './swarmCoreR121.js';
import {SWARM_MODEL_R121} from './swarmCellR121.js';

export const ORGANISM_REVISION='R123';
const clip=(v,n=12000)=>String(v??'').trim().slice(0,n);
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Math.trunc(num(v,a))));
const json=(v,s=200)=>new Response(JSON.stringify(v,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-organism-runtime':ORGANISM_REVISION,'x-omega-swarm-runtime':'R121'}});
async function sha(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof v==='string'?v:JSON.stringify(v)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function merkle(leaves){let level=(leaves||[]).filter(Boolean).map(String).sort();if(!level.length)return sha('OMEGA_EMPTY_MERKLE_R123');while(level.length>1){const next=[];for(let i=0;i<level.length;i+=2)next.push(await sha(`${level[i]}|${level[i+1]||level[i]}`));level=next}return level[0]}
function modelText(r){if(typeof r==='string')return r;if(typeof r?.response==='string')return r.response;if(typeof r?.result?.response==='string')return r.result.response;return typeof r?.choices?.[0]?.message?.content==='string'?r.choices[0].message.content:''}
function sanitizeEvidence(input){return(Array.isArray(input)?input:[]).slice(0,16).map((x,i)=>({id:clip(x?.id||`evidence-${i+1}`,100),type:clip(x?.type||'OPERATOR_CONTEXT',80),sha256:/^[a-f0-9]{64}$/i.test(String(x?.sha256||''))?String(x.sha256).toLowerCase():null,summary:clip(x?.summary||x?.text||'',1200),authority:clip(x?.authority||'OPERATOR_SUPPLIED_NOT_INDEPENDENTLY_VERIFIED',120)}))}
function branchKey(domain,phase){return `${String(domain+1).padStart(2,'0')}:${String(phase+1).padStart(2,'0')}`}
function taskExecutor(cell,budgets){if(cell.profile.domainRole==='ORCHESTRATION'&&cell.profile.phaseRole==='FRAME'&&budgets.genesis>0){budgets.genesis--;return'GENESIS'}if(cell.profile.domainRole==='PHYSICS'&&cell.profile.phaseRole==='EXECUTE'&&budgets.optical>0){budgets.optical--;return'OPTICAL_CHAIN'}if(cell.providerEligible&&budgets.ai>0){budgets.ai--;return'WORKERS_AI'}return'DETERMINISTIC'}
export function planOrganismMissionR123(input={}){const totalProviderBudget=clamp(input.providerBudget??6,0,12),reconvergeWithAI=input.reconvergeWithAI!==false&&totalProviderBudget>0,cellAiBudget=Math.max(0,totalProviderBudget-(reconvergeWithAI?1:0)),base=planMissionR121({...input,providerBudget:cellAiBudget}),budgets={ai:cellAiBudget,genesis:clamp(input.genesisBudget??1,0,2),optical:clamp(input.opticalBudget??1,0,2)},evidence=sanitizeEvidence(input.evidence),branchMap=new Map();for(const cell of base.selected){const key=branchKey(cell.address.domain,cell.address.phase),copy={...cell,executor:taskExecutor(cell,budgets)};if(!branchMap.has(key))branchMap.set(key,{key,domain:cell.address.domain,phase:cell.address.phase,organ:cell.profile.domainRole,cells:[]});branchMap.get(key).cells.push(copy)}const branches=[...branchMap.values()].sort((a,b)=>a.domain-b.domain||a.phase-b.phase),organCounts=Array.from({length:12},(_,d)=>branches.filter(b=>b.domain===d).length);return{...base,schema:'OMEGA_ORGANISM_PLAN_R123',runtimeRevision:ORGANISM_REVISION,totalProviderBudget,reconvergeWithAI,cellAiBudget,evidence,branches,branchCount:branches.length,organBranchCounts:organCounts,budgets:{providerTotal:totalProviderBudget,providerCells:cellAiBudget,reconvergence:reconvergeWithAI?1:0,genesis:clamp(input.genesisBudget??1,0,2),optical:clamp(input.opticalBudget??1,0,2)},deadlineMs:clamp(input.deadlineMs??900000,30000,1800000),branchConcurrency:clamp(input.branchConcurrency??(base.mode==='PIPELINE'?1:4),1,12),maxDeterministicRetries:clamp(input.maxDeterministicRetries??1,0,2),hierarchy:{seed:1,organs:12,branches:144,cells:SWARM_CELL_COUNT,lanes:SWARM_LANE_COUNT},authority:'RESULT_FABRIC_NOT_CANON'} }
function publicMission(m){if(!m)return null;const {queue,providerContributions,...rest}=m;return{...rest,queueDepth:Array.isArray(queue)?queue.length:0,providerContributionCount:Array.isArray(providerContributions)?providerContributions.length:0,progress:m.totalCells?Math.round(((m.completedCells+m.failedCells)/m.totalCells)*1000)/10:0}}

export class OmegaSwarmBranch{
 constructor(state,env){this.storage=state.storage;this.env=env}
 async fetch(request){if(request.method==='GET')return json({ok:true,state:(await this.storage.get('state'))||{status:'IDLE',runs:0,failures:0}});if(request.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);const job=await request.json().catch(()=>({})),cells=Array.isArray(job.cells)?job.cells.slice(0,12):[],startedAt=Date.now(),previous=(await this.storage.get('state'))||{runs:0,failures:0};if(!this.env?.OMEGA_SWARM_CELL)return json({ok:false,code:'CELL_BINDING_UNAVAILABLE'},503);await this.storage.put('state',{...previous,status:'WORKING',missionId:job.missionId,domain:job.domain,phase:job.phase,startedAt});const results=[];for(const cell of cells){const run=async()=>{const id=this.env.OMEGA_SWARM_CELL.idFromName(cell.id),stub=this.env.OMEGA_SWARM_CELL.get(id),task={schema:'OMEGA_ORGANISM_CELL_TASK_R123',missionId:job.missionId,taskId:`${job.missionId}:${cell.index}`,cellId:cell.id,index:cell.index,lane:cell.lane,intent:job.intent,mode:job.mode,executor:cell.executor||'DETERMINISTIC',evidence:job.evidence||[],lineage:[...(job.lineage||[]),`branch:${branchKey(job.domain,job.phase)}`,`cell:${cell.id}`]};const r=await stub.fetch(new Request('https://swarm-cell.internal/task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(task)}));return{cell,ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}};let out=await run();if(!out.ok&&cell.executor==='DETERMINISTIC'&&num(job.maxDeterministicRetries)>0){for(let retry=0;retry<job.maxDeterministicRetries&&!out.ok;retry++)out=await run()}results.push(out)}const completed=results.filter(x=>x.ok).length,failed=results.length-completed,receiptLeaves=results.map(x=>x.data?.receipt?.resultSha256).filter(Boolean),root=await merkle(receiptLeaves),contributions=results.filter(x=>x.ok&&x.cell.executor==='WORKERS_AI').map(x=>({cellId:x.cell.id,role:x.cell.profile?.domainRole,summary:clip(x.data?.result?.summary,1400)})).filter(x=>x.summary),finishedAt=Date.now(),receipt={schema:'OMEGA_BRANCH_RECEIPT_R123',missionId:job.missionId,branch:branchKey(job.domain,job.phase),domain:job.domain,phase:job.phase,cells:results.length,completed,failed,merkleRoot:root,startedAt,finishedAt,runtimeMs:finishedAt-startedAt,canonicalMutation:false};await this.storage.put('state',{status:failed?'DEGRADED':'IDLE',missionId:job.missionId,domain:job.domain,phase:job.phase,runs:num(previous.runs)+1,failures:num(previous.failures)+failed,lastReceipt:receipt,heartbeatAt:finishedAt});return json({ok:completed>0||!results.length,receipt,results:results.map(x=>({cellId:x.cell.id,index:x.cell.index,executor:x.cell.executor,ok:x.ok,status:x.status,receiptSha:x.data?.receipt?.resultSha256||null,summary:clip(x.data?.result?.summary||x.data?.result?.truthBoundary||x.data?.error||x.data?.code,900)})),contributions},failed?207:200)}
}

export class OmegaSwarmOrgan{
 constructor(state,env){this.storage=state.storage;this.env=env}
 async fetch(request){const u=new URL(request.url);if(request.method==='GET')return json({ok:true,state:(await this.storage.get('state'))||{status:'IDLE',branchRuns:0,cellRuns:0,failures:0}});if(request.method!=='POST'||u.pathname!=='/branch')return json({ok:false,code:'NOT_FOUND'},404);const job=await request.json().catch(()=>({}));if(!this.env?.OMEGA_SWARM_BRANCH)return json({ok:false,code:'BRANCH_BINDING_UNAVAILABLE'},503);const prev=(await this.storage.get('state'))||{branchRuns:0,cellRuns:0,failures:0},id=this.env.OMEGA_SWARM_BRANCH.idFromName(`omega-swarm-branch-${job.domain}-${job.phase}`),stub=this.env.OMEGA_SWARM_BRANCH.get(id),started=Date.now();await this.storage.put('state',{...prev,status:'WORKING',domain:job.domain,missionId:job.missionId,heartbeatAt:started});const r=await stub.fetch(new Request('https://branch.internal/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...job,lineage:[...(job.lineage||[]),`organ:${SWARM_DOMAIN_ROLES[job.domain]||job.domain}`]})})),data=await r.json().catch(()=>null),failed=num(data?.receipt?.failed),next={status:r.ok&&failed===0?'IDLE':'DEGRADED',domain:job.domain,missionId:job.missionId,branchRuns:num(prev.branchRuns)+1,cellRuns:num(prev.cellRuns)+num(data?.receipt?.cells),failures:num(prev.failures)+failed,heartbeatAt:Date.now(),lastBranchReceipt:data?.receipt||null};await this.storage.put('state',next);return json({ok:r.ok,organ:{domain:job.domain,role:SWARM_DOMAIN_ROLES[job.domain],state:next},branch:data},r.status)}
}

export class OmegaSwarmOrganismCoordinator{
 constructor(state,env){this.storage=state.storage;this.env=env}
 async ids(){return(await this.storage.get('mission_ids'))||[]}
 async get(id){return this.storage.get(`mission:${id}`)}
 async save(m){await this.storage.put(`mission:${m.id}`,m);const ids=await this.ids();if(!ids.includes(m.id))await this.storage.put('mission_ids',[m.id,...ids].slice(0,64));return m}
 async create(body){const plan=planOrganismMissionR123(body),id=`organism_${Date.now().toString(36)}_${(await sha(`${plan.intent}|${plan.seed}|${Date.now()}`)).slice(0,12)}`,now=Date.now(),m={schema:'OMEGA_ORGANISM_MISSION_R123',runtimeRevision:ORGANISM_REVISION,id,status:'QUEUED',mode:plan.mode,intent:plan.intent,seed:plan.seed,createdAt:now,deadlineAt:now+plan.deadlineMs,totalCells:plan.selected.length,totalBranches:plan.branches.length,completedCells:0,failedCells:0,completedBranches:0,failedBranches:0,queue:plan.branches.map(b=>({...b})),activeBranches:0,branchConcurrency:plan.branchConcurrency,maxDeterministicRetries:plan.maxDeterministicRetries,evidence:plan.evidence,budgets:plan.budgets,providerContributions:[],branchReceipts:[],organ:{target:plan.organBranchCounts,completed:Array(12).fill(0),failed:Array(12).fill(0)},proofState:'QUEUED_NOT_ADMITTED',authority:'RESULT_FABRIC_NOT_CANON',canonicalMutation:false};await this.save(m);await this.storage.setAlarm(Date.now()+75);return{m,plan}}
 async runBranch(m,b){if(!this.env?.OMEGA_SWARM_ORGAN)return{ok:false,branch:b,data:{code:'ORGAN_BINDING_UNAVAILABLE'}};const id=this.env.OMEGA_SWARM_ORGAN.idFromName(`omega-swarm-organ-${b.domain}`),stub=this.env.OMEGA_SWARM_ORGAN.get(id),r=await stub.fetch(new Request('https://organ.internal/branch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:m.id,intent:m.intent,mode:m.mode,domain:b.domain,phase:b.phase,cells:b.cells,evidence:m.evidence,maxDeterministicRetries:m.maxDeterministicRetries,lineage:[`omega-v6:organism:${m.id}`,`seed:${m.seed}`]})}));return{ok:r.ok,branch:b,status:r.status,data:await r.json().catch(()=>null)}}
 async finalize(m){m.status=m.completedCells?'COMPLETE':'FAILED';m.completedAt=Date.now();m.proofState='RETURNED_NOT_ADMITTED';m.merkleRoot=await merkle(m.branchReceipts.map(x=>x.merkleRoot));m.receipt={schema:'OMEGA_ORGANISM_RECEIPT_R123',missionId:m.id,mode:m.mode,totalCells:m.totalCells,completedCells:m.completedCells,failedCells:m.failedCells,totalBranches:m.totalBranches,completedBranches:m.completedBranches,failedBranches:m.failedBranches,merkleRoot:m.merkleRoot,evidence:m.evidence.map(x=>({id:x.id,sha256:x.sha256,authority:x.authority})),budgets:m.budgets,createdAt:m.createdAt,completedAt:m.completedAt,canonicalMutation:false,authority:'RESULT_RECEIPT_NOT_CANON'};if(m.budgets?.reconvergence&&m.providerContributions.length&&this.env?.AI){try{const text=m.providerContributions.map(x=>`[${x.cellId} ${x.role}] ${x.summary}`).join('\n\n').slice(0,18000),r=await this.env.AI.run(SWARM_MODEL_R121,{messages:[{role:'system',content:'You are the bounded OMEGA organism reconvergence layer. Synthesize the supplied cell contributions. Preserve disagreement, uncertainty and missing evidence. Do not relabel model output as measurement, native execution, external research, or CanonState.'},{role:'user',content:`MISSION: ${m.intent}\n\nCELL CONTRIBUTIONS:\n${text}`}],max_tokens:900,temperature:.2,chat_template_kwargs:{enable_thinking:false}}),out=modelText(r);if(out)m.finalSynthesis={provider:SWARM_MODEL_R121,text:out.slice(0,7000),authority:'MODEL_SYNTHESIS_NOT_CANON'}}catch(error){m.finalSynthesis={provider:'FAILED',text:clip(error instanceof Error?error.message:String(error),1000),authority:'NO_RESULT_FABRICATED'}}}return this.save(m)}
 async process(id){let m=await this.get(id);if(!m||!['QUEUED','RUNNING'].includes(m.status))return m;if(Date.now()>m.deadlineAt){m.status='TIMED_OUT';m.completedAt=Date.now();m.proofState='TIMED_OUT_NOT_ADMITTED';return this.save(m)}if(!m.queue.length)return this.finalize(m);m.status='RUNNING';m.startedAt=m.startedAt||Date.now();const n=m.mode==='PIPELINE'?1:Math.min(m.branchConcurrency,m.queue.length),batch=m.queue.splice(0,n);m.activeBranches=batch.length;await this.save(m);const outs=await Promise.all(batch.map(b=>this.runBranch(m,b).catch(error=>({ok:false,branch:b,status:500,data:{error:error instanceof Error?error.message:String(error)}}))));for(const x of outs){const receipt=x.data?.branch?.receipt||x.data?.receipt,cells=num(receipt?.cells,x.branch.cells.length),completed=num(receipt?.completed,0),failed=num(receipt?.failed,cells-completed);m.completedCells+=completed;m.failedCells+=failed;m.completedBranches+=x.ok?1:0;m.failedBranches+=x.ok?0:1;m.organ.completed[x.branch.domain]+=x.ok?1:0;m.organ.failed[x.branch.domain]+=x.ok?0:1;if(receipt)m.branchReceipts.push({...receipt,organ:SWARM_DOMAIN_ROLES[x.branch.domain]});const c=x.data?.branch?.contributions||x.data?.contributions;if(Array.isArray(c))m.providerContributions.push(...c);m.providerContributions=m.providerContributions.slice(0,24)}m.activeBranches=0;if(m.queue.length){await this.save(m);await this.storage.setAlarm(Date.now()+250);return m}return this.finalize(m)}
 async alarm(){for(const id of(await this.ids()).slice(0,12)){const m=await this.get(id);if(m&&['QUEUED','RUNNING'].includes(m.status)){await this.process(id);break}}}
 async fetch(request){const u=new URL(request.url),parts=u.pathname.split('/').filter(Boolean);if(request.method==='GET'&&u.pathname==='/status'){const missions=[];for(const id of(await this.ids()).slice(0,16))missions.push(publicMission(await this.get(id)));return json({ok:true,schema:'OMEGA_ORGANISM_STATUS_R123',runtimeRevision:ORGANISM_REVISION,hierarchy:{seed:1,organs:12,branches:144,cells:SWARM_CELL_COUNT,lanes:SWARM_LANE_COUNT},active:missions.filter(x=>x&&['QUEUED','RUNNING'].includes(x.status)).length,missions:missions.filter(Boolean),canonicalMutation:false})}if(request.method==='POST'&&u.pathname==='/missions'){try{const body=await request.json().catch(()=>({})),{m,plan}=await this.create(body);return json({ok:true,mission:publicMission(m),plan:{...compactPlanR121(plan),schema:plan.schema,runtimeRevision:ORGANISM_REVISION,branchCount:plan.branchCount,organBranchCounts:plan.organBranchCounts,budgets:plan.budgets,evidence:plan.evidence,deadlineMs:plan.deadlineMs,branchConcurrency:plan.branchConcurrency}},202)}catch(error){return json({ok:false,code:error instanceof Error?error.message:'ORGANISM_MISSION_INVALID'},400)}}if(parts[0]==='missions'&&parts[1]){const id=parts[1],m=await this.get(id);if(!m)return json({ok:false,code:'MISSION_NOT_FOUND'},404);if(request.method==='GET'&&parts.length===2)return json({ok:true,mission:publicMission(m)});if(request.method==='POST'&&parts[2]==='tick')return json({ok:true,mission:publicMission(await this.process(id))});if(request.method==='POST'&&parts[2]==='pause'){if(['QUEUED','RUNNING'].includes(m.status)){m.status='PAUSED';m.pausedAt=Date.now();await this.save(m)}return json({ok:true,mission:publicMission(m)})}if(request.method==='POST'&&parts[2]==='resume'){if(m.status==='PAUSED'){m.status='RUNNING';m.resumedAt=Date.now();await this.save(m);await this.storage.setAlarm(Date.now()+75)}return json({ok:true,mission:publicMission(m)})}if(request.method==='POST'&&parts[2]==='cancel'){if(!['COMPLETE','FAILED','CANCELLED'].includes(m.status)){m.status='CANCELLED';m.cancelledAt=Date.now();m.proofState='CANCELLED_NOT_ADMITTED';m.queue=[];await this.save(m)}return json({ok:true,mission:publicMission(m)})}if(request.method==='POST'&&parts[2]==='replay'){const body=await request.json().catch(()=>({})),created=await this.create({intent:m.intent,mode:m.mode,requestedCells:m.totalCells,providerBudget:m.budgets?.providerTotal,genesisBudget:m.budgets?.genesis,opticalBudget:m.budgets?.optical,evidence:m.evidence,branchConcurrency:m.branchConcurrency,maxDeterministicRetries:m.maxDeterministicRetries,...body});return json({ok:true,replayOf:m.id,mission:publicMission(created.m),plan:{schema:created.plan.schema,branchCount:created.plan.branchCount,budgets:created.plan.budgets}},202)}}return json({ok:false,code:'NOT_FOUND'},404)}
}
