import {capabilityProfile,decodeCell,parseCellId} from './swarmCoreR121.js';

export const SWARM_MODEL_R121='@cf/google/gemma-4-26b-a4b-it';
const clip=(v,n=9000)=>String(v??'').trim().slice(0,n);
const json=(v,s=200)=>new Response(JSON.stringify(v,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-swarm-runtime':'R121'}});
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function modelText(r){if(typeof r==='string')return r;if(typeof r?.response==='string')return r.response;if(typeof r?.result?.response==='string')return r.result.response;const c=r?.choices?.[0]?.message?.content;return typeof c==='string'?c:''}
function initial(a){const profile=capabilityProfile(a);return{schema:'OMEGA_SWARM_CELL_STATE_R121',id:profile.cellId,index:a.index,address:{domain:a.domain,phase:a.phase,regulation:a.regulation},profile,status:'IDLE',missionId:null,heartbeatAt:null,completedTasks:0,failedTasks:0,scar:0,lastReceipt:null,lastResultPreview:null,canonicalMutation:false}}
function deterministic(task,a,p){const intent=clip(task.intent||task.text),words=intent.split(/\s+/).filter(Boolean);return{kind:'DETERMINISTIC_CELL_ANALYSIS',summary:`${p.cellId} processed the mission through ${p.domainRole}/${p.phaseRole}/${p.regulationRole}.`,metrics:{intentLength:intent.length,wordCount:words.length,localSeed:(a.index*131+intent.length*17)%100000},partition:{domain:p.domainRole,phase:p.phaseRole,regulation:p.regulationRole},carry:{invariant:'operator intent + address + lineage',scar:'local failures remain scar until recovery'},truthBoundary:'Deterministic swarm decomposition is instrumentation, not measurement or canonical truth.'}}
async function ai(env,task,p){if(!env?.AI)return{kind:'PROVIDER_GATED',summary:'Workers AI binding unavailable; no model result fabricated.'};const system=`You are bounded OMEGA swarm cell ${p.cellId}. Role ${p.domainRole}; phase ${p.phaseRole}; regulation ${p.regulationRole}. Analyze only the supplied operator intent. Return one useful specialist contribution, not a canonical conclusion. Distinguish interpretation from observed evidence. 12/144/1728/20736 are address-resolution levels, not physical dimensions. Never claim PC execution, web research, measurement, RCWA/FDTD, or CanonState mutation unless supplied as evidence.`;const r=await env.AI.run(SWARM_MODEL_R121,{messages:[{role:'system',content:system},{role:'user',content:clip(task.intent||task.text,7000)}],max_tokens:420,temperature:.28,chat_template_kwargs:{enable_thinking:false}});const text=modelText(r);if(!text)throw new Error('EMPTY_WORKERS_AI_RESULT');return{kind:'WORKERS_AI_CELL_SYNTHESIS',provider:SWARM_MODEL_R121,summary:text.slice(0,3200),truthBoundary:'Model synthesis is a candidate packet, not CanonState.'}}
async function genesis(env,task){if(!env?.OMEGA_GENESIS_MACHINE)return{kind:'SERVICE_GATED',summary:'Genesis machine binding unavailable.'};const r=await env.OMEGA_GENESIS_MACHINE.fetch(new Request('https://genesis.internal/api/federation/propose',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:clip(task.intent||task.text,4000),ceremony_id:task.missionId||task.taskId||'swarm-r121'})}));return{kind:'GENESIS_MACHINE',ok:r.ok,status:r.status,data:await r.json().catch(()=>null),truthBoundary:'Genesis is proposal-only and cannot mutate CanonState.'}}
async function optical(env,task){if(!env?.OMEGA_OPTICAL_MACHINE)return{kind:'SERVICE_GATED',summary:'Optical machine binding unavailable.'};const proposed=await genesis(env,task),proposal=proposed?.data?.packet;if(!proposal)return{kind:'OPTICAL_CHAIN_FAILED',stage:'PROPOSE',proposal:proposed};const r=await env.OMEGA_OPTICAL_MACHINE.fetch(new Request('https://optical.internal/api/federation/screen',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({proposal})}));return{kind:'OPTICAL_MACHINE_CHAIN',ok:r.ok,status:r.status,proposal,screen:await r.json().catch(()=>null),truthBoundary:'Proposal plus reduced-order scalar screening only; not RCWA/FDTD/FEM, measurement, fabrication validation, or canonical admission.'}}
export async function runCellTaskR121(env,task,a,p){switch(task.executor){case'WORKERS_AI':return ai(env,task,p);case'GENESIS':return genesis(env,task);case'OPTICAL_CHAIN':return optical(env,task);default:return deterministic(task,a,p)}}

export class OmegaSwarmCell{
 constructor(state,env){this.storage=state.storage;this.env=env}
 async fetch(request){const u=new URL(request.url);if(request.method==='GET'&&u.pathname==='/state')return json({ok:true,cell:(await this.storage.get('cell'))||{schema:'OMEGA_SWARM_CELL_STATE_R121',status:'UNINITIALIZED',canonicalMutation:false}});if(request.method!=='POST'||u.pathname!=='/task')return json({ok:false,code:'NOT_FOUND'},404);const task=await request.json().catch(()=>({})),parsed=parseCellId(task.cellId),a=parsed||decodeCell(Number(task.index)||0),p=capabilityProfile(a),base=(await this.storage.get('cell'))||initial(a),started=Date.now(),taskId=clip(task.taskId||`${task.missionId||'mission'}:${p.cellId}:${started}`,220);await this.storage.put('cell',{...base,...initial(a),status:'WORKING',missionId:clip(task.missionId,180)||null,taskId,heartbeatAt:started,lastStartedAt:started,completedTasks:Number(base.completedTasks||0),failedTasks:Number(base.failedTasks||0),scar:Number(base.scar||0)});try{const result=await runCellTaskR121(this.env,task,a,p),completed=Date.now(),receipt={schema:'OMEGA_SWARM_CELL_RECEIPT_R121',taskId,missionId:clip(task.missionId,180)||null,cellId:p.cellId,index:a.index,lane:Number.isFinite(Number(task.lane))?Number(task.lane):null,executor:task.executor||'DETERMINISTIC',startedAt:started,completedAt:completed,runtimeMs:completed-started,resultSha256:await hash(result),lineage:[...(Array.isArray(task.lineage)?task.lineage.slice(-12):[]),`swarm:${p.cellId}:complete`],canonicalMutation:false},next={...base,...initial(a),status:'IDLE',heartbeatAt:completed,lastCompletedAt:completed,completedTasks:Number(base.completedTasks||0)+1,failedTasks:Number(base.failedTasks||0),scar:Math.max(0,Number(base.scar||0)*.96),lastReceipt:receipt,lastResultPreview:{kind:result.kind,summary:clip(result.summary||result.truthBoundary,1000),provider:result.provider||null}};await this.storage.put('cell',next);return json({ok:true,cell:next,receipt,result})}catch(error){const message=error instanceof Error?error.message:String(error),next={...base,...initial(a),status:'FAILED',heartbeatAt:Date.now(),completedTasks:Number(base.completedTasks||0),failedTasks:Number(base.failedTasks||0)+1,scar:Math.min(1,Number(base.scar||0)+.08),lastResultPreview:{kind:'ERROR',summary:message.slice(0,1000)}};await this.storage.put('cell',next);return json({ok:false,code:'CELL_EXECUTION_FAILED',cell:next,error:message},500)}}
}
