export const R234_REVISION='R234';
export const R234_SCHEMA='OMEGA_SOURCE_SPATIAL_CALIBRATION_SUFFICIENCY_R234';
export const R234_SNAPSHOT_KEY='omega.r234.sourceSpatialCalibrationSufficiency';
export const R234_EVENT='omega-r234-source-spatial-calibration-sufficiency';
export const R234_BOUNDARY='R234 evaluates geometric distribution and uncertainty-normalized residual sufficiency only after an exact passing R232 independent correspondence receipt. It does not authenticate the external control source, solve or alter calibration, prove global physical registration, validate a scientific solver, invoke native/remote execution, prove PC online state, close federation, mutate CanonState, or prove computed photoreal reality.';
const stable=v=>Array.isArray(v)?v.map(stable):(v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v);
const sha256=async v=>{const b=new TextEncoder().encode(JSON.stringify(stable(v))),h=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const hash64=v=>/^[a-f0-9]{64}$/.test(String(v||'')),finite=v=>Number.isFinite(Number(v)),round=(v,p=6)=>Number(Number(v).toFixed(p));
function hull(points){const p=[...points].sort((a,b)=>a.x-b.x||a.y-b.y);if(p.length<3)return p;const cross=(o,a,b)=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lo=[],hi=[];for(const q of p){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),q)<=0)lo.pop();lo.push(q)}for(let i=p.length-1;i>=0;i--){const q=p[i];while(hi.length>=2&&cross(hi.at(-2),hi.at(-1),q)<=0)hi.pop();hi.push(q)}return lo.slice(0,-1).concat(hi.slice(0,-1))}
function polygonArea(p){let a=0;for(let i=0;i<p.length;i++){const q=p[i],r=p[(i+1)%p.length];a+=q.x*r.y-r.x*q.y}return Math.abs(a)/2}
function worldDistribution(points){const c=points.reduce((s,p)=>({x:s.x+p.x,y:s.y+p.y,z:s.z+p.z}),{x:0,y:0,z:0}),n=points.length;c.x/=n;c.y/=n;c.z/=n;const v=points.map(p=>({x:p.x-c.x,y:p.y-c.y,z:p.z-c.z}));let maxR2=0,maxCross2=0;for(const a of v)maxR2=Math.max(maxR2,a.x*a.x+a.y*a.y+a.z*a.z);for(let i=0;i<v.length;i++)for(let j=i+1;j<v.length;j++){const a=v[i],b=v[j],x=a.y*b.z-a.z*b.y,y=a.z*b.x-a.x*b.z,z=a.x*b.y-a.y*b.x;maxCross2=Math.max(maxCross2,x*x+y*y+z*z)}return{radius:Math.sqrt(maxR2),nonCollinearityScore:maxR2>0?maxCross2/(maxR2*maxR2):0}}
export async function evaluateSourceSpatialCalibrationSufficiencyR234({validation,camera,validationEvidence,minCorrespondences=6,minImageHullAreaRatio=.005,minImageSpanRatio=.05,minWorldNonCollinearity=.01,maxNormalizedRms=3}={}){
 const missing=[];
 if(validation?.state!=='INDEPENDENT_SPATIAL_CALIBRATION_VALIDATION_PASSED'||validation?.independentCorrespondenceValidationPassed!==true||!hash64(validation?.receiptSha256))missing.push('R232_PASS_RECEIPT');
 const cameraSha256=await sha256(camera||null);if(cameraSha256!==String(validation?.cameraEvidenceSha256||''))missing.push('R232_CAMERA_HASH');
 const validationEvidenceSha256=await sha256(validationEvidence||null);if(validationEvidenceSha256!==String(validation?.validationEvidenceSha256||''))missing.push('R232_VALIDATION_EVIDENCE_HASH');
 const corr=Array.isArray(validationEvidence?.correspondences)?validationEvidence.correspondences:[],rows=Array.isArray(validation?.residuals)?validation.residuals:[];
 const minN=Math.max(6,Math.min(32,Math.floor(+minCorrespondences||6)));if(corr.length<minN||rows.length!==corr.length)missing.push('CONTROL_COUNT');
 const width=+camera?.imageWidthPx,height=+camera?.imageHeightPx;if(!Number.isInteger(width)||width<=0||!Number.isInteger(height)||height<=0)missing.push('CAMERA_IMAGE_BOUNDS');
 if(missing.length)return{schema:R234_SCHEMA,revision:R234_REVISION,state:'HELD_FOR_CALIBRATION_SUFFICIENCY_EVIDENCE',missing:[...new Set(missing)],r232ReceiptSha256:String(validation?.receiptSha256||''),calibrationSufficiencyEnvelopePassed:false,sourceAuthenticationProved:false,spatialCalibrationProved:false,globalPhysicalRegistrationProved:false,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false,truthBoundary:R234_BOUNDARY};
 const imagePoints=corr.map(c=>({x:+c.u,y:+c.v})),h=hull(imagePoints),hullAreaRatio=polygonArea(h)/(width*height),us=imagePoints.map(p=>p.x),vs=imagePoints.map(p=>p.y),uSpanRatio=(Math.max(...us)-Math.min(...us))/width,vSpanRatio=(Math.max(...vs)-Math.min(...vs))/height;
 const worldPoints=corr.map(c=>({x:+c.world.x,y:+c.world.y,z:+c.world.z}));if(worldPoints.some(p=>!finite(p.x)||!finite(p.y)||!finite(p.z)))throw new Error('R234_INVALID_WORLD_CONTROL');const wd=worldDistribution(worldPoints);
 const defaultSigma=Math.max(.1,+validationEvidence?.uncertainty?.pixel||1),normalized=rows.map((r,i)=>{const sigma=Math.max(.1,+corr[i]?.uncertaintyPx||defaultSigma);return +r.residualPx/sigma}),normalizedRms=Math.sqrt(normalized.reduce((s,x)=>s+x*x,0)/normalized.length);
 const thresholds={minCorrespondences:minN,minImageHullAreaRatio:+minImageHullAreaRatio,minImageSpanRatio:+minImageSpanRatio,minWorldNonCollinearity:+minWorldNonCollinearity,maxNormalizedRms:+maxNormalizedRms};
 const distributionPassed=hullAreaRatio>=thresholds.minImageHullAreaRatio&&uSpanRatio>=thresholds.minImageSpanRatio&&vSpanRatio>=thresholds.minImageSpanRatio&&wd.nonCollinearityScore>=thresholds.minWorldNonCollinearity;
 const uncertaintyResidualPassed=normalizedRms<=thresholds.maxNormalizedRms,passed=distributionPassed&&uncertaintyResidualPassed;
 const core={r232ReceiptSha256:validation.receiptSha256,r230FrameSha256:validation.r230FrameSha256,r228GeometrySha256:validation.r228GeometrySha256,cameraEvidenceSha256:cameraSha256,validationEvidenceSha256,correspondenceCount:corr.length,imageHullAreaRatio:round(hullAreaRatio),uSpanRatio:round(uSpanRatio),vSpanRatio:round(vSpanRatio),worldRadius:round(wd.radius),worldNonCollinearityScore:round(wd.nonCollinearityScore),normalizedRms:round(normalizedRms),distributionPassed,uncertaintyResidualPassed,calibrationSufficiencyEnvelopePassed:passed,thresholds};
 const receiptSha256=await sha256(core);return{schema:R234_SCHEMA,revision:R234_REVISION,state:passed?'CALIBRATION_SUFFICIENCY_ENVELOPE_PASSED':'CALIBRATION_SUFFICIENCY_ENVELOPE_FAILED',...core,receiptSha256,sourceAuthenticationProved:false,spatialCalibrationProved:false,globalPhysicalRegistrationProved:false,calibrationSolvedOrAltered:false,renderedComputedRealityFrame:true,computedRepresentationOnly:true,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false,computedRealityAuthority:'R122_EXISTING_AUTHORITY_UNCHANGED',adaptivePerformanceAuthority:'R185_EXISTING_AUTHORITY_UNCHANGED',canonicalAdmissionAuthority:'R125',operationLedger:'R86',projectContinuity:'R87',authenticatedContinuity:'R97_WHEN_PAIRED',truthBoundary:R234_BOUNDARY};
}
export function persistSourceSpatialCalibrationSufficiencyR234(r){if(!['CALIBRATION_SUFFICIENCY_ENVELOPE_PASSED','CALIBRATION_SUFFICIENCY_ENVELOPE_FAILED'].includes(r?.state)||!hash64(r?.receiptSha256))return false;try{localStorage.setItem(R234_SNAPSHOT_KEY,JSON.stringify(r));window.dispatchEvent(new CustomEvent(R234_EVENT,{detail:r}));return true}catch{return false}}
export function readSourceSpatialCalibrationSufficiencyR234(){try{const v=JSON.parse(localStorage.getItem(R234_SNAPSHOT_KEY)||'null');return v?.schema===R234_SCHEMA?v:null}catch{return null}}
export function manifestR234(){return{schema:'OMEGA_SOURCE_SPATIAL_CALIBRATION_SUFFICIENCY_MANIFEST_R234',revision:R234_REVISION,chain:['exact passing R232 receipt','exact R232 camera/evidence hashes','minimum independent control count','image convex-hull coverage','horizontal and vertical image span','world non-collinearity','uncertainty-normalized residual RMS','bounded sufficiency receipt'],authority:{computedReality:'R122 unchanged',adaptivePerformance:'R185 unchanged',canonicalAdmission:'R125',continuity:'R86/R87/R97 when authenticated'},truthBoundary:R234_BOUNDARY}}
