import {createRunR146,readRunR146,replayRunR146,transitionRunR146} from './durableOperationExecutionR146.js';
import {dispatchRunR147,pollRunR147,readResultR147} from './unifiedExecutorFabricR147.js';

export const R148_REVISION='R148';
export const R148_SCHEMA='OMEGA_DURABLE_OPERATION_GRAPH_R148';
export const R148_GRAPH_STATES=Object.freeze(['DRAFT','AUTHORIZED','RUNNING','WAITING','VERIFIED_EXECUTION_GRAPH','HOLD','FAILED','CANCELLED']);
export const R148_NODE_STATES=Object.freeze(['PENDING','WAITING_DEPENDENCY','READY','WAITING_CONFIRMATION','DISPATCHED','RUNNING','VERIFIED','HOLD','FAILED']);
export const R148_LAWS=Object.freeze([
 'ONE_GRAPH_IS_A_DAG_OF_R143_OPERATION_CONTRACTS',
 'GRAPH_CREATION_IS_NOT_EXECUTION_AUTHORIZATION',
 'DEPENDENCIES_REQUIRE_VERIFIED_EXECUTION_NOT_MERE_RETURN',
 'R146_REMAINS_ATOMIC_DURABLE_RUN_AUTHORITY',
 'R147_REMAINS_CONCRETE_EXECUTOR_DISPATCH_AUTHORITY',
 'HYBRID_AND_BUILD_NODES_REQUIRE_EXPLICIT_EXECUTION_CONFIRMATION',
 'ASYNC_EXECUTORS_ARE_POLLED_WITHOUT_FABRICATING_COMPLETION',
 'GRAPH_VERIFIED_MEANS_ALL_NODE_EXECUTION_RECEIPTS_VERIFIED_NOT_FACTUAL_TRUTH',
 'FAILURE_HOLDS_DEPENDENT_NODES_BY_DEFAULT',
 'GRAPH_CANCEL_STOPS_NEW_SCHEDULING_NOT_ALREADY_DISPATCHED_EXTERNAL_WORK',
 'GRAPH_EVENTS_ARE_HASH_CHAINED_AND_REPLAYABLE',
 'R144_ATTESTATION_R145_SCAR_AND_GRAPH_RECEIPTS_ARE_EVIDENCE_ONLY',
 'R125_REMAINS_THE_ONLY_CANONSTATE_ADMISSION_AUTHORITY'
]);

const GRAPH_PREFIX='execution:r148:graph:';
const INDEX='execution:r148:index';
const txt=(v,n=4000)=>String(v??'').trim().slice(0,n);
const sid=v=>{const s=txt(v,180);return /^[A-Za-z0-9._:-]+$/.test(s)?s:''};
const stable=v=>{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v};
const sha=async v=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(v))));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const key=id=>GRAPH_PREFIX+id;
const terminalRunState=s=>['VERIFIED','UNAVAILABLE','FAILED','REJECTED','STALE'].includes(String(s||''));
const failedRunState=s=>['UNAVAILABLE','FAILED','REJECTED','STALE'].includes(String(s||''));
const nativeDomain=node=>['HYBRID','BUILD'].includes(String(node?.contract?.executionDomain||'').toUpperCase());
function validContract(c={}){return c.schema==='OMEGA_AUTHORITATIVE_UI_OPERATION_CHAIN_R143'&&c.revision==='R143'&&Boolean(sid(c.routeId)&&txt(c.route,160)&&sid(c.capabilityId)&&txt(c.executionDomain,32))&&c.receiptAuthority==='R142'&&c.admissionAuthority==='R125'}
function normalizeNode(raw,index){const id=sid(raw?.id)||`node-${index+1}`,dependsOn=[...new Set((Array.isArray(raw?.dependsOn)?raw.dependsOn:[]).map(sid).filter(Boolean))];return{id,label:txt(raw?.label||raw?.contract?.route||id,180),intent:txt(raw?.intent||raw?.contract?.route||id,4000),contract:stable(raw?.contract||{}),dependsOn,strategy:txt(raw?.strategy||'AUTO',32).toUpperCase(),executionInput:raw?.executionInput&&typeof raw.executionInput==='object'?stable(raw.executionInput):{},state:dependsOn.length?'WAITING_DEPENDENCY':'PENDING',runId:null,executorId:null,resultFingerprint:null,lastError:null,createdAt:Date.now(),updatedAt:Date.now(),canonicalMutation:false}}
function validateGraphNodes(nodes){const errors=[];if(!nodes.length||nodes.length>64)errors.push('graph requires 1-64 nodes');const ids=nodes.map(x=>x.id),set=new Set(ids);if(set.size!==ids.length)errors.push('node ids must be unique');for(const n of nodes){if(!validContract(n.contract))errors.push(`${n.id}: valid R143 route contract required`);for(const d of n.dependsOn){if(!set.has(d))errors.push(`${n.id}: unknown dependency ${d}`);if(d===n.id)errors.push(`${n.id}: self dependency rejected`)}}const marks=new Map();function visit(id){const mark=marks.get(id)||0;if(mark===1)return false;if(mark===2)return true;marks.set(id,1);const n=nodes.find(x=>x.id===id);for(const d of n?.dependsOn||[])if(!visit(d))return false;marks.set(id,2);return true}for(const id of ids)if(!visit(id)){errors.push('operation graph must be acyclic');break}return{ok:errors.length===0,errors}}
async function appendGraphEvent(graph,type,detail,data={}){const base={schema:'OMEGA_OPERATION_GRAPH_EVENT_R148',graphId:graph.id,ordinal:graph.events.length,type,detail:txt(detail,600),at:Date.now(),data:stable(data),previousHash:graph.headSha256||null,canonicalMutation:false,canonicalAdmissionAuthority:'R125'},hash=await sha(base);const ev={...base,hash};graph.events=[...graph.events,ev];graph.headSha256=hash;graph.updatedAt=ev.at;return ev}
async function persist(runtime,graph){await runtime.state.storage.put(key(graph.id),graph);const ids=await runtime.state.storage.get(INDEX)||[];await runtime.state.storage.put(INDEX,[graph.id,...ids.filter(x=>x!==graph.id)].slice(0,128));return graph}
function nodeById(graph,id){return graph.nodes.find(x=>x.id===id)}
function dependencyState(graph,node){const deps=node.dependsOn.map(id=>nodeById(graph,id)).filter(Boolean);if(!deps.length)return'READY';if(deps.some(x=>x.state==='FAILED'||x.state==='HOLD'))return'HOLD';if(deps.every(x=>x.state==='VERIFIED'))return'READY';return'WAITING_DEPENDENCY'}
function activeNodeCount(graph){return graph.nodes.filter(x=>['DISPATCHED','RUNNING'].includes(x.state)).length}
function graphState(graph){if(graph.state==='CANCELLED')return'CANCELLED';if(graph.nodes.every(x=>x.state==='VERIFIED'))return'VERIFIED_EXECUTION_GRAPH';if(graph.config.failFast&&graph.nodes.some(x=>x.state==='FAILED'))return'FAILED';if(graph.nodes.some(x=>x.state==='HOLD'||x.state==='WAITING_CONFIRMATION'))return'WAITING';if(graph.nodes.some(x=>['DISPATCHED','RUNNING'].includes(x.state)))return'RUNNING';if(graph.state==='AUTHORIZED'||graph.nodes.some(x=>['READY','PENDING','WAITING_DEPENDENCY'].includes(x.state)))return'RUNNING';return graph.state}
async function syncNodeFromRun(runtime,graph,node){if(!node.runId)return node;let polled=null;try{polled=await pollRunR147(runtime,node.runId)}catch{}const run=polled?.run||await readRunR146(runtime,node.runId);if(!run){node.state='HOLD';node.lastError='R148_LINKED_RUN_MISSING';node.updatedAt=Date.now();return node}node.executorId=polled?.binding?.executorId||node.executorId||null;node.updatedAt=Date.now();if(run.state==='VERIFIED'){node.state='VERIFIED';const view=await readResultR147(runtime,node.runId);node.resultFingerprint=view?.result?.resultFingerprint||run.headSha256||null;node.lastError=null}else if(failedRunState(run.state)){node.state='FAILED';node.lastError=`R146_${run.state}`}else if(run.state==='AVAILABLE')node.state='DISPATCHED';else if(['INVOKED','RETURNED'].includes(run.state))node.state='RUNNING';else if(run.state==='AUTHORIZED')node.state='READY';return node}
async function createAtomicRun(runtime,graph,node){const created=await createRunR146(runtime,{intent:node.intent,contract:node.contract,metadata:{graphId:graph.id,graphNodeId:node.id,graphRevision:R148_REVISION}});if(!created.ok)return created;const authorized=await transitionRunR146(runtime,created.run.id,{state:'AUTHORIZED',reason:`R148 graph ${graph.id} authorized node ${node.id}`,evidence:{proofRef:'R148_GRAPH_NODE_AUTHORIZATION'}});if(!authorized.ok)return authorized;node.runId=authorized.run.id;node.updatedAt=Date.now();await appendGraphEvent(graph,'NODE_RUN_CREATED',`Created R146 durable run for graph node ${node.id}`,{nodeId:node.id,runId:node.runId});return{ok:true,run:authorized.run}}
async function dispatchNode(runtime,graph,node,callbacks){if(!node.runId){const created=await createAtomicRun(runtime,graph,node);if(!created.ok){node.state='FAILED';node.lastError=created.code||'R148_RUN_CREATE_FAILED';return created}}const input={...stable(node.executionInput||{}),strategy:node.strategy};const out=await dispatchRunR147(runtime,node.runId,input,callbacks);if(!out?.ok){const code=out?.code||'R148_DISPATCH_FAILED';node.lastError=code;node.updatedAt=Date.now();if(code==='R147_EXPLICIT_EXECUTION_CONFIRMATION_REQUIRED'){node.state='WAITING_CONFIRMATION'}else if(code==='R147_EXECUTOR_UNAVAILABLE'||code==='R147_PLUGIN_CONCRETE_ADAPTER_REQUIRED'||code==='R147_HYBRID_DEVICE_PROOF_REQUIRED'){node.state='HOLD'}else{const run=await readRunR146(runtime,node.runId);node.state=failedRunState(run?.state)?'FAILED':'HOLD'}await appendGraphEvent(graph,'NODE_DISPATCH_HELD',`Node ${node.id} did not dispatch`,{nodeId:node.id,runId:node.runId,code});return out}const run=out.run||await readRunR146(runtime,node.runId);node.executorId=out?.binding?.executorId||out?.result?.executorId||node.executorId||null;node.lastError=null;node.updatedAt=Date.now();if(run?.state==='VERIFIED'){node.state='VERIFIED';node.resultFingerprint=out?.result?.resultFingerprint||run.headSha256||null}else if(run?.state==='AVAILABLE')node.state='DISPATCHED';else if(['INVOKED','RETURNED'].includes(run?.state))node.state='RUNNING';else node.state='RUNNING';await appendGraphEvent(graph,'NODE_DISPATCHED',`Node ${node.id} dispatched through R147`,{nodeId:node.id,runId:node.runId,executorId:node.executorId,state:run?.state||null});return out}

export function manifestR148(){return{ok:true,schema:'OMEGA_DURABLE_OPERATION_GRAPH_MANIFEST_R148',revision:R148_REVISION,graphSchema:R148_SCHEMA,graphStates:R148_GRAPH_STATES,nodeStates:R148_NODE_STATES,laws:R148_LAWS,limits:{maxNodes:64,maxConcurrency:12},upstream:{routeContracts:'R143',atomicRuns:'R146',executors:'R147',hybridProof:'R141',swarm:'R125',attestation:'R144',worldScar:'R145'},canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R148 composes verified execution dependencies across R146/R147. Graph VERIFIED means every node has a verified execution receipt under its executor-specific boundary; it does not establish factual truth, physical validity, deployment truth, swarm consensus, or CanonState admission.'}}
export async function createGraphR148(runtime,input={}){const raw=Array.isArray(input.nodes)?input.nodes:[],nodes=raw.map(normalizeNode),validation=validateGraphNodes(nodes);if(!validation.ok)return{ok:false,status:400,code:'R148_GRAPH_INVALID',errors:validation.errors};const id='graph_'+crypto.randomUUID().replaceAll('-',''),t=Date.now(),graph={schema:R148_SCHEMA,revision:R148_REVISION,id,title:txt(input.title||'OMEGA execution graph',220),intent:txt(input.intent||input.title||'OMEGA execution graph',4000),state:'DRAFT',nodes,config:{maxConcurrency:Math.max(1,Math.min(12,Math.trunc(Number(input.maxConcurrency)||4))),failFast:input.failFast!==false},createdAt:t,updatedAt:t,authorizedAt:null,completedAt:null,events:[],headSha256:null,canonicalMutation:false,canonicalAdmissionAuthority:'R125'};await appendGraphEvent(graph,'GRAPH_CREATED','Durable operation DAG created without execution authorization',{nodeCount:nodes.length,maxConcurrency:graph.config.maxConcurrency});await persist(runtime,graph);return{ok:true,status:201,graph}}
export async function readGraphR148(runtime,id){id=sid(id);return id?await runtime.state.storage.get(key(id))||null:null}
export async function listGraphsR148(runtime){const ids=await runtime.state.storage.get(INDEX)||[],graphs=[];for(const id of ids.slice(0,64)){const g=await runtime.state.storage.get(key(id));if(g)graphs.push(g)}return graphs}
export async function authorizeGraphR148(runtime,id,input={}){const graph=await readGraphR148(runtime,id);if(!graph)return{ok:false,status:404,code:'R148_GRAPH_NOT_FOUND'};if(graph.state!=='DRAFT')return{ok:false,status:409,code:'R148_GRAPH_NOT_DRAFT',graph};graph.state='AUTHORIZED';graph.authorizedAt=Date.now();graph.authorization={proofRef:txt(input.proofRef||'R148_AUTHENTICATED_GRAPH_AUTHORIZATION',256),safeAutoDispatch:input.safeAutoDispatch!==false,canonicalMutation:false};await appendGraphEvent(graph,'GRAPH_AUTHORIZED','Operator authorized graph scheduling; native HYBRID/BUILD nodes still require explicit per-node confirmation',{safeAutoDispatch:graph.authorization.safeAutoDispatch});await persist(runtime,graph);return{ok:true,status:200,graph}}
export async function confirmGraphNodeR148(runtime,id,nodeId,input={}){const graph=await readGraphR148(runtime,id);if(!graph)return{ok:false,status:404,code:'R148_GRAPH_NOT_FOUND'};const node=nodeById(graph,sid(nodeId));if(!node)return{ok:false,status:404,code:'R148_NODE_NOT_FOUND'};if(!nativeDomain(node))return{ok:false,status:409,code:'R148_NODE_CONFIRMATION_NOT_REQUIRED',graph,node};node.executionInput={...node.executionInput,...stable(input.executionInput||{}),confirmed:true};if(node.state==='WAITING_CONFIRMATION'||node.state==='HOLD')node.state=dependencyState(graph,node)==='READY'?'READY':dependencyState(graph,node);node.lastError=null;node.updatedAt=Date.now();await appendGraphEvent(graph,'NODE_EXECUTION_CONFIRMED',`Explicit native execution confirmation recorded for ${node.id}`,{nodeId:node.id,route:node.contract.route,executionDomain:node.contract.executionDomain});await persist(runtime,graph);return{ok:true,status:200,graph,node}}
export async function resumeGraphNodeR148(runtime,id,nodeId,input={}){const graph=await readGraphR148(runtime,id);if(!graph)return{ok:false,status:404,code:'R148_GRAPH_NOT_FOUND'};const node=nodeById(graph,sid(nodeId));if(!node)return{ok:false,status:404,code:'R148_NODE_NOT_FOUND'};if(!['HOLD','WAITING_CONFIRMATION'].includes(node.state))return{ok:false,status:409,code:'R148_NODE_NOT_HELD',graph,node};node.executionInput={...node.executionInput,...stable(input.executionInput||{})};if(input.confirmed===true)node.executionInput.confirmed=true;node.lastError=null;node.state=dependencyState(graph,node)==='READY'?(nativeDomain(node)&&node.executionInput.confirmed!==true?'WAITING_CONFIRMATION':'READY'):dependencyState(graph,node);await appendGraphEvent(graph,'NODE_RESUMED',`Held graph node ${node.id} was explicitly resumed`,{nodeId:node.id,state:node.state});await persist(runtime,graph);return{ok:true,status:200,graph,node}}
export async function cancelGraphR148(runtime,id){const graph=await readGraphR148(runtime,id);if(!graph)return{ok:false,status:404,code:'R148_GRAPH_NOT_FOUND'};if(['VERIFIED_EXECUTION_GRAPH','FAILED','CANCELLED'].includes(graph.state))return{ok:false,status:409,code:'R148_GRAPH_TERMINAL',graph};graph.state='CANCELLED';await appendGraphEvent(graph,'GRAPH_CANCELLED','Graph scheduling cancelled. Already-dispatched external work is not claimed cancelled.',{});await persist(runtime,graph);return{ok:true,status:200,graph}}
export async function tickGraphR148(runtime,id,input={},callbacks={}){const graph=await readGraphR148(runtime,id);if(!graph)return{ok:false,status:404,code:'R148_GRAPH_NOT_FOUND'};if(graph.state==='DRAFT')return{ok:false,status:409,code:'R148_GRAPH_AUTHORIZATION_REQUIRED',graph};if(['VERIFIED_EXECUTION_GRAPH','FAILED','CANCELLED'].includes(graph.state))return{ok:true,status:200,graph};
 for(const node of graph.nodes)if(node.runId&&['DISPATCHED','RUNNING','READY'].includes(node.state))await syncNodeFromRun(runtime,graph,node);
 for(const node of graph.nodes){if(['VERIFIED','FAILED'].includes(node.state)||node.runId&&['DISPATCHED','RUNNING'].includes(node.state))continue;const deps=dependencyState(graph,node);if(deps==='HOLD'){node.state='HOLD';node.lastError='R148_DEPENDENCY_NOT_VERIFIED';continue}if(deps==='WAITING_DEPENDENCY'){node.state='WAITING_DEPENDENCY';continue}if(nativeDomain(node)&&node.executionInput.confirmed!==true){node.state='WAITING_CONFIRMATION';node.lastError='R148_EXPLICIT_NATIVE_CONFIRMATION_REQUIRED';continue}if(node.state!=='HOLD')node.state='READY'}
 let slots=Math.max(0,graph.config.maxConcurrency-activeNodeCount(graph));for(const node of graph.nodes){if(slots<=0)break;if(node.state!=='READY')continue;if(graph.authorization?.safeAutoDispatch===false&&!input.dispatchNodeIds?.includes?.(node.id))continue;slots--;await dispatchNode(runtime,graph,node,callbacks)}
 graph.state=graphState(graph);if(graph.state==='VERIFIED_EXECUTION_GRAPH'&&!graph.completedAt){graph.completedAt=Date.now();await appendGraphEvent(graph,'GRAPH_VERIFIED','All graph nodes reached executor-specific VERIFIED execution state',{nodes:graph.nodes.map(x=>({id:x.id,runId:x.runId,executorId:x.executorId,resultFingerprint:x.resultFingerprint}))})}else if(graph.state==='FAILED'){await appendGraphEvent(graph,'GRAPH_FAILED','At least one node failed under fail-fast graph policy',{failed:graph.nodes.filter(x=>x.state==='FAILED').map(x=>x.id)})}else await appendGraphEvent(graph,'GRAPH_TICK','Scheduler tick completed',{state:graph.state,verified:graph.nodes.filter(x=>x.state==='VERIFIED').length,active:activeNodeCount(graph),waitingConfirmation:graph.nodes.filter(x=>x.state==='WAITING_CONFIRMATION').length});await persist(runtime,graph);return{ok:true,status:200,graph}}
export async function replayGraphR148(runtime,id){const graph=await readGraphR148(runtime,id);if(!graph)return null;let previous=null,eventChainOk=true;for(let i=0;i<graph.events.length;i++){const e=graph.events[i],base={schema:e.schema,graphId:e.graphId,ordinal:e.ordinal,type:e.type,detail:e.detail,at:e.at,data:e.data,previousHash:e.previousHash,canonicalMutation:false,canonicalAdmissionAuthority:'R125'},expected=await sha(base);if(e.ordinal!==i||e.previousHash!==previous||e.hash!==expected){eventChainOk=false;break}previous=e.hash}const runs=[];let runReplayOk=true;for(const node of graph.nodes){if(!node.runId)continue;const replay=await replayRunR146(runtime,node.runId);runs.push({nodeId:node.id,runId:node.runId,replay});if(!replay?.ok)runReplayOk=false}return{ok:eventChainOk&&previous===graph.headSha256&&runReplayOk,schema:'OMEGA_OPERATION_GRAPH_REPLAY_R148',graphId:graph.id,eventChainOk,graphHeadMatch:previous===graph.headSha256,replayedHeadSha256:previous,storedHeadSha256:graph.headSha256,runReplayOk,runs,canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'Replay verifies graph-event and linked R146 execution-ledger integrity. It does not independently verify the factual or physical truth of executor outputs.'}}
