import {runtimeStorageR165} from './runtimeStorageR165.js';

export const R146_REVISION='R146';
export const R146_SCHEMA='OMEGA_DURABLE_OPERATION_EXECUTION_R146';
export const R146_STATES=Object.freeze(['DISCOVERED','AUTHORIZED','AVAILABLE','INVOKED','RETURNED','VERIFIED','UNAVAILABLE','FAILED','REJECTED','STALE']);
export const R146_TERMINAL=new Set(['VERIFIED','UNAVAILABLE','FAILED','REJECTED','STALE']);
export const R146_LAWS=Object.freeze([
 'R143_ROUTE_CONTRACT_PRECEDES_DURABLE_EXECUTION_RUN',
 'AUTHENTICATED_UI_SELECTION_CREATES_INTENT_NOT_EXECUTION_PROOF',
 'EVERY_EXECUTION_TRANSITION_IS_HASH_CHAINED_AND_REPLAYABLE',
 'ROUTE_READINESS_DOES_NOT_ADVANCE_INVOCATION',
 'INVOCATION_REQUIRES_AN_EXPLICIT_AUTHORIZED_TRANSITION',
 'RETURNED_DOES_NOT_EQUAL_VERIFIED',
 'HYBRID_VERIFIED_REQUIRES_R141_EXACT_PAYLOAD_PROOF',
 'NON_HYBRID_VERIFIED_REQUIRES_PROOF_REFERENCE_AND_RESULT_FINGERPRINT',
 'R144_ATTESTATION_AND_R145_WORLD_SCAR_ARE_EVIDENCE_NOT_AUTO_ADMISSION',
 'EXECUTION_RUNS_NEVER_MUTATE_CANONSTATE',
 'R125_REMAINS_THE_ONLY_CANONSTATE_ADMISSION_AUTHORITY'
]);
const NEXT=Object.freeze({DISCOVERED:new Set(['AUTHORIZED','UNAVAILABLE','REJECTED','STALE']),AUTHORIZED:new Set(['AVAILABLE','UNAVAILABLE','REJECTED','STALE']),AVAILABLE:new Set(['INVOKED','UNAVAILABLE','FAILED','REJECTED','STALE']),INVOKED:new Set(['RETURNED','FAILED','STALE']),RETURNED:new Set(['VERIFIED','FAILED','REJECTED','STALE']),VERIFIED:new Set(),UNAVAILABLE:new Set(),FAILED:new Set(),REJECTED:new Set(),STALE:new Set()});
const txt=(v,n=320)=>String(v??'').trim().slice(0,n);
const sid=v=>{const s=txt(v,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:''};
const stable=v=>{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v};
const sha=async v=>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(v))));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')};
const key=id=>`execution:r146:run:${id}`;const INDEX='execution:r146:index';
function contract(input={}){return{schema:txt(input.schema,80),revision:txt(input.revision,16),routeId:txt(input.routeId,160),route:txt(input.route,160),workspaceId:txt(input.workspaceId,160),capabilityId:txt(input.capabilityId,160),executionDomain:txt(input.executionDomain,32).toUpperCase(),state:txt(input.state,32).toUpperCase(),receiptAuthority:txt(input.receiptAuthority,32),admissionAuthority:txt(input.admissionAuthority,32)}}
function validContract(c){return c.schema==='OMEGA_AUTHORITATIVE_UI_OPERATION_CHAIN_R143'&&c.revision==='R143'&&Boolean(c.routeId&&c.route&&c.capabilityId&&c.executionDomain)&&c.receiptAuthority==='R142'&&c.admissionAuthority==='R125'}
function evidence(input={}){return{proofRef:txt(input.proofRef,512)||null,resultFingerprint:txt(input.resultFingerprint,256)||null,providerReceipt:txt(input.providerReceipt,1200)||null,r141Closure:input.r141Closure&&typeof input.r141Closure==='object'?stable(input.r141Closure):null,r144Attestation:input.r144Attestation&&typeof input.r144Attestation==='object'?stable(input.r144Attestation):null,r145WorldScar:input.r145WorldScar&&typeof input.r145WorldScar==='object'?stable(input.r145WorldScar):null}}
function hybridProof(e){const c=e?.r141Closure;return Boolean(c&&c.state==='VERIFIED_EXECUTION_RETURN'&&c.fingerprint?.verified===true&&c.fingerprint?.digestMatch===true&&c.fingerprint?.semanticMatch===true&&c.finalHeadSha256)}
function normalProof(e){return Boolean(e?.proofRef&&e?.resultFingerprint)}
async function appendEvent(run,from,to,reason,evd={}){const base={schema:'OMEGA_EXECUTION_EVENT_R146',runId:run.id,ordinal:run.events.length,from,to,reason:txt(reason,500),at:Date.now(),evidence:evidence(evd),previousHash:run.headSha256||null,canonicalMutation:false,canonicalAdmissionAuthority:'R125'},hash=await sha(base);return{...base,hash}}
async function persist(runtime,run){const storage=runtimeStorageR165(runtime);await storage.put(key(run.id),run);const ids=await storage.get(INDEX)||[];await storage.put(INDEX,[run.id,...ids.filter(x=>x!==run.id)].slice(0,256));return run}
export function manifestR146(){return{ok:true,schema:'OMEGA_DURABLE_OPERATION_EXECUTION_MANIFEST_R146',revision:R146_REVISION,runSchema:R146_SCHEMA,states:R146_STATES,laws:R146_LAWS,upstream:{routeContract:'R143',executionLifecycle:'R142',hybridProof:'R141',runtimeAttestation:'R144',worldScar:'R145'},storageCompatibility:'R165',canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R146 is durable operational history. It records authenticated route intent and explicit execution transitions. It does not convert route readiness, UI selection, returned data, runtime attestation, or world scar evidence into execution verification or CanonState admission.'}}
export async function createRunR146(runtime,input={}){const c=contract(input.contract);if(!validContract(c))return{ok:false,status:400,code:'R146_R143_CONTRACT_REQUIRED'};const id='run_'+crypto.randomUUID().replaceAll('-',''),t=Date.now(),run={schema:R146_SCHEMA,revision:R146_REVISION,id,intent:txt(input.intent||c.route,2000),contract:c,state:'DISCOVERED',createdAt:t,updatedAt:t,events:[],headSha256:null,canonicalMutation:false,canonicalAdmissionAuthority:'R125',metadata:input.metadata&&typeof input.metadata==='object'?stable(input.metadata):{}};const ev=await appendEvent(run,null,'DISCOVERED','R143-authoritative operation intent persisted',{proofRef:'R146_CREATE'});run.events.push(ev);run.headSha256=ev.hash;await persist(runtime,run);return{ok:true,status:201,run}}
export async function readRunR146(runtime,id){id=sid(id);return id?await runtimeStorageR165(runtime).get(key(id))||null:null}
export async function listRunsR146(runtime){const storage=runtimeStorageR165(runtime),ids=await storage.get(INDEX)||[],runs=[];for(const id of ids.slice(0,64)){const r=await storage.get(key(id));if(r)runs.push(r)}return runs}
export async function transitionRunR146(runtime,id,input={}){const run=await readRunR146(runtime,id);if(!run)return{ok:false,status:404,code:'R146_RUN_NOT_FOUND'};const to=txt(input.state,32).toUpperCase();if(!R146_STATES.includes(to))return{ok:false,status:400,code:'R146_STATE_INVALID',run};if(R146_TERMINAL.has(run.state))return{ok:false,status:409,code:'R146_TERMINAL_STATE_LOCKED',run};if(!NEXT[run.state]?.has(to))return{ok:false,status:409,code:'R146_ILLEGAL_TRANSITION',from:run.state,to,run};const evd=evidence(input.evidence);if(to==='VERIFIED'){const ok=run.contract.executionDomain==='HYBRID'?hybridProof(evd):normalProof(evd);if(!ok)return{ok:false,status:409,code:run.contract.executionDomain==='HYBRID'?'R146_R141_PROOF_REQUIRED':'R146_RESULT_PROOF_REQUIRED',run}}const ev=await appendEvent(run,run.state,to,input.reason||`${run.state} -> ${to}`,evd);run.state=to;run.updatedAt=ev.at;run.events=[...run.events,ev];run.headSha256=ev.hash;await persist(runtime,run);return{ok:true,status:200,run,event:ev}}
export async function replayRunR146(runtime,id){const run=await readRunR146(runtime,id);if(!run)return null;let previous=null,ok=true;for(let i=0;i<run.events.length;i++){const e=run.events[i],base={schema:e.schema,runId:e.runId,ordinal:e.ordinal,from:e.from,to:e.to,reason:e.reason,at:e.at,evidence:e.evidence,previousHash:e.previousHash,canonicalMutation:false,canonicalAdmissionAuthority:'R125'},expected=await sha(base);if(e.ordinal!==i||e.previousHash!==previous||e.hash!==expected){ok=false;break}previous=e.hash}return{ok:ok&&previous===run.headSha256,schema:'OMEGA_EXECUTION_REPLAY_R146',runId:run.id,eventCount:run.events.length,replayedHeadSha256:previous,storedHeadSha256:run.headSha256,headMatch:previous===run.headSha256,storageCompatibility:'R165',canonicalMutation:false,canonicalAdmissionAuthority:'R125',verifiedAt:Date.now()}}
