export const R184_REVISION='R184';
export type FabricKind='SOURCE'|'PACKET'|'METRIC'|'SCENE'|'BRANCH'|'RUN'|'SYSTEM';
export type FabricNode={id:string;kind:FabricKind;label:string;value?:number|null;weight:number;sourceDiversity:number;uncertainty:number;timestamp?:number|null;meta:any};
export type FabricEdge={a:string;b:string;weight:number;relation:string;independentSources:number};
export type FabricGraph={revision:string;nodes:FabricNode[];edges:FabricEdge[];stats:{nodes:number;edges:number;sources:number;packets:number;metrics:number;scenes:number;branches:number;runs:number};fingerprint:string|null};
const finite=(v:any)=>Number.isFinite(Number(v))?Number(v):null;
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const safe=(v:any,n=100)=>String(v??'').slice(0,n);
const id=(kind:string,v:any)=>`${kind}:${safe(v,160).replace(/[^A-Za-z0-9._:-]/g,'_')}`;
function pushNode(map:Map<string,FabricNode>,node:FabricNode){const prior=map.get(node.id);if(!prior||node.weight>prior.weight)map.set(node.id,node)}
function addEdge(map:Map<string,FabricEdge>,a:string,b:string,weight:number,relation:string,independentSources=1){if(!a||!b||a===b)return;const [x,y]=a<b?[a,b]:[b,a],key=`${x}|${y}|${relation}`,w=clamp(weight);const prior=map.get(key);map.set(key,prior?{...prior,weight:clamp(1-(1-prior.weight)*(1-w)),independentSources:Math.max(prior.independentSources,independentSources)}:{a:x,b:y,weight:w,relation,independentSources})}
export function buildCorrelationFabricR184(input:{calibration?:any;packets?:any[];sar?:any;plan?:any;runs?:any[];system?:any}):FabricGraph{
 const calibration=input.calibration||{},packets=Array.isArray(input.packets)?input.packets:[],scenes=Array.isArray(input.sar?.scenes)?input.sar.scenes:[],branches=Array.isArray(input.plan?.branches)?input.plan.branches:[],runs=Array.isArray(input.runs)?input.runs:[],nodes=new Map<string,FabricNode>(),edges=new Map<string,FabricEdge>(),sourceIds=new Set<string>();
 const sysId=id('system','omega');pushNode(nodes,{id:sysId,kind:'SYSTEM',label:'OMEGA runtime',weight:1,sourceDiversity:Number(calibration.sourceCount||0),uncertainty:clamp(Number(calibration?.residual?.highUncertaintyCount||0)/Math.max(1,Object.keys(calibration?.fusedMetrics||{}).length)),meta:input.system||{}});
 for(const packet of packets){const pid=id('packet',packet.packetId||packet.packetSha256||Math.random()),source=safe(packet?.source?.id||'unknown-source',180),sid=id('source',source);sourceIds.add(source);pushNode(nodes,{id:sid,kind:'SOURCE',label:safe(packet?.source?.title||source,64),weight:clamp(Number(packet.effectiveWeight||.1)),sourceDiversity:1,uncertainty:clamp(Number(packet.uncertainty??.5)),timestamp:finite(packet.observedAt),meta:packet.source});pushNode(nodes,{id:pid,kind:'PACKET',label:safe(packet.packetId||'packet',54),weight:clamp(Number(packet.effectiveWeight||.1)),sourceDiversity:1,uncertainty:clamp(Number(packet.uncertainty??.5)),timestamp:finite(packet.observedAt),meta:packet});addEdge(edges,sid,pid,.9,'PRODUCED',1);
  const metricNames=Object.keys(packet.metrics||{});for(const name of metricNames){const mid=id('metric',name),fused=calibration?.fusedMetrics?.[name]||{},weak=(calibration?.residual?.weakestFirst||[]).find((x:any)=>String(x.name)===name)||{};pushNode(nodes,{id:mid,kind:'METRIC',label:name,value:finite(fused.value??packet.metrics[name]),weight:clamp(Math.log1p(Number(fused.effectiveWeight||packet.effectiveWeight||.1))/3),sourceDiversity:Number(fused.independentSourceCount||1),uncertainty:clamp(Number(weak.relativeUncertainty??fused.weightedStdDev??.25)),timestamp:finite(fused.latestObservedAt||packet.observedAt),meta:{...fused,weak}});addEdge(edges,pid,mid,clamp(Number(packet.effectiveWeight||.2)),'MEASURES',Number(fused.independentSourceCount||1))}
  for(let i=0;i<metricNames.length;i++)for(let j=i+1;j<metricNames.length;j++){const a=id('metric',metricNames[i]),b=id('metric',metricNames[j]);addEdge(edges,a,b,Math.min(.72,.18+.08*metricNames.length),'CO_OCCURS',1)}
 }
 for(const scene of scenes){const sid=id('scene',`${scene.provider||'sar'}:${scene.id||scene.datetime}`),provider=id('source',scene.provider||'sar-provider');sourceIds.add(String(scene.provider||'sar-provider'));pushNode(nodes,{id:provider,kind:'SOURCE',label:safe(scene.provider||'SAR provider',64),weight:.75,sourceDiversity:1,uncertainty:.15,meta:{provider:scene.provider}});pushNode(nodes,{id:sid,kind:'SCENE',label:safe(`${scene.family||'SAR'} ${scene.datetime||''}`,60),weight:.78,sourceDiversity:1,uncertainty:clamp(1-Number(scene?.calibration?.relativeCoherence??.5)),timestamp:scene.datetime?Date.parse(scene.datetime):null,meta:scene});addEdge(edges,provider,sid,.9,'OBSERVED',1);for(const metricName of ['sarSceneCount','sarAcquisitionEpochs','sarMeanRelativeCoherence','sarMeanFrameResidual']){const mid=id('metric',metricName);if(nodes.has(mid))addEdge(edges,sid,mid,.62,'CALIBRATES',Number(nodes.get(mid)?.sourceDiversity||1))}}
 for(const branch of branches){const key=`${branch.domain}:${branch.phase}`,bid=id('branch',key),cells=Array.isArray(branch.cells)?branch.cells:[];pushNode(nodes,{id:bid,kind:'BRANCH',label:`D${branch.domain} · P${branch.phase}`,weight:clamp(.25+cells.length/24),sourceDiversity:Number(calibration.sourceCount||0),uncertainty:clamp(Number(input.plan?.metrics?.uncertainty??.35)),meta:branch});addEdge(edges,sysId,bid,.62,'PLANS',Number(calibration.sourceCount||0));for(const metric of Object.keys(input.plan?.metrics||{})){const mid=id('metric',metric);if(nodes.has(mid))addEdge(edges,mid,bid,.68,'INFORMS',Number(nodes.get(mid)?.sourceDiversity||0))}}
 for(const run of runs.slice(0,80)){const rid=id('run',run.id||run.runId||run.receiptSha256||Math.random());pushNode(nodes,{id:rid,kind:'RUN',label:safe(run.id||run.runId||run.status||'execution',58),weight:String(run.status||'').includes('COMPLETE')?.88:.58,sourceDiversity:0,uncertainty:String(run.status||'').includes('VERIFIED')?.08:.42,timestamp:finite(run.updatedAt||run.completedAt||run.createdAt),meta:run});addEdge(edges,sysId,rid,.55,'EXECUTION_LINEAGE',0)}
 const arr=[...nodes.values()],byKind=(k:FabricKind)=>arr.filter(n=>n.kind===k).length;return{revision:R184_REVISION,nodes:arr,edges:[...edges.values()],stats:{nodes:arr.length,edges:edges.size,sources:sourceIds.size,packets:byKind('PACKET'),metrics:byKind('METRIC'),scenes:byKind('SCENE'),branches:byKind('BRANCH'),runs:byKind('RUN')},fingerprint:calibration?.fingerprint||null}
}
export function visibleFabricR184(graph:FabricGraph,zoom:number,selectedId=''){const z=Math.max(.2,Math.min(4,zoom)),max=z<.55?90:z<1?180:z<1.8?360:900;const priority=(n:FabricNode)=>n.id===selectedId?99:(n.kind==='SYSTEM'?10:n.kind==='METRIC'?8:n.kind==='BRANCH'?7:n.kind==='SCENE'?6:n.kind==='RUN'?5:n.kind==='SOURCE'?4:3)+n.weight*3+n.sourceDiversity*.08-n.uncertainty;const nodes=[...graph.nodes].sort((a,b)=>priority(b)-priority(a)).slice(0,max),set=new Set(nodes.map(n=>n.id)),edges=graph.edges.filter(e=>set.has(e.a)&&set.has(e.b)).sort((a,b)=>b.weight-a.weight).slice(0,max*4);return{nodes,edges,lod:z<.55?'OVERVIEW':z<1?'STRUCTURE':z<1.8?'EVIDENCE':'DETAIL'} as const}
}
