import fs from 'node:fs';
const path='src/TraversalModeStageR100.tsx';
let text=fs.readFileSync(path,'utf8');
const from="const[animated,setAnimated]=useState(true);",to="const[animated,setAnimated]=useState(false);";
if(!text.includes(from)&&!text.includes(to))throw new Error('R182 traversal animation default anchor missing');
text=text.replace(from,to);
for(const token of ["setAnimated(v=>!v)","animated?'Pause motion':'Animate'","<label>TIME<input type='range'",'timeScale','ORIENTATION σ','visualFieldPoint(','warpTraversalPointR99(','applyWovenContinuityR100(','compileSourceTraversal(address,routeDepth)',"projectionPoint(step.address,'MANDALA',1000)"])if(!text.includes(token))throw new Error(`R182 traversal retained function missing ${token}`);
if(text.includes('const[animated,setAnimated]=useState(true);'))throw new Error('R182 traversal still autoplays representational motion');
fs.writeFileSync(path,text);
console.log('R182 TRAVERSAL STABLE-DEFAULT PASS · animation retained as explicit operator action');
