import {corpusState,encodeAddress,STATE_COUNT} from './corpusRuntime';
import {allModesTruthFusionAtAddressR151,R151_CHANNEL_COUNT,type FusionOperatorR151} from './allModesTruthFusionR151';

export const R151_SWARM_HIERARCHY={seed:1,organs:12,branches:144,cells:1728,lanes:20736,statesPerCell:12,channelsPerState:R151_CHANNEL_COUNT,readingsPerCell:12*R151_CHANNEL_COUNT,totalReadings:STATE_COUNT*R151_CHANNEL_COUNT} as const;
export const R151_SWARM_LAWS=Object.freeze([
 'ONE_CELL_EQUALS_ONE_DOMAIN_PHASE_REGULATION_WITH_ALL_12_LAYERS',
 'ALL_20736_CANONICAL_STATES_OCCUR_EXACTLY_ONCE',
 'CELL_RESULTS_RECONVERGE_1728_TO_144_TO_12_TO_1',
 'SWARM_PARTITION_IS_EXECUTION_PLANNING_NOT_INVOCATION_PROOF',
 'CELL_CONSENSUS_IS_NOT_INDEPENDENT_EMPIRICAL_REPLICATION',
 'R125_REMAINS_CANONSTATE_ADMISSION_AUTHORITY'
]);

const cl=(x:any)=>Math.max(0,Math.min(1,Number.isFinite(Number(x))?Number(x):0));
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const fnv1a32=(text:string)=>{let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193)}return(h>>>0).toString(16).padStart(8,'0')};

export type R151SwarmCellPlan={cell:number;organ:number;branch:number;domain:number;phase:number;regulation:number;addresses:number[];stateIds:number[];readings:number;scope:{type:'CELL';domain:number;phase:number;regulation:number}};
export type R151SwarmCellResult={schema:'OMEGA_R151_SWARM_CELL_RESULT';cell:number;organ:number;branch:number;domain:number;phase:number;regulation:number;addresses:number[];stateIds:number[];meanTruthConfidence:number;meanAgreement:number;meanDispersion:number;residualRisk:number;canonicalOperators:Record<FusionOperatorR151,number>;advisoryOperators:Record<FusionOperatorR151,number>;operatorAgreement:number;highestResidualState:{address:number;stateId:number;risk:number}|null;readings:number;fingerprint:string;canonicalMutation:false;boundary:string};

function coordsForCell(cell:number){const c=Math.max(0,Math.min(1727,Math.floor(Number(cell)||0))),domain=Math.floor(c/144),rem=c%144,phase=Math.floor(rem/12),regulation=rem%12;return{cell:c,domain,phase,regulation,organ:domain,branch:domain*12+phase}}
export function compileAllModesSwarmCellPlanR151(cell:number):R151SwarmCellPlan{const c=coordsForCell(cell),addresses=Array.from({length:12},(_,layer)=>encodeAddress(c.domain,c.phase,c.regulation,layer));return{cell:c.cell,organ:c.organ,branch:c.branch,domain:c.domain,phase:c.phase,regulation:c.regulation,addresses,stateIds:addresses.map(x=>x+1),readings:addresses.length*R151_CHANNEL_COUNT,scope:{type:'CELL',domain:c.domain,phase:c.phase,regulation:c.regulation}}}
export function compileAllModesSwarmPlanR151(){const cells=Array.from({length:1728},(_,cell)=>compileAllModesSwarmCellPlanR151(cell)),addresses=cells.flatMap(x=>x.addresses),unique=new Set(addresses);return{schema:'OMEGA_R151_ALL_MODES_SWARM_PLAN',hierarchy:R151_SWARM_HIERARCHY,laws:R151_SWARM_LAWS,cells,totalAddresses:addresses.length,uniqueAddresses:unique.size,complete:addresses.length===STATE_COUNT&&unique.size===STATE_COUNT&&Math.min(...addresses)===0&&Math.max(...addresses)===STATE_COUNT-1,canonicalMutation:false,authority:'EXECUTION_PLAN_ONLY',boundary:'The plan partitions the canonical 20,736-state atlas exactly into 1,728 logical cell tasks of 12 layer states. It does not prove 1,728 physical clouds, agents or executions are online.'}}

const zeroOps=():Record<FusionOperatorR151,number>=>({CARRY:0,CONSTRUCT:0,PRUNE:0,TURN:0,ESCALATE:0});
export function evaluateAllModesSwarmCellR151(cell:number):R151SwarmCellResult{const plan=compileAllModesSwarmCellPlanR151(cell),canonical=zeroOps(),advisory=zeroOps(),rows=plan.addresses.map(address=>{const record=corpusState(address),fusion=allModesTruthFusionAtAddressR151(address),risk=cl(fusion.consensus.dispersion+(1-fusion.consensus.truthConfidence));canonical[fusion.operator.canonical]++;advisory[fusion.operator.advisory]++;return{address,stateId:record.stateId,truth:fusion.consensus.truthConfidence,agreement:fusion.consensus.agreement,dispersion:fusion.consensus.dispersion,risk,operatorAgreement:fusion.operator.agreement}}),highest=[...rows].sort((a,b)=>b.risk-a.risk)[0]||null,meanTruthConfidence=avg(rows.map(x=>x.truth)),meanAgreement=avg(rows.map(x=>x.agreement)),meanDispersion=avg(rows.map(x=>x.dispersion)),operatorAgreement=avg(rows.map(x=>x.operatorAgreement?1:0)),residualRisk=cl(meanDispersion+(1-meanTruthConfidence)),compact={cell:plan.cell,addresses:plan.addresses,meanTruthConfidence,meanAgreement,meanDispersion,residualRisk,canonical,advisory,operatorAgreement,highest:highest?{address:highest.address,stateId:highest.stateId,risk:highest.risk}:null};return{schema:'OMEGA_R151_SWARM_CELL_RESULT',cell:plan.cell,organ:plan.organ,branch:plan.branch,domain:plan.domain,phase:plan.phase,regulation:plan.regulation,addresses:plan.addresses,stateIds:plan.stateIds,meanTruthConfidence,meanAgreement,meanDispersion,residualRisk,canonicalOperators:canonical,advisoryOperators:advisory,operatorAgreement,highestResidualState:compact.highest,readings:plan.readings,fingerprint:fnv1a32(JSON.stringify(compact)),canonicalMutation:false,boundary:'Cell result is an internal fusion summary over 12 canonical layer states and 2,892 provenance-separated mode readings. It is not independent empirical replication or CanonState admission.'}}

function aggregate(rows:R151SwarmCellResult[]){return{count:rows.length,meanTruthConfidence:avg(rows.map(x=>x.meanTruthConfidence)),meanAgreement:avg(rows.map(x=>x.meanAgreement)),meanDispersion:avg(rows.map(x=>x.meanDispersion)),meanResidualRisk:avg(rows.map(x=>x.residualRisk)),readings:rows.reduce((n,x)=>n+x.readings,0)}}
export function foldAllModesSwarmR151(cellResults:R151SwarmCellResult[]){const byCell=new Map(cellResults.map(x=>[x.cell,x])),ordered=Array.from({length:1728},(_,i)=>byCell.get(i)).filter(Boolean) as R151SwarmCellResult[],branches=Array.from({length:144},(_,branch)=>aggregate(ordered.filter(x=>x.branch===branch))),organs=Array.from({length:12},(_,organ)=>aggregate(ordered.filter(x=>x.organ===organ))),seed=aggregate(ordered),complete=ordered.length===1728&&seed.readings===R151_SWARM_HIERARCHY.totalReadings;return{schema:'OMEGA_R151_SWARM_RECONVERGENCE',hierarchy:R151_SWARM_HIERARCHY,receivedCells:ordered.length,branches,organs,seed,complete,canonicalMutation:false,boundary:'Reconvergence carries aggregate internal coherence and residuals from 1,728 cells to 144 branches to 12 organs to one seed. It neither manufactures missing cells nor converts swarm agreement into empirical truth.'}}
