import {useMemo,useState} from 'react';
import {Download,Search,ShieldCheck,Waypoints} from 'lucide-react';
import {R49_ARCHIVE_RECONCILIATION,R49_RECONCILIATION_SUMMARY,type ArchiveReality,type ArchiveRelation} from './archiveReconciliationR49';
import {localState} from './platformAdapter';
import './archiveReconciliationR49.css';
const REALITIES=['ALL','WEB_ACTIVE','SOURCE_ACTIVE','LOCAL_ACTIVE','EVIDENCE_GATED','DEVICE_GATED'] as const;
const RELATIONS=['ALL','CURRENT_SUCCESSOR','MERGED_INTO_SUCCESSOR','DONOR_RETAINED'] as const;
function download(){const payload={...R49_RECONCILIATION_SUMMARY,rows:R49_ARCHIVE_RECONCILIATION};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='OMEGA_ARCHIVE_RECONCILIATION_R49.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),600)}
export default function ArchiveReconciliationR49({onNavigate}:{onNavigate?:(p:string)=>void}={}){const[q,setQ]=useState(''),[reality,setReality]=useState<'ALL'|ArchiveReality>('ALL'),[relation,setRelation]=useState<'ALL'|ArchiveRelation>('ALL');const rows=useMemo(()=>R49_ARCHIVE_RECONCILIATION.filter(x=>(reality==='ALL'||x.reality===reality)&&(relation==='ALL'||x.relation===relation)&&`${x.id} ${x.family} ${x.artifact} ${x.role} ${x.capability} ${x.menuId}`.toLowerCase().includes(q.toLowerCase())),[q,reality,relation]);const s:any=R49_RECONCILIATION_SUMMARY;const go=(p:string)=>{if(onNavigate){onNavigate(p);return}localState.write('omega.v6.panel',p);window.location.reload()};return <section className='r49-reconciliation'><header><div><span>R49 FULL ARCHIVE RECONCILIATION · 100/100 WORKBOOK REGISTRY ROWS</span><h2>Every named software artifact has a current fate</h2><p>KEEP, MERGE and DONOR history remains intact while each row is bound to a current successor route and explicit execution/evidence/device reality.</p></div><button onClick={download}><Download/>Export 100-row receipt</button></header><div className='r49-kpis'><article><b>{s.rowCount}</b><span>registry rows</span></article><article><b>{s.byDisposition.KEEP}</b><span>historical KEEP</span></article><article><b>{s.byDisposition.MERGE}</b><span>historical MERGE</span></article><article><b>{s.byDisposition.DONOR}</b><span>historical DONOR</span></article><article><b>{s.byRelation.CURRENT_SUCCESSOR}</b><span>current successors</span></article><article><b>{s.byRelation.MERGED_INTO_SUCCESSOR}</b><span>merged lineage</span></article><article><b>{s.byRelation.DONOR_RETAINED}</b><span>retained donors</span></article><article><b>{s.unmapped}</b><span>unmapped</span></article></div><div className='r49-filter'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Search all 100 software rows…'/><select value={reality} onChange={e=>setReality(e.target.value as any)}>{REALITIES.map(x=><option key={x}>{x}</option>)}</select><select value={relation} onChange={e=>setRelation(e.target.value as any)}>{RELATIONS.map(x=><option key={x}>{x}</option>)}</select></div><div className='r49-table'><div className='r49-head'><span>ID / artifact</span><span>Archive relation</span><span>Current reality</span><span>Successor</span></div>{rows.map(x=><article key={x.id} data-reality={x.reality}><div><code>{x.id} · {x.sequence}</code><b>{x.artifact}</b><small>{x.family} · {x.role} · {x.menuId}</small><p>{x.capability}</p></div><div><strong>{x.relation}</strong><small>Historical disposition: {x.disposition}</small></div><div><strong>{x.reality}</strong><small>{x.proof}</small></div><button onClick={()=>go(x.route)}><Waypoints/><span>{x.route}</span></button></article>)}</div><footer><ShieldCheck/>{R49_RECONCILIATION_SUMMARY.boundary}</footer></section>}
