import {useEffect,useMemo,useRef} from 'react';
import {corpusState,decodeAddress} from './corpusRuntime';
import {calculusVisualLaw,lawColor,transitionGeometry} from './calculusVisualLawR37';
import './calculusFieldR37.css';

type Mode='FIELD'|'MATTER'|'TRAVERSAL'|'FORECAST'|'RELATIVITY'|'INFINITY'|'SCALE'|'CONVERGENCE';
type Props={address:number;mode?:Mode;steps?:number;onAddress?:(n:number)=>void;label?:string};
const clampAddr=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0)));
const TAU=Math.PI*2;
function routeFrom(address:number,steps:number){const out:number[]=[];let a=clampAddr(address);for(let i=0;i<steps;i++){out.push(a);const n=corpusState(a).autoPing?.dataNext;a=Number.isFinite(n)?clampAddr(n):a}return out}
function modeGains(mode:Mode){switch(mode){case'MATTER':return{radial:1.05,depth:1.18,fold:1.28,spread:.78,recurrence:.7};case'TRAVERSAL':return{radial:.98,depth:1.08,fold:.9,spread:1.18,recurrence:.9};case'FORECAST':return{radial:1.02,depth:.92,fold:.78,spread:1.48,recurrence:.62};case'RELATIVITY':return{radial:.9,depth:1.34,fold:1.06,spread:1.02,recurrence:.84};case'INFINITY':return{radial:1.08,depth:1.04,fold:1.16,spread:.9,recurrence:1.52};case'SCALE':return{radial:.94,depth:1.22,fold:1.34,spread:.8,recurrence:1.22};case'CONVERGENCE':return{radial:.92,depth:1.0,fold:1.18,spread:.66,recurrence:.96};default:return{radial:1,depth:1,fold:1,spread:1,recurrence:1}}}
export default function CalculusFieldR37({address,mode='FIELD',steps=24,onAddress,label}:Props){
 const ref=useRef<HTMLCanvasElement|null>(null),route=useMemo(()=>routeFrom(address,Math.max(6,Math.min(48,steps))),[address,steps]),records=useMemo(()=>route.map(corpusState),[route]),laws=useMemo(()=>records.map(calculusVisualLaw),[records]),g=modeGains(mode);
 useEffect(()=>{const canvas=ref.current;if(!canvas||!laws.length)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,alive=true;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  const draw=(now:number)=>{if(!alive)return;const box=canvas.getBoundingClientRect(),dpr=Math.min(1.8,window.devicePixelRatio||1),W=Math.max(360,Math.round(box.width)),H=Math.max(420,Math.round(box.height));if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const law=laws[0],t=reduce?0:now*.001*law.phaseSpeed,cx=W*.5,cy=H*.5,R=Math.min(W,H)*.36;
   const bg=ctx.createRadialGradient(cx,cy,R*.02,cx,cy,R*1.7);bg.addColorStop(0,lawColor(law,'primary',.16));bg.addColorStop(.48,lawColor(law,'inverse',.06));bg.addColorStop(1,'rgba(0,3,6,1)');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
   for(let s=law.shellCount;s>=1;s--){const k=s/law.shellCount,rr=R*(.12+.88*k)*g.radial*(1+.035*Math.sin(t*law.pulseRate+s*.73)*law.u.Phi),ecc=1+law.shellEccentricity*.62*g.depth,flat=.58+.28*(1-law.fold*g.fold),rot=t*law.shellPrecession*(s%2?-1:1)+law.phaseAngle*.15+s*.11;ctx.beginPath();ctx.ellipse(cx,cy,rr*ecc,rr*flat,rot,0,TAU);ctx.strokeStyle=lawColor(law,s%3===0?'inverse':'primary',law.shellOpacity*(.35+.65*k));ctx.lineWidth=.55+1.6*law.u.light.coherence*k;ctx.stroke()}
   const densityMultiplier=mode==='MATTER'?1.08:(mode==='FIELD'?.72:.88);
   const count=Math.min(3200,Math.max(380,Math.round(law.density*densityMultiplier)));for(let i=0;i<count;i++){const h=Math.sin((address+1)*.013+i*12.9898)*43758.5453,u=Math.abs(h%1),v=Math.abs((Math.sin(i*78.233+address*.017)*24634.6345)%1),w=Math.abs((Math.sin(i*31.117+address*.011)*9758.132)%1),z=w*2-1,baseA=u*TAU+t*(.22+.78*law.u.motionRelativity),scarWarp=Math.sin(baseA*(2.4+law.fold*4.6)+i*.021-t*law.pulseRate)*law.scarMemory*.42,curv=law.curvature*g.fold*Math.sin(baseA*2+law.phaseAngle),a=baseA+scarWarp+curv,r=R*Math.pow(v,.54)*(.22+.72*law.u.Phi)*g.radial*(1+.15*Math.sin(a*(2+law.u.shape.petal*5)+t)*law.u.shape.petal),pers=.66+.34*(z+1)/2*law.perspectiveGain*g.depth,x=cx+Math.cos(a)*r*(1+.48*law.u.shape.anisotropy)*pers,y=cy+Math.sin(a)*r*(.56+.28*law.u.shape.symmetry)*pers+z*R*.31*law.depthGain*g.depth,alpha=law.alpha*(.15+.7*pers)*(.55+.45*law.u.evidence),kind=law.contradictionPressure>.58&&i%5===0?'inverse':law.scarMemory>.52&&i%7===0?'scar':'primary';ctx.fillStyle=lawColor(law,kind as any,alpha);ctx.beginPath();ctx.arc(x,y,law.pointRadius*(.35+.65*pers),0,TAU);ctx.fill()}
   route.forEach((a,i)=>{const rl=laws[i],age=i/Math.max(1,route.length-1),ang=rl.phaseAngle+t*.16+i*(.22+.52*law.branchSpread*g.spread),rad=R*(.14+.62*age*(.6+.4*law.routeStrength)),depth=Math.sin(ang*1.7+i*.31)*R*.12*rl.depthGain*g.depth,x=cx+Math.cos(ang)*rad*(1+.36*rl.u.shape.anisotropy),y=cy+Math.sin(ang)*rad*.66+depth,persist=(1-age)*law.trailPersistence,pulse=.7+.3*Math.sin(t*law.pulseRate-i*.7),rr=i===0?9:2.6+5*(1-age)*rl.routeStrength;ctx.fillStyle=lawColor(rl,i===0?'proof':'primary',i===0?.98:(.16+.58*persist)*pulse);ctx.beginPath();ctx.arc(x,y,rr,0,TAU);ctx.fill();if(i===0||i===route.length-1){ctx.beginPath();ctx.arc(x,y,rr+8+6*rl.proofGlow,0,TAU);ctx.strokeStyle=lawColor(rl,'proof',.18+.48*rl.proofGlow);ctx.lineWidth=1;ctx.stroke()}});
   const travel=((t*.42)%Math.max(1,route.length-1)),idx=Math.min(route.length-2,Math.floor(travel)),u=travel-idx,aLaw=laws[idx],bLaw=laws[idx+1]||aLaw,tg=transitionGeometry(aLaw,bLaw,u),ang=tg.phase+t*.12+idx*.31,rad=R*(.18+.52*((idx+u)/Math.max(1,route.length-1))),mx=cx+Math.cos(ang)*rad*(1+.42*tg.curvature),my=cy+Math.sin(ang)*rad*.64+Math.sin(ang*2)*R*.11*tg.depth;ctx.fillStyle=lawColor(aLaw,'proof',.96);ctx.beginPath();ctx.arc(mx,my,5+5*tg.route,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(mx,my,13+12*tg.fold,0,TAU);ctx.strokeStyle=lawColor(bLaw,'primary',.22+.4*tg.trail);ctx.stroke();
   if(g.recurrence>.8){const loops=Math.max(1,Math.round(2+6*law.u.shape.toroid*g.recurrence));for(let j=0;j<loops;j++){const rr=R*(.22+j*.065),start=t*.11*(j%2?1:-1)+law.phaseAngle;ctx.beginPath();ctx.arc(cx,cy,rr,start,start+TAU*(.38+.5*law.u.C));ctx.strokeStyle=lawColor(law,j%2?'primary':'inverse',.035+.11*law.u.rsc);ctx.lineWidth=.7;ctx.stroke()}}
   ctx.font='600 10px ui-monospace,monospace';ctx.fillStyle='rgba(225,239,236,.86)';ctx.fillText(`${label||mode} · STATE ${records[0].stateId} · ${law.modeDecision}`,16,22);ctx.font='9px ui-monospace,monospace';ctx.fillStyle='rgba(150,181,178,.78)';ctx.fillText(`U ${law.u.unifiedCoherence.toFixed(3)} · CΩ ${law.u.C.toFixed(3)} · Φ ${law.u.Phi.toFixed(3)} · q ${law.u.q.toFixed(3)} · Λ ${law.u.Lambda.toFixed(3)} · scar ${law.u.scar.toFixed(3)}`,16,H-28);ctx.fillText(`conductance ${law.u.water.conductance.toFixed(3)} · motion ${law.u.motionRelativity.toFixed(3)} · curvature ${law.curvature.toFixed(3)} · fold ${law.fold.toFixed(3)} · proof ${law.u.evidence.toFixed(3)}`,16,H-12);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[address,mode,route,records,laws,g.radial,g.depth,g.fold,g.spread,g.recurrence,label]);
 const pick=(e:React.MouseEvent<HTMLCanvasElement>)=>{if(!onAddress)return;const b=e.currentTarget.getBoundingClientRect(),cx=b.width*.5,cy=b.height*.5,mx=e.clientX-b.left,my=e.clientY-b.top;let best=route[0],dist=Infinity;route.forEach((a,i)=>{const law=laws[i],ang=law.phaseAngle+i*(.22+.52*laws[0].branchSpread*g.spread),rad=Math.min(b.width,b.height)*.36*(.14+.62*(i/Math.max(1,route.length-1))*(.6+.4*laws[0].routeStrength)),x=cx+Math.cos(ang)*rad,y=cy+Math.sin(ang)*rad*.66,d=(x-mx)**2+(y-my)**2;if(d<dist){dist=d;best=a}});onAddress(best)};
 const law=laws[0],coords=decodeAddress(address);return <section className='calculus-field-r37'><canvas ref={ref} onClick={pick} aria-label={`${mode} calculus-driven field for state ${address+1}`}/><div className='cfr37-legend'><span><b>{mode}</b> calculus projection</span><span>D{coords.d+1} · P{coords.p+1} · R{coords.r+1} · L{coords.l+1}</span><span>{route.length-1} admitted transitions</span><span>color = phase + inverse/outverse + coherence + proof</span></div><div className='cfr37-law'><span>shells <b>{law.shellCount}</b></span><span>density <b>{law.density}</b></span><span>trail <b>{law.trailPersistence.toFixed(2)}</b></span><span>branch <b>{law.branchSpread.toFixed(2)}</b></span><span>depth <b>{law.depthGain.toFixed(2)}</b></span><span>route <b>{law.routeStrength.toFixed(2)}</b></span></div></section>;
}
