import {useEffect,useMemo,useRef} from 'react';
import {corpusState,decodeAddress} from './corpusRuntime';
import {calculusVisualLaw,lawColor,operatorColor,transitionGeometry,type OperatorColorRole} from './calculusVisualLawR37';
import {projectionForR82} from './omegaExperienceRegistryR82';
import './calculusFieldR37.css';
type Mode='FIELD'|'MATTER'|'TRAVERSAL'|'FORECAST'|'RELATIVITY'|'INFINITY'|'SCALE'|'CONVERGENCE';
type Props={address:number;mode?:Mode;steps?:number;onAddress?:(n:number)=>void;label?:string;observerBeta?:number};
const clampAddr=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0))),cl=(n:number,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a)),TAU=Math.PI*2,ROLES:OperatorColorRole[]=['ALPHA','BASE','CONSTRUCT','PRUNE','OMEGA'];
const ROLE_NOTE:Record<OperatorColorRole,string>={ALPHA:'possibility / phase opening',BASE:'evidence / continuity anchor',CONSTRUCT:'outverse growth / motion',PRUNE:'contradiction / inverse pressure',OMEGA:'coherence / closure'};
function routeFrom(address:number,steps:number){const out:number[]=[];let a=clampAddr(address);for(let i=0;i<steps;i++){out.push(a);const n=corpusState(a).autoPing?.dataNext;a=Number.isFinite(n)?clampAddr(n):a}return out}
function modeGains(mode:Mode){switch(mode){case'MATTER':return{radial:1.0,depth:1.16,fold:1.22,spread:.82,recurrence:.78};case'TRAVERSAL':return{radial:.98,depth:1.06,fold:.9,spread:1.2,recurrence:.9};case'FORECAST':return{radial:1,depth:.92,fold:.78,spread:1.5,recurrence:.64};case'RELATIVITY':return{radial:.92,depth:1.32,fold:1.05,spread:1.02,recurrence:.86};case'INFINITY':return{radial:1.04,depth:1.02,fold:1.14,spread:.94,recurrence:1.46};case'SCALE':return{radial:.94,depth:1.2,fold:1.28,spread:.82,recurrence:1.18};case'CONVERGENCE':return{radial:.94,depth:1,fold:1.16,spread:.68,recurrence:.94};default:return{radial:1,depth:1,fold:1,spread:1,recurrence:1}}}
function weightedRole(law:any,u:number){let total=0;const weighted=ROLES.map(r=>{const w=.08+Number(law.operatorWeights?.[r]||0);total+=w;return[r,w] as const});let p=((u%1)+1)%1*total;for(const[r,w]of weighted){p-=w;if(p<=0)return r}return'OMEGA' as OperatorColorRole}
function observerProjection(mode:Mode,betaInput:number){const beta=mode==='RELATIVITY'?cl(Number(betaInput)||0,0,.94):0,gamma=1/Math.sqrt(Math.max(.0001,1-beta*beta)),doppler=Math.sqrt((1+beta)/Math.max(.0001,1-beta)),compression=1/gamma;return{beta,gamma,doppler,compression}}
function aberrateAngle(theta:number,beta:number){if(beta<=0)return theta;const c=Math.cos(theta),den=Math.max(.0001,1-beta*c),cp=cl((c-beta)/den,-1,1),m=Math.acos(cp),sign=Math.sin(theta)<0?-1:1;return sign*m}
function drawProjectionSignatureR82(ctx:CanvasRenderingContext2D,mode:Mode,L:any,t:number,cx:number,cy:number,R:number,observer:any){
 const ac=(role:OperatorColorRole,a:number)=>operatorColor(L,role,a);
 ctx.save();ctx.lineCap='round';ctx.lineJoin='round';
 if(mode==='MATTER'){
  const step=Math.max(22,R*.16);for(let x=cx-R;x<=cx+R;x+=step){for(let y=cy-R*.72;y<=cy+R*.72;y+=step){const j=Math.sin(x*.013+y*.017+L.phaseAngle)*5,r=1.2+2.8*L.u.evidence;ctx.beginPath();ctx.arc(x+j,y-j*.35,r,0,TAU);ctx.fillStyle=ac('BASE',.12+.34*L.u.C);ctx.fill();if(((Math.round(x/step)+Math.round(y/step))&1)===0){ctx.beginPath();ctx.moveTo(x+j,y-j*.35);ctx.lineTo(cx+(x-cx)*.72,cy+(y-cy)*.72);ctx.strokeStyle=ac('CONSTRUCT',.04+.12*L.u.Phi);ctx.stroke()}}}
 }else if(mode==='TRAVERSAL'){
  for(let k=-3;k<=3;k++){ctx.beginPath();for(let i=0;i<=70;i++){const u=i/70,x=cx-R+u*R*2,y=cy+k*R*.055+Math.sin(u*TAU*1.7+t*.32+k)*R*.055*(.5+L.routeStrength);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=ac(k===0?'OMEGA':'CONSTRUCT',k===0?.48:.06+.06*(4-Math.abs(k)));ctx.lineWidth=k===0?2.6:1;ctx.stroke()}
 }else if(mode==='FORECAST'){
  for(let b=-6;b<=6;b++){ctx.beginPath();ctx.moveTo(cx-R*.72,cy);for(let i=1;i<=44;i++){const u=i/44,x=cx-R*.72+u*R*1.52,y=cy+b*R*.055*Math.pow(u,1.25)+Math.sin(u*8+b+t*.28)*R*.018;ctx.lineTo(x,y)}ctx.strokeStyle=ac(b===0?'OMEGA':'ALPHA',b===0?.45:.035+.12*(1-Math.abs(b)/7));ctx.lineWidth=b===0?2.2:1;ctx.stroke()}
 }else if(mode==='RELATIVITY'){
  const shift=R*.12*Math.sin(t*.22);for(let i=1;i<=7;i++){const q=i/7;ctx.beginPath();ctx.ellipse(cx-shift*q,cy,R*q*1.18*observer.compression,R*q*.58,t*.035,0,TAU);ctx.strokeStyle=ac('BASE',.04+.14*(1-q));ctx.stroke();ctx.beginPath();ctx.ellipse(cx+shift*q,cy,R*q*.78,R*q*.88/Math.max(.7,observer.compression),-t*.028,0,TAU);ctx.strokeStyle=ac('OMEGA',.035+.12*(1-q));ctx.stroke()}
 }else if(mode==='INFINITY'){
  for(let i=0;i<13;i++){const q=(i+1)/13,rr=R*(.12+.72*q),off=R*.05*q;ctx.beginPath();ctx.arc(cx+Math.cos(t*.04+i*.48)*off,cy+Math.sin(t*.04+i*.48)*off,rr,0,TAU*(.68+.025*i));ctx.strokeStyle=ac(i%3===0?'OMEGA':'PRUNE',.035+.16*(1-q));ctx.stroke()}
 }else if(mode==='SCALE'){
  for(let i=1;i<=8;i++){const q=i/8,w=R*1.55*q,h=R*.98*q;ctx.save();ctx.translate(cx,cy);ctx.rotate((i-4)*.035+t*.006*(i%2?1:-1));ctx.strokeStyle=ac(i%2?'BASE':'OMEGA',.035+.16*(1-q));ctx.strokeRect(-w/2,-h/2,w,h);ctx.restore()}
 }else if(mode==='CONVERGENCE'){
  for(let b=0;b<16;b++){const a=b*TAU/16+t*.018*(b%2?1:-1);ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R*.72);ctx.quadraticCurveTo(cx+Math.cos(a+.8)*R*.35,cy+Math.sin(a+.8)*R*.22,cx,cy);ctx.strokeStyle=ac(b%4===0?'OMEGA':'PRUNE',.04+.16*L.routeStrength);ctx.stroke()}
 }else{
  for(let i=1;i<=5;i++){ctx.beginPath();ctx.arc(cx,cy,R*(.18+i*.14),0,TAU);ctx.strokeStyle=ac(ROLES[(i-1)%5],.025+.07*L.operatorWeights[ROLES[(i-1)%5]]);ctx.stroke()}
 }
 ctx.restore();
}
export default function CalculusFieldR37({address,mode='FIELD',steps=24,onAddress,label,observerBeta=0}:Props){const ref=useRef<HTMLCanvasElement|null>(null),projectedRef=useRef<Array<{address:number;x:number;y:number}>>([]),route=useMemo(()=>routeFrom(address,Math.max(6,Math.min(48,steps))),[address,steps]),records=useMemo(()=>route.map(corpusState),[route]),laws=useMemo(()=>records.map(calculusVisualLaw),[records]),g=modeGains(mode),observer=observerProjection(mode,observerBeta),law=laws[0],coords=decodeAddress(address);
 useEffect(()=>{const canvas=ref.current;if(!canvas||!laws.length)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,alive=true;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const draw=(now:number)=>{if(!alive)return;const box=canvas.getBoundingClientRect(),dpr=Math.min(1.65,window.devicePixelRatio||1),W=Math.max(320,Math.round(box.width)),H=Math.max(360,Math.round(box.height));if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const L=laws[0],t=reduce?0:now*.001*L.phaseSpeed*observer.doppler,cx=W*.5,cy=H*.48,R=Math.min(W,H)*.34,obsX=.72+.28*observer.compression,obsDepth=1+.22*(observer.gamma-1);
 ctx.fillStyle='rgb(2,7,10)';ctx.fillRect(0,0,W,H);const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,R*1.55);glow.addColorStop(0,'rgba(18,31,38,.38)');glow.addColorStop(.55,'rgba(6,14,19,.28)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
 drawProjectionSignatureR82(ctx,mode,L,t,cx,cy,R,observer);
  ROLES.forEach((role,i)=>{const w=L.operatorWeights[role],rawA=-Math.PI/2+i*TAU/5+t*.05*(i%2?1:-1),a0=aberrateAngle(rawA,observer.beta),a1=aberrateAngle(rawA+TAU*(.11+.055*w),observer.beta),rr=R*(.58+i*.075);ctx.beginPath();ctx.ellipse(cx,cy,rr*obsX,rr,a0*.06,a0,a1);ctx.strokeStyle=operatorColor(L,role,.34+.5*w);ctx.lineWidth=3+8*w;ctx.lineCap='round';ctx.stroke();ctx.lineCap='butt'});
 for(let s=L.shellCount;s>=1;s--){const k=s/L.shellCount,rr=R*(.18+.82*k)*g.radial,ecc=(1+L.shellEccentricity*.34*g.depth)*obsX,flat=(.66+.18*(1-L.fold*g.fold))*obsDepth,rawRot=t*L.shellPrecession*(s%2?-1:1)+L.phaseAngle*.12+s*.13,rot=aberrateAngle(rawRot,observer.beta),role=ROLES[(s+Math.floor(L.phase01*5))%5];ctx.beginPath();ctx.ellipse(cx,cy,rr*ecc,rr*flat,rot,0,TAU);ctx.strokeStyle=operatorColor(L,role,.05+.18*L.operatorWeights[role]*k);ctx.lineWidth=.55+1.1*L.u.light.coherence*k;ctx.stroke()}
 const densityMultiplier=mode==='MATTER'?.72:(mode==='FIELD'?.58:.68),count=Math.min(2200,Math.max(320,Math.round(L.density*densityMultiplier)));for(let i=0;i<count;i++){const h=Math.sin((address+1)*.013+i*12.9898)*43758.5453,u=Math.abs(h%1),v=Math.abs((Math.sin(i*78.233+address*.017)*24634.6345)%1),w=Math.abs((Math.sin(i*31.117+address*.011)*9758.132)%1),z=w*2-1,baseRaw=u*TAU+t*(.18+.6*L.u.motionRelativity),baseA=aberrateAngle(baseRaw,observer.beta),scarWarp=Math.sin(baseA*(2.4+L.fold*4.2)+i*.021-t*L.pulseRate)*L.scarMemory*.28,curv=L.curvature*g.fold*Math.sin(baseA*2+L.phaseAngle),a=baseA+scarWarp+curv,r=R*Math.pow(v,.6)*(.28+.63*L.u.Phi)*g.radial,pers=.72+.28*(z+1)/2*L.perspectiveGain*g.depth*obsDepth,x=cx+Math.cos(a)*r*(1+.34*L.u.shape.anisotropy)*pers*obsX,y=cy+Math.sin(a)*r*(.62+.2*L.u.shape.symmetry)*pers+z*R*.2*L.depthGain*g.depth*obsDepth,role=weightedRole(L,u*.53+v*.29+w*.18+L.phase01*.21),alpha=(.12+.5*pers)*(.5+.5*L.u.evidence)*(.58+.42*L.operatorWeights[role]);ctx.fillStyle=operatorColor(L,role,alpha);ctx.beginPath();ctx.arc(x,y,.55+L.pointRadius*(.18+.34*pers),0,TAU);ctx.fill()}
 const routePoints=route.map((a,i)=>{const rl=laws[i],age=i/Math.max(1,route.length-1),rawAng=rl.phaseAngle+t*.1+i*(.21+.42*L.branchSpread*g.spread),ang=aberrateAngle(rawAng,observer.beta),rad=R*(.12+.66*age),x=cx+Math.cos(ang)*rad*(1+.24*rl.u.shape.anisotropy)*obsX,y=cy+Math.sin(ang)*rad*.7*obsDepth+Math.sin(ang*1.7+i*.31)*R*.08*rl.depthGain*g.depth*obsDepth,role=(i===0?'BASE':i===route.length-1?'OMEGA':ROLES[(i+2)%5]) as OperatorColorRole,persist=(1-age)*L.trailPersistence,rr=i===0?8:i===route.length-1?6:2.6;return{address:a,rl,x,y,role,persist,rr}});
 projectedRef.current=routePoints.map(p=>({address:p.address,x:p.x,y:p.y}));
 if(routePoints.length>1){for(let i=0;i<routePoints.length-1;i++){const a=routePoints[i],b=routePoints[i+1],samples=7;for(let j=1;j<samples;j++){const u=j/samples,x=a.x+(b.x-a.x)*u,y=a.y+(b.y-a.y)*u,fade=(1-u)*a.persist+u*b.persist;ctx.beginPath();ctx.arc(x,y,.7+1.4*L.routeStrength,0,TAU);ctx.fillStyle=lawColor(L,'proof',.05+.19*fade);ctx.fill()}}}
 routePoints.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,p.rr,0,TAU);ctx.fillStyle=operatorColor(p.rl,p.role,i===0||i===routePoints.length-1?.98:.42+.34*p.persist);ctx.fill();if(i%2===0||i===routePoints.length-1){ctx.beginPath();ctx.arc(p.x,p.y,p.rr+5+8*p.persist,0,TAU);ctx.strokeStyle=lawColor(p.rl,'proof',.06+.2*p.persist+.12*p.rl.proofGlow);ctx.lineWidth=.6+p.persist;ctx.stroke()}});
 const travel=(t*.34)%Math.max(1,route.length-1),idx=Math.min(Math.max(0,route.length-2),Math.floor(travel)),uu=travel-idx,aLaw=laws[idx]||L,bLaw=laws[idx+1]||aLaw,tg=transitionGeometry(aLaw,bLaw,uu),p0=routePoints[idx]||routePoints[0],p1=routePoints[idx+1]||p0,mx=p0?p0.x+(p1.x-p0.x)*uu:cx,my=p0?p0.y+(p1.y-p0.y)*uu:cy,travelRole=ROLES[(idx+Math.floor(uu*5))%5];ctx.fillStyle=operatorColor(aLaw,travelRole,.98);ctx.beginPath();ctx.arc(mx,my,4.5+4*tg.route,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(mx,my,11+10*tg.fold,0,TAU);ctx.strokeStyle=operatorColor(bLaw,ROLES[(ROLES.indexOf(travelRole)+1)%5],.28+.36*tg.trail);ctx.stroke();
 ctx.beginPath();ctx.arc(cx,cy,18+10*L.u.C,0,TAU);ctx.fillStyle='rgba(5,12,17,.92)';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=operatorColor(L,'BASE',.92);ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,24+12*L.proofGlow,0,TAU);ctx.strokeStyle=lawColor(L,'proof',.34+.36*L.proofGlow);ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,7+8*L.proofGlow,0,TAU);ctx.fillStyle=operatorColor(L,'OMEGA',.92);ctx.fill();
 const projectionMeta=projectionForR82(mode);ctx.font='700 10px ui-monospace,monospace';ctx.fillStyle='rgba(230,239,238,.9)';ctx.fillText(`${label||mode} · STATE ${records[0].stateId} · ${L.modeDecision}`,14,22);ctx.font='7px ui-monospace,monospace';ctx.fillStyle='rgba(213,183,105,.78)';ctx.fillText(`${projectionMeta.signature.toUpperCase()} · ${projectionMeta.intent}`,14,H-14);ctx.font='8px ui-monospace,monospace';ctx.fillStyle='rgba(153,177,180,.72)';ctx.fillText(`HERE → ${records[1]?.stateId||records[0].stateId} → … → ${records.at(-1)?.stateId||records[0].stateId}`,14,38);if(mode==='RELATIVITY'){ctx.fillStyle='rgba(224,205,156,.82)';ctx.fillText(`OBSERVER β ${observer.beta.toFixed(2)} · γ ${observer.gamma.toFixed(3)} · Doppler ${observer.doppler.toFixed(3)} · projection only`,14,54)}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[address,mode,route,records,laws,g.radial,g.depth,g.fold,g.spread,label,observer.beta,observer.gamma,observer.doppler,observer.compression]);
 const pick=(e:React.MouseEvent<HTMLCanvasElement>)=>{if(!onAddress)return;const b=e.currentTarget.getBoundingClientRect(),mx=e.clientX-b.left,my=e.clientY-b.top,points=projectedRef.current;if(!points.length)return;let best=points[0].address,dist=Infinity;for(const p of points){const d=(p.x-mx)**2+(p.y-my)**2;if(d<dist){dist=d;best=p.address}}const threshold=Math.max(30,Math.min(b.width,b.height)*.055);if(dist<=threshold*threshold)onAddress(best)};
 return <section className='calculus-field-r37' data-color-authority='ALPHA BASE CONSTRUCT PRUNE OMEGA' data-observer-beta={mode==='RELATIVITY'?observer.beta.toFixed(2):'0.00'}><div className='cfr37-stage'><canvas ref={ref} onClick={pick} aria-label={`${mode} calculus-driven field for state ${address+1}`}/><div className='cfr37-operator-key'>{ROLES.map(role=><span key={role} style={{'--role-color':operatorColor(law,role,.95)} as React.CSSProperties}><i/><b>{role}</b><small>{ROLE_NOTE[role]}</small></span>)}</div></div><div className='cfr37-summary'><div><span>STATE</span><b>{records[0].stateId}</b><small>D{coords.d+1} · P{coords.p+1} · R{coords.r+1} · L{coords.l+1}</small></div><div><span>ROUTE</span><b>{records[0].stateId} → {records[1]?.stateId||records[0].stateId}</b><small>{route.length-1} admitted transitions</small></div><div><span>{mode==='RELATIVITY'?'OBSERVER':'DECISION'}</span><b>{mode==='RELATIVITY'?`β ${observer.beta.toFixed(2)} · γ ${observer.gamma.toFixed(2)}`:law.modeDecision}</b><small>{mode==='RELATIVITY'?`Doppler ${observer.doppler.toFixed(3)} · projection, not canonical state`:`proof ${law.u.evidence.toFixed(3)} · route ${law.routeStrength.toFixed(3)}`}</small></div></div><div className='cfr37-weights'>{ROLES.map(role=><div key={role}><span>{role}</span><i><em style={{width:`${Math.round(law.operatorWeights[role]*100)}%`,background:operatorColor(law,role,.9)}}/></i><b>{law.operatorWeights[role].toFixed(2)}</b></div>)}</div><div className='cfr37-law'><span>CΩ <b>{law.u.C.toFixed(3)}</b></span><span>Φ <b>{law.u.Phi.toFixed(3)}</b></span><span>q <b>{law.u.q.toFixed(3)}</b></span><span>Λ <b>{law.u.Lambda.toFixed(3)}</b></span><span>scar <b>{law.u.scar.toFixed(3)}</b></span><span>conductance <b>{law.u.water.conductance.toFixed(3)}</b></span><span>motion <b>{law.u.motionRelativity.toFixed(3)}</b></span><span>curvature <b>{law.curvature.toFixed(3)}</b></span><span>trail <b>{law.trailPersistence.toFixed(3)}</b></span><span>branch <b>{law.branchSpread.toFixed(3)}</b></span></div></section>}
