import {useEffect,useMemo,useRef} from 'react';
import {corpusState,decodeAddress} from './corpusRuntime';
import {calculusVisualLaw,lawColor,operatorColor,transitionGeometry,type OperatorColorRole} from './calculusVisualLawR37';
import './calculusFieldR37.css';
type Mode='FIELD'|'MATTER'|'TRAVERSAL'|'FORECAST'|'RELATIVITY'|'INFINITY'|'SCALE'|'CONVERGENCE';
type Props={address:number;mode?:Mode;steps?:number;onAddress?:(n:number)=>void;label?:string};
const clampAddr=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0))),TAU=Math.PI*2,ROLES:OperatorColorRole[]=['ALPHA','BASE','CONSTRUCT','PRUNE','OMEGA'];
const ROLE_NOTE:Record<OperatorColorRole,string>={ALPHA:'possibility / phase opening',BASE:'evidence / continuity anchor',CONSTRUCT:'outverse growth / motion',PRUNE:'contradiction / inverse pressure',OMEGA:'coherence / closure'};
function routeFrom(address:number,steps:number){const out:number[]=[];let a=clampAddr(address);for(let i=0;i<steps;i++){out.push(a);const n=corpusState(a).autoPing?.dataNext;a=Number.isFinite(n)?clampAddr(n):a}return out}
function modeGains(mode:Mode){switch(mode){case'MATTER':return{radial:1.0,depth:1.16,fold:1.22,spread:.82,recurrence:.78};case'TRAVERSAL':return{radial:.98,depth:1.06,fold:.9,spread:1.2,recurrence:.9};case'FORECAST':return{radial:1,depth:.92,fold:.78,spread:1.5,recurrence:.64};case'RELATIVITY':return{radial:.92,depth:1.32,fold:1.05,spread:1.02,recurrence:.86};case'INFINITY':return{radial:1.04,depth:1.02,fold:1.14,spread:.94,recurrence:1.46};case'SCALE':return{radial:.94,depth:1.2,fold:1.28,spread:.82,recurrence:1.18};case'CONVERGENCE':return{radial:.94,depth:1,fold:1.16,spread:.68,recurrence:.94};default:return{radial:1,depth:1,fold:1,spread:1,recurrence:1}}}
function weightedRole(law:any,u:number){let total=0;const weighted=ROLES.map(r=>{const w=.08+Number(law.operatorWeights?.[r]||0);total+=w;return[r,w] as const});let p=((u%1)+1)%1*total;for(const[r,w]of weighted){p-=w;if(p<=0)return r}return'OMEGA' as OperatorColorRole}
export default function CalculusFieldR37({address,mode='FIELD',steps=24,onAddress,label}:Props){const ref=useRef<HTMLCanvasElement|null>(null),route=useMemo(()=>routeFrom(address,Math.max(6,Math.min(48,steps))),[address,steps]),records=useMemo(()=>route.map(corpusState),[route]),laws=useMemo(()=>records.map(calculusVisualLaw),[records]),g=modeGains(mode),law=laws[0],coords=decodeAddress(address);
 useEffect(()=>{const canvas=ref.current;if(!canvas||!laws.length)return;const ctx=canvas.getContext('2d');if(!ctx)return;let raf=0,alive=true;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const draw=(now:number)=>{if(!alive)return;const box=canvas.getBoundingClientRect(),dpr=Math.min(1.65,window.devicePixelRatio||1),W=Math.max(320,Math.round(box.width)),H=Math.max(360,Math.round(box.height));if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const L=laws[0],t=reduce?0:now*.001*L.phaseSpeed,cx=W*.5,cy=H*.48,R=Math.min(W,H)*.34;
 ctx.fillStyle='rgb(2,7,10)';ctx.fillRect(0,0,W,H);const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,R*1.55);glow.addColorStop(0,'rgba(18,31,38,.38)');glow.addColorStop(.55,'rgba(6,14,19,.28)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
 ROLES.forEach((role,i)=>{const w=L.operatorWeights[role],a0=-Math.PI/2+i*TAU/5+t*.05*(i%2?1:-1),a1=a0+TAU*(.11+.055*w),rr=R*(.58+i*.075);ctx.beginPath();ctx.arc(cx,cy,rr,a0,a1);ctx.strokeStyle=operatorColor(L,role,.34+.5*w);ctx.lineWidth=3+8*w;ctx.lineCap='round';ctx.stroke();ctx.lineCap='butt'});
 for(let s=L.shellCount;s>=1;s--){const k=s/L.shellCount,rr=R*(.18+.82*k)*g.radial,ecc=1+L.shellEccentricity*.34*g.depth,flat=.66+.18*(1-L.fold*g.fold),rot=t*L.shellPrecession*(s%2?-1:1)+L.phaseAngle*.12+s*.13,role=ROLES[(s+Math.floor(L.phase01*5))%5];ctx.beginPath();ctx.ellipse(cx,cy,rr*ecc,rr*flat,rot,0,TAU);ctx.strokeStyle=operatorColor(L,role,.05+.18*L.operatorWeights[role]*k);ctx.lineWidth=.55+1.1*L.u.light.coherence*k;ctx.stroke()}
 const densityMultiplier=mode==='MATTER'?.72:(mode==='FIELD'?.58:.68),count=Math.min(2200,Math.max(320,Math.round(L.density*densityMultiplier)));for(let i=0;i<count;i++){const h=Math.sin((address+1)*.013+i*12.9898)*43758.5453,u=Math.abs(h%1),v=Math.abs((Math.sin(i*78.233+address*.017)*24634.6345)%1),w=Math.abs((Math.sin(i*31.117+address*.011)*9758.132)%1),z=w*2-1,baseA=u*TAU+t*(.18+.6*L.u.motionRelativity),scarWarp=Math.sin(baseA*(2.4+L.fold*4.2)+i*.021-t*L.pulseRate)*L.scarMemory*.28,curv=L.curvature*g.fold*Math.sin(baseA*2+L.phaseAngle),a=baseA+scarWarp+curv,r=R*Math.pow(v,.6)*(.28+.63*L.u.Phi)*g.radial,pers=.72+.28*(z+1)/2*L.perspectiveGain*g.depth,x=cx+Math.cos(a)*r*(1+.34*L.u.shape.anisotropy)*pers,y=cy+Math.sin(a)*r*(.62+.2*L.u.shape.symmetry)*pers+z*R*.2*L.depthGain*g.depth,role=weightedRole(L,u*.53+v*.29+w*.18+L.phase01*.21),alpha=(.12+.5*pers)*(.5+.5*L.u.evidence)*(.58+.42*L.operatorWeights[role]);ctx.fillStyle=operatorColor(L,role,alpha);ctx.beginPath();ctx.arc(x,y,.55+L.pointRadius*(.18+.34*pers),0,TAU);ctx.fill()}
 ctx.beginPath();route.forEach((a,i)=>{const rl=laws[i],age=i/Math.max(1,route.length-1),ang=rl.phaseAngle+t*.1+i*(.21+.42*L.branchSpread*g.spread),rad=R*(.12+.66*age),x=cx+Math.cos(ang)*rad*(1+.24*rl.u.shape.anisotropy),y=cy+Math.sin(ang)*rad*.7+Math.sin(ang*1.7+i*.31)*R*.08*rl.depthGain*g.depth;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.strokeStyle=operatorColor(L,'BASE',.32+.38*L.routeStrength);ctx.lineWidth=1.4+2.8*L.routeStrength;ctx.stroke();ctx.beginPath();route.forEach((a,i)=>{const rl=laws[i],age=i/Math.max(1,route.length-1),ang=rl.phaseAngle+t*.1+i*(.21+.42*L.branchSpread*g.spread),rad=R*(.12+.66*age),x=cx+Math.cos(ang)*rad*(1+.24*rl.u.shape.anisotropy),y=cy+Math.sin(ang)*rad*.7+Math.sin(ang*1.7+i*.31)*R*.08*rl.depthGain*g.depth;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.strokeStyle=lawColor(L,'proof',.18+.24*L.proofGlow);ctx.lineWidth=.75+L.proofGlow;ctx.stroke();route.forEach((a,i)=>{const rl=laws[i],age=i/Math.max(1,route.length-1),ang=rl.phaseAngle+t*.1+i*(.21+.42*L.branchSpread*g.spread),rad=R*(.12+.66*age),x=cx+Math.cos(ang)*rad*(1+.24*rl.u.shape.anisotropy),y=cy+Math.sin(ang)*rad*.7+Math.sin(ang*1.7+i*.31)*R*.08*rl.depthGain*g.depth,role=i===0?'BASE':i===route.length-1?'OMEGA':ROLES[(i+2)%5];ctx.fillStyle=operatorColor(rl,role as OperatorColorRole,i===0||i===route.length-1?.98:.58);ctx.beginPath();ctx.arc(x,y,i===0?8:i===route.length-1?6:2.6,0,TAU);ctx.fill()});
 const travel=(t*.34)%Math.max(1,route.length-1),idx=Math.min(route.length-2,Math.floor(travel)),uu=travel-idx,aLaw=laws[idx],bLaw=laws[idx+1]||aLaw,tg=transitionGeometry(aLaw,bLaw,uu),ang=tg.phase+t*.08+idx*.28,rad=R*(.14+.58*((idx+uu)/Math.max(1,route.length-1))),mx=cx+Math.cos(ang)*rad*(1+.3*tg.curvature),my=cy+Math.sin(ang)*rad*.68+Math.sin(ang*2)*R*.07*tg.depth,travelRole=ROLES[(idx+Math.floor(uu*5))%5];ctx.fillStyle=operatorColor(aLaw,travelRole,.98);ctx.beginPath();ctx.arc(mx,my,4.5+4*tg.route,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(mx,my,11+10*tg.fold,0,TAU);ctx.strokeStyle=operatorColor(bLaw,ROLES[(ROLES.indexOf(travelRole)+1)%5],.28+.36*tg.trail);ctx.stroke();
 ctx.beginPath();ctx.arc(cx,cy,18+10*L.u.C,0,TAU);ctx.fillStyle='rgba(5,12,17,.92)';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=operatorColor(L,'BASE',.92);ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,24+12*L.proofGlow,0,TAU);ctx.strokeStyle=lawColor(L,'proof',.34+.36*L.proofGlow);ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,7+8*L.proofGlow,0,TAU);ctx.fillStyle=operatorColor(L,'OMEGA',.92);ctx.fill();
 ctx.font='700 10px ui-monospace,monospace';ctx.fillStyle='rgba(230,239,238,.9)';ctx.fillText(`${label||mode} · STATE ${records[0].stateId} · ${L.modeDecision}`,14,22);ctx.font='8px ui-monospace,monospace';ctx.fillStyle='rgba(153,177,180,.72)';ctx.fillText(`HERE → ${records[1]?.stateId||records[0].stateId} → … → ${records.at(-1)?.stateId||records[0].stateId}`,14,38);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[address,mode,route,records,laws,g.radial,g.depth,g.fold,g.spread,label]);
 const pick=(e:React.MouseEvent<HTMLCanvasElement>)=>{if(!onAddress)return;const b=e.currentTarget.getBoundingClientRect(),cx=b.width*.5,cy=b.height*.48,mx=e.clientX-b.left,my=e.clientY-b.top;let best=route[0],dist=Infinity;route.forEach((a,i)=>{const rl=laws[i],ang=rl.phaseAngle+i*(.21+.42*laws[0].branchSpread*g.spread),rad=Math.min(b.width,b.height)*.34*(.12+.66*(i/Math.max(1,route.length-1))),x=cx+Math.cos(ang)*rad,y=cy+Math.sin(ang)*rad*.7,d=(x-mx)**2+(y-my)**2;if(d<dist){dist=d;best=a}});onAddress(best)};
 return <section className='calculus-field-r37' data-color-authority='ALPHA BASE CONSTRUCT PRUNE OMEGA'><div className='cfr37-stage'><canvas ref={ref} onClick={pick} aria-label={`${mode} calculus-driven field for state ${address+1}`}/><div className='cfr37-operator-key'>{ROLES.map(role=><span key={role} style={{'--role-color':operatorColor(law,role,.95)} as React.CSSProperties}><i/><b>{role}</b><small>{ROLE_NOTE[role]}</small></span>)}</div></div><div className='cfr37-summary'><div><span>STATE</span><b>{records[0].stateId}</b><small>D{coords.d+1} · P{coords.p+1} · R{coords.r+1} · L{coords.l+1}</small></div><div><span>ROUTE</span><b>{records[0].stateId} → {records[1]?.stateId||records[0].stateId}</b><small>{route.length-1} admitted transitions</small></div><div><span>DECISION</span><b>{law.modeDecision}</b><small>proof {law.u.evidence.toFixed(3)} · route {law.routeStrength.toFixed(3)}</small></div></div><div className='cfr37-weights'>{ROLES.map(role=><div key={role}><span>{role}</span><i><em style={{width:`${Math.round(law.operatorWeights[role]*100)}%`,background:operatorColor(law,role,.9)}}/></i><b>{law.operatorWeights[role].toFixed(2)}</b></div>)}</div><div className='cfr37-law'><span>CΩ <b>{law.u.C.toFixed(3)}</b></span><span>Φ <b>{law.u.Phi.toFixed(3)}</b></span><span>q <b>{law.u.q.toFixed(3)}</b></span><span>Λ <b>{law.u.Lambda.toFixed(3)}</b></span><span>scar <b>{law.u.scar.toFixed(3)}</b></span><span>conductance <b>{law.u.water.conductance.toFixed(3)}</b></span><span>motion <b>{law.u.motionRelativity.toFixed(3)}</b></span><span>curvature <b>{law.curvature.toFixed(3)}</b></span></div></section>}
