import {useMemo,useState} from 'react';
import {GitBranch,ShieldCheck,CheckCircle2,PauseCircle,RotateCcw} from 'lucide-react';
import {CANON_DONOR_BOUNDARY,CANON_STAGES,admitCanonProposal,canonStageTelemetry,compileCanonProposal,type CanonProposal} from './canonGovernanceRuntime';
import {localState} from './platformAdapter';
import './canonGovernance.css';
export default function CanonGovernanceControl({record,evolution=false}:{record:any;evolution?:boolean}){
 const key='omega.v6.canon.v24.proposals',[rows,setRows]=useState<CanonProposal[]>(()=>localState.read(key,[])),[text,setText]=useState(''),selected=rows[rows.length-1]||null,telemetry=useMemo(()=>selected?canonStageTelemetry(selected):[],[selected]);
 const persist=(next:CanonProposal[])=>{setRows(next);localState.write(key,next)};
 const compile=()=>{if(!text.trim())return;persist([...rows,compileCanonProposal(text,record,(selected?.revision||0)+1)]);setText('')};
 const admit=()=>{if(!selected)return;persist(rows.map(x=>x.id===selected.id?admitCanonProposal(x,true):x))};
 return <section className='special-app canon-v24-app'><header className='special-head'><div><span>CANONCONSOLE OMEGA v24 · SINGLE CANONICALSTATE</span><h2>{evolution?'Canon Evolution':'Governance'}</h2></div><strong>{selected?.status||'NO CANDIDATE'}</strong></header><div className='canon-v24-spine'>{CANON_STAGES.map((s,i)=><div key={s} className={selected?'active':''}><i>{i+1}</i><span>{s.replaceAll('_',' ')}</span></div>)}</div><div className='canon-v24-grid'><article><h3>Candidate law / operator refinement</h3><textarea value={text} onChange={e=>setText(e.target.value)} placeholder='Describe the candidate change to evaluate against the current canonical state…'/><div className='canon-v24-actions'><button onClick={compile} disabled={!text.trim()}><GitBranch/>Compile candidate</button><button onClick={admit} disabled={!selected||selected.status==='REJECTED'}><CheckCircle2/>Explicit admit</button></div><p className='canon-boundary'><ShieldCheck/>{CANON_DONOR_BOUNDARY}</p></article><article>{selected?<><div className='canon-token'><span>BASE STATE</span><b>{selected.baseState}</b><code>{selected.parentHash} → {selected.candidateHash}</code></div><div className='canon-metrics'>{[['PROOF',selected.proofScore],['CONSENSUS',selected.consensusScore],['REPLAY',selected.replayScore],['CAL ERROR',selected.calibrationError]].map(([n,v])=><div key={String(n)}><span>{n}</span><b>{Number(v).toFixed(3)}</b><i style={{width:`${Math.max(3,Number(v)*100)}%`}}/></div>)}</div><div className='canon-corridor'><RotateCcw/><span>SELECTED CORRIDOR</span><b>{selected.selectedCorridor}</b></div></>:<div className='canon-empty'><PauseCircle/><b>No candidate compiled</b><span>The canonical runtime remains unchanged.</span></div>}</article></div>{selected&&<><div className='canon-stage-telemetry'>{telemetry.map(x=><div key={x.stage}><span>{x.index}</span><b>{x.stage.replaceAll('_',' ')}</b><i style={{width:`${x.score*100}%`}}/><small>{x.score.toFixed(3)} · {x.state}</small></div>)}</div><div className='canon-history'>{rows.slice().reverse().map(x=><article key={x.id}><code>r{x.revision} · STATE {x.baseState}</code><b>{x.text}</b><span className={x.status.toLowerCase()}>{x.status}</span></article>)}</div></>}</section>
}
