export const CANON_STAGES=['OBSERVATION','TRANSLATION','ATLAS_MAPPING','SEMANTIC_STATE','TRANSFORMATION_PROOF','FACE_CONSISTENCY','FACE_REPAIR','STEWARDSHIP','COUNTERFACTUAL_GOVERNANCE','MULTISTATE_ARBITRATION','FEDERATED_CONSENSUS','REPLAY_VALIDATION','GOVERNANCE_CALIBRATION'] as const;
export type CanonStage=typeof CANON_STAGES[number];
export type CanonProposalStatus='PROPOSED'|'HELD'|'ADMITTED'|'REJECTED';
export type CanonProposal={id:string;created:number;text:string;baseState:number;status:CanonProposalStatus;revision:number;parentHash:string;candidateHash:string;proofScore:number;consensusScore:number;replayScore:number;calibrationError:number;selectedCorridor:string;stage:CanonStage;notes:string[]};
const clamp=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};
const score=(seed:string,salt:number)=>clamp(((parseInt(hash(seed+':'+salt),16)%10000)/10000));
export function compileCanonProposal(text:string,record:any,revision=1):CanonProposal{
 const baseState=Number(record?.stateId||record?.address+1||1),metrics=record?.metrics||{},parentHash=hash(JSON.stringify({baseState,decision:metrics.decision,continuity:metrics.continuity,burden:metrics.burden,contradiction:metrics.contradiction,scar:metrics.scar})),seed=`${text}|${baseState}|${revision}|${parentHash}`;
 const proofScore=clamp(.44+.38*score(seed,5)+.18*Number(metrics.evidence||0)),consensusScore=clamp(.38+.42*score(seed,11)+.2*Number(metrics.continuity||0)),replayScore=clamp(.48+.34*score(seed,17)+.18*(1-Number(metrics.contradiction||0))),calibrationError=clamp(.08+.5*Number(metrics.contradiction||0)+.2*Number(metrics.burden||0)+.22*(1-score(seed,23)));
 const selectedCorridor=['STAY','TURN','ESCALATE'][Math.min(2,Math.floor(score(seed,29)*3))],candidateHash=hash(seed+':candidate');
 const admitted=proofScore>=.62&&consensusScore>=.58&&replayScore>=.62&&calibrationError<=.45;
 return {id:`canon-${candidateHash}`,created:Date.now(),text:text.trim(),baseState,status:admitted?'ADMITTED':'HELD',revision,parentHash,candidateHash,proofScore,consensusScore,replayScore,calibrationError,selectedCorridor,stage:'GOVERNANCE_CALIBRATION',notes:[`single CanonicalState base ${baseState}`,`parent ${parentHash}`,`candidate ${candidateHash}`,`corridor ${selectedCorridor}`,admitted?'candidate survives proof/consensus/replay/calibration gates':'candidate held; no canon mutation']};
}
export function canonStageTelemetry(proposal:CanonProposal){return CANON_STAGES.map((stage,i)=>{const progress=(i+1)/CANON_STAGES.length,base=clamp((proposal.proofScore+proposal.consensusScore+proposal.replayScore)/3);return {stage,index:i+1,score:clamp(base*(.72+.28*progress)-proposal.calibrationError*(1-progress)*.18),state:i===CANON_STAGES.length-1?proposal.status:'PROVED'}})}
export function admitCanonProposal(p:CanonProposal,explicit:boolean):CanonProposal{if(!explicit)return {...p,status:'HELD',notes:[...p.notes,'explicit admission required']};const survives=p.proofScore>=.62&&p.consensusScore>=.58&&p.replayScore>=.62&&p.calibrationError<=.45;return {...p,status:survives?'ADMITTED':'REJECTED',revision:p.revision+1,notes:[...p.notes,survives?'explicit admission recorded':'explicit admission rejected by proof gates']}}
export const CANON_DONOR_BOUNDARY='CanonConsoleOmega v24/v31r1 is a governance/canonical-state donor. It is not runtime authority; live webcam and Windows EXE behavior remain unverified in the donor evidence.';
