import {useEffect,useMemo,useRef} from 'react';
import {lineagePoint,type CompilerLineageId} from './compilerLineageRuntime';
import {compileDomainBands,compileRouteFlow,CONTINUOUS_FIELD_BOUNDARY} from './continuousFieldR13';
import {compileVectorCarryR113,VECTOR_CARRY_R113_BOUNDARY} from './vectorCarryR113';
import {applyCanvasResolutionR119,R119_RESOLUTION_BOUNDARY} from './renderResolutionR119';
import type {Mandala20736Field} from './mandala20736Runtime';
import './continuousFieldR13.css';
export default function ContinuousFieldOverlayR13({field,address,lineage,yaw,pitch,zoom}:{field:Mandala20736Field;address:number;lineage:CompilerLineageId;yaw:number;pitch:number;zoom:number}){const ref=useRef<HTMLCanvasElement|null>(null),bands=useMemo(()=>compileDomainBands(field),[field]),flow=useMemo(()=>compileRouteFlow(field,260),[field]),carry=useMemo(()=>compileVectorCarryR113(field,260,24),[field]);useEffect(()=>{const c=ref.current;if(!c)return;let raf=0,alive=true;const ctx=c.getContext('2d');if(!ctx)return;const project=(i:number,W:number,H:number)=>{const p=lineagePoint(field,i,lineage),cs=Math.cos(yaw),sn=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),xr=p.x*cs-p.z*sn,zr=p.x*sn+p.z*cs,yr=p.y*cp-zr*sp,z=zr*cp+p.y*sp,scale=Math.min(W,H)*.68*zoom,den=1.72-z*.48;return{x:W/2+xr*scale/den,y:H/2-yr*scale/den,z}};const draw=(now:number)=>{if(!alive)return;const r=c.getBoundingClientRect(),W=Math.max(300,Math.round(r.width)),H=Math.max(360,Math.round(r.height)),res=applyCanvasResolutionR119(c,W,H,'AUTO'),dpr=res.dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='rgba(1,4,6,.64)';ctx.fillRect(0,0,W,H);const cx=W*.5,cy=H*.51,base=Math.min(W,H)*.19,t=now*.00015;
ctx.save();ctx.translate(cx,cy);for(const b of bands){const ring=base*(.72+b.domain*.075),wave=Math.sin(t+b.phase)*(.018+.07*b.contradiction),rx=ring*(1+.13*b.outverse-.08*b.inverse+wave),ry=ring*(.62+.13*b.closure-.10*b.burden),shear=(b.contradiction-.25)*.16,rot=(b.phase*.08)+(b.domain-5.5)*.018;ctx.save();ctx.rotate(rot);ctx.transform(1,shear,-shear*.35,1,0,0);const alpha=.08+.30*b.evidence+.16*b.continuity;ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.lineWidth=1.1+4.2*b.closure;ctx.strokeStyle=`rgba(${Math.round(48+80*b.scar)},${Math.round(120+105*b.continuity)},${Math.round(126+100*b.plasticity)},${alpha})`;ctx.stroke();if(b.scar>.08){ctx.beginPath();ctx.ellipse(-rx*.08,ry*.04,rx*(.96-.12*b.scar),ry*(.94-.08*b.scar),0,Math.PI*.10,Math.PI*(.46+.32*b.scar));ctx.lineWidth=.8+3*b.scar;ctx.strokeStyle=`rgba(176,62,79,${.06+.34*b.scar})`;ctx.stroke()}ctx.beginPath();ctx.arc(rx*.06,0,Math.max(8,rx*.92),Math.PI*1.08,Math.PI*1.52);ctx.lineWidth=.7+2.5*b.outverse;ctx.strokeStyle=`rgba(216,92,72,${.04+.23*b.outverse*b.evidence})`;ctx.stroke();ctx.beginPath();ctx.arc(-rx*.04,0,Math.max(8,rx*.88),Math.PI*.06,Math.PI*.48);ctx.lineWidth=.7+2.5*b.inverse;ctx.strokeStyle=`rgba(78,128,205,${.04+.23*b.inverse*b.evidence})`;ctx.stroke();ctx.restore()}ctx.restore();
ctx.save();ctx.globalCompositeOperation='lighter';for(const s of flow){const a=project(s.from,W,H),b=project(s.to,W,H);if(!Number.isFinite(a.x+b.x+a.y+b.y))continue;const alpha=.025+.18*s.evidence*(.25+.75*s.continuity),bend=18*Math.sign(s.velocity||1)*(Math.abs(s.acceleration)*2+.15);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo((a.x+b.x)/2-bend,(a.y+b.y)/2+bend,b.x,b.y);ctx.lineWidth=.35+1.6*s.continuity+1.1*Math.abs(s.velocity);ctx.strokeStyle=s.contradiction>.28?`rgba(213,91,105,${alpha})`:`rgba(82,214,193,${alpha})`;ctx.stroke();if(s.scar>.35){ctx.setLineDash([2,5]);ctx.lineWidth=.5+1.5*s.scar;ctx.strokeStyle=`rgba(184,70,92,${.03+.14*s.scar})`;ctx.stroke();ctx.setLineDash([])}}ctx.restore();
ctx.save();ctx.globalCompositeOperation='screen';for(const s of carry.segments){const a=project(s.from,W,H),b=project(s.to,W,H);if(!Number.isFinite(a.x+b.x+a.y+b.y))continue;const p=s.primitives,bend=(s.orientation||1)*(6+34*s.turnPressure),mx=(a.x+b.x)/2-bend*s.turn.y,my=(a.y+b.y)/2+bend*s.turn.x,alpha=.025+.22*s.evidence*(.25+.75*p.ingress);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(mx,my,b.x,b.y);ctx.lineWidth=.35+2*p.ingress;ctx.strokeStyle=p.blocked>.28?`rgba(219,111,92,${alpha+.08*p.blocked})`:`rgba(103,225,199,${alpha})`;ctx.stroke();if(p.residue>.24){ctx.beginPath();ctx.arc(mx,my,1.2+4.8*p.residue,0,Math.PI*2);ctx.strokeStyle=`rgba(183,73,101,${.05+.26*p.residue})`;ctx.lineWidth=.6+1.8*p.residue;ctx.stroke()}if(s.turnPressure>.34){ctx.beginPath();ctx.moveTo(mx,my);ctx.lineTo(mx+s.turn.x*(8+18*s.turnPressure),my-s.turn.y*(8+18*s.turnPressure));ctx.strokeStyle=`rgba(244,201,119,${.10+.34*s.turnPressure})`;ctx.lineWidth=.7+1.4*s.turnPressure;ctx.stroke()}}
for(const basin of carry.basins){const p=project(basin.node,W,H);if(!Number.isFinite(p.x+p.y))continue;const pulse=.5+.5*Math.sin(t*8+basin.node*.017),rr=3+11*basin.score+3*pulse;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.strokeStyle=basin.admissible?`rgba(157,232,198,${.09+.28*basin.score})`:`rgba(210,151,104,${.05+.18*basin.score})`;ctx.lineWidth=.6+1.8*basin.score;ctx.stroke();if(basin.recirculationDepth>0){ctx.beginPath();ctx.arc(p.x,p.y,rr+3+basin.recirculationDepth*.35,0,Math.PI*2);ctx.setLineDash([2,4]);ctx.strokeStyle=`rgba(221,197,146,${.05+.15*basin.score})`;ctx.stroke();ctx.setLineDash([])}}ctx.restore();
const here=project(address,W,H),next=project(field.routeNext[address],W,H);ctx.beginPath();ctx.moveTo(here.x,here.y);ctx.quadraticCurveTo((here.x+next.x)/2-20,(here.y+next.y)/2-18,next.x,next.y);ctx.lineWidth=2.3;ctx.strokeStyle='rgba(245,215,153,.90)';ctx.stroke();ctx.beginPath();ctx.arc(here.x,here.y,5.2,0,Math.PI*2);ctx.fillStyle='rgba(255,235,188,.95)';ctx.fill();ctx.font='9px ui-monospace,monospace';ctx.fillStyle='rgba(170,190,190,.78)';ctx.fillText('VECTOR CARRY · INGRESS / EGRESS / BLOCKED / RESIDUE · TURN / BASIN · CΩ / Φ / q / Λ · R119',14,H-16);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[field,address,lineage,yaw,pitch,zoom,bands,flow,carry]);return <canvas ref={ref} className='continuous-field-r13' aria-label='Continuous OMEGA vector-carry state-field projection' data-resolution-authority='R119' title={`${CONTINUOUS_FIELD_BOUNDARY} ${VECTOR_CARRY_R113_BOUNDARY} ${R119_RESOLUTION_BOUNDARY}`}/>}
