import {category,fieldR2,initCorpusPack,isCorpusReady,meta,value} from './corpusPack';

export {initCorpusPack,isCorpusReady};
export const STATE_COUNT=20736;
export const VIEW_MODES=['SOURCE_COLOR','CONTINUITY','PHI','SCAR','INVERSE','PSC','MATH','DECISION'] as const;
export const PROJECTIONS=['LATTICE','MANDALA','INVERSE','THREAD'] as const;
export type ViewMode=typeof VIEW_MODES[number];
export type Projection=typeof PROJECTIONS[number];

const clampAddress=(a:number)=>Math.max(0,Math.min(STATE_COUNT-1,Math.floor(a)));
const cl=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
const mean=(...x:number[])=>x.reduce((a,b)=>a+(Number.isFinite(b)?b:0),0)/Math.max(1,x.length);
const norm=(x:number,min:number,max:number)=>cl((x-min)/(max-min||1));

export function encodeAddress(d:number,p:number,r:number,l:number){return 1728*d+144*p+12*r+l}
export function decodeAddress(a:number){const n=clampAddress(a),d=Math.floor(n/1728),r0=n%1728,p=Math.floor(r0/144),r1=r0%144,r=Math.floor(r1/12);return{d,p,r,l:r1%12}}
function range(field:string){const m=meta().models.find((x:any)=>x.f===field);return m?[m.min,m.max] as const:[0,1] as const}
function vn(a:number,field:string){const[mn,mx]=range(field);return norm(value(a,field),mn,mx)}
function structural(a:number){const c=decodeAddress(a);return{next:(a+1)%STATE_COUNT,previous:(a+STATE_COUNT-1)%STATE_COUNT,domainPlus:encodeAddress((c.d+1)%12,c.p,c.r,c.l),domainMinus:encodeAddress((c.d+11)%12,c.p,c.r,c.l),phasePlus:encodeAddress(c.d,(c.p+1)%12,c.r,c.l),phaseMinus:encodeAddress(c.d,(c.p+11)%12,c.r,c.l),regulationPlus:encodeAddress(c.d,c.p,(c.r+1)%12,c.l),regulationMinus:encodeAddress(c.d,c.p,(c.r+11)%12,c.l),layerPlus:encodeAddress(c.d,c.p,c.r,(c.l+1)%12),layerMinus:encodeAddress(c.d,c.p,c.r,(c.l+11)%12),hourglassMirror:encodeAddress(c.d,11-c.p,c.r,c.l),oppositeDomain:encodeAddress((c.d+6)%12,c.p,c.r,c.l),mode188Plus:(a+188)%STATE_COUNT}}
function routeAddress(a:number,decision:string,recoverability:number,pscGate:string,modeGate:string){const x=structural(a);if(decision==='STAY'&&pscGate==='STAY'&&modeGate!=='PRUNE')return x.next;if(decision==='TURN')return recoverability>=.62?x.phasePlus:x.regulationPlus;if(modeGate==='PRUNE')return x.oppositeDomain;if(pscGate!=='STAY')return x.hourglassMirror;return x.layerPlus}
function positiveNeighbors(a:number){const x=structural(a),cur=value(a,'phi.phi_recoverability'),ns=[x.domainPlus,x.domainMinus,x.phasePlus,x.phaseMinus,x.regulationPlus,x.regulationMinus,x.layerPlus,x.layerMinus];return ns.reduce((n,b)=>n+(value(b,'phi.phi_recoverability')>=cur?1:0),0)}
function inverseCoords(a:number){const th=value(a,'lae.theta'),ph=value(a,'lae.phi'),ready=mean(vn(a,'predict.reconstructability'),vn(a,'predict.compatibility')),rad=.15+.85*ready;return{x:Math.cos(th+ph*.5)*rad,y:Math.sin(ph-th*.35)*rad}}
function sourceGeometry(a:number){const row=Math.floor(a/144)+1,col=a%144+1,x=(col-72.5)/71.5,y=(72.5-row)/71.5,theta=value(a,'lae.theta'),phi=value(a,'lae.phi'),radius=vn(a,'predict.carry'),inv=inverseCoords(a),band=Math.max(1,Math.min(12,Math.ceil(mean(radius,vn(a,'predict.reconstructability'),vn(a,'math.normalized_motion_relativity'))*12))),shape=band<=2?'seed_core':band<=4?'constraint_transition':band<=6?'continuity_petal':band<=8?'carry_toroid':band<=10?'scar_compression':'inverse_rehost';return{x,y,radius,theta:((theta/(Math.PI*2))%1+1)%1,phi:((phi/(Math.PI*2))%1+1)%1,radialBand:`${String(band).padStart(2,'0')}_${shape}`,shape,symmetry:value(a,'geom.symmetry_value'),asymmetry:1-value(a,'geom.symmetry_value'),scar:vn(a,'psc.Scar_Score'),petal:vn(a,'predict.curvature'),toroid:vn(a,'predict.carry'),compression:vn(a,'psc.Compression_Ratio'),inverseReadiness:mean(vn(a,'predict.reconstructability'),vn(a,'predict.compatibility')),inverseX:inv.x,inverseY:inv.y}}

export function projectionPoint(address:number,projection:Projection,size=720){const a=clampAddress(address);if(projection==='LATTICE')return{x:((a%144)+.5)/144*size,y:(Math.floor(a/144)+.5)/144*size};if(projection==='THREAD')return{x:(.04+.92*vn(a,'phi.phi_recoverability'))*size,y:(.04+.92*((a%188)/187))*size};if(projection==='INVERSE'){const q=inverseCoords(a);return{x:size/2+q.x*size*.43,y:size/2-q.y*size*.43}}const th=value(a,'lae.theta')+.24*Math.sin(value(a,'lae.phi')*2),rad=(.06+.91*vn(a,'predict.carry'))*size*.46;return{x:size/2+Math.cos(th)*rad,y:size/2+Math.sin(th)*rad}}

export function corpusState(address:number){
  const M=meta(),A=M.axes,a=clampAddress(address),c=decodeAddress(a),g=sourceGeometry(a);
  const decision=category(a,'predict.decision'),modeGate=category(a,'predict.mode188_gate'),pscGate=category(a,'psc.Gate');
  const C=value(a,'predict.continuity'),Phi=value(a,'phi.phi_recoverability'),q=value(a,'predict.contradiction_q'),burden=value(a,'predict.ledger_burden'),evidence=value(a,'identity.Evidence_Weight'),S=(C*Phi)/(q+burden+1e-9),prev=(a+STATE_COUNT-1)%STATE_COUNT,phiDelta=Phi-value(prev,'phi.phi_recoverability');
  const predict={domain:A.predict.domains[c.d],phase:A.predict.phases[c.p],regulation:A.predict.regulations[c.r],layer:A.predict.layers[c.l],decision,stability:S,continuity:C,burden,contradiction:q,compatibility:value(a,'predict.compatibility'),carry:value(a,'predict.carry'),reconstructability:value(a,'predict.reconstructability'),dOmega:value(a,'predict.D_omega'),integralCarry:value(a,'predict.integral_carry'),curvature:value(a,'predict.curvature'),forecastScore:value(a,'predict.S_hat')};
  const phi={raw:Phi,recoverability:Phi,positiveNeighbors:positiveNeighbors(a),dPhi:phiDelta,sPhi:S,className:category(a,'phi.phi_class')};
  const identity={parent:A.identity.parents[c.d],frame:A.identity.frames[c.p],operator:A.identity.operators[c.r],operatorSymbol:A.identity.operatorSymbols[c.r],transition:A.identity.transitions[c.l],autoPingState:decision,evidenceClass:category(a,'identity.Evidence_Class'),claimLevel:category(a,'identity.Claim_Level'),discoveryStatus:category(a,'identity.Discovery_Status'),returnOrder:decision==='STAY'?Math.max(1,11-c.d):Math.min(12,13-c.d),evidenceWeight:evidence,futurePlasticity:Phi,burden,contradiction:q,uncertainty:1-evidence,continuity:C,deweyScore:S,weakestLink:Math.min(C,Phi,1-q,1-burden,evidence)};
  const math={earthDomain:A.math.earthDomains[c.d],earthSubfield:A.math.earthSubfields[c.p],motionDomain:A.math.motionDomains[c.r],motionSubfield:A.math.motionSubfields[c.l],shapeResponse:value(a,'math.shape_response'),motionRelativity:value(a,'math.motion_relativity_index'),normalizedMotionRelativity:value(a,'math.normalized_motion_relativity'),autoPingGain:value(a,'math.normalized_auto_ping_gain'),predictedState:category(a,'math.predicted_state')};
  const psc={domain:A.psc.domains[c.d],pattern:A.psc.patterns[c.d*12+c.p],parentRoot:A.psc.roots[c.r],operator:A.psc.operators[c.l],operatorSymbol:A.psc.operatorSymbols[c.l],parentScore:value(a,'psc.Parent_Score'),accumulationScore:value(a,'psc.Accumulation_Score'),constraintScore:value(a,'psc.Constraint_Score'),scarScore:value(a,'psc.Scar_Score'),phaseScore:value(a,'psc.Phase_Score'),continuityScore:value(a,'psc.Continuity_Score'),motionRelativityScore:value(a,'psc.MotionRelativity_Score'),totalScore:value(a,'psc.Total_Score'),predictedSuccess:evidence,compressionRatio:value(a,'psc.Compression_Ratio'),gate:pscGate};
  const scar=g.scar,rsc=norm(value(a,'psc.Total_Score'),3.989,4.875),geom=mean(g.symmetry,g.inverseReadiness,value(a,'math.normalized_motion_relativity'));
  const x=structural(a),dataNext=routeAddress(a,decision,Phi,pscGate,modeGate),autoPing={dataNext,next:x.next,previous:x.previous,phasePlus:x.phasePlus,regulationPlus:x.regulationPlus,layerPlus:x.layerPlus,hourglassMirror:x.hourglassMirror,oppositeDomain:x.oppositeDomain,mode188Plus:x.mode188Plus};
  return{address:a,stateId:a+1,coordinates:c,predict,phi,identity,geometry:g,math,psc,metrics:{continuity:C,plasticity:Phi,contradiction:q,burden,scar,evidence,rsc,geometry:geom,stability:S,decision,mode188:modeGate},autoPing,source:{version:M.version,sources:M.sources,compiled:false,embedded:true,externalFetch:false,fieldCount:M.models.length,maxAbsResidual:Math.max(...M.models.map((x:any)=>x.res))}};
}

function scoreForText(text:string,r:ReturnType<typeof corpusState>){const t=text.toLowerCase(),m=r.metrics;if(/forecast|future|predict|prospective/.test(t))return mean(m.plasticity,m.evidence,norm(r.predict.forecastScore,.001656,.2101));if(/proof|evidence|valid|replic|truth/.test(t))return mean(m.evidence,1-r.identity.uncertainty,r.psc.predictedSuccess);if(/scar|memory|history|carry/.test(t))return mean(1-m.scar,m.continuity,m.plasticity,vn(r.address,'predict.carry'));if(/geometry|sphere|atlas|render|image|color|toroid|mandala|symmetry/.test(t))return mean(m.geometry,r.geometry.symmetry,r.geometry.inverseReadiness);if(/relational|skin|rsc|parent|boundary|topology|graph/.test(t))return mean(m.rsc,m.continuity,1-m.contradiction);if(/contradiction|prune|burden|constraint/.test(t))return mean(1-m.contradiction,1-m.burden,m.evidence);if(/motion|travers|auto.?ping|runtime|engine|compute/.test(t))return mean(r.math.autoPingGain,r.math.normalizedMotionRelativity,m.continuity);if(/water|flow|phase/.test(t))return mean(m.continuity,m.plasticity,1-m.burden);return cl(m.stability/(1+m.stability))}
export function evaluateCorpusModes(record:ReturnType<typeof corpusState>){const specs=meta().modeSpecs,results=specs.map((spec:any)=>{const score=cl(scoreForText(`${spec.category} ${spec.mode} ${spec.primary_purpose} ${spec.operators} ${spec.core_algebra} ${spec.calculus_expression}`,record)),gate=score>=.67?'STAY':score>=.42?'TURN':'ESCALATE';return{id:spec.id,name:spec.mode,category:spec.category,priority:spec.all_modes_priority,dimensionFrame:spec.dimension_frame,purpose:spec.primary_purpose,stateVector:spec.state_vector,score,gate,operator:spec.operators,algebra:spec.core_algebra,calculus:spec.calculus_expression,updateRule:spec.differential_or_update_rule,decisionGate:spec.decision_gate,inputs:spec.inputs,outputs:spec.outputs,proof:spec.proof_requirement,ledger:spec.ledger_fields,implementation:spec.implementation_mapping,notes:spec.notes}}),sorted=[...results].sort((a,b)=>a.score-b.score);return{count:results.length,results,weakest:sorted[0],strongest:sorted[sorted.length-1],stay:results.filter((x:any)=>x.gate==='STAY').length,turn:results.filter((x:any)=>x.gate==='TURN').length,escalate:results.filter((x:any)=>x.gate==='ESCALATE').length}}
export function sourceRGB(address:number,mode:ViewMode){const a=clampAddress(address),C=value(a,'predict.continuity'),Phi=value(a,'phi.phi_recoverability'),q=value(a,'predict.contradiction_q'),burden=value(a,'predict.ledger_burden'),scar=vn(a,'psc.Scar_Score'),inverse=mean(vn(a,'predict.reconstructability'),vn(a,'predict.compatibility')),psc=vn(a,'psc.Total_Score'),math=value(a,'math.normalized_motion_relativity'),decision=category(a,'predict.decision'),mix=(x:readonly number[],y:readonly number[],t:number)=>x.map((v,i)=>Math.round(v+(y[i]-v)*cl(t))) as [number,number,number],navy=[5,14,22] as const,teal=[33,190,174] as const,gold=[217,170,84] as const,crimson=[190,58,74] as const,ice=[216,241,244] as const;if(mode==='SOURCE_COLOR')return[Math.round(28+180*cl((q+burden)/1.3)),Math.round(38+190*mean(C,Phi)),Math.round(54+170*math)] as [number,number,number];if(mode==='CONTINUITY')return mix(navy,teal,C);if(mode==='PHI')return mix(crimson,teal,Phi);if(mode==='SCAR')return mix(navy,crimson,scar);if(mode==='INVERSE')return mix(navy,ice,inverse);if(mode==='PSC')return mix(crimson,teal,psc);if(mode==='MATH')return mix(navy,gold,math);return decision==='STAY'?teal:decision==='TURN'?gold:crimson}
export function validateCorpusPack(){const M=meta(),m=evaluateCorpusModes(corpusState(0)),sources=Object.values(M.sources) as any[],rowSources=sources.filter(x=>x.rows===20736).length,hashes=sources.every(x=>/^[a-f0-9]{64}$/.test(x.sha256)),core=['predict.continuity','predict.ledger_burden','predict.contradiction_q','phi.phi_recoverability','math.motion_relativity_index','math.normalized_auto_ping_gain'],coreR2Min=Math.min(...core.map(fieldR2)),medianR2=[...M.models.map((x:any)=>x.r2)].sort((a:number,b:number)=>a-b)[Math.floor(M.models.length/2)],samples=[0,1,187,188,1728,10368,20735],routesMove=samples.every(a=>corpusState(a).autoPing.dataNext!==a),categories=samples.every(a=>category(a,'predict.decision').length>0&&category(a,'psc.Gate').length>0),passed=M.stateCount===20736&&m.count===179&&rowSources===4&&hashes&&coreR2Min>.97&&medianR2>.99&&routesMove&&categories&&M.encoding.externalFetch===false;return{passed,stateCount:M.stateCount,fieldCount:M.models.length,modeCount:m.count,rowSources,hashes,coreR2Min,medianR2,routesMove,categories,sources:M.sources,transport:'embedded text-safe source model; no runtime gzip/bin fetch',boundary:'Numeric channels are all-row main+pair projections fitted over the complete aligned 20,736-row authorities; exact categorical gates/routes are embedded as source codes. Per-field R² and residuals remain explicit. External empirical claims remain separately gated.'}}
