export const DIMENSIONAL_RELATIVITY_R24_SOURCE='20736D_ALL_FULL_DIMENSION_RELATIVITY_ATLAS(2).xlsx';
export const DIMENSIONAL_RELATIVITY_R24_BOUNDARY='Workbook formulas are reproduced as donor-defined computational relations. 0D–12D here are representation/skin stages from the workbook, not a claim that twelve extra physical spacetime dimensions were empirically established.';
export const PRESERVATION_CORE=.7779,TRANSFORMATION_GENERATED=.2338,RECOVERED_CONTINUITY=1.1097;
export const TRANSFORM_SHARE=TRANSFORMATION_GENERATED/(PRESERVATION_CORE+TRANSFORMATION_GENERATED);
export const PRESERVE_SHARE=PRESERVATION_CORE/(PRESERVATION_CORE+TRANSFORMATION_GENERATED);
export type RelativityGate={state:'EXECUTED_EXACT'|'GATED_MISSING_INPUTS';formula:string;value:number|null;missing:string[];source:string};
export const DIMENSIONAL_SKINS=[
{order:0,dimension:'0D',skin:'Seed skin',motion:'point-potential',symmetry:'singular identity',asymmetry:'first deviation',result:'origin pressure',parent:'Origin',child:'Line skin'},
{order:1,dimension:'1D',skin:'Line skin',motion:'direction',symmetry:'path preservation',asymmetry:'forward/backward tension',result:'axis',parent:'Seed skin',child:'Surface skin'},
{order:2,dimension:'2D',skin:'Surface skin',motion:'spread',symmetry:'boundary preservation',asymmetry:'angle/curve',result:'shape',parent:'Line skin',child:'Body skin'},
{order:3,dimension:'3D',skin:'Body skin',motion:'volume',symmetry:'form preservation',asymmetry:'depth',result:'object/body',parent:'Surface skin',child:'Time skin'},
{order:4,dimension:'4D',skin:'Time skin',motion:'sequence',symmetry:'continuity',asymmetry:'before/after',result:'event history',parent:'Body skin',child:'Choice skin'},
{order:5,dimension:'5D',skin:'Choice skin',motion:'branching',symmetry:'viable paths',asymmetry:'divergence',result:'decision field',parent:'Time skin',child:'Pattern skin'},
{order:6,dimension:'6D',skin:'Pattern skin',motion:'repetition',symmetry:'rhythm',asymmetry:'variation',result:'pattern identity',parent:'Choice skin',child:'Relation skin'},
{order:7,dimension:'7D',skin:'Relation skin',motion:'interaction',symmetry:'relational memory',asymmetry:'exchange',result:'network',parent:'Pattern skin',child:'Burden skin'},
{order:8,dimension:'8D',skin:'Burden skin',motion:'compression',symmetry:'load history',asymmetry:'stress',result:'weight/pressure',parent:'Relation skin',child:'Contradiction skin'},
{order:9,dimension:'9D',skin:'Contradiction skin',motion:'conflict',symmetry:'tensional persistence',asymmetry:'rupture/turn',result:'contradiction gate',parent:'Burden skin',child:'Recovery skin'},
{order:10,dimension:'10D',skin:'Recovery skin',motion:'repair',symmetry:'usable structure',asymmetry:'reform',result:'regeneration',parent:'Contradiction skin',child:'Forecast skin'},
{order:11,dimension:'11D',skin:'Forecast skin',motion:'future pressure',symmetry:'trajectory',asymmetry:'probability',result:'forecast',parent:'Recovery skin',child:'Atlas skin'},
{order:12,dimension:'12D',skin:'Atlas skin',motion:'full cycle',symmetry:'global coherence',asymmetry:'transformation map',result:'20,736 lattice',parent:'Forecast skin',child:'Recursive return'}
] as const;
export const DIMENSIONAL_DOMAINS=['Being','Identity','Change','Cause','Time','Space','Mind','Matter','Value','Law','Possibility','Absolute'] as const;
export const DIMENSIONAL_PHASES=['Latent','Arising','Differentiating','Interacting','Stabilizing','Expanding','Conflicting','Collapsing','Turning','Integrating','Transcending','Recursive Return'] as const;
export const DIMENSIONAL_REGULATIONS=['Preserve','Distinguish','Trace','Compare','Prune','Construct','Rehost','Translate','Attest','Test','Forecast','Seal'] as const;
export const DIMENSIONAL_LAYERS=['Seed','Vector','Pattern','Structure','Identity','Continuity','Relation','Network','Burden','Contradiction','Recovery','Atlas'] as const;
export const DIMENSIONAL_LENSES=['Geometric','Kinematic','Energetic','Informational','Material','Optical','Acoustic','Thermal','Electrical','Chemical','Biological','Symbolic'] as const;
export const DIMENSIONAL_OPERATORS=['observe','construct_011','measure','route','store','constrain','prune_01-1','rebalance','stabilize','detect_q','turn','integrate_omega'] as const;
export function decodeDonorState(stateId:number){const n=Math.max(1,Math.min(20736,Math.floor(stateId)))-1;return{domain:Math.floor(n/1728)+1,skin:Math.floor((n%1728)/144)+1,phase:Math.floor((n%144)/12)+1,layer:(n%12)+1}}
const finite=(x:any)=>Number.isFinite(Number(x));
export function compileDimensionalRelativity(record:any){const C=Number(record?.metrics?.continuity),Phi=Number(record?.metrics?.plasticity),q=Number(record?.metrics?.contradiction),Lambda=Number(record?.metrics?.burden),stateId=Number(record?.stateId||Number(record?.address)+1),coords=decodeDonorState(stateId),omega=finite(C)&&finite(q)&&finite(Lambda)?C/(1+Lambda+Math.abs(q)):null,woven=omega!==null&&finite(C)&&finite(q)&&finite(Lambda)?(C+omega)/(1+Lambda+q):null,imbalance=finite(C)&&finite(q)&&finite(Lambda)?Lambda+q-C:null;const exact:RelativityGate[]=[{state:omega===null?'GATED_MISSING_INPUTS':'EXECUTED_EXACT',formula:'Ω = C/(1+Λ+ABS(q))',value:omega,missing:omega===null?['CΩ','q','Λ']:[],source:DIMENSIONAL_RELATIVITY_R24_SOURCE},{state:woven===null?'GATED_MISSING_INPUTS':'EXECUTED_EXACT',formula:'W = (C+Ω)/(1+Λ+q)',value:woven,missing:woven===null?['CΩ','Ω','q','Λ']:[],source:DIMENSIONAL_RELATIVITY_R24_SOURCE},{state:imbalance===null?'GATED_MISSING_INPUTS':'EXECUTED_EXACT',formula:'I = Λ+q-C',value:imbalance,missing:imbalance===null?['CΩ','q','Λ']:[],source:DIMENSIONAL_RELATIVITY_R24_SOURCE},{state:'GATED_MISSING_INPUTS',formula:'RT = (C+Φ+clarity+opportunity)/(1+q+Λ+risk)',value:null,missing:['clarity','opportunity','risk'],source:DIMENSIONAL_RELATIVITY_R24_SOURCE},{state:'GATED_MISSING_INPUTS',formula:'Skin(n+1)=Skin(n)×0.768904+Novelty×0.231096',value:null,missing:['authoritative current Skin(n)','Novelty'],source:DIMENSIONAL_RELATIVITY_R24_SOURCE}];return{schema:'OMEGA_DIMENSIONAL_RELATIVITY_R24',stateId,coords,labels:{domain:DIMENSIONAL_DOMAINS[coords.domain-1],phase:DIMENSIONAL_PHASES[coords.phase-1],regulation:DIMENSIONAL_REGULATIONS[coords.skin-1],layer:DIMENSIONAL_LAYERS[coords.layer-1],lens:DIMENSIONAL_LENSES[coords.layer-1],operator:DIMENSIONAL_OPERATORS[coords.domain-1]},constants:{preservationCore:PRESERVATION_CORE,transformationGenerated:TRANSFORMATION_GENERATED,recoveredContinuity:RECOVERED_CONTINUITY,preserveShare:PRESERVE_SHARE,transformShare:TRANSFORM_SHARE},packet:{C,Phi,q,Lambda},exact,boundary:DIMENSIONAL_RELATIVITY_R24_BOUNDARY}}
