const REVISION='R184';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-earth-sar':REVISION};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
const text=v=>String(v??'').trim();
const asArray=v=>Array.isArray(v)?v:(v==null?[]:[v]);
const finite=v=>Number.isFinite(Number(v))?Number(v):null;
const iso=v=>{try{const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString():null}catch{return null}};
const daysBetween=(a,b)=>Math.abs(new Date(a).getTime()-new Date(b).getTime())/86400000;
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function fetchJson(url,init={}){const started=Date.now();try{const r=await fetch(url,{...init,headers:{accept:'application/geo+json, application/json',...(init.headers||{})},signal:AbortSignal.timeout(10000),cf:{cacheTtl:0,cacheEverything:false}}),raw=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);return{ok:true,data:JSON.parse(raw),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:String(url)}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:String(url)}}}
function bboxAround(lat,lon,radiusDeg=.18){const y=clamp(lat,-89.8,89.8),cos=Math.max(.18,Math.cos(y*Math.PI/180)),rx=Math.min(1.2,radiusDeg/cos);return[clamp(lon-rx,-180,180),clamp(lat-radiusDeg,-90,90),clamp(lon+rx,-180,180),clamp(lat+radiusDeg,-90,90)]}
function geomCenter(geometry){const pts=[];const walk=v=>{if(!Array.isArray(v))return;if(v.length>=2&&typeof v[0]==='number'&&typeof v[1]==='number'){pts.push([v[0],v[1]]);return}for(const x of v)walk(x)};walk(geometry?.coordinates);if(!pts.length)return null;let sx=0,sy=0;for(const [x,y]of pts){sx+=x;sy+=y}return{lon:sx/pts.length,lat:sy/pts.length}}
function polarizations(v){return[...new Set(asArray(v).flatMap(x=>String(x||'').split(/[,+/ ]+/)).map(x=>x.trim().toUpperCase()).filter(Boolean))]}
function bandFor(platform,provider){const p=String(platform||'').toUpperCase();if(p.includes('NISAR'))return'L';if(p.includes('SENTINEL'))return'C';if(provider==='UMBRA'||provider==='CAPELLA'||provider==='ICEYE')return'X';return null}
function normalizeScene(feature,provider,family){const p=feature?.properties||{},center=geomCenter(feature?.geometry),platform=text(p.platform||p.platformName||p.sensor||p.mission||family),datetime=iso(p.datetime||p.start_datetime||p.startTime||p.startDate||p.sceneDate||p.stopTime),pol=polarizations(p['sar:polarizations']||p.polarization||p.polarizations),incidence=finite(p['view:incidence_angle']??p.incidenceAngle),resolution=finite(p.gsd??p.resolution??p['sar:resolution_range']??p.pixelSpacing),id=text(feature?.id||p.fileID||p.sceneName||p.granuleName||p.product_file_id)||`${provider}:${family}:${datetime||'undated'}:${center?.lat??'x'}:${center?.lon??'y'}`;const assets=feature?.assets||{},assetValues=Object.values(assets),thumb=assetValues.find(a=>String(a?.type||'').startsWith('image/')||String(a?.roles||'').includes('thumbnail'))?.href||asArray(p.browse)[0]||p.thumbnail||null,download=assetValues.find(a=>a?.href)?.href||p.url||p.downloadUrl||null;return{id,provider,family,truthClass:'OBSERVED_METADATA',platform,band:bandFor(platform,provider),datetime,geometry:feature?.geometry||null,center,productType:text(p.processingLevel||p.productType||p['sar:product_type']||p.collection||feature?.collection)||null,instrumentMode:text(p.beamModeType||p['sar:instrument_mode']||p.beamMode)||null,polarizations:pol,orbitState:text(p.flightDirection||p['sat:orbit_state']||p.orbitDirection).toUpperCase()||null,lookDirection:text(p.lookDirection||p['sar:observation_direction']).toUpperCase()||null,incidenceAngle:incidence,resolutionM:resolution,dataMaturity:text(p.data_maturity||p.dataMaturity||p.productionConfiguration)||null,thumbnail:thumb,download,sourceProperties:{absoluteOrbit:finite(p.absoluteOrbit),relativeOrbit:finite(p.pathNumber??p.relativeOrbit),frame:text(p.frameNumber||p.frame)||null,fileSizeBytes:finite(p.bytes??p.fileSize)}}}
function jaccardDistance(a,b){const A=new Set(a||[]),B=new Set(b||[]),union=new Set([...A,...B]);if(!union.size)return 0;let same=0;for(const x of A)if(B.has(x))same++;return 1-same/union.size}
function relativeFrame(scene,reference){if(!reference||!scene.datetime||!reference.datetime)return{frameResidual:null,relativeCoherence:null,truth:'DERIVED_RELATIVE_FRAME_SCORE_ONLY'};const temporal=Math.min(2,daysBetween(scene.datetime,reference.datetime)/12),incidence=scene.incidenceAngle!=null&&reference.incidenceAngle!=null?Math.min(1,Math.abs(scene.incidenceAngle-reference.incidenceAngle)/20):0,orbit=scene.orbitState&&reference.orbitState&&scene.orbitState!==reference.orbitState?.3:0,band=scene.band&&reference.band&&scene.band!==reference.band?.4:0,pol=jaccardDistance(scene.polarizations,reference.polarizations)*.25,residual=Math.sqrt(temporal*temporal+incidence*incidence+orbit*orbit+band*band+pol*pol),coherence=Math.exp(-residual);return{frameResidual:Number(residual.toFixed(4)),relativeCoherence:Number(coherence.toFixed(4)),components:{temporal:Number(temporal.toFixed(4)),incidence:Number(incidence.toFixed(4)),orbit,band,polarization:Number(pol.toFixed(4))},truth:'DERIVED_RELATIVE_FRAME_SCORE_ONLY'}}
function summarizeContinuity(scenes){const times=[...new Set(scenes.map(x=>x.datetime).filter(Boolean))].map(x=>new Date(x).getTime()).sort((a,b)=>b-a),gaps=[];for(let i=1;i<times.length;i++)gaps.push((times[i-1]-times[i])/86400000);const maxGap=gaps.length?Math.max(...gaps):null,meanGap=gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:null;return{acquisitions:times.length,maxGapDays:maxGap==null?null:Number(maxGap.toFixed(2)),meanGapDays:meanGap==null?null:Number(meanGap.toFixed(2)),continuityState:times.length===0?'UNOBSERVED':times.length===1?'SINGLE_OBSERVATION':maxGap!=null&&maxGap<=14?'MULTI_EPOCH_CONTINUITY':'SPARSE_MULTI_EPOCH',truth:'DERIVED_FROM_RETURNED_ACQUISITION_TIMES'}}
function providerPrograms(){return[{id:'CDSE_SENTINEL1',label:'Copernicus Sentinel-1',band:'C',access:'PUBLIC_CATALOG_QUERY_ACTIVE',catalog:'https://stac.dataspace.copernicus.eu/v1/',role:'systematic global SAR discovery'},{id:'ASF_SENTINEL1',label:'NASA ASF Sentinel-1',band:'C',access:'PUBLIC_CATALOG_QUERY_ACTIVE',catalog:'https://api.daac.asf.alaska.edu/services/search/param',role:'independent Sentinel-1 catalog cross-check'},{id:'ASF_NISAR',label:'NASA/ISRO NISAR via ASF',band:'L',access:'PUBLIC_CATALOG_QUERY_ACTIVE',catalog:'https://api.daac.asf.alaska.edu/services/search/param',role:'systematic L-band structural/change observations'},{id:'UMBRA_OPEN',label:'Umbra Open Data',band:'X',access:'PUBLIC_OPEN_PROGRAM_EXTERNAL_INDEX',catalog:'https://umbra.space/open-data/',role:'very-high-resolution validation where open scenes exist'},{id:'CAPELLA_OPEN',label:'Capella Open Data',band:'X',access:'PUBLIC_OPEN_PROGRAM_EXTERNAL_INDEX',catalog:'s3://capella-open-data/data/',role:'high-resolution validation where open scenes exist'},{id:'ICEYE_OPEN',label:'ICEYE Open Data',band:'X',access:'PUBLIC_STATIC_STAC_EXTERNAL_INDEX',catalog:'s3://iceye-open-data-catalog/data/',role:'high-resolution validation where open scenes exist'}]}
async function queryCdse(lat,lon,start,end,max){const bbox=bboxAround(lat,lon).join(','),u=new URL('https://stac.dataspace.copernicus.eu/v1/search');u.searchParams.set('collections','sentinel-1-grd');u.searchParams.set('bbox',bbox);u.searchParams.set('datetime',`${start}/${end}`);u.searchParams.set('limit',String(max));u.searchParams.set('sortby','-properties.datetime');const r=await fetchJson(u);if(!r.ok)return{...r,provider:'CDSE_SENTINEL1',scenes:[]};const features=Array.isArray(r.data?.features)?r.data.features:[];return{...r,provider:'CDSE_SENTINEL1',scenes:features.map(x=>normalizeScene(x,'CDSE','SENTINEL-1'))}}
async function queryAsf(dataset,lat,lon,start,end,max){const u=new URL('https://api.daac.asf.alaska.edu/services/search/param');u.searchParams.set('dataset',dataset);u.searchParams.set('intersectsWith',`point(${lon} ${lat})`);u.searchParams.set('start',start);u.searchParams.set('end',end);u.searchParams.set('maxResults',String(max));u.searchParams.set('output','geojson');const r=await fetchJson(u),provider=dataset==='NISAR'?'ASF_NISAR':'ASF_SENTINEL1';if(!r.ok)return{...r,provider,scenes:[]};const features=Array.isArray(r.data?.features)?r.data.features:[];return{...r,provider,scenes:features.map(x=>normalizeScene(x,'ASF',dataset==='NISAR'?'NISAR':'SENTINEL-1'))}}
function agreement(sources){const cdse=sources.find(x=>x.provider==='CDSE_SENTINEL1')?.scenes||[],asf=sources.find(x=>x.provider==='ASF_SENTINEL1')?.scenes||[],a=cdse.map(x=>x.datetime).filter(Boolean).sort().at(-1),b=asf.map(x=>x.datetime).filter(Boolean).sort().at(-1);if(!a||!b)return{state:'NOT_COMPARABLE',deltaDays:null,truth:'CATALOG_TEMPORAL_CROSSCHECK_ONLY'};const delta=daysBetween(a,b);return{state:delta<=2?'TEMPORALLY_CONSISTENT':'CATALOG_TIMES_DIFFER',deltaDays:Number(delta.toFixed(3)),cdseLatest:a,asfLatest:b,truth:'CATALOG_TEMPORAL_CROSSCHECK_ONLY'}}
async function searchSar(url){const lat=clamp(url.searchParams.get('lat'),-90,90),lon=clamp(url.searchParams.get('lon'),-180,180),days=Math.round(clamp(url.searchParams.get('days')||45,1,180)),max=Math.round(clamp(url.searchParams.get('max')||8,1,15)),sensor=text(url.searchParams.get('sensor')||'ALL').toUpperCase(),end=new Date().toISOString(),start=new Date(Date.now()-days*86400000).toISOString(),jobs=[];if(sensor==='ALL'||sensor==='SENTINEL1')jobs.push(queryCdse(lat,lon,start,end,max),queryAsf('SENTINEL-1',lat,lon,start,end,max));if(sensor==='ALL'||sensor==='NISAR')jobs.push(queryAsf('NISAR',lat,lon,start,end,max));const sources=await Promise.all(jobs),scenes=sources.flatMap(x=>x.scenes||[]).filter(x=>x.datetime).sort((a,b)=>new Date(b.datetime)-new Date(a.datetime)).slice(0,30),reference=scenes[0]||null,enriched=scenes.map(x=>({...x,calibration:relativeFrame(x,reference)})),continuity=summarizeContinuity(enriched),sourceAgreement=agreement(sources),latestAgeDays=reference?.datetime?daysBetween(reference.datetime,new Date().toISOString()):null,state=!enriched.length?'UNOBSERVED_RETURNED_SEARCH':latestAgeDays!=null&&latestAgeDays>30?'OBSERVED_STALE':'OBSERVED_CURRENT_OR_RECENT';const payload={ok:true,schema:'OMEGA_EARTH_SAR_R184',revision:REVISION,lineage:'R181_SOURCE_BACKED_SAR_DISCOVERY',target:{lat,lon,crs:'WGS84 / EPSG:4326',searchRadius:'~20 km nominal latitude radius with longitude compensation'},window:{start,end,days},sensor,state,verifiedAt:new Date().toISOString(),referenceScene:reference?{id:reference.id,provider:reference.provider,family:reference.family,datetime:reference.datetime,band:reference.band}:null,scenes:enriched,continuity,sourceAgreement,sources:sources.map(x=>({provider:x.provider,ok:x.ok,verifiedAt:x.verifiedAt,latencyMs:x.latencyMs,source:x.source,error:x.ok?null:x.error,returnedScenes:x.scenes?.length||0})),publicPrograms:providerPrograms(),truthClasses:{OBSERVED_METADATA:'Returned scene metadata/footprints from public mission catalogs.',DERIVED_RELATIVE_FRAME_SCORE:'OMEGA-calculated comparison across time, band, polarization, orbit and incidence metadata; not a new sensor measurement.',UNOBSERVED:'No matching returned scene in the requested search window; no pixels are fabricated.'},truthBoundary:'R184 correlates public SAR discovery metadata with the current Earth operator workspace. It never invents backscatter, phase, deformation, moisture, elevation or missing SAR pixels. Pixel-level radiometry and InSAR require calibrated source products and an explicit processing chain.'};payload.evidenceHash=await sha256(payload);return payload}
export async function earthSarApiR184(request,url=new URL(request.url)){if(url.pathname==='/api/earth/sar/providers'&&request.method==='GET')return json({ok:true,schema:'OMEGA_EARTH_SAR_PROVIDERS_R184',revision:REVISION,verifiedAt:new Date().toISOString(),providers:providerPrograms(),truthBoundary:'Provider availability is not target coverage. A provider becomes observational evidence only when a target query returns a scene.'});if(url.pathname==='/api/earth/sar/search'&&request.method==='GET')return json(await searchSar(url));return null}
export const EARTH_SAR_REVISION=REVISION;
