import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ChevronLeft,ChevronRight,CloudSun,Crosshair,Eye,Globe2,Layers3,Map,MapPin,Maximize2,Minimize2,Mountain,Pause,Play,Radio,RefreshCw,Search,Satellite,ShieldCheck,Wind} from 'lucide-react';
import EarthNowInstrument,{type EarthInstrumentMode} from './EarthNowInstrument';
import EarthObservedGlobeR281 from './EarthObservedGlobeR281';
import EarthLivingFieldR36 from './EarthLivingFieldR36';
import EarthGroundTraversalR9 from './EarthGroundTraversalR9';
import EarthWeatherR375 from './EarthWeatherR375';
import SARLiveTruthR285 from './SARLiveTruthR285';
// R283 proof compatibility: SARLiveTruthR285 owns live source binding and delegates analytical rendering to <SARTruthInstrumentR280/> internally.
import {api} from './platformAdapter';
import {decodeAddress} from './corpusRuntime';
import './earthObservatoryR8.css';

type Props={address:number};
type Coverage={id:string;label:string;state:string;lastModified?:string|null;truth?:string};
type Focus='ALL'|'WEATHER'|'SEISMIC'|'EVENTS'|'SPACE';
type EarthView='SATELLITE'|'PLANET'|'MOTION'|'EVIDENCE'|'WEATHER'|'SPACE'|'GROUND'|'CALCULUS'|'SAR';
const fmt=(v:any,d=1)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
const VIEWS:{id:EarthView;label:string;copy:string}[]=[
 {id:'SATELLITE',label:'Satellite',copy:'latest returned NOAA/CIRA imagery'},
 {id:'PLANET',label:'Planet',copy:'global observed texture + true projection'},
 {id:'MOTION',label:'Global motion',copy:'returned winds + derived continuity'},
 {id:'EVIDENCE',label:'Evidence',copy:'current conditions · seismic · events · space'},
 {id:'WEATHER',label:'Weather',copy:'hourly · 7 day · source agreement · continuity'},
 {id:'SPACE',label:'Earth / space',copy:'solar geometry + near-space frame'},
 {id:'GROUND',label:'Ground',copy:'region → city → street → ground evidence'},
 {id:'CALCULUS',label:'Calculus',copy:'representational comparison only'},
 {id:'SAR',label:'SAR Truth',copy:'live Sentinel-1 catalogue · bound arrays only'}
];
function savedView():EarthView{try{const v=localStorage.getItem('omega.earth.r279.view') as EarthView|null;return VIEWS.some(x=>x.id===v)?v!:'SATELLITE'}catch{return'SATELLITE'}}

export default function EarthObservatoryR8({address}:Props){
 const coords=useMemo(()=>decodeAddress(address),[address]);
 const initial=useMemo(()=>({lat:-90+(coords.d+.5)/12*180,lon:-180+(coords.p*12+coords.r+.5)/144*360}),[coords]);
 const[lat,setLat]=useState(initial.lat),[lon,setLon]=useState(initial.lon),[evidence,setEvidence]=useState<any>(null),[catalog,setCatalog]=useState<Coverage[]>([]),[selected,setSelected]=useState('G19-FD'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[focus,setFocus]=useState<Focus>('ALL'),[view,setView]=useState<EarthView>(savedView),[placeQuery,setPlaceQuery]=useState(''),[placeBusy,setPlaceBusy]=useState(false),[placeError,setPlaceError]=useState(''),[placeResults,setPlaceResults]=useState<any[]>([]),[focusDisplay,setFocusDisplay]=useState(false),[displayExpanded,setDisplayExpanded]=useState(false);
 const evidenceRequest=useRef(0),stageRef=useRef<HTMLDivElement>(null);
 const queryAt=async(qLat=lat,qLon=lon)=>{const request=++evidenceRequest.current;setBusy(true);setError('');setEvidence(null);try{const[e,c]=await Promise.all([api.get<any>(`/api/earth/evidence?lat=${qLat.toFixed(5)}&lon=${qLon.toFixed(5)}`),api.get<any>('/api/earth/noaa/catalog')]);if(request!==evidenceRequest.current)return;const target=e.data?.target;if(!target||Math.abs(Number(target.lat)-qLat)>0.000011||Math.abs(Number(target.lon)-qLon)>0.000011||!Number.isFinite(Number(target.lat))||!Number.isFinite(Number(target.lon)))throw new Error('Returned Earth evidence does not match the selected target.');setEvidence(e.data);const rows=(c.data?.coverages||[]) as Coverage[];setCatalog(rows);if(rows.length&&!rows.some(x=>x.id===selected))setSelected(rows.some(x=>x.id==='G19-FD')?'G19-FD':rows[0].id)}catch(x:any){if(request===evidenceRequest.current)setError(x?.message||String(x))}finally{if(request===evidenceRequest.current)setBusy(false)}};
 useEffect(()=>()=>{evidenceRequest.current++},[]);
 useEffect(()=>{setLat(initial.lat);setLon(initial.lon);void queryAt(initial.lat,initial.lon)},[initial.lat,initial.lon]);
 useEffect(()=>{try{localStorage.setItem('omega.earth.r279.view',view)}catch{}},[view]);
 useEffect(()=>{if(!displayExpanded)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setDisplayExpanded(false)};document.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',onKey)}},[displayExpanded]);
 useEffect(()=>{if(!playing||!catalog.length)return;const id=window.setInterval(()=>setSelected(v=>{const i=Math.max(0,catalog.findIndex(x=>x.id===v));return catalog[(i+1)%catalog.length]?.id||v}),6000);return()=>window.clearInterval(id)},[playing,catalog]);
 const current=catalog.find(x=>x.id===selected)||catalog[0];
 const fullDisks=['G19-FD','G18-FD','G17-FD'].map(id=>catalog.find(x=>x.id===id)).filter(Boolean) as Coverage[];
 const move=(delta:number)=>{if(!catalog.length)return;const i=Math.max(0,catalog.findIndex(x=>x.id===selected));setSelected(catalog[(i+delta+catalog.length)%catalog.length].id)};
 const chooseView=(next:EarthView)=>{setView(next);setPlaying(false)};
 const instrumentMode:EarthInstrumentMode=view==='MOTION'?'MOTION':view==='EVIDENCE'?'EVIDENCE':view==='SPACE'?'SPACE':'PLANET';
 const focusRows=[
  {id:'WEATHER' as Focus,icon:<Wind/>,label:'Weather',value:`${fmt(evidence?.localConditions?.temperatureC)} °C · ${fmt(evidence?.localConditions?.windKph)} km/h`,detail:`cloud ${fmt(evidence?.localConditions?.cloudPct,0)}%`},
  {id:'SEISMIC' as Focus,icon:<Activity/>,label:'Seismic',value:`${evidence?.seismic?.count??'—'} / 24h`,detail:`Mmax ${fmt(evidence?.seismic?.maxMagnitude)}`},
  {id:'EVENTS' as Focus,icon:<Layers3/>,label:'Natural events',value:`${evidence?.naturalEvents?.count??'—'} open`,detail:evidence?.naturalEvents?.nearest?.category||'none returned'},
  {id:'SPACE' as Focus,icon:<Radio/>,label:'Space weather',value:`Kp ${fmt(evidence?.spaceWeather?.kp)}`,detail:evidence?.spaceWeather?.observationTime||'unavailable'},
  {id:'CALCULUS' as Focus,icon:<Mountain/>,label:'Representational calculus',value:`${fmt(evidence?.derivedContext?.index,4)}`,detail:'display summary only · not physical proof'}
];
  {id:'WEATHER' as Focus,icon:<Wind/>,label:'Weather',value:`${fmt(evidence?.localConditions?.temperatureC)} °C · ${fmt(evidence?.localConditions?.windKph)} km/h`,detail:`cloud ${fmt(evidence?.localConditions?.cloudPct,0)}%`},
  {id:'SEISMIC' as Focus,icon:<Activity/>,label:'Seismic',value:`${evidence?.seismic?.count??'—'} / 24h`,detail:`Mmax ${fmt(evidence?.seismic?.maxMagnitude)}`},
  {id:'EVENTS' as Focus,icon:<Layers3/>,label:'Natural events',value:`${evidence?.naturalEvents?.count??'—'} open`,detail:evidence?.naturalEvents?.nearest?.category||'none returned'},
  {id:'SPACE' as Focus,icon:<Radio/>,label:'Space weather',value:`Kp ${fmt(evidence?.spaceWeather?.kp)}`,detail:evidence?.spaceWeather?.observationTime||'unavailable'}
 ];
 const resetTarget=()=>{setLat(initial.lat);setLon(initial.lon);void queryAt(initial.lat,initial.lon)};
 const setSarTarget=(qLat:number,qLon:number)=>{setLat(qLat);setLon(qLon);void queryAt(qLat,qLon)};
 const choosePlace=(row:any)=>{const qLat=Number(row?.lat),qLon=Number(row?.lon);if(!Number.isFinite(qLat)||!Number.isFinite(qLon))return;setLat(qLat);setLon(qLon);setPlaceQuery(String(row?.displayName||row?.name||''));setPlaceResults([]);setPlaceError('');void queryAt(qLat,qLon)};
 const searchPlaces=async()=>{const q=placeQuery.trim();if(q.length<2){setPlaceResults([]);setPlaceError('Enter a city, address, landmark, ZIP code, or place name.');return}setPlaceBusy(true);setPlaceError('');try{const r=await api.get<any>(`/api/earth/geocode?q=${encodeURIComponent(q)}`);const rows=Array.isArray(r.data?.results)?r.data.results:[];setPlaceResults(rows);if(!rows.length)setPlaceError('No matching locations returned.')}catch(e:any){setPlaceResults([]);setPlaceError(e?.message||String(e))}finally{setPlaceBusy(false)}};
 const useDeviceLocation=()=>{if(!navigator.geolocation){setPlaceError('Browser location is unavailable.');return}setPlaceBusy(true);setPlaceError('');navigator.geolocation.getCurrentPosition(p=>{const qLat=p.coords.latitude,qLon=p.coords.longitude;setLat(qLat);setLon(qLon);setPlaceQuery('Device location');setPlaceResults([]);setPlaceBusy(false);void queryAt(qLat,qLon)},e=>{setPlaceBusy(false);setPlaceError(e.message||'Location permission was not granted.')},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})};
 const toggleExpanded=()=>setDisplayExpanded(v=>!v);
 const renderSatellite=()=> <section className='earth-r279-satellite' data-earth-view='SATELLITE'>
  <header><div><span>OBSERVED SATELLITE SURFACE</span><h3>Latest returned NOAA / CIRA GeoColor</h3><small>Source imagery is shown as imagery. OMEGA does not paint calculated pixels into unavailable satellite regions.</small></div><div className='earth-r279-sat-controls'><button type='button' onClick={()=>move(-1)} disabled={!catalog.length} aria-label='Previous satellite coverage'><ChevronLeft/></button><button type='button' onClick={()=>setPlaying(v=>!v)} disabled={!catalog.length}>{playing?<Pause/>:<Play/>}{playing?'Stop cycle':'Cycle coverage'}</button><button type='button' onClick={()=>move(1)} disabled={!catalog.length} aria-label='Next satellite coverage'><ChevronRight/></button></div></header>
  <div className='earth-r279-sat-main'>{current?<figure><img src={`/api/earth/noaa/image?coverage=${encodeURIComponent(current.id)}`} alt={`${current.label} NOAA GeoColor latest returned image`}/><figcaption><b>{current.label}</b><span>{current.state||'UNVERIFIED'} · {current.lastModified||'timestamp unavailable'}</span></figcaption></figure>:<div className='earth-r279-sat-empty'><CloudSun/><b>No satellite coverage returned.</b><span>No substitute image is fabricated.</span></div>}<nav aria-label='Satellite coverage menu'>{catalog.map(x=><button type='button' key={x.id} onClick={()=>setSelected(x.id)} className={x.id===current?.id?'active':''}><span>{x.label}</span><small>{x.state}</small></button>)}</nav></div>
  {fullDisks.length>0&&<div className='earth-r279-global-pair'><header><Satellite/><span><b>FULL-DISK OBSERVATION PAIR</b><small>GOES-East + GOES-West returned views · separate source geometries, not falsely stitched.</small></span></header><div>{fullDisks.map(x=><figure key={x.id}><img src={`/api/earth/noaa/image?coverage=${encodeURIComponent(x.id)}`} alt={`${x.label} returned full-disk GeoColor`}/><figcaption><b>{x.label}</b><small>{x.lastModified||'timestamp unavailable'}</small></figcaption></figure>)}</div></div>}
 </section>;
 return <section className='earth-r8 earth-r72 earth-r279'>
  <header className='earth-r72-bar'><div><span>EARTH NOW · SOURCE-FIRST PLANETARY WORKSPACE</span><h2>Observe first. Compute relationships second. Keep both visible.</h2><small>Satellite imagery, SAR measurement state, WGS84 observations, derived motion, ground evidence and representational calculus remain explicitly separated.</small></div><div className='earth-r372-display-menu' aria-label='Earth display controls'><button type='button' aria-pressed={focusDisplay} data-r313-transient-toggle='true' data-r313-restore-label='Restore panels' onClick={()=>setFocusDisplay(v=>!v)}><Eye/>{focusDisplay?'Restore panels':'Focus display'}</button><button type='button' aria-pressed={displayExpanded} data-r313-transient-toggle='true' data-r313-restore-label='Exit full screen' onClick={toggleExpanded}>{displayExpanded?<Minimize2/>:<Maximize2/>}{displayExpanded?'Exit full screen':'Full screen display'}</button><button type='button' className='primary' onClick={()=>void queryAt()} disabled={busy}><RefreshCw className={busy?'spin':''}/>{busy?'Refreshing…':'Refresh returned evidence'}</button></div></header>
  <nav className='earth-r279-view-tabs' aria-label='Earth view menu'>{VIEWS.map(x=><button type='button' key={x.id} className={view===x.id?'active':''} aria-pressed={view===x.id} onClick={()=>chooseView(x.id)}><b>{x.label}</b><small>{x.copy}</small></button>)}</nav>
  <div className={`earth-r72-workspace ${view==='SAR'?'sar-active':''} ${focusDisplay?'display-focus':''}`}>
   <div ref={stageRef} className={`earth-r72-stage earth-r279-stage ${displayExpanded?'earth-r372-stage-expanded':''}`} data-display-expanded={displayExpanded?'true':'false'}>{displayExpanded&&<div className='earth-r372-expanded-bar'><b>{VIEWS.find(x=>x.id===view)?.label||view}</b><button type='button' data-r313-transient-restore='fullscreen' onClick={()=>setDisplayExpanded(false)}><Minimize2/>Exit full screen</button></div>}{view==='SATELLITE'?renderSatellite():view==='PLANET'?<EarthObservedGlobeR281 address={address} evidence={evidence} targetLat={lat} targetLon={lon}/>:view==='SAR'?<section className='earth-r283-sar earth-r285-sar' data-earth-view='SAR'><SARLiveTruthR285 lat={lat} lon={lon} evidence={evidence} onTargetChange={setSarTarget}/></section>:view==='WEATHER'?<EarthWeatherR375 lat={lat} lon={lon}/>:view==='GROUND'?<section className='earth-r279-ground' data-earth-view='GROUND'><EarthGroundTraversalR9 lat={lat} lon={lon}/></section>:view==='CALCULUS'?<section className='earth-r279-calculus' data-earth-view='CALCULUS' data-provenance='REPRESENTATIONAL'><EarthLivingFieldR36 address={address} lat={lat} lon={lon} evidence={evidence}/><p>REPRESENTATIONAL ONLY · returned measurements determine observed quantities; OMEGA calculus changes relational rendering and inference, not source pixels.</p></section>:<EarthNowInstrument address={address} evidence={evidence} targetLat={lat} targetLon={lon} mode={instrumentMode}/>}</div>
   <aside className='earth-r72-console'><div className='earth-r72-location'><Globe2/><div><b>Choose a location</b><small>Search by place name, address, landmark, ZIP code, or use your device location. Coordinates remain visible as exact WGS84 evidence.</small></div></div><div className='earth-r3563-place-picker'><form onSubmit={e=>{e.preventDefault();void searchPlaces()}}><div className='earth-r3563-search'><Search/><input aria-label='Search Earth location' placeholder='Search Tucson, Mount Lemmon, 85710…' value={placeQuery} onChange={e=>setPlaceQuery(e.target.value)}/><button type='submit' disabled={placeBusy}>{placeBusy?'Searching…':'Find'}</button></div><button type='button' className='earth-r3563-device' aria-label={view==='SAR'?'Use Earth location':'Use my location'} title={view==='SAR'?'Use device location for Earth evidence':'Use my location'} onClick={useDeviceLocation} disabled={placeBusy}><Crosshair/>Use my location</button></form>{placeError&&<div className='earth-r3563-place-error'>{placeError}</div>}{placeResults.length>0&&<div className='earth-r3563-results' role='listbox' aria-label='Location search results'>{placeResults.map((row:any,i:number)=><button type='button' key={row.id||`${row.lat}:${row.lon}:${i}`} onClick={()=>choosePlace(row)}><MapPin/><span><b>{row.name||row.displayName}</b><small>{row.displayName}</small></span></button>)}</div>}</div><details className='earth-r372-exact-coords'><summary>Exact coordinates · advanced</summary><div className='earth-r72-coords'><label>Latitude<input type='number' min='-90' max='90' step='.01' value={lat} onChange={e=>setLat(Math.max(-90,Math.min(90,Number(e.target.value))))}/></label><label>Longitude<input type='number' min='-180' max='180' step='.01' value={lon} onChange={e=>setLon(Math.max(-180,Math.min(180,Number(e.target.value))))}/></label></div><button type='button' className='earth-r72-apply' onClick={()=>void queryAt()} disabled={busy}>Query exact coordinates</button></details><button type='button' className='earth-r72-reset' onClick={resetTarget}>Return + query model-mapped target</button><div className='earth-r72-focus-head'><b>Evidence channels</b><button type='button' className={focus==='ALL'?'active':''} onClick={()=>setFocus('ALL')}>Show all</button></div><div className='earth-r72-focus'>{focusRows.map(row=><button type='button' key={row.id} className={focus===row.id?'active':''} onClick={()=>setFocus(v=>v===row.id?'ALL':row.id)}>{row.icon}<span><b>{row.label}</b><strong>{row.value}</strong><small>{row.detail}</small></span></button>)}</div><div className='earth-r72-truth'><ShieldCheck/><span><b>{evidence?.evidenceHash?'RETURNED EVIDENCE BOUND':'EVIDENCE NOT YET BOUND'}</b><small>{evidence?.verifiedAt||'No verification timestamp returned.'}</small></span></div></aside>
  </div>
  {error&&<div className='earth-r8-error'>{error}</div>}
  <div className={`earth-r72-strip focus-${focus.toLowerCase()}`}>{focusRows.filter(x=>focus==='ALL'||focus===x.id).map(row=><article key={row.id}>{row.icon}<span>{row.label}</span><b>{row.value}</b><small>{row.detail}</small></article>)}<article className='derived'><Mountain/><span>Derived context</span><b>{fmt(evidence?.derivedContext?.index,4)}</b><small>display summary only · not physical proof</small></article></div>
  <div className='earth-r279-shortcuts'><button type='button' onClick={()=>chooseView('SATELLITE')}><Satellite/>Observed imagery</button><button type='button' onClick={()=>chooseView('SAR')}><Radio/>SAR Truth</button><button type='button' onClick={()=>chooseView('MOTION')}><Wind/>Global motion</button><button type='button' onClick={()=>chooseView('WEATHER')}><CloudSun/>Weather forecast</button><button type='button' onClick={()=>chooseView('GROUND')}><Map/>Ground / street evidence</button><button type='button' onClick={()=>chooseView('CALCULUS')}><Layers3/>Representational calculus</button></div>
  <footer className='earth-r72-proof'><ShieldCheck/><div><b>Evidence hash</b><code>{evidence?.evidenceHash||'not available'}</code></div><p>Earth → Region → City → Street → Ground remains source-backed. Satellite, SAR measurement state, returned point evidence, interpolated motion and OMEGA representation are visibly distinct; unavailable providers remain unavailable.</p></footer>
 </section>;
}
