import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {Globe2,Pause,Play,RefreshCw,Satellite,ShieldCheck,SunMedium} from 'lucide-react';
import {decodeAddress} from './corpusRuntime';
import './earthObservedGlobeR281.css';

type Props={address:number;targetLat?:number;targetLon?:number;evidence?:any};
type Texture={width:number;height:number;data:Uint8ClampedArray;date:string;source:string;crs:string};
type Drag={x:number;y:number;lon:number;lat:number};
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const wrapLon=(x:number)=>((x+540)%360)-180;
const rad=(d:number)=>d*Math.PI/180;
const deg=(r:number)=>r*180/Math.PI;
const defaultDate=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);

function solarPoint(date:Date){
 const jd=date.getTime()/86400000+2440587.5,T=(jd-2451545)/36525,L0=(280.46646+T*(36000.76983+T*.0003032))%360,M=357.52911+T*(35999.05029-.0001537*T),e=.016708634-T*(.000042037+.0000001267*T),C=Math.sin(rad(M))*(1.914602-T*(.004817+.000014*T))+Math.sin(rad(2*M))*(.019993-.000101*T)+Math.sin(rad(3*M))*.000289,trueLong=L0+C,omega=125.04-1934.136*T,lambda=trueLong-.00569-.00478*Math.sin(rad(omega)),eps0=23+(26+(21.448-T*(46.815+T*(.00059-T*.001813)))/60)/60,eps=eps0+.00256*Math.cos(rad(omega)),decl=deg(Math.asin(Math.sin(rad(eps))*Math.sin(rad(lambda)))),y=Math.tan(rad(eps/2))**2,eq=4*deg(y*Math.sin(2*rad(L0))-2*e*Math.sin(rad(M))+4*e*y*Math.sin(rad(M))*Math.cos(2*rad(L0))-.5*y*y*Math.sin(4*rad(L0))-1.25*e*e*Math.sin(2*rad(M))),minutes=date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60;
 return{lat:decl,lon:wrapLon(180-(minutes+eq)*.25)};
}
function sample(texture:Texture,lat:number,lon:number){
 const x=((wrapLon(lon)+180)/360)*(texture.width-1),y=((90-clamp(lat,-90,90))/180)*(texture.height-1),x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(texture.width-1,x0+1),y1=Math.min(texture.height-1,y0+1),tx=x-x0,ty=y-y0;
 const at=(ix:number,iy:number,c:number)=>texture.data[(iy*texture.width+ix)*4+c];
 const mix=(a:number,b:number,t:number)=>a+(b-a)*t;
 return[0,1,2].map(c=>mix(mix(at(x0,y0,c),at(x1,y0,c),tx),mix(at(x0,y1,c),at(x1,y1,c),tx),ty));
}
function inverseOrtho(nx:number,ny:number,centerLat:number,centerLon:number){
 const rho=Math.hypot(nx,ny);if(rho>1)return null;const phi0=rad(centerLat),lambda0=rad(centerLon);if(rho<1e-8)return{lat:centerLat,lon:centerLon};const c=Math.asin(clamp(rho,0,1)),sinC=Math.sin(c),cosC=Math.cos(c),lat=Math.asin(cosC*Math.sin(phi0)+(ny*sinC*Math.cos(phi0))/rho),lon=lambda0+Math.atan2(nx*sinC,rho*Math.cos(phi0)*cosC-ny*Math.sin(phi0)*sinC);return{lat:deg(lat),lon:wrapLon(deg(lon))};
}
function forwardOrtho(lat:number,lon:number,centerLat:number,centerLon:number){
 const p=rad(lat),p0=rad(centerLat),dl=rad(wrapLon(lon-centerLon)),x=Math.cos(p)*Math.sin(dl),y=Math.cos(p0)*Math.sin(p)-Math.sin(p0)*Math.cos(p)*Math.cos(dl),z=Math.sin(p0)*Math.sin(p)+Math.cos(p0)*Math.cos(p)*Math.cos(dl);return{x,y,z};
}
function renderSphere(texture:Texture|null,size:number,centerLat:number,centerLon:number,solarShade:boolean,now:Date){
 const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d',{willReadFrequently:false});if(!ctx)return canvas;const image=ctx.createImageData(size,size),out=image.data,R=(size-2)/2,cx=size/2,cy=size/2,sun=solarPoint(now),sp=rad(sun.lat),sl=rad(sun.lon);
 for(let py=0;py<size;py++)for(let px=0;px<size;px++){const nx=(px-cx)/R,ny=-(py-cy)/R,r2=nx*nx+ny*ny,i=(py*size+px)*4;if(r2>1){out[i+3]=0;continue}const geo=inverseOrtho(nx,ny,centerLat,centerLon);if(!geo){out[i+3]=0;continue}let rr=7,gg=16,bb=22;if(texture){const rgb=sample(texture,geo.lat,geo.lon);rr=rgb[0];gg=rgb[1];bb=rgb[2]}if(solarShade){const p=rad(geo.lat),l=rad(geo.lon),illum=Math.sin(p)*Math.sin(sp)+Math.cos(p)*Math.cos(sp)*Math.cos(l-sl),shade=.27+.73*Math.pow(Math.max(0,illum),.42);rr*=shade;gg*=shade;bb*=shade}const limb=.76+.24*Math.pow(Math.sqrt(Math.max(0,1-r2)),.35);out[i]=clamp(Math.round(rr*limb),0,255);out[i+1]=clamp(Math.round(gg*limb),0,255);out[i+2]=clamp(Math.round(bb*limb),0,255);out[i+3]=255}
 ctx.putImageData(image,0,0);return canvas;
}

export default function EarthObservedGlobeR281({address,targetLat,targetLon,evidence}:Props){
 const canvas=useRef<HTMLCanvasElement|null>(null),drag=useRef<Drag|null>(null),texture=useRef<Texture|null>(null);
 const coords=useMemo(()=>decodeAddress(address),[address]),mappedLat=-90+(coords.d+.5)/12*180,mappedLon=-180+(coords.p*12+coords.r+.5)/144*360,target={lat:Number.isFinite(targetLat)?Number(targetLat):mappedLat,lon:Number.isFinite(targetLon)?Number(targetLon):mappedLon};
 const[date,setDate]=useState(defaultDate),[state,setState]=useState<'LOADING'|'OBSERVED'|'UNAVAILABLE'>('LOADING'),[error,setError]=useState(''),[centerLat,setCenterLat]=useState(clamp(target.lat,-75,75)),[centerLon,setCenterLon]=useState(wrapLon(target.lon)),[zoom,setZoom]=useState(1),[solarShade,setSolarShade]=useState(true),[rotating,setRotating]=useState(true),[now,setNow]=useState(()=>new Date()),[revision,setRevision]=useState(0),[meta,setMeta]=useState({source:'NASA GIBS · VIIRS SNPP true color',crs:'EPSG:4326',date:defaultDate()});
 useEffect(()=>{setCenterLat(clamp(target.lat,-75,75));setCenterLon(wrapLon(target.lon))},[target.lat,target.lon]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),60000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{if(!rotating)return;const id=window.setInterval(()=>setCenterLon(v=>wrapLon(v+15/3600)),1000);return()=>window.clearInterval(id)},[rotating]);
 const load=async()=>{const controller=new AbortController();setState('LOADING');setError('');try{const r=await fetch(`/api/earth/gibs/global?date=${encodeURIComponent(date)}&width=2048&height=1024`,{signal:controller.signal,cache:'no-store',headers:{accept:'image/*'}});if(!r.ok)throw new Error(`global observed image HTTP ${r.status}`);const ct=r.headers.get('content-type')||'';if(!ct.startsWith('image/'))throw new Error(`global observed image returned ${ct||'unknown content type'}`);const blob=await r.blob(),bitmap=await createImageBitmap(blob),off=document.createElement('canvas');off.width=bitmap.width;off.height=bitmap.height;const ctx=off.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('2D texture decoder unavailable');ctx.drawImage(bitmap,0,0);const pixels=ctx.getImageData(0,0,off.width,off.height);bitmap.close?.();const source=r.headers.get('x-omega-source')||'NASA-GIBS-VIIRS-SNPP-TRUECOLOR-GLOBAL',returnedDate=r.headers.get('x-omega-date')||date,crs=r.headers.get('x-omega-crs')||'EPSG:4326';texture.current={width:off.width,height:off.height,data:pixels.data,date:returnedDate,source,crs};setMeta({source,crs,date:returnedDate});setState('OBSERVED');setRevision(v=>v+1)}catch(e:any){texture.current=null;setState('UNAVAILABLE');setError(e?.message||String(e));setRevision(v=>v+1)}};
 useEffect(()=>{void load()},[date]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const rect=c.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),W=Math.max(340,Math.round(rect.width)),H=Math.max(520,Math.round(rect.height));c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const bg=ctx.createRadialGradient(W*.5,H*.48,20,W*.5,H*.48,Math.max(W,H)*.7);bg.addColorStop(0,'#071820');bg.addColorStop(.55,'#02080d');bg.addColorStop(1,'#000306');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);const cssDiameter=Math.min(W*.88,H*.82)*zoom,renderSize=Math.round(clamp(cssDiameter*dpr,420,720)),sphere=renderSphere(texture.current,renderSize,centerLat,centerLon,solarShade,now),x=W/2-cssDiameter/2,y=H*.48-cssDiameter/2;ctx.drawImage(sphere,x,y,cssDiameter,cssDiameter);const rim=ctx.createRadialGradient(W/2,H*.48,cssDiameter*.44,W/2,H*.48,cssDiameter*.51);rim.addColorStop(.82,'rgba(74,174,215,0)');rim.addColorStop(.95,'rgba(86,189,224,.20)');rim.addColorStop(1,'rgba(122,220,240,.46)');ctx.fillStyle=rim;ctx.beginPath();ctx.arc(W/2,H*.48,cssDiameter*.515,0,Math.PI*2);ctx.fill();const p=forwardOrtho(target.lat,target.lon,centerLat,centerLon);if(p.z>=0){const px=W/2+p.x*cssDiameter/2,py=H*.48-p.y*cssDiameter/2;ctx.strokeStyle='rgba(255,221,143,.9)';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(px,py,7,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(255,221,143,.95)';ctx.beginPath();ctx.arc(px,py,2.4,0,Math.PI*2);ctx.fill()}},[centerLat,centerLon,zoom,solarShade,now,revision,target.lat,target.lon]);
 const pointerDown=(e:ReactPointerEvent<HTMLCanvasElement>)=>{drag.current={x:e.clientX,y:e.clientY,lon:centerLon,lat:centerLat};e.currentTarget.setPointerCapture(e.pointerId);setRotating(false)};
 const pointerMove=(e:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect(),dx=(e.clientX-drag.current.x)/Math.max(1,rect.width),dy=(e.clientY-drag.current.y)/Math.max(1,rect.height);setCenterLon(wrapLon(drag.current.lon-dx*220));setCenterLat(clamp(drag.current.lat+dy*150,-82,82))};
 const pointerUp=(e:ReactPointerEvent<HTMLCanvasElement>)=>{drag.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}};
 const ageHours=Number.isFinite(Date.parse(meta.date+'T12:00:00Z'))?Math.max(0,(Date.now()-Date.parse(meta.date+'T12:00:00Z'))/3600000):null;
 return <section className='earth-r281-globe' data-earth-view='PLANET' data-source-state={state}>
  <header><div><span>R281 · OBSERVED EARTH GLOBE</span><h3>Returned global true-color imagery projected onto the planet</h3><small>NASA GIBS VIIRS observation texture · interactive orthographic projection · current UTC solar shading is derived and separately identified.</small></div><div className='r281-source-state'><Satellite/><span><b>{state==='OBSERVED'?'OBSERVED TEXTURE':state}</b><small>{state==='OBSERVED'?`${meta.date} · ${meta.crs}`:error||'Loading global source imagery'}</small></span></div></header>
  <div className='r281-stage'><canvas ref={canvas} aria-label='Observed Earth globe projected from returned NASA GIBS true-color imagery' onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}/><div className='r281-hud'><div><Globe2/><span><b>{centerLat.toFixed(2)}°, {centerLon.toFixed(2)}°</b><small>view center · drag planet to inspect</small></span></div><div><SunMedium/><span><b>{solarShade?'UTC SOLAR SHADE ON':'SOURCE BRIGHTNESS'}</b><small>{solarShade?'current solar geometry changes illumination only':'no current solar shading'}</small></span></div><div><ShieldCheck/><span><b>{state==='OBSERVED'?'SOURCE BOUND':'NO SOURCE TEXTURE'}</b><small>{ageHours===null?'age unavailable':`observation day age ≈ ${ageHours.toFixed(1)} h`}</small></span></div></div></div>
  <div className='r281-controls'><button type='button' onClick={()=>setRotating(v=>!v)}>{rotating?<Pause/>:<Play/>}{rotating?'Pause real-time Earth rotation':'Resume 15°/hour rotation'}</button><button type='button' onClick={()=>{setCenterLat(clamp(target.lat,-75,75));setCenterLon(wrapLon(target.lon))}}>Center returned target</button><button type='button' onClick={()=>setSolarShade(v=>!v)}>{solarShade?'Disable derived solar shade':'Enable UTC solar shade'}</button><label>Observation day<input type='date' value={date} max={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label>Zoom<input type='range' min='.78' max='1.28' step='.02' value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><button type='button' onClick={()=>void load()} disabled={state==='LOADING'}><RefreshCw className={state==='LOADING'?'spin':''}/>Reload observed texture</button></div>
  <footer><ShieldCheck/><p><b>Truth boundary.</b> Planet surface pixels come from the returned NASA GIBS VIIRS true-color image in EPSG:4326. Rotation, orthographic reprojection, limb treatment, target marker and UTC solar shading are rendering transforms. Current weather, seismic and space-weather evidence remains separate; unavailable source imagery is not replaced with invented satellite detail.</p><code>{evidence?.evidenceHash||'point-evidence hash not loaded'}</code></footer>
 </section>;
}