import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {CircleDot,Grid3X3,Globe2,Pause,Play,RefreshCw,Satellite,ShieldCheck,SunMedium} from 'lucide-react';
import {decodeAddress} from './corpusRuntime';
import {clamp,createWgs84Orthographic,dot3,geodeticNormal,solarElevationDegrees,solarPoint,terminatorGeodetic,wrapLon,WGS84_F,type GeoPoint,type OrthoWgs84} from './earthProjectionR284';
import './earthObservedGlobeR281.css';

type Props={address:number;targetLat?:number;targetLon?:number;evidence?:any};
type Texture={width:number;height:number;data:Uint8ClampedArray;date:string;source:string;crs:string;bbox:string;truth:string};
type Drag={x:number;y:number;lon:number;lat:number};
type HoverSample={lat:number;lon:number;rgb:[number,number,number];solarElevation:number}|null;
const defaultDate=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);
const EXPECTED_SOURCE='NASA-GIBS-VIIRS-SNPP-TRUECOLOR-GLOBAL';
const EXPECTED_CRS='EPSG:4326';
const EXPECTED_BBOX='-180,-90,180,90';
const EXPECTED_TRUTH='RETURNED_GLOBAL_OBSERVATION';

function sample(texture:Texture,lat:number,lon:number):[number,number,number]{
 const fx=((wrapLon(lon)+180)/360)*texture.width,x0=((Math.floor(fx)%texture.width)+texture.width)%texture.width,x1=(x0+1)%texture.width,tx=fx-Math.floor(fx),fy=((90-clamp(lat,-90,90))/180)*(texture.height-1),y0=Math.floor(fy),y1=Math.min(texture.height-1,y0+1),ty=fy-y0;
 const at=(ix:number,iy:number,c:number)=>texture.data[(iy*texture.width+ix)*4+c],mix=(a:number,b:number,t:number)=>a+(b-a)*t;
 return [0,1,2].map(c=>mix(mix(at(x0,y0,c),at(x1,y0,c),tx),mix(at(x0,y1,c),at(x1,y1,c),tx),ty)) as [number,number,number];
}

function renderEllipsoid(texture:Texture|null,size:number,centerLat:number,centerLon:number,solarShade:boolean,now:Date){
 const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d',{willReadFrequently:false});if(!ctx)return canvas;const image=ctx.createImageData(size,size),out=image.data,R=(size-2)/2,cx=size/2,cy=size/2,sun=solarPoint(now),sunNormal=geodeticNormal(sun.lat,sun.lon),projection=createWgs84Orthographic(centerLat,centerLon);
 for(let py=0;py<size;py++)for(let px=0;px<size;px++){const nx=(px-cx)/R,ny=-(py-cy)/R,i=(py*size+px)*4,geo=projection.inverse(nx,ny);if(!geo){out[i+3]=0;continue}let rr=7,gg=16,bb=22;if(texture){const rgb=sample(texture,geo.lat,geo.lon);rr=rgb[0];gg=rgb[1];bb=rgb[2]}if(solarShade){const illum=dot3(geo.normal,sunNormal),day=Math.pow(Math.max(0,illum),.42),twilight=clamp((illum+.10)/.10,0,1),shade=.08+.92*Math.max(day,.16*twilight),limb=.83+.17*Math.pow(geo.mu,.34);rr*=shade*limb;gg*=shade*limb;bb*=shade*limb}out[i]=clamp(Math.round(rr),0,255);out[i+1]=clamp(Math.round(gg),0,255);out[i+2]=clamp(Math.round(bb),0,255);out[i+3]=255}
 ctx.putImageData(image,0,0);return canvas;
}

function geoPath(ctx:CanvasRenderingContext2D,points:GeoPoint[],projection:OrthoWgs84,cx:number,cy:number,R:number){
 let open=false,lastX=0,lastY=0;ctx.beginPath();for(const point of points){const p=projection.forward(point.lat,point.lon);if(p.z<=0){open=false;continue}const x=cx+p.x*R,y=cy-p.y*R;if(!open||Math.hypot(x-lastX,y-lastY)>R*.22){ctx.moveTo(x,y);open=true}else ctx.lineTo(x,y);lastX=x;lastY=y}ctx.stroke();
}
function latLine(lat:number):GeoPoint[]{const out:GeoPoint[]=[];for(let lon=-180;lon<=180;lon+=2)out.push({lat,lon});return out}
function lonLine(lon:number):GeoPoint[]{const out:GeoPoint[]=[];for(let lat=-89;lat<=89;lat+=2)out.push({lat,lon});return out}

export default function EarthObservedGlobeR281({address,targetLat,targetLon,evidence}:Props){
 const canvas=useRef<HTMLCanvasElement|null>(null),drag=useRef<Drag|null>(null),texture=useRef<Texture|null>(null),fetchController=useRef<AbortController|null>(null),centerLonRef=useRef(0),rotationBase=useRef({time:Date.now(),lon:0});
 const coords=useMemo(()=>decodeAddress(address),[address]),mappedLat=-90+(coords.d+.5)/12*180,mappedLon=-180+(coords.p*12+coords.r+.5)/144*360,target={lat:Number.isFinite(targetLat)?Number(targetLat):mappedLat,lon:Number.isFinite(targetLon)?Number(targetLon):mappedLon};
 const[date,setDate]=useState(defaultDate),[state,setState]=useState<'LOADING'|'OBSERVED'|'UNAVAILABLE'>('LOADING'),[error,setError]=useState(''),[centerLat,setCenterLat]=useState(clamp(target.lat,-82,82)),[centerLon,setCenterLon]=useState(wrapLon(target.lon)),[zoom,setZoom]=useState(1),[solarShade,setSolarShade]=useState(false),[showGrid,setShowGrid]=useState(true),[showTerminator,setShowTerminator]=useState(true),[rotating,setRotating]=useState(true),[interacting,setInteracting]=useState(false),[now,setNow]=useState(()=>new Date()),[revision,setRevision]=useState(0),[layoutRevision,setLayoutRevision]=useState(0),[hover,setHover]=useState<HoverSample>(null),[meta,setMeta]=useState({source:'NASA GIBS · VIIRS SNPP true color',crs:EXPECTED_CRS,date:defaultDate(),bbox:EXPECTED_BBOX,truth:'LOADING',width:0,height:0});
 useEffect(()=>{centerLonRef.current=centerLon},[centerLon]);
 useEffect(()=>{const lat=clamp(target.lat,-82,82),lon=wrapLon(target.lon);setCenterLat(lat);setCenterLon(lon);centerLonRef.current=lon;rotationBase.current={time:Date.now(),lon}},[target.lat,target.lon]);
 useEffect(()=>{const c=canvas.current;if(!c||typeof ResizeObserver==='undefined')return;const ro=new ResizeObserver(()=>setLayoutRevision(v=>v+1));ro.observe(c);return()=>ro.disconnect()},[]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),30000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{if(!rotating)return;rotationBase.current={time:Date.now(),lon:centerLonRef.current};const tick=()=>{const base=rotationBase.current;setCenterLon(wrapLon(base.lon+(Date.now()-base.time)*15/3600000))};tick();const id=window.setInterval(tick,1000);return()=>window.clearInterval(id)},[rotating]);
 const load=async()=>{fetchController.current?.abort();const controller=new AbortController();fetchController.current=controller;setState('LOADING');setError('');try{const r=await fetch(`/api/earth/gibs/global?date=${encodeURIComponent(date)}&width=2048&height=1024`,{signal:controller.signal,cache:'no-store',headers:{accept:'image/*'}});if(!r.ok)throw new Error(`global observed image HTTP ${r.status}`);const ct=r.headers.get('content-type')||'';if(!ct.startsWith('image/'))throw new Error(`global observed image returned ${ct||'unknown content type'}`);const source=r.headers.get('x-omega-source')||'',returnedDate=r.headers.get('x-omega-date')||date,crs=r.headers.get('x-omega-crs')||'',bbox=r.headers.get('x-omega-bbox')||'',truth=r.headers.get('x-omega-truth')||'';if(source!==EXPECTED_SOURCE)throw new Error(`global source identity mismatch: ${source||'missing'}`);if(crs!==EXPECTED_CRS)throw new Error(`global source CRS mismatch: ${crs||'missing'}`);if(bbox!==EXPECTED_BBOX)throw new Error(`global source bbox mismatch: ${bbox||'missing'}`);if(truth!==EXPECTED_TRUTH)throw new Error(`global source truth mismatch: ${truth||'missing'}`);const blob=await r.blob(),bitmap=await createImageBitmap(blob);if(Math.abs(bitmap.width/Math.max(1,bitmap.height)-2)>.025){bitmap.close?.();throw new Error(`global source aspect mismatch ${bitmap.width}×${bitmap.height}`)}const off=document.createElement('canvas');off.width=bitmap.width;off.height=bitmap.height;const ctx=off.getContext('2d',{willReadFrequently:true});if(!ctx){bitmap.close?.();throw new Error('2D texture decoder unavailable')}ctx.drawImage(bitmap,0,0);const pixels=ctx.getImageData(0,0,off.width,off.height);bitmap.close?.();if(controller.signal.aborted)return;texture.current={width:off.width,height:off.height,data:pixels.data,date:returnedDate,source,crs,bbox,truth};setMeta({source,crs,date:returnedDate,bbox,truth,width:off.width,height:off.height});setState('OBSERVED');setRevision(v=>v+1)}catch(e:any){if(controller.signal.aborted)return;texture.current=null;setState('UNAVAILABLE');setError(e?.message||String(e));setRevision(v=>v+1)}};
 useEffect(()=>{void load();return()=>fetchController.current?.abort()},[date]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const rect=c.getBoundingClientRect(),dpr=Math.min(2.25,window.devicePixelRatio||1),W=Math.max(320,Math.round(rect.width)),H=Math.max(470,Math.round(rect.height));c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const bg=ctx.createRadialGradient(W*.5,H*.43,28,W*.5,H*.46,Math.max(W,H)*.72);bg.addColorStop(0,'#081920');bg.addColorStop(.56,'#02080d');bg.addColorStop(1,'#000205');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);const cssDiameter=Math.min(W*.90,H*.78)*zoom,qualityCap=interacting?640:rotating?960:1440,renderSize=Math.round(clamp(cssDiameter*dpr,420,qualityCap)),sphere=renderEllipsoid(texture.current,renderSize,centerLat,centerLon,solarShade,now),cx=W/2,cy=H*.44,R=cssDiameter/2,x=cx-R,y=cy-R,projection=createWgs84Orthographic(centerLat,centerLon);c.dataset.surfaceRender=String(renderSize);c.dataset.devicePixelRatio=dpr.toFixed(2);ctx.drawImage(sphere,x,y,cssDiameter,cssDiameter);
  ctx.save();ctx.beginPath();ctx.arc(cx,cy,R*1.01,0,Math.PI*2);ctx.clip();if(showGrid){ctx.strokeStyle='rgba(177,224,232,.20)';ctx.lineWidth=.65;for(const lat of[-60,-30,0,30,60]){ctx.globalAlpha=lat===0?.9:.56;geoPath(ctx,latLine(lat),projection,cx,cy,R)}for(let lon=-150;lon<=180;lon+=30){ctx.globalAlpha=.48;geoPath(ctx,lonLine(lon),projection,cx,cy,R)}ctx.globalAlpha=1}if(showTerminator){ctx.strokeStyle='rgba(255,208,112,.72)';ctx.lineWidth=1.05;ctx.setLineDash([5,5]);geoPath(ctx,terminatorGeodetic(now,300),projection,cx,cy,R);ctx.setLineDash([]);const sun=solarPoint(now),sp=projection.forward(sun.lat,sun.lon);if(sp.z>0){const sx=cx+sp.x*R,sy=cy-sp.y*R;ctx.strokeStyle='rgba(255,222,137,.86)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(sx,sy,5.5,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(255,222,137,.95)';ctx.beginPath();ctx.arc(sx,sy,1.8,0,Math.PI*2);ctx.fill()}}ctx.restore();
  const rim=ctx.createRadialGradient(cx,cy,R*.91,cx,cy,R*1.035);rim.addColorStop(0,'rgba(82,183,220,0)');rim.addColorStop(.72,'rgba(86,189,224,.10)');rim.addColorStop(.92,'rgba(105,207,236,.34)');rim.addColorStop(1,'rgba(139,225,244,.04)');ctx.fillStyle=rim;ctx.beginPath();ctx.arc(cx,cy,R*1.035,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(146,225,240,.22)';ctx.lineWidth=.8;ctx.beginPath();ctx.arc(cx,cy,R*1.004,0,Math.PI*2);ctx.stroke();
  const p=projection.forward(target.lat,target.lon);if(p.z>=0){const px=cx+p.x*R,py=cy-p.y*R;ctx.strokeStyle='rgba(255,221,143,.96)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(px,py,7.5,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(255,221,143,.98)';ctx.beginPath();ctx.arc(px,py,2.5,0,Math.PI*2);ctx.fill();ctx.font='700 9px ui-monospace,monospace';ctx.fillStyle='rgba(255,230,170,.92)';ctx.fillText(`${target.lat.toFixed(2)}°, ${target.lon.toFixed(2)}°`,px+11,py-9)}
  const north=projection.forward(89.999,0);if(north.z>0){ctx.font='800 10px ui-monospace,monospace';ctx.fillStyle='rgba(218,239,243,.72)';ctx.fillText('N',cx+north.x*R-3,cy-north.y*R-7)}
 },[centerLat,centerLon,zoom,solarShade,showGrid,showTerminator,rotating,interacting,now,revision,layoutRevision,target.lat,target.lon]);
 const inspect=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect(),W=rect.width,H=rect.height,diameter=Math.min(W*.90,H*.78)*zoom,R=diameter/2,cx=W/2,cy=H*.44,nx=(e.clientX-rect.left-cx)/R,ny=-(e.clientY-rect.top-cy)/R,geo=createWgs84Orthographic(centerLat,centerLon).inverse(nx,ny),tex=texture.current;if(!geo||!tex){setHover(null);return}const rgb=sample(tex,geo.lat,geo.lon).map(v=>Math.round(v)) as [number,number,number];setHover({lat:geo.lat,lon:geo.lon,rgb,solarElevation:solarElevationDegrees(geo.lat,geo.lon,now)})};
 const pointerDown=(e:ReactPointerEvent<HTMLCanvasElement>)=>{drag.current={x:e.clientX,y:e.clientY,lon:centerLon,lat:centerLat};e.currentTarget.setPointerCapture(e.pointerId);setRotating(false);setInteracting(true);setHover(null)};
 const pointerMove=(e:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drag.current){inspect(e);return}const rect=e.currentTarget.getBoundingClientRect(),dx=(e.clientX-drag.current.x)/Math.max(1,rect.width),dy=(e.clientY-drag.current.y)/Math.max(1,rect.height);setCenterLon(wrapLon(drag.current.lon-dx*220));setCenterLat(clamp(drag.current.lat+dy*150,-89,89))};
 const pointerUp=(e:ReactPointerEvent<HTMLCanvasElement>)=>{drag.current=null;setInteracting(false);try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}inspect(e)};
 const doubleClick=(e:ReactPointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect(),W=rect.width,H=rect.height,diameter=Math.min(W*.90,H*.78)*zoom,R=diameter/2,cx=W/2,cy=H*.44,geo=createWgs84Orthographic(centerLat,centerLon).inverse((e.clientX-rect.left-cx)/R,-(e.clientY-rect.top-cy)/R);if(!geo)return;setRotating(false);setCenterLat(clamp(geo.lat,-89,89));setCenterLon(wrapLon(geo.lon))};
 const ageHours=Number.isFinite(Date.parse(meta.date+'T12:00:00Z'))?Math.max(0,(Date.now()-Date.parse(meta.date+'T12:00:00Z'))/3600000):null,subsolar=solarPoint(now);
 return <section className='earth-r281-globe earth-r284-globe' data-earth-view='PLANET' data-source-state={state} data-projection='WGS84_ELLIPSOID_ORTHOGRAPHIC' data-source-crs={meta.crs}>
  <header><div><span>R284 · OBSERVED EARTH VISUAL INSTRUMENT</span><h3>Returned Earth pixels on a WGS84 ellipsoid, with source and derived geometry kept visibly distinct</h3><small>NASA GIBS VIIRS observation texture · ellipsoidal orthographic projection · source brightness is the default evidence view.</small></div><div className='r281-source-state'><Satellite/><span><b>{state==='OBSERVED'?'OBSERVED TEXTURE':state}</b><small>{state==='OBSERVED'?`${meta.date} · ${meta.crs} · ${meta.width}×${meta.height}`:error||'Loading global source imagery'}</small></span></div></header>
  <div className='r284-projection-strip'><span><ShieldCheck/><b>OBSERVED</b><small>{state==='OBSERVED'?`${meta.source} · ${meta.bbox}`:'source pending'}</small></span><span><Globe2/><b>WGS84 ELLIPSOID</b><small>flattening 1/{(1/WGS84_F).toFixed(9)} · geodetic latitude</small></span><span><SunMedium/><b>DERIVED UTC GEOMETRY</b><small>subsolar {subsolar.lat.toFixed(2)}°, {subsolar.lon.toFixed(2)}° · never source evidence</small></span></div>
  <div className='r281-stage'><canvas ref={canvas} aria-label='Observed Earth globe projected from returned NASA GIBS true-color imagery using WGS84 ellipsoid geometry' onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onPointerLeave={()=>{if(!drag.current)setHover(null)}} onDoubleClick={doubleClick}/><div className='r281-hud'><div><Globe2/><span><b>{centerLat.toFixed(2)}°, {centerLon.toFixed(2)}°</b><small>view center · drag to rotate · double-click surface to center</small></span></div><div><SunMedium/><span><b>{solarShade?'DERIVED UTC ILLUMINATION':'SOURCE BRIGHTNESS'}</b><small>{solarShade?'solar geometry changes display brightness only':'returned image brightness preserved'}</small></span></div><div><ShieldCheck/><span><b>{state==='OBSERVED'?'SOURCE BOUND':'NO SOURCE TEXTURE'}</b><small>{ageHours===null?'observation-day age unavailable':`observation day age ≈ ${ageHours.toFixed(1)} h`}</small></span></div></div>{hover&&<div className='r284-inspector' aria-live='polite'><b>OBSERVED PIXEL INSPECTOR</b><span>{hover.lat.toFixed(4)}°, {hover.lon.toFixed(4)}°</span><span>RGB {hover.rgb.join(' · ')}</span><small>derived solar elevation {hover.solarElevation.toFixed(1)}° · source RGB sampled before illumination transform</small></div>}</div>
  <div className='r281-controls'><button type='button' onClick={()=>setRotating(v=>!v)}>{rotating?<Pause/>:<Play/>}{rotating?'Pause wall-clock Earth rotation':'Resume 15°/hour rotation'}</button><button type='button' onClick={()=>{const lat=clamp(target.lat,-89,89),lon=wrapLon(target.lon);setCenterLat(lat);setCenterLon(lon);rotationBase.current={time:Date.now(),lon}}}>Center returned target</button><button type='button' onClick={()=>setSolarShade(v=>!v)}><SunMedium/>{solarShade?'Show source brightness':'Enable derived UTC illumination'}</button><button type='button' onClick={()=>setShowGrid(v=>!v)}><Grid3X3/>{showGrid?'Hide geodetic grid':'Show geodetic grid'}</button><button type='button' onClick={()=>setShowTerminator(v=>!v)}><CircleDot/>{showTerminator?'Hide UTC terminator':'Show UTC terminator'}</button><label>Observation day<input type='date' value={date} max={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label>Zoom<input type='range' min='.76' max='1.34' step='.02' value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><button type='button' onClick={()=>void load()} disabled={state==='LOADING'}><RefreshCw className={state==='LOADING'?'spin':''}/>Reload observed texture</button></div>
  <footer><ShieldCheck/><p><b>Truth boundary.</b> Planet surface pixels come from the returned NASA GIBS VIIRS true-color image in EPSG:4326. WGS84 projection, wall-clock rotation, geodetic grid, UTC terminator, target marker, atmosphere rim and optional UTC illumination are declared rendering transforms. The pixel inspector reports the unshaded returned texture sample. Current weather, SAR, seismic and space-weather evidence remains separate; unavailable source imagery is not replaced with invented satellite detail.</p><code>{evidence?.evidenceHash||'point-evidence hash not loaded'}</code></footer>
 </section>;
}
