import {useEffect,useMemo,useState} from 'react';
import {Database,HardDrive,Network,Radio,RefreshCw,ShieldCheck,Target,Workflow} from 'lucide-react';
import {api} from './platformAdapter';
import {corpusState} from './corpusRuntime';
import './earthCorrelationWorkstationR184.css';

type Props={lat:number;lon:number;evidence:any;record?:any;address:number;onNavigate?:(panel:string)=>void};
type Scene={id:string;provider:string;family:string;band?:string|null;datetime?:string|null;geometry?:any;platform?:string|null;productType?:string|null;instrumentMode?:string|null;polarizations?:string[];orbitState?:string|null;incidenceAngle?:number|null;resolutionM?:number|null;calibration?:{frameResidual?:number|null;relativeCoherence?:number|null;truth?:string}};
type NodeState='LIVE'|'RETURNED'|'READY'|'HELD'|'UNPROVEN';
const fmt=(v:any,d=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
const when=(v:any)=>{const d=new Date(v||0);return Number.isFinite(d.getTime())&&d.getTime()>0?d.toLocaleString():'unknown time'};
const finite=(v:any)=>typeof v==='number'&&Number.isFinite(v)?v:null;
const clamp01=(v:number)=>Math.max(0,Math.min(1,v));
const sceneKey=(s:Scene)=>`${s.provider}:${s.id}`;
function ringOf(g:any){const valid=(row:any)=>Array.isArray(row)&&row.length>=2&&Number.isFinite(Number(row[0]))&&Number.isFinite(Number(row[1]));if(g?.type==='Polygon'&&Array.isArray(g.coordinates?.[0]))return g.coordinates[0].filter(valid).map((x:any)=>[Number(x[0]),Number(x[1])]);if(g?.type==='MultiPolygon'&&Array.isArray(g.coordinates?.[0]?.[0]))return g.coordinates[0][0].filter(valid).map((x:any)=>[Number(x[0]),Number(x[1])]);return[] as number[][]}
function stateOf(value:any):NodeState{const s=String(value??'').toUpperCase();if(s.includes('LIVE')||s.includes('ONLINE'))return'LIVE';if(s.includes('RETURN')||s.includes('OBSERVED')||s.includes('VERIFIED'))return'RETURNED';if(s.includes('READY')||s.includes('CURRENT')||s.includes('CLOSED'))return'READY';if(s.includes('HELD')||s.includes('DEGRADED')||s.includes('REQUIRED'))return'HELD';return'UNPROVEN'}
function readLocal(key:string){if(typeof localStorage==='undefined')return null;try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}

export default function EarthCorrelationWorkstationR184({lat,lon,evidence,record,address,onNavigate}:Props){
 const[sar,setSar]=useState<any>(null),[system,setSystem]=useState<any>(null),[autonomic,setAutonomic]=useState<any>(null),[hybrid,setHybrid]=useState<any>(null),[runs,setRuns]=useState<any[]>([]),[days,setDays]=useState(45),[selected,setSelected]=useState(''),[plan,setPlan]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const activeRecord=useMemo(()=>record||corpusState(address),[record,address]);
 const load=async()=>{setBusy(true);setMessage('');try{const[s,c,a,h,r]=await Promise.allSettled([api.get<any>(`/api/earth/sar/search?lat=${lat.toFixed(5)}&lon=${lon.toFixed(5)}&sensor=ALL&days=${days}&max=10`),api.get<any>('/api/system/convergence'),api.get<any>('/api/swarm/autonomic/status'),api.get<any>('/api/hybrid/status'),api.get<any>('/api/execution/runs')]);if(s.status==='fulfilled'){const next=s.value.data;setSar(next);const scenes=Array.isArray(next?.scenes)?next.scenes:[];setSelected(v=>scenes.some((x:Scene)=>sceneKey(x)===v)?v:(scenes[0]?sceneKey(scenes[0]):''))}if(c.status==='fulfilled')setSystem(c.value.data);if(a.status==='fulfilled')setAutonomic(a.value.data);if(h.status==='fulfilled')setHybrid(h.value.data);if(r.status==='fulfilled')setRuns(Array.isArray(r.value.data?.runs)?r.value.data.runs:[]);setMessage('Source, runtime and receipt planes refreshed independently.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[lat,lon,days]);
 const scenes=(Array.isArray(sar?.scenes)?sar.scenes:[]) as Scene[],chosen=scenes.find(x=>sceneKey(x)===selected)||scenes[0]||null;
 const pcOnline=Boolean(hybrid?.nativeExecutionClaimed===true&&Array.isArray(hybrid?.devices)&&hybrid.devices.some((d:any)=>d?.online&&!d?.revoked));
 const sourceRows=useMemo(()=>{const base=Object.entries(evidence?.sources||{}).map(([id,v]:any)=>({id:id.toUpperCase(),state:(v?.ok?'RETURNED':'UNPROVEN') as NodeState,detail:v?.ok?`verified ${when(v?.verifiedAt)}`:'provider unavailable',authority:'RETURNED PUBLIC SOURCE',latency:null}));const sarRows=(sar?.sources||[]).map((v:any)=>({id:v.provider,state:(v.ok?'RETURNED':'UNPROVEN') as NodeState,detail:v.ok?`${v.returnedScenes||0} scene(s) · ${v.latencyMs??'—'} ms`:`${v.error||'unavailable'}`,authority:'RETURNED SAR CATALOG',latency:v.latencyMs??null}));return[...base,...sarRows]},[evidence,sar]);
 const returnedSources=sourceRows.filter(x=>x.state==='RETURNED').length;
 const meanCoherence=useMemo(()=>{const xs=scenes.map(x=>finite(x.calibration?.relativeCoherence)).filter((x):x is number=>x!==null);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null},[scenes]);
 const signals=useMemo(()=>[
  {id:'SEISMIC',label:'Max magnitude / 24h',value:finite(evidence?.seismic?.maxMagnitude),display:clamp01(Number(evidence?.seismic?.maxMagnitude||0)/8),detail:`${evidence?.seismic?.count??'—'} returned events`},
  {id:'SPACE',label:'Planetary Kp',value:finite(evidence?.spaceWeather?.kp),display:clamp01(Number(evidence?.spaceWeather?.kp||0)/9),detail:evidence?.spaceWeather?.observationTime||'not returned'},
  {id:'WIND',label:'Wind km/h',value:finite(evidence?.localConditions?.windKph),display:clamp01(Number(evidence?.localConditions?.windKph||0)/120),detail:`${fmt(evidence?.localConditions?.temperatureC,1)} °C`},
  {id:'CLOUD',label:'Cloud cover %',value:finite(evidence?.localConditions?.cloudPct),display:clamp01(Number(evidence?.localConditions?.cloudPct||0)/100),detail:evidence?.localConditions?.time||'not returned'},
  {id:'EVENTS',label:'Open natural events',value:finite(evidence?.naturalEvents?.count),display:clamp01(Number(evidence?.naturalEvents?.count||0)/100),detail:evidence?.naturalEvents?.nearest?.category||'nearest category unavailable'},
  {id:'SAR',label:'Mean relative-frame score',value:meanCoherence,display:clamp01(Number(meanCoherence||0)),detail:`${sar?.continuity?.acquisitions??0} acquisition epochs`}
 ],[evidence,meanCoherence,sar]);
 const graph=useMemo(()=>{const nodes=[
  {id:'USGS',label:'USGS',sub:'SEISMIC',x:85,y:58,state:stateOf(evidence?.sources?.usgs?.ok?'RETURNED':'UNPROVEN')},
  {id:'EONET',label:'NASA',sub:'EONET',x:85,y:142,state:stateOf(evidence?.sources?.eonet?.ok?'RETURNED':'UNPROVEN')},
  {id:'SWPC',label:'NOAA',sub:'SPACE',x:85,y:226,state:stateOf(evidence?.sources?.swpc?.ok?'RETURNED':'UNPROVEN')},
  {id:'METEO',label:'METEO',sub:'LOCAL',x:85,y:310,state:stateOf(evidence?.sources?.openMeteo?.ok?'RETURNED':'UNPROVEN')},
  {id:'SAR',label:'SAR',sub:`${scenes.length} SCENES`,x:260,y:58,state:stateOf(sar?.state)},
  {id:'TARGET',label:'WGS84',sub:`${lat.toFixed(2)}, ${lon.toFixed(2)}`,x:260,y:184,state:(evidence?.evidenceHash?'RETURNED':'UNPROVEN') as NodeState},
  {id:'R125',label:'R125',sub:'AUTONOMIC',x:455,y:116,state:stateOf(autonomic?.state||(autonomic?.ok?'READY':'UNPROVEN'))},
  {id:'HYBRID',label:'HOST',sub:pcOnline?'HEARTBEAT':'PROOF GATE',x:455,y:252,state:(pcOnline?'LIVE':'HELD') as NodeState},
  {id:'WORLD',label:'R182',sub:'RECONCILE',x:640,y:184,state:(runs.some((x:any)=>String(x?.state||'').toUpperCase().includes('VERIFIED'))?'RETURNED':'READY') as NodeState}
 ];const edges=[['USGS','TARGET'],['EONET','TARGET'],['SWPC','TARGET'],['METEO','TARGET'],['SAR','TARGET'],['TARGET','R125'],['R125','HYBRID'],['R125','WORLD'],['HYBRID','WORLD']];return{nodes,edges}},[evidence,sar,scenes.length,lat,lon,autonomic,pcOnline,runs]);
 const map=useMemo(()=>{const rings=scenes.map(s=>({key:sceneKey(s),scene:s,ring:ringOf(s.geometry)})).filter(x=>x.ring.length>=3),pts:number[][]=[[lon,lat],...rings.flatMap(x=>x.ring)];let minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1]));if(!Number.isFinite(minX)||maxX-minX<.02){minX=lon-.15;maxX=lon+.15}if(!Number.isFinite(minY)||maxY-minY<.02){minY=lat-.15;maxY=lat+.15}const px=(maxX-minX)*.08,py=(maxY-minY)*.08;minX-=px;maxX+=px;minY-=py;maxY+=py;const project=(p:number[])=>[16+(p[0]-minX)/(maxX-minX)*608,304-(p[1]-minY)/(maxY-minY)*288];return{rings:rings.map(x=>({...x,points:x.ring.map(project).map(p=>`${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ')})),target:project([lon,lat])}},[scenes,lat,lon]);
 const timeline=useMemo(()=>{const rows:any[]=[];if(evidence?.verifiedAt)rows.push({time:evidence.verifiedAt,kind:'EARTH',title:'Earth evidence packet returned',detail:String(evidence?.evidenceHash||'').slice(0,18)});for(const s of scenes.slice(0,8))if(s.datetime)rows.push({time:s.datetime,kind:'SAR',title:`${s.family} · ${s.provider}`,detail:`${s.band||'?'}-band acquisition`});for(const r of runs.slice(0,8)){const t=r?.updatedAt||r?.createdAt||r?.transitionedAt;if(t)rows.push({time:t,kind:'RUN',title:`${r.id||r.runId||'execution run'}`,detail:String(r.state||r.status||'UNKNOWN')})}return rows.sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime()).slice(0,12)},[evidence,scenes,runs]);
 const preview=async()=>{if(busy)return;setBusy(true);setMessage('');try{const packets=[evidence?.evidenceHash?{id:'earth-evidence-r184',type:'EARTH_EVIDENCE',sha256:evidence.evidenceHash,summary:`Returned Earth evidence at ${lat.toFixed(5)}, ${lon.toFixed(5)}`,authority:'RETURNED_SOURCE_PACKET'}:null,sar?.evidenceHash?{id:'sar-evidence-r184',type:'EARTH_SAR',sha256:sar.evidenceHash,summary:`${scenes.length} returned SAR scene records at current target`,authority:'OBSERVED_METADATA_PLUS_DERIVED_FRAME_DIAGNOSTICS'}:null].filter(Boolean);const r=await api.post<any>('/api/swarm/autonomic/plan',{intent:`Correlate the current returned Earth and SAR evidence at WGS84 ${lat.toFixed(5)}, ${lon.toFixed(5)} with the active OMEGA packet. Preserve source authority, identify residual evidence gaps, and choose the smallest proof-bounded computation needed next.`,projection:'EARTH',mode:'AUTO',providerBudget:0,reconvergeWithAI:false,metrics:activeRecord?.metrics||{},evidence:packets});setPlan(r.data?.plan||r.data);setMessage('R125 plan preview returned. No mission, host execution or CanonState mutation occurred.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const selectedNode=(id:string)=>graph.nodes.find(n=>n.id===id)!;
 const worldLocal=readLocal('omega.r175.worldTruthSurface'),dispatchLocal=readLocal('omega.r180.executionReceipt');
 return <section className='earth-r184' aria-label='R184 Earth evidence correlation workstation'>
  <header className='earth-r184-head'><div><span>R184 · EARTH EVIDENCE FUSION WORKSTATION</span><h3>Correlate real source returns, acquisition geometry, compute readiness and proof in one operator frame.</h3><small>No synthetic radar pixels, no invented execution, no authority promotion. Every lane is tied to a returned source, current runtime endpoint, or explicit local receipt.</small></div><div className='earth-r184-head-actions'><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/>Refresh mesh</button><button className='primary' onClick={()=>void preview()} disabled={busy}><Target/>Preview bounded compute</button></div></header>
  <div className='earth-r184-kpis'><article><Database/><span>Returned source planes</span><b>{returnedSources}/{sourceRows.length||0}</b><small>public providers independently visible</small></article><article><Radio/><span>SAR acquisitions</span><b>{scenes.length}</b><small>{sar?.continuity?.continuityState||'UNOBSERVED'}</small></article><article><Workflow/><span>Durable runs visible</span><b>{runs.length}</b><small>{runs.filter((x:any)=>String(x?.state||'').toUpperCase().includes('VERIFIED')).length} verified-state rows</small></article><article><HardDrive/><span>Sovereign host</span><b>{pcOnline?'LIVE':'PROOF GATED'}</b><small>{pcOnline?'authenticated heartbeat returned':'no current authenticated heartbeat proof'}</small></article></div>
  <div className='earth-r184-main'>
   <section className='earth-r184-graph'><header><div><span>LIVE PROVENANCE CORRELATION MAP</span><b>Observation → target → bounded planning → execution proof → reconciliation</b></div><code>ATLAS {address} · WGS84 {lat.toFixed(5)}, {lon.toFixed(5)}</code></header><svg viewBox='0 0 720 370' role='img' aria-label='Live evidence and execution authority correlation graph'>{graph.edges.map(([a,b])=>{const A=selectedNode(a),B=selectedNode(b);return <line key={`${a}-${b}`} x1={A.x} y1={A.y} x2={B.x} y2={B.y} className={`edge state-${A.state.toLowerCase()} state2-${B.state.toLowerCase()}`}/>})}{graph.nodes.map(n=><g key={n.id} className={`node state-${n.state.toLowerCase()}`} transform={`translate(${n.x} ${n.y})`}><circle r='34'/><circle r='28' className='node-inner'/><text y='-2'>{n.label}</text><text y='15' className='sub'>{n.sub}</text><title>{`${n.id} · ${n.state}`}</title></g>)}</svg><footer><span><i className='live'/>live/current</span><span><i className='returned'/>returned evidence</span><span><i className='ready'/>available planning/reconciliation</span><span><i className='held'/>proof gated</span><span><i className='unproven'/>unproven/unavailable</span></footer></section>
   <aside className='earth-r184-source-ledger'><header><span>SOURCE LEDGER</span><b>Authority stays separate</b></header><div>{sourceRows.map(row=><article key={row.id} data-state={row.state}><span>{row.id}</span><b>{row.state}</b><small>{row.detail}</small></article>)}</div></aside>
  </div>
  <section className='earth-r184-signal-plane'><header><div><span>RETURNED SIGNAL PLANE</span><b>Actual values; bar length is display normalization only.</b></div></header><div>{signals.map(s=><article key={s.id}><span>{s.id}</span><div><b>{s.label}</b><i><em style={{width:`${Math.round(s.display*100)}%`}}/></i><small>{s.detail}</small></div><strong>{s.value==null?'—':fmt(s.value,s.id==='EVENTS'?0:2)}</strong></article>)}</div></section>
  <section className='earth-r184-sar'><header><div><span>SAR ACQUISITION GEOMETRY</span><b>Returned Sentinel-1 / NISAR catalog footprints</b><small>Relative-frame values compare metadata only; they are not interferometric coherence or deformation.</small></div><div className='earth-r184-segments'>{[14,45,90].map(d=><button key={d} className={days===d?'active':''} onClick={()=>setDays(d)}>{d} d</button>)}</div></header><div className='earth-r184-sar-grid'><div className='earth-r184-map'><svg viewBox='0 0 640 320' role='img' aria-label='Returned SAR footprints around current WGS84 target'><rect width='640' height='320' className='bg'/>{map.rings.map(x=><polygon key={x.key} points={x.points} className={`footprint band-${String(x.scene.band||'unknown').toLowerCase()} ${x.key===selected?'selected':''}`} onClick={()=>setSelected(x.key)}/>)}<circle cx={map.target[0]} cy={map.target[1]} r='5' className='target'/><path d={`M${map.target[0]-13} ${map.target[1]}h26M${map.target[0]} ${map.target[1]-13}v26`} className='cross'/></svg></div><div className='earth-r184-acquisitions'>{scenes.length?scenes.slice(0,14).map(s=><button key={sceneKey(s)} className={sceneKey(s)===sceneKey(chosen as Scene)?'active':''} onClick={()=>setSelected(sceneKey(s))}><span>{s.band||'?'}</span><div><b>{s.family} · {s.provider}</b><small>{when(s.datetime)} · {[s.orbitState,s.instrumentMode,(s.polarizations||[]).join('/')].filter(Boolean).join(' · ')||'metadata only'}</small></div><strong>{s.calibration?.relativeCoherence==null?'OBSERVED':fmt(s.calibration.relativeCoherence,3)}</strong></button>):<p>No returned SAR scene in this window. The workspace stays explicitly unobserved.</p>}</div></div>{chosen&&<div className='earth-r184-scene-detail'><span>SELECTED ACQUISITION</span><b>{chosen.family} · {chosen.platform||chosen.provider}</b><small>{when(chosen.datetime)} · {chosen.band||'?'}-band · {chosen.productType||'product type not returned'}</small><div><em>POL {(chosen.polarizations||[]).join('/')||'—'}</em><em>ORBIT {chosen.orbitState||'—'}</em><em>INC {chosen.incidenceAngle==null?'—':`${fmt(chosen.incidenceAngle)}°`}</em><em>RES {chosen.resolutionM==null?'—':`${fmt(chosen.resolutionM)} m`}</em><em>REL {fmt(chosen.calibration?.relativeCoherence,4)}</em><em>RESID {fmt(chosen.calibration?.frameResidual,4)}</em></div></div>}</section>
  <div className='earth-r184-bottom'>
   <section className='earth-r184-timeline'><header><span>OBSERVATION / EXECUTION TIMELINE</span><b>One clock-ordered ledger</b></header><div>{timeline.map((x,i)=><article key={`${x.kind}-${x.time}-${i}`}><i>{x.kind}</i><span><b>{x.title}</b><small>{x.detail}</small></span><time>{when(x.time)}</time></article>)}{!timeline.length&&<p>No timestamped source or execution rows returned.</p>}</div></section>
   <section className='earth-r184-plan'><header><span>BOUNDED COMPUTE PREVIEW</span><b>{plan?`${plan?.decision||'PLAN'} · ${plan?.totalCells??plan?.cells??'—'} cells`:'Not yet compiled'}</b></header>{plan?<><div className='plan-line'><Network/><span><b>{plan?.projection||'EARTH'} · {plan?.mode||'AUTO'}</b><small>{plan?.totalBranches??'—'} branches · provider budget 0 for this preview</small></span></div><code>{String(plan?.fingerprint||plan?.planHash||'runtime plan returned').slice(0,64)}</code></>:<p>Preview sends the active canonical packet metrics plus Earth/SAR evidence hashes to R125. It does not execute a mission.</p>}{onNavigate&&<div className='earth-r184-route-buttons'><button onClick={()=>onNavigate('Convergence')}>Open Convergence</button><button onClick={()=>onNavigate('Evidence & Proof')}>Open proof ledger</button><button onClick={()=>onNavigate('Hybrid Link')}>Open Hybrid</button></div>}</section>
  </div>
  {message&&<div className='earth-r184-message'>{message}</div>}
  <footer className='earth-r184-proof'><ShieldCheck/><div><b>Active packet</b><code>{activeRecord?.stateId||`atlas:${address}`}</code><b>Earth hash</b><code>{evidence?.evidenceHash||'not returned'}</code><b>SAR hash</b><code>{sar?.evidenceHash||'not returned'}</code></div><p>System {system?.canonical?.state||'UNPROVEN'} · R125 {autonomic?.state||autonomic?.revision||'UNPROVEN'} · R175 local {worldLocal?.eventAccepted?'BOUND':'UNPROVEN'} · R180 local {dispatchLocal?'RECEIPT PRESENT':'UNPROVEN'}. Local receipts remain local evidence; server state remains separately observed.</p></footer>
 </section>;
}
