import {useEffect,useMemo,useRef,useState} from 'react';
import {Globe2,Pause,Play,RefreshCw,RotateCcw,ShieldCheck} from 'lucide-react';
import {feature} from 'topojson-client';
import land110 from 'world-atlas/land-110m.json';
import {corpusState,decodeAddress} from './corpusRuntime';
import {fetchEarthMotionStateR278,type EarthMotionSampleR278,type EarthMotionStateR278} from './earthMotionStateR278';
import './earthNow.css';

export type EarthInstrumentMode='PLANET'|'MOTION'|'EVIDENCE'|'SPACE';
type Props={address:number;evidence?:any;targetLat?:number;targetLon?:number;mode?:EarthInstrumentMode};
type SunState={utc:Date;declination:number;subsolarLat:number;subsolarLon:number;gst:number};
type Track='SIDEREAL'|'SUN'|'SOURCE'|'TARGET'|'FREE';
type Particle={lat:number;lon:number;age:number;life:number};
const LAND:any=feature(land110 as any,(land110 as any).objects.land);
const EXTERNAL_OBSERVATION_STATE='RETURNED_SOURCE_ONLY';
const rad=(d:number)=>d*Math.PI/180,deg=(r:number)=>r*180/Math.PI,clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x)),wrapLon=(x:number)=>((x+540)%360)-180,num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f,fract=(n:number)=>n-Math.floor(n);
function solarState(date:Date):SunState{const ms=date.getTime(),jd=ms/86400000+2440587.5,T=(jd-2451545.0)/36525,L0=(280.46646+T*(36000.76983+T*0.0003032))%360,M=357.52911+T*(35999.05029-0.0001537*T),e=0.016708634-T*(0.000042037+0.0000001267*T),C=Math.sin(rad(M))*(1.914602-T*(0.004817+0.000014*T))+Math.sin(rad(2*M))*(0.019993-0.000101*T)+Math.sin(rad(3*M))*0.000289,trueLong=L0+C,omega=125.04-1934.136*T,lambda=trueLong-0.00569-0.00478*Math.sin(rad(omega)),eps0=23+(26+(21.448-T*(46.815+T*(0.00059-T*0.001813)))/60)/60,eps=eps0+0.00256*Math.cos(rad(omega)),decl=deg(Math.asin(Math.sin(rad(eps))*Math.sin(rad(lambda)))),y=Math.tan(rad(eps/2))**2,eq=4*deg(y*Math.sin(2*rad(L0))-2*e*Math.sin(rad(M))+4*e*y*Math.sin(rad(M))*Math.cos(2*rad(L0))-.5*y*y*Math.sin(4*rad(L0))-1.25*e*e*Math.sin(2*rad(M))),minutes=date.getUTCHours()*60+date.getUTCMinutes()+date.getUTCSeconds()/60+date.getUTCMilliseconds()/60000,subLon=wrapLon(180-(minutes+eq)*.25),gst=(280.46061837+360.98564736629*(jd-2451545.0)+0.000387933*T*T-T*T*T/38710000)%360;return{utc:date,declination:decl,subsolarLat:decl,subsolarLon:subLon,gst:(gst+360)%360}}
function project(lat:number,lon:number,rotation:number,cx:number,cy:number,R:number){const la=rad(lat),lo=rad(wrapLon(lon-rotation)),x=R*Math.cos(la)*Math.sin(lo),y=-R*Math.sin(la),z=Math.cos(la)*Math.cos(lo);return{x:cx+x,y:cy+y,front:z>=0,z}}
function terminatorPoints(sun:SunState,rotation:number,cx:number,cy:number,R:number){const d=rad(sun.subsolarLat),l0=rad(sun.subsolarLon),sx=Math.cos(d)*Math.cos(l0),sy=Math.cos(d)*Math.sin(l0),sz=Math.sin(d),seed=Math.abs(sz)<.9?{x:0,y:0,z:1}:{x:1,y:0,z:0};let ux=sy*seed.z-sz*seed.y,uy=sz*seed.x-sx*seed.z,uz=sx*seed.y-sy*seed.x;const un=Math.hypot(ux,uy,uz)||1;ux/=un;uy/=un;uz/=un;const vx=sy*uz-sz*uy,vy=sz*ux-sx*uz,vz=sx*uy-sy*ux,out:{x:number;y:number;front:boolean}[]=[];for(let i=0;i<=360;i++){const a=i/360*Math.PI*2,X=ux*Math.cos(a)+vx*Math.sin(a),Y=uy*Math.cos(a)+vy*Math.sin(a),Z=uz*Math.cos(a)+vz*Math.sin(a),lat=deg(Math.asin(clamp(Z,-1,1))),lon=deg(Math.atan2(Y,X)),p=project(lat,lon,rotation,cx,cy,R);out.push(p)}return out}
function drawLand(ctx:CanvasRenderingContext2D,rotation:number,cx:number,cy:number,R:number){const polys=LAND.geometry?.type==='MultiPolygon'?LAND.geometry.coordinates:LAND.geometry?.type==='Polygon'?[LAND.geometry.coordinates]:[];const land=ctx.createLinearGradient(cx-R,cy-R,cx+R,cy+R);land.addColorStop(0,'rgba(89,119,76,.94)');land.addColorStop(.48,'rgba(50,91,67,.98)');land.addColorStop(1,'rgba(25,66,57,.98)');ctx.fillStyle=land;ctx.strokeStyle='rgba(176,205,173,.38)';ctx.lineWidth=.55;for(const poly of polys)for(const ring of poly){let segment:{x:number;y:number}[]=[];const flush=()=>{if(segment.length<3){segment=[];return}ctx.beginPath();ctx.moveTo(segment[0].x,segment[0].y);for(let i=1;i<segment.length;i++)ctx.lineTo(segment[i].x,segment[i].y);ctx.closePath();ctx.fill();ctx.stroke();segment=[]};for(const pt of ring){const p=project(pt[1],pt[0],rotation,cx,cy,R);if(!p.front){flush();continue}segment.push(p)}flush()}}
function seedParticles(count:number){const out:Particle[]=[];for(let i=0;i<count;i++){const a=fract(Math.sin(i*93.17+4.3)*43758.5453),b=fract(Math.sin(i*47.71+91.2)*12515.873),c=fract(Math.sin(i*21.37+7.9)*9171.41;out.push({lat:deg(Math.asin(clamp(a*2-1,-1,1))),lon:b*360-180,age:c*8,life:5+c*10})}return out}
function motionAt(state:EarthMotionStateR278|null,lat:number,lon:number){if(!state?.samples?.length)return{east:0,north:0,speed:0,quality:0,woven:0,cloud:0,pressure:1013.25};const best:{d:number;s:EarthMotionSampleR278}[]=[];for(const s of state.samples){const dl=Math.abs(wrapLon(lon-s.lon))*Math.max(.18,Math.cos(rad(lat))),da=lat-s.lat,d=Math.hypot(da,dl);if(best.length<4||d<best[best.length-1].d){best.push({d,s});best.sort((a,b)=>a.d-b.d);if(best.length>4)best.pop()}}let wsum=0,east=0,north=0,speed=0,quality=0,woven=0,cloud=0,pressure=0;for(const x of best){const w=1/(1+x.d*x.d*.018),spd=Math.max(0,x.s.windKph||0),toward=rad(((x.s.windDirectionDeg||0)+180)%360);wsum+=w;east+=Math.sin(toward)*spd*w;north+=Math.cos(toward)*spd*w;speed+=spd*w;quality+=x.s.quality*w;woven+=x.s.woven*w;cloud+=(x.s.cloudPct||0)*w;pressure+=(x.s.surfacePressureHpa||1013.25)*w}return{east:east/wsum,north:north/wsum,speed:speed/wsum,quality:quality/wsum,woven:woven/wsum,cloud:cloud/wsum,pressure:pressure/wsum}}
function drawCloudTexture(ctx:CanvasRenderingContext2D,state:EarthMotionStateR278|null,rotation:number,cx:number,cy:number,R:number,time:number){if(!state)return;ctx.save();ctx.globalCompositeOperation='screen';for(const s of state.samples){const cloud=clamp((s.cloudPct||0)/100,0,1);if(cloud<.08||s.quality<=0)continue;const p=project(s.lat,s.lon,rotation,cx,cy,R*.997);if(!p.front)continue;const rr=R*(.045+.11*cloud),g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,rr),pulse=.82+.12*Math.sin(time*.00035+s.lat*.09+s.lon*.03);g.addColorStop(0,`rgba(244,248,246,${(.04+.16*cloud)*s.quality*pulse})`);g.addColorStop(.55,`rgba(228,239,239,${(.025+.10*cloud)*s.quality})`);g.addColorStop(1,'rgba(220,235,238,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawMotionParticles(ctx:CanvasRenderingContext2D,state:EarthMotionStateR278|null,particles:Particle[],rotation:number,cx:number,cy:number,R:number,dt:number,running:boolean,strong:boolean){if(!state)return;ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<particles.length;i++){const p=particles[i],prev=project(p.lat,p.lon,rotation,cx,cy,R*1.004),f=motionAt(state,p.lat,p.lon);if(running){const visual=.0125,cos=Math.max(.2,Math.cos(rad(p.lat)));p.lon=wrapLon(p.lon+f.east*dt*visual/cos);p.lat=clamp(p.lat+f.north*dt*visual,-84,84);p.age+=dt;if(p.age>p.life||f.quality<.15){const a=fract(Math.sin((i+1)*(p.age+13.7))*15731.743),b=fract(Math.sin((i+11)*(p.age+4.1))*951.117);p.lat=deg(Math.asin(clamp(a*2-1,-1,1)));p.lon=b*360-180;p.age=0;p.life=6+9*fract(Math.sin(i*29.1)*731.9)}}const next=project(p.lat,p.lon,rotation,cx,cy,R*1.004);if(!next.front)continue;const alpha=(strong?.12:.045)+(strong?.46:.18)*clamp(f.quality,0,1)*(.45+.55*clamp(f.woven,0,1));ctx.strokeStyle=`rgba(152,226,239,${alpha})`;ctx.lineWidth=strong?1.45:1;ctx.beginPath();ctx.moveTo(prev.x,prev.y);ctx.lineTo(next.x,next.y);ctx.stroke();ctx.fillStyle=`rgba(226,249,247,${alpha+.08})`;ctx.beginPath();ctx.arc(next.x,next.y,strong?1.25:.8,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawEvidence(ctx:CanvasRenderingContext2D,evidence:any,targetLat:number,targetLon:number,rotation:number,cx:number,cy:number,R:number,time:number){if(!evidence)return;const p=project(targetLat,targetLon,rotation,cx,cy,R*1.012);if(!p.front)return;const mag=clamp((num(evidence?.seismic?.maxMagnitude)-1)/7,0,1),wind=clamp(num(evidence?.localConditions?.windKph)/110,0,1),dir=rad((num(evidence?.localConditions?.windDirectionDeg)+180)%360);ctx.save();ctx.shadowBlur=18;ctx.shadowColor='rgba(255,213,130,.72)';ctx.fillStyle='rgba(255,223,151,.98)';ctx.beginPath();ctx.arc(p.x,p.y,4.2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,223,151,.44)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,10+2*Math.sin(time*.002),0,Math.PI*2);ctx.stroke();if(wind>.02){ctx.strokeStyle=`rgba(89,211,244,${.5+.4*wind})`;ctx.lineWidth=1.5+2*wind;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.sin(dir)*(25+55*wind),p.y-Math.cos(dir)*(25+55*wind));ctx.stroke()}if(mag>.02){ctx.strokeStyle=`rgba(239,108,90,${.22+.5*mag})`;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(p.x,p.y,15+i*11+Math.sin(time*.002+i)*3*mag,0,Math.PI*2);ctx.stroke()}}ctx.restore()}

export default function EarthNowInstrument({address,evidence,targetLat,targetLon,mode='PLANET'}:Props){
 const canvas=useRef<HTMLCanvasElement|null>(null),drag=useRef<{x:number;r:number}|null>(null),particles=useRef<Particle[]>([]),lastFrame=useRef(0);
 const[running,setRunning]=useState(true),[now,setNow]=useState(()=>new Date()),[freeRotation,setFreeRotation]=useState(0),[track,setTrack]=useState<Track>('SIDEREAL'),[rate,setRate]=useState(1),[motion,setMotion]=useState<EarthMotionStateR278|null>(null),[motionBusy,setMotionBusy]=useState(false),[motionError,setMotionError]=useState('');
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setNow(d=>rate===1?new Date():new Date(d.getTime()+250*rate)),250);return()=>window.clearInterval(id)},[running,rate]);
 useEffect(()=>{let live=true,controller:AbortController|null=null;const load=async()=>{controller?.abort();controller=new AbortController();setMotionBusy(true);try{const next=await fetchEarthMotionStateR278(controller.signal);if(live){setMotion(next);setMotionError('')}}catch(e:any){if(live&&e?.name!=='AbortError')setMotionError(e?.message||'Global motion field unavailable')}finally{if(live)setMotionBusy(false)}};void load();const id=window.setInterval(()=>void load(),5*60*1000);return()=>{live=false;controller?.abort();window.clearInterval(id)}},[]);
 const sun=useMemo(()=>solarState(now),[now]),record=useMemo(()=>corpusState(address),[address]),coords=useMemo(()=>decodeAddress(address),[address]),mappedLat=useMemo(()=>-90+(coords.d+.5)/12*180,[coords.d]),mappedLon=useMemo(()=>-180+(coords.p*12+coords.r+.5)/144*360,[coords.p,coords.r]),eLat=Number.isFinite(targetLat)?Number(targetLat):mappedLat,eLon=Number.isFinite(targetLon)?Number(targetLon):mappedLon;
 const rotation=track==='SIDEREAL'?wrapLon(sun.gst):track==='SUN'?sun.subsolarLon:track==='SOURCE'?mappedLon:track==='TARGET'?eLon:freeRotation;
 useEffect(()=>{const count=typeof window!=='undefined'&&window.innerWidth<700?300:720;particles.current=seedParticles(count)},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;let raf=0,alive=true;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const draw=(time=0)=>{if(!alive)return;const rect=c.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),W=Math.max(340,Math.round(rect.width)),H=Math.max(500,Math.round(rect.height));if(c.width!==Math.round(W*dpr)||c.height!==Math.round(H*dpr)){c.width=Math.round(W*dpr);c.height=Math.round(H*dpr)}const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);const cx=W/2,cy=H*.49,R=Math.min(W*.39,H*.39),dt=lastFrame.current?Math.min(.06,(time-lastFrame.current)/1000):.016;lastFrame.current=time;
  const space=ctx.createRadialGradient(cx,cy,R*.25,cx,cy,R*2.2);space.addColorStop(0,mode==='SPACE'?'#06131d':'#06141a');space.addColorStop(.45,'#02080d');space.addColorStop(1,'#000306');ctx.fillStyle=space;ctx.fillRect(0,0,W,H);if(mode==='SPACE')for(let i=0;i<150;i++){const x=fract(Math.sin(i*83.17)*43758.5)*W,y=fract(Math.sin((i+21)*37.93)*12515.8)*H,a=.18+.6*fract(Math.sin(i*9.7)*815.2);ctx.fillStyle=`rgba(225,239,245,${a})`;ctx.fillRect(x,y,i%17===0?1.4:.7,i%17===0?1.4:.7)}
  const atm=ctx.createRadialGradient(cx,cy,R*.82,cx,cy,R*1.10);atm.addColorStop(0,'rgba(65,176,210,0)');atm.addColorStop(.78,'rgba(71,188,219,.04)');atm.addColorStop(.94,'rgba(93,203,229,.18)');atm.addColorStop(1,'rgba(80,183,218,0)');ctx.fillStyle=atm;ctx.fillRect(cx-R*1.16,cy-R*1.16,R*2.32,R*2.32);
  const ocean=ctx.createRadialGradient(cx-R*.31,cy-R*.37,R*.04,cx,cy,R);ocean.addColorStop(0,'#2a7894');ocean.addColorStop(.30,'#16546f');ocean.addColorStop(.68,'#0a344e');ocean.addColorStop(1,'#03131f');ctx.fillStyle=ocean;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();
  ctx.save();ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.clip();drawLand(ctx,rotation,cx,cy,R);if(mode==='MOTION'||mode==='PLANET')drawCloudTexture(ctx,motion,rotation,cx,cy,R,time);const sunView=project(sun.subsolarLat,sun.subsolarLon,rotation,cx,cy,R),night=ctx.createRadialGradient(sunView.x,sunView.y,R*.25,sunView.x,sunView.y,R*2.05);night.addColorStop(0,'rgba(255,237,178,.08)');night.addColorStop(.42,'rgba(0,7,17,.02)');night.addColorStop(.78,'rgba(0,5,14,.42)');night.addColorStop(1,'rgba(0,3,11,.78)');ctx.fillStyle=night;ctx.fillRect(cx-R,cy-R,R*2,R*2);drawLand(ctx,rotation,cx,cy,R);if(mode==='MOTION'||mode==='PLANET')drawMotionParticles(ctx,motion,particles.current,rotation,cx,cy,R,dt,running&&!reduced,mode==='MOTION');if(mode==='EVIDENCE'||mode==='PLANET')drawEvidence(ctx,evidence,eLat,eLon,rotation,cx,cy,R,time);ctx.restore();
  const term=terminatorPoints(sun,rotation,cx,cy,R);ctx.strokeStyle='rgba(255,213,132,.5)';ctx.lineWidth=1;ctx.beginPath();let started=false;for(const p of term){if(!p.front){started=false;continue}if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y)}ctx.stroke();if(mode==='SPACE'){for(const scale of [1.025,1.045,1.08]){ctx.strokeStyle=`rgba(89,190,224,${.18-(scale-1)})`;ctx.lineWidth=.8;ctx.beginPath();ctx.arc(cx,cy,R*scale,0,Math.PI*2);ctx.stroke()}const sp=project(sun.subsolarLat,sun.subsolarLon,rotation,cx,cy,R*1.035);if(sp.front){ctx.fillStyle='#ffdb89';ctx.beginPath();ctx.arc(sp.x,sp.y,5,0,Math.PI*2);ctx.fill()}}
  ctx.strokeStyle='rgba(133,222,230,.28)';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke();ctx.font='10px ui-monospace,monospace';ctx.fillStyle='rgba(211,233,236,.75)';ctx.fillText(`${mode} · ${rate===1?'REAL UTC':'TIME TRAVERSE '+rate+'×'} · ${sun.utc.toISOString()}`,14,22);if(motion){ctx.fillStyle='rgba(164,221,221,.72)';ctx.fillText(`GLOBAL RETURNED FIELD ${motion.observedCount}/${motion.sampleCount} · CΩ ${motion.summary.continuity.toFixed(2)} · W ${motion.summary.woven.toFixed(2)} · MAX WIND ${motion.summary.maxWindKph.toFixed(0)} km/h`,14,39)}ctx.fillStyle='rgba(239,205,139,.78)';ctx.fillText(`SUBSOLAR ${sun.subsolarLat.toFixed(2)}° / ${sun.subsolarLon.toFixed(2)}° · CENTER ${rotation.toFixed(2)}°`,14,H-18);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[sun,rotation,mappedLat,mappedLon,eLat,eLon,evidence,track,rate,mode,motion,running]);
 const pointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{drag.current={x:e.clientX,r:rotation};setTrack('FREE');setRunning(false);e.currentTarget.setPointerCapture(e.pointerId)},pointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drag.current)return;setFreeRotation(wrapLon(drag.current.r-(e.clientX-drag.current.x)*.35))},pointerUp=()=>{drag.current=null};
 const refreshMotion=async()=>{setMotionBusy(true);try{const next=await fetchEarthMotionStateR278();setMotion(next);setMotionError('')}catch(e:any){setMotionError(e?.message||'Global motion field unavailable')}finally{setMotionBusy(false)}};
 const age=motion?Math.max(0,Math.round((Date.now()-Date.parse(motion.observedAt))/1000)):null;
 return <section className='earth-now-plus earth-r279-instrument' data-earth-mode={mode}>
  <div className='earth-now-head'><div><span>EARTH NOW · SOURCE-FIRST PLANETARY INSTRUMENT</span><b>{mode==='MOTION'?'Global observed motion, interpolated continuously':mode==='EVIDENCE'?'Returned evidence in geographic context':mode==='SPACE'?'Earth, solar geometry and near-space context':'Earth as a living observed reference frame'}</b><small>Geographic geometry + UTC solar mechanics + returned public observations. R265/R266-derived continuity guides motion expression; it does not manufacture satellite pixels.</small></div><Globe2/></div>
  <div className='earth-now-grid'><div className='earth-now-stage'><canvas ref={canvas} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} aria-label={`Interactive ${mode.toLowerCase()} Earth view`}/><div className='earth-legend'><span><i className='sun-dot'/>computed solar terminator</span><span><i className='state-dot'/>returned-data motion field</span><span>land = bundled geographic geometry</span><span>cloud haze / particles = derived visualization over returned observations</span></div></div>
   <aside><div className='earth-kpi'><span>Global motion field</span><b>{motion?`${motion.observedCount}/${motion.sampleCount} RETURNED`:(motionBusy?'LOADING':'UNAVAILABLE')}</b><small>{age===null?'awaiting returned global state':`${age}s state age · ${motion?.provider}`}</small></div><div className='earth-kpi'><span>Maximum returned wind</span><b>{motion?`${motion.summary.maxWindKph.toFixed(0)} km/h`:'—'}</b><small>10 m current wind samples · sparse WGS84 grid</small></div><div className='earth-kpi'><span>Woven computation</span><b>{motion?`CΩ ${motion.summary.continuity.toFixed(3)} · W ${motion.summary.woven.toFixed(3)}`:'—'}</b><small>software-derived continuity over observed transitions</small></div><div className='earth-kpi'><span>Evidence target</span><b>{eLat.toFixed(2)}°, {eLon.toFixed(2)}°</b><small>{evidence?'returned evidence bound':'awaiting returned evidence'} · state {record.stateId.toLocaleString()}</small></div>
    <div className='earth-controls'><button type='button' onClick={()=>setRunning(v=>!v)}>{running?<><Pause/>Pause motion</>:<><Play/>Resume motion</>}</button><button type='button' onClick={()=>void refreshMotion()} disabled={motionBusy}><RefreshCw className={motionBusy?'spin':''}/>{motionBusy?'Refreshing':'Refresh global field'}</button><label>Earth orientation<select value={track} onChange={e=>setTrack(e.target.value as Track)}><option value='SIDEREAL'>Sidereal / UTC</option><option value='SUN'>Center on Sun</option><option value='SOURCE'>OMEGA address</option><option value='TARGET'>Evidence target</option><option value='FREE'>Free rotation</option></select></label><label>Time rate<select value={rate} onChange={e=>setRate(Number(e.target.value))}><option value='1'>1× real UTC</option><option value='60'>60× minute traversal</option><option value='3600'>3600× hour traversal</option><option value='86400'>86400× day traversal</option></select></label><button type='button' onClick={()=>{setNow(new Date());setRate(1);setTrack('SIDEREAL');setFreeRotation(0);setRunning(true)}}><RotateCcw/>Return to now</button></div>
   </aside></div>
  {motionError&&<div className='earth-r279-motion-error'>{motionError}</div>}
  <div className='earth-proof'><ShieldCheck/><span><b>Truth boundary:</b> directly returned observations remain distinct from interpolation and OMEGA calculus. Particle paths and cloud haze are visual interpolation of returned weather samples, not replacement satellite imagery. Missing source pixels remain missing; inferred state is labeled derived. External observation authority: {EXTERNAL_OBSERVATION_STATE}.</span></div>
 </section>
}
