export const EMPIRICAL_BENCHMARK_REVISION='R192';
export const EMPIRICAL_BENCHMARK_SCHEMA='OMEGA_EMPIRICAL_BENCHMARK_R192';
export const R192_BENCHMARK_LAWS=Object.freeze([
 'DATASET_AND_MODEL_FINGERPRINTS_ARE_REQUIRED',
 'EVALUATION_ROWS_MUST_BE_HELD_OUT_OR_PROSPECTIVELY_PRECOMMITTED',
 'RETROSPECTIVE_FROZEN_EVALUATION_IS_NOT_PROSPECTIVE_PREDICTION',
 'BASELINE_CLASS_MUST_BE_FROZEN_WITHOUT_READING_EVALUATION_LABELS',
 'ACCURACY_PRECISION_RECALL_F1_BALANCED_ACCURACY_MCC_AND_BRIER_REMAIN_SEPARATE',
 'ABLATION_MUST_COMPARE_THE_SAME_EVALUATION_ROWS',
 'IMPROVEMENT_OVER_BASELINE_IS_A_VALUE_SIGNAL_NOT_UNIVERSAL_PROOF',
 'BENCHMARK_RECEIPTS_NEVER_MUTATE_CANONSTATE',
 'R125_REMAINS_THE_ONLY_CANONSTATE_ADMISSION_AUTHORITY'
]);
const cl=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const div=(a,b)=>b?Number(a)/Number(b):0;
const hex64=v=>/^[a-f0-9]{64}$/i.test(String(v||''));
const stable=v=>{if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const out={};for(const k of Object.keys(v).sort())out[k]=stable(v[k]);return out}return v};
async function sha(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(v))));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function normalizedRow(row,threshold){const truth=Number(row?.truth)===1?1:0,score=Number.isFinite(Number(row?.score))?cl(Number(row.score)):null,predicted=row?.predicted===0||row?.predicted===1?Number(row.predicted):score==null?null:(score>=threshold?1:0);return{truth,score,predicted,split:String(row?.split||'').toUpperCase(),predictionCommittedAt:Number(row?.predictionCommittedAt)||null,outcomeObservedAt:Number(row?.outcomeObservedAt)||null,predictionProofSha256:String(row?.predictionProofSha256||'').toLowerCase()||null,id:String(row?.id||'')||null}}
export function binaryMetricsR192(rows,threshold=.5){const t=cl(Number(threshold)),clean=(Array.isArray(rows)?rows:[]).map(x=>normalizedRow(x,t)).filter(x=>x.predicted===0||x.predicted===1);let tp=0,tn=0,fp=0,fn=0,brierSum=0,brierN=0;for(const r of clean){if(r.truth===1&&r.predicted===1)tp++;else if(r.truth===0&&r.predicted===0)tn++;else if(r.truth===0&&r.predicted===1)fp++;else fn++;if(r.score!==null){brierSum+=(r.score-r.truth)**2;brierN++}}const total=tp+tn+fp+fn,accuracy=div(tp+tn,total),precision=div(tp,tp+fp),recall=div(tp,tp+fn),specificity=div(tn,tn+fp),f1=div(2*precision*recall,precision+recall),balancedAccuracy=(recall+specificity)/2,den=Math.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)),mcc=den?((tp*tn-fp*fn)/den):0;return{threshold,count:total,confusion:{tp,tn,fp,fn},accuracy,precision,recall,specificity,f1,balancedAccuracy,mcc,brier:brierN?brierSum/brierN:null,positivePrevalence:div(tp+fn,total),predictedPositiveRate:div(tp+fp,total)}}
function baselineRows(rows,baselineClass){return rows.map(x=>({...x,predicted:baselineClass,score:baselineClass}))}
function validate(input,rows){const errors=[];if(!String(input?.benchmarkId||'').trim())errors.push('BENCHMARK_ID_REQUIRED');if(!hex64(input?.datasetFingerprint))errors.push('DATASET_FINGERPRINT_SHA256_REQUIRED');if(!hex64(input?.modelFingerprint))errors.push('MODEL_FINGERPRINT_SHA256_REQUIRED');if(!(input?.baselineClass===0||input?.baselineClass===1))errors.push('FROZEN_BASELINE_CLASS_REQUIRED');if(!rows.length)errors.push('EVALUATION_ROWS_REQUIRED');const mode=String(input?.evaluationMode||'RETROSPECTIVE_FROZEN').toUpperCase();if(!['RETROSPECTIVE_FROZEN','PROSPECTIVE_PRECOMMITTED'].includes(mode))errors.push('EVALUATION_MODE_INVALID');for(const r of rows){if(r.predicted!==0&&r.predicted!==1)errors.push('PREDICTION_REQUIRED');if(!['TEST','HOLDOUT','PROSPECTIVE'].includes(r.split))errors.push('EVALUATION_SPLIT_MUST_BE_TEST_HOLDOUT_OR_PROSPECTIVE');if(mode==='PROSPECTIVE_PRECOMMITTED'){if(!r.predictionCommittedAt||!r.outcomeObservedAt||r.predictionCommittedAt>=r.outcomeObservedAt)errors.push('PROSPECTIVE_PREDICTION_MUST_PRECEDE_OUTCOME');if(!hex64(r.predictionProofSha256))errors.push('PROSPECTIVE_PREDICTION_PROOF_REQUIRED')}}return[...new Set(errors)]}
function delta(model,baseline){return{accuracy:model.accuracy-baseline.accuracy,precision:model.precision-baseline.precision,recall:model.recall-baseline.recall,f1:model.f1-baseline.f1,balancedAccuracy:model.balancedAccuracy-baseline.balancedAccuracy,mcc:model.mcc-baseline.mcc,brier:model.brier==null||baseline.brier==null?null:baseline.brier-model.brier}}
function ablationSummary(input,model){const rows=Array.isArray(input?.ablations)?input.ablations:[];return rows.map(x=>{const m=binaryMetricsR192(x?.rows||[],input.threshold??.5);return{id:String(x?.id||'ablation'),removed:Array.isArray(x?.removedFeatures)?x.removedFeatures.map(String):[],metrics:m,deltaFromFull:{f1:model.f1-m.f1,balancedAccuracy:model.balancedAccuracy-m.balancedAccuracy,mcc:model.mcc-m.mcc},sameEvaluationCount:m.count===model.count}})}
export async function evaluateFrozenBenchmarkR192(input={}){const threshold=cl(Number(input?.threshold??.5)),rows=(Array.isArray(input?.rows)?input.rows:[]).map(x=>normalizedRow(x,threshold)),errors=validate(input,rows);if(errors.length)return{ok:false,status:400,schema:EMPIRICAL_BENCHMARK_SCHEMA,revision:EMPIRICAL_BENCHMARK_REVISION,errors,canonicalMutation:false,canonicalAdmissionAuthority:'R125'};const model=binaryMetricsR192(rows,threshold),baseline=binaryMetricsR192(baselineRows(rows,input.baselineClass),threshold),improvement=delta(model,baseline),ablations=ablationSummary(input,model),valueSignal=model.count>=20&&improvement.f1>0&&improvement.balancedAccuracy>0&&improvement.mcc>=0,mode=String(input.evaluationMode||'RETROSPECTIVE_FROZEN').toUpperCase(),core={ok:true,status:200,schema:EMPIRICAL_BENCHMARK_SCHEMA,revision:EMPIRICAL_BENCHMARK_REVISION,benchmarkId:String(input.benchmarkId),datasetFingerprint:String(input.datasetFingerprint).toLowerCase(),modelFingerprint:String(input.modelFingerprint).toLowerCase(),evaluationMode:mode,featureSet:Array.isArray(input.featureSet)?input.featureSet.map(String):[],threshold,baselineClass:Number(input.baselineClass),evaluationCount:model.count,model,baseline,improvement,ablations,valueSignal:valueSignal?'VALUE_SIGNAL_OVER_FROZEN_MAJORITY_BASELINE':'NO_VALUE_SIGNAL_OVER_FROZEN_MAJORITY_BASELINE',prospectiveProof:mode==='PROSPECTIVE_PRECOMMITTED',canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:mode==='PROSPECTIVE_PRECOMMITTED'?'This receipt scores precommitted predictions whose proof timestamps precede outcomes. Statistical performance is evidence about this declared dataset/task only; it is not universal ontology, physical law, medical efficacy, or CanonState admission.':'This receipt is a frozen retrospective held-out benchmark. It may support comparative fit/utility on this dataset but cannot be described as prospective prediction. External predictive superiority requires prospective precommitment or independently replicated held-out evaluation.'};const receiptSha256=await sha(core);return{...core,receiptSha256}}
export function benchmarkManifestR192(){return{ok:true,schema:'OMEGA_EMPIRICAL_BENCHMARK_MANIFEST_R192',revision:EMPIRICAL_BENCHMARK_REVISION,laws:R192_BENCHMARK_LAWS,required:['benchmarkId','datasetFingerprint SHA-256','modelFingerprint SHA-256','evaluationMode','frozen baselineClass','TEST/HOLDOUT/PROSPECTIVE rows'],metrics:['accuracy','precision','recall','specificity','F1','balanced accuracy','MCC','Brier score when probabilities exist','confusion matrix'],baseline:'FROZEN_MAJORITY_CLASS_OR_OPERATOR_DECLARED_BASELINE_WITHOUT_EVALUATION_LABEL_READ',ablation:'same evaluation rows, declared removedFeatures',prospective:'prediction timestamp + proof SHA must precede outcome timestamp',canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'The benchmark harness is a falsification/comparison instrument. It does not train models, select a favorable test set after outcomes, or convert benchmark success into universal truth.'}}
