import {useMemo,useState} from 'react';
import {Activity,GitBranch,Save,ShieldCheck} from 'lucide-react';
import {buildForecastPlan} from './forecastRuntime';
import {corpusState,decodeAddress} from './corpusRuntime';
import SpecialistMotionFieldR36 from './SpecialistMotionFieldR36';

const cl=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
const fmt=(x:any,d=3)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(d):'—';
const score=(p:any)=>{const C=Number(p?.C||0),P=Number(p?.Phi||0),q=Number(p?.q||0),L=Number(p?.Lambda||0),proof=Number(p?.proof||p?.evidence||0),S=C*P/(q+L+.001);return cl(.65*(S/(1+S))+.35*proof)};
const coords=(a:number)=>{const c=decodeAddress(a);return `D${c.d+1} · P${c.p+1} · R${c.r+1} · L${c.l+1}`};
type Props={address:number;onAddress?:(n:number)=>void};
export default function ForecastSovereignPanel({address,onAddress}:Props){
 const[horizon,setHorizon]=useState(12),[selected,setSelected]=useState(''),[frozen,setFrozen]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem('omega.forecast.prior.v2')||'null')}catch{return null}});
 const plan=useMemo(()=>buildForecastPlan(address,horizon,'CANON_PHASE'),[address,horizon]),source=useMemo(()=>corpusState(address),[address]);
 const dominant=plan.corridors.find(c=>c.id===plan.summary.dominantCorridor)||plan.corridors[0],active=plan.corridors.find(c=>c.id===selected)||dominant;
 const end=active?.points[active.points.length-1],currentScore=score({C:source.metrics.continuity,Phi:source.metrics.plasticity,q:source.metrics.contradiction,Lambda:source.metrics.burden,proof:source.metrics.evidence}),endScore=end?score(end):currentScore,delta=endScore-currentScore;
 const freeze=()=>{const packet={id:`PRIOR-${Date.now().toString(36)}`,frozenAt:new Date().toISOString(),sourceAddress:address,sourceStateId:address+1,horizon,plan,futureObservationUsed:false};localStorage.setItem('omega.forecast.prior.v2',JSON.stringify(packet));setFrozen(packet)};
 const later=frozen&&frozen.sourceAddress!==address?corpusState(address):null,firstFrozen=frozen?.plan?.corridors?.find((c:any)=>c.id===frozen.plan.summary.dominantCorridor)||frozen?.plan?.corridors?.[0],frozenEnd=firstFrozen?.points?.[Math.min((firstFrozen?.points?.length||1)-1,Math.max(0,horizon-1))],observedScore=later?score({C:later.metrics.continuity,Phi:later.metrics.plasticity,q:later.metrics.contradiction,Lambda:later.metrics.burden,proof:later.metrics.evidence}):null,predictedScore=frozenEnd?score(frozenEnd):null,error=observedScore!=null&&predictedScore!=null?Math.abs(observedScore-predictedScore):null;
 const turning=active?.turningPoint,first=active?.points?.[0],last=active?.points?.[active.points.length-1];
 const description=active?`${active.mode} is one admissible computed corridor, weighted ${fmt(active.weight)}. It moves from state ${address+1} toward state ${(last?.address??address)+1} over ${horizon} legal transitions. ${turning?`Its first material turn occurs at +${turning.h}: ${turning.reason}.`:'No material turning point is detected inside the selected horizon.'}`:'';
 return <section className='special-app forecast-r36'>
  <header className='forecast-hero special-head'><div><span>FORECAST · Competing legal futures without pretending to observe the future</span><h2>What could happen next — and why</h2><p>Forecast compares legal model continuations from the current packet. It does not pretend future observations already exist. Select a corridor to inspect the actual state evolution instead of reading raw address strings.</p></div><div className='special-status'><b>{plan.corridors.length} CORRIDORS</b><small>{plan.timeUnit}</small></div></header>
  <div className='forecast-controls'><label>How far forward?<input type='range' min='1' max='36' value={horizon} onChange={e=>setHorizon(Number(e.target.value))}/><b>{horizon} transitions</b></label><button className='gold' onClick={freeze}><Save size={15}/>Freeze source-only prior</button><small>future observation used: NO</small></div>
  <div className='forecast-summary-grid'><article><span>NOW</span><b>State {address+1}</b><small>{coords(address)} · {source.metrics.decision}</small></article><article><span>LEADING CORRIDOR</span><b>{dominant?.mode||'—'}</b><small>weight {fmt(dominant?.weight)}</small></article><article><span>SELECTED OUTCOME</span><b>{fmt(currentScore)} → {fmt(endScore)}</b><small>{delta>=0?'+':''}{fmt(delta)} normalized change</small></article><article><span>DIVERGENCE</span><b>{plan.summary.finalUniqueAddresses} states</b><small>{plan.summary.finalDecisionVariants} decision classes</small></article></div>
  <SpecialistMotionFieldR36 address={address} steps={Math.min(30,horizon+1)} label='ADMITTED REFERENCE MOTION' mode='FORECAST' onAddress={onAddress}/>
  <div className='forecast-grid'><div className='forecast-cards'>{plan.corridors.map(c=>{const e=c.points[c.points.length-1],isActive=c.id===active?.id;return <button key={c.id} className={'forecast-card '+(isActive?'active':'')} onClick={()=>setSelected(c.id)}><div><span>{c.variant}</span><strong>{c.mode}</strong></div><b>{fmt(c.weight)}</b><p>State {address+1} → {(e?.address??address)+1} · {e?coords(e.address):'—'}</p><small>utility {fmt(c.avgUtility)} · proof {fmt(c.avgProof)} · future {fmt(c.avgFuture)} · temporal {fmt(c.avgTemporal)}</small></button>})}</div><aside className='forecast-insight forecast-card'><span>SELECTED CORRIDOR</span><h3>{active?.mode||'—'} · {active?.variant||'—'}</h3><p>{description}</p><div className='forecast-turns'>{active?.points.slice(0,Math.min(8,horizon)).map((x:any,i:number)=>{const prior=i?active.points[i-1].address:address;return <div key={`${active.id}-${x.h}`} onClick={()=>onAddress?.(x.address)} role={onAddress?'button':undefined}><b>+{x.h}</b><span>state {prior+1} → {x.address+1}<small>{coords(x.address)} · decision {x.allModes.mode188Decision}</small></span><strong>{fmt(x.proof,2)}</strong></div>})}</div>{first&&last&&<p><GitBranch size={14}/> First {first.address+1} · last {last.address+1} · average jerk {fmt(active.avgJerk)}.</p>}</aside></div>
  <details className='r36-disclosure'><summary>Dominant motion trace · human-readable state traversal</summary><div className='forecast-turns'>{dominant?.points.slice(0,Math.min(12,horizon)).map((x:any)=><div key={`dominant-${x.h}`}><b>+{x.h}</b><span>state {x.address+1}<small>edge {x.edge} · decision {x.allModes.mode188Decision} · temporal {fmt(x.temporal.score)} · directional {fmt(x.temporal.directional)} · jerk {fmt(x.temporal.jerk)} · proof {fmt(x.proof)}</small></span><strong>{coords(x.address)}</strong></div>)}</div><p>Each row is one legal model transition, not an invented minute/hour interval.</p></details>
  {frozen&&<details className='r36-disclosure'><summary>Frozen-prior scoring · {frozen.id}</summary><div className='answer'><p>Frozen at source state {frozen.sourceStateId} for {frozen.horizon} transitions. future observation used: NO.</p>{later?<p><Activity size={13}/> Current later-state score {fmt(observedScore)} versus frozen dominant estimate {fmt(predictedScore)} · absolute error {fmt(error)}.</p>:<p>Move to a later canonical state before scoring. Immediate self-comparison remains intentionally held.</p>}</div></details>}
  <footer className='boundary'><ShieldCheck size={15}/>{plan.boundary}</footer>
 </section>
}
