import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Cpu,Loader2,PauseCircle,Play,RefreshCw,ShieldCheck,TriangleAlert,Waypoints} from 'lucide-react';
import {api} from './platformAdapter';
import {defaultCommandPlan,validateCommandPlan} from './hybridCommandRuntime';
import {buildFullSystemMissionObjectiveR153,fullSystemStateContextR153,R153_FULL_SYSTEM_CONTRACT} from './fullSystemCompletionR153.js';
import './fullSystemCompletionR153.css';

const R153_SOURCE_SCHEMA='OMEGA_SOVEREIGN_FULL_BUILD_R151';
const R153_MAX_CYCLES=12;
const ALLOWED=['INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','WRITE_TEXT'];
const MISSION_TERMINAL=new Set(['COMPLETE','DONE','FAILED','CANCELLED','REPAIR_REQUIRED','HOLD_PROJECT_NOT_FOUND','HOLD_NO_DECLARED_VERIFICATION','HOLD_MAX_CYCLES','HOLD_DEVICE_PROOF','HOLD_PATCH_PROPOSAL','FAILED_PACKAGE']);
const JOB_TERMINAL=new Set(['COMPLETE','DONE','FAILED','CANCELLED']);
const missionTerminal=(v:any)=>MISSION_TERMINAL.has(String(v||'').toUpperCase());
const jobTerminal=(v:any)=>JOB_TERMINAL.has(String(v||'').toUpperCase());
const age=(n:any)=>{const t=Number(n)||0;if(!t)return'never';const s=Math.max(0,Math.round((Date.now()-t)/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};

type Props={onNavigate:(name:string)=>void};
export default function FullSystemCompletionR153({onNavigate}:Props){
 const[hybrid,setHybrid]=useState<any>(null),[mission,setMission]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const root=(()=>{try{return String(window.localStorage.getItem('omega:hybrid:projectRoot')||'.').trim()||'.'}catch{return'.'}})();
 const devices=Array.isArray(hybrid?.devices)?hybrid.devices:[],onlineDevices=devices.filter((d:any)=>d?.online&&!d?.revoked),device=onlineDevices[0]||null,online=Boolean(device&&hybrid?.nativeExecutionClaimed===true);
 const missionState=String(mission?.status||'IDLE').toUpperCase(),job=mission?.currentJob||null,jobState=String(job?.status||'').toUpperCase(),active=Boolean(mission&&!missionTerminal(missionState)&&(['ACTIVE','PAUSED','QUEUED','PENDING','RUNNING'].includes(missionState)||Boolean(jobState&&!jobTerminal(jobState))));
 const held=Boolean(mission&&missionTerminal(missionState)&&!['COMPLETE','DONE'].includes(missionState));
 const familyRows=useMemo(()=>Object.entries(R153_FULL_SYSTEM_CONTRACT.successor.states),[]);
 const refresh=async()=>{try{const[h,m]=await Promise.all([api.get<any>('/api/hybrid/status'),api.get<any>('/api/missions').catch(()=>null)]);setHybrid(h.data||{});const missions=Array.isArray(m?.data?.missions)?m.data.missions:[];const current=mission?.id?missions.find((x:any)=>x.id===mission.id):missions.find((x:any)=>['ACTIVE','PAUSED','QUEUED','PENDING','RUNNING'].includes(String(x?.status||'').toUpperCase()))||missions[0];if(current)setMission(current)}catch(e:any){setMessage(`Status read failed safely: ${e?.message||String(e)}`)}};
 useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),3500);return()=>window.clearInterval(id)},[mission?.id]);
 const run=async()=>{if(busy||active)return;if(!online||!device){setMessage('Current authenticated PC heartbeat is required. Open Hybrid Link, run the R127 zero-drift connector from the approved root, then return here.');return}setBusy(true);setMessage('');try{const initial=defaultCommandPlan('BUILD','AUTO_BUILD',root),validation=validateCommandPlan(initial,root,[]);if(!validation.passed)throw new Error(validation.errors.join(' ')||'Initial bounded build plan did not validate.');const objective=buildFullSystemMissionObjectiveR153(root);const stateContext=JSON.stringify({...fullSystemStateContextR153(),surface:'FullSystemCompletionR153',adaptiveMissionEngine:'R153',sourceMissionSchema:R153_SOURCE_SCHEMA,maxCycles:R153_MAX_CYCLES,device:{id:device.id,name:device.name||null,platform:device.platform||null},approvedRoot:root,previousMission:mission&&missionTerminal(missionState)?{id:mission.id,status:missionState,holdReason:mission.holdReason||null}:null});const r=await api.post<any>('/api/missions',{objective,threadId:'',stateContext,draft:{schema:R153_SOURCE_SCHEMA,action:'BUILD',profile:'AUTO_BUILD',projectPath:root,instructions:objective,allowedDomains:[],steps:validation.steps},targetDeviceId:device.id,allowedOps:ALLOWED,maxCycles:R153_MAX_CYCLES,confirmedMission:true});if(!r.data?.mission?.id)throw new Error('No durable mission identity returned; nothing is treated as started.');setMission(r.data.mission);setMessage(`R151 whole-build request ${r.data.mission.id} entered the R153 adaptive proof engine on ${device.name||device.id}. Discovery, repair, verification and packaging advance only from returned host proof.`)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const control=async(action:'pause'|'resume')=>{if(!mission?.id||busy||missionTerminal(missionState))return;setBusy(true);try{const r=await api.post<any>(`/api/missions/${encodeURIComponent(mission.id)}/${action}`,{});if(r.data?.mission)setMission(r.data.mission);setMessage(action==='pause'?'Mission paused. No later cycle will queue until resumed.':'Mission resumed inside the unchanged R153 proof/mutation envelope.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 return <section className={'r153-completion-executor '+(online?'online':'offline')+(held?' held':'')} aria-label='R153 whole-system completion executor'>
  <header><div><span>R151 → R153 · COMPLETE THE ACTUAL ONE SYSTEM</span><h3>24 families · 100 systems · 44 routes · one governed adaptive build mission</h3><p>This is not another redesign. It compiles the restored successor ledger, one-system workbook authority, route/capability contracts, current Hybrid execution spine and proof/admission laws into the exact R151 request schema consumed by the existing R153 adaptive mission engine.</p></div><div className='r153-executor-state'>{online?<CheckCircle2/>:<TriangleAlert/>}<span><b>{online?'PC PROOF CURRENT':'PC PROOF REQUIRED'}</b><small>{online?`${device?.name||device?.id} · heartbeat ${age(device?.lastSeen)}`:'Browser/cloud work remains live; native build cannot be fictionalized.'}</small></span></div></header>
  <div className='r153-executor-kpis'><article><b>{R153_FULL_SYSTEM_CONTRACT.successor.implemented}</b><span>implemented successors</span></article><article><b>{R153_FULL_SYSTEM_CONTRACT.successor.truthGated}</b><span>evidence/device gates</span></article><article><b>{R153_FULL_SYSTEM_CONTRACT.successor.restorationDebt}</b><span>successor restoration debt</span></article><article><b>{R153_FULL_SYSTEM_CONTRACT.inventory.routes}</b><span>registered routes</span></article><article><b>{R153_FULL_SYSTEM_CONTRACT.inventory.sourceModes}</b><span>source modes</span></article><article><b>{R153_FULL_SYSTEM_CONTRACT.inventory.canonLenses}</b><span>canon lenses</span></article></div>
  <div className='r153-family-state' aria-label='R153 family successor states'>{familyRows.map(([id,state])=><span key={id} data-state={state as string}><code>{id}</code>{String(state).replaceAll('_',' ')}</span>)}</div>
  <div className='r153-stage-strip'>{R153_FULL_SYSTEM_CONTRACT.stages.map((s:any)=><button key={s.order} onClick={()=>onNavigate(s.route)} title={s.proof}><code>{String(s.order).padStart(2,'0')}</code><span><b>{s.menu}</b><small>{s.goal}</small></span><Waypoints/></button>)}</div>
  <div className='r153-executor-actions'>{!online?<button className='primary' onClick={()=>onNavigate('Hybrid Link')}><Cpu/>Connect / prove this PC first</button>:missionState==='PAUSED'?<button className='primary' onClick={()=>void control('resume')} disabled={busy}><Play/>Resume whole-system mission</button>:active?<button onClick={()=>void control('pause')} disabled={busy}><PauseCircle/>Pause mission</button>:<button className='primary' onClick={()=>void run()} disabled={busy}>{busy?<Loader2 className='spin'/>:<Play/>}{held?'START NEW BOUNDED RETRY':'RUN COMPLETE 24-FAMILY BUILD'}</button>}<button onClick={()=>void refresh()} disabled={busy}><RefreshCw/>Refresh proof</button><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Open receipts / proof</button></div>
  {mission&&<div className='r153-mission-receipt'><span><b>{missionState} · {String(mission.id||'').slice(0,18)}</b><small>{Number(mission.cycles||0)}/{Number(mission.maxCycles||R153_MAX_CYCLES)} cycles · {mission?.adaptiveRevision?`adaptive ${mission.adaptiveRevision} · `:''}job {job?.id?String(job.id).slice(0,16):'pending'} · {jobState||'no returned job yet'}{mission?.holdReason?` · ${mission.holdReason}`:''}</small></span><code>{job?.returnPacket?.resultFingerprint||'R141/R142 return fingerprint pending'}</code></div>}
  {message&&<div className='r153-executor-message'>{message}</div>}
  <footer><ShieldCheck/><span>{R153_FULL_SYSTEM_CONTRACT.completionDefinition}</span><small>{R153_FULL_SYSTEM_CONTRACT.truthBoundary}</small></footer>
 </section>
}
