import {useEffect,useState} from 'react';
import {CheckCircle2,FileCheck2,GitCommitHorizontal,RefreshCw,ShieldCheck} from 'lucide-react';

type Promotion={candidateSha?:string|null;promotedMergeSha?:string|null;rollbackSha?:string|null;authority?:string};
type Receipt={schema?:string;state?:string;generatedAt?:string;source?:{repository?:string;sha?:string;branch?:string;role?:string};promotion?:Promotion;qa?:{required?:string;upstreamGate?:string};package?:{builder?:string;output?:string;portable?:boolean;appDeploy?:boolean};deployment?:{authority?:string;canonicalUrl?:string;publicWorkerMutationAuthority?:boolean};workflow?:{runId?:string;runNumber?:string;name?:string};truthBoundary?:string;receiptSha256?:string};
type ReleaseEvidence={schema?:string;canonicalUrl?:string;source?:Receipt['source'];promotionLineage?:Promotion;packageReceipt?:{schema?:string;receiptSha256?:string;state?:string;workflow?:Receipt['workflow']};runtimeVersion?:{id?:string;tag?:string|null;timestamp?:string|null};runtimeAuthority?:{cloudflareVersionMetadata?:string;publicWorkerMutationAuthority?:boolean};externalGates?:{candidateQa?:string;postDeployVerification?:string;rollback?:string};truthBoundary?:string;evidenceSha256?:string;returnedAt?:string};
type RuntimeAttestationR144={schema?:string;revision?:string;canonicalUrl?:string;source?:Receipt['source'];promotionLineage?:Promotion;packageReceipt?:ReleaseEvidence['packageReceipt'];runtimeVersion?:ReleaseEvidence['runtimeVersion'];authorityChain?:{uiOperationChain?:{revision?:string;schema?:string};capabilityLifecycle?:{revision?:string;schema?:string};hybridExecutionProof?:{revision?:string;authority?:string};canonicalAdmission?:{revision?:string;authority?:string}};lifecycle?:{implemented?:string;tested?:string;merged?:string;deployed?:string;live?:string;verified?:string};bindings?:{sourceSha?:string|null;packageReceiptSha256?:string|null;cloudflareVersionId?:string|null;releaseEvidence?:string;buildReceipt?:string};runtimeAuthority?:{cloudflareVersionMetadata?:string;publicWorkerMutationAuthority?:boolean;canonicalMutation?:boolean;admissionAuthority?:string};truthBoundary?:string;attestationSha256?:string;returnedAt?:string};

const trim=(value?:string|null,n=14)=>!value?'UNAVAILABLE':value.length>n?`${value.slice(0,n)}…`:value;

export default function GovernedBuildReceiptPanel(){
 const[receipt,setReceipt]=useState<Receipt|null>(null),[evidence,setEvidence]=useState<ReleaseEvidence|null>(null),[attestation,setAttestation]=useState<RuntimeAttestationR144|null>(null),[live,setLive]=useState<any>(null),[error,setError]=useState('');
 const refresh=async()=>{setError('');try{const[r,e,a,s]=await Promise.all([fetch('/omega-build-receipt.json',{cache:'no-store'}),fetch('/api/release-evidence',{cache:'no-store'}),fetch('/api/runtime-attestation',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);if(!r.ok)throw new Error(`build receipt HTTP ${r.status}`);if(!e.ok)throw new Error(`release evidence HTTP ${e.status}`);if(!a.ok)throw new Error(`runtime attestation HTTP ${a.status}`);if(!s.ok)throw new Error(`status HTTP ${s.status}`);setReceipt(await r.json());setEvidence(await e.json());setAttestation(await a.json());setLive(await s.json())}catch(err:any){setError(err?.message||String(err))}};
 useEffect(()=>{void refresh()},[]);
 const sha=receipt?.source?.sha||'UNAVAILABLE',version=evidence?.runtimeVersion?.id||attestation?.runtimeVersion?.id||'UNAVAILABLE',lineage=evidence?.promotionLineage||receipt?.promotion||attestation?.promotionLineage;
 const receiptBound=Boolean(receipt?.receiptSha256&&evidence?.packageReceipt?.receiptSha256===receipt.receiptSha256&&attestation?.packageReceipt?.receiptSha256===receipt.receiptSha256);
 const canonicalBound=Boolean(evidence?.canonicalUrl&&receipt?.deployment?.canonicalUrl===evidence.canonicalUrl&&attestation?.canonicalUrl===evidence.canonicalUrl);
 const lineageBound=Boolean(lineage?.authority==='GITHUB_MERGE_PARENTS'&&lineage.candidateSha&&lineage.promotedMergeSha&&lineage.rollbackSha);
 const attestationBound=Boolean(attestation?.schema==='OMEGA_RUNTIME_DEPLOYMENT_ATTESTATION_R144'&&attestation?.revision==='R144'&&attestation?.bindings?.sourceSha===sha&&attestation?.bindings?.cloudflareVersionId===version&&attestation?.attestationSha256);
 const releaseTimeline=[
  {label:'1 · Packaged source',value:sha,state:sha==='UNAVAILABLE'?'HOLD':'BOUND'},
  {label:'2 · Candidate head',value:lineage?.candidateSha||'EXTERNAL_RELEASE_LEDGER_REQUIRED',state:lineageBound?'BOUND':'EXTERNAL'},
  {label:'3 · Candidate QA',value:evidence?.externalGates?.candidateQa||receipt?.qa?.upstreamGate||'EXTERNAL_GITHUB_EVIDENCE_REQUIRED',state:'EXTERNAL'},
  {label:'4 · Package receipt',value:receipt?.receiptSha256||'UNAVAILABLE',state:receiptBound?'BOUND':'HOLD'},
  {label:'5 · Promoted merge',value:lineage?.promotedMergeSha||'EXTERNAL_RELEASE_LEDGER_REQUIRED',state:lineageBound?'BOUND':'EXTERNAL'},
  {label:'6 · Runtime version',value:version,state:version==='UNAVAILABLE'?'HOLD':'BOUND'},
  {label:'7 · Canonical verify',value:evidence?.externalGates?.postDeployVerification||'EXTERNAL_FIRST_HAND_PROBE_REQUIRED',state:canonicalBound?'TARGET_BOUND':'HOLD'},
  {label:'8 · Rollback',value:lineage?.rollbackSha||evidence?.externalGates?.rollback||'EXTERNAL_RELEASE_LEDGER_REQUIRED',state:lineageBound?'BOUND':'EXTERNAL'}
 ];
 const lifecycleTimeline=[
  {label:'Implemented',value:attestation?.lifecycle?.implemented||'UNAVAILABLE',state:attestation?.lifecycle?.implemented==='IMPLEMENTED'?'BOUND':'HOLD'},
  {label:'Tested',value:attestation?.lifecycle?.tested||evidence?.externalGates?.candidateQa||'EXTERNAL_GITHUB_EVIDENCE_REQUIRED',state:'EXTERNAL'},
  {label:'Merged',value:attestation?.lifecycle?.merged||lineage?.promotedMergeSha||'EXTERNAL_RELEASE_LEDGER_REQUIRED',state:lineageBound?'BOUND':'EXTERNAL'},
  {label:'Deployed',value:attestation?.lifecycle?.deployed||version,state:version==='UNAVAILABLE'?'HOLD':'BOUND'},
  {label:'Live',value:attestation?.lifecycle?.live||'UNAVAILABLE',state:attestation?.lifecycle?.live==='CURRENT_RUNTIME_RESPONSE_RETURNED'?'BOUND':'HOLD'},
  {label:'Verified',value:attestation?.lifecycle?.verified||evidence?.externalGates?.postDeployVerification||'EXTERNAL_FIRST_HAND_PROBE_REQUIRED',state:'EXTERNAL'}
 ];
 return <section className='panel governed-build-receipt' data-r144-runtime-attestation={attestationBound?'BOUND':'HOLD'}><div className='section-head'><div><p className='overline'>R144 · GOVERNED RUNTIME DEPLOYMENT ATTESTATION · READ ONLY</p><h2>Implemented ≠ tested ≠ merged ≠ deployed ≠ live ≠ verified</h2></div><button onClick={()=>void refresh()} aria-label='Refresh governed build receipt and runtime attestation'><RefreshCw size={16}/>Refresh</button></div>{error?<div className='boundary'><ShieldCheck size={15}/>ATTESTATION UNAVAILABLE · {error}</div>:receipt&&evidence&&attestation?<><div className='buildout-score'><div><span>Package state</span><b>{receipt.state||'UNKNOWN'}</b></div><div><span>Packaged source</span><b>{trim(sha,12)}</b></div><div><span>Merge lineage</span><b>{lineageBound?'BOUND':'EXTERNAL'}</b></div><div><span>Receipt link</span><b>{receiptBound?'MATCH':'HOLD'}</b></div><div><span>Worker version</span><b>{trim(version,12)}</b></div><div><span>R144 attestation</span><b>{attestationBound?'BOUND':'HOLD'}</b></div><div><span>Runtime</span><b>{live?.ok===false?'DEGRADED':'RETURNED'}</b></div></div><div className='buildout-lanes'><article><GitCommitHorizontal/><b>EXACT PACKAGED SOURCE</b><p>{receipt.source?.repository} · {sha}</p></article><article><CheckCircle2/><b>AUTHORITY CHAIN</b><p>R143 UI operation chain → R142 capability lifecycle → R141 Hybrid exact return proof → R125 CanonState admission</p></article><article><FileCheck2/><b>RUNTIME ATTESTATION</b><p>{attestation.attestationSha256||'UNAVAILABLE'} · Cloudflare version {version}</p></article></div><div className='release-evidence-timeline' aria-label='Governed release evidence timeline'>{releaseTimeline.map(step=><article key={step.label} className='release-evidence-step'><span>{step.label}</span><b>{step.state}</b><p title={step.value}>{trim(step.value,28)}</p></article>)}</div><div className='release-evidence-timeline' aria-label='R144 truth-separated deployment lifecycle'>{lifecycleTimeline.map(step=><article key={step.label} className='release-evidence-step'><span>{step.label}</span><b>{step.state}</b><p title={step.value}>{trim(step.value,28)}</p></article>)}</div><div className='boundary'><ShieldCheck size={15}/>{attestation.truthBoundary}</div>{!canonicalBound&&<div className='boundary'><ShieldCheck size={15}/>Canonical URL binding HOLD · receipt, release evidence and runtime attestation must resolve to the same canonical Worker.</div>}</>:<div className='boundary'><ShieldCheck size={15}/>Loading governed release evidence and R144 runtime attestation…</div>}</section>
}
