export type TemporalSampleR301={t:number;[key:string]:unknown};
export function temporalSampleIndexR301(samples:TemporalSampleR301[],target:number){if(!samples.length)return -1;let lo=0,hi=samples.length-1;if(target<=samples[0].t)return 0;if(target>=samples[hi].t)return hi;while(lo+1<hi){const m=(lo+hi)>>1;if(samples[m].t<=target)lo=m;else hi=m}return Math.abs(samples[lo].t-target)<=Math.abs(samples[hi].t-target)?lo:hi}
export function temporalWindowR301(samples:TemporalSampleR301[],target:number,radius=2){const i=temporalSampleIndexR301(samples,target);if(i<0)return[];const r=Math.max(0,Math.min(24,Math.floor(radius)));return samples.slice(Math.max(0,i-r),Math.min(samples.length,i+r+1))}

export type TruthAtlasManifestR301={format:string;version:string;title:string;data?:unknown;visual?:unknown;proof?:{checksums?:Record<string,string>};sourceClass?:'OBSERVED'|'DERIVED'|'MODEL'|'ARCHIVE'};
export function validateTruthAtlasManifestR301(x:unknown){const errors:string[]=[];if(!x||typeof x!=='object')return{ok:false,errors:['manifest must be an object']};const m=x as Partial<TruthAtlasManifestR301>;if(m.format!=='truthatlas')errors.push('format must be truthatlas');if(typeof m.version!=='string'||!m.version.trim())errors.push('version required');if(typeof m.title!=='string'||!m.title.trim())errors.push('title required');if(!m.sourceClass)errors.push('sourceClass required');if(m.proof?.checksums&&Object.values(m.proof.checksums).some(v=>!/^[a-f0-9]{64}$/i.test(v)))errors.push('checksums must be sha256 hex');return{ok:errors.length===0,errors,manifest:m}}

export type RepresentationLensInputR301={domain:number;phase:number;regulation:number;depth:number};
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
export function representationLensR301(input:RepresentationLensInputR301){const d=Math.max(1,Math.min(12,Math.round(input.domain))),p=Math.max(1,Math.min(12,Math.round(input.phase))),r=Math.max(1,Math.min(12,Math.round(input.regulation))),l=Math.max(1,Math.min(12,Math.round(input.depth)));const rt=2*Math.PI*(r-1)/12,lt=2*Math.PI*(l-1)/12,dt=2*Math.PI*(d-1)/12;let build=clamp(.18+.62*Math.exp(-((p-3)**2)/8)+.16*Math.max(0,Math.sin(rt)));let prune=clamp(.14+.64*Math.exp(-((p-10.3)**2)/7)+.16*Math.max(0,-Math.sin(rt)));let base=clamp(.30+.44*Math.exp(-((p-5)**2)/12)+.08*Math.cos(dt-lt));let closure=clamp(.16+.68*Math.exp(-((p-12)**2)/5.8)+.18*Math.exp(-((r-12)**2)/10));let seed=clamp(.12+.58*Math.exp(-((p-1)**2)/5.5)+.35*Math.exp(-((l-1)**2)/7));const sum=build+prune+base+closure+seed||1;const weights={build:build/sum,prune:prune/sum,base:base/sum,closure:closure/sum,seed:seed/sum};return{address:{domain:d,phase:p,regulation:r,depth:l},weights,authority:'MODEL_SPACE_REPRESENTATION_ONLY' as const,resolutionClaim:'ADDRESS_RESOLUTION_NOT_PHYSICAL_DIMENSION' as const}}

export type SvgSemanticGroupR301={id:string;role:'STATE'|'EDGE'|'OPERATOR'|'ANNOTATION'|'TRACE'|'OTHER';source:string;transform?:string};
export function validateSvgSemanticGroupsR301(groups:SvgSemanticGroupR301[]){const ids=new Set<string>(),errors:string[]=[];for(const g of groups){if(!g.id||ids.has(g.id))errors.push(`invalid/duplicate id ${g.id||'EMPTY'}`);ids.add(g.id);if(!g.source)errors.push(`missing source ${g.id}`)}return{ok:errors.length===0,errors,count:groups.length}}

const PSC_OPERATOR_LEXICON_R301={parent:['parent','root','origin','source','trunk','center'],accumulation:['accumulate','build','burden','thicker','larger','load','merge'],scar:['scar','damage','crack','history','memory','defect'],constraint:['limit','boundary','constraint','pressure','rule','gravity'],phase:['phase','change','transition','state','cycle'],carry:['carry','continue','survive','transfer','inherit'],motion:['motion','move','rate','direction','frame','scale'],water:['water','flow','river','wave','channel'],crystal:['crystal','lattice','coherence','symmetry'],light:['light','sun','pattern','interference','mandala']} as const;
export function classifyPscOperatorsR301(query:string){const q=query.toLowerCase();const hits=Object.entries(PSC_OPERATOR_LEXICON_R301).filter(([,terms])=>terms.some(t=>q.includes(t))).map(([k])=>k);return{operators:hits.length?hits:['parent','scar','constraint','phase','carry'],authority:'RETRIEVAL_HINT_ONLY' as const}}
export type PscIndexRowR301={id:string;cat?:string;domain?:string;root?:string;func?:string;opdef?:string;fdef?:string;pred?:string;base?:string;data?:string;gate?:string;questions?:string[];scores?:{Total?:number;Prob?:number;Comp?:number;MR?:number};[key:string]:unknown};
const toksR301=(s:string)=>(s.toLowerCase().match(/[a-z0-9_]{3,}/g)||[]);
export function rankPscRowsR301(rows:PscIndexRowR301[],query:string,limit=8){const bounded=Math.max(1,Math.min(20,Math.floor(limit))),qt=toksR301(query),uniq=new Set(qt);const scored=rows.map((r,index)=>{const text=[r.cat,r.domain,r.root,r.func,r.opdef,r.fdef,r.pred,(r.questions||[]).join(' ')].filter(Boolean).join(' ');const rt=new Set(toksR301(text));let lexical=0;for(const t of uniq)if(rt.has(t))lexical++;const s=r.scores||{};const score=lexical*10+(Number(s.Total)||0)*.1+(Number(s.Prob)||0)*2;return{index,row:r,score,lexical}});scored.sort((a,b)=>b.score-a.score||a.index-b.index);return{hits:scored.slice(0,bounded),authority:'DETERMINISTIC_ARCHIVE_RETRIEVAL_ONLY' as const,queryTokens:[...uniq]}}

export type RendererProofAdapterInputR301={rendererId:string;harnessId:string;sourceClass:'OBSERVED'|'DERIVED'|'MODEL'|'ARCHIVE';inputReceipt:string;outputReceipt?:string};
export function rendererProofAdapterR301(input:RendererProofAdapterInputR301){const errors:string[]=[];if(!input.rendererId.trim())errors.push('rendererId required');if(!input.harnessId.trim())errors.push('harnessId required');if(!input.inputReceipt.trim())errors.push('inputReceipt required');return{ok:errors.length===0,errors,receipt:{...input,proofState:input.outputReceipt?'RETURNED_UNVERIFIED':'READY',authority:'EVIDENCE_ADAPTER_ONLY' as const}}}

export const HTML_SVG_RUNTIME_BOUNDARY_R301={createsCanonState:false,createsExecutionAuthority:false,claimsObservedReality:false,allowsArbitrarySvgScript:false,medicalAuthority:false,truthAtlasRequiresSourceClass:true,retrievalDispatchAuthority:false,rendererProofAuthority:false} as const;
