export const HTML_SVG_RECOVERY_SCHEMA_R301='OMEGA_HTML_SVG_CAPABILITY_RECOVERY_R301' as const;
export type RecoveryStateR301='RECOVER_NOW'|'ADAPT'|'DONOR_ONLY'|'GATED';
export type HtmlSvgCapabilityR301={id:string;artifact:string;driveId:string;kind:'HTML'|'SVG_FAMILY'|'BUILD_GRAPH';masterMenu:string;surface:string;state:RecoveryStateR301;extract:string[];apply:string[];proof:string[];boundary:string};
export const HTML_SVG_CAPABILITIES_R301:HtmlSvgCapabilityR301[]=[
{id:'HSV-01',artifact:'omega_visual_atlas_live.html',driveId:'1YMU4sv23bluaF3-JiR2wTBMRMIlwXQKo',kind:'HTML',masterMenu:'Data / Atlas',surface:'Modes',state:'RECOVER_NOW',extract:['time-series playback contract','12-phase occupancy','ledger/scar/q/entropy/width metrics','top-k state trace','scrub/play/reset state machine','CSV/WebSocket adapter seam'],apply:['shared temporal atlas controller','proof-aware trace inspector','recorded/live stream adapter'],proof:['deterministic scrub identity','recorded/live source label','no synthetic live claim'],boundary:'Embedded preview data is historical donor evidence, not a current live engine feed.'},
{id:'HSV-02',artifact:'full_modes_mode188_working_glyph_interface.html',driveId:'1kVEJHALAflxzUjZyNZPG6CMROi0sMSb3',kind:'HTML',masterMenu:'Data / Atlas',surface:'Modes',state:'RECOVER_NOW',extract:['state coordinates','simplex projection','coupling edges','1+6 neighborhood','shell transport timeline','turn-event flags','proper-time/constraint/prune/scar readouts'],apply:['state-space inspector','neighborhood explorer','turn-event timeline','mode comparison geometry'],proof:['selected-state identity','neighbor determinism','source/model labels'],boundary:'Recover the interaction/state schema; do not promote archived coordinates as empirical truth.'},
{id:'HSV-03',artifact:'mind_circuit_truthatlas.html',driveId:'1j1abdc8IavzBgXq5G4gdTbDR-yzumO8K',kind:'HTML',masterMenu:'Proof & Governance',surface:'Evidence & Proof',state:'RECOVER_NOW',extract:['portable data+SVG+motion+explanation+proof package','embedded JSON manifest','read/data/proof views','checksum-ready bundle contract'],apply:['TruthAtlas export capsule','portable proof receipt','offline evidence package'],proof:['manifest/schema validation','asset checksums','source-class labels'],boundary:'The package format is reusable; its illustrative mind model is not a scientific or medical claim.'},
{id:'HSV-04',artifact:'electric_bio_phase_engine_v2_atlas_self_drive.html',driveId:'18U3arGdxtN7I9P8gTAojQbpWes6K7OHj',kind:'HTML',masterMenu:'Audio / Signal',surface:'Biological Traversal',state:'GATED',extract:['bounded multi-timescale governor','dominant stop/override','phase weighting','bias functions','continuous visual/audio synchronization'],apply:['generic bounded scheduler','signal-lane governor','operator override contract'],proof:['hard stop dominance','bounded output caps','deterministic phase weights'],boundary:'Reuse generic scheduling/safety mechanics only; no diagnosis, treatment, physiological efficacy or clinical authority.'},
{id:'HSV-05',artifact:'renderer_20736_color_state.html',driveId:'1QeIzCpO9aOjpj4zUWLqw3iB2S4WdmZ26',kind:'HTML',masterMenu:'Render Field',surface:'Visual Instrument',state:'ADAPT',extract:['domain/phase/regulation/depth lens','normalized mixture projection','responsive canvas loop','parameter HUD','optional signal coupling'],apply:['representation lens API','state-to-visual projection','render parameter inspector'],proof:['input-state receipt','projection determinism','model-space label'],boundary:'20,736 is an address/resolution lens here, not a literal physical dimension; colors are representation channels, not observations.'},
{id:'HSV-06',artifact:'executable_atlas_truth_engine_188.html + executable_atlas_truth_engine_188.svg',driveId:'1tWEiykL9hL4HTlbCQNzeqDPqcxsMgSt9',kind:'SVG_FAMILY',masterMenu:'Render Field',surface:'Visual Instrument',state:'ADAPT',extract:['scriptable SVG instrument embedding','portable interactive geometry','HTML fallback wrapper'],apply:['safe SVG instrument host','geometry-first portable panels','offline visual proof artifact'],proof:['script policy','declared-data provenance','fallback parity'],boundary:'SVG scripting is an interaction carrier only; it receives no state, execution or proof authority by being rendered.'},
{id:'HSV-07',artifact:'Dewey_Woven_Continuity_General_Equation_Full.svg + animated calculus corpus',driveId:'17y92Koszwk9d7-yZ8fGGlbiiD4mGzXkC',kind:'SVG_FAMILY',masterMenu:'Traversal',surface:'Relativity',state:'RECOVER_NOW',extract:['vector geometry as semantic topology','named operator/layer groups','animation timing as transform sequence','formula-to-shape bindings'],apply:['Woven transform diagrams','geometry/proof overlays','resolution-aware vector export'],proof:['operator-group mapping','declared transform source','orientation/resolution invariants'],boundary:'Recover equations/topology/transform semantics, not raster appearance; unverified labels remain model-space.'},
{id:'HSV-08',artifact:'xref-OMEGA_Workstation.html',driveId:'1Kub2EGz9hqQurDcW1Gw9fGZhGCFd6PZf',kind:'BUILD_GRAPH',masterMenu:'Recovery / Packaging',surface:'Archive Operators',state:'RECOVER_NOW',extract:['historical Python module dependency graph','atlas.psc_omega_master_engine dependency','true_scale_traversal plugin dependency','native-render packaging topology'],apply:['lost-capability dependency diff','native/web parity audit','recovery donor graph'],proof:['module identity map','current-successor mapping','no dependency auto-admission'],boundary:'A historical import graph proves packaging/dependency relationships, not that those modules are currently executing.'},
{id:'HSV-09',artifact:'psc_mode_console.html',driveId:'14yRcHOt4_a07YUGIM3nF5SjC6zyX7Tis',kind:'HTML',masterMenu:'AI Orchestration',surface:'SAI Lab',state:'ADAPT',extract:['deterministic operator-intent lexicon','Parent→Accumulation→Scar→Constraint→Phase→Carry answer spine','explicit structural explanation'],apply:['bounded operator classifier','retrieval explanation spine','query planning hints'],proof:['deterministic token match','fallback declared','no model/dispatch authority'],boundary:'Lexical mode detection is a bounded retrieval aid. It does not prove universal physics, dispatch work, or write CanonState.'},
{id:'HSV-10',artifact:'PSC_Atlas_QR_responsive_tool.html + PSC_Atlas_QR_engine_index.json',driveId:'130opFZBrj1LE-2ZVMw2DZAMNigPQjd7f',kind:'HTML',masterMenu:'AI Orchestration',surface:'SAI Lab',state:'RECOVER_NOW',extract:['deterministic inverted index','bounded lexical ranking','gate/baseline/data-needed response fields','related auto-pings','operator-model metadata'],apply:['archive/atlas retrieval utility','source-grounded SAI lookup','Build Out donor search','evidence-aware response scaffold'],proof:['index source hash','stable ranking vectors','gate/source labels','held-out retrieval tests'],boundary:'Deterministic retrieval ranks indexed archive rows only. Scores and predictions remain source/model metadata and do not create truth, execution, or AI authority.'},
{id:'HSV-11',artifact:'inevitability_proof.html',driveId:'1QaqmIZAmRklig_wLbGceuFz7HeT0CwOD',kind:'HTML',masterMenu:'Proof & Governance',surface:'Evidence & Proof',state:'ADAPT',extract:['renderer/proof-harness separation','explicit operator-triggered proof run','comparison-report panel','host GPU renderer adapter seam'],apply:['proof-harness adapter interface','renderer evidence receipt','explicit proof-run UX'],proof:['renderer identity','input/output receipt','proof harness independent of presentation'],boundary:'A button or rendered comparison is not inevitability proof. GPU/render output is evidence only when the declared harness and inputs are independently verified.'}
];
export const HTML_SVG_RECOVERY_RULES_R301={copyPixels:false,copyArchiveAuthority:false,requireModernSuccessor:true,requireProvenance:true,requireBoundary:true,preferredMethod:'EXTRACT_SCHEMA_ALGORITHM_GEOMETRY_INTERACTION_PROOF_CONTRACT'} as const;
export function htmlSvgRecoverySummaryR301(){return {total:HTML_SVG_CAPABILITIES_R301.length,recoverNow:HTML_SVG_CAPABILITIES_R301.filter(x=>x.state==='RECOVER_NOW').length,adapt:HTML_SVG_CAPABILITIES_R301.filter(x=>x.state==='ADAPT').length,gated:HTML_SVG_CAPABILITIES_R301.filter(x=>x.state==='GATED').length,menus:new Set(HTML_SVG_CAPABILITIES_R301.map(x=>x.masterMenu)).size,surfaces:new Set(HTML_SVG_CAPABILITIES_R301.map(x=>x.surface)).size};}
