import {useEffect,useMemo,useState} from 'react';
import {Activity,Download,RefreshCw,ShieldCheck,TriangleAlert} from 'lucide-react';
import {useHybridRuntimeSnapshotR238} from './HybridRuntimeSnapshotR238';
import './hybridExperienceLedgerR255.css';

type Run={jobId:string;deviceKey:string;action:string|null;status:string;queuedAt:number|null;startedAt:number|null;completedAt:number|null;executionDurationMs:number|null;totalDurationMs:number|null;steps:Array<{op:string;ok:boolean;mutation:boolean;changed:boolean;failureSignature:string|null}>;mutationAttempted:boolean;mutationReturned:boolean;buildReturned:boolean;testReturned:boolean;packageReturned:boolean;resultFingerprint:string|null;failureSignature:string|null;observedAt:number};
type Corpus={schema:'OMEGA_HYBRID_EXPERIENCE_CORPUS_R255';revision:'R255';updatedAt:number;runs:Run[]};
const STORE='omega:r255:hybridExperienceCorpus';
const ACTIVE=new Set(['QUEUED','RUNNING','ACTIVE','PENDING','PAUSED']);
const TERMINAL=new Set(['COMPLETE','COMPLETED','SUCCESS','SUCCEEDED','FAILED','ERROR','REJECTED','TIMEOUT','CANCELLED','CANCELED']);
const MUTATION=new Set(['APPLY_PATCH','WRITE_TEXT']);
const age=(n:any)=>{const t=Number(n)||0;if(!t)return'—';const s=Math.max(0,Math.round((Date.now()-t)/1000));return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m`:`${Math.floor(s/3600)}h`};
const ms=(n:any)=>{const v=Number(n);if(!Number.isFinite(v))return'—';return v<1000?`${Math.round(v)} ms`:v<60000?`${(v/1000).toFixed(1)} s`:`${(v/60000).toFixed(1)} m`};
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):null;
const stat=(v:any)=>String(v||'').trim().toUpperCase()||'UNKNOWN';
const duration=(a:any,b:any)=>{const x=num(a),y=num(b);return x!==null&&y!==null&&y>=x?Math.round(y-x):null};
const fingerprint=(input:any)=>{const s=String(input||'');let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')};
const readCorpus=():Corpus=>{try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x?.schema==='OMEGA_HYBRID_EXPERIENCE_CORPUS_R255'&&Array.isArray(x.runs))return x}catch{}return{schema:'OMEGA_HYBRID_EXPERIENCE_CORPUS_R255',revision:'R255',updatedAt:0,runs:[]}};
const quantile=(values:number[],q:number)=>{const xs=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!xs.length)return null;const i=(xs.length-1)*q,lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?xs[lo]:Math.round(xs[lo]*(hi-i)+xs[hi]*(i-lo))};

function sanitizeJob(job:any,deviceId:string,observedAt:number):Run{
 const packet=job?.returnPacket||{},rawSteps=Array.isArray(packet.stepProofs)?packet.stepProofs:Array.isArray(job?.steps)?job.steps:[];
 const steps=rawSteps.map((step:any)=>{const op=stat(step?.op),ok=step?.ok===true,result=step?.result&&typeof step.result==='object'?step.result:{},rawFailure=!ok?String(step?.error||step?.code||step?.message||result?.error||result?.code||''):'';return{op,ok,mutation:MUTATION.has(op),changed:Boolean(result.changed||result.applied||result.written||result.mutated),failureSignature:rawFailure?`step_${fingerprint(`${op}|${rawFailure}`)}`:null}});
 const queuedAt=num(job?.queuedAt),startedAt=num(job?.startedAt),completedAt=num(job?.completedAt??packet?.receivedAt),jobStatus=stat(job?.status),rawFailure=['FAILED','ERROR','REJECTED','TIMEOUT'].includes(jobStatus)?String(job?.stallReason||packet?.reason||packet?.code||job?.error||''):'';
 return{jobId:String(job?.id||`observed-${observedAt}-${fingerprint(JSON.stringify(rawSteps.map((s:any)=>s?.op)))}`),deviceKey:`device_${fingerprint(deviceId)}`,action:String(job?.action||job?.profile||'')||null,status:jobStatus,queuedAt,startedAt,completedAt,executionDurationMs:duration(startedAt,completedAt),totalDurationMs:duration(queuedAt,completedAt),steps,mutationAttempted:steps.some((s:any)=>s.mutation),mutationReturned:steps.some((s:any)=>s.mutation&&s.ok&&s.changed),buildReturned:steps.some((s:any)=>s.op==='BUILD'&&s.ok),testReturned:steps.some((s:any)=>s.op==='TEST'&&s.ok),packageReturned:steps.some((s:any)=>s.op==='PACKAGE'&&s.ok),resultFingerprint:String(packet?.resultFingerprint||'')||null,failureSignature:rawFailure?`job_${fingerprint(`${jobStatus}|${rawFailure}`)}`:null,observedAt};
}

function aggregate(runs:Run[]){const byOp=new Map<string,any>(),failures=new Map<string,number>();for(const run of runs){if(run.failureSignature)failures.set(run.failureSignature,(failures.get(run.failureSignature)||0)+1);for(const step of run.steps){const x=byOp.get(step.op)||{op:step.op,count:0,success:0,failed:0,durations:[],mutations:0,changed:0};x.count++;if(step.ok)x.success++;else x.failed++;if(Number.isFinite(run.executionDurationMs)&&run.steps.length===1)x.durations.push(run.executionDurationMs);if(step.mutation)x.mutations++;if(step.changed)x.changed++;byOp.set(step.op,x);if(step.failureSignature)failures.set(step.failureSignature,(failures.get(step.failureSignature)||0)+1)}}return{jobs:runs.length,terminalJobs:runs.filter(r=>TERMINAL.has(r.status)).length,successfulJobs:runs.filter(r=>['COMPLETE','COMPLETED','SUCCESS','SUCCEEDED'].includes(r.status)).length,failedJobs:runs.filter(r=>['FAILED','ERROR','REJECTED','TIMEOUT'].includes(r.status)).length,mutationJobs:runs.filter(r=>r.mutationAttempted).length,mutationReturnedJobs:runs.filter(r=>r.mutationReturned).length,operations:[...byOp.values()].map(x=>({op:x.op,count:x.count,success:x.success,failed:x.failed,successRate:x.count?x.success/x.count:0,p50DurationMs:quantile(x.durations,.5),p95DurationMs:quantile(x.durations,.95),mutationAttempts:x.mutations,mutationReturns:x.changed})).sort((a,b)=>b.count-a.count||a.op.localeCompare(b.op)),repeatedFailureSignatures:[...failures.entries()].filter(([,count])=>count>1).map(([signature,count])=>({signature,count})).sort((a,b)=>b.count-a.count)}};

export default function HybridExperienceLedgerR255(){
 const{hybrid,device,selectedDeviceJobs,observedAt,epoch,stale,refresh}=useHybridRuntimeSnapshotR238();
 const[corpus,setCorpus]=useState<Corpus>(readCorpus);
 const currentHeartbeat=Boolean(epoch>0&&!stale&&hybrid?.nativeExecutionClaimed===true&&device?.online&&!device?.revoked);
 useEffect(()=>{if(!device||!observedAt)return;const incoming=selectedDeviceJobs.map((job:any)=>sanitizeJob(job,String(device.id),observedAt));setCorpus(previous=>{const map=new Map(previous.runs.map(run=>[run.jobId,run]));for(const run of incoming)map.set(run.jobId,run);const next:Corpus={schema:'OMEGA_HYBRID_EXPERIENCE_CORPUS_R255',revision:'R255',updatedAt:observedAt,runs:[...map.values()].sort((a,b)=>Number(b.completedAt||b.startedAt||b.queuedAt||b.observedAt)-Number(a.completedAt||a.startedAt||a.queuedAt||a.observedAt)).slice(0,500)};try{localStorage.setItem(STORE,JSON.stringify(next))}catch{}return next})},[device?.id,observedAt,selectedDeviceJobs]);
 const runs=corpus.runs,summary=useMemo(()=>aggregate(runs),[runs]),active=useMemo(()=>runs.filter(r=>ACTIVE.has(r.status)),[runs]),recent=runs.slice(0,12),operations=summary.operations.slice(0,10);
 const exportJson=()=>{const out={...corpus,currentAuthenticatedHeartbeat:currentHeartbeat,selectedDeviceKey:device?`device_${fingerprint(device.id)}`:null,sanitation:{bridgeSecret:false,rawBridgeId:false,rawDeviceId:false,hostName:false,projectPath:false,localPath:false,stdout:false,logs:false,rawFailureText:false,outputPaths:false},authority:{readOnly:true,dispatch:false,mutation:false,promotion:false,productionDeploy:false,canonAdmission:false},aggregate:summary,truthBoundary:'R255 is a local sanitized longitudinal projection of the already-authenticated R238 shared snapshot. It creates no additional API polling or execution authority.'};const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`omega-r255-hybrid-ledger-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};
 return <section className='r255-ledger' data-r255-heartbeat={currentHeartbeat?'CURRENT':'UNPROVED'}>
  <header><div><span>R255 · HYBRID EXPERIENCE LEDGER · SHARED R238 EPOCH</span><h3>Repeated PC runs now accumulate into a persistent execution corpus.</h3><p>R255 reuses the already-authenticated R238 Hybrid/Mission snapshot, sanitizes it in-browser, and carries up to 500 run observations across refreshes. No second Hybrid poller, bridge-secret export, raw device ID, path, log, stdout or raw failure text is retained.</p></div><div className={currentHeartbeat?'r255-live pass':'r255-live hold'}><Activity/><span><b>{currentHeartbeat?'CURRENT AUTHENTICATED HEARTBEAT':'CURRENT HEARTBEAT NOT PROVED'}</b><small>{device?`selected host · ${age(device.lastSeen)} since heartbeat`:'no authenticated selected host'}</small></span></div></header>
  <div className='r255-summary'><article><small>CORPUS RUNS</small><b>{summary.jobs}</b><em>{summary.terminalJobs} terminal</em></article><article><small>SUCCESS</small><b>{summary.successfulJobs}</b><em>{summary.failedJobs} failed</em></article><article><small>MUTATION RETURNS</small><b>{summary.mutationReturnedJobs}</b><em>{summary.mutationJobs} mutation jobs</em></article><article><small>ACTIVE NOW</small><b>{active.length}</b><em>{corpus.updatedAt?`corpus ${age(corpus.updatedAt)} old`:'awaiting first sample'}</em></article></div>
  <div className='r255-columns'><div><h4>Operation calibration</h4><div className='r255-table'><div className='head'><span>OP</span><span>N</span><span>PASS</span><span>P50</span><span>P95</span></div>{operations.map((op:any)=><div key={op.op}><span>{op.op}</span><span>{op.count}</span><span>{Math.round(op.successRate*100)}%</span><span>{ms(op.p50DurationMs)}</span><span>{ms(op.p95DurationMs)}</span></div>)}</div></div><div><h4>Latest returned / active jobs</h4><div className='r255-runs'>{recent.map((run,index)=><article key={run.jobId||index} className={ACTIVE.has(run.status)?'active':''}><span><b>{run.status}</b><small>{run.action||'Hybrid job'}</small></span><span><em>{run.steps.map(s=>s.op).filter(Boolean).join(' → ')||'no returned step proof yet'}</em><small>{run.executionDurationMs!=null?ms(run.executionDurationMs):run.startedAt?`started ${age(run.startedAt)} ago`:'queued'} · {run.deviceKey}</small></span></article>)}</div></div></div>
  {summary.repeatedFailureSignatures.length>0&&<div className='r255-repeat'><TriangleAlert/><span><b>Repeated failure fingerprints detected</b><small>{summary.repeatedFailureSignatures.slice(0,6).map(x=>`${x.signature} ×${x.count}`).join(' · ')}</small></span></div>}
  <div className='r255-actions'><button onClick={()=>void refresh()}><RefreshCw/>Refresh shared R238 epoch</button><button onClick={exportJson} disabled={!runs.length}><Download/>Export sanitized JSON</button></div>
  <footer><ShieldCheck/><span>R255 is observation and local learning memory only. R237 dispatch, R153 mutation, R141 returned proof, R146 history, R239 resource admission, R240 source promotion, canonical ci.yml production deployment, and R125 CanonState admission remain separate authorities.</span></footer>
 </section>;
}
