import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Cpu,FileCheck2,FolderOutput,RefreshCw,ShieldCheck,TriangleAlert,Wrench} from 'lucide-react';
import {useHybridRuntimeSnapshotR238} from './HybridRuntimeSnapshotR238';
import './hybridHostEffectsR212.css';

const TERMINAL=new Set(['COMPLETE','DONE','FAILED','CANCELLED']);
const MUTATION_OPS=new Set(['APPLY_PATCH','WRITE_TEXT']);
const OUTPUT_OPS=new Set(['PACKAGE','SUPPORT_BUNDLE','TRAIN_LOCAL','SCREEN_CAPTURE','RECORD_MACRO','FORENSIC_HASH_LEDGER']);
const terminal=(v:any)=>TERMINAL.has(String(v||'').toUpperCase());
const short=(v:any,n=18)=>{const s=String(v||'');return s?s.length>n?`${s.slice(0,n)}…`:s:'—'};
const age=(n:any)=>{const t=Number(n)||0;if(!t)return'—';const s=Math.max(0,Math.round((Date.now()-t)/1000));return s<60?`${s}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};
const uniq=(rows:any[])=>[...new Set(rows.filter(Boolean).map(x=>String(x)))];
const proofPath=(proof:any)=>proof?.result?.path||proof?.result?.ledgerPath||proof?.result?.macroPath||proof?.result?.backupPath||null;

export default function HybridHostEffectsR212(){
 const{hybrid,jobs,knownDevices,onlineDevices,device,selectedDeviceId,selectedDeviceJobs,currentMission,currentMissionJob:currentJob,observedAt,epoch,stale,error,refresh,selectDevice}=useHybridRuntimeSnapshotR238();
 const[selectedId,setSelectedId]=useState('');
 const terminalJobs=useMemo(()=>selectedDeviceJobs.filter((job:any)=>terminal(job?.status)).sort((a:any,b:any)=>Number(b?.completedAt||b?.returnPacket?.receivedAt||b?.queuedAt||0)-Number(a?.completedAt||a?.returnPacket?.receivedAt||a?.queuedAt||0)).slice(0,8),[selectedDeviceJobs]);
 const otherHostTerminalCount=useMemo(()=>jobs.filter((job:any)=>terminal(job?.status)&&job?.targetDeviceId!==selectedDeviceId).length,[jobs,selectedDeviceId]);
 useEffect(()=>{if(!selectedId&&terminalJobs[0]?.id)setSelectedId(terminalJobs[0].id);else if(selectedId&&!terminalJobs.some((job:any)=>job.id===selectedId))setSelectedId(terminalJobs[0]?.id||'')},[terminalJobs,selectedId,selectedDeviceId]);
 const selectedJob=terminalJobs.find((job:any)=>job.id===selectedId)||null;
 const packet=selectedJob?.returnPacket||null;
 const proofs=Array.isArray(packet?.stepProofs)?packet.stepProofs:[];
 const mutations=proofs.filter((proof:any)=>proof?.ok===true&&MUTATION_OPS.has(String(proof?.op||'').toUpperCase()));
 const outputProofs=proofs.filter((proof:any)=>proof?.ok===true&&OUTPUT_OPS.has(String(proof?.op||'').toUpperCase()));
 const outputs=uniq([...(Array.isArray(packet?.outputPaths)?packet.outputPaths:[]),...(Array.isArray(selectedJob?.outputPaths)?selectedJob.outputPaths:[]),...outputProofs.map((proof:any)=>proofPath(proof))]);
 const currentMissionState=String(currentMission?.status||'IDLE').toUpperCase(),currentJobState=String(currentJob?.status||'IDLE').toUpperCase();
 const missionRunning=Boolean(currentMission&&['ACTIVE','PAUSED','QUEUED','PENDING','RUNNING'].includes(currentMissionState)&&!terminal(currentJobState));
 const pcOnline=Boolean(hybrid?.nativeExecutionClaimed===true&&device?.online&&!device?.revoked);
 const mutationLabel=!selectedJob?'NO RETURN SELECTED':mutations.length?`${mutations.length} SOURCE MUTATION${mutations.length===1?'':'S'} PROVED`:'NO SOURCE MUTATION IN THIS RETURN';
 const offlineHistoryMode=onlineDevices.length===0&&knownDevices.length>0;
 return <section className='r212-host-effects' aria-label='R212 live Hybrid host effects' data-r212-host-effects='FIRST_HAND_RETURN_ONLY' data-r212-selected-device={selectedDeviceId||'NONE'} data-r212-snapshot-epoch={epoch}>
  <header><div><span>R212 + R238 + R309 · LIVE HOST EFFECTS · SHARED DEVICE + SNAPSHOT EPOCH</span><h3>What actually happened on this PC?</h3><p>Observation and R237 command control use the same selected authenticated host and atomic Hybrid/Mission snapshot epoch. When no host is currently online, R309 still permits read-only inspection of retained returns from a known non-revoked host. Historical inspection never upgrades that host to online execution authority.</p></div><button onClick={()=>void refresh()}><RefreshCw/>Refresh shared snapshot</button></header>
  <div className='r212-live-strip'>
   <article className={pcOnline&&!stale?'pass':'hold'}>{pcOnline&&!stale?<CheckCircle2/>:<TriangleAlert/>}<span><small>SELECTED PC HEARTBEAT</small><b>{pcOnline&&!stale?'CURRENT / AUTHENTICATED':stale?'SNAPSHOT STALE':'NOT CURRENTLY PROVED'}</b><em>{device?.name||'no correlated host'} · {short(selectedDeviceId,28)} · epoch {epoch} · observed {age(observedAt)}</em></span></article>
   <article className={missionRunning?'running':currentMissionState==='COMPLETE'?'pass':'hold'}><Cpu/><span><small>CORRELATED CURRENT MISSION</small><b>{currentMissionState}</b><em>{currentMission?.stage||'no selected-host mission'} · cycle {Number(currentMission?.cycle||0)}/{Number(currentMission?.maxCycles||0)||'—'}</em></span></article>
   <article className={currentJobState==='RUNNING'?'running':terminal(currentJobState)?'pass':'hold'}><Wrench/><span><small>CORRELATED CURRENT HOST JOB</small><b>{currentJobState}</b><em>{short(currentJob?.id||currentMission?.currentJobId,24)}{currentJob?.projectPath?` · ${currentJob.projectPath}`:''}</em></span></article>
  </div>
  {offlineHistoryMode&&<div className='r212-history-host-picker'><div><ShieldCheck/><span><b>OFFLINE HISTORY INSPECTION</b><small>No current authenticated host heartbeat exists. Select a retained known host to inspect only that host's terminal proof history.</small></span></div><select aria-label='Historical Hybrid host' value={selectedDeviceId||''} onChange={e=>selectDevice(e.target.value)}>{knownDevices.map((row:any)=><option key={row.id} value={row.id}>{row.name||row.id} · {row.online?'online':'offline'} · {short(row.id,22)}</option>)}</select></div>}
  {missionRunning&&<div className='r212-current-warning'><TriangleAlert/><span><b>The selected host mission is still executing.</b><small>A COMPLETE card below is a historical return from this same selected host. Do not infer new source changes from the current cycle until its own exact returned step proofs arrive.</small></span></div>}
  {error&&<div className='r212-error'><TriangleAlert/>{error} · last successful shared snapshot remains displayed rather than being replaced by fabricated offline state.</div>}
  <div className='r212-return-picker' aria-label='Recent terminal Hybrid returns for selected host'>{terminalJobs.map((job:any)=><button key={job.id} className={selectedId===job.id?'active':''} onClick={()=>setSelectedId(job.id)}><span><b>{job.status}</b><small>{short(job.id,22)}</small></span><em>{age(job.completedAt||job.returnPacket?.receivedAt)}</em></button>)}{!terminalJobs.length&&<span className='empty'>No returned host job is available for this selected PC yet.</span>}</div>
  {otherHostTerminalCount>0&&<div className='r212-current-warning'><ShieldCheck/><span><b>{otherHostTerminalCount} terminal return{otherHostTerminalCount===1?'':'s'} from other host{otherHostTerminalCount===1?' is':'s are'} intentionally isolated.</b><small>{offlineHistoryMode?'Use the offline history selector above to inspect a different known host.':'Change the authenticated compute-host selection in R237 to inspect another online device.'} R212 never mixes cross-device return history into this PC view.</small></span></div>}
  {selectedJob&&<div className='r212-effect-grid'>
   <section className={mutations.length?'mutated':'neutral'}><header><FileCheck2/><span><small>SELECTED HOST RETURN · SOURCE EFFECT</small><b>{mutationLabel}</b></span></header>{mutations.length?<div className='r212-mutations'>{mutations.map((proof:any,i:number)=>{const result=proof?.result||{};return <article key={`${proof.id||proof.op}-${i}`}><b>{proof.op} · {result.path||'returned path'}</b><code>before {short(result.beforeSha256,16)} → after {short(result.afterSha256,16)}</code><small>{result.created?'created new file':'preimage-bound replacement'} · atomic={String(result.atomic===true)}{result.backupPath?` · backup ${result.backupPath}`:''}</small></article>})}</div>:<p className='r212-neutral-copy'>This return did not prove APPLY_PATCH or WRITE_TEXT. Discovery, hashing, build, test and packaging can all complete without changing source. If a build already passes, R153 intentionally packages the verified project instead of inventing a repair.</p>}</section>
   <section><header><FolderOutput/><span><small>FILESYSTEM OUTPUTS · SELECTED HOST</small><b>{outputs.length?`${outputs.length} RETURNED PATH${outputs.length===1?'':'S'}`:'NO EXPLICIT OUTPUT PATH'}</b></span></header>{outputs.length?<div className='r212-output-list'>{outputs.map(path=><code key={path}>{path}</code>)}</div>:<p>No package, support bundle, training index, screen capture, macro or forensic ledger path was returned by this selected-host job.</p>}</section>
  </div>}
  {selectedJob&&<section className='r212-steps'><header><ShieldCheck/><span><small>EXACT SELECTED-HOST STEP PROOFS</small><b>{proofs.length} step{proofs.length===1?'':'s'} · fingerprint {short(packet?.resultFingerprint,22)}</b></span></header><div>{proofs.map((proof:any,i:number)=>{const result=proof?.result||{},detail=result.path||result.ledgerPath||result.macroPath||(Array.isArray(result.command)?result.command.join(' '):'')||result.treeSha256?.slice?.(0,16)||result.sha256?.slice?.(0,16)||(result.exitCode===0?'exit 0':'returned');return <article key={`${proof.id||i}-${proof.op}`} className={proof?.ok===true?'pass':'fail'}><code>{proof.id||String(i+1).padStart(2,'0')}</code><span><b>{proof.op||'UNKNOWN'}</b><small>{proof?.ok===true?'RETURNED OK':`FAILED · ${String(proof?.error||'unknown host error').slice(0,260)}`}</small></span><em>{detail}</em></article>})}</div>{packet?.log&&<pre>{String(packet.log).slice(-6000)}</pre>}</section>}
  <footer><ShieldCheck/><span>R212 remains read-only observation. R238/R309 correlation uses one selected non-revoked device frame; online execution still requires a current authenticated heartbeat. Retained offline proof history never queues work, mutates the PC, infers source edits from build success, installs dependencies, expands the approved root, or alters R141/R146/R147/R125 authority.</span></footer>
 </section>;
}