import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,History,RefreshCw,RotateCcw,ShieldAlert,ShieldCheck,Waypoints,Wrench} from 'lucide-react';
import {api} from './platformAdapter';
import {emitOperationR86} from './omegaOperationBusR86';
import {hybridClosureReceiptR142} from './capabilityExecutionReceiptsR142';
import {boundedRepairActionR143,compileExecutionResidualClosureR143} from './executionResidualClosureR143';
import './hybridProofR141.css';

type Job={id:string;status:string;queuedAt?:number;completedAt?:number;targetDeviceId?:string;targetCapabilityRevision?:string;projectPath?:string;returnPacket?:{receivedAt?:number;resultFingerprint?:string};proofClosure?:{schema?:string;state?:string;fingerprintVerified?:boolean;finalHeadSha256?:string;continuity?:{headSha256?:string;count?:number;scarCount?:number;proofCount?:number};canonicalMutation?:boolean}};
type Replay={ok:boolean;headMatch:boolean;fingerprintMatch:boolean;originalHeadSha256:string;replayedHeadSha256:string;replayedAt:number;canonicalMutation:false;canonicalAdmissionAuthority:'R125'};
type Closure={schema:string;revision?:string;state:string;jobId:string;fingerprint:{supplied?:string|null;expected?:string|null;verified:boolean;digestMatch?:boolean;semanticMatch?:boolean;legacyAuthority?:string};finalHeadSha256:string;previousHeadSha256?:string|null;continuity?:{headSha256?:string;count?:number;scarCount?:number;proofCount?:number};hybridProofAtClose?:{currentHeartbeatProved?:boolean;deviceId?:string;capabilityRevision?:string};canonicalMutation:false;canonicalAdmissionAuthority:'R125';livingWorldOperationBridgeRevision?:'R140';lastReplayReceipt?:Replay;replayCount?:number;truthBoundary?:string};
const fmt=(n?:number)=>n?new Date(n).toLocaleTimeString():'';
const short=(s?:string|null,n=12)=>s?`${s.slice(0,n)}…`:'—';

export default function HybridProofClosureR141(){
 const[status,setStatus]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(''),[closure,setClosure]=useState<Closure|null>(null),[replay,setReplay]=useState<Replay|null>(null),[worldBridge,setWorldBridge]=useState<any>(null);
 const refresh=async()=>{setBusy(x=>x||'refresh');try{const r=await api.get<any>('/api/hybrid/status');setStatus(r.data);setError('')}catch(e:any){setError(e?.message||String(e))}finally{setBusy(x=>x==='refresh'?'':x)}};
 useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{const fn=(e:Event)=>setWorldBridge((e as CustomEvent).detail||null);window.addEventListener('omega-r140-world-frame',fn as EventListener);return()=>window.removeEventListener('omega-r140-world-frame',fn as EventListener)},[]);
 const jobs=useMemo<Job[]>(()=>Array.isArray(status?.jobs)?[...status.jobs].filter((j:Job)=>['COMPLETE','FAILED'].includes(j.status)).sort((a:Job,b:Job)=>Number(b.completedAt||b.queuedAt||0)-Number(a.completedAt||a.queuedAt||0)).slice(0,8):[],[status]);
 useEffect(()=>{if(!selected&&jobs[0]?.id)setSelected(jobs[0].id)},[jobs,selected]);
 const executionReceipt=useMemo(()=>closure?hybridClosureReceiptR142(closure):null,[closure]);
 const residualClosure=useMemo(()=>compileExecutionResidualClosureR143(executionReceipt?[executionReceipt]:[]),[executionReceipt]);
 const executionResidual=residualClosure.residuals[0]||null,repairProposal=residualClosure.proposals[0]||null;
 const repairAction=useMemo(()=>executionReceipt?boundedRepairActionR143(executionReceipt,repairProposal):null,[executionReceipt,repairProposal]);
 const handoffToWorld=async(c:Closure)=>{const deviceId=c.hybridProofAtClose?.deviceId||'device-unknown',native=Boolean(c.fingerprint.verified&&c.hybridProofAtClose?.currentHeartbeatProved),pass=c.fingerprint.verified&&c.state==='VERIFIED_EXECUTION_RETURN';await emitOperationR86({type:'HOST_JOB_PROOF_SELECTED',surface:'Hybrid Link',status:pass?'PASS':'HOLD',detail:`R141 durable Hybrid closure selected: ${c.jobId}`,payload:{sourceIds:[deviceId,c.finalHeadSha256],proofIds:c.fingerprint.verified&&c.fingerprint.supplied?[c.fingerprint.supplied]:[],scarIds:[c.jobId],nativeExecutionClaimed:native,devices:native?[{id:deviceId,online:true,revoked:false}]:[],resultFingerprint:native?c.fingerprint.supplied:null,continuity:c.fingerprint.verified?1:0,evidence:c.fingerprint.verified?1:0,contradiction:pass?0:1,burden:pass?.15:.55,uncertainty:c.fingerprint.verified?.05:1,scar:pass?.18:1,payloadDigest:c.finalHeadSha256}})};
 const inspect=async(id:string)=>{setSelected(id);setBusy('inspect:'+id);setReplay(null);try{const r=await api.get<any>(`/api/hybrid/jobs/${encodeURIComponent(id)}/closure`),c=r.data?.closure||null;setClosure(c);setError('');if(c)await handoffToWorld(c)}catch(e:any){setClosure(null);setError(e?.message||String(e))}finally{setBusy('')}};
 const verifyReplay=async(id:string)=>{setSelected(id);setBusy('replay:'+id);try{const r=await api.post<any>(`/api/hybrid/jobs/${encodeURIComponent(id)}/replay`,{});setReplay(r.data?.receipt||null);setError('');await inspect(id)}catch(e:any){setError(e?.message||String(e));setReplay((e?.payload as any)?.receipt||null);setBusy('')}};
 const online=Boolean(status?.nativeExecutionClaimed===true&&Array.isArray(status?.devices)&&status.devices.some((d:any)=>d?.online===true&&d?.revoked!==true));
 return <section className='r141-proof-ledger' aria-label='Hybrid execution proof closure and replay' data-execution-lifecycle='R142' data-residual-closure='R143'>
  <header><div><span>R143 RESIDUAL CLOSURE · R142 EXECUTION TRUTH · R141 PC WORKLOAD → PROOF → SCAR → REPLAY → R140 WORLD FRAME</span><h3>Execution proof closure</h3><p>R141 remains the exact-payload Hybrid proof authority. R142 states execution lifecycle truth. R143 now converts only explicit failed, rejected, stale, unavailable or returned-but-unverified execution evidence into R125 residuals and bounded repair candidates. Availability alone is not failure, repair eligibility is not admission, and CanonState remains unchanged.</p></div><button onClick={()=>void refresh()} disabled={busy==='refresh'}><RefreshCw className={busy==='refresh'?'spin':''}/>Refresh</button></header>
  <div className='r141-proof-summary'>
   <div className={online?'proved':'held'}>{online?<CheckCircle2/>:<ShieldAlert/>}<span><small>CURRENT PC HEARTBEAT</small><b>{online?'PROVED NOW':'NOT CURRENTLY PROVED'}</b><em>{status?.executionPlane||'execution plane unknown'}</em></span></div>
   <div><ShieldCheck/><span><small>EXECUTION LIFECYCLE</small><b>{executionReceipt?.state||'NO RETURN SELECTED'}</b><em>HOST EVIDENCE · NOT CANONSTATE · R142 truth state · R141 remains proof source</em></span></div>
   <div><Waypoints/><span><small>RESIDUAL CLOSURE</small><b>{executionResidual?`${executionResidual.kind} · ${repairProposal?.mode||'OBSERVE'}`:'NO EXECUTION RESIDUAL'}</b><em>R143 classification · R125 policy · R124 governed build authority</em></span></div>
  </div>
  {error&&<div className='r141-proof-error'><ShieldAlert/>{error}</div>}
  {jobs.length===0?<div className='r141-proof-empty'><History/><div><b>No returned bounded workload is available yet.</b><span>Connection proof and execution proof are separate. Queue confirmed Hybrid work only when actual machine work is required; R141 closes its returned packet, R142 classifies execution truth, and R143 creates a residual only from explicit negative or incomplete proof evidence.</span></div></div>:
  <div className='r141-proof-grid'>{jobs.map(job=>{const p=job.proofClosure,active=selected===job.id;return <article key={job.id} className={active?'active':''}>
   <header><code>{job.id}</code><b>{job.status}</b></header>
   <dl><div><dt>fingerprint</dt><dd className={p?.fingerprintVerified?'ok':'hold'}>{p?.fingerprintVerified===true?'VERIFIED':p?'MISMATCH / HELD':'CLOSURE PENDING'}</dd></div><div><dt>continuity head</dt><dd>{short(p?.finalHeadSha256)}</dd></div><div><dt>device</dt><dd>{job.targetDeviceId||'—'}</dd></div><div><dt>returned</dt><dd>{fmt(job.completedAt||job.returnPacket?.receivedAt)}</dd></div></dl>
   <footer><button onClick={()=>void inspect(job.id)} disabled={Boolean(busy)}><ShieldCheck/>Inspect + project receipt</button><button onClick={()=>void verifyReplay(job.id)} disabled={Boolean(busy)||!p}><RotateCcw className={busy==='replay:'+job.id?'spin':''}/>Verify replay</button></footer>
  </article>})}</div>}
  {closure&&selected===closure.jobId&&<section className='r141-receipt' data-r142-state={executionReceipt?.state||'UNAVAILABLE'}>
   <header><b>Closure receipt · {closure.jobId}</b><span className={executionReceipt?.state==='VERIFIED'?'ok':'hold'}>{executionReceipt?.state||closure.state}</span></header>
   <div><span><small>R142 execution state</small><code>{executionReceipt?.state||'UNAVAILABLE'} · canonicalMutation=false</code></span><span><small>supplied R141 fingerprint</small><code>{closure.fingerprint.supplied||'none'}</code></span><span><small>recomputed payload fingerprint</small><code>{closure.fingerprint.expected||'unavailable'}</code></span><span><small>semantic equality</small><code>{closure.fingerprint.semanticMatch?'MATCH':'NOT VERIFIED'} · digest {closure.fingerprint.digestMatch?'MATCH':'NOT VERIFIED'}</code></span><span><small>final R134 head</small><code>{closure.finalHeadSha256}</code></span><span><small>continuity counts</small><code>{closure.continuity?.count??0} events · {closure.continuity?.proofCount??0} proof · {closure.continuity?.scarCount??0} scar</code></span></div>
   <footer><ShieldCheck/>R141 proof authority retained · R142 lifecycle = {executionReceipt?.state||'UNAVAILABLE'} · admission authority = R125 · current heartbeat at close = {closure.hybridProofAtClose?.currentHeartbeatProved?'proved':'not proved'}</footer>
  </section>}
  {executionReceipt&&<section className={executionResidual?'r143-residual hold':'r143-residual ok'} aria-label='R143 execution residual closure'>
   <header><div><small>R143 EXECUTION → RESIDUAL → REPAIR CLOSURE</small><b>{executionResidual?executionResidual.summary:'Selected execution has no repair residual.'}</b></div><strong>{executionResidual?`${Math.round(executionResidual.confidence*100)}% evidence`:'CLOSED'}</strong></header>
   {executionResidual?<div className='r143-residual-grid'><span><small>residual</small><code>{executionResidual.kind} · {executionResidual.severity}</code></span><span><small>R125 action mode</small><code>{repairProposal?.mode||'OBSERVE_ONLY'}</code></span><span><small>repair recipe</small><code>{repairProposal?.recipeId||'NONE'}</code></span><span><small>authorities</small><code>proof R141 · build R124 · admission R125</code></span></div>:<p>VERIFIED, AVAILABLE, AUTHORIZED, DISCOVERED and non-timed-out INVOKED states do not generate defects merely because no further execution occurred.</p>}
   <footer><span><ShieldCheck/>canonicalMutation=false · repair eligibility ≠ CanonState admission</span>{repairAction?.kind==='POST'&&closure?.jobId?<button onClick={()=>void verifyReplay(closure.jobId)} disabled={Boolean(busy)}><RotateCcw className={busy==='replay:'+closure.jobId?'spin':''}/>{repairAction.label}</button>:repairAction?.kind==='GOVERNED_CANDIDATE'?<em><Wrench/> {repairAction.label}</em>:null}</footer>
  </section>}
  {worldBridge&&<div className='r141-world-bridge ok'><Waypoints/><span><b>R140 LIVING-WORLD PROJECTION RECEIVED</b><small>{worldBridge?.eventId||'operation receipt'} · head {short(worldBridge?.frame?.head?.headSha256)} · canonicalMutation = false</small></span></div>}
  {replay&&<div className={replay.ok?'r141-replay ok':'r141-replay hold'}><RotateCcw/><span><b>{replay.ok?'DETERMINISTIC REPLAY VERIFIED':'REPLAY MISMATCH'}</b><small>fingerprint {replay.fingerprintMatch?'match':'mismatch'} · continuity head {replay.headMatch?'match':'mismatch'} · CanonState unchanged</small></span></div>}
 </section>
}
