export type IntelligenceRole='ROUTER'|'RAG'|'PLANNER'|'TRAINER'|'PROOF'|'FORECAST'|'TRANSLATOR'|'PROGRAMMER'|'AUTOMATION'|'RENDER'|'HYBRID'|'MEMORY';
export type IntelligenceStatus='ACTIVE_HOSTED'|'VERIFIED_DONOR_RUNTIME'|'DONOR_ARCHITECTURE'|'TRAINING_PIPELINE_DONOR'|'MODEL_WEIGHTS_REQUIRED'|'PROVIDER_BOUND'|'PROOF_BOUND';
export type IntelligenceContributor={id:string;name:string;roles:IntelligenceRole[];status:IntelligenceStatus;source:string;capability:string;truth:string};
export const INTELLIGENCE_CONTRIBUTORS:IntelligenceContributor[]=[
{id:'cloud-router',name:'OMEGA route-before-generation assistant',roles:['ROUTER','PLANNER','PROOF'],status:'ACTIVE_HOSTED',source:'B020 + current Cloudflare workstation',capability:'Deterministic FAST routing, provider-bounded deep route, single-flight interaction and proof-state continuity.',truth:'Hosted routing is active; model synthesis is not fabricated when a provider is unavailable.'},
{id:'sai-b059-atlas',name:'SAI B059 PSC Atlas intelligence',roles:['RAG','PLANNER','MEMORY'],status:'PROOF_BOUND',source:'Drive SAI/B059 PSC Atlas donor package',capability:'PSC/Atlas knowledge and state organization donor intended for SAI reasoning context.',truth:'Donor package exists; current browser runtime does not claim its original model weights are executing.'},
{id:'sai-b059-operator',name:'SAI B059 PSC Operator / QR',roles:['PLANNER','TRANSLATOR','PROOF'],status:'PROOF_BOUND',source:'Drive SAI/B059 PSC Operator QR donor package',capability:'Operator/question-response structure and translation between source state and executable operation.',truth:'Integrated as role semantics until executable donor correspondence is proven file-by-file.'},
{id:'sai-b059-calculus',name:'SAI B059 Calculus / Graph / Proof',roles:['PROOF','FORECAST','PLANNER'],status:'PROOF_BOUND',source:'Drive SAI/B059 Calculus Graph Proof donor package',capability:'Calculus, graph reasoning and proof-gate contributor.',truth:'Uses current source-bound calculus; no hidden model invocation is implied.'},
{id:'sai-b059-workbooks',name:'SAI B059 Workbook intelligence',roles:['RAG','MEMORY','TRANSLATOR'],status:'PROOF_BOUND',source:'Drive SAI/B059 Workbooks donor package',capability:'Workbook-derived knowledge, tables and operator-readable training material.',truth:'Knowledge donor; not counted as independent empirical confirmation when it is another projection of the same corpus.'},
{id:'v87-repair-loop',name:'B058/V87 SAI repair + bounded macro loop',roles:['PROGRAMMER','PLANNER','AUTOMATION','HYBRID'],status:'DONOR_ARCHITECTURE',source:'B058 correspondence ledger V87',capability:'Prepare ordered operations, review/edit them, execute through bounded host command transactions, inspect return packet, then prepare another draft.',truth:'Planner semantics are retained; native execution remains DEVICE_PROOF_REQUIRED without heartbeat evidence.'},
{id:'hybrid-trainer',name:'Hybrid local SAI trainer',roles:['TRAINER','RAG','MEMORY','PROOF'],status:'TRAINING_PIPELINE_DONOR',source:'OMEGA_HYBRID_LINK_BRIDGE_V90_R4',capability:'Builds source chunks, approved proof lessons, corpus.jsonl, local-model manifest and training receipt under a local SAI training root.',truth:'Training-pipeline code is a real donor; this hosted browser does not claim compatible trained weights are loaded.'},
{id:'atlas-rag',name:'Atlas OS local RAG + deterministic planner',roles:['RAG','PLANNER','MEMORY','TRANSLATOR'],status:'DONOR_ARCHITECTURE',source:'atlas_os_ai_report',capability:'Offline-first ETL, local vector retrieval, compact local LLM option, deterministic Atlas principle engine and append-only action ledger.',truth:'Architecture donor. Local model/vector store require an actual host binding before ACTIVE status.'},
{id:'total-control',name:'Omega Total Control assistant + automation runtime',roles:['PROGRAMMER','AUTOMATION','PLANNER','PROOF'],status:'VERIFIED_DONOR_RUNTIME',source:'Omega Total Control Suite verification',capability:'Assistant command routing, automation queue/run, instrument navigation, proof snapshots, observation validation and tool execution through runtime authority.',truth:'Verified in its donor package/container; current Cloudflare adapter must rebind capabilities rather than pretending that Python host is present.'},
{id:'render-conditioner',name:'Render Forge math-conditioned intelligence',roles:['RENDER','TRANSLATOR','PLANNER'],status:'MODEL_WEIGHTS_REQUIRED',source:'Render Forge Iter33/34 manifests',capability:'Math-conditioned composition, saliency, depth, texture-density and structure-lock packets with deterministic raster fallback and optional Diffusers backend.',truth:'Historical manifest explicitly reported no local neural weights; arbitrary neural image generation remains MODEL_WEIGHTS_REQUIRED.'},
{id:'forecast-intelligence',name:'Forecast+ counterfactual operator',roles:['FORECAST','PLANNER','PROOF'],status:'ACTIVE_HOSTED',source:'Current Forecast+ runtime',capability:'Competing source-state corridors, future plasticity, proof/evidence weighting and source-only frozen priors.',truth:'Forecast is model-derived and futureObservationUsed remains false.'},
{id:'mode188-fabric',name:'Mode188 / ALL MODES executor fabric',roles:['PLANNER','TRANSLATOR','PROOF','MEMORY'],status:'ACTIVE_HOSTED',source:'179-mode corpus + Mode188 calculus',capability:'Shared state projection through STAY/TURN/ESCALATE and PRUNE→TRANSLATE→PROVE semantics.',truth:'Operational symbolic framework; representational dimensions are not physical dimensions.'}
];
export type IntelligenceIntent='CHAT'|'CODE'|'FORECAST'|'TRANSLATE'|'RENDER'|'PROOF'|'HYBRID'|'MEMORY';
const INTENT_ROLES:Record<IntelligenceIntent,IntelligenceRole[]>={CHAT:['ROUTER','RAG','PLANNER'],CODE:['PROGRAMMER','PLANNER','PROOF','AUTOMATION'],FORECAST:['FORECAST','PLANNER','PROOF'],TRANSLATE:['TRANSLATOR','RAG','PLANNER'],RENDER:['RENDER','TRANSLATOR','PROOF'],PROOF:['PROOF','RAG','MEMORY'],HYBRID:['HYBRID','PROGRAMMER','AUTOMATION','PROOF'],MEMORY:['MEMORY','RAG','PROOF']};
const rank:Record<IntelligenceStatus,number>={ACTIVE_HOSTED:6,VERIFIED_DONOR_RUNTIME:5,TRAINING_PIPELINE_DONOR:4,DONOR_ARCHITECTURE:3,PROOF_BOUND:2,PROVIDER_BOUND:1,MODEL_WEIGHTS_REQUIRED:0};
export function intelligenceRoute(intent:IntelligenceIntent){const roles=INTENT_ROLES[intent];return INTELLIGENCE_CONTRIBUTORS.filter(x=>x.roles.some(r=>roles.includes(r))).sort((a,b)=>rank[b.status]-rank[a.status]);}
export function fabricSummary(){const active=INTELLIGENCE_CONTRIBUTORS.filter(x=>x.status==='ACTIVE_HOSTED').length,verifiedDonor=INTELLIGENCE_CONTRIBUTORS.filter(x=>x.status==='VERIFIED_DONOR_RUNTIME').length,training=INTELLIGENCE_CONTRIBUTORS.filter(x=>x.status==='TRAINING_PIPELINE_DONOR').length,weightsRequired=INTELLIGENCE_CONTRIBUTORS.filter(x=>x.status==='MODEL_WEIGHTS_REQUIRED').length;return{contributors:INTELLIGENCE_CONTRIBUTORS.length,active,verifiedDonor,training,weightsRequired};}
