import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,CheckCircle2,CloudCog,Download,RefreshCw,ShieldAlert,ShieldCheck} from 'lucide-react';
import {api,localState} from './platformAdapter';
import {compileLiveStateSpine,spineSummary,type LiveStateArtifact} from './liveStateSpineR50';
import {currentSessionRowsR105,freshnessLabelR105,retainedRowsR106,R106_LEDGER_TRUTH_BOUNDARY} from './dataFreshnessR105';
import ProofChainSupervisorR54 from './ProofChainSupervisorR54';
import ProofPerformanceProviderR55 from './ProofPerformanceProviderR55';
import './liveStateSpineR50.css';

type Delta={at:number;file:string;from:string;to:string;value:string};
type MeshReceipt={at:number;mode:'FULL_SNAPSHOT'|'DELTA';baseHash:string|null;currentHash:string;deltaHash:string|null;snapshotHash?:string|null;checkpointHash:string;changedComponents:string[];patchCount:number;truncated:boolean;resynced?:boolean};
const packetCore=(record:any)=>({address:record?.address,stateId:record?.stateId,identity:record?.identity??null,metrics:record?.metrics??null,psc:record?.psc??null,predict:record?.predict??null,autoPing:record?.autoPing??null});
const projectionCore=(projectionView?:string,frameHash?:string)=>({view:projectionView||'FIELD',frameHash:frameHash||null});
const boundedRuntimeUnavailable=(schema:string,e:any)=>({schema,ok:false,unavailable:true,error:String(e?.message||e||'Runtime endpoint unavailable.'),boundary:'R118 runtime proof observation is unavailable in this host context. No proof, checkpoint, execution state, or cloud result is synthesized as a substitute.'});
function dl(data:any){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='OMEGA_R56_B015_TEMPORAL_PROOF_LEDGER_RECEIPT.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),700)}

export default function LiveStateSpineR50({record,frameHash,projectionView,operatorLedgerCount=0}:{record:any;frameHash?:string;projectionView?:string;operatorLedgerCount?:number}){
 const[status,setStatus]=useState<any>({}),[restore,setRestore]=useState<any>({}),[workerSpine,setWorkerSpine]=useState<any>({}),[packetProof,setPacketProof]=useState<any>({}),[meshProof,setMeshProof]=useState<any>({}),[busy,setBusy]=useState(false),[last,setLast]=useState<number>(0),[deltas,setDeltas]=useState<Delta[]>(()=>localState.read('omega.r50.spine.deltas',[])),[meshJournal,setMeshJournal]=useState<MeshReceipt[]>(()=>localState.read('omega.r53.delta.mesh.journal',[]));
 const previous=useRef<Record<string,string>>(localState.read('omega.r50.spine.reality',{}));
 const acceptMesh=(m:any,packet:any,projection:any,resynced=false)=>{setMeshProof({...m,resynced});if(m?.ok!==true||String(m?.checkpointHash||'').length!==64)return;localState.write('omega.r53.delta.mesh.previous',{packet,projection});localState.write('omega.r53.delta.mesh.checkpoint',m.checkpointHash);const receipt:MeshReceipt={at:Date.now(),mode:m.mode,baseHash:m.baseHash??null,currentHash:m.currentHash,deltaHash:m.deltaHash??null,snapshotHash:m.snapshotHash??null,checkpointHash:m.checkpointHash,changedComponents:Array.isArray(m.changedComponents)?m.changedComponents:[],patchCount:Array.isArray(m.patches)?m.patches.length:0,truncated:m.truncated===true,resynced};setMeshJournal(prev=>{const duplicate=prev[prev.length-1]?.checkpointHash===receipt.checkpointHash;if(duplicate)return prev;const next=[...prev,receipt].slice(-188);localState.write('omega.r53.delta.mesh.journal',next);return next})};
 const refresh=async()=>{setBusy(true);try{
   const packet=packetCore(record),projection=projectionCore(projectionView,frameHash),prior=localState.read<any>('omega.r53.delta.mesh.previous',null),previousCheckpointHash=localState.read<string|null>('omega.r53.delta.mesh.checkpoint',null);
   const[s,r,w,p]=await Promise.all([api.get<any>('/api/status'),api.get<any>('/api/restoration'),api.get<any>('/api/live-state-spine'),api.post<any>('/api/proof/packet',{packet,projection})]);setStatus(s.data||{});setRestore(r.data||{});setWorkerSpine(w.data||{});setPacketProof(p.data||{});
   try{const m=await api.post<any>('/api/proof/delta',{previous:prior,current:{packet,projection},previousCheckpointHash});acceptMesh(m.data,packet,projection,false)}catch(e:any){const recoverable=['PREVIOUS_PACKET_INVALID','CHECKPOINT_HASH_INVALID'].includes(String(e?.code||''));if(!recoverable)throw e;localState.remove('omega.r53.delta.mesh.previous');localState.remove('omega.r53.delta.mesh.checkpoint');const reset=await api.post<any>('/api/proof/delta',{current:{packet,projection}});acceptMesh(reset.data,packet,projection,true)}
   setLast(Date.now());
  }catch(e:any){const unavailable=boundedRuntimeUnavailable('OMEGA_LIVE_STATE_SPINE_RUNTIME_UNAVAILABLE_R118',e);setWorkerSpine(unavailable);setPacketProof({...unavailable,schema:'OMEGA_PACKET_PROOF_R52_UNAVAILABLE',validation:{valid:false}});setMeshProof({...unavailable,schema:'OMEGA_DELTA_MESH_R53_UNAVAILABLE'});setLast(Date.now())}finally{setBusy(false)}};
 useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),30000);return()=>window.clearInterval(id)},[record?.address,record?.stateId,projectionView,frameHash]);
 const rows=useMemo(()=>compileLiveStateSpine(record,status,restore,{frameHash,projectionView,operatorLedgerCount}),[record,status,restore,frameHash,projectionView,operatorLedgerCount]);
 const summary=useMemo(()=>spineSummary(rows),[rows]);
 useEffect(()=>{if(!last)return;const now:Record<string,string>={},changes:Delta[]=[];for(const r of rows){now[r.file]=r.reality;const old=previous.current[r.file];if(old&&old!==r.reality)changes.push({at:last,file:r.file,from:old,to:r.reality,value:r.value})}previous.current=now;localState.write('omega.r50.spine.reality',now);if(changes.length){setDeltas(prev=>{const next=[...prev,...changes].slice(-120);localState.write('omega.r50.spine.deltas',next);return next})}},[last,rows]);
 const sessionDeltas=useMemo(()=>currentSessionRowsR105(deltas),[deltas]),retainedDeltas=useMemo(()=>retainedRowsR106(deltas),[deltas]);
 const sessionMesh=useMemo(()=>currentSessionRowsR105(meshJournal),[meshJournal]),retainedMesh=useMemo(()=>retainedRowsR106(meshJournal),[meshJournal]);
 const workerFiles=Array.isArray(workerSpine?.rows)?new Set(workerSpine.rows.map((x:any)=>x.file)):new Set<string>(),workerComplete=workerSpine?.complete===true&&workerFiles.size===14,proofValid=packetProof?.schema==='OMEGA_PACKET_PROOF_R52'&&packetProof?.validation?.valid===true&&String(packetProof?.packetHash||'').length===64,meshValid=meshProof?.schema==='OMEGA_DELTA_MESH_R53'&&meshProof?.ok===true&&String(meshProof?.checkpointHash||'').length===64&&!meshProof?.truncated;
 const healthy=summary.complete&&rows.every(x=>x.reality!=='UNAVAILABLE')&&workerComplete&&proofValid&&meshValid,sessionRegressions=sessionDeltas.filter(x=>x.to==='UNAVAILABLE'||x.to==='DEVICE_PROOF_REQUIRED'||x.to==='EXTERNAL_DEGRADED').length,retainedRegressions=retainedDeltas.filter(x=>x.to==='UNAVAILABLE'||x.to==='DEVICE_PROOF_REQUIRED'||x.to==='EXTERNAL_DEGRADED').length;
 const receipt=()=>dl({schema:'OMEGA_R56_B015_TEMPORAL_PROOF_LEDGER_RECEIPT',generatedAt:new Date().toISOString(),current:{lastReconciledAt:last||null,summary,rows,workerSpine,packetProof,meshProof,sessionDeltaCount:sessionDeltas.length,sessionMeshCount:sessionMesh.length},retainedEvidence:{meshJournal,deltas,retainedDeltaCount:retainedDeltas.length,retainedMeshCount:retainedMesh.length},boundary:R106_LEDGER_TRUTH_BOUNDARY});
 return <section className='r50-spine'>
  <header><div><span>B015 LIVE-STATE CONTRACT · R56 TEMPORAL PROOF-LEDGER TRUTH</span><h2>Live State Spine</h2><p>The browser retains canonical packet and journal ownership. R52 proves packets, R53 proves bounded deltas/checkpoints, R54 recomputes chain integrity, and R55 measures Worker proof compute plus browser round trip. R106 separates present-session observations from retained evidence without deleting continuity history.</p></div><div className='r50-spine-actions'><button onClick={()=>void refresh()} disabled={busy}><RefreshCw className={busy?'spin':''}/>{busy?'Refreshing':'Refresh'}</button><button onClick={receipt}><Download/>Receipt</button></div></header>
  <div className='r50-spine-kpis'><article><b>{summary.present}/{summary.required}</b><span>browser states mapped · NOW</span></article><article><b>{workerSpine?.present||0}/{workerSpine?.required||14}</b><span>Worker states mapped · latest response</span></article><article><b>{proofValid?'64 HEX':'HOLD'}</b><span>packet SHA-256 · latest response</span></article><article><b>{meshProof?.mode||'WAIT'}</b><span>transport mode · latest response</span></article><article><b>{sessionMesh.length} / {meshJournal.length}</b><span>session / retained mesh receipts</span></article><article className={healthy?'pass':'hold'}><b>{healthy?'COHERENT':'BOUNDED'}</b><span>current packet/delta state</span></article></div>
  {packetProof?.packetHash&&<section className='r50-delta-ledger'><header><ShieldCheck/><div><b>Worker packet proof · latest runtime response</b><small>LIVE_RUNTIME RESPONSE · NON_AUTHORITATIVE_PROOF_COMPILER · received-not-observed</small></div></header><div><article><code>PACKET SHA-256</code><span><b>{packetProof.packetHash}</b></span><small>STATE {packetProof.validation?.stateId} · address {(Number(packetProof.validation?.address)||0)+1} / 20,736</small></article>{packetProof.projectionHash&&<article><code>PROJECTION SHA-256</code><span><b>{packetProof.projectionHash}</b></span><small>packet hash + supplied projection metadata</small></article>}</div></section>}
  {meshProof?.checkpointHash&&<section className='r50-delta-ledger'><header><Activity/><div><b>B015 bounded delta mesh · R53 · latest runtime response</b><small>one full snapshot then changed-component transport · retained journal continuity kept separate</small></div></header><div><article><code>{meshProof.mode}</code><span><b>{meshProof.mode==='FULL_SNAPSHOT'?'baseline established':`${meshProof.patches?.length||0} semantic changes`}</b></span><small>{meshProof.resynced?'automatic stale-checkpoint resynchronization · ':''}{(meshProof.changedComponents||[]).join(' · ')||'no component change'}</small></article><article><code>CHECKPOINT SHA-256</code><span><b>{meshProof.checkpointHash}</b></span><small>{meshProof.deltaHash?`delta ${String(meshProof.deltaHash).slice(0,16)}…`:`snapshot ${String(meshProof.snapshotHash||'').slice(0,16)}…`} · retained evidence chain {meshJournal.length}</small></article></div></section>}
  {workerSpine?.unavailable&&<section className='r50-delta-ledger'><header><ShieldAlert/><div><b>Worker proof runtime unavailable in this host context</b><small>BOUNDED · NO SYNTHETIC PROOF SUBSTITUTE</small></div></header><p>{workerSpine.error}</p></section>}
  <ProofChainSupervisorR54/>
  <ProofPerformanceProviderR55 record={record} frameHash={frameHash} projectionView={projectionView}/>
  <div className='r50-spine-grid'>{rows.map((r:LiveStateArtifact)=><article key={r.file} data-reality={r.reality}><header>{r.reality==='DEVICE_PROOF_REQUIRED'||r.reality==='EXTERNAL_DEGRADED'||r.reality==='UNAVAILABLE'?<ShieldAlert/>:<CheckCircle2/>}<div><code>{r.file}</code><b>{r.label}</b></div><strong>{r.reality}</strong></header><p>{r.value}</p><small>{r.proof}</small><footer><CloudCog/><span>{r.authority} · Worker {workerFiles.has(r.file)?'REGISTERED':'MISSING'}</span></footer></article>)}</div>
  <section className='r50-delta-ledger'><header><Activity/><div><b>Self-monitor delta ledger · CURRENT SESSION</b><small>{sessionDeltas.length} state-boundary changes observed this browser session · {sessionRegressions} transitions into gated/degraded state</small></div></header>{sessionDeltas.length?<div>{sessionDeltas.slice(-8).reverse().map((d,i)=><article key={`${d.at}-${d.file}-${i}`}><code>{d.file}</code><span>{d.from} → <b>{d.to}</b></span><small>{new Date(d.at).toLocaleTimeString()} · {freshnessLabelR105(d.at)} · {d.value}</small></article>)}</div>:<p>No reality-boundary changes observed during this browser session.</p>}</section>
  <section className='r50-delta-ledger' data-r105-history='retained'><header><Activity/><div><b>Self-monitor delta ledger · RETAINED EVIDENCE HISTORY</b><small>{retainedDeltas.length} pre-session changes retained locally · {retainedRegressions} historical gated/degraded transitions</small></div></header>{retainedDeltas.length?<details><summary>Inspect retained state-boundary history</summary><div>{retainedDeltas.slice(-12).reverse().map((d,i)=><article key={`${d.at}-${d.file}-${i}`}><code>{d.file}</code><span>{d.from} → <b>{d.to}</b></span><small>{new Date(d.at).toLocaleString()} · retained evidence · {d.value}</small></article>)}</div></details>:<p>No pre-session state-boundary history is retained.</p>}</section>
  <section className='r50-delta-ledger'><header><ShieldCheck/><div><b>Checkpoint chain · CURRENT SESSION</b><small>{sessionMesh.length} new receipts this session · full retained evidence chain remains {meshJournal.length}/188</small></div></header>{sessionMesh.length?<div>{sessionMesh.slice(-8).reverse().map((m,i)=><article key={`${m.at}-${m.checkpointHash}-${i}`}><code>{m.mode}</code><span>{m.patchCount} patches · <b>{m.changedComponents.join(', ')||'baseline'}</b></span><small>{new Date(m.at).toLocaleTimeString()} · {freshnessLabelR105(m.at)} · {m.resynced?'RESYNC · ':''}checkpoint {m.checkpointHash.slice(0,20)}…</small></article>)}</div>:<p>Awaiting a current-session delta/snapshot receipt.</p>}</section>
  <section className='r50-delta-ledger' data-r105-history='retained'><header><ShieldCheck/><div><b>Checkpoint chain · RETAINED EVIDENCE HISTORY</b><small>{retainedMesh.length} pre-session receipts · maximum 188 retained in browser/local authority</small></div></header>{retainedMesh.length?<details><summary>Inspect retained checkpoint receipts</summary><div>{retainedMesh.slice(-12).reverse().map((m,i)=><article key={`${m.at}-${m.checkpointHash}-${i}`}><code>{m.mode}</code><span>{m.patchCount} patches · <b>{m.changedComponents.join(', ')||'baseline'}</b></span><small>{new Date(m.at).toLocaleString()} · retained evidence · {m.resynced?'RESYNC · ':''}checkpoint {m.checkpointHash.slice(0,20)}…</small></article>)}</div></details>:<p>No pre-session checkpoint receipts are retained.</p>}</section>
  <footer className='r50-spine-boundary'><ShieldCheck/><span>{R106_LEDGER_TRUTH_BOUNDARY} {meshProof?.boundary||packetProof?.boundary||workerSpine?.boundary||summary.boundary}</span><em>{last?`Last reconciled ${new Date(last).toLocaleTimeString()} · ${freshnessLabelR105(last)}`:'Awaiting first cloud reconciliation'}</em></footer>
 </section>
}
