import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowRight,Earth,Link2,ShieldCheck,Sparkles} from 'lucide-react';
import {R173_EVENT} from './world/federationLedgerWorldObserverR173.js';
import {R175_R140_EVENT,projectMultiDomainLivingWorldTruthR175} from './world/multiDomainLivingWorldTruthR175.js';
import {composeLivingWorldMissionR177,R177_EVENT} from './world/livingWorldMissionComposerR177.js';
import {resolveLivingWorldMissionAgainstAuthorityR178} from './world/livingWorldMissionContractBridgeR178';
import {authorizeLivingWorldResolutionR181,dispatchLivingWorldAuthorizationR181,refreshLivingWorldDispatchR181,R181_AUTHORIZE_CONFIRMATION,R181_DISPATCH_CONFIRMATION} from './livingWorldOperatorClientR181';
import './livingWorldPulseR174.css';

type Bands={mission:string;earth:string;federation:string;hybrid:string;render:string};
type Pulse={revision?:string;eventAccepted:boolean;sourceRevision:string;worldId:string|null;operationRef:unknown;federationStage:string;nextFederationStage:string|null;federationClosed:boolean;truthBands:Bands;activeDomains:string[];lod:number|null;sampleBudget:number|null;scarCount:number;routingTarget:string|null;dispatchAuthorized:boolean;claims:{pcOnlineProved:boolean;solverValidityProved:boolean;computedPhotorealRealityProved:boolean}};
type Props={onNavigate:(panel:string)=>void};
const EMPTY:Pulse={revision:'R175',eventAccepted:false,sourceRevision:'NONE',worldId:null,operationRef:null,federationStage:'NONE',nextFederationStage:null,federationClosed:false,truthBands:{mission:'NONE',earth:'UNPROVED',federation:'NONE',hybrid:'DEVICE_PROOF_REQUIRED',render:'NONE'},activeDomains:[],lod:null,sampleBudget:null,scarCount:0,routingTarget:null,dispatchAuthorized:false,claims:{pcOnlineProved:false,solverValidityProved:false,computedPhotorealRealityProved:false}};
const ready=(step:any)=>step?.readiness==='CONTRACT_RESOLVED_NOT_AUTHORIZED';

export default function LivingWorldPulseR174({onNavigate}:Props){
 const[pulse,setPulse]=useState<Pulse>(EMPTY);const[staged,setStaged]=useState(false);const[stagedMission,setStagedMission]=useState<any>(null);const[operatorOpen,setOperatorOpen]=useState(false);const[resolution,setResolution]=useState<any>(null);const[selected,setSelected]=useState<number[]>([]);const[authorizeConfirmed,setAuthorizeConfirmed]=useState(false);const[authorization,setAuthorization]=useState<any>(null);const[dispatchConfirmed,setDispatchConfirmed]=useState(false);const[dispatchReceipt,setDispatchReceipt]=useState<any>(null);const[busy,setBusy]=useState('');const[operatorMessage,setOperatorMessage]=useState('');
 useEffect(()=>{
  const receive=(event:Event)=>{
   const next=projectMultiDomainLivingWorldTruthR175((event as CustomEvent).detail) as Pulse;
   if(!next.eventAccepted)return;
   setPulse(next);setStaged(false);setStagedMission(null);setResolution(null);setSelected([]);setAuthorizeConfirmed(false);setAuthorization(null);setDispatchConfirmed(false);setDispatchReceipt(null);setOperatorMessage('');
   try{localStorage.setItem('omega.r175.worldTruthSurface',JSON.stringify({...next,claims:{...next.claims,pcOnlineProved:false,computedPhotorealRealityProved:false}}))}catch{}
  };
  window.addEventListener(R173_EVENT,receive as EventListener);
  window.addEventListener(R175_R140_EVENT,receive as EventListener);
  return()=>{window.removeEventListener(R173_EVENT,receive as EventListener);window.removeEventListener(R175_R140_EVENT,receive as EventListener)};
 },[]);
 const mission=useMemo(()=>composeLivingWorldMissionR177({...pulse,revision:'R175'},{operatorStaged:staged}),[pulse,staged]);
 const stageMission=()=>{if(!mission?.accepted)return;const next=composeLivingWorldMissionR177({...pulse,revision:'R175'},{operatorStaged:true});setStaged(true);setStagedMission(next);setOperatorOpen(true);setOperatorMessage('R177 mission staged. Resolve each step against current R143 authority before authorization.');try{localStorage.setItem('omega.r177.stagedMission',JSON.stringify(next))}catch{};window.dispatchEvent(new CustomEvent(R177_EVENT,{detail:next}))};
 const resolveContracts=()=>{if(!stagedMission||busy)return;const next=resolveLivingWorldMissionAgainstAuthorityR178(stagedMission);setResolution(next);setSelected([]);setAuthorizeConfirmed(false);setAuthorization(null);setDispatchConfirmed(false);setDispatchReceipt(null);setOperatorMessage(next?.accepted?`R178 resolved ${next.resolvedSteps?.length||0} mission steps; ${next.heldCount||0} remain held.`:'R178 rejected the staged mission.');};
 const toggleStep=(index:number)=>setSelected(current=>current.includes(index)?current.filter(x=>x!==index):[...current,index].sort((a,b)=>a-b));
 const authorizeSelected=async()=>{if(!resolution||!authorizeConfirmed||!selected.length||busy)return;setBusy('authorize');setOperatorMessage('Authorizing selected R143 contracts into durable R146 history…');try{const receipt=await authorizeLivingWorldResolutionR181(resolution,{authorized:true,confirmation:R181_AUTHORIZE_CONFIRMATION,authorizedStepIndexes:selected});setAuthorization(receipt);setDispatchConfirmed(false);setDispatchReceipt(null);setOperatorMessage(`${receipt.runs.length} durable run${receipt.runs.length===1?'':'s'} AUTHORIZED. Nothing has been dispatched yet.`)}catch(error){setOperatorMessage(error instanceof Error?error.message:String(error))}finally{setBusy('')}};
 const dispatchAuthorized=async()=>{if(!authorization||!dispatchConfirmed||busy)return;setBusy('dispatch');setOperatorMessage('Dispatching only the explicitly authorized durable runs through R147…');try{const receipt=await dispatchLivingWorldAuthorizationR181(authorization,{dispatchConfirmed:true,confirmation:R181_DISPATCH_CONFIRMATION,strategy:'AUTO'});setDispatchReceipt(receipt);setOperatorMessage(`R147 dispatch completed for ${receipt.results?.length||0} run${receipt.results?.length===1?'':'s'}. Receipt states below remain authoritative.`)}catch(error){setOperatorMessage(error instanceof Error?error.message:String(error))}finally{setBusy('')}};
 const refreshReceipts=async()=>{if(!authorization?.runs?.length||busy)return;setBusy('refresh');try{const receipt=await refreshLivingWorldDispatchR181(authorization.runs.map((x:any)=>x.runId));setDispatchReceipt({...receipt,state:'REFRESHED_FROM_R147'});setOperatorMessage('Execution receipts refreshed from the durable runtime.')}catch(error){setOperatorMessage(error instanceof Error?error.message:String(error))}finally{setBusy('')}};
 const federation=pulse.federationClosed?'CLOSED RECEIPT CHAIN':pulse.federationStage==='NONE'?'NO NEW FEDERATION RECEIPT':`${pulse.federationStage} VERIFIED`;
 const domains=`MISSION ${pulse.truthBands.mission} · EARTH ${pulse.truthBands.earth} · HYBRID ${pulse.truthBands.hybrid} · RENDER ${pulse.truthBands.render}`;
 const missionSteps=mission?.accepted&&Array.isArray(mission?.mission?.steps)?mission.mission.steps:[];
 const resolvedSteps=Array.isArray(resolution?.resolvedSteps)?resolution.resolvedSteps:[];
 const receiptRows=Array.isArray(dispatchReceipt?.results)?dispatchReceipt.results:[];
 return <section className='r174-pulse' aria-label='Living canonical world truth surface' data-closed={pulse.federationClosed?'true':'false'}>
  <div className='r174-pulse-title'><Activity/><span><b>LIVING WORLD</b><small>R140 + R173 → R175 · multi-domain evidence, one authority-preserving view</small></span></div>
  <div className='r174-pulse-state'><span>WORLD TRUTH · {pulse.sourceRevision}</span><b>{federation}</b><small>{pulse.nextFederationStage?`NEXT ${pulse.nextFederationStage} · `:''}{domains}</small></div>
  <div className='r174-pulse-metrics'><span><b>{pulse.scarCount}</b><small>SCARS</small></span><span><b>{pulse.lod??'—'}</b><small>LOD</small></span><span><b>{pulse.sampleBudget??'—'}</b><small>SAMPLES</small></span></div>
  <div className='r174-pulse-truth'><ShieldCheck/><span><b>PROOF BOUND</b><small>PC {pulse.claims.pcOnlineProved?'PROVED THIS EVENT':'UNPROVEN'} · SOLVER {pulse.claims.solverValidityProved?'PROVED':'UNPROVEN'} · PHOTOREAL {pulse.claims.computedPhotorealRealityProved?'DIRECT PROOF THIS EVENT':'UNPROVEN'}</small></span></div>
  <div className='r174-pulse-actions'><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Proof</button><button onClick={()=>onNavigate('Hybrid Link')}><Link2/>Hybrid</button><button onClick={()=>onNavigate('Earth Now')}><Earth/>Earth</button><button onClick={()=>onNavigate('Convergence')}>World <ArrowRight/></button></div>
  <div className='r177-mission' data-staged={staged?'true':'false'}><Sparkles/><span><b>{staged?'MISSION STAGED · NOT AUTHORIZED':'MISSION PROPOSAL'}</b><small>{missionSteps.length?missionSteps.map((step:any)=>step.action).join(' · '):'Awaiting accepted living-world state'} · execution remains explicitly governed</small></span><div className='r177-mission-buttons'><button disabled={!mission?.accepted||staged} onClick={stageMission}>{staged?'Staged':'Stage mission'}</button>{staged&&<button onClick={()=>setOperatorOpen(v=>!v)}>{operatorOpen?'Collapse operator':'Open operator'}</button>}</div></div>
  {staged&&operatorOpen&&<div className='r181-operator' aria-label='R181 living-world operator execution'>
   <header><span><b>R181 · OPERATOR EXECUTION</b><small>R178 contract resolution → R179 authorization semantics → R146 durable history → separately confirmed R147 dispatch</small></span><strong>CANON · R125 ONLY</strong></header>
   <div className='r181-stagebar'><span data-active={staged?'true':'false'}>R177 STAGED</span><span data-active={resolution?'true':'false'}>R178 {resolution?'RESOLVED':'PENDING'}</span><span data-active={authorization?'true':'false'}>R179 {authorization?'AUTHORIZED':'PENDING'}</span><span data-active={dispatchReceipt?'true':'false'}>R147 {dispatchReceipt?'RECEIPTS':'NOT DISPATCHED'}</span></div>
   {!resolution&&<button className='r181-primary' onClick={resolveContracts} disabled={Boolean(busy)}>Resolve mission against current R143 contracts</button>}
   {resolution&&<div className='r181-resolution'><div className='r181-resolution-title'><span><b>{resolution.state}</b><small>{resolution.heldCount||0} held · {resolvedSteps.filter(ready).length} eligible · selection is explicit</small></span><button onClick={resolveContracts} disabled={Boolean(busy)}>Re-resolve</button></div><div className='r181-step-list'>{resolvedSteps.map((step:any)=><label key={step.index} data-ready={ready(step)?'true':'false'}><input type='checkbox' disabled={!ready(step)||Boolean(authorization)} checked={selected.includes(step.index)} onChange={()=>toggleStep(step.index)}/><span><b>{step.domain||'STEP'} · {step.route||'NO ROUTE'}</b><small>{step.action||step.reason||'No action'} · {step.readiness}</small></span></label>)}</div></div>}
   {resolution&&!authorization&&<div className='r181-confirm'><label><input type='checkbox' checked={authorizeConfirmed} onChange={e=>setAuthorizeConfirmed(e.target.checked)}/><span><b>Authorize selected contracts</b><small>Creates R146 durable history and advances only to AUTHORIZED. This does not dispatch execution.</small></span></label><button className='r181-primary' disabled={!authorizeConfirmed||!selected.length||Boolean(busy)} onClick={authorizeSelected}>{busy==='authorize'?'Authorizing…':`Authorize ${selected.length||''} selected`}</button></div>}
   {authorization&&<div className='r181-authorized'><div className='r181-run-list'>{authorization.runs.map((run:any)=><span key={run.runId}><b>{run.state}</b><small>{run.route} · {run.executionDomain} · {run.runId}</small></span>)}</div>{!dispatchReceipt&&<div className='r181-confirm dispatch'><label><input type='checkbox' checked={dispatchConfirmed} onChange={e=>setDispatchConfirmed(e.target.checked)}/><span><b>Second confirmation · dispatch through R147</b><small>This can invoke AI, Hybrid, federation, local, proof, swarm, or plugin execution according to the existing R147 domain authority.</small></span></label><button className='r181-primary' disabled={!dispatchConfirmed||Boolean(busy)} onClick={dispatchAuthorized}>{busy==='dispatch'?'Dispatching…':'Dispatch authorized runs'}</button></div>}</div>}
   {dispatchReceipt&&<div className='r181-receipts'><div className='r181-resolution-title'><span><b>{dispatchReceipt.state||'R147 RECEIPTS'}</b><small>Execution state is shown exactly as returned. RETURNED ≠ VERIFIED ≠ factual truth ≠ Canon admission.</small></span><button disabled={Boolean(busy)} onClick={refreshReceipts}>{busy==='refresh'?'Refreshing…':'Refresh receipts'}</button></div><div className='r181-receipt-list'>{receiptRows.map((row:any)=><span key={row.runId}><b>{row.state||'UNKNOWN'}{row.executorId?` · ${row.executorId}`:''}</b><small>{row.runId}{row.code?` · ${row.code}`:''}</small></span>)}</div></div>}
   {operatorMessage&&<div className='r181-message'>{operatorMessage}</div>}
   <footer><ShieldCheck/><span>R181 does not create a new executor. It uses authenticated R146 durable runs and the existing R147 dispatcher. R125 remains the sole CanonState admission authority.</span></footer>
  </div>}
 </section>;
}
