import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowRight,Earth,Link2,ShieldCheck,Sparkles} from 'lucide-react';
import {R173_EVENT} from './world/federationLedgerWorldObserverR173.js';
import {R175_R140_EVENT,projectMultiDomainLivingWorldTruthR175} from './world/multiDomainLivingWorldTruthR175.js';
import {composeLivingWorldMissionR177,R177_EVENT} from './world/livingWorldMissionComposerR177.js';
import {authorizeResolvedLivingWorldMissionR180,dispatchAuthorizedLivingWorldMissionClientR180,resolveStagedLivingWorldMissionR180,type R180AuthorizationReceipt} from './livingWorldExecutionClientR180';
import './livingWorldPulseR174.css';

type Bands={mission:string;earth:string;federation:string;hybrid:string;render:string};
type Pulse={revision?:string;eventAccepted:boolean;sourceRevision:string;worldId:string|null;operationRef:unknown;federationStage:string;nextFederationStage:string|null;federationClosed:boolean;truthBands:Bands;activeDomains:string[];lod:number|null;sampleBudget:number|null;scarCount:number;routingTarget:string|null;dispatchAuthorized:boolean;claims:{pcOnlineProved:boolean;solverValidityProved:boolean;computedPhotorealRealityProved:boolean}};
type Props={onNavigate:(panel:string)=>void};
const EMPTY:Pulse={revision:'R175',eventAccepted:false,sourceRevision:'NONE',worldId:null,operationRef:null,federationStage:'NONE',nextFederationStage:null,federationClosed:false,truthBands:{mission:'NONE',earth:'UNPROVED',federation:'NONE',hybrid:'DEVICE_PROOF_REQUIRED',render:'NONE'},activeDomains:[],lod:null,sampleBudget:null,scarCount:0,routingTarget:null,dispatchAuthorized:false,claims:{pcOnlineProved:false,solverValidityProved:false,computedPhotorealRealityProved:false}};

export default function LivingWorldPulseR174({onNavigate}:Props){
 const[pulse,setPulse]=useState<Pulse>(EMPTY);const[staged,setStaged]=useState(false);const[stagedMission,setStagedMission]=useState<any>(null);const[resolution,setResolution]=useState<any>(null);const[authorization,setAuthorization]=useState<R180AuthorizationReceipt|null>(null);const[execution,setExecution]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{const receive=(event:Event)=>{const next=projectMultiDomainLivingWorldTruthR175((event as CustomEvent).detail) as Pulse;if(!next.eventAccepted)return;setPulse(next);setStaged(false);setStagedMission(null);setResolution(null);setAuthorization(null);setExecution(null);setError('');try{localStorage.setItem('omega.r175.worldTruthSurface',JSON.stringify({...next,claims:{...next.claims,pcOnlineProved:false,computedPhotorealRealityProved:false}}))}catch{}};window.addEventListener(R173_EVENT,receive as EventListener);window.addEventListener(R175_R140_EVENT,receive as EventListener);return()=>{window.removeEventListener(R173_EVENT,receive as EventListener);window.removeEventListener(R175_R140_EVENT,receive as EventListener)}},[]);
 const mission=useMemo(()=>composeLivingWorldMissionR177({...pulse,revision:'R175'},{operatorStaged:staged}),[pulse,staged]);
 const missionSteps=mission?.accepted&&Array.isArray(mission?.mission?.steps)?mission.mission.steps:[];const readySteps=resolution?.accepted&&Array.isArray(resolution?.resolvedSteps)?resolution.resolvedSteps.filter((step:any)=>step.readiness==='CONTRACT_RESOLVED_NOT_AUTHORIZED'):[];const heldSteps=resolution?.accepted&&Array.isArray(resolution?.resolvedSteps)?resolution.resolvedSteps.filter((step:any)=>step.readiness!=='CONTRACT_RESOLVED_NOT_AUTHORIZED'):[];
 const stageMission=()=>{if(!mission?.accepted)return;const next=composeLivingWorldMissionR177({...pulse,revision:'R175'},{operatorStaged:true});const resolved=resolveStagedLivingWorldMissionR180(next);setStaged(true);setStagedMission(next);setResolution(resolved);setAuthorization(null);setExecution(null);setError('');try{localStorage.setItem('omega.r177.stagedMission',JSON.stringify(next));localStorage.setItem('omega.r178.contractResolution',JSON.stringify(resolved))}catch{};window.dispatchEvent(new CustomEvent(R177_EVENT,{detail:next}))};
 const authorizeReady=async()=>{if(!stagedMission||!readySteps.length||busy)return;setBusy(true);setError('');try{const auth=await authorizeResolvedLivingWorldMissionR180(resolution,readySteps.map((step:any)=>step.index));setAuthorization(auth);setExecution(null);try{localStorage.setItem('omega.r179.authorizationReceipt',JSON.stringify(auth))}catch{}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const dispatchAuthorized=async()=>{if(!authorization||busy)return;setBusy(true);setError('');try{const result=await dispatchAuthorizedLivingWorldMissionClientR180(authorization,{confirmHostExecution:false});setExecution(result);try{localStorage.setItem('omega.r180.executionReceipt',JSON.stringify(result))}catch{}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const federation=pulse.federationClosed?'CLOSED RECEIPT CHAIN':pulse.federationStage==='NONE'?'NO NEW FEDERATION RECEIPT':`${pulse.federationStage} VERIFIED`;const domains=`MISSION ${pulse.truthBands.mission} · EARTH ${pulse.truthBands.earth} · HYBRID ${pulse.truthBands.hybrid} · RENDER ${pulse.truthBands.render}`;const verifiedCount=execution?.results?.filter((x:any)=>x.verified).length||0,invokedCount=execution?.results?.filter((x:any)=>x.executionInvoked).length||0,hostHeld=execution?.results?.filter((x:any)=>x.status==='HELD_HOST_EXECUTION_CONFIRMATION_REQUIRED').length||0;const operationState=execution?`${verifiedCount} VERIFIED · ${invokedCount} INVOKED · ${hostHeld} HOST HELD`:authorization?`${authorization.runs.length} AUTHORIZED · NOT YET DISPATCHED`:resolution?`${readySteps.length} READY · ${heldSteps.length} HELD`:staged?'STAGED · RESOLVING':'NOT STAGED';
 return <section className='r174-pulse' aria-label='Living canonical world truth surface' data-closed={pulse.federationClosed?'true':'false'}><div className='r174-pulse-title'><Activity/><span><b>LIVING WORLD</b><small>R140 + R173 → R180 · truth → mission → contract → authorization → governed dispatch</small></span></div><div className='r174-pulse-state'><span>WORLD TRUTH · {pulse.sourceRevision}</span><b>{federation}</b><small>{pulse.nextFederationStage?`NEXT ${pulse.nextFederationStage} · `:''}{domains}</small></div><div className='r174-pulse-metrics'><span><b>{pulse.scarCount}</b><small>SCARS</small></span><span><b>{pulse.lod??'—'}</b><small>LOD</small></span><span><b>{pulse.sampleBudget??'—'}</b><small>SAMPLES</small></span></div><div className='r174-pulse-truth'><ShieldCheck/><span><b>PROOF BOUND</b><small>PC {pulse.claims.pcOnlineProved?'PROVED THIS EVENT':'UNPROVEN'} · SOLVER {pulse.claims.solverValidityProved?'PROVED':'UNPROVEN'} · PHOTOREAL {pulse.claims.computedPhotorealRealityProved?'DIRECT PROOF THIS EVENT':'UNPROVEN'}</small></span></div><div className='r174-pulse-actions'><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Proof</button><button onClick={()=>onNavigate('Hybrid Link')}><Link2/>Hybrid</button><button onClick={()=>onNavigate('Earth Now')}><Earth/>Earth</button><button onClick={()=>onNavigate('Convergence')}>World <ArrowRight/></button></div><div className='r177-mission' data-staged={staged?'true':'false'} data-executing={busy?'true':'false'}><Sparkles/><span><b>{operationState}</b><small>{error?`HELD · ${error}`:missionSteps.length?missionSteps.map((step:any)=>step.action).join(' · '):'Awaiting accepted living-world state'} · R125 remains sole CanonState admission</small></span><div className='r180-controls'><button disabled={!mission?.accepted||staged||busy} onClick={stageMission}>{staged?'Staged':'Stage mission'}</button><button disabled={!staged||!readySteps.length||!!authorization||busy} onClick={authorizeReady}>{authorization?'Authorized':`Authorize ${readySteps.length||''}`}</button><button disabled={!authorization||!!execution||busy} onClick={dispatchAuthorized}>{execution?'Dispatched':'Dispatch authorized'}</button></div></div>{hostHeld>0&&<div className='r180-host-hold'><ShieldCheck/><span><b>{hostHeld} HOST EXECUTION {hostHeld===1?'RUN':'RUNS'} HELD</b><small>Hybrid/Build requires a separate host confirmation in Hybrid Link. Queueing or authorization is not invocation.</small></span><button onClick={()=>onNavigate('Hybrid Link')}>Open Hybrid</button></div>}</section>;
}
