import {useEffect,useMemo,useState} from 'react';
import {GitBranch,Route,ShieldCheck,Sparkles} from 'lucide-react';
import type {HybridMission} from './hybridMissionRuntime';
import {buildMissionContinuity} from './missionContinuityR204';
import {R2023_EVENT} from './world/livingSceneVisualR2023.js';
import {R208_EVENT,R208_SNAPSHOT_KEY} from './world/missionWorldHeadBindingR208';
import {compileRenderIntentLineageR211} from './world/renderIntentLineageR211.js';
import {compileAdaptiveRenderAttemptR213} from './world/adaptiveRenderAttemptR213.js';
import {compileRenderAttemptContinuityR214,persistRenderAttemptContinuityR214,readRenderAttemptContinuityR214} from './world/renderAttemptContinuityR214.js';
import {compileEvidenceReconstructionIntentR216,persistEvidenceReconstructionIntentR216,readEvidenceReconstructionIntentR216,readLatestR215ArtifactReceipt} from './world/evidenceReconstructionIntentR216.js';
import {executeEvidenceReconstructionFrameR217,persistEvidenceReconstructionFrameR217,readEvidenceReconstructionFrameR217} from './world/evidenceReconstructionFrameR217.js';
import {emitOperationR86} from './omegaOperationBusR86';
import {activeProjectIdR87,recordProjectOperationR87} from './omegaProjectContinuityR87';
import './missionWorldContinuityR206.css';

export const R206_MISSION_EVENT='omega-r206-mission-continuity';
const MISSION_KEY='omega.v6.hybrid.missions';
const SCENE_VISUAL_KEY='omega.r2023.livingSceneVisual';
const PERFORMANCE_KEY='omega.r185.performance';

type Props={onNavigate:(panel:string)=>void};
type Snapshot={missions:HybridMission[];scene:any;binding:any;performance:any};
const parse=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
const read=():Snapshot=>({missions:parse<HybridMission[]>(MISSION_KEY,[]),scene:parse<any>(SCENE_VISUAL_KEY,null),binding:parse<any>(R208_SNAPSHOT_KEY,null),performance:parse<any>(PERFORMANCE_KEY,null)});

export default function MissionWorldContinuityR206({onNavigate}:Props){
 const[state,setState]=useState<Snapshot>(()=>read());
 const[renderLineage,setRenderLineage]=useState<any>(null);
 const[renderAttempt,setRenderAttempt]=useState<any>(null);
 const[renderAnchor,setRenderAnchor]=useState<any>(()=>readRenderAttemptContinuityR214());
 const[reconstructionIntent,setReconstructionIntent]=useState<any>(()=>readEvidenceReconstructionIntentR216());
 const[reconstructionFrame,setReconstructionFrame]=useState<any>(()=>readEvidenceReconstructionFrameR217());
 useEffect(()=>{const refresh=()=>setState(read());window.addEventListener(R206_MISSION_EVENT,refresh as EventListener);window.addEventListener(R2023_EVENT,refresh as EventListener);window.addEventListener(R208_EVENT,refresh as EventListener);window.addEventListener('omega-r86-operation',refresh as EventListener);window.addEventListener('storage',refresh);return()=>{window.removeEventListener(R206_MISSION_EVENT,refresh as EventListener);window.removeEventListener(R2023_EVENT,refresh as EventListener);window.removeEventListener(R208_EVENT,refresh as EventListener);window.removeEventListener('omega-r86-operation',refresh as EventListener);window.removeEventListener('storage',refresh)}},[]);
 const view=useMemo(()=>{const current=state.missions[state.missions.length-1]||null;const chain=buildMissionContinuity(state.missions);const anchor=chain[chain.length-1]||null;const scene=state.scene;const binding=state.binding?.missionId===current?.id?state.binding:null;const sceneBound=Boolean(scene?.eventAccepted);const renderReady=Boolean(scene?.renderInputReady);const proof=current?.returnPacket?.proof_status||'NO_MISSION';const route=current?.adapter||'UNASSEMBLED';return{current,anchor,scene,sceneBound,renderReady,proof,route,binding,performance:state.performance}},[state]);
 useEffect(()=>{let alive=true;if(!view.current||!view.anchor){setRenderLineage(null);return()=>{alive=false}};void compileRenderIntentLineageR211({mission:view.current,anchor:view.anchor,binding:view.binding,scene:view.scene}).then(receipt=>{if(alive)setRenderLineage(receipt)}).catch(()=>{if(alive)setRenderLineage(null)});return()=>{alive=false}},[view.current,view.anchor,view.binding,view.scene]);
 useEffect(()=>{let alive=true;if(!renderLineage){setRenderAttempt(null);return()=>{alive=false}};void compileAdaptiveRenderAttemptR213({lineage:renderLineage,performance:view.performance}).then(receipt=>{if(alive)setRenderAttempt(receipt)}).catch(()=>{if(alive)setRenderAttempt(null)});return()=>{alive=false}},[renderLineage,view.performance]);
 useEffect(()=>{let alive=true;if(!renderAttempt){setRenderAnchor(null);return()=>{alive=false}};const projectId=activeProjectIdR87();void compileRenderAttemptContinuityR214({attempt:renderAttempt,projectId}).then(async receipt=>{if(!alive)return;setRenderAnchor(receipt);if(receipt.state!=='RENDER_ATTEMPT_CONTINUITY_READY')return;const prior=readRenderAttemptContinuityR214();if(prior?.anchorSha256===receipt.anchorSha256)return;if(!persistRenderAttemptContinuityR214(receipt))return;const event=await emitOperationR86({type:'RENDER_ATTEMPT_CONTINUITY_ANCHORED',surface:'Living World',status:'PASS',detail:`Anchored R213 render attempt ${String(receipt.parentAttemptSha256).slice(0,12)} for recoverable continuity`,payload:{anchorSha256:receipt.anchorSha256,parentAttemptSha256:receipt.parentAttemptSha256,parentLineageSha256:receipt.parentLineageSha256,missionId:receipt.missionId,worldBindingOperationSha256:receipt.worldBindingOperationSha256,projectId:receipt.projectId,profile:receipt.profile,canonicalMutation:false,renderAttemptExecuted:false,renderedFrame:false,renderReceipt:false}});await recordProjectOperationR87(projectId,event)}).catch(()=>{if(alive)setRenderAnchor(null)});return()=>{alive=false}},[renderAttempt]);
 useEffect(()=>{let alive=true;if(!view.current||!renderAnchor){setReconstructionIntent(null);return()=>{alive=false}};const projectId=activeProjectIdR87(),artifactReceipt=readLatestR215ArtifactReceipt();void compileEvidenceReconstructionIntentR216({mission:view.current,anchor:renderAnchor,scene:view.scene,artifactReceipt,projectId}).then(async receipt=>{if(!alive)return;setReconstructionIntent(receipt);if(receipt.state!=='EVIDENCE_RECONSTRUCTION_INTENT_READY')return;const prior=readEvidenceReconstructionIntentR216();if(prior?.requestSha256===receipt.requestSha256)return;if(!persistEvidenceReconstructionIntentR216(receipt))return;const event=await emitOperationR86({type:'EVIDENCE_RECONSTRUCTION_INTENT_COMPILED',surface:'Living World',status:'PASS',detail:`Compiled R122 evidence reconstruction request ${String(receipt.requestSha256).slice(0,12)} without executing a renderer`,payload:{requestSha256:receipt.requestSha256,missionId:receipt.missionId,r214AnchorSha256:receipt.r214AnchorSha256,r215ArtifactReceiptSha256:receipt.r215ArtifactReceiptSha256,earthHash:receipt.earthHash,groundHash:receipt.groundHash,evidenceDigest:receipt.evidenceDigest,requestedAuthority:'R122',rendererInvoked:false,reconstructionExecuted:false,renderedFrame:false,computedPhotorealRealityProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}).catch(()=>{if(alive)setReconstructionIntent(null)});return()=>{alive=false}},[view.current,view.scene,renderAnchor,state]);
 useEffect(()=>{let alive=true;if(reconstructionIntent?.state!=='EVIDENCE_RECONSTRUCTION_INTENT_READY'){setReconstructionFrame(null);return()=>{alive=false}};void executeEvidenceReconstructionFrameR217({request:reconstructionIntent,scene:view.scene,performance:view.performance}).then(async receipt=>{if(!alive)return;setReconstructionFrame(receipt);if(receipt.state!=='EVIDENCE_RECONSTRUCTION_FRAME_RENDERED')return;const prior=readEvidenceReconstructionFrameR217();if(prior?.receiptSha256===receipt.receiptSha256)return;if(!persistEvidenceReconstructionFrameR217(receipt))return;const projectId=activeProjectIdR87();const event=await emitOperationR86({type:'EVIDENCE_RECONSTRUCTION_FRAME_RENDERED',surface:'Living World',status:'PASS',detail:`Rendered bounded R217 evidence-state frame ${String(receipt.frameSha256).slice(0,12)} and returned it to R216`,payload:{receiptSha256:receipt.receiptSha256,frameSha256:receipt.frameSha256,frameBytes:receipt.frameBytes,width:receipt.width,height:receipt.height,profile:receipt.profile,r216RequestSha256:receipt.r216RequestSha256,r214AnchorSha256:receipt.r214AnchorSha256,r208WorldBindingOperationSha256:receipt.r208WorldBindingOperationSha256,evidenceBoundRepresentationalFrame:true,empiricalPixelReconstruction:false,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,federationClosureProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}).catch(()=>{if(alive)setReconstructionFrame(null)});return()=>{alive=false}},[reconstructionIntent,view.scene,view.performance]);
 if(!view.current||!view.anchor)return <section className='r206-world-mission' data-state='EMPTY' aria-label='Living world mission continuity'><div className='r206-world-mission-icon'><GitBranch/></div><div><small>R206 · MISSION → ONE WORLD CONTINUITY</small><b>No mission continuity anchor yet</b><span>Compile an intent in Hybrid Mission Control. The canonical world remains unchanged until evidence and proof arrive.</span></div><button onClick={()=>onNavigate('Hybrid Link')}>Open Hybrid</button></section>;
 const held=view.proof==='PROOF_REQUIRED'||view.anchor.status==='HELD_FOR_PROOF';
 const stateLabel=held?'PROOF HELD':view.sceneBound?'WORLD BOUND':'MISSION ASSEMBLED';
 const durableLabel=view.binding?`${view.binding.state} · ${String(view.binding.operationSha256||'').slice(0,12)}`:'WORLD-HEAD BINDING PENDING';
 const renderLabel=renderLineage?.state==='RENDER_INTENT_LINEAGE_READY'?`R211 READY · ${String(renderLineage.lineageSha256).slice(0,12)}`:`R211 HELD${renderLineage?.missing?.length?` · ${renderLineage.missing.join('/')}`:''}`;
 const attemptLabel=renderAttempt?.state==='ADAPTIVE_RENDER_ATTEMPT_READY'?`R213 ${renderAttempt.profile} · ${String(renderAttempt.attemptSha256).slice(0,12)}`:'R213 HELD · R211 proof required';
 const anchorLabel=renderAnchor?.state==='RENDER_ATTEMPT_CONTINUITY_READY'?`R214 ANCHORED · ${String(renderAnchor.anchorSha256).slice(0,12)}`:'R214 HELD · R213 attempt required';
 const reconstructionLabel=reconstructionIntent?.state==='EVIDENCE_RECONSTRUCTION_INTENT_READY'?`R216 R122 REQUEST READY · ${String(reconstructionIntent.requestSha256).slice(0,12)}`:`R216 HELD${reconstructionIntent?.missing?.length?` · ${reconstructionIntent.missing.join('/')}`:' · R215 artifact + evidence required'}`;
 const frameLabel=reconstructionFrame?.state==='EVIDENCE_RECONSTRUCTION_FRAME_RENDERED'?`R217 ${reconstructionFrame.profile} FRAME · ${String(reconstructionFrame.frameSha256).slice(0,12)} · ${reconstructionFrame.frameBytes}B`:'R217 HELD · R216 proof-ready request required';
 const frameSrc=reconstructionFrame?.frameSvg?`data:image/svg+xml;charset=utf-8,${encodeURIComponent(reconstructionFrame.frameSvg)}`:'';
 return <section className='r206-world-mission' data-state={held?'HELD':view.sceneBound?'BOUND':'ASSEMBLED'} aria-label='Living world mission continuity'>
  <div className='r206-world-mission-icon'><Sparkles/></div>
  <div className='r206-world-mission-copy'><small>R204 → R206 → R208 → R211 → R213 → R214 → R215 → R216 → R217 · INTENT · WORLD · PRE-RENDER LINEAGE · ADAPTIVE ATTEMPT · RECOVERABLE CONTINUITY · BYTE PROOF · RECONSTRUCTION INTENT · EXECUTED REPRESENTATIONAL FRAME</small><b>{stateLabel} · {view.current.command}</b><span><Route/> {view.route} · continuity {view.anchor.carryHash} · scar {view.anchor.scarCarry.toFixed(3)} · return {view.anchor.returnCarry.toFixed(3)}</span><em>{durableLabel} · {view.sceneBound?'Evidence-bound scene attached':'Scene evidence not attached'} · R122 {view.renderReady?'INPUT READY':'HELD'} · {renderLabel} · {attemptLabel} · {anchorLabel} · {reconstructionLabel} · R216 RECONSTRUCTION NOT EXECUTED · R216 FRAME NOT RENDERED · {frameLabel} · R217 BOUNDED REPRESENTATIONAL RECONSTRUCTION EXECUTED WHEN READY · EMPIRICAL PIXELS NOT RECONSTRUCTED · COMPUTED PHOTOREAL REALITY UNPROVEN</em>{frameSrc&&<img src={frameSrc} alt='R217 evidence-bound representational reconstruction frame; not empirical imagery' style={{width:'100%',maxWidth:360,borderRadius:10,marginTop:8,display:'block'}}/>}</div>
  <div className='r206-world-mission-proof'><ShieldCheck/><span>{view.proof}</span><span>World R134 · persist R149/R97</span><span>Render continuity R86/R87/R97</span><span>R122 request proof-gated</span><span>R217 exact frame-byte proof</span><span>Canon R125 only</span><span>Federation receipt-gated</span></div>
  <button onClick={()=>onNavigate('Hybrid Link')}><GitBranch/>Inspect mission</button>
 </section>;
}
