import {useEffect,useState} from 'react';
import {Pause,Play,ShieldCheck,StepBack,StepForward} from 'lucide-react';
import MatterTraversal from './MatterTraversal';
import OmegaVisualInstrument from './OmegaVisualInstrument';
import OmegaTraversalStudio from './OmegaTraversalStudio';
import OmegaMotionSkinMapR35 from './OmegaMotionSkinMapR35';
import CalculusFieldR37 from './CalculusFieldR37';
import CapabilityMatrixR43 from './CapabilityMatrixR43';
import BiologicalTraversalR46 from './BiologicalTraversalR46';
import CinematicFieldRendererR46 from './CinematicFieldRendererR46';
import VisualCompositorR65 from './VisualCompositorR65';
import {corpusState} from './corpusRuntime';
import {CanonicalPacketTruthPlotR93,TransitionTruthPlotR93} from './TruthVisualsR93';
import './livingSurfaceR36.css';
import './capabilityRestoreR43.css';

type WorkspaceView='LIVE'|'CAPABILITY'|'DEEP'|'ROUTE';
type VisualDisplay='FIELD'|'FORECAST'|'RELATIVITY'|'INFINITY'|'SCALE'|'CONVERGENCE'|'MOTION'|'CINEMATIC';
const VISUAL_DISPLAYS:readonly {id:VisualDisplay;label:string;meaning:string}[]=[
 {id:'FIELD',label:'Unified Field',meaning:'five-role calculus field'},
 {id:'FORECAST',label:'Forecast',meaning:'future-plasticity projection'},
 {id:'RELATIVITY',label:'Relativity',meaning:'observer-relative projection'},
 {id:'INFINITY',label:'Recurrence',meaning:'recursive / recurrence view'},
 {id:'SCALE',label:'Scale',meaning:'nested scale compiler'},
 {id:'CONVERGENCE',label:'Convergence',meaning:'closure / integration view'},
 {id:'MOTION',label:'Motion Skin',meaning:'route and motion membrane'},
 {id:'CINEMATIC',label:'Cinematic',meaning:'bounded browser still renderer'}
] as const;
const clamp=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0)));
function nextOf(a:number){return clamp(corpusState(clamp(a)).autoPing?.dataNext??a)}
function prevOf(a:number){return clamp(corpusState(clamp(a)).autoPing?.previous??a)}
function useActualTraversal(address:number,onAddress:(n:number)=>void){const[running,setRunning]=useState(false),[rate,setRate]=useState(900),[ticks,setTicks]=useState(0);useEffect(()=>{if(!running)return;const id=window.setInterval(()=>{onAddress(nextOf(address));setTicks(x=>x+1)},rate);return()=>window.clearInterval(id)},[running,rate,address,onAddress]);return{running,setRunning,rate,setRate,ticks}}
function TraversalBar({address,onAddress,label}:{address:number;onAddress:(n:number)=>void;label:string}){const t=useActualTraversal(address,onAddress),r=corpusState(address);return <div className='r36-traversal-bar'><button onClick={()=>onAddress(prevOf(address))}><StepBack/>Previous</button><button className={t.running?'active primary-action':'primary-action'} onClick={()=>t.setRunning(v=>!v)}>{t.running?<Pause/>:<Play/>}{t.running?'Traversing':'Traverse'}</button><button onClick={()=>onAddress(nextOf(address))}><StepForward/>Source next</button><label>rate<select value={t.rate} onChange={e=>t.setRate(Number(e.target.value))}><option value='1500'>slow</option><option value='900'>normal</option><option value='450'>fast</option></select></label><span><b>{label}</b> · {r.stateId} · {t.ticks} enacted address transitions</span></div>}
function useWorkspaceView(key:string){const[v,setV]=useState<WorkspaceView>(()=>{const x=localStorage.getItem(`omega.r43.${key}.view`) as WorkspaceView|null;return x&&['LIVE','CAPABILITY','DEEP','ROUTE'].includes(x)?x:'LIVE'});const set=(x:WorkspaceView)=>{setV(x);localStorage.setItem(`omega.r43.${key}.view`,x)};return[v,set] as const}
function WorkspaceTabs({view,setView,deepLabel}:{view:WorkspaceView;setView:(v:WorkspaceView)=>void;deepLabel:string}){return <nav className='r43-workspace-tabs' aria-label='Specialist workspace depth'><button className={view==='LIVE'?'active':''} onClick={()=>setView('LIVE')}><b>LIVE DATA</b><span>source-driven spatial instrument</span></button><button className={view==='CAPABILITY'?'active':''} onClick={()=>setView('CAPABILITY')}><b>CAPABILITY MATRIX</b><span>144 × 12 × 12 operator space</span></button><button className={view==='DEEP'?'active':''} onClick={()=>setView('DEEP')}><b>{deepLabel}</b><span>restored specialist controls</span></button><button className={view==='ROUTE'?'active':''} onClick={()=>setView('ROUTE')}><b>ROUTE + PROOF</b><span>exact transition evidence</span></button></nav>}
function VisualDisplayDeck({address,onAddress}:{address:number;onAddress:(n:number)=>void}){const[display,setDisplayState]=useState<VisualDisplay>(()=>{const x=localStorage.getItem('omega.r58.visual.display') as VisualDisplay|null;return x&&VISUAL_DISPLAYS.some(v=>v.id===x)?x:'FIELD'}),r=corpusState(address);const setDisplay=(x:VisualDisplay)=>{setDisplayState(x);localStorage.setItem('omega.r58.visual.display',x)};const calculus=display!=='MOTION'&&display!=='CINEMATIC';return <section className='r58-visual-deck' data-display={display}><header><div><b>DISPLAY DECK</b><span>8 state-bound views · one canonical packet · no decorative shadow state</span></div><strong>{display}</strong></header><nav aria-label='Visual display family'>{VISUAL_DISPLAYS.map(v=><button key={v.id} className={display===v.id?'active':''} aria-pressed={display===v.id} onClick={()=>setDisplay(v.id)}><b>{v.label}</b><small>{v.meaning}</small></button>)}</nav><div className='r58-display-stage'>{calculus&&<CalculusFieldR37 address={address} mode={display as 'FIELD'|'FORECAST'|'RELATIVITY'|'INFINITY'|'SCALE'|'CONVERGENCE'} steps={display==='FORECAST'?42:30} observerBeta={display==='RELATIVITY'?.58:0} onAddress={onAddress} label={`${display} · FIVE-ROLE CALCULUS`}/>} {display==='MOTION'&&<OmegaMotionSkinMapR35 address={address} onSelectAddress={onAddress}/>} {display==='CINEMATIC'&&<CinematicFieldRendererR46 record={r} address={address}/>}</div><footer><span className='alpha'>ALPHA · possibility</span><span className='base'>BASE · evidence</span><span className='construct'>CONSTRUCT · expansion</span><span className='prune'>PRUNE · contradiction</span><span className='omega'>OMEGA · integration</span></footer></section>}

export function MatterTraversalR36({address,onAddress,state,onNavigate}:{address:number;onAddress:(n:number)=>void;state:any;onNavigate?:(p:string)=>void}){const r=corpusState(address),[view,setView]=useWorkspaceView('matter');return <section className='special-app r36-living-surface r43-restored-surface'><header className='r36-surface-head'><div><span>MATTER · DEWEY/RSC CALCULUS VOLUME · SOURCE-BOUND</span><h2>Matter Traversal</h2><p>Direct canonical packet data and the restored Matter compiler share one canonical address. Biological scale descent remains a representational domain view rather than a separate shadow state.</p></div><strong>{r.metrics.decision}</strong></header><WorkspaceTabs view={view} setView={setView} deepLabel='DEEP MATTER'/><div className='r43-workspace-stage' data-view={view}>{view==='LIVE'&&<><CanonicalPacketTruthPlotR93 record={r} title='Matter Traversal canonical packet'/><TraversalBar address={address} onAddress={onAddress} label='canonical matter evolution'/></>}{view==='CAPABILITY'&&<CapabilityMatrixR43 address={address} onAddress={onAddress} onNavigate={onNavigate}/>} {view==='DEEP'&&<MatterTraversal state={state} onCommit={(c:any)=>onAddress(1728*c.d+144*c.p+12*c.r+c.l)} onNavigate={onNavigate}/>} {view==='DEEP'&&<BiologicalTraversalR46 address={address} onAddress={onAddress}/>} {view==='ROUTE'&&<><TransitionTruthPlotR93 record={r} nextRecord={corpusState(nextOf(address))} title='Matter route / proof transition'/><TraversalBar address={address} onAddress={onAddress} label='route / proof traversal'/></>}</div><footer className='r36-truth'><ShieldCheck/>The rendered volume and biological descent are packet-bound representations. Atlas coordinates, reference scales and biology views are not relabeled as measured particle, cellular or molecular observations.</footer></section>}

export function VisualInstrumentR36({address,onAddress,onNavigate}:{address:number;onAddress:(n:number)=>void;onNavigate?:(p:string)=>void}){const r=corpusState(address),[view,setView]=useWorkspaceView('visual');return <section className='special-app r36-living-surface r36-visual r43-restored-surface'><header className='r36-surface-head'><div><span>VISUAL INSTRUMENT · SYNCHRONIZED COMPOSITOR + RESTORED COMPILER</span><h2>Visual Instrument</h2><p>The living field, forecast, relativity, recurrence, scale, convergence, motion skin, 20,736 depth camera, compiler lineage, capability atlas and bounded cinematic renderer remain reachable on the same canonical packet.</p></div></header><WorkspaceTabs view={view} setView={setView} deepLabel='DEEP COMPILER'/><div className='r43-workspace-stage' data-view={view}>{view==='LIVE'&&<><VisualCompositorR65 address={address} onAddress={onAddress}/><TraversalBar address={address} onAddress={onAddress} label='visual state evolution'/></>}{view==='CAPABILITY'&&<CapabilityMatrixR43 address={address} onAddress={onAddress} onNavigate={onNavigate}/>} {view==='DEEP'&&<OmegaVisualInstrument address={address} onCommit={onAddress}/>} {view==='ROUTE'&&<><OmegaMotionSkinMapR35 address={address} onSelectAddress={onAddress}/><TraversalBar address={address} onAddress={onAddress} label='visual route / proof'/></>}</div><footer className='r36-truth'><ShieldCheck/>Display switching changes the projection lens, never the canonical state owner. ALPHA, BASE, CONSTRUCT, PRUNE and OMEGA colors are semantic operator encodings, not decorative categories; native GPU/video remains separately gated.</footer></section>}

export function TraversalR36({variant,address,state,onAddress,onNavigate}:{variant:'Immersive Traversal'|'Extreme Traversal'|'Traversal';address:number;state:any;onAddress:(n:number)=>void;onNavigate?:(p:string)=>void}){const[view,setView]=useWorkspaceView(`traversal.${variant}`);return <section className='special-app r36-living-surface r43-restored-surface'><header className='r36-surface-head'><div><span>TRAVERSAL · WOVEN CONTINUITY · ENACTED ADDRESS ROUTE</span><h2>{variant}</h2><p>The primary LIVE surface is the source-driven woven traversal studio: current packet, CΩ/Φ/q/Λ, signed orientation, scar/history carry, route geometry and selectable source-backed depiction stay bound to one address. Exact transition evidence belongs in ROUTE + PROOF rather than replacing the live spatial instrument.</p></div></header><WorkspaceTabs view={view} setView={setView} deepLabel='DEEP STUDIO'/><div className='r43-workspace-stage' data-view={view}>{view==='LIVE'&&<><OmegaTraversalStudio variant={variant} address={address} state={state} onAddress={onAddress}/><TraversalBar address={address} onAddress={onAddress} label='woven source-state traversal'/></>}{view==='CAPABILITY'&&<CapabilityMatrixR43 address={address} onAddress={onAddress} onNavigate={onNavigate}/>} {view==='DEEP'&&<OmegaTraversalStudio variant={variant} address={address} state={state} onAddress={onAddress}/>} {view==='ROUTE'&&<><TransitionTruthPlotR93 record={corpusState(address)} nextRecord={corpusState(nextOf(address))} title={`${variant} · route / proof transition`}/><TraversalBar address={address} onAddress={onAddress} label='route / proof traversal'/></>}</div><footer className='r36-truth'><ShieldCheck/>Motion is enacted address-space evolution and the woven studio is a source-bound computational projection. Selecting an address does not itself admit CanonState; visual curvature, depth and atlas resolution remain representational, not unsupported extra physical dimensions.</footer></section>}
