import {useEffect,useMemo,useState} from 'react';
import {BrainCircuit,ChevronRight,Command,Globe2,Heart,Layers3,Search,ShieldCheck,Sparkles,Waypoints,X} from 'lucide-react';
import './omegaLauncher.css';

type Props={onNavigate:(name:string)=>void};
type Group='STUDIO'|'OPERATIONS'|'WORK'|'INTELLIGENCE'|'GOVERNANCE'|'SYSTEM';
type Surface={id:string;group:Group;name:string;hint:string};
export const LAUNCHER_SURFACES:Surface[]=[
{id:'01',group:'STUDIO',name:'Command Center',hint:'Ask, route, inspect and continue work'},{id:'02',group:'STUDIO',name:'Hybrid Link',hint:'Proof-gated device bridge and missions'},{id:'03',group:'STUDIO',name:'Workspace',hint:'General sovereign working surface'},{id:'04',group:'STUDIO',name:'Cockpit',hint:'Runtime operational overview'},{id:'05',group:'STUDIO',name:'Immersive Traversal',hint:'Continuous embodied state traversal'},{id:'06',group:'STUDIO',name:'Matter Traversal',hint:'Matter and conductance exploration'},{id:'07',group:'STUDIO',name:'Extreme Traversal',hint:'Deep microstructure state traversal'},{id:'08',group:'STUDIO',name:'Visual Instrument',hint:'Source-bound field renderer'},{id:'09',group:'STUDIO',name:'Relativity',hint:'Motion and reference-frame analysis'},{id:'10',group:'STUDIO',name:'Earth Now',hint:'Externally gated Earth evidence'},{id:'11',group:'STUDIO',name:'Forecast',hint:'Bounded future-state analysis'},{id:'12',group:'STUDIO',name:'Atlas',hint:'Executable 20,736-state atlas'},{id:'13',group:'STUDIO',name:'Traversal',hint:'General state-space traversal'},{id:'14',group:'STUDIO',name:'Create',hint:'Seed, translate, build and prove'},
{id:'15',group:'OPERATIONS',name:'Field',hint:'Inspect the canonical source packet'},{id:'16',group:'OPERATIONS',name:'Data Motion',hint:'Transport and motion operations'},{id:'17',group:'OPERATIONS',name:'Reality Lab',hint:'Applied state experiments'},{id:'18',group:'OPERATIONS',name:'Atlas Calculator',hint:'State and atlas calculations'},{id:'19',group:'OPERATIONS',name:'Infinity',hint:'Recursive bounded exploration'},{id:'20',group:'OPERATIONS',name:'Convergence',hint:'Convergence and basin analysis'},{id:'21',group:'OPERATIONS',name:'Quality Compiler',hint:'B020 semantic quality gates'},{id:'22',group:'OPERATIONS',name:'Build Out',hint:'Restore, inherit and surpass'},
{id:'23',group:'WORK',name:'Projects',hint:'Organize active OMEGA work'},{id:'24',group:'WORK',name:'Render Queue',hint:'Manage real render tasks'},{id:'25',group:'WORK',name:'Assets',hint:'Inspect available runtime assets'},
{id:'26',group:'INTELLIGENCE',name:'Modes',hint:'Mode188 and executor registry'},{id:'27',group:'INTELLIGENCE',name:'Kernel Intelligence',hint:'SAI kernel intelligence controls'},{id:'28',group:'INTELLIGENCE',name:'Evidence & Proof',hint:'Proof, ledger and evidence controls'},{id:'29',group:'INTELLIGENCE',name:'Memory',hint:'Continuity and retained working memory'},{id:'30',group:'INTELLIGENCE',name:'Archive Census',hint:'Forensic donor census'},{id:'31',group:'INTELLIGENCE',name:'Archive Operators',hint:'Keep, donor, quarantine or expand'},{id:'32',group:'INTELLIGENCE',name:'Development',hint:'Restore-and-surpass development'},{id:'33',group:'INTELLIGENCE',name:'Canon Evolution',hint:'Canonical revision governance'},{id:'34',group:'INTELLIGENCE',name:'SAI Lab',hint:'Sovereign intelligence laboratory'},
{id:'35',group:'GOVERNANCE',name:'Governance',hint:'Canonical admission and proof'},{id:'36',group:'GOVERNANCE',name:'Consolidation',hint:'One-system invariant checks'},{id:'37',group:'GOVERNANCE',name:'Instructions',hint:'Executable operating map'},
{id:'38',group:'SYSTEM',name:'Plugins',hint:'Bounded integration registry'},{id:'39',group:'SYSTEM',name:'Settings',hint:'Runtime configuration'},{id:'40',group:'SYSTEM',name:'System',hint:'Hosted runtime system state'},{id:'41',group:'SYSTEM',name:'Validation',hint:'Universal quality validation'},{id:'42',group:'SYSTEM',name:'System Atlas',hint:'24-family software atlas'},{id:'43',group:'SYSTEM',name:'Scale Compiler',hint:'Recursive-scale compiler'},{id:'44',group:'SYSTEM',name:'Control Matrix',hint:'System Atlas control matrix'}
];
const GROUPS:Group[]=['STUDIO','OPERATIONS','WORK','INTELLIGENCE','GOVERNANCE','SYSTEM'];
const icon=(g:Group)=>g==='STUDIO'?<Sparkles/>:g==='OPERATIONS'?<Waypoints/>:g==='WORK'?<Layers3/>:g==='INTELLIGENCE'?<BrainCircuit/>:g==='GOVERNANCE'?<ShieldCheck/>:<Globe2/>;
function readList(key:string){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x.filter(v=>typeof v==='string'):[]}catch{return[]}}
export default function OmegaLauncher({onNavigate}:Props){
 const[open,setOpen]=useState(false),[q,setQ]=useState(''),[favorites,setFavorites]=useState<string[]>(()=>readList('omega.v6.favorites')),[recent,setRecent]=useState<string[]>(()=>readList('omega.v6.recent'));
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?LAUNCHER_SURFACES.filter(x=>(x.name+' '+x.group+' '+x.hint+' '+x.id).toLowerCase().includes(s)):LAUNCHER_SURFACES},[q]);
 const go=(name:string)=>{const n=[name,...recent.filter(x=>x!==name)].slice(0,6);setRecent(n);localStorage.setItem('omega.v6.recent',JSON.stringify(n));localStorage.setItem('omega.v6.panel',JSON.stringify(name));setOpen(false);onNavigate(name)};
 const fav=(name:string,e:any)=>{e.stopPropagation();const n=favorites.includes(name)?favorites.filter(x=>x!==name):[...favorites,name];setFavorites(n);localStorage.setItem('omega.v6.favorites',JSON.stringify(n))};
 const activate=(name:string,e:React.KeyboardEvent<HTMLDivElement>)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go(name)}};
 return <><button className='omega-nexus-trigger' onClick={()=>setOpen(true)} aria-label='Open OMEGA application launcher'><Command/><span>NEXUS</span><small>44</small></button>{open&&<div className='omega-nexus-backdrop' role='presentation' onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className='omega-nexus' role='dialog' aria-modal='true' aria-label='OMEGA application launcher'><header><div><span>OMEGA APPLICATION NEXUS</span><h2>Go directly to a real capability.</h2><p>Every destination below is routed by the current workstation. Favorites and recents stay in this browser only.</p></div><button onClick={()=>setOpen(false)} aria-label='Close launcher'><X/></button></header><div className='omega-nexus-search'><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder='Search capability, domain, operation, or number…'/><kbd>CTRL K</kbd></div>{!q&&recent.length>0&&<div className='omega-nexus-recents'><span>RECENT</span>{recent.map(name=><button key={name} onClick={()=>go(name)}>{name}<ChevronRight/></button>)}</div>}<main>{GROUPS.map(group=>{const rows=filtered.filter(x=>x.group===group);if(!rows.length)return null;return <section className='omega-nexus-group' key={group}><header>{icon(group)}<b>{group}</b><span>{rows.length}</span></header><div>{rows.map(x=><div className='omega-nexus-card' key={x.id} role='button' tabIndex={0} onClick={()=>go(x.name)} onKeyDown={e=>activate(x.name,e)} aria-label={`Open ${x.name}`}><code>{x.id}</code><span><b>{x.name}</b><small>{x.hint}</small></span><button type='button' className={'omega-nexus-fav '+(favorites.includes(x.name)?'active':'')} onClick={e=>fav(x.name,e)} aria-label={(favorites.includes(x.name)?'Remove ':'Add ')+x.name+' favorite'}><Heart/></button><ChevronRight className='omega-nexus-arrow'/></div>)}</div></section>})}</main><footer><ShieldCheck/><span>44 routed surfaces · every launcher control is actionable · external/native capability remains evidence-gated</span><b>{filtered.length}/44</b></footer></section></div>}</>}
