import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Archive,BookOpen,BrainCircuit,Database,FileCode2,FolderKanban,Gauge,GitBranch,Globe2,Layers3,Orbit,Play,RefreshCw,Save,Settings2,ShieldCheck,Sparkles,TerminalSquare,Waypoints,Wrench} from 'lucide-react';
import OmegaCommandDeck from './OmegaCommandDeck';
import ResponsiveRuntimeShell,{LayoutModeSwitch,type OmegaUiMode} from './ResponsiveRuntimeShell';
import AtlasViewport from './AtlasViewport';
import CalculusTraversal from './CalculusTraversal';
import {corpusState,decodeAddress,evaluateCorpusModes,initCorpusPack,validateCorpusPack} from './corpusRuntime';
import {unifiedFromRecord,validateUnifiedMath} from './unifiedCalculus';
import {api,localState} from './platformAdapter';
import {RUNTIME_IDENTITY} from './runtimeIdentity';
import './responsiveShell.css';
import './commandDeck.css';

type NavName=typeof nav[number][0];
type LocalEvent={id:string;at:number;type:string;text:string;meta?:Record<string,unknown>};
type Project={id:string;name:string;description:string;at:number};
type Job={id:string;title:string;engine:string;stateAddress:number;at:number;status:string};
const nav=[['Command Center',Sparkles],['Hybrid Link',TerminalSquare],['Workspace',Gauge],['Cockpit',Gauge],['Immersive Traversal',Waypoints],['Matter Traversal',Orbit],['Extreme Traversal',Waypoints],['Visual Instrument',Orbit],['Relativity',Orbit],['Earth Now',Globe2],['Forecast',Activity],['Atlas',Orbit],['Traversal',Waypoints],['Create',Sparkles],['Field',Layers3],['Data Motion',Activity],['Reality Lab',Activity],['Atlas Calculator',Orbit],['Infinity',Orbit],['Convergence',GitBranch],['Quality Compiler',ShieldCheck],['Build Out',GitBranch],['Projects',FolderKanban],['Render Queue',Archive],['Assets',Database],['Modes',BrainCircuit],['Kernel Intelligence',BrainCircuit],['Evidence & Proof',ShieldCheck],['Memory',FileCode2],['Archive Census',Archive],['Archive Operators',Wrench],['Development',GitBranch],['Canon Evolution',GitBranch],['SAI Lab',BrainCircuit],['Governance',ShieldCheck],['Consolidation',GitBranch],['Instructions',BookOpen],['Plugins',Wrench],['Settings',Settings2],['System',TerminalSquare],['Validation',ShieldCheck],['System Atlas',Orbit],['Scale Compiler',Layers3],['Control Matrix',TerminalSquare]] as const;
const groups:{label:string;items:NavName[]}[]=[{label:'STUDIO',items:nav.slice(0,14).map(x=>x[0])},{label:'OPERATIONS',items:nav.slice(14,22).map(x=>x[0])},{label:'INTELLIGENCE',items:nav.slice(22,32).map(x=>x[0])},{label:'SYSTEM',items:nav.slice(32).map(x=>x[0])}];
const STATE_COUNT=20736,EPS=1e-12;
const fmt=(v:unknown,d=4)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):String(v??'—');
const uid=(prefix:string)=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const esc=(v:unknown)=>String(v??'');
function Pill({children,kind=''}:{children:any;kind?:string}){return <span className={'pill '+kind}>{children}</span>}
function Metric({name,value,invert=false}:{name:string;value:number;invert?:boolean}){const n=Math.max(0,Math.min(1,Number(value)||0)),bar=(invert?1-n:n)*100;return <div className='metric'><span>{name}</span><b>{fmt(value)}</b><div><i style={{width:`${bar}%`}}/></div></div>}
function Gate({name,value,note}:{name:string;value:unknown;note?:string}){return <div><span>{name}</span><b>{esc(value)}</b>{note&&<small>{note}</small>}</div>}
function SectionHead({over,title,right}:{over:string;title:string;right?:any}){return <div className='section-head'><div><p className='overline'>{over}</p><h2>{title}</h2></div>{right}</div>}
function Boundary({children}:{children:any}){return <div className='boundary'><ShieldCheck size={16}/><span>{children}</span></div>}
function MiniTrajectory({points}:{points:any[]}){if(!points.length)return null;const W=900,H=250,p=28,x=(i:number)=>p+i/Math.max(1,points.length-1)*(W-p*2),y=(v:number)=>H-p-Math.max(0,Math.min(1,v))*(H-p*2),series:[string,string,string][]=[['continuity','CΩ','#58c7ba'],['plasticity','Φ','#d0a866'],['contradiction','q','#c85b69'],['burden','Λ','#8196a8']];return <svg className='forecast-chart' viewBox={`0 0 ${W} ${H}`} role='img' aria-label='Source-routed forecast trajectory'>{[0,.25,.5,.75,1].map(v=><line key={v} x1={p} x2={W-p} y1={y(v)} y2={y(v)} stroke='rgba(255,255,255,.07)'/>)}{series.map(([k,label,color])=><g key={k}><polyline fill='none' stroke={color} strokeWidth='2' points={points.map((q,i)=>`${x(i)},${y(q.metrics[k])}`).join(' ')}/><text x={W-p} y={y(points[points.length-1].metrics[k])-4} fill={color} fontSize='10' textAnchor='end'>{label}</text></g>)}</svg>}
function PacketMetrics({record}:{record:any}){const u=unifiedFromRecord(record);return <div className='channel-grid'><Metric name='Continuity CΩ' value={record.metrics.continuity}/><Metric name='Plasticity Φ' value={record.metrics.plasticity}/><Metric name='Contradiction q' value={record.metrics.contradiction} invert/><Metric name='Burden Λ' value={record.metrics.burden} invert/><Metric name='Scar' value={record.metrics.scar} invert/><Metric name='Evidence' value={record.metrics.evidence}/><Metric name='RSC' value={record.metrics.rsc}/><Metric name='Geometry' value={record.metrics.geometry}/><Metric name='Water conductance' value={u.water.conductance}/><Metric name='Unified coherence' value={u.unifiedCoherence}/></div>}
function RuntimeTruth({status,restoration,onRefresh}:{status:any;restoration:any;onRefresh:()=>void}){return <section className='panel'><SectionHead over='SOVEREIGN AUTHORITY GRAPH' title='Runtime truth' right={<button onClick={onRefresh}><RefreshCw size={14}/> Refresh</button>}/><div className='gate-grid'><Gate name='Release authority' value={status?.canonicalAuthority?.release||'B015 R1'}/><Gate name='Cloud Worker' value={status?.cloud?.worker||'CHECKING'}/><Gate name='Restore branch' value={restoration?.branch||'full-restore'}/><Gate name='Provider' value={status?.modelProvider||'NOT_CONFIGURED'}/><Gate name='Hybrid Link' value={status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}/><Gate name='Earth feeds' value={status?.earth?.liveFeeds||'EXTERNAL_DEGRADED'}/></div><Boundary>Cloudflare is a deployment/runtime bridge. Google Drive remains release authority; native/device/provider/live-feed capabilities are never inferred from UI availability.</Boundary></section>}

export default function OmegaDashboard(){
 const[ready,setReady]=useState(false),[bootError,setBootError]=useState(''),[panel,setPanel]=useState<NavName>(()=>localState.read('omega.v6.panel','Command Center') as NavName),[address,setAddress]=useState(()=>localState.read('omega.v6.address',11498)),[prompt,setPrompt]=useState(()=>localState.read('omega.b015.chatDraft.v1','Use ALL MODES and Mode 188 to assess this state, identify the weakest edge, and give the next useful OMEGA action.')),[response,setResponse]=useState<any>(null),[busy,setBusy]=useState(''),[status,setStatus]=useState<any>(null),[restoration,setRestoration]=useState<any>(null),[menuQuery,setMenuQuery]=useState(''),[uiMode,setUiMode]=useState<OmegaUiMode>(()=>{const s=localStorage.getItem('omega-ui-mode');return s==='DESKTOP'||s==='MOBILE'?s:'AUTO'}),[modePolicy,setModePolicy]=useState<'ALL'|'CONTEXTUAL'|'CUSTOM'>(()=>localState.read('omega.v6.modePolicy','CONTEXTUAL')),[events,setEvents]=useState<LocalEvent[]>(()=>localState.read('omega.v6.events',[])),[memory,setMemory]=useState<LocalEvent[]>(()=>localState.read('omega.v6.memory',[])),[projects,setProjects]=useState<Project[]>(()=>localState.read('omega.v6.projects',[])),[jobs,setJobs]=useState<Job[]>(()=>localState.read('omega.v6.jobs',[])),[input,setInput]=useState(''),[aux,setAux]=useState(''),[systemCheck,setSystemCheck]=useState<any>(null);const mainRef=useRef<HTMLElement|null>(null),seq=useRef(0);
 useEffect(()=>{initCorpusPack().then(()=>setReady(true)).catch(e=>setBootError(e instanceof Error?e.message:String(e)))},[]);
 useEffect(()=>{localState.write('omega.v6.address',address)},[address]);useEffect(()=>{localState.write('omega.v6.panel',panel)},[panel]);useEffect(()=>{localState.write('omega.v6.modePolicy',modePolicy)},[modePolicy]);useEffect(()=>{localState.write('omega.v6.events',events)},[events]);useEffect(()=>{localState.write('omega.v6.memory',memory)},[memory]);useEffect(()=>{localState.write('omega.v6.projects',projects)},[projects]);useEffect(()=>{localState.write('omega.v6.jobs',jobs)},[jobs]);
 const loadStatus=async()=>{try{const [s,r]=await Promise.all([api.get<any>('/api/status'),api.get<any>('/api/restoration')]);setStatus(s.data);setRestoration(r.data)}catch(e:any){setStatus({error:e?.message||String(e)})}};useEffect(()=>{void loadStatus()},[]);
 const record=useMemo(()=>ready?corpusState(address):null,[ready,address]),u=useMemo(()=>record?unifiedFromRecord(record):null,[record]),modeRun=useMemo(()=>record?evaluateCorpusModes(record):null,[record]);
 const state=useMemo(()=>({modePolicy,atlas:{address},frozen:false,d:decodeAddress(address).d,p:decodeAddress(address).p,r:decodeAddress(address).r,l:decodeAddress(address).l,workflow:'LAW',preset:'SOVEREIGN',timeAuthority:'NOW'}),[modePolicy,address]);
 const navigate=(target:string)=>{setPanel(target as NavName);requestAnimationFrame(()=>mainRef.current?.focus({preventScroll:true}))};
 const commitCoords=(c:{d:number;p:number;r:number;l:number})=>setAddress(1728*c.d+144*c.p+12*c.r+c.l);
 const appendEvent=(type:string,text:string,meta?:Record<string,unknown>)=>setEvents(x=>[...x,{id:uid('evt'),at:Date.now(),type,text,meta}].slice(-250));
 const ask=async()=>{const text=prompt.trim();if(!text||busy)return;localState.write('omega.b015.chatDraft.v1',text);const token=++seq.current;setBusy('response');try{const preview=await api.post<any>('/api/route-preview',{text});const r=await api.post<any>('/api/chat',{text});if(token===seq.current){setResponse({answer:r.data?.reply||'No response returned.',responsePath:preview.data?.route,evidenceStatus:preview.data?.route==='FAST_DETERMINISTIC'?'VERIFIED_RUNTIME':'PROVIDER_BOUND',modelInvoked:preview.data?.route!=='FAST_DETERMINISTIC',modelSucceeded:r.ok,appliedModes:modePolicy==='ALL'?['ALL MODES']:['CONTEXTUAL'],uncertainty:preview.data?.route==='FAST_DETERMINISTIC'?'Bounded runtime fact route.':'Synthesis quality depends on a configured external provider.',nextAction:'Use the packet, proof state, and source route as the next bounded context.'});appendEvent('CHAT',text,{route:preview.data?.route})}}catch(e:any){if(token===seq.current)setResponse({answer:e?.message||'Request failed',responsePath:'ROUTED_MODEL',evidenceStatus:'BOUNDED_FAILURE',modelInvoked:true,modelSucceeded:false,uncertainty:'No fabricated synthesis was substituted.',nextAction:'Bind a verified provider or continue with deterministic runtime tools.'})}finally{if(token===seq.current)setBusy('')}};
 const forecast=useMemo(()=>{if(!record)return[];const out:any[]=[];let a=address;for(let i=0;i<24;i++){const q=corpusState(a);out.push(q);a=q.autoPing.dataNext}return out},[record,address]);
 const runSystemCheck=async()=>{if(!record)return;setBusy('system-check');const checks:any[]=[];try{const pack=validateCorpusPack(),math=validateUnifiedMath(record);checks.push({name:'embedded 20,736-state source pack',passed:pack.passed,detail:`${pack.stateCount} states · ${pack.modeCount} algebra modes · core R² ${pack.coreR2Min.toFixed(4)}`});checks.push({name:'unified calculus',passed:math.passed,detail:`${math.checks.filter((x:any)=>x.passed).length}/${math.checks.length} invariants`});for(const [name,url] of [['Worker health','/api/health'],['Runtime status','/api/status'],['Restore ledger','/api/restoration'],['Hybrid Link','/api/hybrid/status']]){try{const r=await api.get<any>(url);checks.push({name,passed:r.ok,detail:r.data?.state||r.data?.ok?'reachable':'returned'})}catch(e:any){checks.push({name,passed:false,detail:e.message})}}setSystemCheck({at:Date.now(),status:checks.every(x=>x.passed)?'PASS':'CHECK',checks});appendEvent('SYSTEM_CHECK',checks.every(x=>x.passed)?'PASS':'CHECK')}finally{setBusy('')}};
 if(bootError)return <div className='boot'><ShieldCheck/><b>SOURCE PACK FAILED</b><span>{bootError}</span><button className='gold' onClick={()=>location.reload()}>Reload</button></div>;
 if(!ready||!record||!u||!modeRun)return <div className='boot'><Orbit className='spin'/><b>OMEGA {RUNTIME_IDENTITY.hostedBuild}</b><span>Loading the embedded 20,736-state source runtime…</span></div>;
 const matches=(name:string)=>!menuQuery.trim()||name.toLowerCase().includes(menuQuery.trim().toLowerCase());
 const localTable=(rows:LocalEvent[])=>rows.length?<div className='table-list'>{[...rows].reverse().slice(0,60).map(x=><div key={x.id}><b>{x.type}</b><span>{x.text}</span><small>{new Date(x.at).toLocaleString()}</small></div>)}</div>:<div className='answer'><b>No entries yet.</b><p>This surface is live and ready to record browser-local continuity without silently promoting it to Drive release evidence.</p></div>;
 const packetPanel=(title:string,over:string,desc:string)=><section className='panel'><SectionHead over={over} title={title} right={<div className='pill-row'><Pill>{record.metrics.decision}</Pill><Pill>STATE {record.stateId.toLocaleString()}</Pill></div>}/><p className='muted'>{desc}</p><PacketMetrics record={record}/><div className='equation'><code>S=(CΩ·Φ)/(q+Λ+ε)</code><b>{fmt(u.commonKernel,6)}</b><span>Full Overall Canon common kernel</span></div><div className='action-row'><button onClick={()=>setAddress(record.autoPing.previous)}>Previous</button><button className='gold' onClick={()=>setAddress(record.autoPing.dataNext)}>Admitted next</button><button onClick={()=>setAddress(record.autoPing.mode188Plus)}>Mode188 +188</button><button onClick={()=>setAddress(record.autoPing.oppositeDomain)}>Opposite domain</button></div></section>;
 const renderPanel=()=>{switch(panel){
  case'Command Center':return <OmegaCommandDeck record={record} state={state} prompt={prompt} onPrompt={v=>{setPrompt(v);localState.write('omega.b015.chatDraft.v1',v)}} onRun={ask} response={response} busy={busy} onNavigate={navigate}/>;
  case'Workspace':case'Cockpit':return <><section className='panel'><SectionHead over='ONE STATE · ONE LEDGER · ONE PACKET' title={panel==='Workspace'?'Unified Workspace':'Renderer-first Cockpit'} right={<Pill kind='ok'>SOURCE BOUND</Pill>}/><div className='hero-grid'><div><CalculusTraversal state={state} onSelect={commitCoords} compact/></div><div className='state-rail'><Metric name='Continuity CΩ' value={record.metrics.continuity}/><Metric name='Plasticity Φ' value={record.metrics.plasticity}/><Metric name='Evidence' value={record.metrics.evidence}/><Metric name='Unified Rᵤ' value={u.unifiedCoherence}/><div className='address-box'><span>ATLAS ADDRESS</span><strong>{record.stateId.toLocaleString()}</strong><code>D{state.d} · P{state.p} · R{state.r} · L{state.l}</code></div></div></div></section><RuntimeTruth status={status} restoration={restoration} onRefresh={loadStatus}/></>;
  case'Immersive Traversal':case'Matter Traversal':case'Extreme Traversal':case'Visual Instrument':case'Traversal':return <section className='panel'><SectionHead over='LIVE SOURCE-BOUND MOTION' title={panel} right={<Pill>{record.identity.autoPingState}</Pill>}/><p className='muted'>This renderer is driven by the embedded source packet, unified calculus, scar carry, phase, motion relativity, geometry and evidence. Density is representational; native GPU authority is not claimed.</p><CalculusTraversal state={state} onSelect={commitCoords}/><PacketMetrics record={record}/></section>;
  case'Atlas':return <section className='panel'><SectionHead over='FULL SPHERE · DATA-DRIVEN' title='20,736-state source Atlas' right={<Pill>{record.metrics.mode188}</Pill>}/><AtlasViewport state={state} onSelect={commitCoords}/><Boundary>LATTICE, MANDALA, INVERSE and THREAD are projections of the same embedded source authority.</Boundary></section>;
  case'Field':return packetPanel('Canonical source packet','SOURCE-BOUND FIELD · READ ONLY','Every metric below is decoded from the embedded corpus model for the selected exact address; presentation controls do not rewrite source values.');
  case'Data Motion':return <><section className='panel'><SectionHead over='AUTO-PING · CARRY · PHASE' title='Data Motion' right={<Pill>{record.autoPing.dataNext+1}</Pill>}/><AtlasViewport state={state} onSelect={commitCoords}/></section>{packetPanel('Transport variables','DEWEY / WATER / RSC','Source routing binds predictive continuity, burden, contradiction, recoverability, PSC topology and motion relativity.')}</>;
  case'Relativity':{const next=corpusState(record.autoPing.dataNext),dv=next.math.normalizedMotionRelativity-record.math.normalizedMotionRelativity;return <section className='panel'><SectionHead over='OBSERVER · MOTION · FRAME' title='Relativity Lab' right={<Pill>ΔMRI {fmt(dv,6)}</Pill>}/><div className='gate-grid'><Gate name='Normalized MRI' value={fmt(record.math.normalizedMotionRelativity,6)}/><Gate name='Next MRI' value={fmt(next.math.normalizedMotionRelativity,6)}/><Gate name='Δ relative motion' value={fmt(dv,6)}/><Gate name='Geometry symmetry' value={fmt(record.geometry.symmetry,6)}/><Gate name='Phase' value={fmt(u.phase,6)}/><Gate name='Orientation' value={u.orientation}/></div><CalculusTraversal state={state} onSelect={commitCoords} compact/><Boundary>Relativity values here are source-model runtime quantities, not claims that 20,736 is a physical dimension.</Boundary></section>}
  case'Forecast':return <section className='panel'><SectionHead over='SOURCE ROUTE · 24-STEP CORRIDOR' title='Forecast Workspace' right={<Pill>UNCERTAINTY VISIBLE</Pill>}/><MiniTrajectory points={forecast}/><div className='table-list'>{forecast.slice(0,12).map((q:any,i)=><div key={i}><b>t+{i} · state {q.stateId}</b><span>{q.metrics.decision}</span><small>CΩ {fmt(q.metrics.continuity,3)} · Φ {fmt(q.metrics.plasticity,3)} · q {fmt(q.metrics.contradiction,3)} · Λ {fmt(q.metrics.burden,3)}</small></div>)}</div><Boundary>This is an endogenous route forecast through the source runtime. It is not asserted as a measured external future.</Boundary></section>;
  case'Earth Now':return <section className='panel'><SectionHead over='EARTH VIEW · SOURCE HONESTY' title='Earth Now' right={<Pill>{status?.earth?.liveFeeds||'EXTERNAL_DEGRADED'}</Pill>}/><div className='earth-stage'><div className='earth-orb'><i/><i/><b>EARTH</b></div></div><div className='gate-grid'><Gate name='Runtime layer' value='LIVE'/><Gate name='External imagery' value='EXTERNAL_DEGRADED'/><Gate name='Temporal authority' value='UNBOUND'/><Gate name='Forecast overlay' value='SOURCE-RUNTIME AVAILABLE'/></div><Boundary>No satellite, weather, conflict, or geophysical observation is labeled current until a verified external source is bound.</Boundary></section>;
  case'Hybrid Link':return <section className='panel'><SectionHead over='PHONE + PC · MISSION CONTROL' title='Hybrid Link' right={<Pill>{status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}</Pill>}/><div className='system-grid'><article className='system-card'><b>Cloud controller</b><p>Public Worker, route gate, planning surface and proof envelope are live.</p></article><article className='system-card'><b>Windows host</b><p>No native heartbeat is inferred. Pairing remains DEVICE_PROOF_REQUIRED.</p></article><article className='system-card'><b>Phone session</b><p>This browser can prepare missions and inspect state without impersonating native authority.</p></article></div><div className='flow-line'>PLAN → GATE → HEARTBEAT → EXECUTE LOCALLY → PROOF RETURN → LEDGER</div><Boundary>Hybrid Link is a first-class control path, not a repair mode. Native screen/control actions remain blocked until an actual host heartbeat exists.</Boundary></section>;
  case'Modes':return <section className='panel'><SectionHead over='179 SOURCE ALGEBRA MODES' title='Executable Mode Registry' right={<div className='mode-policy'><button className={modePolicy==='ALL'?'active':''} onClick={()=>setModePolicy('ALL')}>ALL</button><button className={modePolicy==='CONTEXTUAL'?'active':''} onClick={()=>setModePolicy('CONTEXTUAL')}>CONTEXTUAL</button><button className={modePolicy==='CUSTOM'?'active':''} onClick={()=>setModePolicy('CUSTOM')}>CUSTOM</button></div>}/><div className='corpus-mode-summary'><div><span>EXECUTED</span><b>{modeRun.count}</b></div><div><span>STAY</span><b>{modeRun.stay}</b></div><div><span>TURN</span><b>{modeRun.turn}</b></div><div><span>ESCALATE</span><b>{modeRun.escalate}</b></div><div><span>WEAKEST</span><b>{fmt(modeRun.weakest.score)}</b></div><div><span>STRONGEST</span><b>{fmt(modeRun.strongest.score)}</b></div></div><div className='corpus-mode-list'>{modeRun.results.map((x:any)=><div className='corpus-mode-row' key={x.id}><b>{x.name}<br/><span>{x.category}</span></b><span>{x.gate}</span><strong>{fmt(x.score)}</strong></div>)}</div></section>;
  case'Evidence & Proof':return <section className='panel'><SectionHead over='LOCAL PROOF · CANONICAL BOUNDARY' title='Evidence & Proof' right={<Pill>{events.length} EVENTS</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Observed evidence / proof note'/><button className='gold' onClick={()=>{if(!input.trim())return;appendEvent('EVIDENCE',input.trim(),{state:record.stateId,decision:record.metrics.decision});setInput('')}}><Save size={14}/> Record local proof</button></div>{localTable(events)}<Boundary>Browser-local proof is useful continuity but is not automatically promoted to the Drive release ledger.</Boundary></section>;
  case'Memory':return <section className='panel'><SectionHead over='SCAR · CARRY · CONTINUITY' title='Memory' right={<Pill>{memory.length} NOTES</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Continuity / scar note'/><button className='gold' onClick={()=>{if(!input.trim())return;setMemory(x=>[...x,{id:uid('mem'),at:Date.now(),type:'SCAR_CARRY',text:input.trim(),meta:{state:record.stateId}}].slice(-250));setInput('')}}>Carry forward</button></div>{localTable(memory)}<Boundary>Memory survives reloads locally and stays distinct from release authority.</Boundary></section>;
  case'Projects':return <section className='panel'><SectionHead over='PERSISTENT LOCAL WORK' title='Projects' right={<Pill>{projects.length}</Pill>}/><div className='form-grid'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Project name'/><input value={aux} onChange={e=>setAux(e.target.value)} placeholder='Description'/></div><button className='gold' onClick={()=>{if(!input.trim())return;setProjects(x=>[...x,{id:uid('prj'),name:input.trim(),description:aux.trim(),at:Date.now()}]);setInput('');setAux('')}}>Create project</button><div className='table-list'>{projects.map(x=><div key={x.id}><b>{x.name}</b><span>{x.description||'No description'}</span><small>{new Date(x.at).toLocaleString()}</small></div>)}</div></section>;
  case'Render Queue':case'Render Queue' as any:return null;
  case'Render Queue':return null;
  case'Render Queue' as NavName:return null;
  case'Render Queue' as any:return null;
  case'Render Queue':return null;
  case'Render Queue' as never:return null;
  default:break}
  if(panel==='Render Queue')return <section className='panel'><SectionHead over='ONE QUEUE · MULTIPLE CONSUMERS' title='Render / Handoff Queue' right={<Pill>{jobs.length} JOBS</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Job title'/><select value={aux||'HOSTED_REFERENCE_PACKET'} onChange={e=>setAux(e.target.value)}><option>HOSTED_REFERENCE_PACKET</option><option>TARGET_GPU</option><option>CYCLES</option><option>HYBRID_LINK</option></select><button className='gold' onClick={()=>{if(!input.trim())return;setJobs(x=>[...x,{id:uid('job'),title:input.trim(),engine:aux||'HOSTED_REFERENCE_PACKET',stateAddress:record.address,at:Date.now(),status:(aux==='TARGET_GPU'||aux==='CYCLES'||aux==='HYBRID_LINK')?'DEVICE_PROOF_REQUIRED':'READY'}]);setInput('')}}>Queue</button></div><div className='table-list'>{jobs.map(x=><div key={x.id}><b>{x.title}</b><span>{x.engine} · {x.status}</span><small>state {x.stateAddress+1} · {new Date(x.at).toLocaleString()}</small></div>)}</div></section>;
  if(panel==='Validation')return <section className='panel'><SectionHead over='STRICT SOFTWARE PROOF' title='Validation' right={<button className='gold' onClick={runSystemCheck} disabled={!!busy}><ShieldCheck size={14}/>{busy?' Checking…':' Run validation'}</button>}/>{systemCheck?<><div className='gate-grid'>{systemCheck.checks.map((x:any)=><Gate key={x.name} name={x.name} value={x.passed?'PASS':'CHECK'} note={x.detail}/>)}</div><Boundary>Integrated result: {systemCheck.status}. External/native gates remain separate from source/software validation.</Boundary></>:<div className='answer'>Run validation to check the embedded source corpus, unified calculus, Worker endpoints and Hybrid Link truth state.</div>}</section>;
  if(panel==='System')return <><RuntimeTruth status={status} restoration={restoration} onRefresh={loadStatus}/>{systemCheck&&<section className='panel'><SectionHead over='LATEST INTEGRATED CHECK' title={systemCheck.status}/><div className='gate-grid'>{systemCheck.checks.map((x:any)=><Gate key={x.name} name={x.name} value={x.passed?'PASS':'CHECK'} note={x.detail}/>)}</div></section>}</>;
  if(panel==='Control Matrix')return <section className='panel'><SectionHead over='44 ROUTES · ONE AUTHORITY' title='Control Matrix' right={<Pill>44/44 REGISTERED</Pill>}/><div className='contract-grid'>{nav.map(([name,Icon])=><article key={name}><Icon size={16}/><b>{name}</b><span>{['Immersive Traversal','Matter Traversal','Extreme Traversal','Visual Instrument','Traversal','Atlas'].includes(name)?'SOURCE RENDERER':['Hybrid Link'].includes(name)?'DEVICE-GATED':['Earth Now'].includes(name)?'EXTERNAL-GATED':'PACKET / CLOUD'}</span><small>Bound to the same current packet or an explicit truth gate.</small><button onClick={()=>navigate(name)}>Open</button></article>)}</div></section>;
  if(panel==='Create'||panel==='SAI Lab'||panel==='Development'||panel==='Build Out')return <><OmegaCommandDeck record={record} state={state} prompt={prompt} onPrompt={setPrompt} onRun={ask} response={response} busy={busy} onNavigate={navigate}/><section className='panel'><SectionHead over='BOUNDED DEVELOPMENT' title={panel}/><div className='flow-line'>SENSE → NORMALIZE → SCORE → GATE → ACT → LEDGER</div><PacketMetrics record={record}/><Boundary>Generation and software plans remain provider-bound. Deterministic packet analysis remains available without fabricating model output.</Boundary></section></>;
  if(panel==='Reality Lab'||panel==='Atlas Calculator'||panel==='Infinity'||panel==='Convergence'||panel==='Quality Compiler'||panel==='Kernel Intelligence'||panel==='Canon Evolution'||panel==='Governance'||panel==='Consolidation'||panel==='System Atlas'||panel==='Scale Compiler')return <><section className='panel'><SectionHead over='EXECUTABLE SOURCE INSTRUMENT' title={panel} right={<Pill>{record.metrics.decision}</Pill>}/><CalculusTraversal state={state} onSelect={commitCoords} compact/><PacketMetrics record={record}/><div className='gate-grid'><Gate name='Common kernel' value={fmt(u.commonKernel,6)}/><Gate name='Reference v3' value={fmt(u.referenceV3,6)}/><Gate name='Unified coherence' value={fmt(u.unifiedCoherence,6)}/><Gate name='Auto-Ping next' value={record.autoPing.dataNext+1}/><Gate name='Mode188 next' value={record.autoPing.mode188Plus+1}/><Gate name='Weakest algebra mode' value={modeRun.weakest.name} note={`${modeRun.weakest.gate} · ${fmt(modeRun.weakest.score)}`}/></div></section><Boundary>{panel} uses the same source packet/calculus rather than a disconnected decorative placeholder. Specialized donor UI can continue to replace this shared instrument without changing authority.</Boundary></>;
  if(panel==='Archive Census'||panel==='Archive Operators'||panel==='Assets'||panel==='Plugins')return <section className='panel'><SectionHead over='DONOR / CAPABILITY INVENTORY' title={panel} right={<Pill>BOUNDED</Pill>}/><div className='system-grid'><article className='system-card'><b>Embedded corpus</b><p>20,736 source addresses and 179 algebra modes loaded in-browser.</p></article><article className='system-card'><b>Cloud Worker</b><p>Health, routing, restoration and truth-state APIs available.</p></article><article className='system-card'><b>Drive authority</b><p>B015 R1 release pointer remains external canonical authority.</p></article><article className='system-card'><b>Native targets</b><p>Qt/OpenGL/CUDA/Cycles remain device-gated consumers, not simulated cloud capabilities.</p></article></div><Boundary>No unseen archive or device donor is promoted from a filename alone.</Boundary></section>;
  if(panel==='Settings')return <section className='panel'><SectionHead over='WORKSTATION PREFERENCES' title='Settings'/><div className='settings-grid'><label>UI mode <LayoutModeSwitch value={uiMode} onChange={setUiMode}/></label><label>Mode policy<select value={modePolicy} onChange={e=>setModePolicy(e.target.value as any)}><option>CONTEXTUAL</option><option>ALL</option><option>CUSTOM</option></select></label><label>Address<input type='number' min='1' max='20736' value={address+1} onChange={e=>setAddress(Math.max(0,Math.min(20735,Number(e.target.value)-1)))}/></label></div><Boundary>Preferences affect presentation/routing policy only; they do not rewrite the embedded source corpus.</Boundary></section>;
  if(panel==='Instructions')return <section className='panel'><SectionHead over='HOW TO USE OMEGA' title='Instructions'/><div className='table-list'><div><b>1 · Ask naturally</b><p>Command Center routes verified runtime facts deterministically and sends synthesis only to a configured provider.</p></div><div><b>2 · Traverse the source</b><p>Atlas and traversal instruments move through exact source addresses. Commit a state to make it the shared workstation packet.</p></div><div><b>3 · Inspect proof</b><p>Evidence, validation, status, and truth gates remain visible. No provider/native/external gap is hidden.</p></div><div><b>4 · Use Hybrid Link</b><p>Prepare device missions here; native execution remains locked until an actual heartbeat/proof channel is connected.</p></div></div></section>;
  return packetPanel(panel,'SOURCE-BOUND WORKSTATION','This registered surface is operating against the shared source packet.');};
 return <div className={'studio layout-'+uiMode.toLowerCase()}><div className='menu-bar'><div className='wordmark'><Orbit size={18}/><b>OMEGA</b><span>{RUNTIME_IDENTITY.hostedBuild} · {RUNTIME_IDENTITY.runtimeContract} · SOVEREIGN CLOUD</span></div><button onClick={()=>navigate('Projects')}>File</button><button onClick={()=>navigate('Field')}>Edit</button><button onClick={()=>navigate('Matter Traversal')}>View</button><button onClick={()=>navigate('Control Matrix')}>Menus</button><button onClick={()=>navigate('Modes')}>Modes</button><button onClick={()=>navigate('Render Queue')}>Render</button><button onClick={()=>navigate('System')}>Tools</button><button onClick={()=>navigate('Instructions')}>Help</button><LayoutModeSwitch value={uiMode} onChange={setUiMode}/><div className='menu-spacer'/><Pill>{status?.cloud?.worker||'CLOUD'}</Pill><Pill>{record.metrics.decision}</Pill><Pill>S {fmt(record.metrics.stability,3)}</Pill></div><div className='tool-bar'><button className='gold' onClick={()=>navigate('Command Center')}><Sparkles size={15}/> AI Command</button><button onClick={()=>navigate('Workspace')}><Gauge size={15}/> Workspace</button><button onClick={()=>navigate('Immersive Traversal')}><Waypoints size={15}/> Live Immersive</button><button onClick={()=>navigate('Matter Traversal')}><Orbit size={15}/> Matter</button><button onClick={()=>navigate('Relativity')}><Orbit size={15}/> Relativity</button><button onClick={()=>navigate('Earth Now')}><Globe2 size={15}/> Earth</button><button onClick={()=>navigate('Hybrid Link')}><GitBranch size={15}/> Hybrid Link</button><button onClick={runSystemCheck}><ShieldCheck size={15}/> System Check</button></div><ResponsiveRuntimeShell uiMode={uiMode} onUiMode={setUiMode} panel={panel} onNavigate={navigate} record={record} modePolicy={modePolicy} modeCount={modeRun.count} busy={busy}/><aside><div className='menu-search'><label htmlFor='omega-menu-search'>FIND ANY OF 44 MENUS</label><input id='omega-menu-search' value={menuQuery} onChange={e=>setMenuQuery(e.target.value)} placeholder='Search Matter, Forecast, System…'/></div>{groups.map(g=><div className='aside-section' key={g.label}><small>{g.label}</small>{g.items.filter(matches).map(name=>{const Icon=nav.find(x=>x[0]===name)![1];return <button key={name} className={panel===name?'active':''} onClick={()=>navigate(name)}><Icon size={16}/>{name}</button>})}</div>)}</aside><main ref={mainRef} tabIndex={-1}>{renderPanel()}</main><footer><span>{busy?`BUSY · ${busy}`:'READY'}</span><span>DRIVE B015 R1 AUTHORITY</span><span>CSV {record.stateId.toLocaleString()}/20,736</span><span>{modePolicy} · {modeRun.count} MODES</span><span>HYBRID {status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}</span></footer></div>
}
