import {useEffect,useMemo,useState} from 'react';
import {Activity,Archive,BrainCircuit,Cloud,Database,Earth,GitBranch,HardDrive,Layers3,Lightbulb,Play,RefreshCw,Route,ShieldCheck,Sparkles,Target,Workflow} from 'lucide-react';
import {CANON_AUTHORITY_STACK} from './allModesAuthority';
import {compileOmegaMaximumR126,R126_MANIFEST,R126_PROJECTIONS,R126_SYSTEM_FAMILIES,type R126ScalePolicy,type R126Scope} from './omegaMaximumRuntimeR126';
import './omegaMaximumCockpitR126.css';

type Props={record?:any;state?:any;address?:number;onAddress?:(n:number)=>void;onNavigate?:(p:string)=>void};
type ScopeType='BODY'|'ORGAN'|'BRANCH'|'CELL';
type NetState={autonomic?:any;organism?:any;swarm?:any;convergence?:any;hybrid?:any;federation?:any;accuracy?:any;selfBuild?:any};
const SCALE:R126ScalePolicy[]=['AUTO','SOLO','FLOCK','TREE','PIPELINE','CONSENSUS','MIRROR','FULL'];
const SCOPES:ScopeType[]=['BODY','ORGAN','BRANCH','CELL'];
const ROLES=['ORCHESTRATION','SOFTWARE','RESEARCH','MATHEMATICS','PHYSICS','VISUAL','DATA','FORECAST','TOOLS','SOVEREIGN','PROOF','COORDINATION'];
const safe=async(path:string,init?:RequestInit)=>{try{const r=await fetch(path,{cache:'no-store',...init,headers:{'cache-control':'no-cache',...(init?.body?{'content-type':'application/json'}:{}),...(init?.headers||{})}});const data=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data}}catch(error:any){return{ok:false,status:0,data:null,error:error?.message||String(error)}}};
const tag=(v:any)=>String(v??'UNPROVEN').toUpperCase();
const pct=(v:any)=>`${Math.round(Math.max(0,Math.min(1,Number(v)||0))*100)}%`;

export default function OmegaMaximumCockpitR126({record,state,address=0,onAddress,onNavigate}:Props){
 const[intent,setIntent]=useState('Use the complete OMEGA system: preserve all source-backed modes and canon lenses, route through the strongest lawful capabilities, execute only what current evidence and runtime availability support, retain scar and lineage, compare independent results, and return a proof-bounded answer without inventing observations.');
 const[scale,setScale]=useState<R126ScalePolicy>('AUTO'),[scope,setScope]=useState<ScopeType>('BODY'),[domain,setDomain]=useState(1),[phase,setPhase]=useState(0),[regulation,setRegulation]=useState(0),[allModes,setAllModes]=useState(true),[providerBudget,setProviderBudget]=useState(8),[allowFullAuto,setAllowFullAuto]=useState(false),[evidenceText,setEvidenceText]=useState(''),[canonSearch,setCanonSearch]=useState('');
 const[net,setNet]=useState<NetState>({}),[backendPlan,setBackendPlan]=useState<any>(null),[mission,setMission]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Loading live proof surfaces…');
 const metrics=record?.metrics??state?.metrics??{continuity:.7,plasticity:.6,contradiction:.25,burden:.3,evidence:.5,uncertainty:.5,scar:.2};
 const evidence=useMemo(()=>evidenceText.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,32).map((summary,i)=>({id:`operator-${i+1}`,summary,source:'operator',authority:'OPERATOR_SUPPLIED_NOT_INDEPENDENTLY_VERIFIED'})),[evidenceText]);
 const scopePacket:R126Scope=useMemo(()=>({type:scope,domain,phase,regulation}),[scope,domain,phase,regulation]);
 const compiled=useMemo(()=>compileOmegaMaximumR126({intent,record,width:typeof window==='undefined'?1280:window.innerWidth,nativePc:Boolean(net.hybrid?.nativeExecutionClaimed===true&&Array.isArray(net.hybrid?.devices)&&net.hybrid.devices.some((d:any)=>d?.online&&!d?.revoked)),metrics,modePolicy:allModes?'ALL':'RELEVANT',scalePolicy:scale,requestedCells:scale==='FULL'?1728:undefined,allowFullAuto,scope:scopePacket,providerBudget,evidence}),[intent,record,metrics,allModes,scale,allowFullAuto,scopePacket,providerBudget,evidence,net.hybrid]);
 const filteredCanon=useMemo(()=>CANON_AUTHORITY_STACK.filter(x=>!canonSearch.trim()||x.name.toLowerCase().includes(canonSearch.toLowerCase())).slice(0,62),[canonSearch]);
 const pcOnline=Boolean(net.hybrid?.nativeExecutionClaimed===true&&Array.isArray(net.hybrid?.devices)&&net.hybrid.devices.some((d:any)=>d?.online&&!d?.revoked));
 const load=async()=>{setMessage('Refreshing live proof surfaces…');const [autonomic,organism,swarm,convergence,hybrid,federation,accuracy,selfBuild]=await Promise.all([
  safe('/api/swarm/autonomic/status'),safe('/api/swarm/organism/status'),safe('/api/swarm/status'),safe('/api/system/convergence'),safe('/api/hybrid/status'),safe('/api/federation/run/status'),safe('/omega-r125-accuracy-state.json'),safe('/omega-r124-selfbuild-state.json')
 ]);setNet({autonomic:autonomic.data,organism:organism.data,swarm:swarm.data,convergence:convergence.data,hybrid:hybrid.data,federation:federation.data,accuracy:accuracy.data,selfBuild:selfBuild.data});setMessage('Live surfaces refreshed. Unavailable endpoints remain explicitly unproven.');};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!mission?.id||!['QUEUED','RUNNING','PAUSED'].includes(mission.status))return;const id=window.setInterval(async()=>{const r=await safe(`/api/swarm/autonomic/missions/${mission.id}`);if(r.data?.mission)setMission(r.data.mission)},1500);return()=>window.clearInterval(id)},[mission?.id,mission?.status]);
 const backendPayload=()=>({intent,mode:scale,scope:scopePacket,providerBudget,metrics,reconvergeWithAI:providerBudget>0,allowFullAuto,evidence});
 const preview=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Compiling local all-mode plan and requesting bounded runtime route…');const r=await safe('/api/swarm/autonomic/plan',{method:'POST',body:JSON.stringify(backendPayload())});setBackendPlan(r.data?.plan??null);setMessage(r.ok?'Runtime route preview returned. No execution or CanonState admission occurred.':`Local R126 plan is valid; runtime preview unavailable (${r.status||'network'}).`);setBusy(false)};
 const execute=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Submitting proof-bounded autonomic mission…');const r=await safe('/api/swarm/autonomic/missions',{method:'POST',body:JSON.stringify(backendPayload())});if(r.data?.mission)setMission(r.data.mission);if(r.data?.plan)setBackendPlan(r.data.plan);setMessage(r.ok?'Mission queued through the autonomic execution fabric. CanonState remains unchanged until normal proof/admission.':`Execution route not accepted (${r.status||'network'}). No execution is claimed.`);setBusy(false)};
 const setAddress=(n:number)=>{const a=Math.max(0,Math.min(20735,Math.floor(n)));onAddress?.(a)};
 const executionPlan=backendPlan??compiled.execution;
 const subsystemRows=[
  ['CANON','OMEGAv6',tag(net.convergence?.canonical?.state),ShieldCheck],['AUTONOMIC','R126 scope router',net.autonomic?tag(net.autonomic?.state||'READY'):'UNPROVEN',Route],['ORGANISM','R123 hierarchy',net.organism?tag(net.organism?.state||'READY'):'UNPROVEN',GitBranch],['DIRECT SWARM','R121 cells',net.swarm?tag(net.swarm?.state||'READY'):'UNPROVEN',BrainCircuit],
  ['SOVEREIGN','Authenticated PC',pcOnline?'LIVE':'UNPROVEN',HardDrive],['GENESIS','Proposal machine',tag(net.convergence?.proposal?.effectiveState||net.federation?.nodes?.genesis?.state),Sparkles],['OPTICAL','Screening / solver path',tag(net.convergence?.optical?.effectiveScreenState||net.federation?.nodes?.optical?.state),Lightbulb],['FEDERATION','Typed handoff',net.federation?tag(net.federation?.ok===false?'DEGRADED':'READY'):'UNPROVEN',Cloud],
  ['ACCURACY','R125 residual engine',tag(net.accuracy?.mode||'UNPROVEN'),Target],['SELF BUILD','R124 governed loop',tag(net.selfBuild?.active===true?'LIVE':net.selfBuild?.generation!==undefined?'READY':'UNPROVEN'),Workflow],['EARTH','Evidence-bound projection',tag(net.convergence?.earth?.state||'READY'),Earth],['ARCHIVE','Donor memory / lineage','READY',Archive]
 ] as const;
 return <section className='r126-max' aria-label='OMEGA R126 total maximum cockpit'>
  <header className='r126-hero'><div><span>R126 · TOTAL MAXIMUM BUILD</span><h2>One runtime. All preserved modes. Every proven subsystem.</h2><p>The maximum surface compiles source-backed calculus, canon lenses, 12 projections, adaptive 1→12→144→1,728 execution, proof, federation, sovereign compute, optical screening, archive memory, residual repair and governed self-build into one operator path. Catalog membership never masquerades as execution or measurement.</p></div><div className='r126-seal'><Layers3/><b>{R126_MANIFEST.runtime}</b><small>{compiled.decision} · {compiled.projection} · {compiled.deviceTier}</small></div></header>

  <section className='r126-numbers'><article><span>SOURCE MODE CATALOG</span><b>{compiled.modeContract.source.catalogCount}</b><small>{compiled.modeContract.source.hostedEvaluationContracts} hosted contracts · input gated</small></article><article><span>CANON LENSES</span><b>{compiled.modeContract.canon.available}</b><small>{compiled.modeContract.canon.selected} selected now</small></article><article><span>RESIDENT STATES</span><b>20,736</b><small>12⁴ address-resolution lattice</small></article><article><span>REPRESENTATION</span><b>248,832</b><small>12 × 20,736 scale atlas</small></article><article><span>VIRTUAL ADDRESSING</span><b>61,917,364,224</b><small>computational capacity · not physical dimensions</small></article></section>

  <section className='r126-projection-row'>{R126_PROJECTIONS.map(x=><button key={x} data-active={compiled.projection===x?'true':'false'} onClick={()=>setIntent(v=>`${v}\nPreferred projection: ${x}.`)}>{x}</button>)}</section>

  <section className='r126-body'><section className='r126-compose'><header><div><span>MASTER MISSION COMPILER</span><b>ALL MODES → ROUTE → EXECUTE → PROVE</b></div><button onClick={()=>void load()}><RefreshCw/>REFRESH PROOF</button></header><label className='r126-intent'><span>OBJECTIVE</span><textarea value={intent} onChange={e=>setIntent(e.target.value)}/></label><div className='r126-controls'><label><span>SCALE</span><select value={scale} onChange={e=>setScale(e.target.value as R126ScalePolicy)}>{SCALE.map(x=><option key={x}>{x}</option>)}</select></label><label><span>SCOPE</span><select value={scope} onChange={e=>setScope(e.target.value as ScopeType)}>{SCOPES.map(x=><option key={x}>{x}</option>)}</select></label>{scope!=='BODY'&&<label><span>ORGAN</span><select value={domain} onChange={e=>setDomain(Number(e.target.value))}>{ROLES.map((x,i)=><option key={x} value={i}>{String(i+1).padStart(2,'0')} · {x}</option>)}</select></label>}{(scope==='BRANCH'||scope==='CELL')&&<label><span>PHASE</span><input type='number' min='0' max='11' value={phase} onChange={e=>setPhase(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}{scope==='CELL'&&<label><span>REGULATION</span><input type='number' min='0' max='11' value={regulation} onChange={e=>setRegulation(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}<label><span>AI BUDGET · 0–12</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label></div><div className='r126-switches'><label><input type='checkbox' checked={allModes} onChange={e=>setAllModes(e.target.checked)}/><span>ALL MODES AVAILABLE</span><small>All 179 catalog authorities + 62 canon lenses may inform lawful routing; this does not call 241 models.</small></label><label><input type='checkbox' checked={allowFullAuto} onChange={e=>setAllowFullAuto(e.target.checked)}/><span>ALLOW FULL AUTO 1,728</span><small>Explicit opt-in only. FULL operator mode remains available regardless.</small></label></div><label className='r126-evidence'><span>EVIDENCE / CONTEXT · ONE PACKET PER LINE</span><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} placeholder='Optional context. Operator-supplied text stays labeled unverified until proof-backed.'/><small>{evidence.length}/32 packets</small></label><div className='r126-actions'><button onClick={()=>void preview()} disabled={busy||!intent.trim()}><Target/>PREVIEW COMPLETE ROUTE</button><button className='prime' onClick={()=>void execute()} disabled={busy||!intent.trim()}><Play/>EXECUTE PROOF-BOUND ROUTE</button></div><p className='r126-message'>{message}</p></section>

  <aside className='r126-plan'><header><span>COMPILED PLAN</span><b>{compiled.projection} · {compiled.decision}</b></header><div className='r126-plan-grid'><article><span>EXECUTION SCOPE</span><b>{compiled.execution.scope.type}</b><small>{executionPlan?.totalCells??executionPlan?.cells??compiled.execution.cells} cells selected</small></article><article><span>MODE POLICY</span><b>{compiled.modeContract.source.policy}</b><small>{compiled.modeContract.canon.selected} canon lenses · {compiled.modeContract.source.catalogCount} source catalog</small></article><article><span>MODEL CEILING</span><b>{compiled.execution.providerBudget.total}</b><small>{compiled.execution.providerBudget.cells} cells + {compiled.execution.providerBudget.reconvergence} reconvergence</small></article><article><span>ACCURACY TARGET</span><b>{pct(compiled.accuracyTarget)}</b><small>target, not a claimed measured score</small></article></div><div className='r126-stage-list'>{compiled.execution.stages.map((x:string,i:number)=><div key={x}><i>{String(i+1).padStart(2,'0')}</i><span>{x}</span><small>{x==='ADMIT'?'OMEGAv6 only':x==='EXECUTE'?'Sovereign/swarm when proven':x==='SCREEN'?'Optical/federation when available':'proof-bounded stage'}</small></div>)}</div>{mission&&<div className='r126-live-mission'><span>LIVE MISSION RECEIPT</span><b>{mission.id}</b><strong>{mission.status}</strong><small>{mission.completedCells||0}/{mission.totalCells||0} cells · {mission.proofState||'proof pending'}</small></div>}</aside></section>

  <section className='r126-subsystems'><header><div><span>REAL SUBSYSTEM MESH</span><b>Availability is observed separately from capability design.</b></div></header><div className='r126-system-grid'>{subsystemRows.map(([name,detail,status,Icon])=><article key={name} data-state={status}><Icon/><div><span>{name}</span><b>{status}</b><small>{detail}</small></div></article>)}</div></section>

  <section className='r126-modes'><header><div><span>CANON / CALCULUS LENS STACK</span><b>62 higher-order lenses over the same canonical packet</b></div><label><span>FILTER</span><input value={canonSearch} onChange={e=>setCanonSearch(e.target.value)} placeholder='Mode 188, truth, relativity…'/></label></header><div className='r126-mode-grid'>{filteredCanon.map(x=><article key={x.id}><span>{String(x.id).padStart(2,'0')} · {x.group}</span><b>{x.name}</b><small>{x.classification}</small></article>)}</div></section>

  <section className='r126-family'><header><span>24 SYSTEM FAMILIES</span><b>Full software-universe coverage</b></header><div>{R126_SYSTEM_FAMILIES.map(x=><span key={x}>{x.replaceAll('_',' ')}</span>)}</div></section>

  <section className='r126-address'><Database/><div><span>CANONICAL ADDRESS</span><b>{Math.max(0,Math.min(20735,Number(address)||0)).toLocaleString()} / 20,735</b><small>Changing observer address changes the selected packet, not the existence of canonical state.</small></div><input type='range' min='0' max='20735' value={Math.max(0,Math.min(20735,Number(address)||0))} onChange={e=>setAddress(Number(e.target.value))}/>{onNavigate&&<button onClick={()=>onNavigate('Atlas')}>OPEN ATLAS</button>}</section>

  <footer className='r126-boundary'><ShieldCheck/><div><b>R126 TRUTH / AUTHORITY BOUNDARY</b><span>{compiled.truthBoundary}</span></div></footer>
 </section>
}
