import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronDown,ChevronUp,Pause,Play,RotateCcw,ShieldCheck,StepBack,StepForward} from 'lucide-react';
import MatterTraversal from './MatterTraversal';
import OmegaVisualInstrument from './OmegaVisualInstrument';
import OmegaTraversalStudio from './OmegaTraversalStudio';
import OmegaMotionSkinMapR35 from './OmegaMotionSkinMapR35';
import OmegaLivingField from './OmegaLivingField';
import {corpusState,decodeAddress} from './corpusRuntime';
import './livingSurfaceR36.css';

type Common={address:number;onAddress:(n:number)=>void;state:any};
const clamp=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0)));
const fmt=(n:any,d=3)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
function nextOf(a:number){return clamp(corpusState(clamp(a)).autoPing?.dataNext??a)}
function prevOf(a:number){return clamp(corpusState(clamp(a)).autoPing?.previous??a)}

function useActualTraversal(address:number,onAddress:(n:number)=>void){
 const [running,setRunning]=useState(false),[rate,setRate]=useState(900),[ticks,setTicks]=useState(0);
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>{onAddress(nextOf(address));setTicks(x=>x+1)},rate);return()=>window.clearInterval(id)},[running,rate,address,onAddress]);
 return{running,setRunning,rate,setRate,ticks,reset:()=>{setRunning(false);setTicks(0)}};
}

function StateVolume({address,kind}:{address:number;kind:'MATTER'|'TRAVERSAL'}){
 const canvas=useRef<HTMLCanvasElement|null>(null),record=useMemo(()=>corpusState(address),[address]),coords=useMemo(()=>decodeAddress(address),[address]);
 useEffect(()=>{const c=canvas.current;if(!c)return;let raf=0,alive=true;const ctx=c.getContext('2d');if(!ctx)return;const draw=(now:number)=>{if(!alive)return;const box=c.getBoundingClientRect(),dpr=Math.min(1.7,window.devicePixelRatio||1),W=Math.max(420,Math.round(box.width)),H=Math.max(430,Math.round(box.height));if(c.width!==Math.round(W*dpr)||c.height!==Math.round(H*dpr)){c.width=Math.round(W*dpr);c.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#02070a';ctx.fillRect(0,0,W,H);const cx=W*.5,cy=H*.52,t=now*.00018,C=record.metrics.continuity,P=record.metrics.plasticity,q=record.metrics.contradiction,L=record.metrics.burden,E=record.metrics.evidence,scar=record.metrics.scar||0;const layers=kind==='MATTER'?9:12;for(let shell=layers; shell>=1; shell--){const shellR=Math.min(W,H)*(.075+shell*.032)*(1+.08*Math.sin(t+shell));ctx.beginPath();ctx.ellipse(cx,cy,shellR*1.42,shellR*(.64+.12*C),t*.08+shell*.19,0,Math.PI*2);ctx.strokeStyle=`rgba(${Math.round(70+130*q)},${Math.round(125+110*C)},${Math.round(135+100*P)},${.05+.018*shell})`;ctx.lineWidth=.8;ctx.stroke()}
 const count=kind==='MATTER'?1350:900;for(let i=0;i<count;i++){const u=(Math.sin((address+1)*.031+i*12.9898)*43758.5453)%1,v=(Math.sin((address+7)*.017+i*78.233)*24634.6345)%1,w=(Math.sin((address+13)*.011+i*31.117)*9758.132)%1;const a=Math.abs(u)*Math.PI*2+t*(.15+.38*C),r=Math.pow(Math.abs(v),.62)*Math.min(W,H)*(.27+.05*P),z=(Math.abs(w)-.5)*2,warp=Math.sin(a*(3+coords.r*.18)+t*2+i*.003)*(.04+.10*scar);const perspective=.78+.22*(z+1)/2,x=cx+Math.cos(a+warp)*r*1.45*perspective,y=cy+Math.sin(a)*r*.68*perspective+z*56*(.35+.65*P),stress=Math.max(0,Math.min(1,.55*q+.45*L)),alpha=.08+.55*E*(.45+.55*perspective);ctx.fillStyle=stress>.55?`rgba(222,111,101,${alpha})`:`rgba(84,223,205,${alpha})`;ctx.beginPath();ctx.arc(x,y,.65+1.35*perspective,0,Math.PI*2);ctx.fill()}
 const path:number[]=[address];let a=address;for(let i=0;i<7;i++){a=nextOf(a);path.push(a)}path.forEach((s,i)=>{const r=corpusState(s),c2=decodeAddress(s),ang=-Math.PI/2+i*.52+t*.04,rad=Math.min(W,H)*(.08+i*.032),x=cx+Math.cos(ang)*rad*1.35,y=cy+Math.sin(ang)*rad*.72;ctx.fillStyle=i===0?'#fff0bd':'#62e1d0';ctx.globalAlpha=i===0?1:.35+.07*i;ctx.beginPath();ctx.arc(x,y,i===0?7:3.8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(i>0){ctx.font='9px ui-monospace,monospace';ctx.fillStyle='rgba(205,226,226,.5)';ctx.fillText(`${r.stateId} D${c2.d+1}P${c2.p+1}R${c2.r+1}L${c2.l+1}`,x+7,y-5)}});
 ctx.font='11px ui-monospace,monospace';ctx.fillStyle='rgba(222,239,236,.82)';ctx.fillText(`${kind} VOLUME · STATE ${record.stateId} · D${coords.d+1}/P${coords.p+1}/R${coords.r+1}/L${coords.l+1}`,16,24);ctx.fillStyle='rgba(136,169,170,.72)';ctx.fillText(`CΩ ${fmt(C)} · Φ ${fmt(P)} · q ${fmt(q)} · Λ ${fmt(L)} · evidence ${fmt(E)}`,16,42);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[address,kind,record,coords]);
 return <canvas className='r36-state-volume' ref={canvas} aria-label={`${kind} volumetric state field with admitted state evolution`}/>;
}

function TraversalBar({address,onAddress,label}:{address:number;onAddress:(n:number)=>void;label:string}){const t=useActualTraversal(address,onAddress),r=corpusState(address);return <div className='r36-traversal-bar'><button onClick={()=>onAddress(prevOf(address))}><StepBack/>Previous</button><button className={t.running?'active primary-action':'primary-action'} onClick={()=>t.setRunning(v=>!v)}>{t.running?<Pause/>:<Play/>}{t.running?'Traversing':'Traverse'}</button><button onClick={()=>onAddress(nextOf(address))}><StepForward/>Admitted next</button><label>rate<select value={t.rate} onChange={e=>t.setRate(Number(e.target.value))}><option value='1500'>slow</option><option value='900'>normal</option><option value='450'>fast</option></select></label><span><b>{label}</b> · {r.stateId} · {t.ticks} enacted transitions</span></div>}

export function MatterTraversalR36({address,onAddress,state,onNavigate}:{address:number;onAddress:(n:number)=>void;state:any;onNavigate?:(p:string)=>void}){const r=corpusState(address);return <section className='special-app r36-living-surface'><header className='r36-surface-head'><div><span>MATTER · STATE VOLUME · SOURCE-BOUND</span><h2>Matter Traversal</h2><p>The visible object is now the evolving state volume. Traversal changes the canonical packet through admitted transitions; it is not a decorative line trace.</p></div><strong>{r.metrics.decision}</strong></header><StateVolume address={address} kind='MATTER'/><TraversalBar address={address} onAddress={onAddress} label='canonical matter path'/><OmegaMotionSkinMapR35 address={address} onSelectAddress={onAddress} compact/><details className='r36-advanced'><summary><ChevronDown/>Advanced matter compiler / proof / host controls</summary><div className='r36-advanced-body'><MatterTraversal state={state} onCommit={(c:any)=>onAddress(1728*c.d+144*c.p+12*c.r+c.l)} onNavigate={onNavigate}/></div></details><footer className='r36-truth'><ShieldCheck/>State-volume geometry is computed from the active source packet and admitted route. Physical-scale labels remain reference contexts, not claims that atlas coordinates are measured particle positions.</footer></section>}

export function VisualInstrumentR36({address,onAddress}:{address:number;onAddress:(n:number)=>void}){return <section className='special-app r36-living-surface r36-visual'><header className='r36-surface-head'><div><span>VISUAL INSTRUMENT · FIELD FIRST</span><h2>Visual Instrument</h2><p>The field owns the screen. Motion, continuity, scar and route are visible first; compiler lineage, lenses and camera calibration remain available only when requested.</p></div></header><div className='r36-visual-primary'><OmegaLivingField address={address} onSelectAddress={onAddress}/></div><TraversalBar address={address} onAddress={onAddress} label='visual state evolution'/><OmegaMotionSkinMapR35 address={address} onSelectAddress={onAddress} compact/><details className='r36-advanced'><summary><ChevronDown/>Advanced 20,736 field compiler / camera / lens controls</summary><div className='r36-advanced-body'><OmegaVisualInstrument address={address} onCommit={onAddress}/></div></details></section>}

export function TraversalR36({variant,address,state,onAddress}:{variant:'Immersive Traversal'|'Extreme Traversal'|'Traversal';address:number;state:any;onAddress:(n:number)=>void}){return <section className='special-app r36-living-surface'><header className='r36-surface-head'><div><span>TRAVERSAL · ENACTED ROUTE</span><h2>{variant}</h2><p>Press Traverse and the canonical address actually advances through admitted states. The volume reorganizes from the packet instead of drawing a route over a static point cloud.</p></div></header><StateVolume address={address} kind='TRAVERSAL'/><TraversalBar address={address} onAddress={onAddress} label='enacted traversal'/><OmegaMotionSkinMapR35 address={address} onSelectAddress={onAddress} compact/><details className='r36-advanced'><summary><ChevronDown/>Advanced traversal renderer / proof receipt</summary><div className='r36-advanced-body'><OmegaTraversalStudio variant={variant} address={address} state={state} onAddress={onAddress}/></div></details></section>}
