import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Archive,BookOpen,BrainCircuit,Database,FileCode2,FolderKanban,Gauge,GitBranch,Globe2,Layers3,Orbit,RefreshCw,Save,Settings2,ShieldCheck,Sparkles,TerminalSquare,Waypoints,Wrench} from 'lucide-react';
import OmegaCommandDeck from './OmegaCommandDeck';
import ResponsiveRuntimeShell,{LayoutModeSwitch,type OmegaUiMode} from './ResponsiveRuntimeShell';
import AtlasViewport from './AtlasViewport';
import CalculusTraversal from './CalculusTraversal';
import {corpusState,decodeAddress,evaluateCorpusModes,initCorpusPack,validateCorpusPack} from './corpusRuntime';
import {unifiedFromRecord,validateUnifiedMath} from './unifiedCalculus';
import {api,localState} from './platformAdapter';
import {RUNTIME_IDENTITY} from './runtimeIdentity';
import './responsiveShell.css';
import './commandDeck.css';

const NAV=[['Command Center',Sparkles],['Hybrid Link',TerminalSquare],['Workspace',Gauge],['Cockpit',Gauge],['Immersive Traversal',Waypoints],['Matter Traversal',Orbit],['Extreme Traversal',Waypoints],['Visual Instrument',Orbit],['Relativity',Orbit],['Earth Now',Globe2],['Forecast',Activity],['Atlas',Orbit],['Traversal',Waypoints],['Create',Sparkles],['Field',Layers3],['Data Motion',Activity],['Reality Lab',Activity],['Atlas Calculator',Orbit],['Infinity',Orbit],['Convergence',GitBranch],['Quality Compiler',ShieldCheck],['Build Out',GitBranch],['Projects',FolderKanban],['Render Queue',Archive],['Assets',Database],['Modes',BrainCircuit],['Kernel Intelligence',BrainCircuit],['Evidence & Proof',ShieldCheck],['Memory',FileCode2],['Archive Census',Archive],['Archive Operators',Wrench],['Development',GitBranch],['Canon Evolution',GitBranch],['SAI Lab',BrainCircuit],['Governance',ShieldCheck],['Consolidation',GitBranch],['Instructions',BookOpen],['Plugins',Wrench],['Settings',Settings2],['System',TerminalSquare],['Validation',ShieldCheck],['System Atlas',Orbit],['Scale Compiler',Layers3],['Control Matrix',TerminalSquare]] as const;
type PanelName=typeof NAV[number][0];
type EventRow={id:string;at:number;type:string;text:string;state?:number};
type Project={id:string;at:number;name:string;description:string};
type Job={id:string;at:number;title:string;engine:string;state:number;status:string};
const GROUPS=[['STUDIO',NAV.slice(0,14)],['OPERATIONS',NAV.slice(14,22)],['INTELLIGENCE',NAV.slice(22,32)],['SYSTEM',NAV.slice(32)]] as const;
const fmt=(v:any,d=4)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):String(v??'—');
const id=(p:string)=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
function Pill({children,kind=''}:{children:any;kind?:string}){return <span className={'pill '+kind}>{children}</span>}
function Metric({label,value,invert=false}:{label:string;value:number;invert?:boolean}){const v=Math.max(0,Math.min(1,Number(value)||0)),w=(invert?1-v:v)*100;return <div className='metric'><span>{label}</span><b>{fmt(value)}</b><div><i style={{width:`${w}%`}}/></div></div>}
function Gate({label,value,detail}:{label:string;value:any;detail?:string}){return <div><span>{label}</span><b>{String(value??'—')}</b>{detail&&<small>{detail}</small>}</div>}
function Head({over,title,right}:{over:string;title:string;right?:any}){return <div className='section-head'><div><p className='overline'>{over}</p><h2>{title}</h2></div>{right}</div>}
function Bound({children}:{children:any}){return <div className='boundary'><ShieldCheck size={16}/>{children}</div>}
function Packet({record}:{record:any}){const u=unifiedFromRecord(record);return <><div className='channel-grid'><Metric label='Continuity CΩ' value={record.metrics.continuity}/><Metric label='Plasticity Φ' value={record.metrics.plasticity}/><Metric label='Contradiction q' value={record.metrics.contradiction} invert/><Metric label='Burden Λ' value={record.metrics.burden} invert/><Metric label='Scar' value={record.metrics.scar} invert/><Metric label='Evidence' value={record.metrics.evidence}/><Metric label='RSC' value={record.metrics.rsc}/><Metric label='Geometry' value={record.metrics.geometry}/><Metric label='Water conductance' value={u.water.conductance}/><Metric label='Unified Rᵤ' value={u.unifiedCoherence}/></div><div className='equation'><code>S=(CΩ·Φ)/(q+Λ+ε)</code><b>{fmt(u.commonKernel,6)}</b><span>Full Overall Canon common kernel</span></div></>}
function RouteForecast({address}:{address:number}){const rows=useMemo(()=>{const a=[];let n=address;for(let i=0;i<36;i++){const r=corpusState(n);a.push(r);n=r.autoPing.dataNext}return a},[address]);const W=900,H=270,p=30,x=(i:number)=>p+i/(rows.length-1)*(W-p*2),y=(v:number)=>H-p-Math.max(0,Math.min(1,v))*(H-p*2),series=[['continuity','CΩ','#58c7ba'],['plasticity','Φ','#d0a866'],['contradiction','q','#c85b69'],['burden','Λ','#8196a8']] as const;return <><svg className='forecast-chart' viewBox={`0 0 ${W} ${H}`} role='img' aria-label='36-step source-route forecast'>{[0,.25,.5,.75,1].map(v=><line key={v} x1={p} x2={W-p} y1={y(v)} y2={y(v)} stroke='rgba(255,255,255,.07)'/>)}{series.map(([key,label,color])=><g key={key}><polyline fill='none' stroke={color} strokeWidth='2' points={rows.map((r,i)=>`${x(i)},${y(r.metrics[key])}`).join(' ')}/><text x={W-p} y={y(rows.at(-1)!.metrics[key])-4} fill={color} fontSize='10' textAnchor='end'>{label}</text></g>)}</svg><div className='table-list'>{rows.slice(0,12).map((r,i)=><div key={i}><b>t+{i} · state {r.stateId}</b><span>{r.metrics.decision}</span><small>CΩ {fmt(r.metrics.continuity,3)} · Φ {fmt(r.metrics.plasticity,3)} · q {fmt(r.metrics.contradiction,3)} · Λ {fmt(r.metrics.burden,3)}</small></div>)}</div></>}

export default function OmegaWorkstation(){
 const[ready,setReady]=useState(false),[bootError,setBootError]=useState(''),[panel,setPanel]=useState<PanelName>(()=>localState.read('omega.v6.panel','Command Center') as PanelName),[address,setAddress]=useState(()=>localState.read('omega.v6.address',11498)),[uiMode,setUiMode]=useState<OmegaUiMode>(()=>{const x=localStorage.getItem('omega-ui-mode');return x==='DESKTOP'||x==='MOBILE'?x:'AUTO'}),[modePolicy,setModePolicy]=useState<'CONTEXTUAL'|'ALL'|'CUSTOM'>(()=>localState.read('omega.v6.modePolicy','CONTEXTUAL')),[prompt,setPrompt]=useState(()=>localState.read('omega.b015.chatDraft.v1','Use ALL MODES and Mode 188 to assess this state, identify the weakest edge, and give the next useful OMEGA action.')),[response,setResponse]=useState<any>(null),[busy,setBusy]=useState(''),[status,setStatus]=useState<any>(null),[restore,setRestore]=useState<any>(null),[query,setQuery]=useState(''),[events,setEvents]=useState<EventRow[]>(()=>localState.read('omega.v6.events',[])),[memory,setMemory]=useState<EventRow[]>(()=>localState.read('omega.v6.memory',[])),[projects,setProjects]=useState<Project[]>(()=>localState.read('omega.v6.projects',[])),[jobs,setJobs]=useState<Job[]>(()=>localState.read('omega.v6.jobs',[])),[input,setInput]=useState(''),[aux,setAux]=useState(''),[systemCheck,setSystemCheck]=useState<any>(null);const main=useRef<HTMLElement|null>(null),seq=useRef(0);
 useEffect(()=>{initCorpusPack().then(()=>setReady(true)).catch(e=>setBootError(e instanceof Error?e.message:String(e)))},[]);
 useEffect(()=>void localState.write('omega.v6.panel',panel),[panel]);useEffect(()=>void localState.write('omega.v6.address',address),[address]);useEffect(()=>void localState.write('omega.v6.modePolicy',modePolicy),[modePolicy]);useEffect(()=>void localState.write('omega.v6.events',events),[events]);useEffect(()=>void localState.write('omega.v6.memory',memory),[memory]);useEffect(()=>void localState.write('omega.v6.projects',projects),[projects]);useEffect(()=>void localState.write('omega.v6.jobs',jobs),[jobs]);
 const loadStatus=async()=>{try{const [s,r]=await Promise.all([api.get<any>('/api/status'),api.get<any>('/api/restoration')]);setStatus(s.data);setRestore(r.data)}catch(e:any){setStatus({error:e.message})}};useEffect(()=>{void loadStatus()},[]);
 const record=useMemo(()=>ready?corpusState(address):null,[ready,address]);const math=useMemo(()=>record?unifiedFromRecord(record):null,[record]);const modes=useMemo(()=>record?evaluateCorpusModes(record):null,[record]);const coords=useMemo(()=>decodeAddress(address),[address]);const state=useMemo(()=>({atlas:{address},modePolicy,frozen:false,d:coords.d,p:coords.p,r:coords.r,l:coords.l,workflow:'LAW',preset:'SOVEREIGN',timeAuthority:'NOW'}),[address,modePolicy,coords]);
 const go=(name:string)=>{setPanel(name as PanelName);requestAnimationFrame(()=>main.current?.focus({preventScroll:true}))};const commit=(c:{d:number;p:number;r:number;l:number})=>setAddress(1728*c.d+144*c.p+12*c.r+c.l);const log=(type:string,text:string)=>setEvents(x=>[...x,{id:id('evt'),at:Date.now(),type,text,state:record?.stateId}].slice(-300));
 const ask=async()=>{if(!prompt.trim()||busy)return;localState.write('omega.b015.chatDraft.v1',prompt);const s=++seq.current;setBusy('response');try{const pre=await api.post<any>('/api/route-preview',{text:prompt}),r=await api.post<any>('/api/chat',{text:prompt});if(s===seq.current){setResponse({answer:r.data?.reply||'No response.',responsePath:pre.data?.route,evidenceStatus:pre.data?.route==='FAST_DETERMINISTIC'?'VERIFIED_RUNTIME':'PROVIDER_BOUND',modelInvoked:pre.data?.route!=='FAST_DETERMINISTIC',modelSucceeded:r.ok,appliedModes:modePolicy==='ALL'?['ALL MODES']:['CONTEXTUAL'],uncertainty:pre.data?.route==='FAST_DETERMINISTIC'?'Bounded runtime fact.':'External synthesis remains provider-bound.',nextAction:'Continue from the shared source packet and proof state.'});log('CHAT',prompt)}}catch(e:any){if(s===seq.current)setResponse({answer:e.message,responsePath:'ROUTED_MODEL',evidenceStatus:'BOUNDED_FAILURE',modelInvoked:true,modelSucceeded:false,uncertainty:'No fabricated response substituted.',nextAction:'Use deterministic tools or bind a provider.'})}finally{if(s===seq.current)setBusy('')}};
 const validate=async()=>{if(!record)return;setBusy('validation');const c:any[]=[];try{const p=validateCorpusPack(),m=validateUnifiedMath(record);c.push({name:'20,736 source pack',pass:p.passed,detail:`${p.stateCount} states · ${p.modeCount} modes · R²≥${p.coreR2Min.toFixed(4)}`},{name:'unified calculus',pass:m.passed,detail:`${m.checks.filter((x:any)=>x.passed).length}/${m.checks.length} invariants`});for(const [name,url] of [['Worker health','/api/health'],['Runtime truth','/api/status'],['Restoration','/api/restoration'],['Hybrid Link','/api/hybrid/status']]){try{const r=await api.get<any>(url);c.push({name,pass:r.ok,detail:String(r.data?.state||r.data?.ok||'reachable')})}catch(e:any){c.push({name,pass:false,detail:e.message})}}const result={at:Date.now(),status:c.every(x=>x.pass)?'PASS':'CHECK',checks:c};setSystemCheck(result);log('VALIDATION',result.status)}finally{setBusy('')}};
 if(bootError)return <div className='boot'><ShieldCheck/><b>SOURCE PACK FAILED</b><span>{bootError}</span><button className='gold' onClick={()=>location.reload()}>Reload</button></div>;if(!ready||!record||!math||!modes)return <div className='boot'><Orbit className='spin'/><b>OMEGA {RUNTIME_IDENTITY.hostedBuild}</b><span>Loading embedded 20,736-state source runtime…</span></div>;
 const sourceInstrument=(name:string,description:string)=><section className='panel'><Head over='SOURCE-BOUND WORKSTATION' title={name} right={<><Pill>{record.metrics.decision}</Pill><Pill>STATE {record.stateId}</Pill></>}/><p className='muted'>{description}</p><CalculusTraversal state={state} onSelect={commit} compact/><Packet record={record}/><div className='gate-grid'><Gate label='Auto-Ping next' value={record.autoPing.dataNext+1}/><Gate label='Mode188 +188' value={record.autoPing.mode188Plus+1}/><Gate label='Common kernel' value={fmt(math.commonKernel,6)}/><Gate label='Unified coherence' value={fmt(math.unifiedCoherence,6)}/><Gate label='Weakest mode' value={modes.weakest.name} detail={`${modes.weakest.gate} · ${fmt(modes.weakest.score)}`}/></div></section>;
 const table=(rows:EventRow[])=>rows.length?<div className='table-list'>{[...rows].reverse().slice(0,80).map(x=><div key={x.id}><b>{x.type}</b><span>{x.text}</span><small>state {x.state||'—'} · {new Date(x.at).toLocaleString()}</small></div>)}</div>:<div className='answer'><b>No entries yet.</b><p>This live local ledger is ready without claiming Drive release promotion.</p></div>;
 const panelView=()=>{
  if(panel==='Command Center'||panel==='Create'||panel==='SAI Lab'||panel==='Development'||panel==='Build Out')return <><OmegaCommandDeck record={record} state={state} prompt={prompt} onPrompt={v=>{setPrompt(v);localState.write('omega.b015.chatDraft.v1',v)}} onRun={ask} response={response} busy={busy} onNavigate={go}/>{panel!=='Command Center'&&sourceInstrument(panel,'Assistant synthesis is provider-gated while deterministic source/runtime analysis remains live.')}</>;
  if(panel==='Workspace'||panel==='Cockpit')return <><section className='panel'><Head over='ONE STATE · ONE LEDGER · ONE PACKET' title={panel==='Workspace'?'Unified Workspace':'Renderer-first Cockpit'} right={<Pill kind='ok'>SOURCE LIVE</Pill>}/><div className='hero-grid'><CalculusTraversal state={state} onSelect={commit} compact/><div className='state-rail'><Metric label='Continuity CΩ' value={record.metrics.continuity}/><Metric label='Plasticity Φ' value={record.metrics.plasticity}/><Metric label='Evidence' value={record.metrics.evidence}/><Metric label='Unified Rᵤ' value={math.unifiedCoherence}/><div className='address-box'><span>ATLAS ADDRESS</span><strong>{record.stateId.toLocaleString()}</strong><code>D{coords.d} · P{coords.p} · R{coords.r} · L{coords.l}</code></div></div></div></section><RuntimeTruth/></>;
  if(['Immersive Traversal','Matter Traversal','Extreme Traversal','Visual Instrument','Traversal'].includes(panel))return <section className='panel'><Head over='LIVE MOTION · CALCULUS · SCAR CARRY' title={panel} right={<Pill>{record.identity.autoPingState}</Pill>}/><CalculusTraversal state={state} onSelect={commit}/><Packet record={record}/><Bound>Renderer data is driven by the embedded source corpus. Native GPU/Qt/CUDA authority remains a separate device consumer.</Bound></section>;
  if(panel==='Atlas'||panel==='Data Motion')return <section className='panel'><Head over='20,736 SOURCE ADDRESSES' title={panel==='Atlas'?'Full Source Atlas':'Data Motion'} right={<Pill>{record.metrics.mode188}</Pill>}/><AtlasViewport state={state} onSelect={commit}/><Packet record={record}/><Bound>LATTICE, MANDALA, INVERSE and THREAD are projections of one source packet.</Bound></section>;
  if(panel==='Field')return sourceInstrument('Canonical Field','Read-only source packet values, Water/Dewey/RSC relationships and admitted state motion.');
  if(panel==='Relativity'){const n=corpusState(record.autoPing.dataNext),delta=n.math.normalizedMotionRelativity-record.math.normalizedMotionRelativity;return <section className='panel'><Head over='OBSERVER · FRAME · MOTION' title='Relativity Lab' right={<Pill>ΔMRI {fmt(delta,6)}</Pill>}/><div className='gate-grid'><Gate label='Normalized MRI' value={fmt(record.math.normalizedMotionRelativity,6)}/><Gate label='Next MRI' value={fmt(n.math.normalizedMotionRelativity,6)}/><Gate label='Δ relative motion' value={fmt(delta,6)}/><Gate label='Symmetry' value={fmt(record.geometry.symmetry,6)}/><Gate label='Phase' value={fmt(math.phase,6)}/><Gate label='Orientation' value={math.orientation}/></div><CalculusTraversal state={state} onSelect={commit} compact/><Bound>20,736 is a software representation scale, not asserted as a physical dimension.</Bound></section>}
  if(panel==='Forecast')return <section className='panel'><Head over='36-STEP ENDOGENOUS ROUTE' title='Forecast Workspace' right={<Pill>UNCERTAINTY VISIBLE</Pill>}/><RouteForecast address={address}/><Bound>This forecasts the runtime's own admitted route. It is not labeled as measured external future data.</Bound></section>;
  if(panel==='Earth Now')return <section className='panel'><Head over='EARTH VIEW · TRUTH GATE' title='Earth Now' right={<Pill>{status?.earth?.liveFeeds||'EXTERNAL_DEGRADED'}</Pill>}/><div className='earth-stage'><div className='earth-orb'><i/><i/><b>EARTH</b></div></div><div className='gate-grid'><Gate label='Visualization' value='LIVE'/><Gate label='External imagery' value='EXTERNAL_DEGRADED'/><Gate label='Temporal authority' value='UNBOUND'/><Gate label='Source forecast' value='AVAILABLE'/></div><Bound>No external Earth observation is called live until an independently verified source is bound.</Bound></section>;
  if(panel==='Hybrid Link')return <section className='panel'><Head over='PHONE + PC · MISSION CONTROL' title='Hybrid Link' right={<Pill>{status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}</Pill>}/><div className='system-grid'><article className='system-card'><b>Cloud controller</b><p>Planning, route gates, status and proof envelopes are live.</p></article><article className='system-card'><b>Windows host</b><p>Native execution remains DEVICE_PROOF_REQUIRED until a verified heartbeat arrives.</p></article><article className='system-card'><b>Phone session</b><p>This browser can prepare work and inspect state without impersonating PC authority.</p></article></div><div className='flow-line'>PLAN → GATE → HEARTBEAT → LOCAL EXECUTION → PROOF RETURN → LEDGER</div><Bound>Hybrid Link is the normal multi-device path, not a repair mode.</Bound></section>;
  if(panel==='Modes')return <section className='panel'><Head over='SOURCE ALGEBRA REGISTRY' title='Modes' right={<div className='mode-policy'><button className={modePolicy==='CONTEXTUAL'?'active':''} onClick={()=>setModePolicy('CONTEXTUAL')}>CONTEXTUAL</button><button className={modePolicy==='ALL'?'active':''} onClick={()=>setModePolicy('ALL')}>ALL</button><button className={modePolicy==='CUSTOM'?'active':''} onClick={()=>setModePolicy('CUSTOM')}>CUSTOM</button></div>}/><div className='corpus-mode-summary'><div><span>EXECUTED</span><b>{modes.count}</b></div><div><span>STAY</span><b>{modes.stay}</b></div><div><span>TURN</span><b>{modes.turn}</b></div><div><span>ESCALATE</span><b>{modes.escalate}</b></div><div><span>WEAKEST</span><b>{fmt(modes.weakest.score)}</b></div><div><span>STRONGEST</span><b>{fmt(modes.strongest.score)}</b></div></div><div className='corpus-mode-list'>{modes.results.map((x:any)=><div className='corpus-mode-row' key={x.id}><b>{x.name}<br/><span>{x.category}</span></b><span>{x.gate}</span><strong>{fmt(x.score)}</strong></div>)}</div></section>;
  if(panel==='Evidence & Proof')return <section className='panel'><Head over='LOCAL PROOF · NO FALSE PROMOTION' title='Evidence & Proof' right={<Pill>{events.length} EVENTS</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Observed evidence / proof note'/><button className='gold' onClick={()=>{if(input.trim()){log('EVIDENCE',input.trim());setInput('')}}}><Save size={14}/> Record proof</button></div>{table(events)}<Bound>Browser-local evidence stays separate from the Drive release ledger until explicitly admitted through the canonical process.</Bound></section>;
  if(panel==='Memory')return <section className='panel'><Head over='SCAR · CARRY · CONTINUITY' title='Memory' right={<Pill>{memory.length} NOTES</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Continuity / scar memory'/><button className='gold' onClick={()=>{if(input.trim()){setMemory(x=>[...x,{id:id('mem'),at:Date.now(),type:'SCAR_CARRY',text:input.trim(),state:record.stateId}].slice(-300));setInput('')}}}>Carry forward</button></div>{table(memory)}<Bound>Local continuity persists across reloads but is not silently promoted to release authority.</Bound></section>;
  if(panel==='Projects')return <section className='panel'><Head over='PERSISTENT LOCAL WORK' title='Projects' right={<Pill>{projects.length}</Pill>}/><div className='form-grid'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Project name'/><input value={aux} onChange={e=>setAux(e.target.value)} placeholder='Description'/></div><button className='gold' onClick={()=>{if(input.trim()){setProjects(x=>[...x,{id:id('prj'),at:Date.now(),name:input.trim(),description:aux.trim()}]);setInput('');setAux('')}}}>Create project</button><div className='table-list'>{projects.map(x=><div key={x.id}><b>{x.name}</b><span>{x.description||'No description'}</span><small>{new Date(x.at).toLocaleString()}</small></div>)}</div></section>;
  if(panel==='Render Queue')return <section className='panel'><Head over='ONE QUEUE · MULTIPLE CONSUMERS' title='Render / Handoff Queue' right={<Pill>{jobs.length}</Pill>}/><div className='form-row'><input value={input} onChange={e=>setInput(e.target.value)} placeholder='Job title'/><select value={aux||'HOSTED_REFERENCE_PACKET'} onChange={e=>setAux(e.target.value)}><option>HOSTED_REFERENCE_PACKET</option><option>TARGET_GPU</option><option>CYCLES</option><option>HYBRID_LINK</option></select><button className='gold' onClick={()=>{if(input.trim()){const engine=aux||'HOSTED_REFERENCE_PACKET',device=['TARGET_GPU','CYCLES','HYBRID_LINK'].includes(engine);setJobs(x=>[...x,{id:id('job'),at:Date.now(),title:input.trim(),engine,state:record.address,status:device?'DEVICE_PROOF_REQUIRED':'READY'}]);setInput('')}}}>Queue handoff</button></div><div className='table-list'>{jobs.map(x=><div key={x.id}><b>{x.title}</b><span>{x.engine} · {x.status}</span><small>state {x.state+1} · {new Date(x.at).toLocaleString()}</small></div>)}</div></section>;
  if(panel==='Validation')return <section className='panel'><Head over='STRICT SOFTWARE PROOF' title='Validation' right={<button className='gold' onClick={validate} disabled={!!busy}><ShieldCheck size={14}/>{busy?' Checking…':' Run validation'}</button>}/>{systemCheck?<><div className='gate-grid'>{systemCheck.checks.map((x:any)=><Gate key={x.name} label={x.name} value={x.pass?'PASS':'CHECK'} detail={x.detail}/>)}</div><Bound>Integrated result {systemCheck.status}; external/native gates remain separate.</Bound></>:<div className='answer'>Run validation to test the source pack, unified calculus and public Worker truth endpoints.</div>}</section>;
  if(panel==='System')return <RuntimeTruth/>;
  if(panel==='Control Matrix')return <section className='panel'><Head over='44 ROUTES · ONE PACKET' title='Control Matrix' right={<Pill>44/44</Pill>}/><div className='contract-grid'>{NAV.map(([name,Icon])=><article key={name}><Icon size={16}/><b>{name}</b><span>{['Immersive Traversal','Matter Traversal','Extreme Traversal','Visual Instrument','Traversal','Atlas'].includes(name)?'SOURCE RENDERER':name==='Hybrid Link'?'DEVICE GATE':name==='Earth Now'?'EXTERNAL GATE':'PACKET / CLOUD'}</span><small>Shared source authority or explicit truth gate.</small><button onClick={()=>go(name)}>Open</button></article>)}</div></section>;
  if(panel==='Settings')return <section className='panel'><Head over='WORKSTATION PREFERENCES' title='Settings'/><div className='settings-grid'><label>UI mode<LayoutModeSwitch value={uiMode} onChange={setUiMode}/></label><label>Mode policy<select value={modePolicy} onChange={e=>setModePolicy(e.target.value as any)}><option>CONTEXTUAL</option><option>ALL</option><option>CUSTOM</option></select></label><label>Source state<input type='number' min='1' max='20736' value={address+1} onChange={e=>setAddress(Math.max(0,Math.min(20735,Number(e.target.value)-1)))}/></label></div><Bound>Settings alter view/routing state only, never source data.</Bound></section>;
  if(panel==='Instructions')return <section className='panel'><Head over='OMEGA OPERATING MODEL' title='Instructions'/><div className='table-list'><div><b>Ask naturally</b><p>Command Center routes bounded facts before synthesis.</p></div><div><b>Traverse exact source states</b><p>Atlas and traversal commit the selected address to the shared workstation.</p></div><div><b>Keep proof visible</b><p>Validation and truth gates stay separate from visual polish.</p></div><div><b>Use Hybrid Link for native work</b><p>Cloud planning does not equal native execution; heartbeat/proof is required.</p></div></div></section>;
  if(['Reality Lab','Atlas Calculator','Infinity','Convergence','Quality Compiler','Kernel Intelligence','Canon Evolution','Governance','Consolidation','System Atlas','Scale Compiler'].includes(panel))return sourceInstrument(panel,`${panel} operates on the shared source packet, calculus, route, proof and mode state instead of a disconnected placeholder.`);
  if(['Assets','Archive Census','Archive Operators','Plugins'].includes(panel))return <section className='panel'><Head over='CAPABILITY / DONOR INVENTORY' title={panel} right={<Pill>BOUNDED</Pill>}/><div className='system-grid'><article className='system-card'><b>Embedded source</b><p>20,736 addresses and {modes.count} source algebra modes are loaded.</p></article><article className='system-card'><b>Cloud runtime</b><p>Worker health, route, restoration and status gates are exposed.</p></article><article className='system-card'><b>Drive authority</b><p>B015 R1 remains the release pointer authority.</p></article><article className='system-card'><b>Native consumers</b><p>GPU/Qt/CUDA/Cycles remain device-gated.</p></article></div><Bound>No unseen donor is promoted from a filename or label alone.</Bound></section>;
  return sourceInstrument(panel,`${panel} is bound to the shared source packet and remains operational through the common runtime instrument.`)
 };
 function RuntimeTruth(){return <section className='panel'><Head over='SOVEREIGN AUTHORITY GRAPH' title='Runtime Truth' right={<button onClick={loadStatus}><RefreshCw size={14}/> Refresh</button>}/><div className='gate-grid'><Gate label='Release authority' value={status?.canonicalAuthority?.release||'B015 R1'}/><Gate label='Cloud Worker' value={status?.cloud?.worker||'CHECKING'}/><Gate label='Restore branch' value={restore?.branch||'full-restore'}/><Gate label='Provider' value={status?.modelProvider||'NOT_CONFIGURED'}/><Gate label='Hybrid Link' value={status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}/><Gate label='Earth feeds' value={status?.earth?.liveFeeds||'EXTERNAL_DEGRADED'}/></div>{systemCheck&&<div className='gate-grid'>{systemCheck.checks.map((x:any)=><Gate key={x.name} label={x.name} value={x.pass?'PASS':'CHECK'} detail={x.detail}/>)}</div>}<Bound>Google Drive remains release authority. Cloudflare is the public runtime/deployment bridge and does not create native/device/provider truth by itself.</Bound></section>}
 const visible=(name:string)=>!query.trim()||name.toLowerCase().includes(query.trim().toLowerCase());
 return <div className={'studio layout-'+uiMode.toLowerCase()}><div className='menu-bar'><div className='wordmark'><Orbit size={18}/><b>OMEGA</b><span>{RUNTIME_IDENTITY.hostedBuild} · {RUNTIME_IDENTITY.runtimeContract} · SOVEREIGN CLOUD</span></div><button onClick={()=>go('Projects')}>File</button><button onClick={()=>go('Field')}>Edit</button><button onClick={()=>go('Matter Traversal')}>View</button><button onClick={()=>go('Control Matrix')}>Menus</button><button onClick={()=>go('Modes')}>Modes</button><button onClick={()=>go('Render Queue')}>Render</button><button onClick={()=>go('System')}>Tools</button><button onClick={()=>go('Instructions')}>Help</button><LayoutModeSwitch value={uiMode} onChange={setUiMode}/><div className='menu-spacer'/><Pill>{status?.cloud?.worker||'CLOUD'}</Pill><Pill>{record.metrics.decision}</Pill><Pill>S {fmt(record.metrics.stability,3)}</Pill></div><div className='tool-bar'><button className='gold' onClick={()=>go('Command Center')}><Sparkles size={15}/> AI Command</button><button onClick={()=>go('Workspace')}><Gauge size={15}/> Workspace</button><button onClick={()=>go('Immersive Traversal')}><Waypoints size={15}/> Live Immersive</button><button onClick={()=>go('Matter Traversal')}><Orbit size={15}/> Matter</button><button onClick={()=>go('Relativity')}><Orbit size={15}/> Relativity</button><button onClick={()=>go('Earth Now')}><Globe2 size={15}/> Earth</button><button onClick={()=>go('Hybrid Link')}><GitBranch size={15}/> Hybrid Link</button><button onClick={validate}><ShieldCheck size={15}/> System Check</button></div><ResponsiveRuntimeShell uiMode={uiMode} onUiMode={setUiMode} panel={panel} onNavigate={go} record={record} modePolicy={modePolicy} modeCount={modes.count} busy={busy}/><aside><div className='menu-search'><label htmlFor='omega-menu-search'>FIND ANY OF 44 MENUS</label><input id='omega-menu-search' value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search Matter, Forecast, System…'/></div>{GROUPS.map(([label,items])=><div className='aside-section' key={label}><small>{label}</small>{items.filter(([name])=>visible(name)).map(([name,Icon])=><button key={name} className={panel===name?'active':''} onClick={()=>go(name)}><Icon size={16}/>{name}</button>)}</div>)}</aside><main ref={main} tabIndex={-1}>{panelView()}</main><footer><span>{busy?`BUSY · ${busy}`:'READY'}</span><span>DRIVE B015 R1 AUTHORITY</span><span>STATE {record.stateId.toLocaleString()}/20,736</span><span>{modePolicy} · {modes.count} MODES</span><span>HYBRID {status?.hybridLink?.state||'DEVICE_PROOF_REQUIRED'}</span></footer></div>
}
