import {useEffect,useMemo,useState} from 'react';
import {Activity,BrainCircuit,CheckCircle2,CirclePause,GitBranch,MemoryStick,Network,Play,RefreshCw,RotateCcw,ShieldCheck,Workflow} from 'lucide-react';
import './omegaCortexR130.css';

type Props={record?:any;state?:any};
type Mode='ADAPTIVE'|'SOLO'|'BRANCH'|'ORGAN'|'FLOCK'|'BODY'|'FULL';
type ScopeType='BODY'|'ORGAN'|'BRANCH'|'CELL';
const MODES:Mode[]=['ADAPTIVE','SOLO','BRANCH','ORGAN','FLOCK','BODY','FULL'];
const SCOPES:ScopeType[]=['BODY','ORGAN','BRANCH','CELL'];
const PROJECTIONS=['CONVERGENCE','FIELD','MATTER','TRAVERSAL','FORECAST','RELATIVITY','INFINITY','SCALE','EARTH','OPTICAL','PROOF','BUILD'];
const safe=async(path:string,init?:RequestInit)=>{try{const r=await fetch(path,{cache:'no-store',...init,headers:{'cache-control':'no-cache',...(init?.body?{'content-type':'application/json'}:{}),...(init?.headers||{})}}),data=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data}}catch(error:any){return{ok:false,status:0,data:null,error:error?.message||String(error)}}};
const tag=(v:any)=>String(v??'UNPROVEN').toUpperCase();
export default function OmegaCortexR130({record,state}:Props){
 const[intent,setIntent]=useState('Operate the OMEGA organism at maximum useful capacity: distribute the mission across independent cells, synchronize the whole selected body, exchange candidate memory through bounded synapses, cross-check every represented branch, synthesize each represented organ, perform inter-organ exchange, preserve scars and evidence authority, and return one proof-bounded result without converting execution agreement into truth.');
 const[mode,setMode]=useState<Mode>('ADAPTIVE'),[scope,setScope]=useState<ScopeType>('BODY'),[domain,setDomain]=useState(0),[phase,setPhase]=useState(0),[regulation,setRegulation]=useState(0),[providerBudget,setProviderBudget]=useState(8),[dispatchWidth,setDispatchWidth]=useState(24),[allowFullAuto,setAllowFullAuto]=useState(false),[projection,setProjection]=useState('CONVERGENCE');
 const[plan,setPlan]=useState<any>(null),[mission,setMission]=useState<any>(null),[memory,setMemory]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[checkpoint,setCheckpoint]=useState<any>(null),[evidence,setEvidence]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('R130 maximum-capacity organism ready.');
 const metrics=record?.metrics??state?.metrics??{plasticity:.6,uncertainty:.5,contradiction:.2,evidence:.5,burden:.3};
 const payload=useMemo(()=>({intent,mode,projection,providerBudget,dispatchWidth,allowFullAuto,metrics,scope:{type:scope,domain,phase,regulation}}),[intent,mode,projection,providerBudget,dispatchWidth,allowFullAuto,metrics,scope,domain,phase,regulation]);
 const refresh=async(id=mission?.id)=>{if(!id)return;const r=await safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}`);if(r.data?.mission)setMission(r.data.mission);const [mem,ev,proof]=await Promise.all([safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}/memory?limit=36`),safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}/events`),safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}/evidence`)]);setMemory(mem.data?.memory??[]);setEvents(ev.data?.events??[]);if(proof.ok)setEvidence(proof.data)};
 useEffect(()=>{if(!mission?.id||!['QUEUED','RUNNING'].includes(mission.status))return;const id=window.setInterval(()=>void refresh(mission.id),1300);return()=>window.clearInterval(id)},[mission?.id,mission?.status]);
 const preview=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Compiling maximum-capacity body graph…');const r=await safe('/api/swarm/cortex/plan',{method:'POST',body:JSON.stringify(payload)});setPlan(r.data?.plan??null);setMessage(r.ok?'Plan compiled. No execution or canonical admission occurred.':`Plan unavailable (${r.status||'network'}).`);setBusy(false)};
 const execute=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Creating durable organism mission…');const r=await safe('/api/swarm/cortex/missions',{method:'POST',body:JSON.stringify(payload)});if(r.data?.mission)setMission(r.data.mission);if(r.data?.plan)setPlan(r.data.plan);setMessage(r.ok?'Mission created. Bounded concurrent cell execution will advance through the seven-stage body graph.':'Mission was not accepted; no execution is claimed.');setBusy(false)};
 const action=async(name:'advance'|'pause'|'resume'|'checkpoint'|'rejoin')=>{if(!mission?.id||busy)return;setBusy(true);const method=name==='checkpoint'?'GET':'POST',r=await safe(`/api/swarm/cortex/missions/${encodeURIComponent(mission.id)}/${name}`,{method,body:method==='POST'?JSON.stringify(name==='advance'?{batchSize:dispatchWidth}:{}):undefined});if(r.data?.mission)setMission(r.data.mission);if(r.data?.checkpoint)setCheckpoint(r.data.checkpoint);if(r.data?.executionEvidence)setEvidence(r.data);setMessage(r.ok?`Cortex ${name} completed.`:`Cortex ${name} failed (${r.status||'network'}).`);await refresh(mission.id);setBusy(false)};
 const p=plan??{},m=mission??{};
 return <section className='r130-cortex'>
  <header className='r130-head'><div><span>R130 · MAX-CAPACITY ORGANISM</span><h3>Independent cells, synchronized branches, interacting organs, one bounded body.</h3><p>Real stateful cell execution is organized as frame → parallel cell work → whole-cell barrier → branch cross-check → organ synthesis → inter-organ exchange → proof return. The system can use all 1,728 cells without pretending that means 1,728 model calls.</p></div><div className='r130-badge'><BrainCircuit/><b>1 → 12 → 144 → 1,728 → 20,736</b><small>address/execution hierarchy · not literal physical dimensions</small></div></header>
  <section className='r130-topology'>{[['SEED','1'],['ORGANS','12'],['BRANCHES','144'],['STATEFUL CELLS','1,728'],['EXECUTION LANES','20,736']].map(([k,v])=><article key={k}><span>{k}</span><b>{v}</b></article>)}</section>
  <section className='r130-main'><div className='r130-compose'><label><span>WHOLE-BODY OBJECTIVE</span><textarea value={intent} onChange={e=>setIntent(e.target.value)}/></label><div className='r130-controls'><label><span>SCALE</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>SCOPE</span><select value={scope} onChange={e=>setScope(e.target.value as ScopeType)}>{SCOPES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>PROJECTION</span><select value={projection} onChange={e=>setProjection(e.target.value)}>{PROJECTIONS.map(x=><option key={x}>{x}</option>)}</select></label><label><span>CONCURRENT DISPATCH · 1–48</span><input type='number' min='1' max='48' value={dispatchWidth} onChange={e=>setDispatchWidth(Math.max(1,Math.min(48,Number(e.target.value)||24)))}/></label><label><span>MODEL BUDGET · 0–12</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label>{scope!=='BODY'&&<label><span>ORGAN · 0–11</span><input type='number' min='0' max='11' value={domain} onChange={e=>setDomain(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}{(scope==='BRANCH'||scope==='CELL')&&<label><span>BRANCH · 0–11</span><input type='number' min='0' max='11' value={phase} onChange={e=>setPhase(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}{scope==='CELL'&&<label><span>CELL · 0–11</span><input type='number' min='0' max='11' value={regulation} onChange={e=>setRegulation(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}<label className='r130-check'><input type='checkbox' checked={allowFullAuto} onChange={e=>setAllowFullAuto(e.target.checked)}/><div><span>ALLOW ADAPTIVE FULL BODY</span><small>Without this, adaptive escalation stops at 288 cells. BODY/FULL is explicit operator intent.</small></div></label></div><div className='r130-actions'><button onClick={()=>void preview()} disabled={busy}><Workflow/>COMPILE ORGANISM</button><button className='prime' onClick={()=>void execute()} disabled={busy}><Play/>EXECUTE ORGANISM</button></div><p className='r130-message'>{message}</p></div>
  <aside className='r130-plan'><header><span>COMPILED BODY</span><b>{p.mode??mode} · {p.scope?.type??scope}</b></header><div className='r130-planstats'><article><span>SELECTED CELLS</span><b>{p.selectedCellCount??'—'}</b></article><article><span>TOTAL TASKS</span><b>{p.totalTaskCount??'—'}</b></article><article><span>BRANCH CHECKS</span><b>{p.totalBranchChecks??'—'}</b></article><article><span>ORGANS</span><b>{p.totalOrganSyntheses??'—'}</b></article><article><span>INTER-ORGAN</span><b>{p.totalInterorganExchanges??'—'}</b></article><article><span>DISPATCH WIDTH</span><b>{p.dispatchWidth??dispatchWidth}</b></article></div><div className='r130-waves'>{(p.waves??[]).map((w:any)=><div key={w.wave}><i>{w.wave}</i><span>{w.name}</span><b>{w.tasks}</b></div>)}</div><small>Workers AI hard ceiling: {p.budgets?.hardProviderMax??12} per mission. Full-body execution remains mostly deterministic/stateful unless specialist/model work is explicitly allocated.</small></aside></section>
  {mission&&<section className='r130-mission'><header><div><span>LIVE ORGANISM MISSION</span><b>{m.id}</b></div><strong data-state={tag(m.status)}>{tag(m.status)} · {m.phase}</strong></header><div className='r130-progress'><span style={{width:`${m.progress||0}%`}}/></div><div className='r130-missionstats'>{[['PROGRESS',`${m.progress??0}%`],['CELL COMPLETE',m.completedCellTasks??0],['CELL SCARS',m.failedCellTasks??0],['ALL TASKS',`${m.completedTasks??0}/${m.totalTaskCount??0}`],['MEMORY',m.memoryCount??0],['SCARS',m.scarCount??0],['PROOF',m.proofState??'—'],['DISPATCH',m.dispatchWidth??'—']].map(([k,v])=><article key={String(k)}><span>{k}</span><b>{String(v)}</b></article>)}</div><div className='r130-live-actions'><button onClick={()=>void refresh()}><RefreshCw/>REFRESH</button><button onClick={()=>void action('advance')} disabled={busy||!['QUEUED','RUNNING'].includes(m.status)}><Activity/>ADVANCE {dispatchWidth}</button>{m.status==='PAUSED'?<button onClick={()=>void action('resume')}><Play/>RESUME</button>:<button onClick={()=>void action('pause')} disabled={m.status!=='RUNNING'}><CirclePause/>PAUSE</button>}<button onClick={()=>void action('checkpoint')}><ShieldCheck/>CHECKPOINT</button><button onClick={()=>void action('rejoin')} disabled={m.status!=='COMPLETE'}><RotateCcw/>RETURN / REJOIN</button></div>{checkpoint&&<div className='r130-checkpoint'><CheckCircle2/><div><span>CHECKPOINT SHA-256</span><b>{checkpoint.sha256}</b><small>{checkpoint.authority}</small></div></div>}{evidence?.executionSemanticHash&&<div className='r130-checkpoint'><GitBranch/><div><span>EXECUTION REPLAY / PROOF HASH</span><b>{evidence.executionSemanticHash}</b><small>Eligible as an upstream proof/replay identity; R128 external-validation credit remains 0 unless independent external data is supplied.</small></div></div>}</section>}
  <section className='r130-lower'><div className='r130-memory'><header><MemoryStick/><div><span>SHARED CANDIDATE BLACKBOARD</span><b>{memory.length} recent packets</b></div></header><div>{memory.length?memory.slice(0,18).map((x:any)=><article key={x.taskId}><span>{x.role} · wave {x.wave} · {x.status}</span><b>{x.cellId||x.taskId}</b><p>{x.summary}</p><small>{x.authority}</small></article>):<p className='empty'>No candidate memory yet. Nothing is fabricated before cell receipts return.</p>}</div></div><div className='r130-events'><header><Network/><div><span>CAUSAL EVENT STREAM</span><b>{events.length} retained events</b></div></header><div>{events.length?events.slice(-28).reverse().map((x:any)=><article key={`${x.seq}-${x.at}`}><i>{x.seq}</i><div><b>{x.type}</b><small>{new Date(x.at).toLocaleTimeString()} {x.taskId?`· ${x.taskId}`:''}</small></div></article>):<p className='empty'>No mission events yet.</p>}</div></div></section>
  <footer className='r130-truth'><ShieldCheck/><div><b>PROOF / EMPIRICAL / CANONICAL BOUNDARY</b><span>R130 produces real execution receipts, internal integrity hashes, candidate memory and a replay identity. Those can feed the R127 evidence/execution proof fabric and R129 replay ledger. They do not count as independent reproduction or external R128 empirical validation, and they do not bypass R125/OMEGAv6 canonical admission.</span></div></footer>
 </section>
}
