import {useMemo,useState} from 'react';
import {Cable,CheckCircle2,Database,FileJson,FileSpreadsheet,Globe2,Link2,Network,Play,Search,ShieldCheck,Upload,Workflow,XCircle} from 'lucide-react';
import {api,localState} from './platformAdapter';
import {R44_TRANSITION_SEQUENCE} from './runtimeAuthorityR44';
import './integrationHubR44.css';

type Tab='ADAPTERS'|'DATA'|'LEXICON'|'DONOR';
type Adapter={id:string;label:string;endpoint:string;boundary:string};
type Imported={id:string;name:string;size:number;type:string;sha256:string;at:string;kind:'CSV'|'JSON'|'XLSX'|'OTHER';rows?:number;columns?:number;preview?:string[][];keys?:string[];boundary:string};
const STORE='omega.v6.integration.imports.r44';
const ADAPTERS:Adapter[]=[
 {id:'runtime',label:'Runtime authority',endpoint:'/api/health',boundary:'Hosted Worker health only.'},
 {id:'status',label:'System status',endpoint:'/api/status',boundary:'Configured hosted capabilities and explicit gates.'},
 {id:'hybrid',label:'Hybrid device bridge',endpoint:'/api/hybrid/status',boundary:'Device actions remain DEVICE_PROOF_REQUIRED until authenticated host proof returns.'},
 {id:'earth',label:'Earth evidence',endpoint:'/api/earth/evidence',boundary:'External source availability and returned evidence control admission.'}
];
const NAV:Record<string,string>={ask:'Command Center',command:'Command Center',build:'Build Out',code:'Development',create:'Create',render:'Visual Instrument',visual:'Visual Instrument',signal:'Visual Instrument',audio:'Visual Instrument',matter:'Matter Traversal',traverse:'Traversal',travel:'Traversal',earth:'Earth Now',weather:'Earth Now',forecast:'Forecast',future:'Forecast',proof:'Evidence & Proof',evidence:'Evidence & Proof',memory:'Memory',archive:'Archive Census',plugin:'Plugins',adapter:'Plugins',data:'Plugins',csv:'Plugins',excel:'Plugins',language:'Plugins',lexicon:'Plugins',system:'System Atlas',mode:'Modes',calculus:'Modes',hybrid:'Hybrid Link',computer:'Hybrid Link',pc:'Hybrid Link'};
const MODE:Record<string,string>={carry:'CARRY',construct:'CONSTRUCT',build:'CONSTRUCT',prune:'PRUNE',remove:'PRUNE',turn:'TURN',change:'TURN',escalate:'ESCALATE',scar:'SCAR',translate:'TRANSLATE',prove:'PROVE',proof:'PROVE',forecast:'FORECAST',ledger:'LEDGER'};
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<text.length&&rows.length<101;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.length))rows.push(row);row=[];cell=''}else cell+=c}if((cell||row.length)&&rows.length<101){row.push(cell);rows.push(row)}return rows}
function kindFor(file:File):Imported['kind']{const n=file.name.toLowerCase();return n.endsWith('.csv')?'CSV':n.endsWith('.json')?'JSON':n.endsWith('.xlsx')||n.endsWith('.xls')?'XLSX':'OTHER'}
function lexicon(text:string){const tokens=(text.toLowerCase().match(/[a-z0-9ΩΦλ]+/g)||[]),routes=[...new Set(tokens.map(t=>NAV[t]).filter(Boolean))],operators=[...new Set(tokens.map(t=>MODE[t]).filter(Boolean))],route=routes[0]||'Command Center';return{schema:'OMEGA_DETERMINISTIC_LEXICON_R44',input:text,tokens,route,candidateRoutes:routes.length?routes:[route],operators:operators.length?operators:['CARRY','CONSTRUCT','PROVE','LEDGER'],commandChain:['COMMAND_REGISTRY','PRESSURE_PACKET','SCENE_AUTHORITY','IMMUTABLE_STATE_PACKET','DEWEY_TRANSITION_KERNEL','UNIFIED_RENDERER','FRAME_PACKET','EVIDENCE_LEDGER'],transitionSequence:R44_TRANSITION_SEQUENCE,confidence:Math.min(.98,.42+Math.min(tokens.length,12)*.025+Math.min(routes.length,3)*.08+Math.min(operators.length,3)*.05),boundary:'Deterministic local vocabulary routing. This is not an LLM, translation proof, inferred intent authority or external provider output.'}}

export default function OmegaIntegrationHubR44({record,onNavigate}:{record:any;onNavigate:(p:string)=>void}){
 const[tab,setTab]=useState<Tab>('ADAPTERS'),[tests,setTests]=useState<Record<string,any>>({}),[testing,setTesting]=useState(''),[imports,setImports]=useState<Imported[]>(()=>localState.read(STORE,[])),[prompt,setPrompt]=useState('translate this CSV into a visual field, prove the route, then ledger it');
 const language=useMemo(()=>lexicon(prompt),[prompt]);
 const test=async(a:Adapter)=>{setTesting(a.id);try{const started=performance.now(),r=await api.get<any>(a.endpoint);setTests(x=>({...x,[a.id]:{ok:r.ok,status:r.status,ms:Math.round(performance.now()-started),data:r.data}}))}catch(e:any){setTests(x=>({...x,[a.id]:{ok:false,status:e?.status||0,error:e?.message||String(e)}}))}finally{setTesting('')}};
 const testAll=async()=>{for(const a of ADAPTERS)await test(a)};
 const ingest=async(file:File)=>{
  const buffer=await file.arrayBuffer(),sha256=hex(await crypto.subtle.digest('SHA-256',buffer)),kind=kindFor(file);
  let imported:Imported={id:`${sha256.slice(0,16)}-${Date.now()}`,name:file.name,size:file.size,type:file.type||'application/octet-stream',sha256,at:new Date().toISOString(),kind,boundary:'Local browser intake and fingerprint only. Import does not promote the file to source authority or external evidence.'};
  if(kind==='CSV'){
   const preview=parseCsv(new TextDecoder().decode(buffer).slice(0,1_500_000));
   imported={...imported,rows:preview.length?Math.max(0,preview.length-1):0,columns:preview.reduce((n,r)=>Math.max(n,r.length),0),preview:preview.slice(0,8)};
  }else if(kind==='JSON'){
   try{
    const value=JSON.parse(new TextDecoder().decode(buffer));
    imported={...imported,rows:Array.isArray(value)?value.length:1,keys:value&&typeof value==='object'&&!Array.isArray(value)?Object.keys(value).slice(0,64):[],preview:Array.isArray(value)?value.slice(0,5).map((x:any)=>[JSON.stringify(x)]):[[JSON.stringify(value).slice(0,500)]]};
   }catch{imported={...imported,boundary:'SHA-256 verified locally, but JSON parsing failed. The file is retained as metadata only and is not admitted.'}}
  }else if(kind==='XLSX'){
   imported={...imported,boundary:'Workbook bytes were SHA-256 fingerprinted locally. Formula recalculation and workbook semantics require the governed spreadsheet pipeline; no Excel execution is claimed in-browser.'};
  }
  const next=[imported,...imports].slice(0,24);setImports(next);localState.write(STORE,next);
 };
 return <section className='special-app r44-integration-hub'>
  <header className='special-head'><div><span>LOCAL ADAPTERS · DATA INTAKE · LANGUAGE ROUTING · DONOR BRIDGE</span><h2>Integration Hub</h2><p>A working sovereign edge for inspecting APIs, fingerprinting CSV/JSON/workbooks, compiling deterministic commands, and reaching the historical Site without granting it runtime authority.</p></div><Network/></header>
  <nav className='r44-integration-tabs'>{(['ADAPTERS','DATA','LEXICON','DONOR'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==='ADAPTERS'&&<div className='r44-adapter-stage'><header><div><b>Hosted adapter diagnostics</b><span>Tests execute real same-origin API requests and report returned status.</span></div><button className='primary-action' onClick={testAll} disabled={Boolean(testing)}><Play/>Test all</button></header><div className='r44-adapter-grid'>{ADAPTERS.map(a=>{const r=tests[a.id];return <article key={a.id} className={r?.ok?'pass':r?'fail':''}><header>{a.id==='earth'?<Globe2/>:a.id==='hybrid'?<Link2/>:<Cable/>}<span><b>{a.label}</b><small>{a.endpoint}</small></span>{r?.ok?<CheckCircle2/>:r?<XCircle/>:null}</header><p>{a.boundary}</p><footer><button onClick={()=>test(a)} disabled={testing===a.id}>{testing===a.id?'TESTING…':'RUN TEST'}</button><span>{r?r.ok?`${r.status} · ${r.ms} ms`:`${r.status||'OFFLINE'} · ${r.error}`:'NOT TESTED'}</span></footer>{r?.data&&<details><summary>Returned payload</summary><pre>{JSON.stringify(r.data,null,2).slice(0,2400)}</pre></details>}</article>})}</div></div>}
  {tab==='DATA'&&<div className='r44-data-stage'><label className='r44-drop'><Upload/><b>Inspect a local data artifact</b><span>CSV and JSON receive a bounded preview. XLS/XLSX receive byte identity and explicit spreadsheet-pipeline gating.</span><input type='file' accept='.csv,.json,.xlsx,.xls,text/csv,application/json' onChange={e=>{const f=e.target.files?.[0];if(f)void ingest(f);e.currentTarget.value=''}}/></label><div className='r44-import-list'>{imports.map(x=><article key={x.id}><header>{x.kind==='CSV'||x.kind==='XLSX'?<FileSpreadsheet/>:<FileJson/>}<span><b>{x.name}</b><small>{x.kind} · {x.size.toLocaleString()} bytes · {new Date(x.at).toLocaleString()}</small></span><strong>SHA-256</strong></header><code>{x.sha256}</code><div className='r44-import-metrics'><span>PREVIEW ROWS <b>{x.rows??'—'}</b></span><span>PREVIEW COLUMNS <b>{x.columns??'—'}</b></span><span>KEYS <b>{x.keys?.length??'—'}</b></span></div>{x.preview&&<div className='r44-import-preview'>{x.preview.map((r,i)=><div key={i}>{r.slice(0,8).map((c,j)=><span key={j}>{c.slice(0,90)}</span>)}</div>)}</div>}<footer><ShieldCheck/>{x.boundary}</footer></article>)}{!imports.length&&<p>No local artifacts fingerprinted in this browser yet.</p>}</div></div>}
  {tab==='LEXICON'&&<div className='r44-lexicon-stage'><label><Search/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder='Describe an OMEGA action…'/></label><div className='r44-lexicon-result'><header><Workflow/><span><small>DETERMINISTIC ROUTE · {Math.round(language.confidence*100)}% vocabulary match</small><b>{language.route}</b></span><button className='primary-action' onClick={()=>onNavigate(language.route)}>Open route</button></header><div className='r44-token-row'>{language.tokens.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div><h3>Operator chain</h3><div className='r44-chain'>{language.operators.map(x=><b key={x}>{x}</b>)}</div><h3>Full command path</h3><div className='r44-chain command'>{language.commandChain.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div><footer><ShieldCheck/>{language.boundary}</footer></div></div>}
  {tab==='DONOR'&&<div className='r44-donor-stage'><div><span>HISTORICAL SITE APPLICATION · B058/V91 DONOR</span><h3>OMEGA Sovereign Runtime</h3><p>The earlier Site remains useful as a compact command, device, Earth and runtime reference. This release borrows proven interaction ideas but does not fork state, deploy authority or truth into that donor.</p><a href='https://omega-sovereign-runtime.foundasound.chatgpt.site' target='_blank' rel='noreferrer'><Link2/>Open donor Site</a></div><aside><Database/><b>Authority relationship</b><dl><dt>Canonical product</dt><dd>OMEGAv6 GitHub / Cloudflare runtime</dd><dt>Donor role</dt><dd>interaction and control-surface reference</dd><dt>State mutation</dt><dd>not permitted across the link</dd><dt>External proof</dt><dd>must return through current adapters and ledger</dd></dl></aside></div>}
  <footer className='r44-integration-boundary'><ShieldCheck/><span><b>Integration boundary</b>Local adapters can test, parse, fingerprint, preview and route. They do not install arbitrary code, execute workbook macros, grant providers authority, prove a device action, or convert donor output into canonical evidence without explicit admission.</span></footer>
 </section>
}
