import {useEffect,useMemo,useState} from 'react';
import {Activity,Database,GitCommitHorizontal,Globe2,RefreshCw,ShieldCheck,Waypoints} from 'lucide-react';
import {api} from './platformAdapter';
import './omegaWorldContinuityR125.css';

type Props={address:number};
const fmt=(v:any,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
function latLon(address:number){const a=Math.max(0,Math.min(20735,Math.floor(address))),d=Math.floor(a/1728),p=Math.floor(a/144)%12,r=Math.floor(a/12)%12;return{lat:-90+(d+.5)/12*180,lon:-180+(p*12+r+.5)/144*360}}
export default function OmegaWorldContinuityR125({address}:Props){
 const[manifest,setManifest]=useState<any>(null),[organism,setOrganism]=useState<any>(null),[projection,setProjection]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const geo=useMemo(()=>latLon(address),[address]);
 const load=async()=>{setBusy(true);setMessage('');try{const[m,o,p]=await Promise.all([api.get<any>('/api/world/manifest'),api.get<any>('/api/world/organism'),api.get<any>(`/api/world/project?address=${address}&observer=OMEGA_OPERATOR&projection=CONVERGENCE`)]);setManifest(m.data);setOrganism(o.data);setProjection(p.data)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[address]);
 const ingestEarth=async()=>{setBusy(true);setMessage('');try{const r=await api.post<any>('/api/world/observe/earth',{lat:geo.lat,lon:geo.lon,address,observerId:'OMEGA_OPERATOR',projection:'EARTH'});setMessage(r.data?.deduped?'Earth evidence already exists in the causal ledger.':'Returned Earth evidence appended to the persistent ledger as SOURCE_RETURNED_NOT_ADMITTED.');await load()}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const syncSwarm=async()=>{setBusy(true);setMessage('');try{const r=await api.post<any>('/api/world/sync/swarm',{});setMessage(`Swarm continuity sync complete · ${r.data?.ingested??0} new returned mission packet(s).`);await load()}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const world=organism?.world,ledger=world?.ledger||projection?.ledger||{},canonical=world?.canonical||projection?.canonical||{},recent=projection?.recent||[],swarm=organism?.swarm,selfBuild=organism?.selfBuild,sovereign=organism?.sovereign;
 return <section className='r125-world' aria-label='OMEGA persistent world continuity'>
  <header className='r125-world-head'><div><span>R125 · PERSISTENT WORLD / CAUSAL CONTINUITY</span><h2>One canonical world · many lawful projections · recoverable path</h2><p>Earth evidence, swarm results, observer-relative views, self-build lineage, federation state and proof references can now meet in one durable ledger without pretending that returned data or model output is automatically CanonState.</p></div><div className='r125-world-actions'><button onClick={()=>void ingestEarth()} disabled={busy}><Globe2/>INGEST CURRENT EARTH</button><button onClick={()=>void syncSwarm()} disabled={busy}><Waypoints/>SYNC SWARM</button><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/>REFRESH</button></div></header>
  <div className='r125-world-law'><ShieldCheck/><b>{manifest?.worldLaw||'ONE CANONICAL WORLD / MANY LAWFUL PROJECTIONS / PERSISTENT CAUSAL PATH'}</b><small>Public admission is forbidden. Returned evidence and computation remain lineage-bearing candidates until proof-gated internal admission.</small></div>
  <div className='r125-world-grid'>
   <article><header><Database/><span><b>CANONICAL WORLD</b><small>durable identity + admitted state only</small></span></header><strong>v{canonical?.version??0}</strong><dl><div><dt>ADDRESS</dt><dd>{canonical?.address??0} / 20,736</dd></div><div><dt>HOST</dt><dd>{canonical?.host||'OMEGA_CANON'}</dd></div><div><dt>SCAR HEAD</dt><dd>{canonical?.scarHead?String(canonical.scarHead).slice(0,16):'GENESIS'}</dd></div></dl></article>
   <article><header><GitCommitHorizontal/><span><b>CAUSAL LEDGER</b><small>hash-chained observation / proposal / proof history</small></span></header><strong>{ledger?.eventCount??0}</strong><dl><div><dt>PENDING</dt><dd>{ledger?.pending??0}</dd></div><div><dt>ADMITTED</dt><dd>{ledger?.admitted??0}</dd></div><div><dt>HEAD</dt><dd>{ledger?.head?String(ledger.head).slice(0,16):'GENESIS'}</dd></div></dl></article>
   <article><header><Activity/><span><b>ORGANISM BODY</b><small>1 → 12 → 144 → 1,728 → 20,736</small></span></header><strong>{swarm?.active??0} active</strong><dl><div><dt>MISSIONS</dt><dd>{Array.isArray(swarm?.missions)?swarm.missions.length:0}</dd></div><div><dt>SELF-BUILD</dt><dd>G{selfBuild?.generation??'—'} · {selfBuild?.active?'ACTIVE':'IDLE'}</dd></div><div><dt>SOVEREIGN</dt><dd>{sovereign?.nativeExecutionClaimed?'HEARTBEAT CLAIM PRESENT':'NOT PROVEN HERE'}</dd></div></dl></article>
   <article><header><Waypoints/><span><b>OBSERVER FRAME</b><small>projection does not replace canonical existence</small></span></header><strong>{address}</strong><dl><div><dt>EARTH MAP</dt><dd>{geo.lat.toFixed(2)}°, {geo.lon.toFixed(2)}°</dd></div><div><dt>CΩ / Φ</dt><dd>{fmt(canonical?.metrics?.continuity)} / {fmt(canonical?.metrics?.plasticity)}</dd></div><div><dt>q / Λ / U</dt><dd>{fmt(canonical?.metrics?.contradiction)} / {fmt(canonical?.metrics?.burden)} / {fmt(canonical?.metrics?.uncertainty)}</dd></div></dl></article>
  </div>
  <section className='r125-world-trace'><header><span>RECENT WORLD TRACE</span><b>Every transform keeps a previous-hash path</b></header>{recent.length?<div>{recent.slice(0,8).map((e:any)=><article key={e.hash}><span>{e.seq} · {e.type}</span><b>{e.host||'OMEGA'} · {e.kind||'STATE'}</b><small>{e.summary||e.authority||'No summary returned'}</small><code>{String(e.hash||'').slice(0,20)} ← {String(e.previousHash||'').slice(0,20)}</code></article>)}</div>:<p>No returned world events have been appended yet. The canonical container exists without fabricating observations.</p>}</section>
  {message&&<p className='r125-world-message'>{message}</p>}
 </section>
}
