import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,BrainCircuit,GitBranch,Pause,Play,RefreshCw,RotateCcw,ShieldCheck,Square,TreePine} from 'lucide-react';
import {api} from './platformAdapter';
import './omegaOrganismR123.css';

type Mode='SOLO'|'FLOCK'|'TREE'|'PIPELINE'|'CONSENSUS'|'MIRROR'|'FULL';
const MODES:Mode[]=['SOLO','FLOCK','TREE','PIPELINE','CONSENSUS','MIRROR','FULL'];
const ROLES=['ORCHESTRATION','SOFTWARE','RESEARCH','MATHEMATICS','PHYSICS','VISUAL','DATA','FORECAST','TOOLS','SOVEREIGN','PROOF','COORDINATION'];
const DEFAULTS:Record<Mode,number>={SOLO:1,FLOCK:24,TREE:144,PIPELINE:12,CONSENSUS:12,MIRROR:2,FULL:1728};
const pad=(n:number)=>String(n+1).padStart(2,'0');
const pct=(a:number,b:number)=>b?Math.min(100,Math.max(0,a/b*100)):0;

export default function OmegaOrganismR123(){
 const worldSynced=useRef(new Set<string>());
 const[manifest,setManifest]=useState<any>(null),[status,setStatus]=useState<any>(null),[mission,setMission]=useState<any>(null),[plan,setPlan]=useState<any>(null),[mode,setMode]=useState<Mode>('TREE'),[cells,setCells]=useState(144),[providerBudget,setProviderBudget]=useState(6),[branchConcurrency,setBranchConcurrency]=useState(4),[deadlineMin,setDeadlineMin]=useState(15),[intent,setIntent]=useState('Use the OMEGA organism hierarchy to partition this objective from seed to organ to branch to cell, preserve invariant and scar carry, compare independent specialist results, and reconverge only what the returned evidence supports.'),[evidenceText,setEvidenceText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[inspector,setInspector]=useState<any>(null);
 const active=mission&&['QUEUED','RUNNING'].includes(mission.status),paused=mission?.status==='PAUSED';
 const load=async()=>{try{const[m,s]=await Promise.all([api.get<any>('/api/swarm/organism/manifest'),api.get<any>('/api/swarm/organism/status')]);setManifest(m.data);setStatus(s.data);if(mission?.id){const r=await api.get<any>(`/api/swarm/organism/missions/${mission.id}`);if(r.data?.mission)setMission(r.data.mission)}}catch(e:any){setMessage(e?.message||String(e))}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!active)return;const id=window.setInterval(()=>void load(),1500);return()=>window.clearInterval(id)},[active,mission?.id]);
 useEffect(()=>setCells(DEFAULTS[mode]),[mode]);
 useEffect(()=>{const terminal=mission&&['COMPLETE','FAILED','TIMED_OUT','CANCELLED'].includes(mission.status);if(!terminal||!mission?.id||worldSynced.current.has(mission.id))return;worldSynced.current.add(mission.id);const total=Number(mission.totalCells||0),failed=Number(mission.failedCells||0),completed=Number(mission.completedCells||0),key=`swarm:${mission.id}:${mission.merkleRoot||mission.status}`;void api.post<any>('/api/world/propose',{host:'SWARM',kind:'SWARM_RETURN',address:Number(mission.seed)||0,projection:'CONVERGENCE',metrics:{continuity:total?completed/total:0,plasticity:.5,contradiction:total?failed/total:0,burden:total?Math.min(1,total/1728):0,evidence:Array.isArray(mission.evidence)&&mission.evidence.length?.7:.25,uncertainty:failed?.7:.35,scar:Number(mission.failedBranches||0)/Math.max(1,Number(mission.totalBranches||1))},evidenceRefs:(mission.evidence||[]).map((x:any)=>x.sha256||x.id).filter(Boolean),proofRefs:[mission.merkleRoot].filter(Boolean),sourceRefs:[`swarm:${mission.id}`],summary:mission.finalSynthesis?.text||`${mission.status} organism mission ${mission.id}`,payload:{missionId:mission.id,status:mission.status,totalCells:mission.totalCells,completedCells:mission.completedCells,failedCells:mission.failedCells,totalBranches:mission.totalBranches,completedBranches:mission.completedBranches,failedBranches:mission.failedBranches,proofState:mission.proofState,authority:mission.authority,finalSynthesis:mission.finalSynthesis||null},dedupeKey:key,truthBoundary:'Organism output and Merkle receipts are retained as returned computation and remain non-canonical until the OMEGAv6 proof/admission boundary admits them.'}).catch(()=>{worldSynced.current.delete(mission.id)})},[mission?.id,mission?.status,mission?.merkleRoot]);
 const evidence=useMemo(()=>evidenceText.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,16).map((summary,i)=>({id:`operator-${i+1}`,type:'OPERATOR_CONTEXT',summary,authority:'OPERATOR_SUPPLIED_NOT_INDEPENDENTLY_VERIFIED'})),[evidenceText]);
 const launch=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('');try{const r=await api.post<any>('/api/swarm/organism/missions',{intent,mode,requestedCells:mode==='FULL'?1728:cells,providerBudget,genesisBudget:1,opticalBudget:1,branchConcurrency,deadlineMs:deadlineMin*60_000,maxDeterministicRetries:1,reconvergeWithAI:providerBudget>0,evidence});setMission(r.data?.mission);setPlan(r.data?.plan);setMessage('Organism mission accepted: seed → organ → branch → cell. Returned work remains non-canonical until normal OMEGA proof/admission.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const act=async(action:'pause'|'resume'|'cancel'|'replay'|'tick')=>{if(!mission?.id||busy)return;setBusy(true);try{const r=await api.post<any>(`/api/swarm/organism/missions/${mission.id}/${action}`,{});if(action==='replay'){setMission(r.data?.mission);setPlan(r.data?.plan||plan)}else if(r.data?.mission)setMission(r.data.mission)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const inspectOrgan=async(d:number)=>{try{const r=await api.get<any>(`/api/swarm/organism/organs/${d}`);setInspector({kind:'ORGAN',domain:d,role:ROLES[d],data:r.data})}catch(e:any){setInspector({kind:'ORGAN',domain:d,error:e?.message||String(e)})}};
 const inspectBranch=async(d:number,p:number)=>{try{const r=await api.get<any>(`/api/swarm/organism/branches/${d}/${p}`);setInspector({kind:'BRANCH',domain:d,phase:p,role:ROLES[d],data:r.data})}catch(e:any){setInspector({kind:'BRANCH',domain:d,phase:p,error:e?.message||String(e)})}};
 const target=mission?.organ?.target||plan?.organBranchCounts||Array(12).fill(0),done=mission?.organ?.completed||Array(12).fill(0),failed=mission?.organ?.failed||Array(12).fill(0),cellProgress=mission?mission.completedCells+mission.failedCells:0,total=mission?.totalCells||plan?.requestedCells||0;
 return <section className='r123-organism' aria-label='OMEGA organism swarm hierarchy'>
  <header className='r123-hero'><div><span>R123 · ORGANISM EXECUTION FABRIC</span><h2>Seed → 12 Organs → 144 Branches → 1,728 Cells</h2><p>The swarm now has an actual operator chain instead of a flat fan-out. Root state delegates through persistent organ and branch identities, branches drive independently addressable cells, then receipts reconverge upward through a Merkle-rooted proof boundary.</p></div><div className='r123-badge'><TreePine/><b>{manifest?.runtimeRevision||'R123'}</b><small>{status?.active??0} active organism missions</small></div></header>
  <div className='r123-path'><article><BrainCircuit/><b>1 SEED</b><small>intent · global mission state</small></article><i>→</i><article><Activity/><b>12 ORGANS</b><small>persistent capability domains</small></article><i>→</i><article><GitBranch/><b>144 BRANCHES</b><small>domain × phase isolation</small></article><i>→</i><article><TreePine/><b>1,728 CELLS</b><small>independent state + scar + receipts</small></article><i>→</i><article><ShieldCheck/><b>20,736 LANES</b><small>addressed execution resolution</small></article></div>
  <section className='r123-launch'><label className='r123-intent'><span>OPERATOR SEED / OBJECTIVE</span><textarea value={intent} onChange={e=>setIntent(e.target.value)}/></label><div className='r123-config'><label><span>TOPOLOGY</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>CELLS</span><input type='number' min='1' max='1728' disabled={mode==='FULL'} value={mode==='FULL'?1728:cells} onChange={e=>setCells(Math.max(1,Math.min(1728,Number(e.target.value)||1)))}/></label><label><span>TOTAL AI BUDGET</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label><label><span>BRANCH CONCURRENCY</span><input type='number' min='1' max='12' value={branchConcurrency} onChange={e=>setBranchConcurrency(Math.max(1,Math.min(12,Number(e.target.value)||1)))}/></label><label><span>DEADLINE MIN</span><input type='number' min='1' max='30' value={deadlineMin} onChange={e=>setDeadlineMin(Math.max(1,Math.min(30,Number(e.target.value)||1)))}/></label></div><label className='r123-evidence'><span>EVIDENCE / CONTEXT PACKETS · ONE PER LINE</span><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} placeholder='Optional operator-supplied context. Each line stays explicitly labeled as unverified unless backed by a proof receipt.'/><small>{evidence.length}/16 packets</small></label><div className='r123-actions'><button className='prime' onClick={()=>void launch()} disabled={busy||!intent.trim()}><Play/>LAUNCH ORGANISM</button><button onClick={()=>void load()}><RefreshCw/>REFRESH</button>{active&&<button onClick={()=>void act('pause')}><Pause/>PAUSE</button>}{paused&&<button onClick={()=>void act('resume')}><Play/>RESUME</button>}{mission&&!['COMPLETE','FAILED','CANCELLED'].includes(mission.status)&&<button onClick={()=>void act('cancel')}><Square/>CANCEL</button>}{mission&&['COMPLETE','FAILED','CANCELLED','TIMED_OUT'].includes(mission.status)&&<button onClick={()=>void act('replay')}><RotateCcw/>REPLAY</button>}</div>{message&&<p className='r123-message'>{message}</p>}</section>
  {mission&&<section className='r123-mission'><header><div><span>MISSION</span><b>{mission.id}</b><strong data-state={mission.status}>{mission.status}</strong></div><div><small>{mission.completedCells||0} complete</small><small>{mission.failedCells||0} failed</small><small>{mission.queueDepth||0} branches queued</small></div></header><div className='r123-bar'><i style={{width:`${pct(cellProgress,total)}%`}}/></div><div className='r123-receipt'><span>PROOF STATE</span><b>{mission.proofState}</b><small>{mission.merkleRoot?`organism Merkle ${mission.merkleRoot}`:'Merkle root will seal after reconvergence'}</small></div>{mission.finalSynthesis&&<div className='r123-synthesis'><span>RECONVERGED MODEL SYNTHESIS · {mission.finalSynthesis.authority}</span><p>{mission.finalSynthesis.text}</p></div>}</section>}
  <section className='r123-organs'><header><div><span>PERSISTENT ORGAN LAYER</span><b>Twelve semi-independent capability bodies</b><small>Click an organ or branch to inspect its own durable state. A degraded organ does not erase the rest of the body.</small></div></header><div className='r123-organ-grid'>{ROLES.map((role,d)=>{const t=Number(target[d]||0),ok=Number(done[d]||0),bad=Number(failed[d]||0);return <article key={role}><button className='r123-organ-head' onClick={()=>void inspectOrgan(d)}><span>{pad(d)} · ORGAN</span><b>{role}</b><small>{ok}/{t} branches · {bad} failed</small></button><div className='r123-organ-bar'><i style={{width:`${pct(ok+bad,t)}%`}}/></div><div className='r123-branches'>{Array.from({length:12},(_,p)=><button key={p} title={`${role} branch ${pad(p)}`} onClick={()=>void inspectBranch(d,p)} data-active={t? 'true':'false'}><i/></button>)}</div></article>})}</div></section>
  {inspector&&<section className='r123-inspector'><header><div><span>{inspector.kind} INSPECTOR</span><b>{inspector.role||'OMEGA'}{inspector.phase!==undefined?` · branch ${pad(inspector.phase)}`:''}</b></div><button onClick={()=>setInspector(null)}>CLOSE</button></header><pre>{JSON.stringify(inspector.data||{error:inspector.error},null,2)}</pre></section>}
  <footer className='r123-boundary'><ShieldCheck/><div><b>AUTHORITY BOUNDARY</b><span>Every cell result, branch Merkle root, organ ledger, organism synthesis and R125 world-ledger handoff remains a result packet. OMEGAv6 proof/admission is still the only canonical-state authority.</span></div></footer>
 </section>
}
