import {useEffect,useMemo,useState} from 'react';
import {Activity,BrainCircuit,GitBranch,Link,Pause,Play,RefreshCw,Route,ShieldCheck,Square,Target} from 'lucide-react';
import {api} from './platformAdapter';
import './omegaAutonomicR125.css';

type Scope='BODY'|'ORGAN'|'BRANCH'|'CELL';
type Mode='AUTO'|'SOLO'|'FLOCK'|'TREE'|'PIPELINE'|'CONSENSUS'|'MIRROR'|'FULL';
const SCOPES:Scope[]=['BODY','ORGAN','BRANCH','CELL'];
const MODES:Mode[]=['AUTO','SOLO','FLOCK','TREE','PIPELINE','CONSENSUS','MIRROR','FULL'];
const ROLES=['ORCHESTRATION','SOFTWARE','RESEARCH','MATHEMATICS','PHYSICS','VISUAL','DATA','FORECAST','TOOLS','SOVEREIGN','PROOF','COORDINATION'];
const pct=(v:number)=>`${Math.round(Math.max(0,Math.min(1,v))*100)}%`;

export default function OmegaAutonomicR125(){
 const[manifest,setManifest]=useState<any>(null),[status,setStatus]=useState<any>(null),[plan,setPlan]=useState<any>(null),[mission,setMission]=useState<any>(null),[checkpoint,setCheckpoint]=useState<any>(null),[mode,setMode]=useState<Mode>('AUTO'),[scope,setScope]=useState<Scope>('BODY'),[domain,setDomain]=useState(1),[phase,setPhase]=useState(0),[regulation,setRegulation]=useState(0),[providerBudget,setProviderBudget]=useState(6),[intent,setIntent]=useState('Route this objective across the strongest OMEGA capabilities, detach only the necessary organ/branch/cell when useful, preserve evidence and scars, then return a proof-bounded result that can rejoin the full body.'),[metrics,setMetrics]=useState({continuity:.72,plasticity:.65,contradiction:.22,burden:.35,evidence:.55,uncertainty:.45,scar:.18}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const active=mission&&['QUEUED','RUNNING'].includes(mission.status),paused=mission?.status==='PAUSED',detached=mission?.detached===true;
 const payload=useMemo(()=>({intent,mode,scope:{type:scope,domain,phase,regulation},providerBudget,metrics,reconvergeWithAI:providerBudget>0,allowFullAuto:false}),[intent,mode,scope,domain,phase,regulation,providerBudget,metrics]);
 const load=async()=>{try{const[m,s]=await Promise.all([api.get<any>('/api/swarm/autonomic/manifest'),api.get<any>('/api/swarm/autonomic/status')]);setManifest(m.data);setStatus(s.data);if(mission?.id){const r=await api.get<any>(`/api/swarm/autonomic/missions/${mission.id}`);if(r.data?.mission)setMission(r.data.mission)}}catch(e:any){setMessage(e?.message||String(e))}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!active)return;const id=window.setInterval(()=>void load(),1400);return()=>window.clearInterval(id)},[active,mission?.id]);
 const preview=async()=>{if(!intent.trim()||busy)return;setBusy(true);try{const r=await api.post<any>('/api/swarm/autonomic/plan',payload);setPlan(r.data?.plan);setMessage('Autonomic plan computed only; nothing has been queued or admitted.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const launch=async()=>{if(!intent.trim()||busy)return;setBusy(true);try{const r=await api.post<any>('/api/swarm/autonomic/missions',payload);setPlan(r.data?.plan);setMission(r.data?.mission);setCheckpoint(null);setMessage('Autonomic mission queued. Routing authority remains execution-only; CanonState is unchanged.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const action=async(a:'pause'|'resume'|'cancel'|'tick')=>{if(!mission?.id||busy)return;setBusy(true);try{const r=await api.post<any>(`/api/swarm/autonomic/missions/${mission.id}/${a}`,{});if(r.data?.mission)setMission(r.data.mission)}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const getCheckpoint=async()=>{if(!mission?.id)return;try{const r=await api.get<any>(`/api/swarm/autonomic/missions/${mission.id}/checkpoint`);setCheckpoint(r.data)}catch(e:any){setMessage(e?.message||String(e))}};
 const rejoin=async()=>{if(!mission?.id||!detached||mission.status!=='COMPLETE'||busy)return;setBusy(true);try{const r=await api.post<any>(`/api/swarm/autonomic/missions/${mission.id}/rejoin`,{providerBudget:Math.min(4,providerBudget),mode:'TREE'});setMessage(r.data?.ok?`Detached receipt re-entered the full organism as evidence. New organism mission: ${r.data?.data?.mission?.id||'created'}`:'Rejoin was not accepted.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const setMetric=(k:keyof typeof metrics,v:string)=>setMetrics(x=>({...x,[k]:Math.max(0,Math.min(1,Number(v)||0))}));
 return <section className='r125-auto' aria-label='OMEGA autonomic swarm controller'>
  <header className='r125-hero'><div><span>R125 · AUTONOMIC SWARM CONTROL</span><h2>Route the body. Detach a limb. Rejoin with receipts.</h2><p>This layer turns the 1→12→144→1,728 hierarchy into a scope-aware execution system. It can plan against continuity, contradiction, burden, evidence, uncertainty and scar; isolate a body/organ/branch/cell scope; checkpoint returned state; then carry a detached receipt back into the organism as evidence.</p></div><div className='r125-runtime'><Route/><b>{manifest?.runtimeRevision||'R125'}</b><small>{status?.active??0} active</small></div></header>
  <section className='r125-console'><label className='r125-intent'><span>MISSION INTENT</span><textarea value={intent} onChange={e=>setIntent(e.target.value)}/></label><div className='r125-routing'><label><span>ROUTER</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>SCOPE</span><select value={scope} onChange={e=>setScope(e.target.value as Scope)}>{SCOPES.map(x=><option key={x}>{x}</option>)}</select></label>{scope!=='BODY'&&<label><span>ORGAN</span><select value={domain} onChange={e=>setDomain(Number(e.target.value))}>{ROLES.map((x,i)=><option key={x} value={i}>{String(i+1).padStart(2,'0')} · {x}</option>)}</select></label>}{(scope==='BRANCH'||scope==='CELL')&&<label><span>PHASE 0–11</span><input type='number' min='0' max='11' value={phase} onChange={e=>setPhase(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}{scope==='CELL'&&<label><span>REGULATION 0–11</span><input type='number' min='0' max='11' value={regulation} onChange={e=>setRegulation(Math.max(0,Math.min(11,Number(e.target.value)||0)))}/></label>}<label><span>TOTAL AI BUDGET</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label></div>
   <div className='r125-metrics'>{(Object.keys(metrics) as (keyof typeof metrics)[]).map(k=><label key={k}><span>{k.toUpperCase()} · {metrics[k].toFixed(2)}</span><input type='range' min='0' max='1' step='.01' value={metrics[k]} onChange={e=>setMetric(k,e.target.value)}/></label>)}</div>
   <div className='r125-actions'><button onClick={()=>void preview()} disabled={busy||!intent.trim()}><Target/>PREVIEW ROUTE</button><button className='prime' onClick={()=>void launch()} disabled={busy||!intent.trim()}><Play/>EXECUTE ROUTE</button><button onClick={()=>void load()}><RefreshCw/>REFRESH</button>{active&&<button onClick={()=>void action('pause')}><Pause/>PAUSE</button>}{paused&&<button onClick={()=>void action('resume')}><Play/>RESUME</button>}{mission&&!['COMPLETE','FAILED','CANCELLED','TIMED_OUT'].includes(mission.status)&&<button onClick={()=>void action('cancel')}><Square/>CANCEL</button>}{mission&&<button onClick={()=>void getCheckpoint()}><ShieldCheck/>CHECKPOINT</button>}{detached&&mission?.status==='COMPLETE'&&<button onClick={()=>void rejoin()} disabled={busy}><Link/>REJOIN BODY</button>}</div>{message&&<p className='r125-message'>{message}</p>}
  </section>
  {plan&&<section className='r125-plan'><header><div><span>AUTONOMIC PLAN</span><b>{plan.projection} · {plan.decision}</b></div><strong>{plan.detached?'DETACHED SCOPE':'BODY SCOPE'}</strong></header><div className='r125-kpis'><article><span>SCOPE</span><b>{plan.scope?.type}</b><small>{plan.scope?.type==='BODY'?'whole execution fabric':`${ROLES[plan.scope?.domain]||'scoped unit'} ${plan.scope?.phase??''}`}</small></article><article><span>CELLS</span><b>{plan.totalCells}</b><small>{plan.totalBranches} branches</small></article><article><span>CONCURRENCY</span><b>{plan.branchConcurrency}</b><small>bounded branch fan-out</small></article><article><span>AI BUDGET</span><b>{plan.budgets?.providerTotal}</b><small>{plan.budgets?.providerCells} cell + {plan.budgets?.reconvergence} reconvergence</small></article></div>{plan.buildCapsule&&<div className='r125-build'><span>R124 SELF-BUILD HANDOFF</span><b>{plan.buildCapsule.status}</b><p>{plan.buildCapsule.objective}</p><small>Candidate only. No repository mutation is performed by the autonomic router.</small></div>}</section>}
  {mission&&<section className='r125-mission'><header><div><span>MISSION</span><b>{mission.id}</b><strong>{mission.status}</strong></div><small>{mission.completedCells||0}/{mission.totalCells||0} cells · {mission.failedCells||0} failed</small></header><div className='r125-bar'><i style={{width:pct((mission.completedCells+mission.failedCells)/Math.max(1,mission.totalCells))}}/></div>{mission.quorum&&<div className='r125-quorum'><article><span>CELL EXECUTION QUORUM</span><b>{pct(mission.quorum.cellSuccess)}</b></article><article><span>BRANCH EXECUTION QUORUM</span><b>{pct(mission.quorum.branchSuccess)}</b></article><article><span>HASHED EVIDENCE</span><b>{pct(mission.quorum.evidenceHashCoverage)}</b></article><small>{mission.quorum.authority}</small></div>}<div className='r125-proof'><span>PROOF STATE</span><b>{mission.proofState}</b><small>{mission.merkleRoot||'Merkle root pending'}</small></div>{mission.finalSynthesis&&<div className='r125-synthesis'><span>{mission.finalSynthesis.authority}</span><p>{mission.finalSynthesis.text}</p></div>}</section>}
  {checkpoint&&<section className='r125-checkpoint'><BrainCircuit/><div><span>CHECKPOINT</span><b>{checkpoint.checkpointSha256}</b><small>{checkpoint.status} · {checkpoint.proofState} · CanonState mutation false</small></div></section>}
  <footer className='r125-boundary'><ShieldCheck/><div><b>MAXIMUM CAPACITY WITH GOVERNED AUTONOMY</b><span>AUTO may escalate aggressively but does not silently spend all 1,728 cells; FULL remains an explicit operator mode unless full-auto is explicitly enabled. Execution quorum measures successful returned work, not factual truth. Detached receipts rejoin as evidence, never as automatic CanonState.</span></div></footer>
 </section>
}
