import {useEffect,useMemo,useState} from 'react';
import {Activity,BrainCircuit,CheckCircle2,CirclePause,GitBranch,MemoryStick,Network,Play,RefreshCw,RotateCcw,ShieldCheck,Sparkles,Workflow} from 'lucide-react';
import './omegaCortexR127.css';

type Props={record?:any;state?:any};
type Mode='ADAPTIVE'|'SOLO'|'ORGAN'|'BRANCH'|'FLOCK'|'BODY'|'FULL';
const MODES:Mode[]=['ADAPTIVE','SOLO','ORGAN','BRANCH','FLOCK','BODY','FULL'];
const safe=async(path:string,init?:RequestInit)=>{try{const r=await fetch(path,{cache:'no-store',...init,headers:{'cache-control':'no-cache',...(init?.body?{'content-type':'application/json'}:{}),...(init?.headers||{})}}),data=await r.json().catch(()=>null);return{ok:r.ok,status:r.status,data}}catch(error:any){return{ok:false,status:0,data:null,error:error?.message||String(error)}}};
const status=(v:any)=>String(v??'UNPROVEN').toUpperCase();

export default function OmegaCortexR127({record,state}:Props){
 const[intent,setIntent]=useState('Operate as one organized body: frame the mission, distribute bounded specialist work across the OMEGA cell lattice, exchange candidate results through causal dependencies, cross-check contradictions at branch level, synthesize at organ level, preserve scar/history and evidence authority, then reconverge into one proof-bounded return packet without treating execution agreement as truth.');
 const[mode,setMode]=useState<Mode>('ADAPTIVE'),[providerBudget,setProviderBudget]=useState(8),[allowFullAuto,setAllowFullAuto]=useState(false),[projection,setProjection]=useState('CONVERGENCE'),[plan,setPlan]=useState<any>(null),[mission,setMission]=useState<any>(null),[memory,setMemory]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[checkpoint,setCheckpoint]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('R127 cortex ready to compile a living task graph.');
 const metrics=record?.metrics??state?.metrics??{plasticity:.6,uncertainty:.5,contradiction:.2,evidence:.5,burden:.3};
 const payload=useMemo(()=>({intent,mode,projection,providerBudget,allowFullAuto,metrics}),[intent,mode,projection,providerBudget,allowFullAuto,metrics]);
 const refreshMission=async(id=mission?.id)=>{if(!id)return;const r=await safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}`);if(r.data?.mission)setMission(r.data.mission);if(r.data?.mission?.status==='COMPLETE'||r.data?.mission?.status==='RUNNING'){const [mem,ev]=await Promise.all([safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}/memory?limit=36`),safe(`/api/swarm/cortex/missions/${encodeURIComponent(id)}/events`)]);setMemory(mem.data?.memory??[]);setEvents(ev.data?.events??[])}};
 useEffect(()=>{if(!mission?.id||!['QUEUED','RUNNING'].includes(mission.status))return;const id=window.setInterval(()=>void refreshMission(mission.id),1400);return()=>window.clearInterval(id)},[mission?.id,mission?.status]);
 const preview=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Compiling causal body graph…');const r=await safe('/api/swarm/cortex/plan',{method:'POST',body:JSON.stringify(payload)});setPlan(r.data?.plan??null);setMessage(r.ok?'Cortex graph compiled. No task execution or CanonState admission occurred.':`Cortex plan unavailable (${r.status||'network'}).`);setBusy(false)};
 const execute=async()=>{if(!intent.trim()||busy)return;setBusy(true);setMessage('Creating durable cortex mission…');const r=await safe('/api/swarm/cortex/missions',{method:'POST',body:JSON.stringify(payload)});if(r.data?.mission)setMission(r.data.mission);if(r.data?.plan)setPlan(r.data.plan);setMessage(r.ok?'Durable organism mission created. The cortex will advance in bounded waves.':'Cortex execution was not accepted; no execution is claimed.');setBusy(false)};
 const action=async(name:'advance'|'pause'|'resume'|'checkpoint'|'rejoin')=>{if(!mission?.id||busy)return;setBusy(true);const method=name==='checkpoint'?'GET':'POST',r=await safe(`/api/swarm/cortex/missions/${encodeURIComponent(mission.id)}/${name}`,{method,body:method==='POST'?JSON.stringify(name==='advance'?{batchSize:24}:{}):undefined});if(r.data?.mission)setMission(r.data.mission);if(r.data?.checkpoint)setCheckpoint(r.data.checkpoint);setMessage(r.ok?`Cortex ${name} completed.`:`Cortex ${name} failed (${r.status||'network'}).`);await refreshMission(mission.id);setBusy(false)};
 const p=plan??{};const m=mission??{};const waves=p.waves??[];
 return <section className='r127-cortex'>
  <header className='r127-head'><div><span>R127 · SYNAPTIC ORGANISM CORTEX</span><h3>1,728 independent cells that can behave as one causal body.</h3><p>This layer is the missing connective tissue: mission graph, causal dependencies, shared candidate memory, branch error-correction, organ synthesis, bounded model use, scar carry, checkpoints and proof-bounded return.</p></div><div className='r127-badge'><BrainCircuit/><b>OMEGA CORTEX</b><small>execution fabric · not canonical authority</small></div></header>
  <section className='r127-topology'>{[['SEED','1'],['ORGANS','12'],['BRANCHES','144'],['CELLS','1,728'],['LANES','20,736']].map(([k,v],i)=><article key={k}><span>{k}</span><b>{v}</b>{i<4&&<i>→</i>}</article>)}</section>
  <section className='r127-main'><div className='r127-compose'><label><span>BODY OBJECTIVE</span><textarea value={intent} onChange={e=>setIntent(e.target.value)}/></label><div className='r127-controls'><label><span>TOPOLOGY</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>PROJECTION</span><select value={projection} onChange={e=>setProjection(e.target.value)}>{['CONVERGENCE','FIELD','MATTER','TRAVERSAL','FORECAST','RELATIVITY','INFINITY','SCALE','EARTH','OPTICAL','PROOF','BUILD'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>MODEL BUDGET · 0–12</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label><label className='r127-check'><input type='checkbox' checked={allowFullAuto} onChange={e=>setAllowFullAuto(e.target.checked)}/><div><span>FULL AUTO 1,728</span><small>Explicit opt-in. FULL/BODY mode is also explicit operator intent.</small></div></label></div><div className='r127-actions'><button onClick={()=>void preview()} disabled={busy}><Workflow/>COMPILE BODY GRAPH</button><button className='prime' onClick={()=>void execute()} disabled={busy}><Play/>START LIVING MISSION</button></div><p className='r127-message'>{message}</p></div>
  <aside className='r127-plan'><header><span>COMPILED CORTEX</span><b>{p.mode??mode} · {p.projection??projection}</b></header><div className='r127-planstats'><article><span>SELECTED CELLS</span><b>{p.selectedCellCount??'—'}</b></article><article><span>TOTAL TASKS</span><b>{p.totalTaskCount??'—'}</b></article><article><span>BRANCH CHECKS</span><b>{p.totalBranchChecks??'—'}</b></article><article><span>ORGAN SYNTHESIS</span><b>{p.totalOrganSyntheses??'—'}</b></article></div><div className='r127-waves'>{waves.map((w:any)=><div key={w.wave}><i>{w.wave}</i><span>{['FRAME','CELL WORK','BRANCH CROSSCHECK','ORGAN SYNTHESIS','PROOF RETURN'][w.wave]??`WAVE ${w.wave}`}</span><b>{w.tasks}</b></div>)}</div><small className='r127-boundary'>Adaptive compute pressure: {p.relativeCompute?.pressure??'—'} · provider ceiling {p.budgets?.providerTotal??providerBudget}. Catalog/mode availability remains distinct from execution.</small></aside></section>
  {mission&&<section className='r127-mission'><header><div><span>LIVE CORTEX MISSION</span><b>{mission.id}</b></div><strong data-state={status(mission.status)}>{status(mission.status)}</strong></header><div className='r127-progress'><div><span style={{width:`${mission.progress||0}%`}}/></div><div className='r127-missionstats'><article><span>PROGRESS</span><b>{mission.progress??0}%</b></article><article><span>COMPLETE</span><b>{mission.completedTasks??0}</b></article><article><span>FAILED / SCARS</span><b>{mission.failedTasks??0} / {mission.scarCount??0}</b></article><article><span>READY</span><b>{mission.ready??0}</b></article><article><span>MEMORY</span><b>{mission.memoryCount??0}</b></article><article><span>PROOF STATE</span><b>{mission.proofState??'—'}</b></article></div><div className='r127-live-actions'><button onClick={()=>void refreshMission()}><RefreshCw/>REFRESH</button><button onClick={()=>void action('advance')} disabled={busy||!['QUEUED','RUNNING'].includes(mission.status)}><Activity/>ADVANCE 24</button>{mission.status==='PAUSED'?<button onClick={()=>void action('resume')}><Play/>RESUME</button>:<button onClick={()=>void action('pause')} disabled={mission.status!=='RUNNING'}><CirclePause/>PAUSE</button>}<button onClick={()=>void action('checkpoint')}><ShieldCheck/>CHECKPOINT</button><button onClick={()=>void action('rejoin')} disabled={mission.status!=='COMPLETE'}><RotateCcw/>RETURN / REJOIN</button></div>{checkpoint&&<div className='r127-checkpoint'><CheckCircle2/><div><span>CHECKPOINT</span><b>{checkpoint.sha256}</b><small>{checkpoint.authority}</small></div></div>}</section>}
  <section className='r127-lower'><div className='r127-memory'><header><MemoryStick/><div><span>SHARED CANDIDATE BLACKBOARD</span><b>{memory.length} recent memory packets</b></div></header><div>{memory.length?memory.slice(0,18).map((x:any)=><article key={x.taskId}><span>{x.role} · wave {x.wave}</span><b>{x.cellId}</b><p>{x.summary}</p><small>{x.authority}</small></article>):<p className='empty'>No candidate memory yet. Memory appears only after real cell receipts return.</p>}</div></div><div className='r127-events'><header><Network/><div><span>CAUSAL EVENT STREAM</span><b>{events.length} retained events</b></div></header><div>{events.length?events.slice(-24).reverse().map((x:any)=><article key={`${x.seq}-${x.at}`}><i>{x.seq}</i><div><b>{x.type}</b><small>{new Date(x.at).toLocaleTimeString()} {x.taskId?`· ${x.taskId}`:''}</small></div></article>):<p className='empty'>No mission events yet.</p>}</div></div></section>
  <footer className='r127-truth'><ShieldCheck/><div><b>R127 AUTHORITY BOUNDARY</b><span>Cell results, shared memory, branch checks, organ synthesis, causal graph completion and execution quorum remain candidate computation. They do not become empirical fact or CanonState merely because the body agrees. OMEGAv6 proof/admission remains the canonical gate.</span></div></footer>
 </section>
}
