import {useEffect,useRef,useState} from 'react';
import {Orbit,Pause,Play,ShieldCheck} from 'lucide-react';
import {corpusState} from './corpusRuntime';
import {getMandala20736Field,mandalaLensDescriptor,mandalaLensWeight,type FieldLens,type Mandala20736Field} from './mandala20736Runtime';
import {getVisualCalibration,type VisualCalibration} from './visualCalibration';

const LENSES:FieldLens[]=['UNIFIED','WATER','LIGHT','SCAR','RELATIVITY','FORECAST','PROOF','TOPOLOGY'];
const clamp=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
export default function OmegaVisualInstrument({address,onCommit}:{address:number;onCommit:(address:number)=>void}){
 const canvas=useRef<HTMLCanvasElement|null>(null),[field,setField]=useState<Mandala20736Field|null>(null),[cal,setCal]=useState<VisualCalibration|null>(null),[lens,setLens]=useState<FieldLens>('UNIFIED'),[zoom,setZoom]=useState(1),[spin,setSpin]=useState(true),[error,setError]=useState('');
 useEffect(()=>{Promise.all([getMandala20736Field(),getVisualCalibration()]).then(([f,c])=>{setField(f);setCal(c)}).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]);
 useEffect(()=>{if(!field||!canvas.current)return;let raf=0,alive=true;const c=canvas.current,ctx=c.getContext('2d');if(!ctx)return;const draw=(now:number)=>{if(!alive)return;const rect=c.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),W=Math.max(300,Math.round(rect.width)),H=Math.max(360,Math.round(rect.height));if(c.width!==Math.round(W*dpr)||c.height!==Math.round(H*dpr)){c.width=Math.round(W*dpr);c.height=Math.round(H*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#020609';ctx.fillRect(0,0,W,H);const t=(spin?now*.00005:0),cs=Math.cos(t),sn=Math.sin(t),scale=Math.min(W,H)*.66*zoom;ctx.globalCompositeOperation='lighter';const stride=W<720?3:1;for(let i=0;i<field.count;i+=stride){const x0=field.x[i],z0=field.z[i],x=x0*cs-z0*sn,z=x0*sn+z0*cs,y=field.y[i],depth=clamp((z+1.2)/2.4),w=mandalaLensWeight(field,i,lens),px=W/2+x*scale/(1.7-z*.45),py=H/2-y*scale/(1.7-z*.45),a=.03+.3*w*(.35+.65*depth),r=.45+2*w*(.45+.55*depth);ctx.fillStyle=lens==='SCAR'?`rgba(210,78,96,${a})`:lens==='WATER'?`rgba(65,218,199,${a})`:lens==='LIGHT'?`rgba(235,239,216,${a})`:lens==='RELATIVITY'?`rgba(100,160,210,${a})`:lens==='FORECAST'?`rgba(117,203,164,${a})`:lens==='PROOF'?`rgba(225,181,102,${a})`:lens==='TOPOLOGY'?`rgba(173,126,221,${a})`:`rgba(${Math.round(65+120*field.q[i])},${Math.round(115+115*field.C[i])},${Math.round(135+110*field.Phi[i])},${a})`;ctx.fillRect(px-r/2,py-r/2,r,r)}ctx.globalCompositeOperation='source-over';const i=Math.max(0,Math.min(field.count-1,address)),x0=field.x[i],z0=field.z[i],x=x0*cs-z0*sn,z=x0*sn+z0*cs,y=field.y[i],px=W/2+x*scale/(1.7-z*.45),py=H/2-y*scale/(1.7-z*.45);ctx.beginPath();ctx.arc(px,py,10,0,Math.PI*2);ctx.strokeStyle='#f2ca82';ctx.lineWidth=2;ctx.stroke();ctx.font='11px ui-monospace,monospace';ctx.fillStyle='#e8f2f4';ctx.fillText(`STATE ${i+1} · ${lens} · ${field.count.toLocaleString()} NODES`,14,22);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf)}},[field,lens,zoom,spin,address]);
 const record=corpusState(address),descriptor=mandalaLensDescriptor(lens);
 return <section className='special-app visual-instrument-app'><header className='special-head'><div><span>FIELD RENDER ENGINE · SAME PACKET CORE</span><h2>Visual Instrument</h2></div><div className='special-status'><b>{record.metrics.decision}</b><small>STATE {record.stateId}</small></div></header><div className='lens-tabs'>{LENSES.map(x=><button key={x} className={lens===x?'active':''} onClick={()=>setLens(x)}>{x}</button>)}</div><div className='visual-stage'><canvas ref={canvas}/>{!field&&<div className='stage-loading'><Orbit className='spin'/><b>{error||'Compiling field…'}</b></div>}<aside className='visual-equation'><span>{descriptor.family}</span><b>{descriptor.equation}</b><p>{descriptor.meaning}</p><small>{descriptor.boundary}</small></aside></div><div className='instrument-controls'><button onClick={()=>setSpin(v=>!v)}>{spin?<Pause/>:<Play/>}{spin?'Pause motion':'Resume motion'}</button><label>Zoom <input type='range' min='.55' max='2.1' step='.05' value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><button onClick={()=>onCommit(record.autoPing.previous)}>Previous</button><button className='gold' onClick={()=>onCommit(record.autoPing.dataNext)}>Admitted next</button><span><ShieldCheck/> calibration {cal?`${cal.channelCount} channels · ${cal.passed?'PASS':'CHECK'}`:'BUILDING'}</span></div></section>
}