import {useEffect,useMemo,useState} from 'react';
import {BrainCircuit,ChevronRight,Command,Globe2,Heart,Layers3,Search,ShieldCheck,Sparkles,Waypoints,X} from 'lucide-react';
import {OMEGA_NAVIGATION} from './navigationRegistry';
import './omegaLauncher.css';
import './omegaLauncherR12.css';

type Props={onNavigate:(name:string)=>void};
export const LAUNCHER_SURFACES=OMEGA_NAVIGATION;
const DOMAIN_SECTIONS=[
 {id:'COMMAND',label:'COMMAND & WORKSPACE',icon:'command',items:['Command Center','Workspace','Cockpit','Create']},
 {id:'VISUAL',label:'VISUALIZE & TRAVERSE',icon:'visual',items:['Visual Instrument','Immersive Traversal','Matter Traversal','Extreme Traversal','Traversal','Relativity','Atlas','Atlas Calculator','Infinity','Scale Compiler']},
 {id:'EARTH',label:'EARTH, FIELD & FORECAST',icon:'earth',items:['Earth Now','Forecast','Reality Lab','Data Motion','Field','Convergence']},
 {id:'INTELLIGENCE',label:'INTELLIGENCE & MODES',icon:'intelligence',items:['Modes','Kernel Intelligence','SAI Lab','Memory','Instructions']},
 {id:'BUILD',label:'BUILD & WORK',icon:'build',items:['Development','Build Out','Projects','Render Queue','Assets','Quality Compiler']},
 {id:'PROOF',label:'ARCHIVE, EVIDENCE & PROOF',icon:'proof',items:['Evidence & Proof','Archive Census','Archive Operators','Validation']},
 {id:'SYSTEM',label:'SYSTEM & GOVERNANCE',icon:'system',items:['Hybrid Link','Governance','Consolidation','Canon Evolution','Plugins','Settings','System','System Atlas','Control Matrix']}
] as const;
function icon(kind:string){return kind==='command'?<Command/>:kind==='visual'?<Sparkles/>:kind==='earth'?<Globe2/>:kind==='intelligence'?<BrainCircuit/>:kind==='build'?<Layers3/>:kind==='proof'?<ShieldCheck/>:<Waypoints/>}
function readList(key:string){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x.filter(v=>typeof v==='string'):[]}catch{return[]}}
export default function OmegaLauncher({onNavigate}:Props){
 const[open,setOpen]=useState(false),[q,setQ]=useState(''),[favorites,setFavorites]=useState<string[]>(()=>readList('omega.v6.favorites')),[recent,setRecent]=useState<string[]>(()=>readList('omega.v6.recent'));
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?LAUNCHER_SURFACES.filter(x=>(x.name+' '+x.group+' '+x.hint+' '+x.id+' '+x.effect+' '+x.authority).toLowerCase().includes(s)):LAUNCHER_SURFACES},[q]);
 const go=(name:string)=>{const n=[name,...recent.filter(x=>x!==name)].slice(0,6);setRecent(n);localStorage.setItem('omega.v6.recent',JSON.stringify(n));localStorage.setItem('omega.v6.panel',JSON.stringify(name));setOpen(false);onNavigate(name)};
 const fav=(name:string,e:any)=>{e.stopPropagation();const n=favorites.includes(name)?favorites.filter(x=>x!==name):[...favorites,name];setFavorites(n);localStorage.setItem('omega.v6.favorites',JSON.stringify(n))};
 const activate=(name:string,e:React.KeyboardEvent<HTMLDivElement>)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go(name)}};
 return <><button className='omega-nexus-trigger' onClick={()=>setOpen(true)} aria-label='Open OMEGA application launcher'><Command/><span>NEXUS</span><small>44</small></button>{open&&<div className='omega-nexus-backdrop' role='presentation' onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className='omega-nexus omega-nexus-r12' role='dialog' aria-modal='true' aria-label='OMEGA application launcher'><header><div><span>OMEGA APPLICATION NEXUS · FUNCTIONAL MAP</span><h2>Choose what you are trying to do.</h2><p>All 44 real destinations remain available, but they are grouped by operational purpose so navigation does not become the work.</p></div><button onClick={()=>setOpen(false)} aria-label='Close launcher'><X/></button></header><div className='omega-nexus-search'><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder='Search capability, function, evidence boundary, operation, or number…'/><kbd>CTRL K</kbd></div>{!q&&recent.length>0&&<div className='omega-nexus-recents'><span>RECENT</span>{recent.map(name=><button key={name} onClick={()=>go(name)}>{name}<ChevronRight/></button>)}</div>}<main>{DOMAIN_SECTIONS.map(domain=>{const rows=filtered.filter(x=>(domain.items as readonly string[]).includes(x.name));if(!rows.length)return null;return <section className='omega-nexus-group omega-domain-group' data-domain={domain.id} key={domain.id}><header>{icon(domain.icon)}<b>{domain.label}</b><span>{rows.length}</span></header><div>{rows.map(x=><div className='omega-nexus-card' data-authority={x.authority} data-effect={x.effect} key={x.id} role='button' tabIndex={0} onClick={()=>go(x.name)} onKeyDown={e=>activate(x.name,e)} aria-label={`Open ${x.name}`}><code>{x.id}</code><span><b>{x.name}</b><small>{x.hint}</small><em>{x.group} · {x.effect.replace('_',' ')} · {x.authority.replace('_',' ')}</em></span><button type='button' className={'omega-nexus-fav '+(favorites.includes(x.name)?'active':'')} onClick={e=>fav(x.name,e)} aria-label={(favorites.includes(x.name)?'Remove ':'Add ')+x.name+' favorite'}><Heart/></button><ChevronRight className='omega-nexus-arrow'/></div>)}</div></section>})}</main><footer><ShieldCheck/><span>44 real routes · 7 functional domains · one navigation authority · no decorative dead controls</span><b>{filtered.length}/44</b></footer></section></div>}</>}
