import {Suspense,startTransition,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {BrainCircuit,Home,Orbit,ShieldCheck,Sparkles} from 'lucide-react';
import OmegaCommandDeck from './OmegaCommandDeck';
import ResponsiveRuntimeShell,{LayoutModeSwitch,type OmegaUiMode} from './ResponsiveRuntimeShell';
import PhaseWheel from './PhaseWheel';
import {corpusState,decodeAddress,evaluateCorpusModes,initCorpusPack} from './corpusRuntime';
import {sourceBackedModeSummary} from './sourceBackedModeRuntimeR21';
import {unifiedFromRecord} from './unifiedCalculus';
import {CAPABILITY_REALITY_LABEL} from './capabilityAuthority';
import {capabilityExecutionContract,capabilityPerformanceHints,effectiveCapabilityReality} from './operationalCapabilityRuntimeR45';
import {api,localState} from './platformAdapter';
import {RUNTIME_IDENTITY} from './runtimeIdentity';
import {compileFullOverallModePlanR79,compactModePlanR79} from './fullOverallModeOrchestratorR79';
import SurfaceIntegrityR81 from './SurfaceIntegrityR81';
import OmegaIntentWorkbenchR85 from './OmegaIntentWorkbenchR85';
import {readWorkflowR85,type WorkflowSessionR85} from './omegaWorkflowRuntimeR85';
import {syncProjectContinuityR97} from './omegaProjectContinuityR87';
import {applyWorkflowVisualIntentR86,emitOperationR86} from './omegaOperationBusR86';
import {commitRouteLifecycleR356,requestRouteLifecycleR356} from './system/routeLifecycleR356';
import {OMEGA_ALL_ROUTES_R82} from './omegaExperienceRegistryR82';
import {operationContractForRouteR143} from './authoritativeOperationChainR143';
import {OMEGA_NAV_NAMES,type OmegaRouteName} from './navigationRegistry';
import CorpusExecutionIntentR473,{readCorpusExecutionIntentR473,type CorpusExecutionIntentR473 as CorpusExecutionIntentR473Type} from './CorpusExecutionIntentR473';
import CorpusAdapterWorkbenchR473 from './CorpusAdapterWorkbenchR473';
import {OMEGA_CONTROL_RECONCILIATION_R466,omegaMasterMenuForRouteR289,omegaNavItem} from './navigationRegistry';
import {
 ArchiveGovernanceR109,AtlasCalculatorR109,AtlasViewportR109,BuildOutR109,EarthNowR109,ExtremeTraversalR109,ForecastR109,
 HybridMissionControlR109,InfinityR109,IntelligenceFabricR109,MatterTraversalR109,OmegaWorkspaceCockpitR109,PluginRegistryR109,
 RealityLabR109,RelativityR109,RETAINED_DEEP_SPECIALIST_LOADERS_R109,SAIControlR109,ScaleCompilerR109,SourceBackedModesR109,
 ConvergenceR416,SpecialistSuiteR109,SystemAtlasR109,TraversalR109,UniversalQualityR109,VisualInstrumentR109,prefetchSpecialistPanelR109,prefetchSpecialistPanelsR109,specialistLoadersForPanelR109
} from './specialistLoaderR109';
import './workstationV2.css';
import './workstationPresentationR356.css';
import './specialistLoaderR109.css';
import './omegaNavigationShellR411.css';
import './corpusExecutionIntentR473.css';

export const OMEGA_SURFACES=OMEGA_NAV_NAMES;
type Panel=OmegaRouteName;
const LEGACY_R82_SURFACE_INVENTORY_SCAR="OMEGA_SURFACES=['Command Center','Hybrid Link','Workspace','Cockpit','Immersive Traversal','Matter Traversal','Extreme Traversal','Visual Instrument','Relativity','Earth Now','Forecast','Atlas','Traversal','Create','Field','Data Motion','Reality Lab','Atlas Calculator','Infinity','Convergence','Quality Compiler','Build Out','Projects','Render Queue','Assets','Modes','Kernel Intelligence','Evidence & Proof','Memory','Archive Census','Archive Operators','Development','Canon Evolution','SAI Lab','Governance','Consolidation','Instructions','Plugins','Settings','System','Validation','System Atlas','Scale Compiler','Control Matrix'] as const";
void LEGACY_R82_SURFACE_INVENTORY_SCAR;
const RETAINED_DEEP_SPECIALIST_AUTHORITY: { [key: string]: any } ={OmegaVisualInstrument:RETAINED_DEEP_SPECIALIST_LOADERS_R109.OmegaVisualInstrument,OmegaTraversalStudio:RETAINED_DEEP_SPECIALIST_LOADERS_R109.OmegaTraversalStudio,MatterTraversal:RETAINED_DEEP_SPECIALIST_LOADERS_R109.MatterTraversal};
void RETAINED_DEEP_SPECIALIST_AUTHORITY;
const LEGACY_R23_STALE_ROUTE_FALLBACK: string ="isPrimaryOperationalCapability(String(v))?v as Panel:'System Atlas'";
void LEGACY_R23_STALE_ROUTE_FALLBACK;
const SPECIALIST_EXISTING=new Set<Panel>(['Hybrid Link','Workspace','Cockpit','Matter Traversal','Visual Instrument','Relativity','Earth Now','Forecast','Atlas','Reality Lab','Atlas Calculator','Infinity','Scale Compiler','Build Out','SAI Lab','Kernel Intelligence','Immersive Traversal','Extreme Traversal','Traversal','Archive Census','Archive Operators','Quality Compiler','Validation','System Atlas','Control Matrix']);
const SPECIALIST_SUITE=new Set<Panel>(['Field','Data Motion','Projects','Render Queue','Assets','Evidence & Proof','Memory','Canon Evolution','Governance','Consolidation','Instructions','Settings','System']);
const VISUAL_FIRST_SURFACES=new Set<Panel>(['Matter Traversal','Visual Instrument','Immersive Traversal','Extreme Traversal','Traversal','Forecast','Relativity','Earth Now','Atlas','Infinity','Scale Compiler','Reality Lab','Field','Data Motion','Convergence']);
export const OMEGA_WORKSTATION_CONTROL_RECONCILIATION='R466';
const DIRECT_WORKSTATION_SURFACES_R466=new Set<Panel>(['Command Center','Create','Development','Modes','Plugins','Convergence']);
type WorkstationControlAuditR466={
 route:Panel;
 declaredAuthority:string|null;
 registeredExactlyOnce:boolean;
 experienceExactlyOnce:boolean;
 masterMenuReachable:boolean;
 mountClaims:number;
 mountedExactlyOnce:boolean;
 operationBound:boolean;
 routable:boolean;
 hiddenUnreachable:boolean;
 duplicateAuthority:boolean;
 canonicalMutation:false;
};
const workstationMountClaimsR466=(route:Panel)=>Number(DIRECT_WORKSTATION_SURFACES_R466.has(route))+Number(SPECIALIST_EXISTING.has(route))+Number(SPECIALIST_SUITE.has(route));
export const OMEGA_WORKSTATION_CONTROL_AUDIT_R466=Object.freeze(OMEGA_ALL_ROUTES_R82.map(route=>{
 const panel=route as Panel;
 const navItem=omegaNavItem(route);
 const registeredExactlyOnce=OMEGA_NAV_NAMES.filter(name=>name===route).length===1;
 const experienceExactlyOnce=OMEGA_ALL_ROUTES_R82.filter(name=>name===route).length===1;
 const masterMenuReachable=Boolean(omegaMasterMenuForRouteR289(route));
 const mountClaims=workstationMountClaimsR466(panel);
 const mountedExactlyOnce=mountClaims===1;
 const chain=operationContractForRouteR143(route);
 const operationBound=Boolean(chain?.routeId&&chain?.capabilityId&&chain?.executionDomain);
 const routable=Boolean(capabilityExecutionContract(route).routable);
 const duplicateAuthority=!registeredExactlyOnce;
 const hiddenUnreachable=!(registeredExactlyOnce&&experienceExactlyOnce&&masterMenuReachable&&mountedExactlyOnce&&operationBound&&routable);
 return Object.freeze({route:panel,declaredAuthority:navItem?.authority||null,registeredExactlyOnce,experienceExactlyOnce,masterMenuReachable,mountClaims,mountedExactlyOnce,operationBound,routable,hiddenUnreachable,duplicateAuthority,canonicalMutation:false}) satisfies WorkstationControlAuditR466;
}));
export const OMEGA_WORKSTATION_CONTROL_SUMMARY_R466=Object.freeze({
 schema:'OMEGA_WORKSTATION_CONTROL_RECONCILIATION_R466',
 revision:'R466',
 routeCount:OMEGA_WORKSTATION_CONTROL_AUDIT_R466.length,
 recoveredControls:Object.freeze(OMEGA_WORKSTATION_CONTROL_AUDIT_R466.filter(row=>!row.hiddenUnreachable).map(row=>row.route)),
 hiddenUnreachableRoutes:Object.freeze(OMEGA_WORKSTATION_CONTROL_AUDIT_R466.filter(row=>row.hiddenUnreachable).map(row=>row.route)),
 duplicateAuthorityRoutes:Object.freeze(OMEGA_WORKSTATION_CONTROL_AUDIT_R466.filter(row=>row.duplicateAuthority).map(row=>row.route)),
 nonUniqueMountRoutes:Object.freeze(OMEGA_WORKSTATION_CONTROL_AUDIT_R466.filter(row=>!row.mountedExactlyOnce).map(row=>row.route)),
 navigationRegistryPass:OMEGA_CONTROL_RECONCILIATION_R466.pass,
 pass:OMEGA_CONTROL_RECONCILIATION_R466.pass&&OMEGA_WORKSTATION_CONTROL_AUDIT_R466.every(row=>!row.hiddenUnreachable&&!row.duplicateAuthority&&row.mountedExactlyOnce),
 proof:{routeAuthority:'navigationRegistry',operationAuthority:'R143',executionProof:'R142',canonAdmission:'R125'},
 canonicalMutation:false,
 rule:'RECOVER_EVERY_REGISTERED_CONTROL_WITH_EXACTLY_ONE_MOUNT_AND_NO_SHADOW_ROUTE_AUTHORITY'
});
export const OMEGA_ROUTE_FUNCTIONAL_INHERITANCE='R464';
type RouteFunctionalInheritanceR464={
 route:string;
 usableControl:boolean;
 stateOutput:string;
 proof:{operationAuthority:'R143';executionProof:'R142';canonAdmission:'R125'};
 failureRecovery:{state:'READY'|'DEGRADED';degradeTo:'System Atlas';preserveRequestedRoute:boolean};
 canonicalMutation:false;
};
const routeFunctionalInheritanceR464=(route:string):RouteFunctionalInheritanceR464=>{
 const registered=OMEGA_ALL_ROUTES_R82.includes(route as any);
 if(!registered)return{route,usableControl:false,stateOutput:'UNRESOLVED_ROUTE',proof:{operationAuthority:'R143',executionProof:'R142',canonAdmission:'R125'},failureRecovery:{state:'DEGRADED',degradeTo:'System Atlas',preserveRequestedRoute:true},canonicalMutation:false};
 const chain=operationContractForRouteR143(route);
 const usableControl=Boolean(chain?.routeId&&chain?.capabilityId&&chain?.executionDomain);
 return{route,usableControl,stateOutput:`${chain.state}:${chain.capabilityId}`,proof:{operationAuthority:'R143',executionProof:'R142',canonAdmission:'R125'},failureRecovery:{state:usableControl?'READY':'DEGRADED',degradeTo:'System Atlas',preserveRequestedRoute:true},canonicalMutation:false};
};
function normalizePanel(v:any):Panel{const route=String(v);if(!OMEGA_SURFACES.includes(v as Panel))return 'System Atlas';const inheritance=routeFunctionalInheritanceR464(route);return inheritance.usableControl&&capabilityExecutionContract(String(v)).routable?v as Panel:inheritance.failureRecovery.degradeTo}

export default function OmegaWorkstationFullV2(){
 const[ready,setReady]=useState(false),[bootError,setBootError]=useState('');
 const[panel,setPanel]=useState<Panel>(()=>normalizePanel(localState.read('omega.v6.panel','Command Center')));
 const[address,setAddress]=useState(()=>Math.max(0,Math.min(20735,Number(localState.read('omega.v6.address',11498))||11498)));
 const[uiMode,setUiMode]=useState<OmegaUiMode>(()=>{const x=localStorage.getItem('omega-ui-mode');return x==='DESKTOP'||x==='MOBILE'?x:'AUTO'});
 const[modePolicy,setModePolicy]=useState<'SOURCE_BACKED'|'CATALOG'>('SOURCE_BACKED');
 const[workflow,setWorkflow]=useState<WorkflowSessionR85|null>(()=>readWorkflowR85());
 const[corpusIntent,setCorpusIntent]=useState<CorpusExecutionIntentR473Type|null>(()=>readCorpusExecutionIntentR473());
 const[prompt,setPrompt]=useState(()=>localState.read('omega.b015.chatDraft.v1','Use every source-backed executable OMEGA operator that has authoritative inputs, preserve missing-input formulas as gated, and continue without losing continuity or inventing execution.'));
 const[response,setResponse]=useState<any>(null),[busy,setBusy]=useState(''),[status,setStatus]=useState<any>(null),[restore,setRestore]=useState<any>(null);const seq=useRef(0);
 useEffect(()=>{initCorpusPack().then(()=>setReady(true)).catch(e=>setBootError(e instanceof Error?e.message:String(e)))},[]);
 useEffect(()=>{void syncProjectContinuityR97()},[]);
 useEffect(()=>{localState.write('omega.v6.panel',panel)},[panel]);useLayoutEffect(()=>{commitRouteLifecycleR356(panel)},[panel]);useEffect(()=>{localState.write('omega.v6.address',address)},[address]);useEffect(()=>{localState.write('omega.v6.modePolicy',modePolicy)},[modePolicy]);
 useEffect(()=>{const sync=(e:Event)=>setWorkflow((e as CustomEvent).detail??readWorkflowR85());window.addEventListener('omega-r85-workflow-changed',sync as EventListener);return()=>window.removeEventListener('omega-r85-workflow-changed',sync as EventListener)},[]);
 useEffect(()=>{const sync=(e:Event)=>setCorpusIntent((e as CustomEvent<CorpusExecutionIntentR473Type>).detail??readCorpusExecutionIntentR473());const clear=()=>setCorpusIntent(null);window.addEventListener('omega:r473-corpus-execution',sync as EventListener);window.addEventListener('omega:r473-corpus-execution-cleared',clear);return()=>{window.removeEventListener('omega:r473-corpus-execution',sync as EventListener);window.removeEventListener('omega:r473-corpus-execution-cleared',clear)}},[]);
 useEffect(()=>{if(!workflow)return;const next=workflow.steps?.[Math.min(workflow.steps.length-1,workflow.currentStep+1)]?.route||'';const capabilityRoutes=Array.isArray(workflow.capabilityPlan?.next?.routes)?workflow.capabilityPlan.next.routes.slice(0,2):[];void prefetchSpecialistPanelsR109([next,...capabilityRoutes])},[workflow?.id,workflow?.currentStep]);
 const refresh=async()=>{try{const[s,r]=await Promise.all([api.get<any>('/api/status'),api.get<any>('/api/restoration')]);setStatus(s.data);setRestore(r.data)}catch(e:any){setStatus({error:e?.message||String(e)});setRestore({error:e?.message||String(e)})}};useEffect(()=>{let live=true;const poll=()=>{if(live)void refresh()};poll();const id=window.setInterval(poll,30000);return()=>{live=false;window.clearInterval(id)}},[]);
 const record=useMemo(()=>ready?corpusState(address):null,[ready,address]),coords=useMemo(()=>decodeAddress(address),[address]),catalog=useMemo(()=>record?evaluateCorpusModes(record):null,[record]),sourceModes=useMemo(()=>record?sourceBackedModeSummary(record):null,[record]),unified=useMemo(()=>record?unifiedFromRecord(record):null,[record]);
 const workflowContext=(workflow?`\nACTIVE WORKFLOW ${workflow.intent}\nGOAL ${workflow.goal}`:'')+(corpusIntent?`\nACTIVE YEAR-CORPUS EXECUTION ${corpusIntent.name}\nOPERATION ${corpusIntent.operation}\nTARGET ${corpusIntent.route}\nEXECUTION STATE ${corpusIntent.state}`:'');
 const modePlan=useMemo(()=>record?compileFullOverallModePlanR79(record,panel,prompt+workflowContext):null,[record,panel,prompt,workflowContext]);
 const state=useMemo(()=>({atlas:{address},modePolicy:'SOURCE_BACKED',fullOverallModePlan:modePlan?compactModePlanR79(modePlan):null,frozen:false,d:coords.d,p:coords.p,r:coords.r,l:coords.l,workflow:'LAW',preset:'SOVEREIGN',timeAuthority:'NOW',viewportMode:'CANON_FIELD',instrumentView:'LIVE',workspace:'LAW',embodimentIndex:4}),[address,coords,modePlan]);
 const go=(name:string)=>{const requestedInheritance=routeFunctionalInheritanceR464(name),next=requestedInheritance.usableControl?normalizePanel(name):requestedInheritance.failureRecovery.degradeTo,routeDeferred=specialistLoadersForPanelR109(next).length>0;void prefetchSpecialistPanelR109(next);if(workflow&&(next==='Visual Instrument'||next==='Modes')){const marker=`${workflow.id}:${workflow.intent}:${next}`;try{if(localStorage.getItem('omega.r86.intentVisualApplied')!==marker){applyWorkflowVisualIntentR86(workflow.intent);const selected=modePlan?.intentModes?.[0]?.id||modePlan?.kernel?.[0]?.id;if(selected){localStorage.setItem('omega.r83.selectedModeRef',selected);localStorage.setItem('omega.r82.selectedModeId',selected)}localStorage.setItem('omega.r86.intentVisualApplied',marker)}}catch{}}const routeLifecycle=requestRouteLifecycleR356(panel,next);if(next===panel){commitRouteLifecycleR356(panel)}else{if(routeDeferred)setPanel(next);else startTransition(()=>setPanel(next));window.setTimeout(()=>{const root=document.documentElement;if(root.dataset.omegaRouteEpoch===routeLifecycle.epoch&&root.dataset.omegaRouteState==='REQUESTED'&&root.dataset.omegaRouteTarget===next&&root.dataset.omegaRouteCurrent!==next)setPanel(next)},240)}void emitOperationR86({type:'SURFACE_OPENED',surface:next,stateId:record?.stateId,address,status:requestedInheritance.usableControl?'INFO':'WARN',detail:requestedInheritance.usableControl?`Opened ${next}`:`Functional inheritance degraded ${name} to ${next}`,payload:{from:panel,requested:name,to:next,workflowIntent:workflow?.intent||null,functionalInheritance:OMEGA_ROUTE_FUNCTIONAL_INHERITANCE,usableControl:requestedInheritance.usableControl,stateOutput:requestedInheritance.stateOutput,proof:requestedInheritance.proof,failureRecovery:requestedInheritance.failureRecovery,yearCorpusExecution:corpusIntent?{id:corpusIntent.id,name:corpusIntent.name,operation:corpusIntent.operation,targetRoute:corpusIntent.route,state:corpusIntent.state}:null,canonicalMutation:false}});window.dispatchEvent(new CustomEvent('omega-capability-change',{detail:{name:next,contract:capabilityExecutionContract(next)}}));window.requestAnimationFrame(()=>{document.querySelector<HTMLElement>('.workstation-main')?.scrollTo({top:0,behavior:'auto'});window.scrollTo({top:0,behavior:'auto'})})};
 useEffect(()=>{const direct=(e:Event)=>{const requested=String((e as CustomEvent<{route?:string}>).detail?.route||'');if(requested)go(requested)};window.addEventListener('omega-r356-navigate',direct as EventListener);return()=>window.removeEventListener('omega-r356-navigate',direct as EventListener)},[panel,workflow,modePlan,address,record]);
 const commit=(c:any)=>{if(typeof c==='number')setAddress(Math.max(0,Math.min(20735,Math.floor(c))));else if(c&&Number.isFinite(c.d))setAddress(1728*c.d+144*c.p+12*c.r+c.l)};
 const ask=async()=>{if(!prompt.trim()||busy||!record||!catalog||!sourceModes||!modePlan)return;const s=++seq.current;setBusy('assistant');localState.write('omega.b015.chatDraft.v1',prompt);try{const context={address,stateId:record.stateId,coords,decision:record.metrics.decision,identity:record.identity,metrics:record.metrics,psc:record.psc,predict:record.predict,nextAddress:record.autoPing?.dataNext??address,phase:coords.p+1,modePolicy:'SOURCE_BACKED_ALL_AVAILABLE',modeCatalogCount:catalog.count,appliedModeCount:sourceModes.appliedCount,exactModeCount:sourceModes.exactCount,packetModeCount:sourceModes.packetCount,gatedModeCount:sourceModes.gatedCount,exactModes:sourceModes.executed.map(x=>({id:x.id,name:x.name,formula:x.formula,value:x.value,source:x.source})),sourcePacketModes:sourceModes.packet.map(x=>({id:x.id,name:x.name,value:x.value,source:x.source})),gatedModes:sourceModes.gated.map(x=>({id:x.id,name:x.name,formula:x.formula,missing:x.missing,source:x.source})),modeTruthBoundary:sourceModes.boundary,yearCorpusExecution:corpusIntent?{...corpusIntent,canonicalMutation:false}:null,fullOverallModePlan:compactModePlanR79(modePlan),unified:{coherence:unified?.unifiedCoherence,waterConductance:unified?.water?.conductance,motionRelativity:unified?.motionRelativity,phase:unified?.phase}};const route=await api.post<any>('/api/route-preview',{text:prompt,context});const reply=await api.post<any>('/api/chat',{text:prompt,context});if(s===seq.current)setResponse({answer:reply.data?.reply||'No response returned.',responsePath:route.data?.route||'ROUTED',provider:reply.data?.provider||'UNKNOWN',evidenceStatus:reply.data?.evidenceStatus||((route.data?.route==='FAST_DETERMINISTIC')?'VERIFIED_RUNTIME':'PROVIDER_BOUND'),modelInvoked:Boolean(reply.data?.modelInvoked),modelSucceeded:reply.ok,appliedModes:[`FULL OVERALL ${modePlan.intent} · ${modePlan.kernel.length} KERNEL · ${modePlan.intentModes.length} INTENT · ${modePlan.supportModes.length} SUPPORT · ${sourceModes.appliedCount} SOURCE-BACKED APPLIED · ${sourceModes.gatedCount} GATED · ${catalog.count} CATALOG`],uncertainty:reply.data?.uncertainty||'Synthesis is grounded to the supplied OMEGA packet and source-backed operator ledger; external facts still require evidence.',nextAction:reply.data?.nextAction||'Continue from the same packet, admitted route and proof state.'})}catch(e:any){if(s===seq.current)setResponse({answer:e?.message||String(e),responsePath:'ROUTED_MODEL',evidenceStatus:'BOUNDED_FAILURE',modelInvoked:true,modelSucceeded:false,appliedModes:[`FULL OVERALL ${modePlan.intent} · SOURCE-BACKED ${sourceModes.appliedCount} APPLIED · ${sourceModes.gatedCount} GATED`],uncertainty:'No fabricated answer substituted.',nextAction:'Continue with deterministic runtime tools while the provider recovers.'})}finally{if(s===seq.current)setBusy('')}};
 if(bootError)return <div className='omega-workstation-v2' data-panel={panel} data-ui-mode={uiMode.toLowerCase()}><div className='workstation-topbar'><button className='home-return' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home/><span>HOME</span></button><div className='workstation-identity'><b>OMEGA · WORKSPACE DEGRADED</b><small>{RUNTIME_IDENTITY.hostedBuild} · corpus unavailable · independent navigation remains available</small></div><LayoutModeSwitch value={uiMode} onChange={setUiMode}/></div><main className='workstation-main' tabIndex={-1}><section className='special-app' role='status' aria-live='polite'><header className='special-head'><div><span>TRUTH-GATED DIAGNOSTIC</span><h2>Source-backed corpus unavailable</h2></div><ShieldCheck/></header><p>{bootError}</p><div className='create-paths'><button type='button' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><b>RETURN HOME</b><span>Keep using available OMEGA surfaces</span></button><button type='button' onClick={()=>location.reload()}><b>RETRY CORPUS</b><span>Retry initialization without fabricating proof</span></button></div></section></main></div>;if(!ready||!record||!catalog||!sourceModes||!modePlan)return <div className='omega-workstation-v2' data-panel={panel} data-ui-mode={uiMode.toLowerCase()}><div className='workstation-topbar'><button className='home-return' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home/><span>HOME</span></button><div className='workstation-identity'><b>OMEGA · PREPARING WORKSPACE</b><small>{RUNTIME_IDENTITY.hostedBuild} · source-backed corpus materializing</small></div><LayoutModeSwitch value={uiMode} onChange={setUiMode}/></div><main className='workstation-main' tabIndex={-1}><section className='r109-specialist-loading' aria-live='polite' aria-busy='true'><span>NON-BLOCKING INITIALIZATION</span><b>Materializing source-backed applications…</b><small>OMEGA Home remains available while corpus-dependent instruments initialize.</small><button type='button' className='home-return' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home/><span>RETURN HOME</span></button></section></main></div>;
 const phase=<PhaseWheel address={address} onSelectAddress={commit} compact title='Phase / timing context'/>;const command=<div className='command-experience-r4'><div className='command-phase-context'>{phase}</div><OmegaCommandDeck record={record} state={state} prompt={prompt} onPrompt={v=>{setPrompt(v);localState.write('omega.b015.chatDraft.v1',v)}} onRun={ask} response={response} busy={busy} onNavigate={go}/></div>;const withPhase=(child:any,kind:string)=><div className={`experience-phase-bound experience-${kind}`}><div className='experience-phase-dock'>{phase}</div>{child}</div>;
 const existing=()=>{switch(panel){case 'Hybrid Link':return withPhase(<HybridMissionControlR109 status={status} record={record}/>,'hybrid');case 'Workspace':case 'Cockpit':return <OmegaWorkspaceCockpitR109 variant={panel} record={record} state={state} address={address} onAddress={commit} onNavigate={go} status={status} restore={restore} modeCount={sourceModes.appliedCount}/>;case 'Archive Census':return <ArchiveGovernanceR109/>;case 'Archive Operators':return <ArchiveGovernanceR109 operators/>;case 'Quality Compiler':case 'Validation':return <UniversalQualityR109 record={record} status={status} restore={restore} modeCount={sourceModes.appliedCount}/>;case 'System Atlas':return <SystemAtlasR109 record={record} onNavigate={go}/>;case 'Control Matrix':return <SystemAtlasR109 record={record} onNavigate={go} control/>;case 'Matter Traversal':return withPhase(<MatterTraversalR109 address={address} onAddress={commit} state={state} onNavigate={go}/>,'matter');case 'Visual Instrument':return <VisualInstrumentR109 address={address} onAddress={commit}/>;case 'Relativity':return withPhase(<RelativityR109 record={record} state={state} onNavigate={go}/>,'relativity');case 'Earth Now':return withPhase(<EarthNowR109 address={address}/>,'earth');case 'Forecast':return <ForecastR109 address={address}/>;case 'Atlas':return <section className='special-app'><header className='special-head'><div><span>EXECUTABLE ATLAS · 20,736 SOURCE STATES</span><h2>Atlas</h2></div></header><AtlasViewportR109 state={state} onSelect={commit}/></section>;case 'Reality Lab':return <RealityLabR109 canonicalAddress={address} onCommitAddress={commit}/>;case 'Atlas Calculator':return <section className='special-app'><AtlasCalculatorR109 record={record} onCommit={commit}/></section>;case 'Infinity':return <InfinityR109 record={record}/>;case 'Scale Compiler':return <ScaleCompilerR109 address={address} onAddress={commit}/>;case 'Build Out':return <BuildOutR109 address={address} onNavigate={go}/>;case 'SAI Lab':return <section className='special-app intelligence-lab'><SAIControlR109 record={record} modeCount={sourceModes.appliedCount} onNavigate={go}/><div className='intelligence-secondary'><IntelligenceFabricR109 address={address}/></div><div className='embedded-command'>{command}</div></section>;case 'Kernel Intelligence':return <SAIControlR109 record={record} modeCount={sourceModes.appliedCount} onNavigate={go}/>;case 'Extreme Traversal':return <ExtremeTraversalR109 record={record} address={address} state={state} onAddress={commit} onNavigate={go}/>;case 'Immersive Traversal':case 'Traversal':return <TraversalR109 variant={panel} address={address} state={state} onAddress={commit} onNavigate={go}/>;default:return null}};
 const modesPanel=<SourceBackedModesR109 record={record} address={address} onAddress={commit} onNavigate={go}/>;const createPanel=<section className='special-app create-app'><header className='special-head'><div><span>UNIVERSAL SEED → TRANSLATE → BUILD → PROVE</span><h2>Create</h2></div><Sparkles/></header><div className='create-paths'>{[['RENDER','Visual Instrument'],['MATTER','Matter Traversal'],['CODE / BUILD','Development'],['TRANSLATE','SAI Lab'],['FORECAST','Forecast'],['PROVE','Evidence & Proof']].map(([a,b])=><button key={a} onClick={()=>go(b)}><b>{a}</b><span>{b}</span></button>)}</div>{command}</section>;const development=<section className='special-app development-app'><header className='special-head'><div><span>BUILD OUT MODE · RESTORE + SURPASS</span><h2>Development</h2></div><BrainCircuit/></header><BuildOutR109 address={address} onNavigate={go}/><div className='embedded-command'>{command}</div></section>;
 let content:any;if(panel==='Command Center')content=command;else if(panel==='Create')content=createPanel;else if(panel==='Development')content=development;else if(panel==='Modes')content=modesPanel;else if(panel==='Plugins')content=<PluginRegistryR109/>;else if(panel==='Convergence')content=<ConvergenceR416 record={record} state={state} address={address} onAddress={commit} onNavigate={go} status={status} restore={restore}/>;else if(SPECIALIST_EXISTING.has(panel))content=existing();else if(SPECIALIST_SUITE.has(panel))content=<SpecialistSuiteR109 panel={panel} record={record} state={state} address={address} onAddress={commit} onNavigate={go} status={status} restore={restore} uiMode={uiMode} onUiMode={setUiMode}/>;else content=<SystemAtlasR109 record={record} onNavigate={go}/>;
 const specialistFallback=<section className='r109-specialist-loading' aria-live='polite'><span>ROUTE-DEFERRED SPECIALIST · R109</span><b>Loading {panel}</b><small>Loading this instrument's module bytes for STATE {record.stateId} · address {address+1}. This loading step does not execute the capability, contact an external backend, mutate CanonState, or create proof.</small><i/></section>;
 const reality=effectiveCapabilityReality(panel),perf=capabilityPerformanceHints(panel);return <div className='omega-workstation-v2' data-panel={panel} data-visual-first={VISUAL_FIRST_SURFACES.has(panel)?'true':'false'} data-ui-mode={uiMode.toLowerCase()} data-capability-reality={reality} data-performance-class={perf.class.toLowerCase()} data-low-power={perf.lowPower?'true':'false'} data-specialist-loading='R109_ROUTE_DEFERRED'><div className='workstation-topbar'><button className='home-return' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home/><span>HOME</span></button><div className='workstation-identity'><b>OMEGA · {panel} · {CAPABILITY_REALITY_LABEL[reality]}</b><small>{RUNTIME_IDENTITY.hostedBuild} · STATE {record.stateId} · PHASE {coords.p+1} · {sourceModes.appliedCount} SOURCE-BACKED APPLIED · {sourceModes.gatedCount} GATED · {catalog.count} CATALOG · {record.metrics.decision}{workflow?` · WORKFLOW ${workflow.intent}`:''} · {perf.targetFps||'REDUCED'} FPS TARGET</small></div><LayoutModeSwitch value={uiMode} onChange={setUiMode}/></div><main className='workstation-main' tabIndex={-1}>{corpusIntent&&<CorpusExecutionIntentR473 intent={corpusIntent} currentRoute={panel} onClear={()=>setCorpusIntent(null)}/>} {corpusIntent&&corpusIntent.state==='EXECUTES_AS_ADAPTER'&&corpusIntent.route===panel&&<CorpusAdapterWorkbenchR473 intent={corpusIntent} record={record} address={address} onNavigate={go}/>}<OmegaIntentWorkbenchR85 variant='STRIP' record={record} address={address} currentPanel={panel} onAddress={commit} onNavigate={go}/><SurfaceIntegrityR81 panel={panel} record={record} onRecover={()=>go('System')}><Suspense fallback={specialistFallback}>{content}</Suspense></SurfaceIntegrityR81></main><ResponsiveRuntimeShell uiMode={uiMode} onUiMode={setUiMode} panel={panel} onNavigate={go} record={record} modePolicy={modePolicy} modeCount={sourceModes.appliedCount} busy={busy}/></div>
}
