import {useMemo,useState} from 'react';
import {Activity,ArrowRight,CheckCircle2,GitMerge,MoveRight,Route,ShieldCheck,Waypoints} from 'lucide-react';
import OmegaLivingField from './OmegaLivingField';
import DriveVectorField from './DriveVectorField';
import SpecialistMotionFieldR36 from './SpecialistMotionFieldR36';
import {compileConvergence,validateConvergence} from './convergenceRuntime';
import {corpusState,decodeAddress} from './corpusRuntime';
import './omegaFieldMotionConvergenceR28.css';

type Props={variant:'Field'|'Data Motion'|'Convergence';record:any;state:any;address:number;onAddress:(n:number)=>void;onNavigate:(name:string)=>void};
const clampAddr=(n:number)=>Math.max(0,Math.min(20735,Math.floor(Number(n)||0)));
const fmt=(n:any,d=4)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
function routeCandidates(record:any){const vals=Object.entries(record.autoPing||{}).filter(([,v])=>typeof v==='number'&&Number.isFinite(v as number)).map(([kind,v])=>({kind,address:clampAddr(v as number)}));const seen=new Set<number>();return vals.filter(x=>!seen.has(x.address)&&seen.add(x.address)).slice(0,12).map(x=>{const r=corpusState(x.address),m=r.metrics||{};const score=(Number(m.continuity||0)+Number(m.plasticity||0)+Number(m.evidence||0)+(1-Number(m.contradiction||0))+(1-Number(m.burden||0)))/5;return{...x,record:r,score}}).sort((a,b)=>b.score-a.score)}
function M({label,value,detail}:{label:string;value:string;detail?:string}){return <div className='r28-metric'><span>{label}</span><b>{value}</b>{detail&&<small>{detail}</small>}</div>}
export default function OmegaFieldMotionConvergenceR28({variant,record,state,address,onAddress,onNavigate}:Props){
 const next=clampAddr(record.autoPing?.dataNext??address),nextRecord=useMemo(()=>corpusState(next),[next]),coords=decodeAddress(address),nextCoords=decodeAddress(next),candidates=useMemo(()=>routeCandidates(record),[record]);
 const[selected,setSelected]=useState<number>(next),delta=next-address,velocity=delta/20736,prev=clampAddr(record.autoPing?.dataPrevious??record.autoPing?.previous??address),prevRecord=useMemo(()=>corpusState(prev),[prev]),prevDelta=address-prev,acceleration=(delta-prevDelta)/20736;
 const derivative={continuity:Number(nextRecord.metrics.continuity)-Number(record.metrics.continuity),plasticity:Number(nextRecord.metrics.plasticity)-Number(record.metrics.plasticity),contradiction:Number(nextRecord.metrics.contradiction)-Number(record.metrics.contradiction),burden:Number(nextRecord.metrics.burden)-Number(record.metrics.burden),scar:Number(nextRecord.metrics.scar)-Number(record.metrics.scar),evidence:Number(nextRecord.metrics.evidence)-Number(record.metrics.evidence)};
 const conv=useMemo(()=>compileConvergence(record,{...state,velocity,acceleration}),[record,state,velocity,acceleration]),valid=useMemo(()=>validateConvergence(record,{...state,velocity,acceleration}),[record,state,velocity,acceleration]);
 if(variant==='Field')return <section className='special-app r28-field'><header className='special-head'><div><span>LIVING MEMBRANE · ONE PACKET · CONTINUITY / SCAR / ROUTE</span><h2>Field</h2><p>The field surface exposes the active packet first. Move to the admitted state or inspect derivatives/convergence without drawing a synthetic route over the geometry.</p></div><strong>STATE {record.stateId}</strong></header><div className='r28-field-stage'><OmegaLivingField address={address} onSelectAddress={onAddress}/></div><div className='r28-field-readout'><M label='CΩ continuity' value={fmt(record.metrics.continuity)}/><M label='Φ plasticity' value={fmt(record.metrics.plasticity)}/><M label='q contradiction' value={fmt(record.metrics.contradiction)}/><M label='Λ burden' value={fmt(record.metrics.burden)}/><M label='scar' value={fmt(record.metrics.scar)}/><M label='evidence' value={fmt(record.metrics.evidence)}/></div><div className='r28-route-strip'><button onClick={()=>onAddress(next)}><Route/><span><b>Admitted next</b><small>{record.stateId} → {nextRecord.stateId}</small></span><ArrowRight/></button><button onClick={()=>onNavigate('Data Motion')}><Activity/><span><b>Inspect motion</b><small>derivatives / velocity / acceleration</small></span><ArrowRight/></button><button onClick={()=>onNavigate('Convergence')}><GitMerge/><span><b>Inspect convergence</b><small>candidate routes / proof stages</small></span><ArrowRight/></button></div><div className='special-boundary'><ShieldCheck/>Field is a source-packet visualization. Continuous geometry expresses modeled relationships; it does not manufacture external observations.</div></section>;
 if(variant==='Data Motion')return <section className='special-app r28-motion'><header className='special-head'><div><span>PERSISTENT PACKET · ROUTE DERIVATIVES · SOURCE → NEXT</span><h2>Data Motion</h2><p>The moving packet and changing field values are primary. The legacy vector/export instrument remains available below as an expert tool instead of covering the motion.</p></div><strong>Δ {delta>=0?'+':''}{delta}</strong></header><SpecialistMotionFieldR36 address={address} steps={22} label='DATA MOTION · ADMITTED STATES' mode='CANON' onAddress={onAddress}/><div className='r28-motion-hero'><section><span>ROUTE TRANSPORT</span><b>{record.stateId} <MoveRight/> {nextRecord.stateId}</b><small>D{coords.d+1}/P{coords.p+1}/R{coords.r+1}/L{coords.l+1} → D{nextCoords.d+1}/P{nextCoords.p+1}/R{nextCoords.r+1}/L{nextCoords.l+1}</small></section><div className='r28-motion-kpis'><M label='normalized velocity' value={fmt(velocity,6)} detail='Δ address / 20,736'/><M label='normalized acceleration' value={fmt(acceleration,6)} detail='route second-difference proxy'/><M label='previous Δ' value={String(prevDelta)} detail={`from STATE ${prevRecord.stateId}`}/></div></div><div className='r28-derivative-grid'>{Object.entries(derivative).map(([k,v])=><div key={k} className={Number(v)>0?'positive':Number(v)<0?'negative':'neutral'}><span>d{k}/route</span><b>{Number(v)>=0?'+':''}{fmt(v,5)}</b><i style={{width:`${Math.min(100,Math.abs(Number(v))*500)}%`}}/></div>)}</div><div className='r28-route-table'>{candidates.map((x,i)=><button key={`${x.kind}-${x.address}`} onClick={()=>onAddress(x.address)}><code>{String(i+1).padStart(2,'0')}</code><span><b>{x.kind}</b><small>STATE {x.record.stateId} · {x.record.metrics.decision}</small></span><strong>{fmt(x.score,3)}</strong><ArrowRight/></button>)}</div><details className='r36-disclosure'><summary>Expert Drive vector / SVG portability instrument</summary><DriveVectorField address={address} onCommit={onAddress}/></details><div className='special-boundary'><ShieldCheck/>Velocity and acceleration are normalized derivatives in OMEGA atlas address space, not claims of physical velocity or acceleration.</div></section>;
 const selectedCandidate=candidates.find(x=>x.address===selected)||candidates[0];
 return <section className='special-app r28-convergence'><header className='special-head'><div><span>PRESSURE → ADMISSION → CARRY → PROOF</span><h2>Convergence</h2><p>Convergence now starts with the packet’s admitted movement, then compares alternative endpoints and proof stages. It is a decision surface, not a wall of abstract pipeline labels.</p></div><strong>{valid.passed?'HOSTED PASS':'HOLD'}</strong></header><SpecialistMotionFieldR36 address={address} steps={20} label='CONVERGENCE · ADMITTED REFERENCE' mode='CONVERGENCE' onAddress={onAddress}/><div className='r28-convergence-summary'><M label='61.9B address' value={String(conv.address619)} detail={`chunk ${conv.parentChunk}`}/><M label='Mode188 ratio' value={fmt(conv.kernel.mode188Ratio)} detail={conv.kernel.mode188Decision}/><M label='water field' value={fmt(conv.kernel.waterField)} detail='modeled conductance field'/><M label='proof scar' value={fmt(conv.kernel.proofScar)} detail={`${valid.failed.length} failed stages`}/></div><div className='r28-convergence-layout'><aside className='r28-candidates'><div><Waypoints/><span><b>Alternative endpoints</b><small>Select a computed candidate, inspect its score, then commit only if wanted.</small></span></div>{candidates.map((x,i)=><button key={`${x.kind}-${x.address}`} aria-pressed={selected===x.address} className={selected===x.address?'active':''} onClick={()=>setSelected(x.address)}><code>{i+1}</code><span><b>{x.kind}</b><small>STATE {x.record.stateId} · score {fmt(x.score,3)} · {x.record.metrics.decision}</small></span></button>)}{selectedCandidate&&<button className='primary-action r28-commit' onClick={()=>onAddress(selectedCandidate.address)}>Commit selected STATE {selectedCandidate.record.stateId}<ArrowRight/></button>}</aside><details className='r36-disclosure' open><summary>Proof stages for selected computation</summary><section className='r28-stage-list'>{conv.stages.map((s:any)=><article key={s.phase} className={s.status.toLowerCase()}>{s.status==='PASS'||s.status==='HOSTED_PASS'?<CheckCircle2/>:<ShieldCheck/>}<code>{s.phase}</code><span><b>{s.name}</b><small>{s.metric}</small></span><strong>{s.status}</strong></article>)}</section></details></div><details className='r36-disclosure'><summary>Mode-family convergence scores</summary><div className='r28-family-strip'>{conv.families.map((f:any)=><div key={f.id} className={f.status.toLowerCase()}><code>{f.id}</code><b>{f.name}</b><span>{fmt(f.score,2)}</span></div>)}</div></details><div className='special-boundary'><ShieldCheck/>Convergence compares model-route candidates and proof stages. Selecting a route commits an atlas state only; it is not a claim of physical destiny or external causation.</div></section>
}
