import {useEffect,useMemo,useState} from 'react';
import {Activity,Cloud,Database,GitBranch,HardDrive,Network,RefreshCw,Route,ShieldCheck,Sparkles,Target,Workflow} from 'lucide-react';
import {api} from './platformAdapter';
import './omegaCorrelationMeshR184.css';

type Props={record:any;address:number;onNavigate:(panel:string)=>void};
type Plane={id:string;label:string;detail:string;state:string;authority:string;route:string;x?:number;y?:number};
const upper=(v:any)=>String(v??'UNPROVEN').toUpperCase();
const state=(v:any)=>{const s=upper(v);if(s.includes('LIVE')||s.includes('ONLINE'))return'LIVE';if(s.includes('VERIFIED')||s.includes('RETURNED')||s.includes('CLOSED'))return'VERIFIED';if(s.includes('READY')||s.includes('CURRENT')||s.includes('AVAILABLE'))return'READY';if(s.includes('HELD')||s.includes('DEGRADED')||s.includes('REQUIRED')||s.includes('PENDING'))return'HELD';return'UNPROVEN'};
const when=(v:any)=>{const d=new Date(v||0);return Number.isFinite(d.getTime())&&d.getTime()>0?d.toLocaleString():'unknown time'};
function local(key:string){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}

export default function OmegaCorrelationMeshR184({record,address,onNavigate}:Props){
 const[net,setNet]=useState<any>({}),[runs,setRuns]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[objective,setObjective]=useState('Correlate the current OMEGA world, evidence, swarm, federation, Hybrid and durable execution states; identify the smallest proof-bounded next operation without collapsing authority boundaries.'),[plan,setPlan]=useState<any>(null);
 const load=async()=>{setBusy(true);setMessage('');const paths=[['convergence','/api/system/convergence'],['hybrid','/api/hybrid/status'],['federation','/api/federation/run/status'],['autonomic','/api/swarm/autonomic/status'],['organism','/api/swarm/organism/status'],['swarm','/api/swarm/status'],['runs','/api/execution/runs']];const settled=await Promise.allSettled(paths.map(([,p])=>api.get<any>(p)));const next:any={};settled.forEach((r,i)=>{const key=paths[i][0];if(r.status==='fulfilled')next[key]=r.value.data;else next[key]={state:'UNPROVEN',error:String(r.reason||'unavailable')}});setNet(next);setRuns(Array.isArray(next.runs?.runs)?next.runs.runs:[]);setMessage('Current runtime planes refreshed independently. Missing planes remain unproven.');setBusy(false)};
 useEffect(()=>{void load()},[]);
 const world=local('omega.r175.worldTruthSurface'),resolution=local('omega.r178.contractResolution'),authorization=local('omega.r179.authorizationReceipt'),dispatch=local('omega.r180.executionReceipt');
 const pcOnline=Boolean(net.hybrid?.nativeExecutionClaimed===true&&Array.isArray(net.hybrid?.devices)&&net.hybrid.devices.some((d:any)=>d?.online&&!d?.revoked));
 const verifiedRuns=runs.filter((x:any)=>String(x?.state||x?.status||'').toUpperCase().includes('VERIFIED'));
 const planes=useMemo<Plane[]>(()=>[
  {id:'CANON',label:'Canonical Worker',detail:'R183 API authority',state:state(net.convergence?.canonical?.state),authority:'FIRST-HAND WORKER LIVENESS',route:'System'},
  {id:'WORLD',label:'Living World',detail:'R175/R182 continuity',state:world?.eventAccepted?'VERIFIED':'UNPROVEN',authority:'LOCAL WORLD RECEIPT + R134/R182 LAW',route:'Convergence'},
  {id:'GENESIS',label:'Genesis',detail:'proposal machine',state:state(net.convergence?.proposal?.effectiveState||net.federation?.nodes?.genesis?.state),authority:'PROPOSE ONLY',route:'Convergence'},
  {id:'OPTICAL',label:'Optical',detail:'screen / full-wave gate',state:state(net.convergence?.optical?.effectiveScreenState||net.federation?.nodes?.optical?.state),authority:'SCREEN ONLY',route:'Convergence'},
  {id:'DIRECT',label:'Direct Swarm',detail:'R121 cells',state:state(net.swarm?.state||net.swarm?.ok?'READY':'UNPROVEN'),authority:'BOUNDED CELL EXECUTION',route:'Convergence'},
  {id:'ORGANISM',label:'Organism',detail:'R123 hierarchy',state:state(net.organism?.state||net.organism?.ok?'READY':'UNPROVEN'),authority:'HIERARCHICAL SWARM',route:'Convergence'},
  {id:'AUTONOMIC',label:'Autonomic',detail:'R125 planner/admission',state:state(net.autonomic?.state||net.autonomic?.ok?'READY':'UNPROVEN'),authority:'SOLE CANON ADMISSION',route:'Convergence'},
  {id:'FED',label:'Federation',detail:'typed handoff ledger',state:state(net.federation?.state||net.federation?.ok?'READY':'UNPROVEN'),authority:'HANDOFF / RECEIPT',route:'Evidence & Proof'},
  {id:'HYBRID',label:'Hybrid Host',detail:'authenticated heartbeat',state:pcOnline?'LIVE':'HELD',authority:'DEVICE PROOF REQUIRED',route:'Hybrid Link'},
  {id:'AUTH',label:'Authorization',detail:'R179 durable authorization',state:authorization?'VERIFIED':resolution?'HELD':'UNPROVEN',authority:'AUTHORIZATION ≠ EXECUTION',route:'Convergence'},
  {id:'DISPATCH',label:'Dispatch',detail:'R180 governed dispatch',state:dispatch?'VERIFIED':authorization?'HELD':'UNPROVEN',authority:'RETURN PROOF SEPARATE',route:'Convergence'},
  {id:'RUNS',label:'Durable Runs',detail:`${runs.length} visible · ${verifiedRuns.length} verified`,state:verifiedRuns.length?'VERIFIED':runs.length?'READY':'UNPROVEN',authority:'R146 LIFECYCLE',route:'Evidence & Proof'}
 ],[net,pcOnline,world,authorization,resolution,dispatch,runs.length,verifiedRuns.length]);
 const graph=useMemo(()=>{const cx=360,cy=205,rx=285,ry=150;return planes.map((p,i)=>({...p,x:cx+Math.cos(-Math.PI/2+i/planes.length*Math.PI*2)*rx,y:cy+Math.sin(-Math.PI/2+i/planes.length*Math.PI*2)*ry}))},[planes]);
 const correlated=planes.filter(p=>p.state==='LIVE'||p.state==='VERIFIED'||p.state==='READY').length,held=planes.filter(p=>p.state==='HELD').length;
 const timeline=useMemo(()=>{const rows:any[]=[];if(world?.worldId||world?.sourceRevision)rows.push({kind:'WORLD',time:Date.now(),title:`${world?.sourceRevision||'R175'} world surface`,state:world?.eventAccepted?'VERIFIED':'UNPROVEN'});if(authorization?.createdAt||authorization?.authorizedAt)rows.push({kind:'AUTH',time:authorization.createdAt||authorization.authorizedAt,title:authorization?.missionId||'R179 authorization',state:'AUTHORIZED'});if(dispatch?.createdAt||dispatch?.dispatchedAt||dispatch?.verifiedAt)rows.push({kind:'DISPATCH',time:dispatch.createdAt||dispatch.dispatchedAt||dispatch.verifiedAt,title:dispatch?.missionId||dispatch?.operationId||'R180 dispatch',state:'RECEIPT'});for(const r of runs.slice(0,16)){const t=r?.updatedAt||r?.createdAt||r?.transitionedAt;if(t)rows.push({kind:'RUN',time:t,title:r.id||r.runId||'durable run',state:r.state||r.status||'UNKNOWN'})}return rows.sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime()).slice(0,14)},[runs,world,authorization,dispatch]);
 const preview=async()=>{if(!objective.trim()||busy)return;setBusy(true);setMessage('');try{const evidence=[world?.worldId?{id:'r184-world-local',type:'WORLD_TRUTH',summary:`R175 world ${world.worldId} · ${world.sourceRevision||''}`,authority:'LOCAL_RECEIPT_NOT_SERVER_LIVENESS'}:null,dispatch?{id:'r184-dispatch-local',type:'DISPATCH_RECEIPT',summary:'R180 local dispatch receipt is present',authority:'LOCAL_RECEIPT_REQUIRES_RETURN_PROOF'}:null].filter(Boolean);const r=await api.post<any>('/api/swarm/autonomic/plan',{intent:objective,mode:'AUTO',projection:'UNIFIED',providerBudget:0,reconvergeWithAI:false,metrics:record?.metrics||{},evidence});setPlan(r.data?.plan||r.data);setMessage('R125 route preview returned. This mesh did not create, authorize or dispatch a mission.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 return <section className='r184-mesh' aria-label='R184 whole-system operational correlation mesh'>
  <header className='r184-mesh-head'><div><span>R184 · WHOLE-SYSTEM OPERATIONAL MESH</span><h2>One live authority graph instead of disconnected status cards.</h2><p>Canonical runtime, world truth, swarm topology, federation, device proof, durable authorization, dispatch and returned execution remain separate authorities but are visible in one correlated operating frame.</p></div><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/>Refresh all planes</button></header>
  <div className='r184-mesh-summary'><article><Network/><span>Correlated planes</span><b>{correlated}/{planes.length}</b><small>live, verified or ready</small></article><article><ShieldCheck/><span>Proof-gated planes</span><b>{held}</b><small>not silently promoted</small></article><article><HardDrive/><span>Native host</span><b>{pcOnline?'LIVE':'HELD'}</b><small>authenticated heartbeat only</small></article><article><Database/><span>Durable runs</span><b>{runs.length}</b><small>{verifiedRuns.length} verified-state rows</small></article></div>
  <div className='r184-mesh-stage'><section className='r184-mesh-orbit'><header><div><span>AUTHORITY TOPOLOGY</span><b>Current observed state across 12 execution/proof planes</b></div><code>ATLAS {address} · R183 base → R184 correlation</code></header><svg viewBox='0 0 720 410' role='img' aria-label='OMEGA operational authority topology'>{graph.map(n=><line key={`edge-${n.id}`} x1='360' y1='205' x2={n.x} y2={n.y} className={`link state-${n.state.toLowerCase()}`}/>)}<g className='core'><circle cx='360' cy='205' r='62'/><circle cx='360' cy='205' r='48'/><text x='360' y='199'>OMEGA</text><text x='360' y='217' className='sub'>R183/R184</text></g>{graph.map(n=><g key={n.id} transform={`translate(${n.x} ${n.y})`} className={`plane state-${n.state.toLowerCase()}`} onClick={()=>onNavigate(n.route)}><circle r='36'/><circle r='29' className='inner'/><text y='-3'>{n.id}</text><text y='14' className='sub'>{n.state}</text><title>{`${n.label} · ${n.detail} · ${n.authority}`}</title></g>)}</svg><footer><span><i className='live'/>LIVE</span><span><i className='verified'/>VERIFIED</span><span><i className='ready'/>READY</span><span><i className='held'/>HELD</span><span><i className='unproven'/>UNPROVEN</span></footer></section>
   <aside className='r184-mesh-matrix'><header><span>AUTHORITY MATRIX</span><b>Click a row to open its working surface</b></header><div>{planes.map(p=><button key={p.id} data-state={p.state} onClick={()=>onNavigate(p.route)}><i>{p.id}</i><span><b>{p.label}</b><small>{p.detail}</small></span><strong>{p.state}</strong><em>{p.authority}</em></button>)}</div></aside>
  </div>
  <section className='r184-mesh-command'><div className='r184-mesh-objective'><span>PROOF-BOUNDED CORRELATION OBJECTIVE</span><textarea value={objective} onChange={e=>setObjective(e.target.value)}/><div><button onClick={()=>void preview()} disabled={busy||!objective.trim()}><Target/>Compile R125 route preview</button><button onClick={()=>onNavigate('Hybrid Link')}><HardDrive/>Host execution</button><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Proof ledger</button></div></div><aside><span>COMPILED NEXT ROUTE</span>{plan?<><b>{plan?.decision||'PLAN'} · {plan?.projection||'UNIFIED'}</b><strong>{plan?.totalCells??plan?.cells??'—'} cells · {plan?.totalBranches??'—'} branches</strong><code>{String(plan?.fingerprint||plan?.planHash||'runtime plan returned').slice(0,72)}</code><small>Provider budget 0. Preview only.</small></>:<p>No preview compiled yet. Existing R126 mission controls remain intact below this mesh.</p>}</aside></section>
  <section className='r184-mesh-timeline'><header><div><span>DURABLE / LOCAL RECEIPT TIMELINE</span><b>Returned server lifecycle rows and local world/authorization/dispatch receipts stay distinguishable.</b></div></header><div>{timeline.map((x,i)=><article key={`${x.kind}-${x.time}-${i}`}><i>{x.kind}</i><span><b>{x.title}</b><small>{upper(x.state)}</small></span><time>{when(x.time)}</time></article>)}{!timeline.length&&<p>No timestamped durable or local receipts are visible in this session.</p>}</div></section>
  {message&&<div className='r184-mesh-message'>{message}</div>}
  <footer className='r184-mesh-proof'><ShieldCheck/><p><b>Truth boundary:</b> this surface correlates status and receipts; it does not merge their authority. R125 remains sole CanonState admission authority. R147 dispatch, R146 lifecycle, R134/R182 world continuity, current Hybrid heartbeat, and returned external proof remain distinct.</p></footer>
 </section>;
}
