import {useMemo,useState} from 'react';
import {Eye,FastForward,Orbit,Pause,Play,Rotate3d,ShieldCheck,Waypoints} from 'lucide-react';
import CalculusTraversal from './CalculusTraversal';
import {corpusState,decodeAddress} from './corpusRuntime';

type Props={variant:'Immersive Traversal'|'Extreme Traversal'|'Traversal';address:number;state:any;onAddress:(n:number)=>void};
const CAMERAS=['ORBIT','INWARD_DIVE','SHELL_FOLLOW','HOST_CENTERED','PROOF_FOLLOW','REPLAY_FOLLOW','FREE'] as const;
const ROUTES=['CONTINUOUS_SHELL','HELICAL','SYMMETRY_CORRIDOR','ASYMMETRY_STRESS','TARGET_LOCK'] as const;
export default function OmegaTraversalStudio({variant,address,state,onAddress}:Props){const[camera,setCamera]=useState<(typeof CAMERAS)[number]>(variant==='Immersive Traversal'?'INWARD_DIVE':variant==='Extreme Traversal'?'SHELL_FOLLOW':'ORBIT'),[route,setRoute]=useState<(typeof ROUTES)[number]>(variant==='Extreme Traversal'?'ASYMMETRY_STRESS':'HELICAL'),[playing,setPlaying]=useState(true),r=corpusState(address),coords=decodeAddress(address);const corridor=useMemo(()=>{const rows=[] as any[];let n=address;for(let i=0;i<12;i++){const x=corpusState(n);rows.push(x);n=x.autoPing.dataNext}return rows},[address]);return <section className={'special-app traversal-studio '+variant.toLowerCase().replaceAll(' ','-')}><header className='special-head'><div><span>TRAVERSAL KERNEL · IDENTITY PRESERVED</span><h2>{variant}</h2></div><div className='special-status'><b>{camera}</b><small>{route}</small></div></header><div className='traversal-toolbar'><div>{CAMERAS.map(x=><button key={x} className={camera===x?'active':''} onClick={()=>setCamera(x)}><Eye/>{x}</button>)}</div><div>{ROUTES.map(x=><button key={x} className={route===x?'active':''} onClick={()=>setRoute(x)}><Waypoints/>{x}</button>)}</div></div><div className='traversal-stage'><CalculusTraversal state={{...state,viewportMode:variant==='Immersive Traversal'?'IMMERSIVE':variant==='Extreme Traversal'?'EXTREME':'CANON_FIELD'}} onSelect={(c:any)=>onAddress(1728*c.d+144*c.p+12*c.r+c.l)}/><aside className='traversal-hud'><Orbit/><b>STATE {r.stateId}</b><span>D{coords.d} P{coords.p} R{coords.r} L{coords.l}</span><small>CΩ {r.metrics.continuity.toFixed(3)} · q {r.metrics.contradiction.toFixed(3)}</small></aside></div><div className='corridor-strip'>{corridor.map((x,i)=><button key={i} onClick={()=>onAddress(x.address)} className={x.metrics.decision.toLowerCase()} style={{height:`${28+x.metrics.continuity*52}px`}}><span>{i}</span><small>{x.stateId}</small></button>)}</div><div className='instrument-controls'><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause/>:<Play/>}{playing?'Pause route':'Resume route'}</button><button onClick={()=>onAddress(r.autoPing.previous)}><Rotate3d/>Previous</button><button className='gold' onClick={()=>onAddress(r.autoPing.dataNext)}><FastForward/>Admitted next</button><span><ShieldCheck/> model traversal · not scene swapping</span></div></section>}
