import {OMEGA_CAPABILITY_AUTHORITY,capabilityReality,type CapabilityReality} from './capabilityAuthority';
import {FAMILIES,MASTER_MENUS} from './systemAtlasRuntime';

// R45 remains the schema lineage for the operational-capability record. R168 is the current authority/performance revision.
export const OPERATIONAL_CAPABILITY_SCHEMA='OMEGA_OPERATIONAL_CAPABILITY_R45' as const;
export const OPERATIONAL_CAPABILITY_REVISION='R168' as const;
export const PERFORMANCE_FABRIC_REVISION='R168' as const;
export type PerformanceClass='LIGHT'|'NORMAL'|'HEAVY'|'EXTREME';
export type PersistenceClass='NONE'|'LOCAL'|'PACKET'|'EVIDENCE';
export type ExecutionContract={name:string;familyId:string;reality:CapabilityReality;routable:boolean;performance:PerformanceClass;persistence:PersistenceClass;input:string;output:string;degradeTo:string;proof:string};
const FAMILY_ALIAS:Record<string,string>={'AI Cockpit':'S22','Hybrid Link':'S03','Atlas OS':'S00','Traversal / Domain':'S06','Reality Compiler':'S01','Field Renderer':'S08','Observer / Now':'S19','Earth':'S09','Dewey':'S14','Atlas Generator':'S06','Living Membrane':'S13','Persistent Packet':'S02','Proof / Governance':'S15','Recovery / Packaging':'S20','Rendering / Media':'S21','Dewey / Mode188':'S14','Proof Ledger':'S15','Artifact Governance':'S20','CanonForge':'S04','Universal Language':'S18','Control Planes':'S22'};
const HEAVY=new Set(['Matter Traversal','Visual Instrument','Earth Now','Atlas','Reality Lab','Immersive Traversal','Extreme Traversal','Traversal']);
const EXTREME=new Set(['Matter Traversal','Visual Instrument','Extreme Traversal']);
const LOCAL=new Set(['Workspace','Create','Projects','Render Queue','Assets','Memory','Consolidation','Plugins','Settings','Build Out']);
const EVIDENCE=new Set(['Evidence & Proof','Validation','Quality Compiler','Governance','Archive Census','Archive Operators','System','Earth Now','Reality Lab']);
export function familyIdForCapability(family:string){return FAMILY_ALIAS[family]||'S00'}
export function effectiveCapabilityReality(name:string):CapabilityReality{return capabilityReality(name)}
export function capabilityExecutionContract(name:string):ExecutionContract{const c=OMEGA_CAPABILITY_AUTHORITY.find(x=>x.name===name);if(!c)throw new Error(`Unknown capability: ${name}`);const reality=capabilityReality(name),routable=reality!=='DONOR_ONLY'&&reality!=='RESTORATION_DEBT';const performance:PerformanceClass=EXTREME.has(name)?'EXTREME':HEAVY.has(name)?'HEAVY':'NORMAL';const persistence:PersistenceClass=EVIDENCE.has(name)?'EVIDENCE':LOCAL.has(name)?'LOCAL':c.boundary==='SOURCE_PACKET'?'PACKET':'NONE';return{name,familyId:familyIdForCapability(c.family),reality,routable,performance,persistence,input:c.boundary,output:c.purpose,degradeTo:routable?name:'System Atlas',proof:`${c.implementation} · ${c.boundary} · ${reality} · current reality R168`}}
export const OPERATIONAL_CAPABILITIES=OMEGA_CAPABILITY_AUTHORITY.map(x=>capabilityExecutionContract(x.name));
export function operationalCapabilityAudit(){const familyIds=new Set(FAMILIES.map(x=>x.id)),mappedFamilies=new Set(OPERATIONAL_CAPABILITIES.map(x=>x.familyId));const missingFamilyMappings=[...mappedFamilies].filter(x=>!familyIds.has(x));const duplicateNames=OPERATIONAL_CAPABILITIES.filter((x,i,a)=>a.findIndex(y=>y.name===x.name)!==i).map(x=>x.name);const unroutable=OPERATIONAL_CAPABILITIES.filter(x=>!x.routable).map(x=>x.name);const menuTargets=MASTER_MENUS.map(x=>x[2]),missingMenuTargets=menuTargets.filter(x=>!OPERATIONAL_CAPABILITIES.some(c=>c.name===x));const routedFamilies=new Set(OPERATIONAL_CAPABILITIES.filter(x=>x.routable).map(x=>x.familyId));const inventoryFamiliesWithoutRoute=FAMILIES.filter(x=>!routedFamilies.has(x.id)).map(x=>x.id);const currentRestorationDebt=OPERATIONAL_CAPABILITIES.filter(x=>['RESTORATION_DEBT','DONOR_ONLY'].includes(x.reality)).map(x=>x.name);return{schema:OPERATIONAL_CAPABILITY_SCHEMA,revision:OPERATIONAL_CAPABILITY_REVISION,total:OPERATIONAL_CAPABILITIES.length,routable:OPERATIONAL_CAPABILITIES.filter(x=>x.routable).length,gated:OPERATIONAL_CAPABILITIES.filter(x=>['EVIDENCE_GATED','DEVICE_GATED','PROVIDER_GATED'].includes(x.reality)).length,local:OPERATIONAL_CAPABILITIES.filter(x=>x.reality==='LOCAL_ACTIVE').length,source:OPERATIONAL_CAPABILITIES.filter(x=>x.reality==='SOURCE_ACTIVE'||x.reality==='RUNTIME_ACTIVE').length,currentRestorationDebt,unroutable,duplicateNames,missingFamilyMappings,missingMenuTargets,inventoryFamiliesWithoutRoute,pass:duplicateNames.length===0&&missingFamilyMappings.length===0&&missingMenuTargets.length===0&&currentRestorationDebt.length===0,boundary:'R168 audits one current capability-reality authority while preserving the R45 record schema. Historical debt remains predecessor evidence only. A routable capability can still be evidence-, provider-, device-, or local-artifact-gated; routing is not proof of external execution.'}}
function detectWebGL2(){if(typeof document==='undefined')return false;try{return Boolean(document.createElement('canvas').getContext('webgl2',{powerPreference:'high-performance'} as any))}catch{return false}}
export function capabilityPerformanceHints(name:string){const c=capabilityExecutionContract(name);const nav=typeof navigator!=='undefined'?(navigator as Navigator&{deviceMemory?:number}):null;const cores=Math.max(1,Number(nav?.hardwareConcurrency||4)),memoryGb=Math.max(0,Number(nav?.deviceMemory||0));const reduced=typeof window!=='undefined'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;const coarse=typeof window!=='undefined'&&window.matchMedia('(pointer: coarse)').matches;const width=typeof window!=='undefined'?window.innerWidth:1280,height=typeof window!=='undefined'?window.innerHeight:720,dpr=typeof window!=='undefined'?Math.min(3,window.devicePixelRatio||1):1;const pixels=width*height*dpr*dpr,webgl2=detectWebGL2(),hidden=typeof document!=='undefined'&&document.visibilityState==='hidden';const constrained=cores<=4||(memoryGb>0&&memoryGb<=4)||pixels>9_500_000;const highCapacity=cores>=8&&(memoryGb===0||memoryGb>=8)&&webgl2&&!coarse;const lowPower=coarse||constrained;const quality=reduced?'STATIC':highCapacity?'MAXIMUM':lowPower?'CONSERVE':'BALANCED';const targetFps=reduced?0:hidden?10:highCapacity?60:lowPower?30:c.performance==='EXTREME'?50:60;const renderDensity=reduced ? .72 : highCapacity ? 1 : lowPower ? .62 : c.performance==='EXTREME' ? .88 : 1;const particleScale=reduced ? .35 : highCapacity ? (c.performance==='EXTREME'?1.15:1.08) : lowPower ? .55 : c.performance==='EXTREME' ? .82 : 1;const idleChunk=highCapacity?512:lowPower?96:256;const frameBudgetMs=targetFps>0?Math.max(8,1000/targetFps):0;return{revision:PERFORMANCE_FABRIC_REVISION,class:c.performance,quality,cores,memoryGb,webgl2,coarsePointer:coarse,devicePixelRatio:dpr,viewportPixels:pixels,highCapacity,lowPower,reducedMotion:reduced,hidden,targetFps,renderDensity,particleScale,idleChunk,frameBudgetMs,boundary:'Performance hints change scheduling/density only. R168 additionally adapts sampling, particle budget and frame cadence; canonical state, calculus, evidence, route authority and proof semantics remain invariant. Capable desktops target full-density 60 Hz; constrained/mobile surfaces adapt without inventing lower-fidelity state.'}}
