const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:H});
const text=v=>String(v??'').trim();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
async function sha256(value){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function validProposal(p){return p?.schema==='OMEGA_PACKET_v1'&&p?.source_node==='omega-genesis'&&p?.geometry&&Number(p?.wavelength_nm)>0}
function geometryOk(g){const p=Number(g?.pitch_nm),w=Number(g?.width_nm),l=Number(g?.length_nm),h=Number(g?.height_nm);return [p,w,l,h].every(Number.isFinite)&&p>0&&w>0&&l>0&&h>0&&w<=p&&l<=p}
async function screen(body){const proposal=body?.proposal;if(!validProposal(proposal)||!geometryOk(proposal.geometry))return json({ok:false,code:'INVALID_GENESIS_PROPOSAL'},400);const g=proposal.geometry,p=Number(g.pitch_nm),w=Number(g.width_nm),l=Number(g.length_nm),h=Number(g.height_nm),wl=Number(proposal.wavelength_nm),fill=clamp((w*l)/(p*p),0,1),aspect=h/Math.max(1,p),phaseRaw=((2*Math.PI*2.4*h/wl)*180/Math.PI)%360,target=Number.isFinite(Number(proposal.target_phase_deg))?Number(proposal.target_phase_deg):0,phaseError=Math.min(Math.abs(phaseRaw-target),360-Math.abs(phaseRaw-target)),estimatedEfficiency=clamp((1-Math.abs(fill-.42)*1.6)*(1-Math.min(phaseError,180)/360),0,1),crosstalk=clamp(Math.abs(fill-.42)*.8+Math.abs(aspect-1.5)*.12,0,1),continuity=clamp(.55+.35*estimatedEfficiency,0,1),burden=clamp(.15+.35*crosstalk,0,1),contradiction=clamp(.08+.5*crosstalk+.25*(phaseError/180),0,1),scar=clamp(.15*crosstalk+.1*(phaseError/180),0,1),mode188=Number((1+estimatedEfficiency*.28-contradiction*.12).toFixed(6)),gate=mode188>=1.05&&contradiction<.75?'STAY':'TURN',screenHash=await sha256({proposal:proposal.packet_id,fill,phaseError,estimatedEfficiency,crosstalk}),packet={...proposal,packet_id:'opt_'+screenHash.slice(0,24),source_node:'omega-optical',source_sha:screenHash,scalar_metrics:{scalar_focus:Number((1-phaseError/180).toFixed(6)),phase_error_deg:Number(phaseError.toFixed(6)),estimated_efficiency:Number(estimatedEfficiency.toFixed(6)),crosstalk:Number(crosstalk.toFixed(6)),mode188_score:mode188,fill_fraction:Number(fill.toFixed(6))},proof:{gate,mode188_score:mode188,continuity:Number(continuity.toFixed(6)),burden:Number(burden.toFixed(6)),contradiction:Number(contradiction.toFixed(6)),scar:Number(scar.toFixed(6))},scar:[...(proposal.scar||[]),{type:'REDUCED_ORDER_SCREEN',phase_error_deg:Number(phaseError.toFixed(6)),crosstalk:Number(crosstalk.toFixed(6))}],requested_solver:'rcwa',lineage:[...(proposal.lineage||[]),`omega-optical:r115:${screenHash.slice(0,16)}`],material_model:{n_incident:1,n_feature:2.4,n_background:1,n_substrate:1.46},numerics:{nx:48,ny:48,harmonics_low:25,harmonics_high:49,convergence_tolerance:.04,energy_tolerance:.04},truth_boundary:'R115 Optical SCREEN is a reduced-order computational ranking model. It is not RCWA/FDTD/FEM and not fabrication or measurement validation.'};const tier2_job={schema:'OMEGA_FULLWAVE_QUEUE_v1',job_id:'r115_'+screenHash.slice(0,20),source_packet_id:packet.packet_id,solver:'rcwa',geometry:packet.geometry,wavelength_nm:packet.wavelength_nm,polarization:packet.polarization||'s',material_model:packet.material_model,numerics:packet.numerics,proof:packet.proof,lineage:[...packet.lineage,'omega-optical:r115:tier2-request'],priority:Number((.45+.5*estimatedEfficiency).toFixed(6))};return json({ok:true,service:'OMEGA Optical Machine R115',version:'R115.0',authority:'SCREEN_ONLY',packet,tier2_job})}
export default{async fetch(request){const u=new URL(request.url);if(u.pathname==='/api/health')return json({ok:true,service:'OMEGA Optical Machine R115',version:'R115.0',authority:'SCREEN_ONLY',truth_boundary:'Reduced-order screening only; full-wave validation remains Sovereign RCWA/FDTD/FEM gated.'});if(u.pathname==='/api/federation/screen'&&request.method==='POST')return screen(await request.json().catch(()=>({})));return json({ok:false,code:'NOT_FOUND'},404)}};
