import {corpusState} from './corpusRuntime';
import type {Mandala20736Field} from './mandala20736Runtime';
import type {CompilerLineageId} from './compilerLineageRuntime';
export type SpineView='FIELD'|'OCCUPANCY'|'PREDICTION'|'XRAY';
export const SPINE_VIEWS:SpineView[]=['FIELD','OCCUPANCY','PREDICTION','XRAY'];
const cl=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
export function compilePcExecutionSpine(address:number,lineage:CompilerLineageId,depthLabel:string,lens:string){const r=corpusState(address),m=r.metrics,g=r.geometry,p=r.predict,a=r.autoPing,epsilon=.05,kernel=(Number(m.continuity)*Number(m.plasticity))/(Number(m.contradiction)+Number(m.burden)+epsilon);return{version:'PC_EXECUTION_SPINE_ADAPTED_V2',source:'CANON CONSOLE OMEGA v7 integration report',stages:[
{id:'CAMERA',label:'camera',value:depthLabel,detail:`lineage ${lineage}`},
{id:'FEATURE',label:'feature field',value:Number(m.geometry).toFixed(3),detail:`motion ${Number(r.math.normalizedMotionRelativity).toFixed(3)} · symmetry ${Number(g.symmetry).toFixed(3)}`},
{id:'CANON',label:'canon state',value:String(r.stateId),detail:`CΩ ${Number(m.continuity).toFixed(3)} · Φ ${Number(m.plasticity).toFixed(3)} · q ${Number(m.contradiction).toFixed(3)} · Λ ${Number(m.burden).toFixed(3)}`},
{id:'ATLAS',label:'runtime atlas sample',value:String(address+1),detail:`next ${Number(a.dataNext)+1} · evidence ${Number(m.evidence).toFixed(3)}`},
{id:'KERNEL',label:'unified kernel',value:kernel.toFixed(3),detail:`${m.decision} · ${lens}`},
{id:'LEARNING',label:'adaptive learning',value:Number(p.forecastScore).toFixed(3),detail:`reconstruct ${Number(p.reconstructability).toFixed(3)} · scar ${Number(m.scar).toFixed(3)}`},
{id:'RENDER',label:'renderer / panels',value:'BOUND',detail:'source packet → semantic camera'}],kernel,boundary:'Adapted browser execution spine. It preserves the archived stage order and current corpus correspondence; it is not a claim that every historical native package is fully code-merged.'}}
export function spineViewWeight(f:Mandala20736Field,i:number,view:SpineView,base:number){if(view==='OCCUPANCY')return cl(.18*base+.28*f.geometry[i]+.18*f.C[i]+.14*f.evidence[i]+.12*(1-f.q[i])+.10*f.symmetry[i]);if(view==='PREDICTION')return cl(.18*base+.24*f.forecast[i]+.18*f.continuityGate[i]+.15*f.Phi[i]+.12*f.evidence[i]+.08*f.motionDrive[i]+.05*(1-f.route[i]));if(view==='XRAY')return cl(.14*base+.24*f.geometry[i]+.20*f.symmetry[i]+.18*f.evidence[i]+.12*(1-f.q[i])+.07*f.scar[i]+.05*f.motion[i]);return cl(base)}
export type TrajectoryStep={address:number;stateId:number;decision:string;C:number;Phi:number;q:number;Lambda:number;evidence:number;gate:number;drive:number;closure:number};
export function compileSourceTrajectory(field:Mandala20736Field,start:number,maxSteps=48){const path:TrajectoryStep[]=[];const seen=new Set<number>();let a=Math.max(0,Math.min(field.count-1,Math.floor(start)));for(let step=0;step<maxSteps;step++){if(seen.has(a))break;seen.add(a);const r=corpusState(a),closure=cl(.34*field.continuityGate[a]+.22*field.evidence[a]+.18*(1-field.q[a])+.14*(1-field.Lambda[a])+.12*(1-field.motionDrive[a]));path.push({address:a,stateId:a+1,decision:String(r.metrics.decision),C:field.C[a],Phi:field.Phi[a],q:field.q[a],Lambda:field.Lambda[a],evidence:field.evidence[a],gate:field.continuityGate[a],drive:field.motionDrive[a],closure});const n=Number(field.routeNext[a]);if(!Number.isFinite(n)||n===a||n<0||n>=field.count)break;a=n}const final=path[path.length-1],first=path[0],delta=final&&first?final.closure-first.closure:0;return{version:'PC_ROUTE_STEERING_V1',source:'canon_omega_align + canon_phase3_steering + canon_omega_closure adapted to source routeNext graph',path,closed:path.length>1&&path[path.length-1].closure>=.72,closureDelta:delta,best:path.reduce((a,b)=>!a||b.closure>a.closure?b:a,null as TrajectoryStep|null),boundary:'Trajectory follows the embedded source route graph/AutoPing relation. It is a computational state-space route, not measured physical time or unconstrained autonomous action.'}}
export function trajectoryDecision(step:TrajectoryStep){if(step.closure>=.72&&step.q<.35)return'STAY';if(step.closure>=.48&&step.Lambda<.72)return'TURN';return'ESCALATE'}
export function appendSpineLedger(packet:{version:string;stages:any[]},address:number,lineage:CompilerLineageId,view:SpineView){if(typeof localStorage==='undefined')return;const key='omega.pc.spine.ledger';let old:any[]=[];try{old=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const entry={ts:new Date().toISOString(),address,stateId:address+1,lineage,view,version:packet.version,kernel:packet.stages.find(x=>x.id==='KERNEL')?.value};localStorage.setItem(key,JSON.stringify([...old,entry].slice(-188)))}
