import {useEffect,useMemo,useState} from 'react';
import {Activity,BrainCircuit,ChevronRight,Command,Earth,Eye,FolderOpen,Home,Layers3,Link2,Menu,Search,Settings2,ShieldCheck,X} from 'lucide-react';
import {R57_WORKSPACES,r57WorkspaceForSurface,type R57WorkspaceId} from './productConvergenceR57';
import {CAPABILITY_REALITY_LABEL} from './capabilityAuthority';
import {effectiveCapabilityReality} from './operationalCapabilityRuntimeR45';
import {RUNTIME_IDENTITY} from './runtimeIdentity';
import type {OmegaUiMode} from './SingleFrameRuntimeShellR27';
import './productRuntimeR57.css';

type Props={uiMode:OmegaUiMode;onUiMode:(mode:OmegaUiMode)=>void;panel:string;onNavigate:(panel:string)=>void;record:any;modePolicy:string;modeCount:number;busy:string};
const ICONS:Record<R57WorkspaceId,any>={COMMAND:Command,WORK:FolderOpen,HYBRID:Link2,REALITY:Eye,EARTH:Earth,VISUAL:Activity,INTELLIGENCE:BrainCircuit,EVIDENCE:ShieldCheck,BUILD:Layers3,SYSTEM:Settings2};
function compactMode(uiMode:OmegaUiMode){const[small,setSmall]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(max-width:960px)').matches);useEffect(()=>{const q=window.matchMedia('(max-width:960px)'),f=()=>setSmall(q.matches);f();q.addEventListener('change',f);return()=>q.removeEventListener('change',f)},[]);return uiMode==='MOBILE'||(uiMode==='AUTO'&&small)}
function WorkspaceButton({w,current,onClick}:{w:(typeof R57_WORKSPACES)[number];current:string;onClick:()=>void}){const I=ICONS[w.id];const reality=effectiveCapabilityReality(w.panel);return <button className={'r57-workspace-button '+(w.tools.includes(current)?'active':'')} onClick={onClick}><I/><span><b>{w.label}</b><small>{w.description}</small></span><em>{CAPABILITY_REALITY_LABEL[reality]}</em><ChevronRight/></button>}
function ToolList({workspace,panel,onNavigate}:{workspace:(typeof R57_WORKSPACES)[number];panel:string;onNavigate:(p:string)=>void}){return <div className='r57-tool-list'>{workspace.tools.map((name,i)=>{const reality=effectiveCapabilityReality(name);return <button key={name} className={name===panel?'active':''} onClick={()=>onNavigate(name)}><span><b>{name}</b><small>{i===0?'Primary workspace':'Integrated specialist tool'} · {CAPABILITY_REALITY_LABEL[reality]}</small></span><ChevronRight/></button>})}</div>}
function Desktop({panel,onNavigate,record,modeCount,busy}:Props){const current=r57WorkspaceForSurface(panel);const[selected,setSelected]=useState<R57WorkspaceId>(current.id);useEffect(()=>setSelected(current.id),[current.id]);const active=R57_WORKSPACES.find(x=>x.id===selected)||current;return <aside className='r57-shell desktop'><header><button onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))} aria-label='OMEGA home'><Home/></button><div><b>OMEGA</b><small>{RUNTIME_IDENTITY.hostedBuild} · {busy?'WORKING':'READY'}</small></div></header><div className='r57-runtime-summary'><span><i>STATE</i><b>{record?.stateId?.toLocaleString?.()||'—'}</b></span><span><i>DECISION</i><b>{record?.metrics?.decision||'—'}</b></span><span><i>MODES</i><b>{modeCount}</b></span></div><nav className='r57-workspaces'>{R57_WORKSPACES.map(w=><WorkspaceButton key={w.id} w={w} current={panel} onClick={()=>setSelected(w.id)}/>)}</nav><section className='r57-tools'><header><div><b>{active.label}</b><small>{active.tools.length} integrated function{active.tools.length===1?'':'s'}</small></div></header><ToolList workspace={active} panel={panel} onNavigate={onNavigate}/></section></aside>}
function Mobile({panel,onNavigate,record,modeCount,busy}:Props){const[open,setOpen]=useState(false),[q,setQ]=useState('');const current=r57WorkspaceForSurface(panel);const results=useMemo(()=>{const s=q.trim().toLowerCase();return s?R57_WORKSPACES.flatMap(w=>w.tools).filter(x=>x.toLowerCase().includes(s)):[]},[q]);const go=(p:string)=>{onNavigate(p);setOpen(false);setQ('')};return <><header className='r57-mobile-head'><button onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home/></button><div><b>OMEGA · {current.label}</b><small>{panel} · state {record?.stateId?.toLocaleString?.()||'—'} · {modeCount} modes</small></div><button onClick={()=>setOpen(true)}><Menu/></button></header><nav className='r57-mobile-bottom'><button onClick={()=>go('Command Center')}><Command/><span>Command</span></button><button onClick={()=>go('Workspace')}><FolderOpen/><span>Work</span></button><button onClick={()=>go('Matter Traversal')}><Eye/><span>Reality</span></button><button onClick={()=>go('Evidence & Proof')}><ShieldCheck/><span>Proof</span></button><button onClick={()=>setOpen(true)}><Menu/><span>More</span></button></nav>{open&&<div className='r57-drawer' role='dialog' aria-modal='true'><header><div><b>OMEGA WORKSPACES</b><small>{busy?'Action in progress · ':''}organized operational access</small></div><button onClick={()=>setOpen(false)}><X/></button></header><label><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder='Find a workspace or tool…'/></label>{q?<div className='r57-search-results'>{results.map(x=><button key={x} onClick={()=>go(x)}>{x}<ChevronRight/></button>)}</div>:<div className='r57-mobile-workspaces'>{R57_WORKSPACES.map(w=><section key={w.id}><WorkspaceButton w={w} current={panel} onClick={()=>go(w.panel)}/>{w.tools.length>1&&<details open={w.tools.includes(panel)}><summary>{w.tools.length-1} specialist tools</summary><ToolList workspace={w} panel={panel} onNavigate={go}/></details>}</section>)}</div>}</div>}</>}
export default function ProductRuntimeShellR57(props:Props){return compactMode(props.uiMode)?<Mobile {...props}/>:<Desktop {...props}/>}
