import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,CloudCog,RefreshCw,ShieldCheck,TriangleAlert} from 'lucide-react';
import {api,localState} from './platformAdapter';

type Sample={at:number;roundTripMs:number;workerTotalMs:number|null;packetMs:number|null;chainMs:number|null;provider:string;providerClass:string;proofHealth:string};
type Transition={at:number;from:string;to:string};
const packetCore=(record:any)=>({address:record?.address,stateId:record?.stateId,identity:record?.identity??null,metrics:record?.metrics??null,psc:record?.psc??null,predict:record?.predict??null,autoPing:record?.autoPing??null});
export default function ProofPerformanceProviderR55({record,frameHash,projectionView}:{record:any;frameHash?:string;projectionView?:string}){
 const[data,setData]=useState<any>({}),[busy,setBusy]=useState(false),[samples,setSamples]=useState<Sample[]>(()=>localState.read('omega.r55.performance.journal',[])),[transitions,setTransitions]=useState<Transition[]>(()=>localState.read('omega.r55.provider.transitions',[]));
 const run=useCallback(async()=>{setBusy(true);const start=performance.now();try{const segment=localState.read<any[]>('omega.r53.delta.mesh.journal',[]),r=await api.post<any>('/api/proof/performance',{packet:packetCore(record),projection:{view:projectionView||'FIELD',frameHash:frameHash||null},segment});const roundTripMs=Math.max(0,performance.now()-start),d=r.data||{};setData(d);const sample:Sample={at:Date.now(),roundTripMs:Math.round(roundTripMs*1000)/1000,workerTotalMs:Number.isFinite(d?.timing?.totalComputeMs)?d.timing.totalComputeMs:null,packetMs:Number.isFinite(d?.timing?.packetComputeMs)?d.timing.packetComputeMs:null,chainMs:Number.isFinite(d?.timing?.chainComputeMs)?d.timing.chainComputeMs:null,provider:String(d?.provider?.reported||'UNKNOWN'),providerClass:String(d?.provider?.class||'UNKNOWN_PROVIDER_STATE'),proofHealth:String(d?.proofHealth||'UNKNOWN')};setSamples(prev=>{const next=[...prev,sample].slice(-188);localState.write('omega.r55.performance.journal',next);return next});const prior=localState.read<string|null>('omega.r55.provider.last',null);if(prior&&prior!==sample.providerClass)setTransitions(prev=>{const next=[...prev,{at:sample.at,from:prior,to:sample.providerClass}].slice(-188);localState.write('omega.r55.provider.transitions',next);return next});localState.write('omega.r55.provider.last',sample.providerClass)}finally{setBusy(false)}},[record?.address,record?.stateId,frameHash,projectionView]);
 useEffect(()=>{void run();const id=window.setInterval(()=>void run(),30000);return()=>window.clearInterval(id)},[run]);
 const stats=useMemo(()=>{const xs=samples.slice(-30).map(x=>x.roundTripMs).filter(Number.isFinite).sort((a,b)=>a-b);const avg=xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0,p95=xs.length?xs[Math.min(xs.length-1,Math.floor(xs.length*.95))]:0;return{avg,p95}},[samples]);
 const healthy=data?.proofHealth==='COHERENT',providerClass=String(data?.provider?.class||'AWAITING_PROVIDER');
 return <section className='r50-delta-ledger' data-r55-provider={providerClass}>
  <header>{healthy?<ShieldCheck/>:<TriangleAlert/>}<div><b>B011 proof/performance + B007 provider recovery · R55</b><small>measured Worker compute + browser round trip · native-PC performance is not measured here · provider transitions observed, never silently mutated</small></div><button onClick={()=>void run()} disabled={busy} aria-label='Refresh proof performance'><RefreshCw className={busy?'spin':''}/></button></header>
  <div><article><code>PROOF HEALTH</code><span><b>{data?.proofHealth||'AWAITING_PROOF'}</b></span><small>packet {data?.packet?.valid===true?'valid':'waiting'} · chain {data?.chain?.health||'no segment'}</small></article><article><code>WORKER COMPUTE</code><span><b>{Number.isFinite(data?.timing?.totalComputeMs)?`${data.timing.totalComputeMs} ms`:'waiting'}</b></span><small>packet {data?.timing?.packetComputeMs??'—'} ms · chain {data?.timing?.chainComputeMs??'—'} ms</small></article><article><code>BROWSER ROUND TRIP</code><span><b>{samples.length?`${samples[samples.length-1].roundTripMs} ms`:'waiting'}</b></span><small>last 30 avg {stats.avg.toFixed(1)} ms · p95 {stats.p95.toFixed(1)} ms</small></article><article><code>PROVIDER</code><span><b>{providerClass}</b></span><small>{data?.provider?.reported||'awaiting runtime'} · {transitions.length} observed transitions</small></article></div>
  {!!transitions.length&&<div>{transitions.slice(-6).reverse().map((t,i)=><article key={`${t.at}-${i}`}><CloudCog/><span>{t.from} → <b>{t.to}</b></span><small>{new Date(t.at).toLocaleTimeString()} · observed transition only</small></article>)}</div>}
  <footer><Activity/><span>{data?.boundary||'R55 awaits a measured proof supervision cycle.'}</span><em>{samples.length?`${samples.length}/188 performance samples retained locally`:'No samples yet'}</em></footer>
 </section>
}
