import {startTransition,useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,Braces,Crosshair,Database,Focus,GitBranch,HardDrive,Layers3,Network,Pause,Play,RefreshCw,Satellite,Search,ShieldCheck,Waypoints,Zap} from 'lucide-react';
import {getHybridBridge,runtimeSessionId} from './platformAdapter';
import {decodeAddress} from './corpusRuntime';
import {buildCorrelationFabricR184,visibleFabricR184,type FabricGraph,type FabricNode} from './r184/correlationFabricR184';
import './r184CorrelationFabric.css';

type Props={record:any;state:any;address:number;onAddress?:(n:number)=>void;onNavigate?:(p:string)=>void};
type Snapshot={calibration:any;packets:any[];sar:any;swarm:any;convergence:any;hybrid:any;federation:any;runs:any[];loadedAt:number;errors:string[]};
const EMPTY:Snapshot={calibration:null,packets:[],sar:null,swarm:null,convergence:null,hybrid:null,federation:null,runs:[],loadedAt:0,errors:[]};
const KIND_ORDER=['SYSTEM','METRIC','BRANCH','SCENE','SOURCE','PACKET','RUN'] as const;
const finite=(v:any)=>Number.isFinite(Number(v))?Number(v):null;
const fmt=(v:any,d=3)=>{const n=finite(v);return n===null?'—':n.toFixed(d)};
const label=(v:any,n=80)=>String(v??'').slice(0,n);
function authHeaders(){const bridge=getHybridBridge(),h:Record<string,string>={'x-omega-session-id':runtimeSessionId(),'cache-control':'no-cache'};if(bridge){h['x-omega-bridge-id']=bridge.bridgeId;h['x-omega-bridge-secret']=bridge.secret}return h}
async function jsonFetch(path:string,signal:AbortSignal,init:RequestInit={}){const headers={...authHeaders(),...(init.body?{'content-type':'application/json'}:{}),...((init.headers||{}) as any)},r=await fetch(path,{...init,headers,signal,cache:'no-store',credentials:'same-origin'});const body=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(body?.reply||body?.message||body?.code||`${r.status}`),{status:r.status,body});return body}
function mean(xs:number[]){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
function sarPacket(sar:any,lat:number,lon:number){const scenes=Array.isArray(sar?.scenes)?sar.scenes:[],sources=Array.isArray(sar?.sources)?sar.sources:[],coh=scenes.map((s:any)=>finite(s?.calibration?.relativeCoherence)).filter((x:any)=>x!==null) as number[],res=scenes.map((s:any)=>finite(s?.calibration?.frameResidual)).filter((x:any)=>x!==null) as number[],metrics:any={sarSceneCount:scenes.length,sarAcquisitionEpochs:Number(sar?.continuity?.acquisitions||0)};for(const[k,v]of Object.entries({sarMeanGapDays:finite(sar?.continuity?.meanGapDays),sarMaxGapDays:finite(sar?.continuity?.maxGapDays),sarCatalogAgreementDeltaDays:finite(sar?.sourceAgreement?.deltaDays),sarMeanRelativeCoherence:mean(coh),sarMeanFrameResidual:mean(res)}))if(v!==null)metrics[k]=v;const hash=String(sar?.evidenceHash||'').toLowerCase(),ok=sources.filter((s:any)=>s?.ok).length;return{packetId:/^[a-f0-9]{64}$/.test(hash)?`sar_${hash.slice(0,48)}`:undefined,source:{id:`earth-sar-target:${lat.toFixed(3)}:${lon.toFixed(3)}`,title:'R184 operator-bound SAR correlation packet',revision:'R184',uri:`/api/earth/sar/search?lat=${lat.toFixed(5)}&lon=${lon.toFixed(5)}&sensor=ALL&days=45&max=12`,authority:'PUBLIC_SAR_METADATA_PLUS_DERIVED_RELATIVE_FRAME_DIAGNOSTICS'},evidenceClass:'DERIVED',observedAt:Date.parse(sar?.verifiedAt||'')||Date.now(),domain:'EARTH_SAR',address:{lat,lon,crs:'WGS84 / EPSG:4326'},metrics,confidence:sources.length?ok/sources.length:.2,uncertainty:.35,quality:Math.min(1,Math.max(.25,scenes.length/6)),proofRefs:[hash?`OMEGA_EARTH_SAR_EVIDENCE_SHA256:${hash}`:null,...sources.filter((s:any)=>s?.ok&&s?.source).map((s:any)=>String(s.source))].filter(Boolean),notes:'Explicit operator binding. Metadata/relative-frame diagnostics only; no fabricated radiometry, InSAR deformation, moisture or elevation.'}}

export default function R184CorrelationFabric({address,onNavigate}:Props){
 const coords=useMemo(()=>decodeAddress(address),[address]),mapped=useMemo(()=>({lat:-90+(coords.d+.5)/12*180,lon:-180+(coords.p*12+coords.r+.5)/144*360}),[coords]);
 const[lat,setLat]=useState(mapped.lat),[lon,setLon]=useState(mapped.lon),[snapshot,setSnapshot]=useState<Snapshot>(EMPTY),[plan,setPlan]=useState<any>(null),[selected,setSelected]=useState('SYSTEM:omega'),[zoom,setZoom]=useState(1),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[live,setLive]=useState(true),[epoch,setEpoch]=useState(1),[intent,setIntent]=useState('Correlate current returned evidence, source diversity, calibration residuals, swarm topology and execution lineage; compute the strongest bounded next step and prioritize measurements that most reduce uncertainty.');
 const canvas=useRef<HTMLCanvasElement|null>(null),host=useRef<HTMLDivElement|null>(null),requestRef=useRef(0),abortRef=useRef<AbortController|null>(null),deferredQuery=useDeferredValue(query);
 useEffect(()=>{setLat(mapped.lat);setLon(mapped.lon)},[mapped.lat,mapped.lon]);
 const load=async(silent=false)=>{const seq=++requestRef.current;abortRef.current?.abort();const ctl=new AbortController();abortRef.current=ctl;if(!silent)setBusy('sync');const paths=[['cal','/api/calibration/r181/state'],['packets','/api/calibration/r181/packets?limit=1024'],['swarm','/api/swarm/autonomic/status'],['conv','/api/system/convergence'],['hybrid','/api/hybrid/status'],['fed','/api/federation/run/status'],['runs','/api/execution/runs'],['sar',`/api/earth/sar/search?lat=${lat.toFixed(5)}&lon=${lon.toFixed(5)}&sensor=ALL&days=90&max=12`]] as const;const settled=await Promise.allSettled(paths.map(([,path])=>jsonFetch(path,ctl.signal)));if(seq!==requestRef.current)return;const next:any={...EMPTY,loadedAt:Date.now(),errors:[]};settled.forEach((r,i)=>{const key=paths[i][0];if(r.status==='rejected'){next.errors.push(`${key}:${r.reason?.message||'unavailable'}`);return}const d=r.value;if(key==='cal')next.calibration=d?.state||null;else if(key==='packets')next.packets=Array.isArray(d?.packets)?d.packets:[];else if(key==='swarm')next.swarm=d;else if(key==='conv')next.convergence=d;else if(key==='hybrid')next.hybrid=d;else if(key==='fed')next.federation=d;else if(key==='runs')next.runs=Array.isArray(d?.runs)?d.runs:[];else if(key==='sar')next.sar=d});startTransition(()=>setSnapshot(next));if(!silent)setBusy('')};
 useEffect(()=>{void load();return()=>abortRef.current?.abort()},[lat,lon]);
 useEffect(()=>{if(!live)return;const id=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(id)},[live,lat,lon]);
 const graph=useMemo<FabricGraph>(()=>buildCorrelationFabricR184({calibration:snapshot.calibration,packets:snapshot.packets,sar:snapshot.sar,plan:plan?.plan||plan,runs:snapshot.runs,system:{convergence:snapshot.convergence,hybrid:snapshot.hybrid,federation:snapshot.federation}}),[snapshot,plan]);
 const filtered=useMemo(()=>{const view=visibleFabricR184(graph,zoom,selected),q=deferredQuery.trim().toLowerCase();return q?{...view,nodes:view.nodes.filter(n=>n.label.toLowerCase().includes(q)||n.kind.toLowerCase().includes(q)||n.id.toLowerCase().includes(q))}:view},[graph,zoom,selected,deferredQuery]);
 const nodeMap=useMemo(()=>new Map(filtered.nodes.map(n=>[n.id,n])),[filtered.nodes]),selectedNode=nodeMap.get(selected)||graph.nodes.find(n=>n.id===selected)||null;
 const scenes=useMemo(()=>[...(snapshot.sar?.scenes||[])].sort((a:any,b:any)=>Date.parse(a.datetime||'')-Date.parse(b.datetime||'')),[snapshot.sar]),epochScene=scenes.length?scenes[Math.max(0,Math.min(scenes.length-1,Math.round((epoch/100)*(scenes.length-1))))]:null;
 useEffect(()=>{const el=canvas.current,parent=host.current;if(!el||!parent)return;let raf=0;const draw=()=>{const rect=parent.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(320,rect.width),h=Math.max(330,rect.height);if(el.width!==Math.floor(w*dpr)||el.height!==Math.floor(h*dpr)){el.width=Math.floor(w*dpr);el.height=Math.floor(h*dpr);el.style.width=`${w}px`;el.style.height=`${h}px`}const c=el.getContext('2d');if(!c)return;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);c.fillStyle='#03080b';c.fillRect(0,0,w,h);const nodes=filtered.nodes,edges=filtered.edges,center={x:w*.5,y:h*.5},rings:Record<string,number>={SYSTEM:0,METRIC:.17,BRANCH:.31,SCENE:.43,SOURCE:.54,PACKET:.68,RUN:.79};const pos=new Map<string,{x:number;y:number}>();const grouped=new Map<string,FabricNode[]>();for(const n of nodes){const a=grouped.get(n.kind)||[];a.push(n);grouped.set(n.kind,a)}for(const kind of KIND_ORDER){const arr=grouped.get(kind)||[],r=Math.min(w,h)*(rings[kind]||.6);arr.forEach((n,i)=>{const phase=(i/Math.max(1,arr.length))*Math.PI*2+(kind.charCodeAt(0)%9)*.21;pos.set(n.id,{x:center.x+Math.cos(phase)*r*(.78+n.uncertainty*.22),y:center.y+Math.sin(phase)*r})})}c.lineWidth=1;for(const e of edges){const a=pos.get(e.a),b=pos.get(e.b);if(!a||!b)continue;c.globalAlpha=.08+e.weight*.34;c.strokeStyle=e.relation==='INFORMS'?'#a99cff':e.relation==='CALIBRATES'?'#e6c76f':'#5bc7c3';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}c.globalAlpha=1;for(const n of nodes){const p=pos.get(n.id);if(!p)continue;const active=n.id===selected,r=active?7:Math.max(2.2,2.5+n.weight*3);c.fillStyle=n.kind==='METRIC'?'#69ddd6':n.kind==='BRANCH'?'#a99cff':n.kind==='SCENE'?'#e6c76f':n.kind==='RUN'?'#7bd495':n.kind==='SOURCE'?'#70a9c5':n.kind==='SYSTEM'?'#ffffff':'#82939c';c.globalAlpha=active?1:.45+n.weight*.45;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();if(active||filtered.lod==='DETAIL'||(filtered.lod==='EVIDENCE'&&n.kind!=='PACKET')){c.globalAlpha=active?1:.76;c.fillStyle='#d9e5e9';c.font=`${active?11:8}px ui-monospace,monospace`;c.fillText(n.label.slice(0,active?42:24),p.x+r+4,p.y+3)}}c.globalAlpha=1;(el as any)._omegaPositions=pos};const schedule=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)};const ro=new ResizeObserver(schedule);ro.observe(parent);schedule();return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[filtered,selected]);
 const canvasPick=(e:any)=>{const el=canvas.current;if(!el)return;const pos:Map<string,{x:number;y:number}>=(el as any)._omegaPositions||new Map(),r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best:string|null=null,dist=18;for(const[k,p]of pos){const d=Math.hypot(p.x-x,p.y-y);if(d<dist){dist=d;best=k}}if(best)setSelected(best)};
 const preview=async()=>{if(busy)return;setBusy('plan');setMessage('');try{const r=await jsonFetch('/api/calibration/r181/plan',new AbortController().signal,{method:'POST',body:JSON.stringify({intent,projection:'CONVERGENCE',mode:'AUTO',providerBudget:4,reconvergeWithAI:true})});startTransition(()=>setPlan(r));setMessage(`Topology returned · ${r?.plan?.totalCells||0} cells / ${r?.plan?.totalBranches||0} branches · no mission created.`)}catch(e:any){setMessage(e.message)}finally{setBusy('')}};
 const bindSar=async()=>{if(busy)return;setBusy('bind');setMessage('');try{if(!snapshot.sar?.scenes?.length)throw new Error('No returned SAR scenes in the current evidence window.');const r=await jsonFetch('/api/calibration/r181/ingest',new AbortController().signal,{method:'POST',body:JSON.stringify({confirmCalibrationIngest:true,packet:sarPacket(snapshot.sar,lat,lon)})});setMessage(`Calibration receipt ${r?.receipt?.packetId||'returned'} · ${String(r?.receipt?.stateFingerprint||'').slice(0,18)}…`);await load(true)}catch(e:any){setMessage(e.message)}finally{setBusy('')}};
 const recompute=async()=>{if(busy)return;setBusy('recompute');setMessage('');try{await jsonFetch('/api/calibration/r181/recompute',new AbortController().signal,{method:'POST',body:JSON.stringify({confirmCalibrationRecompute:true})});await load(true);setMessage('Durable calibration fusion recomputed.')}catch(e:any){setMessage(e.message)}finally{setBusy('')}};
 const pcOnline=Boolean(snapshot.hybrid?.nativeExecutionClaimed&&snapshot.hybrid?.devices?.some((d:any)=>d?.online&&!d?.revoked));
 return <section className='r184-fabric'>
  <header className='r184-head'><div><span>R184 · ULTRA CORRELATION FABRIC</span><h2>Operate the whole returned system as one evolving field.</h2><p>Real evidence, calibration residuals, SAR epochs, R125 topology and durable execution lineage share one selectable state space. Rendering detail changes with zoom; authority does not.</p></div><div className='r184-head-actions'><button onClick={()=>setLive(v=>!v)}>{live?<Pause/>:<Play/>}{live?'LIVE 15s':'PAUSED'}</button><button onClick={()=>void load()} disabled={Boolean(busy)}><RefreshCw className={busy==='sync'?'spin':''}/>SYNC</button><button onClick={()=>onNavigate?.('Evidence & Proof')}><ShieldCheck/>PROOF</button></div></header>
  <div className='r184-statebar'><b data-live={Boolean(snapshot.calibration?.fingerprint)}>CAL {snapshot.calibration?.fingerprint?'BOUND':'EMPTY'}</b><b data-live={Boolean(snapshot.sar?.scenes?.length)}>SAR {snapshot.sar?.scenes?.length||0}</b><b data-live={pcOnline}>PC {pcOnline?'HEARTBEAT':'NO PROOF'}</b><b data-live={Boolean(plan)}>PLAN {plan?.plan?.totalCells||0}</b><b>GRAPH {graph.stats.nodes}N/{graph.stats.edges}E</b><b>LOD {filtered.lod}</b><small>{snapshot.errors.length?snapshot.errors.join(' · '):`synced ${snapshot.loadedAt?new Date(snapshot.loadedAt).toLocaleTimeString():'—'}`}</small></div>
  <div className='r184-command'><textarea value={intent} onChange={e=>setIntent(e.target.value)} aria-label='R184 correlated planning intent'/><div><button className='primary' onClick={preview} disabled={Boolean(busy)}><Waypoints/>COMPUTE TOPOLOGY</button><button onClick={bindSar} disabled={Boolean(busy)||!snapshot.sar?.scenes?.length}><Satellite/>BIND RETURNED SAR</button><button onClick={recompute} disabled={Boolean(busy)}><Braces/>RECOMPUTE FUSION</button></div></div>
  <div className='r184-workspace'>
   <div className='r184-field-column'>
    <div className='r184-toolbar'><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='filter source, metric, run…'/></label><label><Focus/><input type='range' min='.25' max='2.5' step='.05' value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><b>{zoom.toFixed(2)}×</b></label></div>
    <div className='r184-canvas-host' ref={host}><canvas ref={canvas} onPointerDown={canvasPick}/><div className='r184-rings'><span>SYSTEM</span><span>METRICS</span><span>COMPUTE</span><span>OBSERVATION</span><span>PROVENANCE</span></div></div>
    <div className='r184-epoch'><Satellite/><div><b>SAR TEMPORAL FRAME</b><small>{epochScene?`${epochScene.family||'SAR'} · ${epochScene.datetime||'unknown'} · ${epochScene.band||'?'}-band`:'No returned scene'}</small></div><input type='range' min='0' max='100' value={epoch} onChange={e=>setEpoch(Number(e.target.value))}/><code>{scenes.length?`${Math.round((epoch/100)*(scenes.length-1))+1}/${scenes.length}`:'0/0'}</code></div>
   </div>
   <aside className='r184-inspector'>
    <header><Crosshair/><div><span>SELECTED STATE</span><b>{selectedNode?.kind||'NONE'} · {selectedNode?.label||'select a node'}</b></div></header>
    {selectedNode?<><div className='r184-selected'><strong>{selectedNode.value==null?'RELATIONAL NODE':fmt(selectedNode.value,5)}</strong><div><span>weight <b>{fmt(selectedNode.weight)}</b></span><span>uncertainty <b>{fmt(selectedNode.uncertainty)}</b></span><span>sources <b>{selectedNode.sourceDiversity}</b></span></div></div><pre>{JSON.stringify(selectedNode.meta,null,2).slice(0,7000)}</pre></>:<p className='empty'>Select a node in the field.</p>}
   </aside>
  </div>
  <div className='r184-bottom'>
   <section><header><Database/><div><span>FUSION PRESSURE</span><b>Weakest independent support</b></div></header><div className='r184-weak'>{(snapshot.calibration?.planningHints?.weakestMetrics||[]).slice(0,10).map((x:any)=><button key={x.name} onClick={()=>setSelected(`metric:${String(x.name).replace(/[^A-Za-z0-9._:-]/g,'_')}`)}><b>{x.name}</b><i style={{'--u':Math.min(1,Number(x.evidenceWeakness??x.relativeUncertainty??0))} as any}/><small>u {fmt(x.relativeUncertainty)} · src {x.independentSourceCount??0}</small></button>)}</div></section>
   <section><header><GitBranch/><div><span>COMPUTE FIELD</span><b>Returned R125 branch topology</b></div></header><div className='r184-branches'>{(plan?.plan?.branches||[]).slice(0,36).map((b:any)=><button key={`${b.domain}:${b.phase}`} onClick={()=>setSelected(`branch:${b.domain}:${b.phase}`)}><b>D{b.domain}·P{b.phase}</b><span>{b.cells?.length||0}</span></button>)}</div></section>
   <section><header><Activity/><div><span>EXECUTION LINEAGE</span><b>Durable runs remain separate authority</b></div></header><div className='r184-runs'>{snapshot.runs.slice(0,12).map((r:any)=><button key={r.id||r.runId} onClick={()=>setSelected(`run:${String(r.id||r.runId).replace(/[^A-Za-z0-9._:-]/g,'_')}`)}><b>{label(r.id||r.runId,28)}</b><span>{r.status||r.state||'UNKNOWN'}</span></button>)}</div></section>
  </div>
  {message&&<div className='r184-message'><Zap/>{message}</div>}
  <footer><Network/><p><b>R184 performance law:</b> source fan-out is cancellable and concurrent; stale responses are discarded; graph density is LOD-bounded; canvas repaint is animation-frame scheduled; calibration changes require the existing authenticated bridge; planning remains non-mutating; execution remains under the existing governed execution fabric.</p></footer>
 </section>
}
