import {useEffect,useMemo,useState} from 'react';
import {Activity,GitBranch,RefreshCw,ShieldCheck,Sparkles,Waypoints} from 'lucide-react';
import {api} from './platformAdapter';
import './reflexAutonomicR164.css';

type Run={id:string;state:string;intent?:string;headSha256?:string;metadata?:Record<string,any>;contract?:Record<string,any>};
type Mode='AUTO'|'SOLO'|'FLOCK'|'TREE'|'PIPELINE'|'CONSENSUS'|'MIRROR'|'FULL';
const STATES=new Set(['RETURNED','VERIFIED','FAILED']);
const MODES:Mode[]=['AUTO','SOLO','FLOCK','TREE','PIPELINE','CONSENSUS','MIRROR','FULL'];
const sev=(s:any)=>({CRITICAL:1,HIGH:.78,MEDIUM:.5,LOW:.24,INFO:.1}[String(s||'MEDIUM').toUpperCase()]??.35);
const c01=(v:number)=>Math.max(0,Math.min(1,v));
const pct=(v:any)=>`${Math.round(c01(Number(v)||0)*100)}%`;

function residuals(run:Run|null){return(Array.isArray(run?.metadata?.residuals)?run!.metadata!.residuals:[]).slice(0,32)}
function metrics(run:Run|null){const rs=residuals(run),xs=rs.map((r:any)=>sev(r?.severity)),mean=xs.length?xs.reduce((a:number,b:number)=>a+b,0)/xs.length:0,max=xs.length?Math.max(...xs):0,count=Math.min(1,rs.length/12),verified=run?.state==='VERIFIED',failed=run?.state==='FAILED';return{continuity:c01((verified?.84:failed?.42:.68)-mean*.18),plasticity:c01(.62+count*.2+(failed?.12:0)),contradiction:c01(max*.7+count*.22),burden:c01(.2+mean*.46+count*.24+(failed?.12:0)),evidence:c01(verified?.82:run?.state==='RETURNED'?.58:.42),uncertainty:c01(.22+mean*.48+(verified?-.08:.08)),scar:c01(.12+mean*.52+count*.22)}}
function sourceEvidence(run:Run){const rows:any[]=[];if(/^[a-f0-9]{64}$/i.test(run.headSha256||''))rows.push({id:`r146:${run.id}`,type:'R146_HASH_CHAIN',sha256:run.headSha256,summary:`Returned reflex source ${run.id} ${run.state}.`,authority:'R146_DURABLE_EXECUTION_HISTORY'});const world=String(run.metadata?.worldHeadSha256||'');if(/^[a-f0-9]{64}$/i.test(world))rows.push({id:`world:${world.slice(0,16)}`,type:'R134_R136_WORLD_HEAD',sha256:world,summary:'World/scar continuity carried from R157/R161.',authority:'WORLD_EVIDENCE_NOT_CANON'});for(const [i,r] of residuals(run).entries())rows.push({id:r?.evidence_id||r?.id||`residual-${i+1}`,type:`RESIDUAL_${r?.kind||'UNCLASSIFIED'}`,summary:`${r?.severity||'MEDIUM'}: ${r?.summary||r?.kind||'returned residual'}`,authority:'RETURNED_RESIDUAL_CONTEXT_NOT_INDEPENDENTLY_VERIFIED'});return rows.slice(0,32)}

export default function ReflexAutonomicR164(){
 const[runs,setRuns]=useState<Run[]>([]),[runId,setRunId]=useState(''),[mode,setMode]=useState<Mode>('AUTO'),[providerBudget,setProviderBudget]=useState(8),[plan,setPlan]=useState<any>(null),[replay,setReplay]=useState<any>(null),[mission,setMission]=useState<any>(null),[authorized,setAuthorized]=useState(false),[fullAuthorized,setFullAuthorized]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const run=useMemo(()=>runs.find(x=>x.id===runId)||null,[runs,runId]),rs=useMemo(()=>residuals(run),[run]),derived=useMemo(()=>metrics(run),[run]);
 const active=mission&&['QUEUED','RUNNING','PAUSED'].includes(mission.status);
 const payload=useMemo(()=>run?{intent:`Resolve returned residuals from ${run.intent||run.id}. Preserve disagreement and source authority, use the minimum sufficient OMEGA scope, and return proof-bounded work for governed reconvergence.`,mode,scope:{type:'BODY'},providerBudget,metrics:derived,evidence:sourceEvidence(run),reconvergeWithAI:providerBudget>0,allowFullAuto:false}:null,[run,mode,providerBudget,derived]);
 const loadRuns=async()=>{setBusy(true);try{const r=await api.get<any>('/api/execution/runs'),all=(r.data?.runs||[]) as Run[],eligible=all.filter(x=>x?.metadata?.sourceRevision==='R157'&&STATES.has(x.state));setRuns(eligible);setRunId(id=>eligible.some(x=>x.id===id)?id:(eligible[0]?.id||''));if(!eligible.length)setMessage('No returned R157-lineage durable execution is available yet. R164 remains held until a governed reflex run returns, verifies, or records a terminal failure.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 useEffect(()=>{void loadRuns()},[]);
 useEffect(()=>{setPlan(null);setReplay(null);setMission(null);setAuthorized(false);setFullAuthorized(false)},[runId]);
 useEffect(()=>{if(!active||!mission?.id)return;const t=window.setInterval(async()=>{try{const r=await api.get<any>(`/api/swarm/autonomic/missions/${mission.id}`);if(r.data?.mission)setMission(r.data.mission)}catch{}},1500);return()=>window.clearInterval(t)},[active,mission?.id]);
 const preview=async()=>{if(!run||!payload||busy)return;setBusy(true);try{const [rr,p]=await Promise.all([api.post<any>(`/api/execution/runs/${encodeURIComponent(run.id)}/replay`,{}),api.post<any>('/api/swarm/autonomic/plan',payload)]);if(rr.data?.receipt?.ok!==true)throw new Error('R146 replay did not verify; R164 will not plan from an unverified source chain.');setReplay(rr.data.receipt);setPlan(p.data?.plan);setMessage('R164 preview bound the returned R146 source to an R125 autonomic topology. No swarm mission has been queued.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 const launch=async()=>{if(!run||!payload||!authorized||busy)return;setBusy(true);try{const rr=replay?.ok?{receipt:replay}:(await api.post<any>(`/api/execution/runs/${encodeURIComponent(run.id)}/replay`,{})).data;if(rr?.receipt?.ok!==true)throw new Error('R146 replay proof is required before R164 launch.');const p=plan||(await api.post<any>('/api/swarm/autonomic/plan',payload)).data?.plan;if(!p)throw new Error('R125 autonomic plan missing.');if((p.totalCells>=1728||mode==='FULL')&&!fullAuthorized)throw new Error('All 1,728 cells require separate explicit FULL authorization.');const r=await api.post<any>('/api/swarm/autonomic/missions',{...payload,allowFullAuto:false});setPlan(r.data?.plan||p);setMission(r.data?.mission);setMessage('R164 launched the existing R125 autonomic execution fabric from a replay-verified returned reflex source. CanonState remains unchanged.')}catch(e:any){setMessage(e?.message||String(e))}finally{setBusy(false)}};
 return <section className='r164-reflex' aria-label='R164 returned reflex autonomic swarm convergence'>
  <header><div><span>R164 · REFLEX → AUTONOMIC SWARM</span><h3>Returned work can now recruit the body.</h3><p>R164 takes a returned R157→R161→R162 durable execution, replays its R146 hash chain, carries its residual/scar evidence, and can route the unresolved pressure into the existing 1→12→144→1,728 R125 autonomic swarm. AUTO stays bounded; FULL 1,728-cell use requires a second explicit authorization.</p></div><Waypoints/></header>
  <div className='r164-controls'><label><span>RETURNED REFLEX SOURCE</span><select value={runId} onChange={e=>setRunId(e.target.value)} disabled={!runs.length}>{runs.length?runs.map(r=><option value={r.id} key={r.id}>{r.state} · {r.metadata?.sourceFamily||r.contract?.executionDomain||'REFLEX'} · {r.id.slice(0,18)}</option>):<option>No eligible returned reflex run</option>}</select></label><label><span>SWARM MODE</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{MODES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>AI BUDGET · 0–12</span><input type='number' min='0' max='12' value={providerBudget} onChange={e=>setProviderBudget(Math.max(0,Math.min(12,Number(e.target.value)||0)))}/></label><button onClick={()=>void loadRuns()} disabled={busy}><RefreshCw/>REFRESH SOURCES</button><button onClick={()=>void preview()} disabled={!run||busy}><GitBranch/>PREVIEW RECRUITMENT</button></div>
  {run&&<div className='r164-source'><article><span>PRIMARY RUN</span><b>{run.state}</b><small>{run.id}</small></article><article><span>RESIDUALS</span><b>{rs.length}</b><small>pressure {Number(run.metadata?.residualPressure||0).toFixed(2)}</small></article><article><span>SCAR</span><b>{run.metadata?.reflexScarId?'BOUND':'HELD'}</b><small>{run.metadata?.reflexScarId||'no scar id returned'}</small></article><article><span>R146 REPLAY</span><b>{replay?.ok?'VERIFIED':'REQUIRED'}</b><small>{replay?.replayedHeadSha256||run.headSha256||'hash chain pending replay'}</small></article></div>}
  {run&&<div className='r164-metrics'>{Object.entries(derived).map(([k,v])=><div key={k}><span>{k}</span><b>{pct(v)}</b><i style={{width:pct(v)}}/></div>)}</div>}
  {rs.length>0&&<details className='r164-residuals'><summary>Returned residual/scar carry · {rs.length}</summary>{rs.map((r:any,i:number)=><div key={r?.id||i}><b>{r?.severity||'MEDIUM'} · {r?.kind||'UNCLASSIFIED'}</b><span>{r?.summary||'No residual summary.'}</span><small>{r?.evidence_id||'source evidence id not supplied'}</small></div>)}</details>}
  {plan&&<div className='r164-plan'><Sparkles/><div><span>R125 AUTONOMIC PLAN · {plan.projection} · {plan.decision}</span><b>{plan.totalCells} cells / {plan.totalBranches} branches / concurrency {plan.branchConcurrency}</b><small>provider budget {plan.budgets?.providerTotal} · {plan.detached?'detached scope':'body scope'} · execution quorum remains evidence, not truth</small></div></div>}
  {plan&&<div className='r164-authorize'><label><input type='checkbox' checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/><span><b>AUTHORIZE SWARM EXECUTION</b><small>Queue the R125 plan against the returned R146 reflex source.</small></span></label>{(plan.totalCells>=1728||mode==='FULL')&&<label className='full'><input type='checkbox' checked={fullAuthorized} onChange={e=>setFullAuthorized(e.target.checked)}/><span><b>AUTHORIZE FULL 1,728</b><small>Separate explicit approval for the entire cell body.</small></span></label>}<button onClick={()=>void launch()} disabled={!authorized||busy}><Activity/>LAUNCH GOVERNED FOLLOW-THROUGH</button></div>}
  {mission&&<div className='r164-mission'><header><span>R125 MISSION</span><b>{mission.id}</b><strong>{mission.status}</strong></header><div><article><span>CELLS</span><b>{mission.completedCells||0}/{mission.totalCells||0}</b></article><article><span>BRANCHES</span><b>{mission.completedBranches||0}/{mission.totalBranches||0}</b></article><article><span>PROOF STATE</span><b>{mission.proofState||'PENDING'}</b></article><article><span>MERKLE</span><b>{mission.merkleRoot?'BOUND':'PENDING'}</b></article></div>{mission.finalSynthesis&&<p>{mission.finalSynthesis.text}</p>}</div>}
  {message&&<p className='r164-message'>{message}</p>}
  <footer><ShieldCheck/><span>R164 does not add a second executor or CanonState authority. It binds returned reflex history to the existing R125 swarm as governed follow-through. PC ONLINE, solver validity, factual truth, federation closure and R125 admission remain separately proven states.</span></footer>
 </section>
}
