import {useEffect,useMemo,useState} from 'react';
import {Activity,ChevronDown,ChevronUp,GitCommitHorizontal,Layers3,ShieldCheck,Waypoints} from 'lucide-react';
import {evaluateCorpusModes} from './corpusRuntime';
import {evaluateCanonAuthorityStack} from './allModesAuthority';
import {sourceBackedModeSummary} from './sourceBackedModeRuntimeR21';
import {latestRuntimeReceiptR44,R44_LEDGER_EVENT,R44_TRANSITION_SEQUENCE,runtimeLedgerR44,type R44RuntimeReceipt} from './runtimeAuthorityR44';
import './runtimeAuthorityR44.css';

type Props={record:any;policy:'ALL_ACTIVE'|'SOURCE_ONLY';onPolicy:(policy:'ALL_ACTIVE'|'SOURCE_ONLY')=>void;onNavigate:(panel:string)=>void};
const short=(s:string)=>s?`${s.slice(0,10)}…${s.slice(-6)}`:'GENESIS';
export default function RuntimeAuthorityRailR44({record,policy,onPolicy,onNavigate}:Props){
 const[receipt,setReceipt]=useState<R44RuntimeReceipt|null>(()=>latestRuntimeReceiptR44()),[open,setOpen]=useState(false),catalog=useMemo(()=>evaluateCorpusModes(record),[record]),canon=useMemo(()=>evaluateCanonAuthorityStack(record),[record]),source=useMemo(()=>sourceBackedModeSummary(record),[record]);
 useEffect(()=>{const onLedger=(e:Event)=>setReceipt((e as CustomEvent<R44RuntimeReceipt>).detail);window.addEventListener(R44_LEDGER_EVENT,onLedger);return()=>window.removeEventListener(R44_LEDGER_EVENT,onLedger)},[]);
 const rows=open?runtimeLedgerR44().slice(-8).reverse():[];
 return <section className='r44-authority' data-policy={policy.toLowerCase()}>
  <header><button className='r44-authority-title' onClick={()=>setOpen(v=>!v)} aria-expanded={open}><GitCommitHorizontal/><span><b>ONE RUNTIME AUTHORITY · R44</b><small>{receipt?`${receipt.mutationClass} · ${receipt.edge} · REV ${receipt.revision}`:'GENESIS · ledger begins on first state mutation'}</small></span>{open?<ChevronUp/>:<ChevronDown/>}</button><div className='r44-authority-counts'><button onClick={()=>onNavigate('Modes')}><Layers3/><span>ACTIVE MODE FIELD</span><b>{catalog.count} projections · {canon.length} lenses</b></button><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/><span>CANONICAL MUTATORS</span><b>{source.appliedCount} applied · {source.gatedCount} input gates</b></button><div className='r44-policy'><button className={policy==='ALL_ACTIVE'?'active':''} onClick={()=>onPolicy('ALL_ACTIVE')}>ALL ACTIVE</button><button className={policy==='SOURCE_ONLY'?'active':''} onClick={()=>onPolicy('SOURCE_ONLY')}>SOURCE ONLY</button></div></div></header>
  <div className='r44-sequence' aria-label='Canonical runtime transition sequence'>{R44_TRANSITION_SEQUENCE.map((stage,i)=><span key={stage} className={receipt||i===0?'ready':''}><b>{String(i+1).padStart(2,'0')}</b>{stage}</span>)}</div>
  {open&&<div className='r44-ledger'><div className='r44-ledger-current'><article><span>STATE</span><b>{record.stateId.toLocaleString()}</b><small>D{record.coordinates.d+1} · P{record.coordinates.p+1} · R{record.coordinates.r+1} · L{record.coordinates.l+1}</small></article><article><span>LAST PROOF</span><b>{receipt?.proof.status||'AWAITING MUTATION'}</b><small>{receipt?short(receipt.ledgerHash):'no transaction hash yet'}</small></article><article><span>SCAR Δ</span><b>{receipt?receipt.scar.delta.toFixed(6):'—'}</b><small>{receipt?'carried through ledger':'first transition will calculate carry'}</small></article><article><span>FORECAST</span><b>{receipt?`STATE ${receipt.forecast.candidateStateId}`:`STATE ${Number(record.autoPing.dataNext)+1}`}</b><small>{receipt?.forecast.decision||record.metrics.decision}</small></article></div><div className='r44-ledger-list'>{rows.map(x=><article key={x.ledgerHash}><Waypoints/><div><b>REV {x.revision} · {x.sourceSurface}</b><span>{x.fromStateId} → {x.toStateId} · {x.mutationClass} · {x.edge}</span><small>{short(x.ledgerHash)} · {new Date(x.at).toLocaleTimeString()}</small></div><strong>{x.selectedOperator}</strong></article>)}{!rows.length&&<p>Change the active state to create the first proof-bound runtime transaction.</p>}</div><footer><Activity/>All 179 catalog operators are live read-only projections when ALL ACTIVE is selected. Only source-backed/admitted operators can mutate the canonical address; missing-input formulas remain executable contracts that request their absent authority instead of inventing values.</footer></div>}
 </section>
}
