import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,BrainCircuit,Database,Download,GitBranch,Network,Play,Route,Search,ShieldCheck,Sparkles,Waypoints,Wrench} from 'lucide-react';
import {INTELLIGENCE_CONTRIBUTORS} from './intelligenceFabric';
import {sourceBackedModeSummary} from './sourceBackedModeRuntimeR21';
import {appendSaiLedger,buildSaiTraversal,compileSaiImprovementProposal,compileSaiRetrievalPlan,readSaiLedger,SAI_B059_AUTHORITIES,SAI_B059_BOUNDARY,SAI_B059_DB_BYTES,SAI_B059_DONOR_SELFTEST,SAI_B059_EDGE_COUNT,SAI_B059_TRAVERSAL_STEPS,saiHostedReceipt,saiKernel,verifySaiLedger,type SaiLedgerEntry} from './saiB059Runtime';
import './saiSovereign.css';

type Tab='IMPROVE'|'QUERY'|'CORPUS'|'TRAVERSAL'|'LEDGER'|'SELFTEST'|'FABRIC';
const TABS:Tab[]=['IMPROVE','QUERY','CORPUS','TRAVERSAL','LEDGER','SELFTEST','FABRIC'];
const fmtBytes=(n:number)=>`${(n/1024/1024).toFixed(1)} MB`;
function download(name:string,payload:any){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}
export default function SAISovereignControl({record,modeCount,onNavigate}:{record:any;modeCount?:number;onNavigate?:(p:string)=>void}){
 const summary=useMemo(()=>sourceBackedModeSummary(record),[record]);
 const resolvedModeCount=modeCount??summary.appliedCount;
 const[tab,setTab]=useState<Tab>('IMPROVE'),[query,setQuery]=useState('What is the strongest source-grounded next action from this state?'),[plan,setPlan]=useState<any>(()=>compileSaiRetrievalPlan('What is the strongest source-grounded next action from this state?',record.address)),[ledger,setLedger]=useState<SaiLedgerEntry[]>(()=>readSaiLedger()),[ledgerProof,setLedgerProof]=useState<any>({passed:true,entries:0,head:'0'.repeat(64)}),[proposalState,setProposalState]=useState<'READY'|'LEDGERED'>('READY');
 const kernel=useMemo(()=>saiKernel(record),[record]),traversal=useMemo(()=>buildSaiTraversal(record.address),[record.address]),receipt=useMemo(()=>saiHostedReceipt(record,resolvedModeCount),[record,resolvedModeCount]);
 const improvement=useMemo(()=>compileSaiImprovementProposal(record,{appliedCount:summary.appliedCount,gatedCount:summary.gatedCount,catalogCount:summary.catalogCount}),[record,summary.appliedCount,summary.gatedCount,summary.catalogCount]);
 useEffect(()=>{verifySaiLedger(ledger).then(setLedgerProof)},[ledger]);
 useEffect(()=>setProposalState('READY'),[improvement.proposalId]);
 const inspect=async()=>{const next=compileSaiRetrievalPlan(query,record.address);setPlan(next);await appendSaiLedger('RETRIEVAL_PLAN',{query:next.query,stateId:next.stateId,roles:next.roles,decision:next.kernel.decision});setLedger([...readSaiLedger()])};
 const advance=async()=>{await appendSaiLedger('TRAVERSAL_INSPECT',{fromState:record.stateId,steps:SAI_B059_TRAVERSAL_STEPS,head:traversal[0],tail:traversal.at(-1)});setLedger([...readSaiLedger()])};
 const ledgerImprovement=async()=>{await appendSaiLedger('IMPROVEMENT_PROPOSAL',improvement);setLedger([...readSaiLedger()]);setProposalState('LEDGERED')};
 return <section className='sai-sovereign special-app'>
  <header className='special-head'><div><span>OMEGA SAI B059 · GROUNDED INTELLIGENCE + GOVERNED IMPROVEMENT LOOP</span><h2>SAI Sovereign Lab</h2><p>Restores B059 corpus, provenance, canon, ledger and traversal contracts, then turns the current packet into auditable improvement proposals. Browser SAI proposes and proves intent; the governed repository/release pipeline remains the only authority that may change production source.</p></div><BrainCircuit/></header>
  <div className='sai-summary'><div><span>CORPUS AUTHORITIES</span><b>{SAI_B059_AUTHORITIES.length}</b></div><div><span>DONOR DB</span><b>{fmtBytes(SAI_B059_DB_BYTES)}</b></div><div><span>DONOR EDGES</span><b>{SAI_B059_EDGE_COUNT.toLocaleString()}</b></div><div><span>TRAVERSAL</span><b>{SAI_B059_TRAVERSAL_STEPS}</b></div><div><span>SOURCE-BACKED MODES</span><b>{resolvedModeCount}</b><small>{summary.gatedCount} gated · {summary.catalogCount} catalog</small></div><div><span>DECISION</span><b>{kernel.decision}</b></div></div>
  <nav className='sai-tabs'>{TABS.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==='IMPROVE'&&<div className='sai-improvement'>
   <header className='sai-improvement-hero'><div><span>SELF-IMPROVEMENT CONTROL</span><h3>{improvement.priority}</h3><p>SAI has compiled a bounded improvement candidate from the current state, current executable-mode truth and the same STAY / TURN / ESCALATE gate used by the runtime.</p></div><strong>{improvement.proposalId}</strong></header>
   <div className='sai-improvement-flow'>{improvement.workflow.map((x,i)=><span key={x} className={i<4?'active':i===4?'handoff':''}><code>{String(i+1).padStart(2,'0')}</code><b>{x}</b><small>{x==='Handoff'?'governed source pipeline':x==='Verify'?'QA + public runtime':x==='Ledger'?'hash chained receipt':'SAI runtime'}</small></span>)}</div>
   <div className='sai-improvement-grid'><article className='sai-observations'><header><BrainCircuit/><div><b>Current diagnosis</b><small>packet-derived observations</small></div></header>{improvement.observations.map(x=><p key={x}>{x}</p>)}</article><article className='sai-boundary-card'><header><ShieldCheck/><div><b>Mutation boundary</b><small>no fake autonomous code writing</small></div></header><p>SAI may diagnose, prioritize, compile a proposal and add it to the proof ledger. It cannot silently edit GitHub or promote production from the browser. A source change is real only after a governed diff, full QA, deployment and public verification receipt.</p></article></div>
   <div className='sai-targets'>{improvement.targets.map((x,i)=><article key={x.area}><code>{String(i+1).padStart(2,'0')}</code><div><b>{x.area.replaceAll('_',' ')}</b><p>{x.reason}</p><small>ACCEPT · {x.acceptance}</small></div></article>)}</div>
   <div className='sai-improvement-actions'><button className='primary' onClick={ledgerImprovement}><Sparkles/>{proposalState==='LEDGERED'?'Proposal ledgered':'Ledger improvement proposal'}</button>{onNavigate&&<button onClick={()=>onNavigate('Development')}><Wrench/>Open governed Development <ArrowRight/></button>}{onNavigate&&<button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Inspect proof chain <ArrowRight/></button>}<button onClick={()=>download(`${improvement.proposalId}.json`,improvement)}><Download/>Export proposal</button></div>
   <footer className='sai-improvement-proof'><GitBranch/><span><b>Execution boundary:</b> {improvement.executionBoundary}</span></footer>
  </div>}
  {tab==='QUERY'&&<div className='sai-query-layout'><div className='sai-query-box'><Search/><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder='Prepare a source-grounded retrieval plan…'/><button onClick={inspect}><Route/>Compile retrieval plan</button>{onNavigate&&<button onClick={()=>onNavigate('Command Center')}><BrainCircuit/>Route to assistant</button>}</div><article className='sai-plan'><header><ShieldCheck/><b>{plan.schema}</b><span>{plan.execution}</span></header><div className='sai-workflow'>{plan.workflow.map((x:string,i:number)=><span key={x}><code>{String(i+1).padStart(2,'0')}</code>{x}</span>)}</div><h3>Evidence role order</h3><div className='sai-role-order'>{plan.roles.map((x:string,i:number)=><span key={x}><code>{i+1}</code>{x}</span>)}</div><div className='sai-kernel-grid'><span>CΩ<b>{kernel.continuity.toFixed(4)}</b></span><span>Φ<b>{kernel.plasticity.toFixed(4)}</b></span><span>q<b>{kernel.contradiction.toFixed(4)}</b></span><span>Λ<b>{kernel.burden.toFixed(4)}</b></span><span>S<b>{kernel.stability.toFixed(4)}</b></span><span>GATE<b>{kernel.decision}</b></span></div></article></div>}
  {tab==='CORPUS'&&<div className='sai-corpus'><div className='sai-boundary'><Database/><p><b>15 SHA-bound authorities restored as manifest truth.</b> The B059 donor compiled them into a 747 MB SQLite database. The hosted Worker does not claim that database is resident; it preserves exact source identity and routes current hosted computation through the existing 20,736-state corpus.</p></div><div className='sai-source-grid'>{SAI_B059_AUTHORITIES.map((x,i)=><article key={x.name}><header><code>{String(i+1).padStart(2,'0')}</code><b>{x.role}</b><span>{fmtBytes(x.size)}</span></header><p>{x.name}</p><small>SHA-256 · {x.sha256}</small></article>)}</div></div>}
  {tab==='TRAVERSAL'&&<div className='sai-traversal'><header><Waypoints/><div><b>188-step retained source path</b><span>Uses the current canonical graph's admitted-next relation; B059's compiled donor graph is not impersonated.</span></div><button onClick={advance}><Play/>Ledger traversal inspection</button></header><div className='sai-path'>{traversal.map((x,i)=><i key={`${x}-${i}`} className={i===0?'head':i===traversal.length-1?'tail':''} title={`Step ${i+1} · state ${x}`}><span>{i+1}</span></i>)}</div><div className='sai-path-meta'><span>FROM<b>{traversal[0]}</b></span><span>TO<b>{traversal.at(-1)}</b></span><span>STEPS<b>{traversal.length}</b></span><span>STATE NOW<b>{record.stateId}</b></span></div></div>}
  {tab==='LEDGER'&&<div className='sai-ledger'><header><ShieldCheck/><div><b>Hash-chained scar / decision / improvement ledger</b><span>{ledgerProof.passed?'CHAIN VERIFIED':'CHAIN FAILURE'} · {ledgerProof.entries} entries</span></div></header><div className='sai-ledger-list'>{ledger.slice().reverse().map((x,i)=><article key={x.entry_hash}><code>{ledger.length-i}</code><div><b>{x.event}</b><span>{new Date(x.timestamp_utc).toLocaleString()}</span><small>prev {x.previous_hash.slice(0,16)}… → {x.entry_hash.slice(0,16)}…</small></div></article>)}</div></div>}
  {tab==='SELFTEST'&&<div className='sai-selftest'><div className='sai-test-grid'>{SAI_B059_DONOR_SELFTEST.map(x=><article key={x.name}><ShieldCheck/><div><b>{x.name}</b><p>{x.requirement}</p></div><span>DONOR {x.donor}</span><strong>{x.hosted}</strong></article>)}</div><div className='sai-boundary'><ShieldCheck/><p>The B059 acceptance report passed its local Linux/Python, SQLite FTS5, HTTP/API, corpus/query/traversal/ledger and unit-test path. Windows batch invocation, J: installation and native target-machine behavior remain separate evidence domains.</p></div></div>}
  {tab==='FABRIC'&&<div className='sai-fabric-restored'><div className='sai-boundary'><Network/><p><b>Cross-build intelligence fabric retained.</b> B059 is the deterministic grounded core donor; current hosted routing, Forecast+, Mode188, Hybrid, trainer and render donors remain separately classified by executable evidence.</p></div><div className='sai-source-grid'>{INTELLIGENCE_CONTRIBUTORS.map((x,i)=><article key={x.id}><header><code>{String(i+1).padStart(2,'0')}</code><b>{x.status}</b><span>{x.roles.join(' · ')}</span></header><p><strong>{x.name}</strong><br/>{x.capability}</p><small>{x.source} · {x.truth}</small></article>)}</div></div>}
  <footer className='sai-footer'><ShieldCheck/><p><b>Truth boundary:</b> {SAI_B059_BOUNDARY} Source catalog membership is not executable mode count. Self-improvement means governed proposal + verified source change + release evidence, not hidden browser mutation.</p><button onClick={()=>download('OMEGA_SAI_B059_HOSTED_RECEIPT.json',{...receipt,sourceBackedModes:{applied:summary.appliedCount,gated:summary.gatedCount,catalog:summary.catalogCount},improvement,ledger:ledgerProof})}><Download/>Export hosted receipt</button></footer>
 </section>
}
