import{useEffect,useMemo,useState}from'react';
import{Crosshair,Database,ExternalLink,RefreshCw,Satellite,ShieldCheck}from'lucide-react';
import SARTruthInstrumentR280 from'./SARTruthInstrumentR280Surface';
import{api}from'./platformAdapter';
import type{SarObservationR280,SarPolarizationR280,SarProductLevelR280}from'./sarTruthR280';
import'./sarLiveR285.css';

type ProductMode='GRD'|'SLC';
type LiveProduct={id:string;collection:string;catalogUrl:string;acquiredAt:string|null;platform:string|null;constellation:string|null;instrumentMode:string|null;frequencyBand:string|null;centerFrequencyGHz:number|null;polarizations:string[];orbitState:string|null;relativeOrbit:number|null;incidenceAngle:number|null;bbox:number[]|null;geometry:any;previewUrl:string|null;previewAssetKey:string|null;assetCount:number;dataAssetCount:number;catalogOnly:true;sourceEvidenceBound:false;nativeDataBound:false;complexDataBound:false;truth:string};
type CatalogResponse={ok:boolean;schema:string;state:string;verifiedAt:string;latencyMs:number;target:{lat:number;lon:number;crs:string};query:{product:ProductMode;collection:string;days:number;limit:number;bbox:number[];datetime:string};source:{provider:string;endpoint:string};products:LiveProduct[];latest:LiveProduct|null;evidenceHash:string;truthBoundary:string;error?:string};
type Props={lat:number;lon:number;onTargetChange?:(lat:number,lon:number)=>void};
const short=(x:string,n=34)=>x.length>n?`${x.slice(0,n-1)}…`:x;
const valid=(n:unknown)=>typeof n==='number'&&Number.isFinite(n);
function pol(p:string[]):SarPolarizationR280{const q=p.map(x=>x.toUpperCase());if(q.length>=4)return'QUAD';if(q.length>=2)return'DUAL';const one=q[0];return one==='HH'||one==='VV'||one==='HV'||one==='VH'?one:'UNKNOWN'}
function productLevel(p:LiveProduct,mode:ProductMode):SarProductLevelR280{return mode==='SLC'||/slc/i.test(p.collection)?'SLC':'GRD'}
function footprint(g:any):Array<[number,number]>|undefined{const ring=g?.type==='Polygon'?g?.coordinates?.[0]:g?.type==='MultiPolygon'?g?.coordinates?.[0]?.[0]:null;if(!Array.isArray(ring))return undefined;const rows=ring.map((x:any)=>[Number(x?.[0]),Number(x?.[1])] as [number,number]).filter((x:[number,number])=>Number.isFinite(x[0])&&Number.isFinite(x[1]));return rows.length>=3?rows:undefined}
function observation(p:LiveProduct,mode:ProductMode):SarObservationR280{return{
 id:`r285-${p.id}`,missionId:'sentinel-1',sensor:'C-SAR',productId:p.id,productLevel:productLevel(p,mode),band:'C',frequencyGHz:p.centerFrequencyGHz??5.405,wavelengthCm:5.55,polarization:pol(p.polarizations),
 provenance:{sourceId:p.id,sourceUrl:p.catalogUrl||undefined,provider:'Copernicus Data Space Ecosystem STAC · catalogue metadata',acquiredAt:p.acquiredAt||new Date(0).toISOString(),receivedAt:new Date().toISOString(),processingParameters:{catalogBound:true,assetCount:p.assetCount,dataAssetCount:p.dataAssetCount,instrumentMode:p.instrumentMode||null,relativeOrbit:p.relativeOrbit,orbitHandled:false,topographyHandled:false,atmosphereHandled:false,unwrappedPhaseBound:false,noiseCharacterized:false}},
 geometry:{crs:'EPSG:4326',datum:'WGS84',surfaceClass:'SCATTERING_SURFACE',orbitDirection:p.orbitState?.toUpperCase()==='ASCENDING'?'ASCENDING':p.orbitState?.toUpperCase()==='DESCENDING'?'DESCENDING':'UNKNOWN',incidenceDeg:valid(p.incidenceAngle)?p.incidenceAngle!:undefined,lookDirection:'UNKNOWN',footprint:footprint(p.geometry)},
 truth:'CATALOG_ONLY',missingness:['NO_SOURCE'],residuals:{notes:['Real STAC acquisition metadata is bound. Native measurement bytes and derived numerical arrays are not bound by catalogue discovery alone.']},nativeDataBound:false,complexDataBound:false,sourceEvidenceBound:false
}}
const EMPTY: SarObservationR280={id:'r285-no-catalog-result',missionId:'sentinel-1',sensor:'C-SAR',productLevel:'UNKNOWN',band:'C',frequencyGHz:5.405,wavelengthCm:5.55,polarization:'UNKNOWN',provenance:{sourceId:'no-returned-acquisition',provider:'Copernicus Data Space Ecosystem STAC',acquiredAt:new Date(0).toISOString()},geometry:{crs:'EPSG:4326',datum:'WGS84',surfaceClass:'SCATTERING_SURFACE',orbitDirection:'UNKNOWN',lookDirection:'UNKNOWN'},truth:'CATALOG_ONLY',missingness:['NO_SOURCE'],residuals:{notes:['No matching acquisition metadata has been returned for the current query.']},nativeDataBound:false,complexDataBound:false,sourceEvidenceBound:false};

export default function SARLiveTruthR285({lat,lon,onTargetChange}:Props){
 const[mode,setMode]=useState<ProductMode>('GRD'),[days,setDays]=useState(60),[data,setData]=useState<CatalogResponse|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[draftLat,setDraftLat]=useState(lat),[draftLon,setDraftLon]=useState(lon),[previewFailed,setPreviewFailed]=useState(false);
 useEffect(()=>{setDraftLat(lat);setDraftLon(lon)},[lat,lon]);
 const load=async()=>{setBusy(true);setError('');try{const r=await api.get<CatalogResponse>(`/api/earth/sar/catalog?lat=${lat.toFixed(5)}&lon=${lon.toFixed(5)}&product=${mode}&days=${days}&limit=12`);setData(r.data);const rows=r.data?.products||[];setSelected(v=>rows.some(x=>x.id===v)?v:(rows[0]?.id||''));setPreviewFailed(false)}catch(e:any){setData(null);setError(e?.message||String(e))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[lat,lon,mode,days]);
 const products=data?.products||[],picked=products.find(x=>x.id===selected)||products[0]||null,obs=useMemo(()=>picked?observation(picked,mode):EMPTY,[picked,mode]);
 const applyTarget=()=>{const la=Math.max(-90,Math.min(90,Number(draftLat))),lo=Math.max(-180,Math.min(180,Number(draftLon)));setDraftLat(la);setDraftLon(lo);onTargetChange?.(la,lo)};
 const state=picked?'CATALOG BOUND':busy?'QUERYING':data?.state||'NO ACQUISITION';
 return <section className="sar-r285-live" data-r285-state={state.replaceAll(' ','_')}>
  <header className="r285-livebar"><div className="r285-livebrand"><span><Satellite/></span><div><small>OMEGA · R285 · LIVE SAR DATA FIDELITY</small><h2>Sentinel‑1 source workstation</h2><p>Returned acquisition metadata drives the panel. Unbound pixels and derived fields stay visibly unavailable.</p></div></div><div className="r285-live-state"><i/><span><small>RETURN STATE</small><b>{state}</b></span><button type="button" onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/>{busy?'Querying':'Refresh source'}</button></div></header>
  <div className="r285-querybar"><div className="r285-target"><Crosshair/><label>LAT<input type="number" min="-90" max="90" step=".01" value={draftLat} onChange={e=>setDraftLat(Number(e.target.value))}/></label><label>LON<input type="number" min="-180" max="180" step=".01" value={draftLon} onChange={e=>setDraftLon(Number(e.target.value))}/></label><button type="button" onClick={applyTarget}>Query target</button></div><div className="r285-mode"><button type="button" aria-pressed={mode==='GRD'} onClick={()=>setMode('GRD')}>GRD · calibrated intensity candidate</button><button type="button" aria-pressed={mode==='SLC'} onClick={()=>setMode('SLC')}>SLC · complex-data candidate</button><label>WINDOW<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label></div></div>
  <div className="r285-source-ribbon"><span><Database/><b>{data?.source?.provider||'Copernicus Data Space Ecosystem STAC'}</b></span><span>WGS84 {lat.toFixed(5)}, {lon.toFixed(5)}</span><span>{data?.verifiedAt?new Date(data.verifiedAt).toLocaleString():'not yet returned'}</span><span>{data?.latencyMs!=null?`${data.latencyMs} ms`:'—'}</span><strong>{products.length} acquisition{products.length===1?'':'s'}</strong></div>
  <div className="r285-live-layout">
   <aside className="r285-products"><header><div><small>RETURNED ACQUISITIONS</small><b>{data?.query?.collection||`sentinel-1-${mode.toLowerCase()}`}</b></div><ShieldCheck/></header>{error&&<div className="r285-source-error"><b>SOURCE QUERY FAILED</b><span>{error}</span><small>No acquisition is fabricated.</small></div>}{!error&&!busy&&!products.length&&<div className="r285-source-empty"><Satellite/><b>No matching acquisition returned</b><span>Expand the time window or move the target.</span></div>}<div className="r285-product-list">{products.map((p,i)=><button type="button" key={p.id} className={p.id===picked?.id?'active':''} onClick={()=>{setSelected(p.id);setPreviewFailed(false)}}><span className="r285-rank">{String(i+1).padStart(2,'0')}</span><span className="r285-card-copy"><b>{short(p.id,31)}</b><small>{p.acquiredAt?new Date(p.acquiredAt).toLocaleString():'acquisition time missing'}</small><em>{p.instrumentMode||'mode —'} · {p.orbitState||'orbit —'} · {p.polarizations.join('/')||'pol —'}</em></span><span className="r285-card-proof"><i/>{p.dataAssetCount} data</span></button>)}</div>
   </aside>
   <main className="r285-stage">
    <div className="r285-product-head"><div><small>SELECTED SOURCE RECORD</small><h3>{picked?.id||'No acquisition selected'}</h3><p>{picked?`${picked.platform||'Sentinel‑1'} · ${picked.instrumentMode||'mode unavailable'} · relative orbit ${picked.relativeOrbit??'—'} · incidence ${picked.incidenceAngle!=null?`${picked.incidenceAngle.toFixed(2)}°`:'—'}`:'The analytical panel remains source-empty until a real catalogue record returns.'}</p></div><div className="r285-product-badges"><span className={picked?'bound':''}>CATALOG {picked?'BOUND':'UNBOUND'}</span><span>NATIVE PIXELS UNBOUND</span><span>DERIVED FIELDS UNBOUND</span>{picked?.catalogUrl&&<a href={picked.catalogUrl} target="_blank" rel="noreferrer">STAC record<ExternalLink/></a>}</div></div>
    {picked?.previewUrl&&!previewFailed&&<figure className="r285-preview"><img src={picked.previewUrl} alt={`Returned catalogue preview for ${picked.id}`} onError={()=>setPreviewFailed(true)}/><figcaption><b>RETURNED CATALOGUE PREVIEW</b><span>{picked.previewAssetKey||'preview asset'} · visual reference only · not a decoded SAR measurement raster</span></figcaption></figure>}
    <SARTruthInstrumentR280 observation={obs} catalogBound={!!picked} allowDemonstration={false}/>
   </main>
  </div>
  <footer className="r285-truth-law"><ShieldCheck/><div><b>R285 DATA TRUTH</b><p>{data?.truthBoundary||'Catalogue metadata, native measurement arrays, and derived products remain separate evidence classes.'}</p></div><code>{data?.evidenceHash||'catalog evidence hash unavailable'}</code></footer>
 </section>
}
