import{sarAssetProbeR325}from'./sarAssetProbeR325.js';
import{sarNativeRasterR326,R326_INTERNAL,R326_TESTABLE}from'./sarNativeRasterR326.js';
export const SAR_MEASUREMENT_RASTER_SCHEMA_R337='OMEGA_SAR_MEASUREMENT_RASTER_R337';
const MAX_BLOCK_BYTES=2*1024*1024,MAX_TOTAL_COMPRESSED=8*1024*1024,MAX_BLOCKS=64,TARGET_MAX=48;
const{fetchRange,entryValues,collectIfds,chooseIfd,georefForIfd,decompress,outputShape,planSamples,finiteRange}=R326_INTERNAL;
function complexAt(bytes,index,le){const off=index*4;if(off<0||off+4>bytes.byteLength)return null;const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),i=dv.getInt16(off,le),q=dv.getInt16(off+2,le);return Number.isFinite(i)&&Number.isFinite(q)?{i,q,amplitude:Math.hypot(i,q),phaseRad:Math.atan2(q,i)}:null}
function phaseRange(values,mask){let n=0;for(let i=0;i<values.length;i++)if(mask[i]&&Number.isFinite(values[i]))n++;return{lo:-Math.PI,hi:Math.PI,count:n}}
function geoPayload(geo,meta){const corners=geo.affineBound?[geo.point(0,0),geo.point(meta.width-1,0),geo.point(meta.width-1,meta.height-1),geo.point(0,meta.height-1)]:[];return{bound:geo.bound,affineBound:geo.affineBound,gcpBound:geo.gcpBound,method:geo.method,crs:geo.crs,epsg:geo.epsg,affine:geo.affine,corners,gcpCount:geo.gcpCount,gcps:geo.gcps}}
async function decodeSlc(url){
 const started=Date.now(),probe=await sarAssetProbeR325(url),base={schema:SAR_MEASUREMENT_RASTER_SCHEMA_R337,revision:'R337',verifiedAt:new Date().toISOString(),collection:probe.collection,productId:probe.productId,assetKey:probe.assetKey,probeState:probe.state};
 if(!probe.nativeByteEvidenceBound||!probe.asset?.href)return{ok:false,...base,state:probe.state==='AUTH_REQUIRED'?'AUTH_REQUIRED':'BYTE_EVIDENCE_REQUIRED',probe,truthBoundary:'R337 decodes only an exact SLC measurement asset whose byte/container evidence passed R325.'};
 if(probe.collection!=='sentinel-1-slc')return{ok:false,...base,state:'NOT_SLC',probe,truthBoundary:'R337 complex ingress is restricted to Sentinel-1 SLC assets. GRD is delegated to the proven R326 scalar decoder.'};
 try{
  const href=probe.asset.href,header=await fetchRange(href,0,16),ctx=R326_TESTABLE.parseHeader(header),ifds=await collectIfds(href,ctx),meta=chooseIfd(ifds),geo=await georefForIfd(href,ctx,meta.ifd);
  if(meta.planar!==1||meta.samplesPerPixel!==1)return{ok:false,...base,state:'RASTER_LAYOUT_HELD',probe,decoder:{planar:meta.planar,samplesPerPixel:meta.samplesPerPixel},truthBoundary:'R337 admits Sentinel-1 SLC only in the mission-specified contiguous one-complex-sample-per-pixel layout.'};
  if(meta.bits!==32||meta.sampleFormat!==5)return{ok:false,...base,state:'COMPLEX_ENCODING_HELD',probe,decoder:{bits:meta.bits,sampleFormat:meta.sampleFormat},truthBoundary:'Sentinel-1 SLC truth requires BitsPerSample=32 and SampleFormat=5 (complex signed int16 I/Q). Other encodings remain held.'};
  if(meta.compression!==1)return{ok:false,...base,state:'SLC_COMPRESSION_HELD',probe,decoder:{compression:meta.compression},truthBoundary:'The Sentinel-1 product specification defines uncompressed SLC measurement TIFF. R337 refuses to guess a non-standard compressed complex layout.'};
  let{w,h}=outputShape(meta.width,meta.height,TARGET_MAX),plan=planSamples(meta,w,h);while(plan.blocks.size>MAX_BLOCKS&&(w>4||h>4)){w=Math.max(4,Math.floor(w*.8));h=Math.max(4,Math.floor(h*.8));plan=planSamples(meta,w,h)}
  if(plan.blocks.size>MAX_BLOCKS)return{ok:false,...base,state:'BLOCK_BUDGET_HELD',probe,decoder:{requestedBlocks:plan.blocks.size,maxBlocks:MAX_BLOCKS},truthBoundary:'The SLC scene exceeds the bounded Worker decode budget. Full burst processing must move to the governed host compute path.'};
  const ifd=meta.ifd,offsetTag=plan.tiled?324:273,countTag=plan.tiled?325:279,offsets=(await entryValues(href,ctx,ifd.entries.get(offsetTag),200000)).map(Number),counts=(await entryValues(href,ctx,ifd.entries.get(countTag),200000)).map(Number);
  if(!offsets.length||offsets.length!==counts.length)throw new Error('BLOCK_OFFSETS_COUNTS_MISSING');
  let compressedTotal=0;for(const block of plan.blocks.keys()){const n=counts[block];if(!Number.isSafeInteger(n)||n<1||n>MAX_BLOCK_BYTES)throw new Error(`BLOCK_BYTECOUNT_${block}_${n}`);compressedTotal+=n}if(compressedTotal>MAX_TOTAL_COMPRESSED)throw new Error(`COMPRESSED_BUDGET_${compressedTotal}`);
  const total=w*h,I=new Array(total).fill(0),Q=new Array(total).fill(0),amplitude=new Array(total).fill(0),phase=new Array(total).fill(0),mask=new Array(total).fill(0),blockReceipts=[];
  for(const[block,points]of plan.blocks){const offset=offsets[block],count=counts[block];if(!Number.isSafeInteger(offset)||offset<0)throw new Error(`BLOCK_OFFSET_${block}`);const compressed=await fetchRange(href,offset,count),raw=await decompress(compressed,meta.compression),blockRows=plan.tiled?plan.blockH:Math.min(plan.blockH,meta.height-(Math.floor(block/plan.across)*plan.blockH)),expected=plan.blockW*blockRows*4;if(raw.byteLength<expected)throw new Error(`BLOCK_DECODE_SHORT_${block}_${raw.byteLength}_${expected}`);for(const p of points){const idx=p.oy*w+p.ox,local=p.ly*plan.blockW+p.lx,z=complexAt(raw,local,ctx.le);if(z){I[idx]=z.i;Q[idx]=z.q;amplitude[idx]=z.amplitude;phase[idx]=z.phaseRad;mask[idx]=1}}blockReceipts.push({block,offset,compressedBytes:count,decodedBytes:raw.byteLength})}
  const ampRange=finiteRange(amplitude,mask),pRange=phaseRange(phase,mask);if(!ampRange.count||!pRange.count)throw new Error('NO_FINITE_COMPLEX_SAMPLES');
  const raster={width:w,height:h,sourceId:`${probe.productId}:${probe.assetKey}`,native:true,nativeIntensity:amplitude,complexI:I,complexQ:Q,phaseRad:phase,validMask:mask,sourceUnits:'NATIVE_COMPLEX_IQ_MAGNITUDE',ranges:{nativeIntensity:[ampRange.lo,ampRange.hi]},sampling:{sourceWidth:meta.width,sourceHeight:meta.height,selectedIfdOffset:meta.ifd.offset,overview:false,method:'EVEN_GRID_NATIVE_COMPLEX_SAMPLE',validSamples:ampRange.count,totalSamples:total},georeference:geoPayload(geo,meta)};
  return{ok:true,...base,state:'COMPLEX_SAMPLES_BOUND',latencyMs:Date.now()-started,nativeDataBound:true,sourceEvidenceBound:true,complexDataBound:true,calibrationBound:false,amplitudeBound:false,derivedFieldBound:true,raster,decoder:{container:probe.tiff?.container||null,width:meta.width,height:meta.height,bits:meta.bits,sampleFormat:meta.sampleFormat,compression:meta.compression,planar:meta.planar,samplesPerPixel:meta.samplesPerPixel,tiled:plan.tiled,tileWidth:meta.tileWidth||null,tileHeight:meta.tileHeight||null,rowsPerStrip:meta.rowsPerStrip||null,ifdCount:ifds.length,selectedIfdOffset:meta.ifd.offset,blocksRead:plan.blocks.size,compressedBytesRead:compressedTotal,blockReceipts,complexLayout:'I16_Q16_INTERLEAVED',georeference:{bound:geo.bound,affineBound:geo.affineBound,gcpBound:geo.gcpBound,method:geo.method,crs:geo.crs,epsg:geo.epsg,gcpCount:geo.gcpCount}},probe:{state:probe.state,prefix:probe.prefix,http:probe.http,asset:probe.asset},truthBoundary:'R337 binds exact bounded Sentinel-1 SLC complex I/Q samples and derives only per-sample magnitude and wrapped phase via hypot(I,Q) and atan2(Q,I). This does not establish radiometric calibration, co-registration, coherence, interferometric phase between acquisitions, unwrapping, atmospheric correction, topographic correction, or deformation.'};
 }catch(e){return{ok:false,...base,state:'COMPLEX_DECODE_HELD',latencyMs:Date.now()-started,error:e instanceof Error?e.message:String(e),probe,truthBoundary:'Complex decode failure remains explicit; no phase, coherence, interferogram or deformation is fabricated.'}}
}
export async function sarMeasurementRasterR337(url){const collection=String(url.searchParams.get('collection')||'').toLowerCase();if(collection==='sentinel-1-grd'){const r=await sarNativeRasterR326(url);return{...r,schema:SAR_MEASUREMENT_RASTER_SCHEMA_R337,revision:'R337',measurementKind:'GRD_INTENSITY',complexDataBound:false,truthBoundary:`R337 delegated GRD ingress to R326. ${r.truthBoundary||''}`}}if(collection==='sentinel-1-slc')return{...(await decodeSlc(url)),measurementKind:'SLC_COMPLEX'};return{ok:false,schema:SAR_MEASUREMENT_RASTER_SCHEMA_R337,revision:'R337',state:'INVALID_REQUEST',collection,verifiedAt:new Date().toISOString(),truthBoundary:'Only Sentinel-1 GRD and SLC measurement collections are admitted.'}}
export const R337_TESTABLE=Object.freeze({complexAt,phaseRange});