import{clamp01R280,normalizeDbR280,normalizeLinearR280,normalizePhaseR280,normalizeSignedR280}from'./sarVisualMathR280';
export interface SarRasterFieldR283{
 width:number;height:number;sourceId:string;native:boolean;
 nativeIntensity?:number[];validMask?:number[];sourceUnits?:string;sampling?:{sourceWidth:number;sourceHeight:number;selectedIfdOffset:number;overview:boolean;method:string;validSamples:number;totalSamples:number};georeference?:{bound:boolean;affineBound?:boolean;gcpBound?:boolean;method:string;crs:string|null;epsg:number|null;affine:number[]|null;corners:Array<{x:number;y:number}|null>;gcpCount?:number;gcps?:Array<{pixel:number;line:number;zPixel:number;x:number;y:number;z:number}>};
 amplitudeDb?:number[];phaseRad?:number[];coherence?:number[];losDisplacementM?:number[];elevationM?:number[];polarimetricPower?:number[];multiBandRelative?:number[];timeStackRelative?:number[];uncertainty?:number[];quality?:number[];
 ranges?:{nativeIntensity?:[number,number];amplitudeDb?:[number,number];losDisplacementM?:[number,number];elevationM?:[number,number];polarimetricPower?:[number,number];multiBandRelative?:[number,number];timeStackRelative?:[number,number]};
}
const at=(a:number[]|undefined,i:number,mask?:number[])=>a&&i>=0&&i<a.length&&Number.isFinite(a[i])&&(!mask||mask[i]>0)?a[i]:null;
const range=(a:number[]|undefined,fallback:[number,number]):[number,number]=>{if(!a?.length)return fallback;let lo=Infinity,hi=-Infinity;for(const v of a)if(Number.isFinite(v)){lo=Math.min(lo,v);hi=Math.max(hi,v)}return Number.isFinite(lo)&&Number.isFinite(hi)?[lo,hi]:fallback};
export function rasterIndexR283(r:SarRasterFieldR283,x01:number,y01:number){const x=Math.max(0,Math.min(r.width-1,Math.round(x01*(r.width-1)))),y=Math.max(0,Math.min(r.height-1,Math.round(y01*(r.height-1))));return y*r.width+x}
export function rasterVisualValueR283(r:SarRasterFieldR283,view:string,x01:number,y01:number){const i=rasterIndexR283(r,x01,y01);let v:number|null=null;
 if(view==='SOURCE'){v=at(r.nativeIntensity,i,r.validMask);if(v!=null){const q=r.ranges?.nativeIntensity||range(r.nativeIntensity,[0,1]);if(q[0]>=0&&q[1]>q[0])return normalizeLinearR280(Math.log1p(v),Math.log1p(q[0]),Math.log1p(q[1]));return normalizeLinearR280(v,q[0],q[1])}v=at(r.amplitudeDb,i);if(v==null)return null;const q=r.ranges?.amplitudeDb||[-30,5];return normalizeDbR280(v,q[0],q[1])}
 if(view==='AMPLITUDE'){v=at(r.amplitudeDb,i);if(v==null)return null;const q=r.ranges?.amplitudeDb||[-30,5];return normalizeDbR280(v,q[0],q[1])}
 if(view==='TIME_STACK'){v=at(r.timeStackRelative,i);if(v==null)return null;const q=r.ranges?.timeStackRelative||range(r.timeStackRelative,[0,1]);return normalizeLinearR280(v,q[0],q[1])}
 if(view==='PHASE'||view==='INTERFEROGRAM'){v=at(r.phaseRad,i);return v==null?null:normalizePhaseR280(v)}
 if(view==='COHERENCE'){v=at(r.coherence,i);return v==null?null:clamp01R280(v)}
 if(view==='DEFORMATION'){v=at(r.losDisplacementM,i);if(v==null)return null;const q=r.ranges?.losDisplacementM||range(r.losDisplacementM,[-.05,.05]);const limit=Math.max(Math.abs(q[0]),Math.abs(q[1]),1e-9);return normalizeSignedR280(v,limit)}
 if(view==='ELEVATION'){v=at(r.elevationM,i);if(v==null)return null;const q=r.ranges?.elevationM||range(r.elevationM,[0,1]);return normalizeLinearR280(v,q[0],q[1])}
 if(view==='POLARIMETRY'){v=at(r.polarimetricPower,i);if(v==null)return null;const q=r.ranges?.polarimetricPower||range(r.polarimetricPower,[0,1]);return normalizeLinearR280(v,q[0],q[1])}
 if(view==='MULTI_BAND'){v=at(r.multiBandRelative,i);if(v==null)return null;const q=r.ranges?.multiBandRelative||range(r.multiBandRelative,[-1,1]);const limit=Math.max(Math.abs(q[0]),Math.abs(q[1]),1e-9);return normalizeSignedR280(v,limit)}
 if(view==='SCAR_UNCERTAINTY'){v=at(r.uncertainty,i);return v==null?null:clamp01R280(v)}
 if(view==='PROOF'){v=at(r.quality,i);return v==null?null:clamp01R280(v)}return null;
}
export function rasterCoverageR283(r:SarRasterFieldR283,view:string){const key=view==='SOURCE'?(r.nativeIntensity?.length?'nativeIntensity':'amplitudeDb'):view==='AMPLITUDE'?'amplitudeDb':view==='TIME_STACK'?'timeStackRelative':view==='PHASE'||view==='INTERFEROGRAM'?'phaseRad':view==='COHERENCE'?'coherence':view==='DEFORMATION'?'losDisplacementM':view==='ELEVATION'?'elevationM':view==='POLARIMETRY'?'polarimetricPower':view==='MULTI_BAND'?'multiBandRelative':view==='SCAR_UNCERTAINTY'?'uncertainty':view==='PROOF'?'quality':'amplitudeDb';const a=(r as any)[key] as number[]|undefined,mask=key==='nativeIntensity'?r.validMask:undefined,actual=a?.length?(mask?mask.filter(x=>x>0).length:a.filter(Number.isFinite).length):0;return{field:key,bound:actual>0,expected:r.width*r.height,actual,complete:actual===r.width*r.height}}
export function rasterTruthBoundaryR283(){return'R283/R326 raster rendering reads declared measurement arrays. SOURCE may read exact decoded native DN samples with an explicit validity mask; calibrated amplitude, time-stack and derived lenses require their own arrays. Missing arrays/pixels remain missing and never become claimed source evidence.'}
