import {useEffect,useMemo,useState} from 'react';
import {BrainCircuit,ChevronRight,Command,Earth,Eye,FolderOpen,Home,Link2,Menu,Search,Settings2,ShieldCheck,Sparkles,X} from 'lucide-react';
import {CAPABILITY_REALITY_LABEL,capabilityReality,isPrimaryOperationalCapability} from './capabilityAuthority';
import {RUNTIME_IDENTITY} from './runtimeIdentity';
import LivingRuntimePulseR33 from './LivingRuntimePulseR33';
import './singleFrameR27.css';
import './shellR31.css';
import './shellR32.css';
import './shellR33.css';

export type OmegaUiMode='AUTO'|'DESKTOP'|'MOBILE';
type DomainId='WORK'|'EXPLORE'|'INTELLIGENCE'|'EVIDENCE'|'SYSTEM';
type LegacyDomainId='COMMAND'|'VISUALIZE'|'EARTH'|'INTELLIGENCE'|'BUILD'|'EVIDENCE'|'SYSTEM';
const LEGACY_DOMAIN_LINEAGE:readonly LegacyDomainId[]=['COMMAND','VISUALIZE','EARTH','INTELLIGENCE','BUILD','EVIDENCE','SYSTEM'];
type Props={uiMode:OmegaUiMode;onUiMode:(mode:OmegaUiMode)=>void;panel:string;onNavigate:(panel:string)=>void;record:any;modePolicy:string;modeCount:number;busy:string};
type Domain={id:DomainId;label:string;description:string;routes:readonly string[]};
export const R27_REGISTERED_SURFACES=['Command Center','Hybrid Link','Workspace','Cockpit','Immersive Traversal','Matter Traversal','Extreme Traversal','Visual Instrument','Relativity','Earth Now','Forecast','Atlas','Traversal','Create','Field','Data Motion','Reality Lab','Atlas Calculator','Infinity','Convergence','Quality Compiler','Build Out','Projects','Render Queue','Assets','Modes','Kernel Intelligence','Evidence & Proof','Memory','Archive Census','Archive Operators','Development','Canon Evolution','SAI Lab','Governance','Consolidation','Instructions','Plugins','Settings','System','Validation','System Atlas','Scale Compiler','Control Matrix'] as const;
const ROUTE_NO=new Map(R27_REGISTERED_SURFACES.map((name,i)=>[name,String(i+1).padStart(2,'0')]));
const DOMAIN_ROUTES:Record<DomainId,readonly string[]>={WORK:['Command Center','Workspace','Cockpit','Hybrid Link','Create','Projects','Render Queue','Assets','Development'],EXPLORE:['Earth Now','Forecast','Reality Lab','Matter Traversal','Visual Instrument','Relativity','Atlas','Traversal','Field','Data Motion','Atlas Calculator','Infinity','Convergence','Scale Compiler'],INTELLIGENCE:['Modes','Kernel Intelligence','Memory','Canon Evolution','SAI Lab'],EVIDENCE:['Quality Compiler','Evidence & Proof','Archive Census','Archive Operators','Governance','Validation'],SYSTEM:['Instructions','Settings','System','System Atlas','Control Matrix']};
const operational=(x:readonly string[])=>x.filter(isPrimaryOperationalCapability);
const DOMAINS:readonly Domain[]=[{id:'WORK',label:'Work',description:'Ask · act · continue',routes:operational(DOMAIN_ROUTES.WORK)},{id:'EXPLORE',label:'Explore',description:'Earth · matter · motion · scale',routes:operational(DOMAIN_ROUTES.EXPLORE)},{id:'INTELLIGENCE',label:'Intelligence',description:'AI · modes · memory · learning',routes:operational(DOMAIN_ROUTES.INTELLIGENCE)},{id:'EVIDENCE',label:'Evidence',description:'Proof · archive · validation',routes:operational(DOMAIN_ROUTES.EVIDENCE)},{id:'SYSTEM',label:'System',description:'Settings · topology · instructions',routes:operational(DOMAIN_ROUTES.SYSTEM)}];
const ALL_OPERATIONAL=Array.from(new Set(DOMAINS.flatMap(x=>x.routes)));const iconFor=(id:DomainId)=>id==='WORK'?Sparkles:id==='EXPLORE'?Eye:id==='INTELLIGENCE'?BrainCircuit:id==='EVIDENCE'?ShieldCheck:Settings2;const domainFor=(panel:string)=>DOMAINS.find(d=>d.routes.includes(panel))||DOMAINS[0];
function useCompact(uiMode:OmegaUiMode){const[small,setSmall]=useState(()=>typeof window!=='undefined'?window.matchMedia('(max-width: 900px)').matches:false);useEffect(()=>{const m=window.matchMedia('(max-width: 900px)'),f=()=>setSmall(m.matches);f();m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);return uiMode==='MOBILE'||(uiMode==='AUTO'&&small)}
export function LayoutModeSwitch({value,onChange,compact=false}:{value:OmegaUiMode;onChange:(mode:OmegaUiMode)=>void;compact?:boolean}){return <div className={'r27-layout-switch '+(compact?'compact':'')} role='group' aria-label='Workspace layout'>{(['AUTO','DESKTOP','MOBILE'] as OmegaUiMode[]).map(m=><button key={m} className={value===m?'active':''} aria-pressed={value===m} onClick={()=>onChange(m)}>{compact?m[0]:m}</button>)}</div>}
function Route({name,panel,onNavigate,close}:{name:string;panel:string;onNavigate:(p:string)=>void;close?:()=>void}){const reality=capabilityReality(name);return <button className={'r27-route '+(name===panel?'active':'')} data-route-number={ROUTE_NO.get(name)} data-capability-reality={reality} aria-current={name===panel?'page':undefined} onClick={()=>{onNavigate(name);close?.()}}><span><b>{name}</b><small>{CAPABILITY_REALITY_LABEL[reality]}</small></span><ChevronRight size={15}/></button>}
function SearchBox({panel,onNavigate,close}:{panel:string;onNavigate:(p:string)=>void;close?:()=>void}){const[q,setQ]=useState('');const rows=useMemo(()=>ALL_OPERATIONAL.filter(x=>x.toLowerCase().includes(q.trim().toLowerCase())),[q]);return <div className='r27-search'><label><Search size={16}/><input aria-label='Search working capabilities' value={q} onChange={e=>setQ(e.target.value)} placeholder='Find anything in OMEGA…'/></label>{q&&<div className='r27-search-results'>{rows.map(x=><Route key={x} name={x} panel={panel} onNavigate={onNavigate} close={close}/>)}{rows.length===0&&<p>No working capability matches.</p>}</div>}</div>}
function ActionShortcuts({onNavigate,compact=false,close}:{onNavigate:(p:string)=>void;compact?:boolean;close?:()=>void}){const go=(p:string)=>{onNavigate(p);close?.()};return <div className={compact?'r31-drawer-shortcuts r32-action-shortcuts':'r32-desktop-actions'}><button onClick={()=>go('Command Center')}><Command/><span><b>Ask / Act</b><small>Reason, remember, prepare and govern action</small></span></button><button onClick={()=>go('Workspace')}><FolderOpen/><span><b>Continue work</b><small>Return to the active workspace</small></span></button><button onClick={()=>go('Hybrid Link')}><Link2/><span><b>Connect PC</b><small>Pair host, run approved work, receive proof</small></span></button><button onClick={()=>go('Earth Now')}><Earth/><span><b>Earth now</b><small>Live evidence-gated Earth context</small></span></button><button onClick={()=>go('Evidence & Proof')}><ShieldCheck/><span><b>Evidence</b><small>Inspect what actually happened</small></span></button></div>}
function ToolBrowser({active,domain,setDomain,panel,onNavigate,close}:{active:Domain;domain:DomainId;setDomain:(d:DomainId)=>void;panel:string;onNavigate:(p:string)=>void;close?:()=>void}){return <><nav className='r27-mobile-domains'>{DOMAINS.map(d=>{const I=iconFor(d.id);return <button key={d.id} className={domain===d.id?'active':''} onClick={()=>setDomain(d.id)}><I size={17}/><span>{d.label}</span></button>})}</nav><section><header><span>{active.label}</span><small>{active.description}</small></header>{active.routes.map(x=><Route key={x} name={x} panel={panel} onNavigate={onNavigate} close={close}/>)}</section></>}
function DesktopFrame({panel,onNavigate,busy}:Omit<Props,'uiMode'|'onUiMode'|'modePolicy'|'modeCount'|'record'>){const current=domainFor(panel),[domain,setDomain]=useState<DomainId>(current.id);useEffect(()=>setDomain(current.id),[current.id]);const active=DOMAINS.find(x=>x.id===domain)||current;return <aside className='r27-desktop-frame' aria-label='OMEGA navigation'><header><button className='r27-home' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home size={17}/></button><div><b>OMEGA</b><small>{busy?'WORKING':'LIVING'} · {RUNTIME_IDENTITY.hostedBuild}</small></div></header><LivingRuntimePulseR33 onNavigate={onNavigate}/><ActionShortcuts onNavigate={onNavigate}/><SearchBox panel={panel} onNavigate={onNavigate}/><nav className='r27-domains'>{DOMAINS.map(d=>{const I=iconFor(d.id);return <button key={d.id} className={(domain===d.id?'selected ':'')+(current.id===d.id?'current':'')} onClick={()=>setDomain(d.id)}><I size={17}/><span>{d.label}</span></button>})}</nav><section className='r27-route-pane'><header><span>{active.label.toUpperCase()}</span><b>{active.description}</b></header><div>{active.routes.map(x=><Route key={x} name={x} panel={panel} onNavigate={onNavigate}/>)}</div></section></aside>}
function MobileFrame({panel,onNavigate,busy,uiMode,onUiMode,modePolicy,modeCount}:Props){void modePolicy;const[open,setOpen]=useState(false),current=domainFor(panel),[domain,setDomain]=useState<DomainId>(current.id);useEffect(()=>setDomain(current.id),[current.id]);const active=DOMAINS.find(x=>x.id===domain)||current;const direct=(name:string)=>{onNavigate(name);setOpen(false)};const openSystemAtlas=()=>{onNavigate('System Atlas');setOpen(false)};return <><header className='r27-mobile-head'><button className='r31-brand-button' onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))} aria-label='OMEGA home'><span className='r31-orb'/></button><div><b>OMEGA</b><small>{busy?'acting · ':''}{panel}</small></div><button onClick={()=>setOpen(true)} aria-label='Open OMEGA navigation'><Menu size={20}/></button></header><nav className='r27-mobile-bottom' aria-label='Primary navigation'><button onClick={()=>window.dispatchEvent(new CustomEvent('omega-home-request'))}><Home size={19}/><span>Now</span></button><button className={panel==='Command Center'?'active':''} onClick={()=>direct('Command Center')}><Command size={19}/><span>Ask</span></button><button className={panel==='Hybrid Link'?'active':''} onClick={()=>direct('Hybrid Link')}><Link2 size={19}/><span>PC</span></button><button className={panel==='Earth Now'?'active':''} onClick={()=>direct('Earth Now')}><Earth size={19}/><span>Earth</span></button><button onClick={()=>setOpen(true)}><Menu size={19}/><span>Tools</span></button></nav>{open&&<div className='r27-mobile-drawer r33-mobile-drawer' role='dialog' aria-modal='true' aria-label='OMEGA navigation'><header><div><b>What should OMEGA do now?</b><small>{busy?'Action in progress · ':''}{modeCount} source-backed operators available</small></div><button onClick={()=>setOpen(false)} aria-label='Close navigation'><X size={20}/></button></header><LivingRuntimePulseR33 onNavigate={direct} compact/><ActionShortcuts onNavigate={onNavigate} compact close={()=>setOpen(false)}/><SearchBox panel={panel} onNavigate={onNavigate} close={()=>setOpen(false)}/><details className='r33-all-tools'><summary>All tools <span>browse specialist surfaces</span></summary><ToolBrowser active={active} domain={domain} setDomain={setDomain} panel={panel} onNavigate={onNavigate} close={()=>setOpen(false)}/></details><footer><LayoutModeSwitch value={uiMode} onChange={onUiMode} compact/><button onClick={openSystemAtlas}>System map <ChevronRight size={14}/></button></footer></div>}</>}
export default function SingleFrameRuntimeShellR27(props:Props){void LEGACY_DOMAIN_LINEAGE;const compact=useCompact(props.uiMode);useEffect(()=>{document.documentElement.dataset.omegaFrame=compact?'mobile':'desktop';return()=>{delete document.documentElement.dataset.omegaFrame}},[compact]);return compact?<MobileFrame {...props}/>:<DesktopFrame panel={props.panel} onNavigate={props.onNavigate} busy={props.busy}/>}
