import {useEffect,useMemo,useRef,useState} from 'react';
import {Pause,Play,RotateCcw,ShieldCheck,Square,Volume2} from 'lucide-react';
import './somaAudio.css';

type Props={record:any};
type Lane={osc:OscillatorNode;gain:GainNode;pan:StereoPannerNode;phi:number;k:number};
const TAU=Math.PI*2,cl=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
const LANE_META=[
 ['α','Alpha seed'],['Base','Yellow carrier'],['Base+','Foundation pressure'],['011','+π/2 construct'],['Build','Constructive expansion'],['Excess','Saturation'],['Oppose','180° reversal'],['Cool','Correction'],['01-1','−π/2 prune'],['Return','Release / return'],['Ω','Integrate'],['α′','Renewal']
] as const;
function packetPhase(record:any){const a=Math.max(0,Number(record?.stateId||1)-1);return Math.floor((a%1728)/144)%12}
function packetControls(record:any){const m=record?.metrics||{},C=cl(Number(m.continuity)||0),Phi=cl(Number(m.plasticity)||0),q=cl(Number(m.contradiction)||0),L=cl(Number(m.burden)||0),e=cl(Number(m.evidence??C)||0);return{baseFrequency:Math.round(48+40*cl(.45*C+.55*Phi)),masterGain:Number((.035+.025*e).toFixed(3)),contrast:Number((.25+.65*cl((C+Phi+1-q)/3)).toFixed(2)),clockSeconds:Number((3.5+7.5*cl(.55*L+.45*(1-Phi))).toFixed(1)),C,Phi,q,L,e}}
function phaseGainShape(k:number,active:number,contrast:number){const dist=Math.min((k-active+12)%12,(active-k+12)%12),base=.018,peak=.09,halo=Math.max(0,1-dist/3);return base*(1-contrast)+(base+peak*halo)*contrast}
export default function SomaAudioEngine({record}:Props){
 const audio=useRef<AudioContext|null>(null),master=useRef<GainNode|null>(null),compressor=useRef<DynamicsCompressorNode|null>(null),lanes=useRef<Lane[]>([]),timer=useRef<number|null>(null);
 const packet=useMemo(()=>packetControls(record),[record]),packetP=useMemo(()=>packetPhase(record),[record]);
 const[activePhase,setActivePhaseState]=useState(packetP),[running,setRunning]=useState(false),[sequencing,setSequencing]=useState(false),[syncPacket,setSyncPacket]=useState(true),[baseFrequency,setBaseFrequency]=useState(packet.baseFrequency),[masterGain,setMasterGain]=useState(packet.masterGain),[contrast,setContrast]=useState(packet.contrast),[clockSeconds,setClockSeconds]=useState(packet.clockSeconds),[message,setMessage]=useState('Audio is off until you explicitly start it.');
 const stopTimer=()=>{if(timer.current!==null){window.clearInterval(timer.current);timer.current=null}};
 const setActivePhase=(k:number,smooth=true)=>{const next=((k%12)+12)%12;setActivePhaseState(next);if(audio.current){const now=audio.current.currentTime;for(const lane of lanes.current){const g=phaseGainShape(lane.k,next,contrast);lane.gain.gain.cancelScheduledValues(now);lane.gain.gain.setTargetAtTime(running?g:.0001,now,smooth?.08:.01)}}};
 const applyParams=()=>{if(!audio.current)return;const now=audio.current.currentTime;master.current?.gain.setTargetAtTime(masterGain,now,.08);for(const lane of lanes.current){const ratio=1+(lane.k-5.5)*.0025;lane.osc.frequency.setTargetAtTime(baseFrequency*ratio,now,.12);lane.pan.pan.setTargetAtTime(Math.sin(lane.phi)*.72,now,.12)}setActivePhase(activePhase,false)};
 const initAudio=async()=>{if(audio.current)return audio.current;const Ctor=window.AudioContext||(window as any).webkitAudioContext;if(!Ctor)throw new Error('Web Audio is unavailable in this browser.');const ctx:AudioContext=new Ctor(),comp=ctx.createDynamicsCompressor(),out=ctx.createGain();comp.threshold.value=-28;comp.knee.value=18;comp.ratio.value=12;comp.attack.value=.015;comp.release.value=.22;out.gain.value=masterGain;comp.connect(out).connect(ctx.destination);const built:Lane[]=[];for(let k=0;k<12;k++){const osc=ctx.createOscillator(),gain=ctx.createGain(),pan=ctx.createStereoPanner(),phi=k*TAU/12;osc.type=k%3===1?'triangle':'sine';gain.gain.value=.0001;pan.pan.value=Math.sin(phi)*.62;const ratio=1+(k-5.5)*.0025;osc.frequency.value=baseFrequency*ratio;osc.connect(gain).connect(pan).connect(comp);osc.start();built.push({osc,gain,pan,phi,k})}audio.current=ctx;compressor.current=comp;master.current=out;lanes.current=built;return ctx};
 const start=async()=>{try{const ctx=await initAudio();if(ctx.state==='suspended')await ctx.resume();setRunning(true);setMessage('12-lane browser-local sonification active.');const now=ctx.currentTime;master.current?.gain.setTargetAtTime(masterGain,now,.08);for(const lane of lanes.current)lane.gain.gain.setTargetAtTime(phaseGainShape(lane.k,activePhase,contrast),now,.08)}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
 const stop=()=>{stopTimer();setSequencing(false);setRunning(false);if(audio.current){const now=audio.current.currentTime;for(const lane of lanes.current)lane.gain.gain.setTargetAtTime(.0001,now,.12);master.current?.gain.setTargetAtTime(.0001,now,.08)}setMessage('Audio stopped; packet state remains unchanged.')};
 const toggleSequence=async()=>{if(sequencing){stopTimer();setSequencing(false);setMessage('Phase sequence paused at the current lane.');return}await start();stopTimer();setSequencing(true);timer.current=window.setInterval(()=>setActivePhase((activePhase+1)%12),Math.max(.5,clockSeconds)*1000);setMessage('Packet phase sequence running locally in this browser.')};
 const syncFromPacket=()=>{setSyncPacket(true);setActivePhaseState(packetP);setBaseFrequency(packet.baseFrequency);setMasterGain(packet.masterGain);setContrast(packet.contrast);setClockSeconds(packet.clockSeconds);setMessage(`Controls synchronized from source packet ${record.stateId}.`)};
 useEffect(()=>{if(syncPacket){setActivePhaseState(packetP);setBaseFrequency(packet.baseFrequency);setMasterGain(packet.masterGain);setContrast(packet.contrast);setClockSeconds(packet.clockSeconds)}},[packetP,packet.baseFrequency,packet.masterGain,packet.contrast,packet.clockSeconds,syncPacket]);
 useEffect(()=>{applyParams()},[baseFrequency,masterGain,contrast]);
 useEffect(()=>{if(!sequencing)return;stopTimer();timer.current=window.setInterval(()=>setActivePhase((activePhase+1)%12),Math.max(.5,clockSeconds)*1000);return stopTimer},[sequencing,clockSeconds,activePhase]);
 useEffect(()=>()=>{stopTimer();for(const lane of lanes.current){try{lane.osc.stop()}catch{}}lanes.current=[];void audio.current?.close();audio.current=null},[]);
 return <section className='soma-audio-r45' aria-label='Echo Chamber SOMA Audio Engine'>
  <header><div><span>S17 · PHASE_COHERENT_AUDIO · LOCAL WEB AUDIO</span><h3>Echo-Chamber / SOMA Audio Engine</h3></div><strong>{running?'LOCAL ACTIVE':'READY'}</strong></header>
  <div className='soma-boundary'><ShieldCheck/><span><b>Sonification boundary.</b> The authoritative packet drives audible parameters; audio never changes canon state, evidence, route admission, or physical claims. Frequencies are an audible mapping, not measured frequencies of the represented system.</span></div>
  <div className='soma-actions'><button className='primary' onClick={start}><Play/>Start audio</button><button onClick={toggleSequence}>{sequencing?<Pause/>:<Volume2/>}{sequencing?'Pause sequence':'Sequence 12 phases'}</button><button onClick={stop}><Square/>Stop</button><button onClick={syncFromPacket}><RotateCcw/>Sync source packet</button><label><input type='checkbox' checked={syncPacket} onChange={e=>setSyncPacket(e.target.checked)}/>follow packet</label></div>
  <div className='soma-lanes'>{LANE_META.map(([code,label],k)=><button key={code} className={activePhase===k?'active':''} onClick={()=>{setSyncPacket(false);setActivePhase(k)}}><code>{String(k+1).padStart(2,'0')}</code><span><b>{code}</b><small>{label}</small></span><em>{k*30}°</em></button>)}</div>
  <div className='soma-controls'>
   <label><span>Audible carrier</span><input type='range' min='36' max='144' step='1' value={baseFrequency} onChange={e=>{setSyncPacket(false);setBaseFrequency(+e.target.value)}}/><b>{baseFrequency} Hz</b></label>
   <label><span>Master cap</span><input type='range' min='.005' max='.08' step='.001' value={masterGain} onChange={e=>{setSyncPacket(false);setMasterGain(+e.target.value)}}/><b>{masterGain.toFixed(3)}</b></label>
   <label><span>Lane contrast</span><input type='range' min='0' max='1' step='.01' value={contrast} onChange={e=>{setSyncPacket(false);setContrast(+e.target.value)}}/><b>{contrast.toFixed(2)}</b></label>
   <label><span>Phase clock</span><input type='range' min='.5' max='12' step='.1' value={clockSeconds} onChange={e=>{setSyncPacket(false);setClockSeconds(+e.target.value)}}/><b>{clockSeconds.toFixed(1)} s</b></label>
  </div>
  <div className='soma-readout'><article><span>Source state</span><b>{record.stateId}</b><small>packet phase {packetP+1}/12</small></article><article><span>Active lane</span><b>{activePhase+1}/12 · {LANE_META[activePhase][0]}</b><small>{LANE_META[activePhase][1]}</small></article><article><span>CΩ / Φ</span><b>{packet.C.toFixed(3)} / {packet.Phi.toFixed(3)}</b><small>q {packet.q.toFixed(3)} · Λ {packet.L.toFixed(3)}</small></article><article><span>Signal chain</span><b>12 lanes → compressor → master</b><small>stereo pan = sin(φ) · gain = discrete lane halo</small></article></div>
  <footer><span>{message}</span><small>Donor lineage: electric_bio_phase_engine_v1.html · software inventory S17. Browser user gesture is required by WebAudio policy.</small></footer>
 </section>
}
