import {useMemo,useState} from 'react';
import {Activity,ArrowRight,Calculator,ChevronRight,Database,GitBranch,Search,ShieldCheck,Waypoints} from 'lucide-react';
import {corpusState,evaluateCorpusModes} from './corpusRuntime';
import {compileSourceTraversal,R21_MODE_AUTHORITY,sourceBackedModeSummary,type SourceBackedModeResult} from './sourceBackedModeRuntimeR21';
import TransitionProofPanelR23 from './TransitionProofPanelR23';
import './sourceBackedModesR21.css';

type Props={record:any;address:number;onAddress:(address:number)=>void;onNavigate:(panel:string)=>void};
const fmt=(v:any,d=4)=>Number.isFinite(Number(v))?Number(v).toFixed(d):String(v??'—');
const statusLabel=(x:SourceBackedModeResult)=>x.state==='EXECUTED_EXACT'?'EXECUTED EXACT':x.state==='SOURCE_PACKET'?'SOURCE PACKET':x.state==='DERIVED_RUNTIME'?'DERIVED RUNTIME':'GATED';

export default function SourceBackedModesPanelR21({record,address,onAddress,onNavigate}:Props){
  const summary=useMemo(()=>sourceBackedModeSummary(record),[record]),catalog=useMemo(()=>evaluateCorpusModes(record),[record]),route=useMemo(()=>compileSourceTraversal(address,72),[address]),[query,setQuery]=useState(''),[showCatalog,setShowCatalog]=useState(false),[selectedModeId,setSelectedModeId]=useState('M001');
  const q=query.trim().toLowerCase(),catalogRows=catalog.results.filter((x:any)=>!q||`${x.name} ${x.category} ${x.operator} ${x.algebra} ${x.calculus}`.toLowerCase().includes(q));
  const implementedCount=summary.rows.length,registryOnlyCount=Math.max(0,summary.catalogCount-implementedCount);
  const activeMode=summary.rows.find(x=>x.id===selectedModeId&&x.state!=='GATED_MISSING_INPUTS')||summary.rows.find(x=>x.id==='M001')!;
  const modeTrace=useMemo(()=>route.path.map(x=>{const row=sourceBackedModeSummary(corpusState(x.address)).rows.find(m=>m.id===activeMode.id);return{address:x.address,stateId:x.stateId,value:row?.value??null,state:row?.state??'GATED_MISSING_INPUTS',decision:x.decision,dewey:x.dewey}}),[route,activeMode.id]);
  const numericTrace=modeTrace.map(x=>Number(x.value)).filter(Number.isFinite),traceMin=numericTrace.length?Math.min(...numericTrace):0,traceMax=numericTrace.length?Math.max(...numericTrace):0,traceSpan=Math.max(1e-9,traceMax-traceMin),hasNumericTrace=numericTrace.length===modeTrace.length&&numericTrace.length>0;
  const points=route.path.map((x,i)=>{const px=18+(i/Math.max(1,route.path.length-1))*964,raw=Number(modeTrace[i]?.value),score=hasNumericTrace?((raw-traceMin)/traceSpan):Math.max(0,Math.min(1,x.dewey/(1+x.dewey)));return{x,px,py:220-score*168}}),line=points.map(p=>`${p.px.toFixed(1)},${p.py.toFixed(1)}`).join(' ');
  const goStep=(n:number)=>{const p=route.path[Math.max(0,Math.min(route.path.length-1,n))];if(p)onAddress(p.address)};
  return <section className='special-app sbm21-app'>
    <header className='special-head'><div><span>SOURCE-BACKED CALCULUS · CANONICAL TRANSITION AUTHORITY</span><h2>Modes + Applied Calculus</h2></div><strong>{summary.appliedCount} APPLIED · {summary.gatedCount} GATED · {implementedCount} IMPLEMENTED</strong></header>
    <div className='sbm21-truth'><ShieldCheck/><div><b>{summary.catalogCount} catalog entries exist, but only {implementedCount} currently have hosted evaluation contracts.</b><span>{summary.exactCount} exact operators execute from current packet inputs · {summary.packetCount} source/derived runtime channels are exposed directly · {summary.gatedCount} implemented formulas remain gated · {registryOnlyCount} catalog entries are registry-only until their donor formula/input contracts are restored. Catalog membership is never reported as execution.</span></div></div>
    <div className='sbm21-kpis'><div><span>STATE</span><b>{record.stateId}</b><small>D{record.coordinates.d+1} · P{record.coordinates.p+1} · R{record.coordinates.r+1} · L{record.coordinates.l+1}</small></div><div><span>DEWEY S</span><b>{fmt(summary.executed.find(x=>x.id==='M001')?.value)}</b><small>(CΩ·Φ)/(q+Λ+ε)</small></div><div><span>MODE 188</span><b>{fmt(summary.executed.find(x=>x.id==='M002')?.value)}</b><small>{String(record.metrics.mode188)}</small></div><div><span>MODE COVERAGE</span><b>{implementedCount}/{summary.catalogCount}</b><small>{registryOnlyCount} awaiting donor contract restoration</small></div></div>
    <TransitionProofPanelR23 address={address} onAddress={onAddress}/>
    <section className='sbm21-route'><header><div><Waypoints/><span>ACTUAL ADMITTED TRAVERSAL · {activeMode.id}</span><b>{route.path.length} source states</b></div><div className='sbm21-route-actions'><button onClick={()=>onAddress(record.autoPing.previous)}>Previous</button><button onClick={()=>onAddress(record.autoPing.dataNext)}>Admitted next <ArrowRight/></button><button onClick={()=>goStep(12)}>Follow 12</button><button onClick={()=>onNavigate('Visual Instrument')}>Visual Instrument</button><button onClick={()=>onNavigate('Traversal')}>Traversal</button></div></header><svg viewBox='0 0 1000 250' role='img' aria-label={`Canonical source traversal traced by ${activeMode.name}`}><line x1='18' y1='220' x2='982' y2='220' className='sbm21-axis'/><polyline points={line} className='sbm21-route-line'/>{points.map((p,i)=><g key={`${p.x.address}-${i}`} className={`sbm21-node ${p.x.decision.toLowerCase()}`} onClick={()=>onAddress(p.x.address)}><circle cx={p.px} cy={p.py} r={i===0?7:4.5}/>{i%8===0&&<text x={p.px} y={Math.max(14,p.py-10)} textAnchor='middle'>{p.x.stateId}</text>}</g>)}</svg><footer><span>{hasNumericTrace?`vertical = ${activeMode.id} normalized across this admitted route`:'vertical = Dewey route geometry; active mode is categorical/source-bound'}</span><span>route = exact autoPing.dataNext sequence</span><b>{route.closed?'LOOP/CLOSURE DETECTED':'OPEN TRAVERSAL'}</b></footer><div className='special-boundary' data-active-mode={activeMode.id}><ShieldCheck/><span><b>{activeMode.id} · {activeMode.name} · {statusLabel(activeMode)}</b> · {activeMode.formula} · current {String(activeMode.value??'—')} · source {activeMode.source}. Each plotted sample is re-evaluated from that exact canonical route packet when the selected mode is numeric; gated formulas cannot be selected for trace execution.</span></div></section>
    <div className='sbm21-mode-columns'><section><header><Calculator/><b>EXECUTED / SOURCE-BOUND OPERATORS</b><span>{summary.appliedCount}</span></header><div className='sbm21-mode-list'>{summary.rows.filter(x=>x.state!=='GATED_MISSING_INPUTS').map(x=><article key={x.id} className={`${x.state.toLowerCase()} ${x.id===activeMode.id?'selected':''}`}><code>{x.id}</code><div><b>{x.name}</b><small>{x.formula}</small><em>{x.source}</em><p>{x.detail}</p><button onClick={()=>setSelectedModeId(x.id)} aria-pressed={x.id===activeMode.id}>Trace this mode</button></div><strong>{statusLabel(x)}<span>{x.value===null?'—':String(x.value)}</span></strong></article>)}</div></section><section><header><ShieldCheck/><b>FORMULAS HELD FOR MISSING INPUTS</b><span>{summary.gatedCount}</span></header><div className='sbm21-mode-list gated'>{summary.gated.map(x=><article key={x.id}><code>{x.id}</code><div><b>{x.name}</b><small>{x.formula}</small><em>{x.source}</em><p>Missing authoritative inputs: {x.missing.join(', ')}</p></div><strong>GATED</strong></article>)}</div></section></div>
    <section className='sbm21-catalog'><header><div><Database/><b>{summary.catalogCount}-SOURCE MODE REGISTRY</b><span>{implementedCount} hosted evaluation contracts · {registryOnlyCount} registry-only entries</span></div><div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search mode source registry…'/></label><button onClick={()=>setShowCatalog(v=>!v)}>{showCatalog?'Hide':'Inspect'} catalog</button></div></header>{showCatalog&&<div className='sbm21-catalog-grid'>{catalogRows.map((x:any)=><details key={x.id}><summary><code>{x.id}</code><span><b>{x.name}</b><small>{x.category}</small></span><strong>REGISTRY</strong><ChevronRight/></summary><div><p><b>Operator</b> {x.operator||'—'}</p><p><b>Algebra</b> {x.algebra||'—'}</p><p><b>Calculus</b> {x.calculus||'—'}</p><p><b>Proof requirement</b> {x.proof||'—'}</p><p><b>Ledger</b> {x.ledger||'—'}</p><em>Registry metadata is not an executable hosted operator until a source-backed evaluation contract is bound.</em></div></details>)}</div>}</section>
    <div className='sbm21-actions'><button onClick={()=>onNavigate('Relativity')}><GitBranch/>Dimensional Relativity</button><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Evidence & Proof</button><button onClick={()=>onNavigate('System Atlas')}><Database/>Software Atlas</button><button onClick={()=>onNavigate('Control Matrix')}><Activity/>Control Matrix</button></div>
    <div className='special-boundary'><ShieldCheck/>{R21_MODE_AUTHORITY.boundary} {route.boundary}</div>
  </section>
}
