import {useState} from 'react';
import {ShieldCheck} from 'lucide-react';
import {buildSourceSpatialAttestationPayloadR236,persistSourceSpatialControlAttestationR236,verifySourceSpatialControlAttestationR236} from './world/sourceSpatialControlAttestationR236.js';
import {emitOperationR86} from './omegaOperationBusR86';
import {activeProjectIdR87,recordProjectOperationR87} from './omegaProjectContinuityR87';

const ATTESTATION_EXAMPLE={schema:'OMEGA_SOURCE_SPATIAL_CONTROL_ATTESTATION_R236',revision:'R236',algorithm:'ECDSA_P256_SHA256',sourceIdentity:'independent-survey-control',payloadSha256:'<exact R236 payload SHA-256>',publicKeyJwk:{kty:'EC',crv:'P-256',x:'<base64url x> ',y:'<base64url y>'},keyFingerprintSha256:'<SHA-256 of canonical {kty,crv,x,y}>',signatureBase64:'<64-byte raw P-256 r||s signature, base64/base64url>',signedAt:'2026-09-08T20:00:00Z',keyId:'<governed source key id>'};

export default function SourceSpatialControlAttestationR236({sufficiency,validation,validationEvidence}:{sufficiency:any,validation:any,validationEvidence:any}){
 const[payload,setPayload]=useState<any>(null),[attestationText,setAttestationText]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const prepare=async()=>{if(busy)return;setBusy('prepare');setError('');try{const next=await buildSourceSpatialAttestationPayloadR236({sufficiency,validation,validationEvidence});if(!next.ok)throw new Error(`R236 lineage held: ${(next.missing||[]).join(', ')}`);setPayload(next)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 const verify=async()=>{if(busy)return;setBusy('verify');setError('');try{const attestation=JSON.parse(attestationText),next=await verifySourceSpatialControlAttestationR236({sufficiency,validation,validationEvidence,attestation});if(next.state.startsWith('HELD_'))throw new Error(`R236 held: ${(next.missing||[]).join(', ')}`);if(!persistSourceSpatialControlAttestationR236(next))throw new Error('R236 attestation receipt persistence failed');setResult(next);const projectId=activeProjectIdR87();const event=await emitOperationR86({type:'SOURCE_SPATIAL_CONTROL_ATTESTATION_VERIFIED',surface:'Living World',status:next.sourceAuthenticationProved?'PASS':next.sourceSignatureVerified?'HOLD':'FAIL',detail:`R236 ${next.state} · signature ${next.sourceSignatureVerified?'verified':'rejected'} · trusted key ${next.trustedSourceKeyMatched?'matched':'absent'}`,payload:{revision:'R236',receiptSha256:next.receiptSha256,r234ReceiptSha256:next.r234ReceiptSha256,r232ReceiptSha256:next.r232ReceiptSha256,payloadSha256:next.payloadSha256,attestationSha256:next.attestationSha256,keyFingerprintSha256:next.keyFingerprintSha256,sourceSignatureVerified:next.sourceSignatureVerified,trustedSourceKeyMatched:next.trustedSourceKeyMatched,sourceAuthenticationProved:next.sourceAuthenticationProved,spatialCalibrationProved:false,globalPhysicalRegistrationProved:false,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
 if(sufficiency?.state!=='CALIBRATION_SUFFICIENCY_ENVELOPE_PASSED'||sufficiency?.calibrationSufficiencyEnvelopePassed!==true)return null;
 const authenticated=result?.sourceAuthenticationProved===true,signed=result?.sourceSignatureVerified===true;
 return <div className='r206-world-mission' data-state={authenticated?'BOUND':'ASSEMBLED'} aria-label='R236 authenticated spatial control attestation'><div className='r206-world-mission-icon'><ShieldCheck/></div><div className='r206-world-mission-copy'><small>R234 → R236 · SOURCE ATTESTATION</small><b>{result?authenticated?'SOURCE KEY AUTHENTICATED':signed?'SIGNATURE VERIFIED · KEY NOT TRUSTED':'SOURCE ATTESTATION REJECTED':payload?'ATTESTED PAYLOAD READY':'SOURCE AUTHENTICATION READY'}</b><span>{result?`Signature ${signed?'verified':'rejected'} · trust anchor ${result.trustedSourceKeyMatched?'matched':'not enrolled'} · key ${String(result.keyFingerprintSha256||'').slice(0,16)}…`:payload?`Payload ${payload.payloadSha256} · sign these exact canonical bytes with the source's P-256 key.`:'Build the exact R232/R234-bound payload first. R236 will verify a detached P-256 signature but will not trust a self-supplied key.'}</span><em>{error||(authenticated?'The source key is code-pinned for this identity/method/frame scope. Calibration proof remains a separate gate.':signed?'The signature is mathematically valid, but no governed production trust anchor matches this key. Source authentication remains false.':'A provenance string, digest, Hybrid heartbeat, or low residual cannot substitute for a governed source trust anchor.')}</em>{payload&&<textarea aria-label='R236 canonical payload to sign' readOnly value={payload.payloadCanonical}/>} {!result&&<textarea aria-label='R236 detached source attestation JSON' value={attestationText} onChange={e=>setAttestationText(e.target.value)} placeholder={JSON.stringify(ATTESTATION_EXAMPLE)}/>}</div><div className='r206-world-mission-proof'><ShieldCheck/><span>exact R232 + R234 lineage</span><span>P-256 detached signature</span><span>code-pinned trust only</span><span>self-key ≠ authentication</span><span>Calibration still separate</span></div><div>{!payload&&<button onClick={prepare} disabled={Boolean(busy)}>{busy==='prepare'?'Binding…':'Build attested payload'}</button>}{payload&&!result&&<button onClick={verify} disabled={Boolean(busy)||!attestationText.trim()}>{busy==='verify'?'Verifying…':'Verify source attestation'}</button>}</div></div>;
}
