import{useEffect,useMemo,useState}from'react';
import{Database,GitBranch,Search,ShieldCheck,TriangleAlert}from'lucide-react';
import{R328_SOURCE_CANON_RECEIPT,R328_SOURCE_CANON_URL,compileComputationLanguageR328,crosswalkSourceExactRecordR328,loadSourceExactCanonR328,type R328CanonRow}from'./system/sourceExactCanonR328';
import'./sourceExactCanonR328.css';

const label=(v:string)=>v.replaceAll('_',' ');
const tally=(rows:R328CanonRow[],key:(r:R328CanonRow)=>string)=>{const m=new Map<string,number>();for(const r of rows){const k=key(r)||'UNSPECIFIED';m.set(k,(m.get(k)||0)+1)}return[...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))};

export default function SourceExactCanonR328(){
 const[rows,setRows]=useState<R328CanonRow[]>([]),[compiled,setCompiled]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[family,setFamily]=useState('ALL'),[epistemic,setEpistemic]=useState('ALL'),[crosswalk,setCrosswalk]=useState('ALL'),[selected,setSelected]=useState<string>('');
 useEffect(()=>{const controller=new AbortController();loadSourceExactCanonR328(controller.signal).then(x=>{setRows(x.rows);setCompiled(x.compiled)}).catch(e=>{if(e?.name!=='AbortError')setError(e instanceof Error?e.message:String(e))});return()=>controller.abort()},[]);
 const families=useMemo(()=>tally(rows,r=>r.source_family),[rows]),epistemics=useMemo(()=>tally(rows,r=>r.epistemic_status||'UNSPECIFIED'),[rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>{const x=crosswalkSourceExactRecordR328(r);return(family==='ALL'||r.source_family===family)&&(epistemic==='ALL'||(r.epistemic_status||'UNSPECIFIED')===epistemic)&&(crosswalk==='ALL'||x.state===crosswalk)&&(!q||`${r.record_id} ${r.source_family} ${r.category} ${r.concept_name} ${r.property_name} ${r.canonical_value} ${r.computation_language} ${r.epistemic_status} ${r.conflict_group}`.toLowerCase().includes(q))})},[rows,query,family,epistemic,crosswalk]);
 const active=rows.find(r=>r.record_id===selected)||filtered[0]||null,activeCode=active?compileComputationLanguageR328(active):null,activeMap=active?crosswalkSourceExactRecordR328(active):null;
 const states=compiled?Object.entries(compiled.crosswalk||{}):[];
 return <section className='r328-canon' data-r328-source-exact={compiled?.revision||'LOADING'}>
  <header className='r328-head'><div><span>R328 · SOURCE-EXACT SEMANTIC CANON</span><h2>3,743-record Canon Registry</h2><p>The semantic/provenance corpus is now a first-class source beside the 675-row implementation canon. Conflict variants stay intact; crosswalk state never becomes Canon admission.</p></div><div className='r328-status'>{error?<TriangleAlert/>:<ShieldCheck/>}<b>{error?'SOURCE HOLD':compiled?'SOURCE VERIFIED':'LOADING'}</b><small>{error||`SHA-256 ${R328_SOURCE_CANON_RECEIPT.sha256.slice(0,12)}…`}</small></div></header>
  <div className='r328-kpis'>
   <article><span>Records</span><b>{compiled?.rowCount??R328_SOURCE_CANON_RECEIPT.records}</b><small>exact source rows</small></article>
   <article><span>Concepts</span><b>{compiled?.census?.concepts??R328_SOURCE_CANON_RECEIPT.concepts}</b><small>{R328_SOURCE_CANON_RECEIPT.propertyNames} property names</small></article>
   <article><span>Conflict groups</span><b>{compiled?.census?.conflictGroups??R328_SOURCE_CANON_RECEIPT.conflictGroups}</b><small>{compiled?.census?.multiVariantConflictGroups??R328_SOURCE_CANON_RECEIPT.multiVariantConflictGroups} multivariant · preserved</small></article>
   <article><span>Computation heads</span><b>{compiled?.census?.computationHeads??R328_SOURCE_CANON_RECEIPT.computationHeads}</b><small>14 structural families + direct symbolic expressions</small></article>
   <article><span>Source families</span><b>{compiled?.census?.sourceFamilies??R328_SOURCE_CANON_RECEIPT.sourceFamilies}</b><small>{R328_SOURCE_CANON_RECEIPT.sourceFiles} recovered source files</small></article>
   <article><span>Epistemic statuses</span><b>{compiled?.census?.epistemicStatuses??R328_SOURCE_CANON_RECEIPT.epistemicStatuses}</b><small>physics/math/model/audit/proof remain distinct</small></article>
  </div>
  <div className='r328-crosswalk'>{states.map(([state,count])=><span key={String(state)} data-state={String(state).toLowerCase()}><b>{Number(count).toLocaleString()}</b><small>{label(String(state))}</small></span>)}</div>
  <div className='r328-controls'><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search record, concept, formula, source, conflict group…'/></label><select value={family} onChange={e=>setFamily(e.target.value)}><option value='ALL'>All source families</option>{families.map(([v,n])=><option key={v} value={v}>{v} · {n}</option>)}</select><select value={epistemic} onChange={e=>setEpistemic(e.target.value)}><option value='ALL'>All epistemic statuses</option>{epistemics.map(([v,n])=><option key={v} value={v}>{v} · {n}</option>)}</select><select value={crosswalk} onChange={e=>setCrosswalk(e.target.value)}><option value='ALL'>All implementation states</option>{states.map(([v,n])=><option key={String(v)} value={String(v)}>{label(String(v))} · {Number(n)}</option>)}</select><a href={R328_SOURCE_CANON_URL} target='_blank' rel='noreferrer'><Database/>Open exact source CSV</a></div>
  <div className='r328-body'>
   <div className='r328-table-wrap'><table><thead><tr><th>ID</th><th>Source / category</th><th>Concept / property</th><th>Canonical value</th><th>State</th></tr></thead><tbody>{filtered.slice(0,250).map(row=>{const x=crosswalkSourceExactRecordR328(row);return <tr key={row.record_id} data-active={active?.record_id===row.record_id?'true':'false'} onClick={()=>setSelected(row.record_id)}><td><button type='button' onClick={()=>setSelected(row.record_id)}>{row.record_id}</button></td><td><b>{row.source_family}</b><small>{row.category}</small></td><td><b>{row.concept_name}</b><small>{row.property_name}</small></td><td><code>{row.canonical_value}</code></td><td><span>{label(x.state)}</span></td></tr>})}</tbody></table>{filtered.length>250&&<p className='r328-limit'>Showing first 250 of {filtered.length.toLocaleString()} matching records. Search/filter operates across all {rows.length.toLocaleString()} indexed rows.</p>}</div>
   <aside className='r328-detail'>{active&&activeCode&&activeMap?<><header><GitBranch/><div><span>{active.record_id} · {active.source_family}</span><b>{active.concept_name}</b><small>{active.property_name}</small></div></header><section><small>CANONICAL VALUE</small><code>{active.canonical_value}</code></section><section><small>COMPUTATION LANGUAGE · {activeCode.family}</small><code>{active.computation_language}</code><p>{activeCode.boundary}</p></section><section><small>EPISTEMIC STATUS</small><b>{active.epistemic_status||'UNSPECIFIED'}</b><p>{active.units_or_frame||'units/frame not declared'}</p></section><section><small>IMPLEMENTATION CROSSWALK</small><b>{label(activeMap.state)}</b><p>{activeMap.boundary}</p>{activeMap.artifacts.length?<ul>{activeMap.artifacts.map(x=><li key={x}>{x}</li>)}</ul>:null}</section><section><small>VALIDATION / CONFLICT</small><p>{active.validation_rule}</p><code>{active.conflict_group||'NO CONFLICT GROUP'}</code></section><section><small>PROVENANCE</small><p>{active.provenance_note||'No additional provenance note.'}</p></section></>:<div className='r328-empty'><Database/><b>{error||'Loading source-exact canon…'}</b></div>}</aside>
  </div>
  <footer><ShieldCheck/><span><b>Authority boundary:</b> R328 is semantic source + crosswalk. R314 remains implementation reconciliation; R147 dispatches; R146 records history; R141/R142 close returned proof; R125 alone admits CanonState.</span></footer>
 </section>
}
