import {useEffect,useState} from 'react';
import {ScanSearch,ShieldCheck} from 'lucide-react';
import {readSourceSpatialReconstructionR228,R228_EVENT} from './world/sourceSpatialReconstructionR228.js';
import {renderSourceSpatialComputedFrameR230} from './world/sourceSpatialComputedFrameR230.js';
import {emitOperationR86} from './omegaOperationBusR86';
import {activeProjectIdR87,recordProjectOperationR87} from './omegaProjectContinuityR87';
export default function SourceSpatialComputedFrameR230(){
 const[reconstruction,setReconstruction]=useState<any>(()=>readSourceSpatialReconstructionR228());const[frame,setFrame]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{const sync=()=>{setReconstruction(readSourceSpatialReconstructionR228());setFrame(null)};window.addEventListener(R228_EVENT,sync as EventListener);window.addEventListener('storage',sync);return()=>{window.removeEventListener(R228_EVENT,sync as EventListener);window.removeEventListener('storage',sync)}},[]);
 if(reconstruction?.state!=='SOURCE_SPATIAL_RECONSTRUCTION_COMPUTED')return null;
 const render=async()=>{if(busy)return;setBusy(true);setError('');try{const next=await renderSourceSpatialComputedFrameR230({reconstruction,maxVisualPoints:1024});if(next.state!=='SOURCE_SPATIAL_COMPUTED_FRAME_RENDERED')throw new Error(`R230 held: ${(next.missing||[]).join(', ')}`);setFrame(next);const projectId=activeProjectIdR87();const event=await emitOperationR86({type:'SOURCE_SPATIAL_COMPUTED_FRAME_RENDERED',surface:'Living World',status:'PASS',detail:`R230 rendered exact-byte computed frame ${String(next.frameSha256).slice(0,12)} from R228 geometry ${String(next.r228GeometrySha256).slice(0,12)}`,payload:{revision:'R230',frameSha256:next.frameSha256,receiptSha256:next.receiptSha256,r228GeometrySha256:next.r228GeometrySha256,r228ReceiptSha256:next.r228ReceiptSha256,renderedComputedRealityFrame:true,computedRepresentationOnly:true,computedPhotorealRealityProved:false,spatialCalibrationProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div className='r206-world-mission' data-state={frame?'BOUND':'ASSEMBLED'} aria-label='R230 proof-bound computed spatial frame'><div className='r206-world-mission-icon'><ScanSearch/></div><div className='r206-world-mission-copy'><small>R228 → R230 · EXACT-BYTE COMPUTED FRAME</small><b>{frame?'COMPUTED REPRESENTATIONAL FRAME RENDERED':'SOURCE 3-D FRAME READY'}</b><span>{frame?`${frame.renderedPointCount}/${frame.sourcePointCount} source-derived points · frame ${String(frame.frameSha256).slice(0,12)}`:'Render the exact R228 geometry into deterministic SVG bytes and hash the bytes actually displayed.'}</span><em>{error||(frame?'Rendered computed frame is proven as bytes; physical calibration, solver validity and photoreal reality remain unproven.':'No empirical pixels or missing geometry are synthesized.')}</em>{frame&&<div dangerouslySetInnerHTML={{__html:frame.svgBytes}}/>}</div><div className='r206-world-mission-proof'><ShieldCheck/><span>exact R228 geometry bound</span><span>exact SVG bytes SHA-256</span><span>R122 authority unchanged</span><span>R125 Canon only</span><span>Photoreal unproven</span></div>{!frame&&<button onClick={render} disabled={busy}>{busy?'Rendering…':'Render proof-bound computed frame'}</button>}</div>;
}
