import {useState} from 'react';
import {Crosshair,ShieldCheck} from 'lucide-react';
import {readSourceSpatialReconstructionR228} from './world/sourceSpatialReconstructionR228.js';
import {validateSourceSpatialCalibrationR231,persistSourceSpatialCalibrationValidationR231} from './world/sourceSpatialCalibrationValidationR231.js';
import {emitOperationR86} from './omegaOperationBusR86';
import {activeProjectIdR87,recordProjectOperationR87} from './omegaProjectContinuityR87';

const CAMERA_EXAMPLE={sourceIdentity:'camera-calibration-id',imageWidthPx:1920,imageHeightPx:1080,intrinsics:{fx:1200,fy:1200,cx:960,cy:540},pose:{referenceFrame:'WGS84-ENU:R218',position:{x:0,y:0,z:0},orientation:{x:0,y:0,z:0,w:1}}};
const VALIDATION_EXAMPLE={sourceIdentity:'independent-survey-control',referenceFrame:'WGS84-ENU:R218',capturedOrAuthoritativeTime:'2026-09-08T19:00:00Z',provenance:'independent control points or calibration target observations',acquisitionMethod:'SURVEY_CONTROL',uncertainty:{pixel:0.5,worldM:0.02},correspondences:[{u:960,v:540,world:{x:0,y:0,z:10}},{u:1080,v:540,world:{x:1,y:0,z:10}},{u:960,v:660,world:{x:0,y:1,z:10}},{u:840,v:540,world:{x:-1,y:0,z:10}}]};

export default function SourceSpatialCalibrationValidationR231({frame}:{frame:any}){
 const[cameraText,setCameraText]=useState('');const[validationText,setValidationText]=useState('');const[result,setResult]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const run=async()=>{if(busy)return;setBusy(true);setError('');try{const reconstruction=readSourceSpatialReconstructionR228();if(reconstruction?.state!=='SOURCE_SPATIAL_RECONSTRUCTION_COMPUTED')throw new Error('R228 source geometry is not available');const camera=JSON.parse(cameraText);const validationEvidence=JSON.parse(validationText);const next=await validateSourceSpatialCalibrationR231({frame,reconstruction,camera,validationEvidence});if(next.state==='HELD_FOR_INDEPENDENT_CALIBRATION_EVIDENCE')throw new Error(`R231 held: ${(next.missing||[]).join(', ')}`);if(!persistSourceSpatialCalibrationValidationR231(next))throw new Error('R231 validation receipt persistence failed');setResult(next);const projectId=activeProjectIdR87();const event=await emitOperationR86({type:'SOURCE_SPATIAL_CALIBRATION_VALIDATED',surface:'Living World',status:next.independentCorrespondenceValidationPassed?'PASS':'HOLD',detail:`R231 independent reprojection ${next.independentCorrespondenceValidationPassed?'PASS':'FAIL'} · RMS ${next.rmsResidualPx}px · max ${next.maxResidualPx}px`,payload:{revision:'R231',receiptSha256:next.receiptSha256,r230FrameSha256:next.r230FrameSha256,r228GeometrySha256:next.r228GeometrySha256,validationEvidenceSha256:next.validationEvidenceSha256,independentCorrespondenceValidationPassed:next.independentCorrespondenceValidationPassed,rmsResidualPx:next.rmsResidualPx,p95ResidualPx:next.p95ResidualPx,maxResidualPx:next.maxResidualPx,sourceAuthenticationProved:false,spatialCalibrationProved:false,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 if(frame?.state!=='SOURCE_SPATIAL_COMPUTED_FRAME_RENDERED')return null;
 return <div className='r206-world-mission' data-state={result?.independentCorrespondenceValidationPassed?'BOUND':'ASSEMBLED'} aria-label='R231 independent spatial calibration validation'><div className='r206-world-mission-icon'><Crosshair/></div><div className='r206-world-mission-copy'><small>R230 → R231 · INDEPENDENT REPROJECTION RESIDUAL</small><b>{result?result.independentCorrespondenceValidationPassed?'INDEPENDENT CORRESPONDENCE CHECK PASSED':'CALIBRATION CHECK HELD':'CALIBRATION VALIDATION READY'}</b><span>{result?`RMS ${result.rmsResidualPx}px · p95 ${result.p95ResidualPx}px · max ${result.maxResidualPx}px · ${result.correspondenceCount} controls`:'Provide the exact R228-bound camera packet plus independent world↔image control observations. R231 evaluates them; it never derives controls from the R228 point cloud.'}</span><em>{error||(result?'This is a bounded independent correspondence check, not source authentication or proof of global physical registration.':'Use survey control, a calibration target, external registration, marker detection, or an independent sensor source.')}</em>{!result&&<><textarea aria-label='R231 exact camera evidence JSON' value={cameraText} onChange={e=>setCameraText(e.target.value)} placeholder={JSON.stringify(CAMERA_EXAMPLE)}/><textarea aria-label='R231 independent validation evidence JSON' value={validationText} onChange={e=>setValidationText(e.target.value)} placeholder={JSON.stringify(VALIDATION_EXAMPLE)}/></>}</div><div className='r206-world-mission-proof'><ShieldCheck/><span>exact R230/R228 lineage</span><span>independent controls only</span><span>RMS + p95 + max residual</span><span>R122 authority unchanged</span><span>Photoreal unproven</span></div>{!result&&<button onClick={run} disabled={busy||!cameraText.trim()||!validationText.trim()}>{busy?'Validating…':'Validate independent calibration'}</button>}</div>;
}
