import {useMemo,useState} from 'react';
import {Activity,ArrowRight,Calculator,ChevronRight,Database,GitBranch,Search,ShieldCheck,Sparkles,Waypoints} from 'lucide-react';
import {corpusState,evaluateCorpusModes} from './corpusRuntime';
import {compileSourceTraversal,R21_MODE_AUTHORITY,sourceBackedModeSummary,type SourceBackedModeResult} from './sourceBackedModeRuntimeR21';
import TransitionProofPanelR23 from './TransitionProofPanelR23';
import ModeExpressionCanvasR82 from './ModeExpressionCanvasR82';
import {compileModeExpressionR82} from './modeExpressionRuntimeR82';
import {ALL_MODES_BOUNDARY,CANON_AUTHORITY_STACK,evaluateCanonAuthorityStack} from './allModesAuthority';
import './sourceBackedModesR21.css';

type Props={record:any;address:number;onAddress:(address:number)=>void;onNavigate:(panel:string)=>void};
const fmt=(v:any,d=4)=>Number.isFinite(Number(v))?Number(v).toFixed(d):String(v??'—');
const statusLabel=(x:SourceBackedModeResult)=>x.state==='EXECUTED_EXACT'?'EXECUTED EXACT':x.state==='SOURCE_PACKET'?'SOURCE PACKET':x.state==='DERIVED_RUNTIME'?'DERIVED RUNTIME':'GATED';
const authorityRef=(id:number)=>`A${String(id).padStart(3,'0')}`;

export default function SourceBackedModesPanelR21({record,address,onAddress,onNavigate}:Props){
  const summary=useMemo(()=>sourceBackedModeSummary(record),[record]),catalog=useMemo(()=>evaluateCorpusModes(record),[record]),authorities=useMemo(()=>evaluateCanonAuthorityStack(record),[record]),route=useMemo(()=>compileSourceTraversal(address,72),[address]),[query,setQuery]=useState(''),[showCatalog,setShowCatalog]=useState(false),[showAuthorities,setShowAuthorities]=useState(true),[selectedModeId,setSelectedModeId]=useState(()=>{try{return localStorage.getItem('omega.r83.selectedModeRef')||localStorage.getItem('omega.r82.selectedModeId')||'M001'}catch{return'M001'}});
  const q=query.trim().toLowerCase(),catalogRows=catalog.results.filter((x:any)=>!q||`${x.name} ${x.category} ${x.operator} ${x.algebra} ${x.calculus}`.toLowerCase().includes(q)),authorityRows=authorities.filter(x=>!q||`${x.name} ${x.group} ${x.basis} ${x.state}`.toLowerCase().includes(q));
  const implementedCount=summary.rows.length,registryOnlyCount=Math.max(0,summary.catalogCount-implementedCount);
  const selectedCatalog=(catalog.results as any[]).find(x=>x.id===selectedModeId)||null,selectedExecution=summary.rows.find(x=>x.id===selectedModeId)||null,selectedAuthority=authorities.find(x=>authorityRef(x.id)===selectedModeId)||null;
  const authorityCatalog=selectedAuthority?{id:authorityRef(selectedAuthority.id),name:selectedAuthority.name,category:selectedAuthority.group,operator:'DERIVED CANON / CALCULUS AUTHORITY LENS',purpose:selectedAuthority.basis,classification:selectedAuthority.classification}:null;
  const authorityExecution=selectedAuthority?{id:authorityRef(selectedAuthority.id),name:selectedAuthority.name,state:'DERIVED_RUNTIME',value:selectedAuthority.activation,formula:'Derived governance activation over canonical packet',source:'ALL MODES repaired authority stack',detail:selectedAuthority.basis,authorityLens:true}:null;
  const expression=useMemo(()=>{const base=compileModeExpressionR82(selectedCatalog||authorityCatalog,selectedExecution||authorityExecution,record);return selectedAuthority?{...base,executed:false,gated:false,metadataOnly:true,detail:`${selectedAuthority.group} · ${selectedAuthority.state} · ${selectedAuthority.basis}`,boundary:'This is a higher-order canon/calculus governance lens over the same canonical packet. Its activation is not a source-mode execution and does not create external evidence.'}:base},[selectedCatalog,selectedExecution,authorityCatalog,authorityExecution,record,selectedAuthority]);
  const activeMode=summary.rows.find(x=>x.id===selectedModeId&&x.state!=='GATED_MISSING_INPUTS')||summary.rows.find(x=>x.id==='M001')!;
  const modeTrace=useMemo(()=>route.path.map(x=>{const row=sourceBackedModeSummary(corpusState(x.address)).rows.find(m=>m.id===activeMode.id);return{address:x.address,stateId:x.stateId,value:row?.value??null,state:row?.state??'GATED_MISSING_INPUTS',decision:x.decision,dewey:x.dewey}}),[route,activeMode.id]);
  const numericTrace=modeTrace.map(x=>Number(x.value)).filter(Number.isFinite),traceMin=numericTrace.length?Math.min(...numericTrace):0,traceMax=numericTrace.length?Math.max(...numericTrace):0,traceSpan=Math.max(1e-9,traceMax-traceMin),hasNumericTrace=numericTrace.length===modeTrace.length&&numericTrace.length>0;
  const points=route.path.map((x,i)=>{const px=18+(i/Math.max(1,route.path.length-1))*964,raw=Number(modeTrace[i]?.value),score=hasNumericTrace?((raw-traceMin)/traceSpan):Math.max(0,Math.min(1,x.dewey/(1+x.dewey)));return{x,px,py:220-score*168}}),line=points.map(p=>`${p.px.toFixed(1)},${p.py.toFixed(1)}`).join(' ');
  const goStep=(n:number)=>{const p=route.path[Math.max(0,Math.min(route.path.length-1,n))];if(p)onAddress(p.address)};
  const selectMode=(id:string)=>{setSelectedModeId(id);try{localStorage.setItem('omega.r83.selectedModeRef',id);if(id.startsWith('M'))localStorage.setItem('omega.r82.selectedModeId',id)}catch{}};
  const openModeInstrument=()=>{try{localStorage.setItem('omega.r65.visual.lens','MODE');localStorage.setItem('omega.r83.selectedModeRef',selectedModeId)}catch{}onNavigate('Visual Instrument')};
  const allModeRefs=[...(catalog.results as any[]).map(x=>x.id),...CANON_AUTHORITY_STACK.map(x=>authorityRef(x.id))],modeIndex=Math.max(0,allModeRefs.indexOf(selectedModeId)),stepMode=(delta:number)=>{if(!allModeRefs.length)return;const next=(modeIndex+delta+allModeRefs.length)%allModeRefs.length;selectMode(allModeRefs[next])};
  return <section className='special-app sbm21-app'>
    <header className='special-head'><div><span>SOURCE-BACKED CALCULUS · CANONICAL TRANSITION AUTHORITY</span><h2>Modes + Applied Calculus</h2></div><strong>{summary.appliedCount} APPLIED · {summary.gatedCount} GATED · {implementedCount} IMPLEMENTED · {CANON_AUTHORITY_STACK.length} CANON LENSES</strong></header>
    <div className='sbm21-truth'><ShieldCheck/><div><b>179 catalog entries are loaded as source metadata, not automatically called “executed.” {CANON_AUTHORITY_STACK.length} higher-order canon/calculus authorities are preserved separately.</b><span>Only {implementedCount} source modes currently have hosted evaluation contracts: {summary.exactCount} exact operators execute from current packet inputs · {summary.packetCount} source/derived runtime channels are exposed directly · {summary.gatedCount} implemented formulas remain gated · {registryOnlyCount} catalog entries are registry-only. The {CANON_AUTHORITY_STACK.length} canon/calculus authorities remain derived governance lenses over the same packet and are not double-counted as source executors.</span></div></div>
    <div className='sbm21-kpis'><div><span>STATE</span><b>{record.stateId}</b><small>D{record.coordinates.d+1} · P{record.coordinates.p+1} · R{record.coordinates.r+1} · L{record.coordinates.l+1}</small></div><div><span>DEWEY S</span><b>{fmt(summary.executed.find(x=>x.id==='M001')?.value)}</b><small>(CΩ·Φ)/(q+Λ+ε)</small></div><div><span>MODE 188</span><b>{fmt(summary.executed.find(x=>x.id==='M002')?.value)}</b><small>{String(record.metrics.mode188)}</small></div><div><span>MODE COVERAGE</span><b>{implementedCount}/{summary.catalogCount}</b><small>{registryOnlyCount} awaiting donor contract restoration</small></div><div><span>CANON LENSES</span><b>{CANON_AUTHORITY_STACK.length}</b><small>{ALL_MODES_BOUNDARY.countingRule}</small></div></div>
    <section className='sbm21-expression'><header><div><Sparkles/><span><b>SELECTED {selectedAuthority?'CANON AUTHORITY':'MODE'} EXPRESSION · {expression.id}</b><small>{expression.family} · {expression.signature} · {expression.motion}</small></span></div><div className='sbm21-expression-controls'><button onClick={()=>stepMode(-1)} aria-label='Previous mode or authority'>←</button><label><span>MODE / LENS</span><select value={selectedModeId} onChange={e=>selectMode(e.target.value)} aria-label='Select any OMEGA source mode or canon authority'><optgroup label={`SOURCE MODE CATALOG · ${catalog.count}`}>{(catalog.results as any[]).map(x=>{const executed=summary.rows.find(m=>m.id===x.id);return <option key={x.id} value={x.id}>{x.id} · {x.name} · {executed?(executed.state==='GATED_MISSING_INPUTS'?'GATED':'SOURCE'):'REGISTRY'}</option>})}</optgroup><optgroup label={`CANON / CALCULUS AUTHORITY LENSES · ${CANON_AUTHORITY_STACK.length}`}>{authorities.map(x=><option key={authorityRef(x.id)} value={authorityRef(x.id)}>{authorityRef(x.id)} · {x.name} · {x.state}</option>)}</optgroup></select></label><button onClick={()=>stepMode(1)} aria-label='Next mode or authority'>→</button><button onClick={openModeInstrument}>Open full Visual Instrument <ArrowRight/></button></div></header><ModeExpressionCanvasR82 expression={expression} address={address} value={(selectedExecution||authorityExecution)?.value}/><div className='sbm21-expression-boundary'><ShieldCheck/><span>{expression.boundary}</span></div></section>
    <TransitionProofPanelR23 address={address} onAddress={onAddress}/>
    <section className='sbm21-route'><header><div><Waypoints/><span>{selectedAuthority?'UNDERLYING SOURCE TRAVERSAL':'ACTUAL ADMITTED TRAVERSAL'} · {activeMode.id}</span><b>{route.path.length} source states</b></div><div className='sbm21-route-actions'><button onClick={()=>onAddress(record.autoPing.previous)}>Previous</button><button onClick={()=>onAddress(record.autoPing.dataNext)}>Admitted next <ArrowRight/></button><button onClick={()=>goStep(12)}>Follow 12</button><button onClick={()=>onNavigate('Visual Instrument')}>Visual Instrument</button><button onClick={()=>onNavigate('Traversal')}>Traversal</button></div></header><svg viewBox='0 0 1000 250' role='img' aria-label={`Canonical source traversal traced by ${activeMode.name}`}><line x1='18' y1='220' x2='982' y2='220' className='sbm21-axis'/><polyline points={line} className='sbm21-route-line'/>{points.map((p,i)=><g key={`${p.x.address}-${i}`} className={`sbm21-node ${p.x.decision.toLowerCase()}`} onClick={()=>onAddress(p.x.address)}><circle cx={p.px} cy={p.py} r={i===0?7:4.5}/>{i%8===0&&<text x={p.px} y={Math.max(14,p.py-10)} textAnchor='middle'>{p.x.stateId}</text>}</g>)}</svg><footer><span>{hasNumericTrace?`vertical = ${activeMode.id} normalized across this admitted route`:'vertical = Dewey route geometry; active mode is categorical/source-bound'}</span><span>route = exact autoPing.dataNext sequence</span><b>{route.closed?'LOOP/CLOSURE DETECTED':'OPEN TRAVERSAL'}</b></footer><div className='special-boundary' data-active-mode={activeMode.id}><ShieldCheck/><span><b>{activeMode.id} · {activeMode.name} · {statusLabel(activeMode)}</b> · {activeMode.formula} · current {String(activeMode.value??'—')} · source {activeMode.source}. Each plotted sample is re-evaluated from that exact canonical route packet when the selected mode is numeric; gated formulas cannot be selected for trace execution.</span></div></section>
    <div className='sbm21-mode-columns'><section><header><Calculator/><b>EXECUTED / SOURCE-BOUND OPERATORS</b><span>{summary.appliedCount}</span></header><div className='sbm21-mode-list'>{summary.rows.filter(x=>x.state!=='GATED_MISSING_INPUTS').map(x=><article key={x.id} className={`${x.state.toLowerCase()} ${x.id===activeMode.id?'selected':''}`}><code>{x.id}</code><div><b>{x.name}</b><small>{x.formula}</small><em>{x.source}</em><p>{x.detail}</p><button onClick={()=>selectMode(x.id)} aria-pressed={x.id===activeMode.id}>Express visually + Trace this mode</button></div><strong>{statusLabel(x)}<span>{x.value===null?'—':String(x.value)}</span></strong></article>)}</div></section><section><header><ShieldCheck/><b>FORMULAS HELD FOR MISSING INPUTS</b><span>{summary.gatedCount}</span></header><div className='sbm21-mode-list gated'>{summary.gated.map(x=><article key={x.id} className={x.id===selectedModeId?'selected':''}><code>{x.id}</code><div><b>{x.name}</b><small>{x.formula}</small><em>{x.source}</em><p>Missing authoritative inputs: {x.missing.join(', ')}</p><button onClick={()=>selectMode(x.id)} aria-pressed={x.id===selectedModeId}>Express gated mode</button></div><strong>GATED</strong></article>)}</div></section></div>
    <section className='sbm21-authorities'><header><div><Sparkles/><b>{CANON_AUTHORITY_STACK.length} CANON / CALCULUS AUTHORITY LENSES</b><span>Full Overall Canon · Deep Mother · High Father · Seven-Star · Alpha · laws · governance · runtime</span></div><button onClick={()=>setShowAuthorities(v=>!v)}>{showAuthorities?'Hide':'Inspect'} authorities</button></header>{showAuthorities&&<div className='sbm21-authority-grid'>{authorityRows.map(x=>{const ref=authorityRef(x.id);return <button key={ref} className={selectedModeId===ref?'selected':''} onClick={()=>selectMode(ref)} aria-pressed={selectedModeId===ref}><code>{ref}</code><span><b>{x.name}</b><small>{x.group} · {x.basis}</small></span><strong data-state={x.state}>{x.state}<small>{fmt(x.activation,3)}</small></strong></button>})}</div>}<footer><ShieldCheck/>{ALL_MODES_BOUNDARY.countingRule} {ALL_MODES_BOUNDARY.truthBoundary}</footer></section>
    <section className='sbm21-catalog'><header><div><Database/><b>{summary.catalogCount}-SOURCE MODE REGISTRY</b><span>{implementedCount} hosted evaluation contracts · {registryOnlyCount} registry-only entries</span></div><div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search mode source registry…'/></label><button onClick={()=>setShowCatalog(v=>!v)}>{showCatalog?'Hide':'Inspect'} catalog</button></div></header>{showCatalog&&<div className='sbm21-catalog-grid'>{catalogRows.map((x:any)=><details key={x.id}><summary><code>{x.id}</code><span><b>{x.name}</b><small>{x.category}</small></span><strong>REGISTRY</strong><ChevronRight/></summary><div><p><b>Operator</b> {x.operator||'—'}</p><p><b>Algebra</b> {x.algebra||'—'}</p><p><b>Calculus</b> {x.calculus||'—'}</p><p><b>Proof requirement</b> {x.proof||'—'}</p><p><b>Ledger</b> {x.ledger||'—'}</p><em>Legacy semantic affinity score/gate is intentionally not displayed as execution. Registry metadata is not an executable hosted operator until a source-backed evaluation contract is bound.</em><button className='sbm21-express-catalog' onClick={()=>selectMode(x.id)}>Express this catalog mode visually</button></div></details>)}</div>}</section>
    <div className='sbm21-actions'><button onClick={()=>onNavigate('Relativity')}><GitBranch/>Dimensional Relativity</button><button onClick={()=>onNavigate('Evidence & Proof')}><ShieldCheck/>Evidence & Proof</button><button onClick={()=>onNavigate('System Atlas')}><Database/>Software Atlas</button><button onClick={()=>onNavigate('Control Matrix')}><Activity/>Control Matrix</button></div>
    <div className='special-boundary'><ShieldCheck/>{R21_MODE_AUTHORITY.boundary} {route.boundary}</div>
  </section>
}
