import {useState} from 'react';
import {Gauge,ShieldCheck} from 'lucide-react';
import {evaluateSourceSpatialCalibrationSufficiencyR234,persistSourceSpatialCalibrationSufficiencyR234} from './world/sourceSpatialCalibrationSufficiencyR234.js';
import {emitOperationR86} from './omegaOperationBusR86';
import {activeProjectIdR87,recordProjectOperationR87} from './omegaProjectContinuityR87';
export default function SourceSpatialCalibrationSufficiencyR234({validation,camera,validationEvidence}:{validation:any,camera:any,validationEvidence:any}){
 const[result,setResult]=useState<any>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const run=async()=>{if(busy)return;setBusy(true);setError('');try{const next=await evaluateSourceSpatialCalibrationSufficiencyR234({validation,camera,validationEvidence});if(next.state==='HELD_FOR_CALIBRATION_SUFFICIENCY_EVIDENCE')throw new Error(`R234 held: ${(next.missing||[]).join(', ')}`);if(!persistSourceSpatialCalibrationSufficiencyR234(next))throw new Error('R234 sufficiency receipt persistence failed');setResult(next);const projectId=activeProjectIdR87();const event=await emitOperationR86({type:'SOURCE_SPATIAL_CALIBRATION_SUFFICIENCY_EVALUATED',surface:'Living World',status:next.calibrationSufficiencyEnvelopePassed?'PASS':'HOLD',detail:`R234 ${next.calibrationSufficiencyEnvelopePassed?'PASS':'HOLD'} · image hull ${(next.imageHullAreaRatio*100).toFixed(2)}% · normalized RMS ${next.normalizedRms}`,payload:{revision:'R234',receiptSha256:next.receiptSha256,r232ReceiptSha256:next.r232ReceiptSha256,distributionPassed:next.distributionPassed,uncertaintyResidualPassed:next.uncertaintyResidualPassed,calibrationSufficiencyEnvelopePassed:next.calibrationSufficiencyEnvelopePassed,sourceAuthenticationProved:false,spatialCalibrationProved:false,computedPhotorealRealityProved:false,solverValidityProved:false,nativeExecutionClaimed:false,pcOnlineClaimed:false,federationClosureProved:false,canonicalMutation:false}});await recordProjectOperationR87(projectId,event)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 if(validation?.state!=='INDEPENDENT_SPATIAL_CALIBRATION_VALIDATION_PASSED')return null;
 return <div className='r206-world-mission' data-state={result?.calibrationSufficiencyEnvelopePassed?'BOUND':'ASSEMBLED'} aria-label='R234 calibration sufficiency envelope'><div className='r206-world-mission-icon'><Gauge/></div><div className='r206-world-mission-copy'><small>R232 → R234 · CALIBRATION SUFFICIENCY</small><b>{result?result.calibrationSufficiencyEnvelopePassed?'CONTROL GEOMETRY SUFFICIENT':'CALIBRATION SUFFICIENCY HELD':'SUFFICIENCY CHECK READY'}</b><span>{result?`Hull ${(result.imageHullAreaRatio*100).toFixed(2)}% · spans ${(result.uSpanRatio*100).toFixed(1)}% × ${(result.vSpanRatio*100).toFixed(1)}% · world non-collinearity ${result.worldNonCollinearityScore} · normalized RMS ${result.normalizedRms}`:'Check that the independent controls are numerous and spatially distributed enough to make the low R232 reprojection residual meaningful.'}</span><em>{error||(result?'A passing envelope is stronger numerical sufficiency evidence, not source authentication or proof of physical calibration.':'Requires at least six controls, image-plane coverage, non-collinear world geometry, and uncertainty-bounded residuals.')}</em></div><div className='r206-world-mission-proof'><ShieldCheck/><span>exact R232 receipt</span><span>control distribution</span><span>uncertainty-normalized RMS</span><span>R122/R185 unchanged</span><span>Photoreal unproven</span></div>{!result&&<button onClick={run} disabled={busy}>{busy?'Evaluating…':'Evaluate calibration sufficiency'}</button>}</div>;
}
