import {useEffect,useMemo,useState} from 'react';
import {Archive,BookOpen,GitBranch,Network,Save,ShieldCheck,TerminalSquare} from 'lucide-react';
import {api,localState} from './platformAdapter';
import {corpusState,decodeAddress,evaluateCorpusModes,validateCorpusPack} from './corpusRuntime';
import {unifiedFromRecord,validateUnifiedMath} from './unifiedCalculus';

type Tab='ARCHIVE'|'GOVERNANCE'|'CONSOLIDATION'|'INSTRUCTIONS'|'HYBRID'|'QUALITY'|'SYSTEM_ATLAS';
type Snap={id:string;at:number;address:number;stateId:number;decision:string;continuity:number;plasticity:number;contradiction:number;burden:number;note:string};
const TABS:Tab[]=['ARCHIVE','GOVERNANCE','CONSOLIDATION','INSTRUCTIONS','HYBRID','QUALITY','SYSTEM_ATLAS'];
const key='omega.v6.sovereignOps.snapshots';
const fmt=(n:number,d=4)=>Number.isFinite(n)?n.toFixed(d):'—';
export default function SovereignOperationsPanel({address,onCommit}:{address:number;onCommit:(n:number)=>void}){
 const[tab,setTab]=useState<Tab>('ARCHIVE'),[note,setNote]=useState(''),[snaps,setSnaps]=useState<Snap[]>(()=>localState.read(key,[])),[hybrid,setHybrid]=useState<any>(null),[quality,setQuality]=useState<any>(null);
 const record=useMemo(()=>corpusState(address),[address]),coords=useMemo(()=>decodeAddress(address),[address]),modes=useMemo(()=>evaluateCorpusModes(record),[record]),u=useMemo(()=>unifiedFromRecord(record),[record]);
 useEffect(()=>{localState.write(key,snaps)},[snaps]);
 const capture=()=>setSnaps(x=>[{id:`snap_${Date.now().toString(36)}`,at:Date.now(),address,stateId:record.stateId,decision:record.metrics.decision,continuity:record.metrics.continuity,plasticity:record.metrics.plasticity,contradiction:record.metrics.contradiction,burden:record.metrics.burden,note:note.trim()},...x].slice(0,120));
 const runHybrid=async()=>{try{const r=await api.get<any>('/api/hybrid/status');setHybrid(r.data)}catch(e:any){setHybrid({state:'DEVICE_PROOF_REQUIRED',error:e.message})}};
 const runQuality=async()=>{const p=validateCorpusPack(),m=validateUnifiedMath(record);let worker:any={};try{const [h,s,r]=await Promise.all([api.get<any>('/api/health'),api.get<any>('/api/status'),api.get<any>('/api/restoration')]);worker={health:h.data,status:s.data,restoration:r.data}}catch(e:any){worker={error:e.message}}setQuality({at:Date.now(),sourcePack:p,math:m,worker,pass:p.passed&&m.passed})};
 const neighbors=useMemo(()=>{const out:number[]=[];for(const dd of [-1,1])out.push((((coords.d+dd+12)%12)*1728)+(coords.p*144)+(coords.r*12)+coords.l);for(const dp of [-1,1])out.push(coords.d*1728+(((coords.p+dp+12)%12)*144)+(coords.r*12)+coords.l);for(const dr of [-1,1])out.push(coords.d*1728+coords.p*144+(((coords.r+dr+12)%12)*12)+coords.l);for(const dl of [-1,1])out.push(coords.d*1728+coords.p*144+coords.r*12+((coords.l+dl+12)%12));return out},[coords]);
 return <section className='panel'>
  <div className='section-head'><div><p className='overline'>SOVEREIGN OPERATIONS · PORTABLE SOURCE</p><h2>Archive · Governance · Consolidation · Mission Control · Quality · Atlas</h2></div><span className='pill ok'>STATE {record.stateId}</span></div>
  <div className='rel-tabs'>{TABS.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t.replace('_',' ')}</button>)}</div>
  {tab==='ARCHIVE'&&<><div className='gate-grid'><div><span>Local archive</span><b>{snaps.length} snapshots</b><small>Portable browser ledger; Drive release authority is not mutated.</small></div><div><span>Current state</span><b>{record.stateId}</b><small>{record.metrics.decision}</small></div></div><div className='input-row'><input value={note} onChange={e=>setNote(e.target.value)} placeholder='Snapshot note'/><button className='gold' onClick={capture}><Save size={14}/> Capture</button></div><div className='table-list'>{snaps.slice(0,40).map(s=><button key={s.id} className='table-button' onClick={()=>onCommit(s.address)}><b>{new Date(s.at).toLocaleString()} · state {s.stateId}</b><span>{s.decision} · {s.note||'no note'}</span><small>CΩ {fmt(s.continuity)} · Φ {fmt(s.plasticity)} · q {fmt(s.contradiction)} · Λ {fmt(s.burden)}</small></button>)}</div></>}
  {tab==='GOVERNANCE'&&<><div className='channel-grid'><div className='metric'><span>Continuity CΩ</span><b>{fmt(record.metrics.continuity)}</b></div><div className='metric'><span>Plasticity Φ</span><b>{fmt(record.metrics.plasticity)}</b></div><div className='metric'><span>Contradiction q</span><b>{fmt(record.metrics.contradiction)}</b></div><div className='metric'><span>Burden Λ</span><b>{fmt(record.metrics.burden)}</b></div></div><div className='gate-grid'><div><span>Governance decision</span><b>{record.metrics.decision}</b><small>STAY/TURN/ESCALATE from the current source packet.</small></div><div><span>Weakest mode</span><b>{modes.weakest.name}</b><small>{modes.weakest.gate} · {fmt(modes.weakest.score)}</small></div><div><span>Common kernel</span><b>{fmt(u.commonKernel,6)}</b><small>No new physical primitive introduced.</small></div></div></>}
  {tab==='CONSOLIDATION'&&<><div className='answer'><b>Consolidation snapshot</b><p>One state → one packet → one durable local scar ledger. Capture before branch or route changes; compare against the previous snapshot before accepting a new state.</p></div><button className='gold' onClick={capture}><GitBranch size={14}/> Consolidate current packet</button><div className='table-list'>{snaps.slice(0,8).map(s=><div key={s.id}><b>state {s.stateId} · {s.decision}</b><span>{s.note||'consolidated packet'}</span><small>{new Date(s.at).toLocaleString()}</small></div>)}</div></>}
  {tab==='INSTRUCTIONS'&&<div className='table-list'><div><b>1 · Drive authority first</b><span>Read LATEST_OMEGA_UPDATE.json before QA or promotion.</span><small>B015 R1 · immutable-core preflight · transactional rollback.</small></div><div><b>2 · Lineage before write</b><span>Candidate branch must be based on current main. Stale branches are donor evidence only.</span></div><div><b>3 · QA before promotion</b><span>Worker syntax · 30-route regression · restore/surpass invariants · Vite build · Wrangler dry-run · portability locks.</span></div><div><b>4 · Truth gates</b><span>Hybrid requires device proof. Earth stays external-degraded until bound. Provider absence is bounded failure.</span></div><div><b>5 · Public truth</b><span>Source/build success never equals LIVE PASS without direct workers.dev verification.</span></div></div>}
  {tab==='HYBRID'&&<><div className='answer'><b>Hybrid Mission Control</b><p>Native PC/screen/device execution is never simulated. This panel reads the Worker truth endpoint and exposes the exact device-proof state.</p></div><button className='gold' onClick={runHybrid}><TerminalSquare size={14}/> Check Hybrid proof</button>{hybrid&&<pre className='code-block'>{JSON.stringify(hybrid,null,2)}</pre>}</>}
  {tab==='QUALITY'&&<><div className='answer'><b>Universal Quality Compiler</b><p>Validates the embedded 20,736-state pack and unified calculus, then queries Worker health/status/restoration without converting source success into LIVE PASS.</p></div><button className='gold' onClick={runQuality}><ShieldCheck size={14}/> Run quality gate</button>{quality&&<pre className='code-block'>{JSON.stringify(quality,null,2)}</pre>}</>}
  {tab==='SYSTEM_ATLAS'&&<><div className='gate-grid'><div><span>Address</span><b>D{coords.d+1} P{coords.p+1} R{coords.r+1} L{coords.l+1}</b><small>Representational 12×12×12×12 hierarchy.</small></div><div><span>Auto-Ping</span><b>{record.autoPing.dataNext+1}</b><small>Mode188 +188: {record.autoPing.mode188Plus+1}</small></div></div><div className='table-list'>{neighbors.map(n=>{const r=corpusState(n);return <button className='table-button' key={n} onClick={()=>onCommit(n)}><b>state {r.stateId}</b><span>{r.metrics.decision}</span><small>CΩ {fmt(r.metrics.continuity)} · Φ {fmt(r.metrics.plasticity)} · q {fmt(r.metrics.contradiction)} · Λ {fmt(r.metrics.burden)}</small></button>})}</div><div className='boundary'><Network size={16}/> System Atlas traversal is source-derived and portable; it does not claim physical dimensionality.</div></>}
 </section>
}
