import {useMemo,useState} from 'react';
import {Box,Download,Grid3X3,Layers3,Search,ShieldCheck,Waypoints} from 'lucide-react';
import {EXPRESSION_PLANES,FAMILIES,GRID_CELLS,MASTER_MENUS,PHASE_COUNT,STREAM_COUNT,SUBSYSTEM_COUNT,SYSTEM_ATLAS_ID,SYSTEM_INVARIANT,atlasCell,expressionPlanesForFamily,systemAtlasReceipt} from './systemAtlasRuntime';
import {OPERATIONAL_CAPABILITIES,effectiveCapabilityReality,operationalCapabilityAudit} from './operationalCapabilityRuntimeR45';
import {CanonicalPacketTruthPlotR93} from './TruthVisualsR93';
import SomaAudioEngine from './SomaAudioEngine';
import ExtremeRestorationR46 from './ExtremeRestorationR46';
import OmegaSystemInventoryR83 from './OmegaSystemInventoryR83';
import {MASTER_SYSTEMS_R83} from './softwareMasterLedgerR83';
import './systemAtlas.css';
import './systemCapabilityR13.css';
import './systemAtlasDepthR38_4.css';
import './convergenceR45.css';

type Props={record:any;onNavigate:(name:string)=>void;control?:boolean};
const dl=(name:string,x:any)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
const nonExecutable=new Set(['DONOR_ONLY','NATIVE_TARGET','RESTORATION_DEBT']);

export default function SystemAtlasControl({record,onNavigate,control=false}:Props){
 const[q,setQ]=useState(''),[family,setFamily]=useState(()=>{try{const id=localStorage.getItem('omega.r83.familyFocus');const i=FAMILIES.findIndex(x=>x.id===id);return i>=0?i:0}catch{return 0}}),[subsystem,setSubsystem]=useState(0),[phase,setPhase]=useState(0),[stream,setStream]=useState(0);
 const rows=useMemo(()=>FAMILIES.filter(x=>(x.id+' '+x.name+' '+x.invariant+' '+x.role+' '+x.status+' '+x.statusNote+' '+x.inventoryPurpose).toLowerCase().includes(q.toLowerCase())),[q]);
 const cell=atlasCell(family,subsystem,phase,stream),receipt=systemAtlasReceipt(record.stateId),expressions=expressionPlanesForFamily(cell.family.id),inlineLocal=cell.family.id==='S17'&&cell.family.status==='LOCAL_ACTIVE',canOpen=!nonExecutable.has(cell.family.status)&&cell.family.target!=='System Atlas';
 const counts=useMemo(()=>Object.fromEntries([...new Set(FAMILIES.map(x=>x.status))].map(s=>[s,FAMILIES.filter(x=>x.status===s).length])),[]),audit=useMemo(()=>operationalCapabilityAudit(),[]);
 const activeAddress=Number.isFinite(Number(record?.address))?Number(record.address):Math.max(0,Number(record?.stateId||1)-1);
 const restoreFocus=(()=>{try{const familyId=localStorage.getItem('omega.r83.familyFocus')||'';const systemId=localStorage.getItem('omega.r83.systemFocus')||'';const row=MASTER_SYSTEMS_R83.find(x=>x.id===systemId);return [familyId,row?.id,row?.artifact,row?.family,row?.role].filter(Boolean).join(' ')}catch{return''}})();
 void GRID_CELLS;void PHASE_COUNT;void STREAM_COUNT;void SUBSYSTEM_COUNT;
 return <section className='special-app system-atlas-r1 system-atlas-r13 system-atlas-r38'>
  <header className='special-head'><div><span>V24 INVENTORY-ALIGNED SOFTWARE UNIVERSE · R45 EXECUTION + CAPABILITY TRUTH · R46 RESTORATION OVERLAY</span><h2>{control?'System Control Matrix':'System Atlas'}</h2></div><div className='atlas-r1-status'><b>{FAMILIES.length} INVENTORY FAMILIES · {audit.total} APPLICATION SURFACES · {EXPRESSION_PLANES.length} EXPRESSION PLANES</b><small>{SYSTEM_ATLAS_ID} · STATE {record.stateId} · {record.metrics.decision} · registration ≠ execution</small></div></header>
  <div className='atlas-r1-invariant'><ShieldCheck/><b>{SYSTEM_INVARIANT}</b><span>One authoritative packet can have multiple lawful expressions, but a donor name, native target, or restoration plan is never displayed as a live executable capability.</span></div>
  <section className='atlas-r38-stage' aria-label='Active packet and System Atlas truth context'>
   <div className='atlas-r38-field'><CanonicalPacketTruthPlotR93 record={record} title={control?'System Control · canonical packet':'System Atlas · canonical packet'}/></div>
   <aside className='atlas-r38-context'>
    <article><span>Active packet</span><b>STATE {record.stateId}</b><small>CΩ {Number(record.metrics.continuity).toFixed(3)} · Φ {Number(record.metrics.plasticity).toFixed(3)} · q {Number(record.metrics.contradiction).toFixed(3)} · Λ {Number(record.metrics.burden).toFixed(3)}</small></article>
    <article><span>Selected family</span><b>{cell.family.name}</b><small>{cell.family.status} · {cell.family.statusNote}</small></article>
    <article><span>Execution boundary</span><b>{canOpen||inlineLocal?'EXECUTABLE HERE':'PROOF / RESTORE REQUIRED'}</b><small>Registered capability never implies executable capability.</small></article>
    <article><span>Expression relation</span><b>{expressions.length} lawful views</b><small>Every expression inherits its own execution boundary.</small></article>
   </aside>
  </section>
  <div className='atlas-r1-kpis'><article><b>{counts.WEB_ACTIVE||0}</b><span>WEB ACTIVE</span></article><article><b>{counts.SOURCE_ACTIVE||0}</b><span>SOURCE ACTIVE</span></article><article><b>{counts.LOCAL_ACTIVE||0}</b><span>LOCAL ACTIVE</span></article><article><b>{counts.EVIDENCE_GATED||0}</b><span>EVIDENCE GATED</span></article><article><b>{counts.DEVICE_GATED||0}</b><span>DEVICE GATED</span></article><article><b>{(counts.DONOR_ONLY||0)+(counts.NATIVE_TARGET||0)+(counts.RESTORATION_DEBT||0)}</b><span>HISTORICAL V24 DEBT/TARGET</span></article></div>
  <OmegaSystemInventoryR83 onNavigate={onNavigate}/>
    <section className='r45-capability-audit' aria-label='R45 operational capability audit'><article><b>{audit.total}</b><span>APPLICATION SURFACES</span></article><article><b>{audit.routable}</b><span>ROUTABLE</span></article><article><b>{audit.source}</b><span>SOURCE / RUNTIME</span></article><article><b>{audit.local}</b><span>LOCAL ACTIVE</span></article><article><b>{audit.gated}</b><span>TRUTH GATED</span></article><article><b>{audit.pass?'PASS':'CHECK'}</b><span>ROUTE CONTRACT</span></article></section>
  <ExtremeRestorationR46 record={record} address={activeAddress} onNavigate={onNavigate} focus={restoreFocus}/>
  {inlineLocal&&<SomaAudioEngine record={record}/>} 
  <section className='capability-expression-r13' aria-label='OMEGA expression planes'><header><div><span>ONE STATE · MANY LAWFUL EXPRESSIONS</span><b>Expression targets inherit their own execution boundary</b></div><small>No expression plane creates a missing backend.</small></header><div>{EXPRESSION_PLANES.map(p=><button key={p.id} onClick={()=>onNavigate(p.target)} title={p.boundary}><code>{p.id}</code><span><b>{p.label}</b><small>{p.purpose}</small></span><em>{p.target}</em></button>)}</div></section>
  <section className='atlas-r1-menus'><header><Waypoints/><div><span>R45 EXECUTION CONTRACT</span><b>Every application surface has route, family, performance, persistence and truth-boundary authority</b></div></header><div className='r45-capability-table'>{OPERATIONAL_CAPABILITIES.map(c=><button key={c.name} data-routable={c.routable?'true':'false'} data-reality={effectiveCapabilityReality(c.name)} onClick={()=>onNavigate(c.routable?c.name:c.degradeTo)} title={`${c.input} · ${c.proof}`}><b>{c.name}</b><small>{c.familyId} · {c.performance} · {c.persistence} · {effectiveCapabilityReality(c.name)}</small></button>)}</div><div className='r45-boundary'><ShieldCheck/><span>{audit.boundary} Unroutable surfaces: {audit.unroutable.length?audit.unroutable.join(', '):'none'}.</span></div></section>
  <div className='atlas-r1-layout'><section><div className='atlas-r1-search'><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Find family / status / invariant / role…'/><span>{rows.length}/24</span></div><div className='atlas-r1-families'>{rows.map(f=><button key={f.id} data-family-status={f.status} className={FAMILIES[family].id===f.id?'active':''} onClick={()=>setFamily(FAMILIES.indexOf(f))}><code>{f.id}</code><span><b>{f.name}</b><small>{f.invariant}</small></span><em>{f.status}</em></button>)}</div></section><section className='atlas-r1-cell'><header><Grid3X3/><div><span>SELECTED SOFTWARE CELL</span><b>{cell.artifactCode}</b></div></header><dl><div><dt>Family</dt><dd>{cell.family.name}</dd></div><div><dt>V24 historical reality</dt><dd>{cell.family.status}</dd></div><div><dt>Subsystem</dt><dd>{cell.subsystem+1} / 24</dd></div><div><dt>Phase</dt><dd>{cell.phase}</dd></div><div><dt>Stream</dt><dd>{cell.stream}</dd></div><div><dt>619D address</dt><dd>{cell.address.toLocaleString()}</dd></div><div><dt>Packet address</dt><dd>{cell.packetAddress.toLocaleString()}</dd></div></dl><div className='special-boundary'><ShieldCheck/><span><b>{cell.family.status}</b> · {cell.family.statusNote}</span></div><div className='atlas-r13-family-expression'><span>REGISTERED EXPRESSIONS</span><div>{expressions.map(p=><button key={p.id} onClick={()=>onNavigate(p.target)}><b>{p.label}</b><small>{p.target}</small></button>)}</div></div><div className='atlas-r1-sliders'><label>Subsystem <input type='range' min='0' max='23' value={subsystem} onChange={e=>setSubsystem(+e.target.value)}/><b>{subsystem+1}</b></label><label>Phase <input type='range' min='0' max='11' value={phase} onChange={e=>setPhase(+e.target.value)}/><b>{phase+1}</b></label><label>Stream <input type='range' min='0' max='3' value={stream} onChange={e=>setStream(+e.target.value)}/><b>{cell.stream}</b></label></div>{inlineLocal?<div className='special-boundary'><Volume2Inline/><span>S17 executes inline above because browser audio requires an explicit local user gesture; it does not navigate to a fake external backend.</span></div>:canOpen?<button className='atlas-r1-open' onClick={()=>onNavigate(cell.family.target)}><Waypoints/>OPEN {cell.family.target.toUpperCase()}</button>:<div className='special-boundary'><ShieldCheck/><span>No fake OPEN button from the historical V24 registry: this family was {cell.family.status}. Check the R46 successor restoration overlay above for newly bounded execution.</span></div>}</section></div>
  <section className='atlas-r1-menus'><header><Layers3/><div><span>12 MASTER OPERATIONAL INTENTS</span><b>Targets route only to currently bounded surfaces</b></div></header><div>{MASTER_MENUS.map(([id,name,target,purpose])=><button key={id} onClick={()=>onNavigate(target)}><code>{id}</code><span><b>{name}</b><small>{purpose}</small></span><em>{target}</em></button>)}</div></section>
  <footer className='atlas-r1-footer'><div><Box/><span><b>Execution truth boundary</b><small>V24 registration remains historical evidence. R46 successor executors are separately bounded and do not rewrite prior DONOR_ONLY / NATIVE_TARGET / RESTORATION_DEBT evidence. Native GPU/device/installer capabilities still require their own proof.</small></span></div><button onClick={()=>dl('OMEGA_SYSTEM_ATLAS_V24_TRUTH.json',{...receipt,operational:audit})}><Download/>Export truth receipt</button></footer>
 </section>
}
function Volume2Inline(){return <span aria-hidden='true' style={{fontSize:14}}>◖))</span>}
