export type SystemFamilyStatus='WEB_ACTIVE'|'SOURCE_ACTIVE'|'LOCAL_ACTIVE'|'EVIDENCE_GATED'|'DEVICE_GATED'|'DONOR_ONLY'|'NATIVE_TARGET'|'RESTORATION_DEBT';
export type SystemFamily={id:string;name:string;invariant:string;role:'CORE'|'DOMAIN'|'SUPPORT';status:SystemFamilyStatus;statusNote:string;base:number;target:string;inventoryPurpose:string};
export type ExpressionPlaneId='VISUAL'|'ANALYSIS'|'CONVERSATION'|'FORECAST'|'PROOF'|'CREATIVE'|'DEVICE'|'BUILD'|'ARCHIVE'|'SIGNAL';
export type ExpressionPlane={id:ExpressionPlaneId;label:string;purpose:string;target:string;boundary:string};
export const SYSTEM_ATLAS_ID='OMEGA_SYSTEM_ATLAS_V24_INVENTORY_ALIGNED';
export const SOFTWARE_MASTER_SOURCE='OMEGA_ALL_SOFTWARE_61917364224D_FULL_BUILD_ATLAS_v22.xlsx / SOFTWARE_MASTER';
export const ADDRESS_SPACE=61917364224,PACKET_SPACE=20736,SUBSYSTEM_COUNT=24,PHASE_COUNT=12,STREAM_COUNT=4,GRID_CELLS=27648;
export const SYSTEM_INVARIANT='ONE FIELD / ONE PACKET / ONE CONTINUITY LAW';
export const STREAMS=['Runtime','Render','Packaging','Design'] as const;
export const PHASES=['Canon Intent','Architecture','Data Contract','Authority','Compile','Traversal','Render','Proof','Return Packet','Runtime Sync','Package / Repair','Verification'] as const;
export const EXPRESSION_PLANES:ExpressionPlane[]=[
{id:'VISUAL',label:'Visual Field',purpose:'Express packet state as continuous geometry, topology, motion, scars and evidence-aware traversal.',target:'Visual Instrument',boundary:'Visualization is a projection of the authoritative packet; geometry does not create new facts.'},
{id:'ANALYSIS',label:'Analysis',purpose:'Inspect metrics, relations, calculus, derivatives, comparisons and cross-domain transforms.',target:'Reality Lab',boundary:'Derived analytics remain model outputs unless bound to measured evidence.'},
{id:'CONVERSATION',label:'Conversation',purpose:'Translate the same packet, modes, evidence and history into usable language and guided action.',target:'Command Center',boundary:'Language synthesis cannot override source state, evidence gates or proof status.'},
{id:'FORECAST',label:'Forecast',purpose:'Traverse admissible next-state alternatives, analogs, plasticity and uncertainty.',target:'Forecast',boundary:'Forecasts are conditional model projections, not guaranteed future events.'},
{id:'PROOF',label:'Proof & Ledger',purpose:'Record hashes, scars, admissibility, contradictions, provenance, replay and closure evidence.',target:'Evidence & Proof',boundary:'Proof surfaces report what was actually checked; missing evidence remains missing.'},
{id:'CREATIVE',label:'Create / Render',purpose:'Generate representations from the same state/traversal substrate when a proven renderer/export capability exists.',target:'Create',boundary:'Creative projections must retain their source packet and cannot imply unavailable GPU/native media production.'},
{id:'DEVICE',label:'Device / Hybrid',purpose:'Plan typed local-device operations through proof-gated paired-host transport.',target:'Hybrid Link',boundary:'Native execution remains DEVICE_PROOF_REQUIRED until a paired host returns proof.'},
{id:'BUILD',label:'Build / Deploy',purpose:'Patch, test, package, verify, rollback and promote capabilities that exist in the active host.',target:'Build Out',boundary:'A design or donor package is not a live installer or native build until independently proven.'},
{id:'ARCHIVE',label:'Archive / Recovery',purpose:'Census, classify, compare and recover donor capability without allowing stale donors to seize authority.',target:'Archive Operators',boundary:'Archive presence is donor evidence, not automatic runtime authority.'},
{id:'SIGNAL',label:'Audio / Signal',purpose:'Sonify packet phase, continuity, plasticity, contradiction and burden through the restored 12-lane local signal engine.',target:'System Atlas',boundary:'S17 is browser-local WebAudio sonification. It requires an explicit user gesture and never becomes packet authority or a claim of measured physical frequency.'}
];
export const FAMILY_EXPRESSION:Record<string,ExpressionPlaneId[]>={S00:['VISUAL','ANALYSIS','CONVERSATION','PROOF','DEVICE','BUILD'],S01:['VISUAL','ANALYSIS','FORECAST','CREATIVE'],S02:['VISUAL','ANALYSIS','FORECAST','PROOF'],S03:['CONVERSATION','DEVICE','PROOF','ARCHIVE'],S04:['ANALYSIS','CONVERSATION','FORECAST','BUILD'],S05:['ANALYSIS','PROOF','FORECAST'],S06:['VISUAL','ANALYSIS','FORECAST','CREATIVE'],S07:['VISUAL','ANALYSIS','SIGNAL'],S08:['VISUAL','CREATIVE'],S09:['VISUAL','ANALYSIS','FORECAST','PROOF'],S10:['VISUAL','ANALYSIS','FORECAST'],S11:['BUILD','PROOF','ARCHIVE'],S12:['BUILD','ARCHIVE','DEVICE'],S13:['VISUAL','ANALYSIS','FORECAST','SIGNAL'],S14:['ANALYSIS','FORECAST','PROOF','CONVERSATION'],S15:['PROOF','ARCHIVE','BUILD'],S16:['ANALYSIS','ARCHIVE','PROOF'],S17:['SIGNAL','CREATIVE','ANALYSIS'],S18:['CONVERSATION','ANALYSIS','CREATIVE'],S19:['VISUAL','ANALYSIS','FORECAST'],S20:['ARCHIVE','PROOF','BUILD'],S21:['CREATIVE','VISUAL','SIGNAL'],S22:['CONVERSATION','DEVICE','PROOF','ANALYSIS'],S23:['BUILD','PROOF','ARCHIVE','DEVICE']};
export const MASTER_MENUS=[['01','Runtime Core','System','Owns bounded hosted state/runtime inspection'],['02','Proof & Governance','Evidence & Proof','Truth, admissibility, replay and drift'],['03','Traversal','Traversal','Move through admitted source-state relations'],['04','Render Field','Visual Instrument','Source-packet field visualization'],['05','Host Inputs','Cockpit','Bounded input/observation control'],['06','AI Orchestration','SAI Lab','Provider-gated assistance with evidence boundaries'],['07','Data / Atlas','Atlas','20,736 source atlas control plane'],['08','Audio / Signal','System Atlas','Browser-local 12-lane packet sonification; user gesture required'],['09','World / Forecast','Earth Now','Evidence-gated Earth and model forecast'],['10','Recovery / Packaging','Build Out','Hosted build/restore tooling; native installer remains separate'],['11','Archive Merge','Archive Operators','Donor ingestion and proof-bound classification'],['12','Operator Cockpit','Command Center','Human control and source-backed dispatch']] as const;
const F=(id:string,name:string,invariant:string,role:SystemFamily['role'],status:SystemFamilyStatus,statusNote:string,base:number,target:string,inventoryPurpose:string):SystemFamily=>({id,name,invariant,role,status,statusNote,base,target,inventoryPurpose});
export const FAMILIES:SystemFamily[]=[
F('S00','Omega Atlas Desktop / Atlas OS','HOST_DESKTOP_TRAVERSAL','CORE','WEB_ACTIVE','Hosted Worker/runtime shell is active; the historical native desktop host remains a separately proven target.',72,'System','Primary desktop runtime shell for atlas-native traversal, mode selection, HUD, launcher, proof display, and field navigation.'),
F('S01','Omega Reality Compiler','STATE_TO_FIELD_COMPILER','CORE','SOURCE_ACTIVE','Current hosted state-to-field/analysis path exists over the canonical packet; native compiler breadth is not implied.',5341946328,'Reality Lab','Compiles reality tree, seed chain, packet state, observer frame, and traversal output.'),
F('S02','Persistent Packet Substrate','ONE_PACKET_TYPE','CORE','SOURCE_ACTIVE','20,736 source packet and derived state channels are active in the hosted runtime.',10684141416,'Field','One packet type across all scales: continuity, burden, memory, phase, contradiction, scar, neighbor links, child seed.'),
F('S03','Hybrid Link Software','BRIDGE_VERIFY_RETURN','CORE','DEVICE_GATED','Planning/status contracts are hosted; native PC/phone execution requires paired-device proof.',15596105976,'Hybrid Link','Connective tissue: donor intake, adapter bridge, authority resolver, conflict scan, return packets.'),
F('S04','CanonForge / Genesis Engine','CANON_LAW_RUNTIME','DOMAIN','EVIDENCE_GATED','Proposal/governance surfaces exist; constitutional admission requires explicit proof and release authority.',20938301064,'Canon Evolution','Geometry-law recursion stack: Alpha/Omega, E0, Genesis, CanonForge interpreter.'),
F('S05','VGCL / Vigil Geometry','VERIFIED_GEOMETRIC_LOGIC','DOMAIN','EVIDENCE_GATED','Relational/governance semantics are represented; full historical executable breadth is not independently proven.',25850265624,'Governance','Executable proof-geometry, forecast topology, auto-ping propagation, no-zero residual logic.'),
F('S06','Executable Atlas Generator','ATLAS_COMPILER','DOMAIN','SOURCE_ACTIVE','Canonical 144/1,728/20,736 addressing, projections and admitted routes are active.',31192460712,'Atlas','Generates 144D, 1728D, 20736D, shell states, topology maps, and packet tables.'),
F('S07','Shell / Mandala Engine','LOCAL_1_PLUS_6_SHELL','DOMAIN','SOURCE_ACTIVE','Shell/mandala source projections exist; this does not claim the full historical GPU/native engine.',36534406968,'Visual Instrument','Recursive shell detector, transport corridors, simplex/opposite-pair burden topology.'),
F('S08','Field Render Engine','CONTINUITY_VISUALIZER','DOMAIN','SOURCE_ACTIVE','Hosted source-bound field rendering is active; WebGPU/native cinematic production remains separate.',41446620360,'Visual Instrument','Pointillist volumetric field renderer: macro/micro continuity, glow, turbulence, temporal accumulation.'),
F('S09','Earth Traversal Engine','WGS84_GIS_LIDAR_GATE','DOMAIN','EVIDENCE_GATED','WGS84/evidence paths are active where providers return data; unavailable GIS/DEM/OSM/LiDAR is never synthesized as fact.',46788566616,'Earth Now','Earth/city/region traversal with geodesy, GIS, OSM, DEM, LiDAR evidence gates.'),
F('S10','Biological Traversal Engine','BODY_CELL_ATOM_STACK','DOMAIN','RESTORATION_DEBT','Historical biology traversal is registered but no complete microscopy/molecular source adapter is proven in this Worker.',51700780008,'System Atlas','Organism → organ → tissue → cell → molecule → atom using same packet substrate.'),
F('S11','Omega Patch System','SAFE_DELTA_UPGRADE','SUPPORT','LOCAL_ACTIVE','Hosted build/restore controls exist; native patch-chain behavior requires artifact and rollback proof.',57042726264,'Build Out','Delta patches, backup/restore, checksum, rollback, chained upgrade and repair.'),
F('S12','Omega Micro Build','SOVEREIGN_SEED_RUNTIME','DOMAIN','DONOR_ONLY','Registered portable donor/packaging concept; no independent live micro-build runtime is claimed.',1493064,'System Atlas','Small portable archive-aware runtime seed with merge rules and lock files.'),
F('S13','Living Coherence Membrane','COHERENCE_FIELD_SUBSTRATE','DOMAIN','SOURCE_ACTIVE','Continuity/plasticity/scar/contradiction field channels drive hosted visualization and analysis.',5343439320,'Matter Traversal','20,736-cell continuity membrane, burden routing, contradiction transport, attractor curvature.'),
F('S14','Dewey Calculus Engine','STAY_TURN_ESCALATE','DOMAIN','SOURCE_ACTIVE','Only source-backed formulas with present authoritative inputs execute; missing-input formulas remain gated.',10685634408,'Modes','Decision operator runtime: stay, turn, escalate, construct, prune, ledger.'),
F('S15','Proof / Forensic System','AUTHORITY_DRIFT_AUDIT','SUPPORT','EVIDENCE_GATED','Hosted proof/hash/ledger surfaces exist; claims are limited to checks actually performed.',15597598968,'Evidence & Proof','Closure ledger, proof state, shadow detection, hash checks, replay validation.'),
F('S16','Workbook / Excel Atlas Runtime','SPREADSHEET_CONTROL_PLANE','SUPPORT','DONOR_ONLY','Drive/Library workbooks are authority donors; the Worker does not pretend to host a full Excel execution engine.',20939794056,'System Atlas','Excel as atlas editor, build chart, ledger surface, 619D engineering map.'),
F('S17','Echo-Chamber / SOMA Audio Engine','PHASE_COHERENT_AUDIO','DOMAIN','LOCAL_ACTIVE','Restored browser-local WebAudio backend: 12 discrete phase lanes, per-lane oscillator/gain/pan, safety compressor, master bus, packet sync, explicit start/stop and phase sequencing. Audio is sonification only.',25851758616,'System Atlas','Field-loop audio system, harmonic carriers, adaptive equilibrium loops.'),
F('S18','Universal Language System','SEMANTIC_PACKET_LANGUAGE','DOMAIN','RESTORATION_DEBT','Language donor semantics survive, but a distinct proven lexicon engine has not been restored as an executable subsystem.',31193953704,'Instructions','Geometry-language mapping, semantic packets, symbol/meaning bridge.'),
F('S19','Observer / Now-Frame Runtime','MOVING_RELATIVE_ANCHOR','DOMAIN','SOURCE_ACTIVE','Current observer/phase/relative-frame source projections are active.',36535899960,'Relativity','Floating-origin observer frame, phase displacement, dynamic coordinate origin.'),
F('S20','Recovery Board System','KEEP_DONOR_QUARANTINE','SUPPORT','EVIDENCE_GATED','Archive classification/governance is available; donor promotion remains proof-gated.',41448113352,'Archive Operators','Artifact governance board: KEEP/DONOR/QUARANTINE/EXPAND NEXT classification.'),
F('S21','Cinematic Field Renderer','IMMERSIVE_SNAPSHOT_ENGINE','DOMAIN','NATIVE_TARGET','Source-packet browser renders exist; the historical high-end cinematic GPU/image/video production path is not claimed as live.',46790059608,'System Atlas','Still-image renderer from same packet state core: Tucson, cell, atom, space, workplace images.'),
F('S22','Operator Dashboard / Control Surface','HUMAN_IN_LOOP_UI','SUPPORT','WEB_ACTIVE','Command Center/Cockpit/System Atlas provide hosted human-in-loop control; native-device actions remain separately gated.',51702273000,'Cockpit','Dashboard for field intake, active chain, topology map, return packets, proof/case export.'),
F('S23','One-Click Packaging System','DESKTOP_INSTALLER_RELEASE','SUPPORT','NATIVE_TARGET','Build Out exposes hosted packaging/release evidence, but a one-click native installer is not live in the Worker until target-machine proof passes.',57044219256,'Build Out','Installer, launcher, dependency repair, support bundle, executable packaging.')
];
export function atlasCell(family:number,subsystem:number,phase:number,stream:number){const f=((family%24)+24)%24,s=((subsystem%24)+24)%24,p=((phase%12)+12)%12,t=((stream%4)+4)%4,row=(((f*24+s)*12+p)*4+t);return{row,family:FAMILIES[f],subsystem:s,phase:PHASES[p],stream:STREAMS[t],packetAddress:row%PACKET_SPACE,address:(FAMILIES[f].base+row*2987856)%ADDRESS_SPACE,artifactCode:`${FAMILIES[f].id}.${String(s).padStart(2,'0')}.${String(p).padStart(2,'0')}.${t}`}}
export function expressionPlanesForFamily(id:string){const ids=FAMILY_EXPRESSION[id]||[];return ids.map(id=>EXPRESSION_PLANES.find(x=>x.id===id)!).filter(Boolean)}
export function systemAtlasReceipt(state:number){const statusCounts=Object.fromEntries([...new Set(FAMILIES.map(x=>x.status))].map(s=>[s,FAMILIES.filter(x=>x.status===s).length]));return{schema:SYSTEM_ATLAS_ID,source:SOFTWARE_MASTER_SOURCE,state,generatedAt:new Date().toISOString(),invariant:SYSTEM_INVARIANT,addressSpace:ADDRESS_SPACE,packetSpace:PACKET_SPACE,families:FAMILIES.length,statusCounts,subsystems:SUBSYSTEM_COUNT,phases:PHASE_COUNT,streams:STREAM_COUNT,gridCells:GRID_CELLS,menus:MASTER_MENUS.length,expressionPlanes:EXPRESSION_PLANES.length,boundary:'Representational software/runtime atlas aligned to the authoritative 24-family software inventory. Family registration is not execution. S17 LOCAL_ACTIVE means browser-local sonification only. 61,917,364,224 is software address capacity, not a claim of physical dimensions. Drive release authority is never mutated by this receipt.'}}
