import {corpusState} from './corpusRuntime';
import {sourceBackedModeSummary} from './sourceBackedModeRuntimeR21';
import {sha256Hex} from './saiB059Runtime';

export type DeweyDispatchOperator='CARRY'|'CONSTRUCT'|'PRUNE'|'TURN'|'ESCALATE';
export type TransitionProofStatus='SOURCE_TRANSITION_VERIFIED'|'SOURCE_TRANSITION_INVALID';
export type CanonicalTransitionReceipt={
 schema:'OMEGA_CANONICAL_TRANSITION_R23';
 fromAddress:number;toAddress:number;fromStateId:number;toStateId:number;
 sourceDecision:string;mode188Gate:string;selectedOperator:DeweyDispatchOperator;
 dispatchOrder:readonly DeweyDispatchOperator[];rejectedOperators:DeweyDispatchOperator[];
 beforeHash:string;afterHash:string;transitionHash:string;
 before:any;after:any;scarCarry:{before:number;after:number;delta:number};
 evidence:{before:number;after:number;sourceVersion:string;fieldCount:number;externalEvidenceAdded:false};
 modes:{applied:string[];gated:string[]};sceneRevision:1;returnAddress:number;
 proofStatus:TransitionProofStatus;reasons:string[];boundary:string;
};
const ORDER=['CARRY','CONSTRUCT','PRUNE','TURN','ESCALATE'] as const;
function canonical(value:any):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`}
function packetProjection(r:any){return{address:r.address,stateId:r.stateId,coordinates:r.coordinates,decision:r.metrics.decision,mode188:r.metrics.mode188,continuity:r.metrics.continuity,plasticity:r.metrics.plasticity,contradiction:r.metrics.contradiction,burden:r.metrics.burden,scar:r.metrics.scar,evidence:r.metrics.evidence,pscGate:r.psc.gate,dataNext:r.autoPing.dataNext,previous:r.autoPing.previous,sourceVersion:r.source.version}}
function dispatchOperator(r:any):{selected:DeweyDispatchOperator;reasons:string[]}{const decision=String(r?.metrics?.decision||'').toUpperCase(),mode188=String(r?.metrics?.mode188||'').toUpperCase(),prunePressure=Number(r?.metrics?.contradiction||0)+Number(r?.metrics?.burden||0)-Number(r?.metrics?.continuity||0);if(mode188==='PRUNE')return{selected:'PRUNE',reasons:['Source Mode188 gate is PRUNE.']};if(decision==='TURN')return{selected:'TURN',reasons:['Canonical source decision is TURN.']};if(decision==='ESCALATE')return{selected:'ESCALATE',reasons:['Canonical source decision is ESCALATE.']};if(decision==='STAY')return{selected:'CONSTRUCT',reasons:['Canonical source decision is STAY; hosted dispatch preserves the admitted source route as constructive continuation.']};return{selected:prunePressure>0?'PRUNE':'CONSTRUCT',reasons:['Source decision label was unavailable; fallback is bounded to packet prune pressure and is explicitly derived.']}}
export async function compileCanonicalTransition(address:number):Promise<CanonicalTransitionReceipt>{const from=corpusState(address),to=corpusState(from.autoPing.dataNext),dispatch=dispatchOperator(from),before=packetProjection(from),after=packetProjection(to),beforeHash=await sha256Hex(canonical(before)),afterHash=await sha256Hex(canonical(after)),m=sourceBackedModeSummary(from),body={fromAddress:from.address,toAddress:to.address,sourceDecision:from.metrics.decision,mode188Gate:from.metrics.mode188,selectedOperator:dispatch.selected,beforeHash,afterHash};const transitionHash=await sha256Hex(canonical(body)),valid=to.address===from.autoPing.dataNext&&beforeHash!==afterHash;return{schema:'OMEGA_CANONICAL_TRANSITION_R23',fromAddress:from.address,toAddress:to.address,fromStateId:from.stateId,toStateId:to.stateId,sourceDecision:String(from.metrics.decision),mode188Gate:String(from.metrics.mode188),selectedOperator:dispatch.selected,dispatchOrder:ORDER,rejectedOperators:ORDER.filter(x=>x!=='CARRY'&&x!==dispatch.selected) as DeweyDispatchOperator[],beforeHash,afterHash,transitionHash,before,after,scarCarry:{before:Number(from.metrics.scar),after:Number(to.metrics.scar),delta:Number(to.metrics.scar)-Number(from.metrics.scar)},evidence:{before:Number(from.metrics.evidence),after:Number(to.metrics.evidence),sourceVersion:String(from.source.version),fieldCount:Number(from.source.fieldCount),externalEvidenceAdded:false},modes:{applied:m.rows.filter(x=>x.state!=='GATED_MISSING_INPUTS').map(x=>x.id),gated:m.gated.map(x=>x.id)},sceneRevision:1,returnAddress:from.autoPing.previous,proofStatus:valid?'SOURCE_TRANSITION_VERIFIED':'SOURCE_TRANSITION_INVALID',reasons:[...dispatch.reasons,'Next state is taken directly from canonical autoPing.dataNext.','CARRY is represented by the source packet/previous-state continuity and scar channels before terminal dispatch.'],boundary:'This receipt proves internal hosted source-state transition consistency only. It does not establish an external physical event, native-device execution, or empirical truth.'}}
export async function compileTransitionCorridor(address:number,steps=12){const receipts:CanonicalTransitionReceipt[]=[];let cursor=Math.max(0,Math.min(20735,Math.floor(address)));for(let i=0;i<Math.max(1,Math.min(64,steps));i++){const receipt=await compileCanonicalTransition(cursor);receipts.push(receipt);cursor=receipt.toAddress;if(receipt.toAddress===receipt.fromAddress)break}return{schema:'OMEGA_TRANSITION_CORRIDOR_R23',startAddress:address,receipts,boundary:'Every edge is a verified internal canonical autoPing transition; no interpolated state is promoted to source data.'}}
