export const R157_VISUAL_TRUTH_SCHEMA='OMEGA_VISUAL_TRUTH_R157' as const;

export const R157_VISUAL_SURFACES=[
 'Matter Traversal','Visual Instrument','Immersive Traversal','Extreme Traversal','Traversal','Forecast','Relativity','Earth Now','Atlas','Infinity','Scale Compiler','Reality Lab','Field','Data Motion','Convergence'
] as const;

export type VisualTruthSurfaceR157=typeof R157_VISUAL_SURFACES[number];
export type VisualTruthKindR157='RETURNED_OBSERVATION'|'IMPORTED_OBSERVATION'|'CANONICAL_STATE'|'EXACT_TRANSFORM'|'FORECAST_MODEL'|'DERIVED_PROJECTION'|'ARCHIVE_SOURCE';
export type VisualSpaceR157='WGS84_GEOGRAPHIC'|'OMEGA_ADDRESS_SPACE'|'OMEGA_TRANSITION_SPACE'|'OBSERVER_PROJECTION'|'MODEL_FUTURE_SPACE'|'USER_DATA_SPACE'|'ARCHIVE_SOURCE_SPACE'|'DERIVED_HIERARCHY';
export type CanonEffectR157='NONE'|'ADDRESS_COMMIT_ONLY';

export type VisualTruthContractR157={
 surface:VisualTruthSurfaceR157;
 kind:VisualTruthKindR157;
 space:VisualSpaceR157;
 sourceAuthority:string;
 renderAuthority:string;
 timeAuthority:string;
 interactionAuthority:string;
 canonEffect:CanonEffectR157;
 absenceLaw:string;
 forbiddenClaim:string;
 signature:readonly string[];
};

const V=(surface:VisualTruthSurfaceR157,kind:VisualTruthKindR157,space:VisualSpaceR157,sourceAuthority:string,renderAuthority:string,timeAuthority:string,interactionAuthority:string,canonEffect:CanonEffectR157,absenceLaw:string,forbiddenClaim:string,signature:readonly string[]):VisualTruthContractR157=>({surface,kind,space,sourceAuthority,renderAuthority,timeAuthority,interactionAuthority,canonEffect,absenceLaw,forbiddenClaim,signature});

export const VISUAL_TRUTH_R157:readonly VisualTruthContractR157[]=[
 V('Matter Traversal','CANONICAL_STATE','OMEGA_ADDRESS_SPACE','Canonical 20,736-state corpus packet + exact transition/field-node evaluation','WebGL projection of packet metrics, shell/topology relations, route state, evidence, contradiction, burden, scar and continuity','Canonical packet transition / renderer animation time; never physical elapsed time','Camera/view/projection controls change representation only; an explicit canonical address commit is the only state mutation','ADDRESS_COMMIT_ONLY','If canonical field data is unavailable the renderer must hold/error rather than invent matter.','Rendered matter, biology, density, shell deformation or motion is not measured physical matter or microscopic observation.',['canvas','VIEW_CONTRACT','PROJECTION_CONTRACT']),
 V('Visual Instrument','CANONICAL_STATE','OMEGA_ADDRESS_SPACE','Canonical 20,736-state mandala field + evaluated packet + visual calibration','Depth/lineage/lens projection of the real field arrays and selected canonical address','Canonical state plus renderer animation time','Lens, depth, yaw, pitch, zoom and renderer reductions change only view; explicit address selection/admitted-next changes canonical address','ADDRESS_COMMIT_ONLY','Field/calibration failure remains a visible loading/error state; no replacement point cloud is fabricated.','Point geometry, color, depth and cinematic lenses are derived projections of source-bound state, not observations of physical space.',['visual-stage','SOURCE-BOUND','calibration']),
 V('Immersive Traversal','CANONICAL_STATE','OMEGA_TRANSITION_SPACE','Current canonical packet + exact admitted-next transition','Immersive traversal projection of legal state evolution','Model transition order; not an invented clock interval','Traversal controls inspect or follow the admitted path; state changes only through canonical address commit','ADDRESS_COMMIT_ONLY','Missing transition authority holds traversal instead of creating an alternative route.','Immersive geometry and apparent motion are not measured physical motion or an external scene.',['admitted-next','canonical']),
 V('Extreme Traversal','CANONICAL_STATE','OMEGA_TRANSITION_SPACE','Canonical packet + exact evaluation + explicitly restored source-bound functions','High-detail traversal/field projection with restored functions kept provenance-separated','Model transition order plus renderer frame time','Restored/deep controls change projection unless they invoke the existing canonical address commit','ADDRESS_COMMIT_ONLY','Restored modules remain unavailable when their source/runtime dependency is unavailable.','Restored or elaborate rendering does not become a measurement, host-execution proof or independent source authority.',['canonical','restored']),
 V('Traversal','CANONICAL_STATE','OMEGA_TRANSITION_SPACE','Current packet + admitted autoPing transition + exact route evaluation','Traversal studio representation of the admitted state path','Discrete legal model transitions','Camera/path controls change representation; only the admitted address commit changes canonical state','ADDRESS_COMMIT_ONLY','No admitted transition means no fabricated continuation.','Rendered route motion is address-space evolution, not physical velocity or spatial travel.',['transition','admitted']),
 V('Forecast','FORECAST_MODEL','MODEL_FUTURE_SPACE','Current canonical packet + exact evaluator + deterministic forecast-plan corridor generator','SVG corridor geometry is generated from the forecast plan actual route points, weights and scores','Transition horizon only; future observation is explicitly false','Horizon/scenario controls recompute/select model corridors and never observe or cause the future','NONE','If the forecast plan cannot be computed the surface must hold/error; it may not substitute an imagined future.','Forecast corridors, weights and turning points are admissible model continuations, never future observations or guaranteed outcomes.',['Advanced competing future corridor comparison','futureObservationUsed:false','Competing legal futures without pretending to observe the future']),
 V('Relativity','EXACT_TRANSFORM','OBSERVER_PROJECTION','Canonical packet + source/workbook relations + exact Lorentz/Doppler/OMEGA evaluator values','Observer-relative projection and exact current→admitted-next truth plots','Canonical packet transition plus declared observer β parameter','β/perspective/controller controls alter the observer projection only and must not rewrite the canonical packet','NONE','If exact source relations are unavailable they stay gated; no physical measurement is inferred from a projection.','β is a projection parameter here, not a measured velocity of the OMEGA state; derived depth/rate are not new physical evidence or dimensions.',['Observer speed β','Lorentz γ','observer changes projection, not canonical existence']),
 V('Earth Now','RETURNED_OBSERVATION','WGS84_GEOGRAPHIC','Returned public weather/seismic/natural-event/space-weather evidence + NOAA coverage metadata/images','WGS84 geographic instrument; NOAA GeoColor is a documented derived sensor composite; calculus comparison is separately representational','Returned provider observation timestamps / current source aliases','Latitude/longitude changes the source query target; model-mapped address only seeds the initial target','NONE','Unavailable source/provider material remains unavailable and is never synthetically replaced.','OMEGA calculus overlays are not a second Earth sensor; a model-mapped target is not itself an observed location fact.',['WGS84 target','RETURNED EVIDENCE BOUND','Missing or unavailable source material is not synthetically replaced']),
 V('Atlas','DERIVED_PROJECTION','OMEGA_ADDRESS_SPACE','Canonical atlas addresses and deterministic address/state mapping','Interactive geometric projection of canonical address relationships','Canonical state identity; no physical clock implied','Selecting an atlas node may commit that exact canonical address; camera/projection controls do not mutate state','ADDRESS_COMMIT_ONLY','Missing canonical address data yields no substitute atlas geometry.','Atlas geometry and 12→144→1728→20,736 resolution are model/address structure, not literal physical dimensions or measured spatial coordinates.',['20,736','SOURCE STATES']),
 V('Infinity','ARCHIVE_SOURCE','ARCHIVE_SOURCE_SPACE','Recovered archive/source rows kept distinct from the live canonical packet','Source-row and recursive/derived comparison views','Archive/source record order plus current packet context','Row/context selection changes inspection only unless an explicit canonical address action is separately invoked','NONE','Missing archive/source rows remain missing; no donor/source content is fabricated.','Recovered source channels are historical/source evidence, not current external observation or infinite physical scale.',['archive','source']),
 V('Scale Compiler','DERIVED_PROJECTION','DERIVED_HIERARCHY','Canonical packet + exact evaluator inputs to recursive compiler-node hierarchy','Nested scale/hierarchy representation generated from declared compiler inputs','Model hierarchy order','Scale/depth controls change hierarchy representation; canonical state changes only through explicit address selection if exposed','ADDRESS_COMMIT_ONLY','Unbound measured inputs remain gated; the renderer must not fill them with invented measurement.','Recursive scale levels are representational/address hierarchy, not measured physical size or extra physical dimensions.',['scale','compiler']),
 V('Reality Lab','IMPORTED_OBSERVATION','USER_DATA_SPACE','User-imported CSV/TSV bytes + deterministic parse/analysis receipt','Plots/maps of the actual imported rows with optional derived calculus mapping separated','Dataset timestamps/row order only when present in imported data','Import/filter/analysis controls operate on user-provided data; canonical commit remains an explicit separate action','ADDRESS_COMMIT_ONLY','No imported dataset means no observational analysis; missing rows/columns are never synthesized.','Derived mappings are analysis of imported data, not replacement observations or proof beyond the supplied dataset.',['CSV','TSV','import']),
 V('Field','CANONICAL_STATE','OMEGA_ADDRESS_SPACE','Direct canonical packet metrics + admitted-next packet comparison','Field/calculus representation of exact packet values and source-bound relations','Current and admitted-next canonical state relation','Field/lens controls change representation; only explicit canonical address commit mutates state','ADDRESS_COMMIT_ONLY','Missing packet values stay gated/unavailable rather than filled decoratively.','Field geometry, color and motion are representational encodings of packet values, not a measured external field.',['continuity','contradiction','evidence']),
 V('Data Motion','EXACT_TRANSFORM','OMEGA_TRANSITION_SPACE','Exact current→admitted-next packet values and deterministic deltas/derivatives','Motion/transition plots encode those exact address-space changes','Discrete canonical transition index','Display controls change inspection only; data motion does not itself mutate canonical state','NONE','A missing next packet/delta holds the display; interpolation may not be presented as source fact.','Address-space derivatives and motion scores are not physical velocity, acceleration or measured spacetime motion.',['delta','motion','transition']),
 V('Convergence','DERIVED_PROJECTION','OMEGA_TRANSITION_SPACE','Canonical packet + exact evaluator + explicitly scored candidate routes/proof stages','Ranked convergence/candidate geometry generated from those candidate scores','Candidate/proof-stage order','Ranking/filter controls change candidate inspection; only an explicit selected candidate commit may change canonical address','ADDRESS_COMMIT_ONLY','If candidate evidence is insufficient the candidate remains held; no ranking is promoted to truth by appearance.','A visually dominant basin/candidate is not destiny, external causation, execution proof or CanonState until the existing admission boundary passes.',['candidate','proof','convergence'])
] as const;

export const VISUAL_TRUTH_KIND_LABEL_R157:Record<VisualTruthKindR157,string>={
 RETURNED_OBSERVATION:'RETURNED OBSERVATION',IMPORTED_OBSERVATION:'IMPORTED OBSERVATION',CANONICAL_STATE:'CANONICAL STATE',EXACT_TRANSFORM:'EXACT TRANSFORM',FORECAST_MODEL:'FORECAST MODEL',DERIVED_PROJECTION:'DERIVED PROJECTION',ARCHIVE_SOURCE:'ARCHIVE SOURCE'
};

export const VISUAL_SPACE_LABEL_R157:Record<VisualSpaceR157,string>={
 WGS84_GEOGRAPHIC:'WGS84 GEOGRAPHIC',OMEGA_ADDRESS_SPACE:'OMEGA ADDRESS SPACE',OMEGA_TRANSITION_SPACE:'OMEGA TRANSITION SPACE',OBSERVER_PROJECTION:'OBSERVER PROJECTION',MODEL_FUTURE_SPACE:'MODEL FUTURE SPACE',USER_DATA_SPACE:'USER DATA SPACE',ARCHIVE_SOURCE_SPACE:'ARCHIVE SOURCE SPACE',DERIVED_HIERARCHY:'DERIVED HIERARCHY'
};

const BY_SURFACE=new Map(VISUAL_TRUTH_R157.map(x=>[x.surface,x]));
export function visualTruthForSurfaceR157(surface:string){return BY_SURFACE.get(surface as VisualTruthSurfaceR157)||null}
export function isVisualTruthSurfaceR157(surface:string):surface is VisualTruthSurfaceR157{return BY_SURFACE.has(surface as VisualTruthSurfaceR157)}

export function visualTruthAuditR157(){
 const names=VISUAL_TRUTH_R157.map(x=>x.surface),duplicates=names.filter((x,i)=>names.indexOf(x)!==i),missingBoundary=VISUAL_TRUTH_R157.filter(x=>!x.absenceLaw||!x.forbiddenClaim||!x.sourceAuthority||!x.renderAuthority).map(x=>x.surface),observationWithoutNoSynthesis=VISUAL_TRUTH_R157.filter(x=>['RETURNED_OBSERVATION','IMPORTED_OBSERVATION'].includes(x.kind)&&!/never|no |unavailable|missing/i.test(x.absenceLaw)).map(x=>x.surface),literalDimensionClaims=VISUAL_TRUTH_R157.filter(x=>/physical dimensions?[^.]*20,?736|20,?736 physical dimensions?/i.test(`${x.sourceAuthority} ${x.renderAuthority} ${x.forbiddenClaim}`)).map(x=>x.surface);
 return{schema:R157_VISUAL_TRUTH_SCHEMA,total:names.length,unique:new Set(names).size,duplicates,missingBoundary,observationWithoutNoSynthesis,literalDimensionClaims,pass:names.length===R157_VISUAL_SURFACES.length&&new Set(names).size===R157_VISUAL_SURFACES.length&&duplicates.length===0&&missingBoundary.length===0&&observationWithoutNoSynthesis.length===0&&literalDimensionClaims.length===0,boundary:'R157 visual truth classifies what a renderer shows and what its controls may change. A correct visualization of a canonical/model state is still not an external observation, and visual prominence never upgrades evidence or canonical authority.'};
}
