import {workerLiveStateSpine} from './workerLiveStateR51.js';
import {compilePacketProofR52} from './workerPacketProofR52.js';
import {compileDeltaMeshR53} from './workerDeltaMeshR53.js';
import {verifyProofChainR54} from './workerProofChainR54.js';
const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const PUBLIC_HOST="omegav6.jeffdeweyeljefe.workers.dev";
const PUBLIC_URL=`https://${PUBLIC_HOST}/`;
const WORKERS_AI_MODEL="@cf/google/gemma-4-26b-a4b-it";
const SOURCE_RESTORE=Object.freeze({branch:"main",sourceBranch:"full-restore",donor:"hosted B058/V90",releaseAuthority:"Google Drive LATEST_OMEGA_UPDATE.json -> B015 R1 + explicit owner public-cloud authorization 2026-08-29",sourceRuntime:{stateSpace:20736,sourceAlgebraModes:179,embeddedCorpus:"MIGRATED_EXACT",unifiedCalculus:"MIGRATED_EXACT",atlas:"MIGRATED_EXACT",calculusTraversal:"MIGRATED_ADAPTED"},workstation:{routesRegistered:44,assistantFirst:"LIVE_SOURCE",localContinuity:"LIVE_BROWSER",projects:"LIVE_BROWSER",renderQueue:"LIVE_BROWSER",proofLedger:"LIVE_BROWSER",memory:"LIVE_BROWSER",routeForecast:"LIVE_SOURCE",systemValidation:"LIVE_SOURCE_AND_WORKER",hybridLink:"DEVICE_PROOF_REQUIRED",earthExternalFeeds:"EXTERNAL_DEGRADED"},preserved:["B020_ROUTE_BEFORE_GENERATION","PUBLIC_HEALTH","TRUTHFUL_STATUS","WORKERS_DEV_ROUTE","LOCAL_DRAFT_CONTINUITY","SINGLE_FLIGHT","RESPONSIVE_CONTAINMENT","AUTH_CONTINUITY","DRIVE_RELEASE_AUTHORITY","OWNER_PUBLIC_PROMOTION_AUTHORIZATION"]});
const BUILD=Object.freeze({product:"OMEGAv6 Sovereign Cloud Runtime",deploymentLineage:"OMEGA B015 sovereign chain + hosted B058/V90 donor merge",acceptedDescendant:"phase-aware restore-and-surpass workstation",publicAdapter:"R21 phase-aware grounded AI bridge",releaseAuthority:"Drive local lineage + explicit owner public promotion authorization",deployBridge:"GitHub -> Cloudflare Workers",publicUrl:PUBLIC_URL,appDeploy:false,generatedAt:"2026-08-29"});
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS})}
function isPublicRuntime(url){return url.protocol==="https:"&&url.hostname.toLowerCase()===PUBLIC_HOST}
function restorationPayload(url){const liveVerified=isPublicRuntime(url);return{...SOURCE_RESTORE,state:liveVerified?"PUBLIC_RUNTIME_VERIFIED":"SOURCE_RESTORE_READY",lineageClassification:liveVerified?"FULL_SOURCE_RESTORE_PUBLIC_RUNTIME":"SOURCE_RESTORE_NOT_PUBLICLY_VERIFIED",publicUrl:PUBLIC_URL,liveDeploymentVerification:liveVerified?"LIVE_PASS":"NOT_VERIFIED_IN_THIS_REQUEST",fullSourceRestoreClaimed:liveVerified,fullRestoreClaimed:liveVerified,truthBoundary:"FULL RESTORE refers to the cloud-hosted source/workstation slice. Native PC execution still requires device proof; Earth feeds and external observations remain truth-gated until bound. Workers AI synthesis is model output, not source observation."}}
function isBoundedRuntimeQuery(text){const t=String(text||"").trim();return /^(?:status|health|version|build status|runtime status|provider status|bridge status|hybrid link status|heartbeat status|restoration status)\??$/i.test(t)||/^(?:what(?:'s| is)|show|check|get)\s+(?:the\s+)?(?:status|health|version|build status|runtime status|provider status|bridge status|hybrid link status|heartbeat status|restoration status)\??$/i.test(t)}
function classify(text){const t=String(text||"").trim();if(!t)return{route:"FAST_DETERMINISTIC",reason:"empty-input",modelInvocations:0};if(/\b(all modes|full modes|activate all modes)\b/i.test(t))return{route:"ROUTED_MODEL_FULL",reason:"explicit-all-modes",modelInvocations:0};if(isBoundedRuntimeQuery(t))return{route:"FAST_DETERMINISTIC",reason:"bounded-runtime-query",modelInvocations:0};if(/\b(repair|design|forecast|train|compare|analy[sz]e|deep|full|build|code|program|create|make|implement|upgrade|fix)\b/i.test(t))return{route:"ROUTED_MODEL",reason:"synthesis-required",modelInvocations:0};return{route:"ROUTED_MODEL",reason:"conversational-synthesis",modelInvocations:0}}
function cleanContext(value){if(!value||typeof value!=="object")return{};const raw=JSON.stringify(value);if(raw.length>24000)return JSON.parse(raw.slice(0,23900).replace(/[,][^,{}]*$/,'')+'}');return value}
function statusPayload(env,url){const restoration=restorationPayload(url),provider=env.AI?`WORKERS_AI_BOUND:${WORKERS_AI_MODEL}`:(env.OMEGA_MODEL_ENDPOINT?"CONFIGURED_EXTERNAL":"GROUNDED_RUNTIME_ONLY");return{ok:true,build:BUILD,cloud:{worker:restoration.liveDeploymentVerification==="LIVE_PASS"?"LIVE_PASS":"LIVE_REQUEST_CONTEXT",staticAssets:"MAIN_BUILD",mergeTarget:"main",publicUrl:PUBLIC_URL,liveDeploymentVerification:restoration.liveDeploymentVerification},canonicalAuthority:{source:"Google Drive local lineage + owner public authorization",release:"B015 R1 / public restore-and-surpass",state:"SPLIT_SCOPE_AUTHORITY",promotion:"VERIFIED_CANDIDATE_ALLOWED"},modelProvider:provider,workersAI:{bound:Boolean(env.AI),model:env.AI?WORKERS_AI_MODEL:"NOT_BOUND",truthRole:"SYNTHESIS_ONLY"},hybridLink:{state:"DEVICE_PROOF_REQUIRED",missionControlSurface:"LIVE_PLANNER",nativeExecutionClaimed:false},earth:{state:"SOURCE_VISUALIZATION_LIVE",liveFeeds:"EXTERNAL_DEGRADED_UNTIL_BOUND"},restoration,truthBoundary:restoration.truthBoundary}}
function deterministicReply(text,restoration){if(/\brestoration\b/i.test(text))return`Restoration is ${restoration.state}. Public runtime ${restoration.liveDeploymentVerification}. Native Hybrid Link remains device-proof gated.`;if(/\bhealth\b/i.test(text))return`Cloud Worker request handling is live at ${PUBLIC_URL}. Native Hybrid Link requires verified device proof.`;if(/\b(provider|model)\b/i.test(text))return"Provider status is reported by /api/status. Workers AI is synthesis-only and does not become source authority.";if(/\b(status|version|build status)\b/i.test(text))return`${BUILD.product}; ${BUILD.publicAdapter}; restoration ${restoration.state}; local release lineage B015 R1.`;return"Bounded deterministic route completed."}
function groundedFallback(text,context,reason){const state=context?.stateId??context?.address??"unknown",phase=context?.phase??"unknown",decision=context?.decision??"unknown",m=context?.metrics||{},next=context?.nextAddress!=null?Number(context.nextAddress)+1:"unknown",modeCount=context?.modeCount??"unknown";return{ok:true,provider:"OMEGA_GROUNDED_RUNTIME",modelInvoked:false,evidenceStatus:"SOURCE_BOUND_FALLBACK",reply:`I am connected to OMEGA's deterministic runtime, but general AI synthesis is temporarily unavailable (${reason}). I will not pretend nobody answered or fabricate a model result. Current supplied state: ${state}; phase ${phase}; decision ${decision}; ALL MODES ${modeCount}; CΩ ${Number(m.continuity||0).toFixed(3)}, Φ ${Number(m.plasticity||0).toFixed(3)}, q ${Number(m.contradiction||0).toFixed(3)}, Λ ${Number(m.burden||0).toFixed(3)}; routed next state ${next}. Your request was: “${String(text).slice(0,500)}”. You can still traverse, inspect phase, matter, Earth geometry, forecast, proof and system state while synthesis recovers.`,uncertainty:"No generative interpretation was substituted. This fallback reports only the runtime context supplied with the request.",nextAction:"Retry synthesis or continue with the source-bound workstation."}}
function extractModelText(result){if(!result)return"";if(typeof result==="string")return result;if(typeof result.response==="string")return result.response;if(typeof result.result?.response==="string")return result.result.response;const c=result.choices?.[0]?.message?.content;if(typeof c==="string")return c;if(Array.isArray(c))return c.map(x=>typeof x==="string"?x:(x?.text||"")).join("\n").trim();return""}
async function workersAiReply(env,text,context,routing){const system=`You are the synthesis layer inside OMEGA, a sovereign evidence-bound workstation. The route-before-generation classifier already ran: ${routing.route}. Use the supplied OMEGA runtime context as the authority for claims about the current OMEGA state. ALL MODES means the local registry was evaluated; do not pretend you personally executed hidden modes beyond the summary supplied. Clearly distinguish: (1) source/runtime values, (2) internal model interpretation or projection, (3) external observation, and (4) unavailable evidence. Never fabricate live Earth/weather/satellite/device facts, native PC execution, provider success, or physical validation. 12/144/1728/20736 are representational resolution, not physical dimensions. Preserve continuity, phase, burden, contradiction, scar, future plasticity, evidence, route-before-generation and rollback/truth boundaries. Be useful, conversational and concise. When the user asks how a state behaves, explain relationships and motion rather than dumping a table.`;const user=`OMEGA RUNTIME CONTEXT\n${JSON.stringify(context)}\n\nUSER REQUEST\n${text}`;const result=await env.AI.run(WORKERS_AI_MODEL,{messages:[{role:"system",content:system},{role:"user",content:user}],max_tokens:1200,temperature:.35,chat_template_kwargs:{enable_thinking:false}});const reply=extractModelText(result);if(!reply)throw Error("Workers AI returned no textual completion");return reply}
async function externalReply(env,text,routing,context){const upstream=await fetch(env.OMEGA_MODEL_ENDPOINT,{method:"POST",headers:{"content-type":"application/json",...(env.OMEGA_MODEL_AUTH?{authorization:env.OMEGA_MODEL_AUTH}:{})},body:JSON.stringify({text,route:routing.route,context})});const raw=await upstream.text();if(!upstream.ok)throw Error(`External model adapter failed (${upstream.status})`);try{const parsed=JSON.parse(raw),reply=parsed.reply||parsed.response||parsed.choices?.[0]?.message?.content;if(reply)return String(reply)}catch{}return raw}
async function api(request,env,url){
 const restoration=restorationPayload(url);
 if(url.pathname==="/api/health"&&request.method==="GET")return json({ok:true,service:BUILD.product,build:BUILD,publicUrl:PUBLIC_URL,restoration:{state:restoration.state,fullRestoreClaimed:restoration.fullRestoreClaimed},ai:{bound:Boolean(env.AI),model:env.AI?WORKERS_AI_MODEL:"NOT_BOUND"},now:new Date().toISOString()});
 if(url.pathname==="/api/status"&&request.method==="GET")return json(statusPayload(env,url));
 if(url.pathname==="/api/live-state-spine"&&request.method==="GET"){const status=statusPayload(env,url),provider=status.modelProvider;return json(workerLiveStateSpine({status,restoration,provider,publicUrl:PUBLIC_URL}));}
 if(url.pathname==="/api/proof/packet"&&request.method==="POST"){const body=await request.json().catch(()=>({})),proof=await compilePacketProofR52(body);return json(proof,proof.status||200);}
 if(url.pathname==="/api/proof/delta"&&request.method==="POST"){const body=await request.json().catch(()=>({})),proof=await compileDeltaMeshR53(body);return json(proof,proof.status||200);}
 if(url.pathname==="/api/proof/chain"&&request.method==="POST"){const body=await request.json().catch(()=>({})),proof=await verifyProofChainR54(body);return json(proof,proof.status||200);}
 if(url.pathname==="/api/restoration"&&request.method==="GET")return json({ok:true,...restoration,build:BUILD.publicAdapter,provider:env.AI?`WORKERS_AI:${WORKERS_AI_MODEL}`:(env.OMEGA_MODEL_ENDPOINT?"CONFIGURED_EXTERNAL":"GROUNDED_RUNTIME_ONLY"),nativeHost:"DEVICE_PROOF_REQUIRED",earthFeeds:"EXTERNAL_DEGRADED_UNTIL_BOUND"});
 if(url.pathname==="/api/hybrid/status"&&request.method==="GET")return json({ok:true,state:"DEVICE_PROOF_REQUIRED",controller:"LIVE_PLANNER",devices:[],jobs:[],nativeExecutionClaimed:false,message:"Cloud mission planning is live; no native heartbeat is claimed until a paired host proves itself."});
 if(url.pathname==="/api/hybrid/desktop-update"&&request.method==="GET")return json({ok:true,state:"DEVICE_PROOF_REQUIRED",nativeUpdate:"NOT_TESTABLE_WITHOUT_HOST",message:"A paired Windows host must prove its current version before an update decision can be made."});
 if(url.pathname==="/api/missions"&&request.method==="GET")return json({ok:true,missions:[],state:"DEVICE_PROOF_REQUIRED"});
 if(url.pathname==="/api/orchestrator/thread"&&request.method==="GET")return json({ok:true,thread:null,persistence:"LOCAL_BROWSER",routeBeforeGeneration:true});
 if(url.pathname==="/api/orchestrator/turn"&&request.method==="POST")return json({ok:false,code:"ORCHESTRATOR_GOVERNED_ADAPTER_REQUIRED",reply:"Conversation synthesis is live separately. ENACT remains gated because executable plan translation requires the governed Hybrid adapter and authenticated device proof."},503);
 if((url.pathname==="/api/hybrid/jobs"||url.pathname.startsWith("/api/hybrid/jobs/")||url.pathname==="/api/missions")&&request.method==="POST")return json({ok:false,code:"DEVICE_PROOF_REQUIRED",reply:"Native mission execution requires a verified paired-host heartbeat and proof channel."},503);
 if(url.pathname.startsWith("/api/missions/")&&request.method==="POST")return json({ok:false,code:"DEVICE_PROOF_REQUIRED",reply:"Mission control execution is unavailable until a verified paired host is bound."},503);
 if((url.pathname==="/api/subscriptions"||url.pathname==="/api/subscriptions/remove")&&request.method==="POST")return json({ok:true,state:"LOCAL_BROWSER_ONLY",realtime:"NOT_BOUND"});
 if(url.pathname==="/api/route-preview"&&request.method==="POST"){const body=await request.json().catch(()=>({})),text=String(body.text||body.message||"").slice(0,16384);return json({ok:true,...classify(text)})}
 if(url.pathname==="/api/chat"&&request.method==="POST"){const body=await request.json().catch(()=>({})),text=String(body.text||body.message||"").slice(0,16384),context=cleanContext(body.context),routing=classify(text);if(routing.route==="FAST_DETERMINISTIC")return json({ok:true,routing,provider:"OMEGA_DETERMINISTIC",modelInvoked:false,evidenceStatus:"VERIFIED_RUNTIME",reply:deterministicReply(text,restoration),uncertainty:"Bounded runtime route; no model synthesis required."});if(env.AI){try{const reply=await workersAiReply(env,text,context,routing);return json({ok:true,routing:{...routing,modelInvocations:1},provider:`WORKERS_AI:${WORKERS_AI_MODEL}`,modelInvoked:true,evidenceStatus:"MODEL_SYNTHESIS_GROUNDED_TO_RUNTIME_CONTEXT",reply,uncertainty:"This is model synthesis grounded to supplied OMEGA runtime state. External facts require independent evidence.",nextAction:"Continue from the same canonical packet and phase context."})}catch(e){if(env.OMEGA_MODEL_ENDPOINT){try{const reply=await externalReply(env,text,routing,context);return json({ok:true,routing:{...routing,modelInvocations:1},provider:"EXTERNAL_MODEL_ADAPTER",modelInvoked:true,evidenceStatus:"MODEL_SYNTHESIS_GROUNDED_TO_RUNTIME_CONTEXT",reply,uncertainty:"External synthesis; source and external claims remain evidence-gated."})}catch{}}return json(groundedFallback(text,context,e instanceof Error?e.message:"Workers AI unavailable"))}}if(env.OMEGA_MODEL_ENDPOINT){try{const reply=await externalReply(env,text,routing,context);return json({ok:true,routing:{...routing,modelInvocations:1},provider:"EXTERNAL_MODEL_ADAPTER",modelInvoked:true,evidenceStatus:"MODEL_SYNTHESIS_GROUNDED_TO_RUNTIME_CONTEXT",reply,uncertainty:"External synthesis; source and external claims remain evidence-gated."})}catch(e){return json(groundedFallback(text,context,e instanceof Error?e.message:"external provider unavailable"))}}return json(groundedFallback(text,context,"Workers AI binding not available"))}
 return json({ok:false,code:"NOT_FOUND"},404)
}
export{classify,SOURCE_RESTORE,PUBLIC_HOST,PUBLIC_URL,WORKERS_AI_MODEL,restorationPayload};
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return api(request,env,url);return env.ASSETS.fetch(request)}};
