import r27 from './workerR27.js';
import {WORKERS_AI_MODEL} from './worker.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const text=v=>String(v??'').trim();
const now=()=>Date.now();
const safeId=(v,fallback='anonymous')=>{const s=text(v).slice(0,128);return /^[A-Za-z0-9._:-]+$/.test(s)?s:fallback};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
const HYBRID_OPS=Object.freeze(['TRAIN_LOCAL','INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','SAFE_IMPORT','WORKBOOK_AUDIT','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','OPEN_URL','WAIT','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO']);
const HYBRID_PROFILES=Object.freeze(['AUTO_BUILD','NODE_BUILD','PYTHON_TEST','DOTNET_BUILD','WINDOWS_AUTOMATION','BROWSER_AUTOMATION']);
async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function randomToken(bytes=24){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function modelText(result){if(!result)return'';if(typeof result==='string')return result;if(typeof result.response==='string')return result.response;if(typeof result.result?.response==='string')return result.result.response;const c=result.choices?.[0]?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>typeof x==='string'?x:(x?.text||'')).join('\n').trim();return''}
function relativePath(v){const s=text(v||'.').replace(/\\/g,'/');if(!s||s==='.')return'.';if(s.startsWith('/')||/^[A-Za-z]:/.test(s)||s.split('/').includes('..')||s.includes('\0'))return null;return s.split('/').filter(Boolean).join('/')||'.'}
function parseProjectPath(prompt){const m=String(prompt).match(/(?:project|root|folder|path)\s*(?:=|:|at|is)?\s*["'`](.+?)["'`]/i);return relativePath(m?.[1]||'.')||'.'}
function allowedDomains(prompt){const out=[];for(const m of String(prompt).matchAll(/https:\/\/([A-Za-z0-9.-]+)(?:[:/]|$)/g)){const host=m[1].toLowerCase();if(!out.includes(host))out.push(host)}return out.slice(0,12)}
function intent(prompt){const p=String(prompt).toLowerCase();return{execution:/\b(build|repair|fix|patch|test|package|zip|train|index|search|read|audit|open|click|type|macro|desktop|pc|hybrid|execute|run|operate)\b/.test(p),train:/\b(train|learning|learn locally)\b/.test(p),build:/\b(build|compile)\b/.test(p),test:/\b(test|qa|verify)\b/.test(p),repair:/\b(repair|fix|patch|edit)\b/.test(p),package:/\b(package|zip|installer)\b/.test(p),audit:/\b(audit|inspect|scan|index|workspace)\b/.test(p),browser:/\b(open|browser|click|type|macro)\b/.test(p)}}
function safePlan(prompt){const i=intent(prompt),projectPath=parseProjectPath(prompt),domains=allowedDomains(prompt),steps=[];const add=(op,label,extra={})=>steps.push({id:'S'+String(steps.length+1).padStart(2,'0'),op,label,...extra});
 if(i.train){add('TRAIN_LOCAL','Rebuild the local SAI retrieval corpus and return an evaluation receipt',{path:projectPath,maxResults:25000});return{projectPath,allowedDomains:domains,steps}}
 if(i.browser&&domains.length){const url=String(prompt).match(/https:\/\/[^\s"')]+/i)?.[0];if(url)add('OPEN_URL','Open the explicitly approved HTTPS destination',{url});add('ASSERT_WINDOW','Lock the visible browser window before any interaction',{windowTitle:'Browser'});return{projectPath,allowedDomains:domains,steps}}
 add('INDEX','Discover project manifests and working files inside the approved root',{path:projectPath});add('HASH_TREE','Fingerprint the approved source tree before action',{path:projectPath,maxResults:5000});
 if(projectPath!=='.'){if(i.repair)add('SEARCH_TEXT','Locate likely repair targets from the approved project',{path:projectPath,query:'TODO FIXME error failed',maxResults:120});if(i.build||i.repair)add('BUILD','Run the declared project build',{path:projectPath,profile:'AUTO_BUILD'});if(i.test||i.build||i.repair)add('TEST','Run the declared project verification',{path:projectPath,profile:'AUTO_BUILD'});if(i.package)add('PACKAGE','Package the verified project output',{path:projectPath})}
 return{projectPath,allowedDomains:domains,steps:steps.slice(0,24)}}
function validateJob(raw){const errors=[],steps=Array.isArray(raw?.steps)?raw.steps:[];if(!raw?.confirmed)errors.push('explicit confirmation required');if(steps.length<1||steps.length>24)errors.push('1-24 steps required');for(const [idx,row] of steps.entries()){if(!HYBRID_OPS.includes(row?.op))errors.push(`step ${idx+1}: unsupported op`);if(row?.profile&&!HYBRID_PROFILES.includes(row.profile))errors.push(`step ${idx+1}: unsupported profile`);if(row?.path&&!relativePath(row.path))errors.push(`step ${idx+1}: unsafe path`);if(row?.url&&!String(row.url).startsWith('https://'))errors.push(`step ${idx+1}: HTTPS required`)}return{valid:!errors.length,errors,steps}}

export class OmegaRuntime {
 constructor(ctx,env){this.ctx=ctx;this.env=env}
 async get(key,fallback){const v=await this.ctx.storage.get(key);return v===undefined?fallback:v}
 async put(key,value){await this.ctx.storage.put(key,value)}
 async event(type,message,data={}){const events=await this.get('events',[]),row={id:'evt_'+now().toString(36)+'_'+randomToken(3),at:now(),type,message,data};events.push(row);await this.put('events',events.slice(-300));return row}
 async devices(){const rows=await this.get('devices',[]),t=now();return rows.map(x=>({...x,online:t-Number(x.lastSeen||0)<30000}))}
 async authorized(req){const secret=text(req.headers.get('x-omega-bridge-secret'));const hash=await this.get('bridgeSecretHash','');return Boolean(secret&&hash&&await sha256(secret)===hash)}
 async state(){const devices=await this.devices(),jobs=await this.get('jobs',[]),missions=await this.get('missions',[]),events=await this.get('events',[]),paired=Boolean(await this.get('bridgeSecretHash',''));const online=devices.filter(x=>x.online&&!x.revoked);return{schema:'OMEGA_ENACTED_RUNTIME_R32',state:online.length?'VERIFIED_DEVICE_ONLINE':paired?'DEVICE_PROOF_REQUIRED':'PAIRING_REQUIRED',paired,devices,jobs:jobs.slice(-80),missions:missions.slice(-40),activeJobs:jobs.filter(x=>['QUEUED','RUNNING'].includes(x.status)).length,events:events.slice(-30),nativeExecutionClaimed:online.length>0,lastEvent:events.at(-1)||null}}
 async fetch(request){const u=new URL(request.url),path=u.pathname;
  if(path==='/snapshot'&&request.method==='GET')return json(await this.state());
  if(path==='/events'&&request.method==='GET'){const events=await this.get('events',[]);return json({ok:true,events:events.slice(-100)})}
  if(path==='/pair'&&request.method==='POST'){const body=await request.json().catch(()=>({})),existing=await this.get('bridgeSecretHash','');if(existing&&!body.rotate)return json({ok:true,state:'PAIRING_EXISTS',secretReturned:false});const secret=randomToken(24);await this.put('bridgeSecretHash',await sha256(secret));await this.put('bridgeCreatedAt',now());await this.event(existing?'PAIR_ROTATED':'PAIR_CREATED','A new Hybrid Link pairing credential was issued.');return json({ok:true,state:'PAIRING_READY',secretReturned:true,secret})}
  if(path==='/agent/register'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.deviceId,'');if(!id)return json({ok:false,code:'DEVICE_ID_REQUIRED'},400);let rows=await this.get('devices',[]),row={id,name:text(b.name||'OMEGA PC').slice(0,120),platform:text(b.platform||'unknown').slice(0,120),version:text(b.version||'R32-agent').slice(0,80),capabilities:Array.isArray(b.capabilities)?b.capabilities.filter(x=>HYBRID_OPS.includes(x)).slice(0,40):[],rootLabel:text(b.rootLabel||'approved root').slice(0,160),lastSeen:now(),revoked:false};rows=[...rows.filter(x=>x.id!==id),row].slice(-20);await this.put('devices',rows);await this.event('DEVICE_REGISTERED',`${row.name} registered with authenticated bridge proof.`,{deviceId:id});return json({ok:true,device:row})}
  if(path==='/agent/heartbeat'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.deviceId,'');let rows=await this.get('devices',[]),found=false;rows=rows.map(x=>x.id===id?(found=true,{...x,lastSeen:now(),version:text(b.version||x.version)}):x);if(!found)return json({ok:false,code:'DEVICE_NOT_REGISTERED'},404);await this.put('devices',rows);return json({ok:true,at:now()})}
  if(path==='/agent/poll'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.deviceId,'');let jobs=await this.get('jobs',[]),job=jobs.find(x=>x.status==='QUEUED'&&x.targetDeviceId===id);if(job){jobs=jobs.map(x=>x.id===job.id?({...x,status:'RUNNING',startedAt:now()}):x);job=jobs.find(x=>x.id===job.id);await this.put('jobs',jobs);await this.event('JOB_CLAIMED',`Job ${job.id} claimed by paired host.`,{jobId:job.id,deviceId:id})}return json({ok:true,job:job||null})}
  if(path==='/agent/result'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),jobId=safeId(b.jobId,''),deviceId=safeId(b.deviceId,'');let jobs=await this.get('jobs',[]),target=jobs.find(x=>x.id===jobId&&x.targetDeviceId===deviceId);if(!target)return json({ok:false,code:'JOB_NOT_FOUND'},404);const packet={schema:'OMEGA_HYBRID_RETURN_PACKET_R32',receivedAt:now(),deviceId,stepProofs:Array.isArray(b.stepProofs)?b.stepProofs.slice(0,24):[],outputPaths:Array.isArray(b.outputPaths)?b.outputPaths.slice(0,40):[],log:text(b.log).slice(-12000),evaluation:b.evaluation||null,promotion:b.promotion||null,resultFingerprint:text(b.resultFingerprint)||await sha256({jobId,deviceId,stepProofs:b.stepProofs||[],at:now()})};const status=b.ok===false?'FAILED':'COMPLETE';jobs=jobs.map(x=>x.id===jobId?({...x,status,completedAt:now(),returnPacket:packet,outputPaths:packet.outputPaths,log:packet.log}):x);await this.put('jobs',jobs);await this.event('JOB_RETURNED',`Job ${jobId} returned ${status} with host proof.`,{jobId,deviceId,status});return json({ok:true,job:jobs.find(x=>x.id===jobId)})}
  if(path==='/status'&&request.method==='GET')return json({ok:true,...await this.state()});
  if(path==='/jobs'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'DEVICE_PROOF_REQUIRED',reply:'Pair this browser to the local OMEGA agent before native work can queue.'},503);const b=await request.json().catch(()=>({})),v=validateJob(b);if(!v.valid)return json({ok:false,code:'PLAN_REJECTED',errors:v.errors},400);const devices=await this.devices(),target=devices.find(x=>x.id===b.targetDeviceId&&x.online&&!x.revoked);if(!target)return json({ok:false,code:'DEVICE_PROOF_REQUIRED',reply:'The selected paired host is not currently proving an online heartbeat.'},503);let jobs=await this.get('jobs',[]);const job={id:'job_'+now().toString(36)+'_'+randomToken(4),schema:b.schema||'OMEGA_HYBRID_JOB_R32',action:b.action||'PLAN',profile:b.profile||'AUTO_BUILD',projectPath:relativePath(b.projectPath)||'.',instructions:text(b.instructions||''),allowedDomains:Array.isArray(b.allowedDomains)?b.allowedDomains.slice(0,12):[],steps:v.steps,targetDeviceId:target.id,status:'QUEUED',confirmed:true,queuedAt:now(),inputFingerprint:await sha256({steps:v.steps,targetDeviceId:target.id,projectPath:b.projectPath||'.'})};jobs.push(job);await this.put('jobs',jobs.slice(-120));await this.event('JOB_QUEUED',`Approved job ${job.id} queued for ${target.name}.`,{jobId:job.id,deviceId:target.id});return json({ok:true,job})}
  if(path.startsWith('/jobs/')&&path.endsWith('/analyze')&&request.method==='POST'){const id=safeId(path.split('/')[2],''),jobs=await this.get('jobs',[]),job=jobs.find(x=>x.id===id);if(!job?.returnPacket)return json({ok:false,code:'HOST_PROOF_REQUIRED'},409);return json({ok:true,draft:{schema:'OMEGA_HOST_PROOF_REPAIR_DRAFT_R32',projectPath:job.projectPath,allowedDomains:job.allowedDomains||[],steps:[{id:'S01',op:'HASH_TREE',label:'Re-check the approved tree after returned host proof',path:job.projectPath,maxResults:5000},{id:'S02',op:'TEST',label:'Verify the smallest next delta against the same project',path:job.projectPath,profile:job.profile||'AUTO_BUILD'}],diagnosis:`Host proof for ${job.id} returned ${job.status}. Continue from the returned evidence rather than inventing state.`}})}
  if(path==='/missions'&&request.method==='GET')return json({ok:true,missions:(await this.get('missions',[])).slice(-40),state:(await this.state()).state});
  if(path==='/missions'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'DEVICE_PROOF_REQUIRED'},503);const b=await request.json().catch(()=>({})),v=validateJob({...b.draft,confirmed:b.confirmedMission});if(!v.valid)return json({ok:false,code:'MISSION_REJECTED',errors:v.errors},400);const devices=await this.devices(),target=devices.find(x=>x.id===b.targetDeviceId&&x.online&&!x.revoked);if(!target)return json({ok:false,code:'DEVICE_PROOF_REQUIRED'},503);let jobs=await this.get('jobs',[]),missions=await this.get('missions',[]);const missionId='mission_'+now().toString(36)+'_'+randomToken(3),job={id:'job_'+now().toString(36)+'_'+randomToken(4),schema:'OMEGA_MISSION_JOB_R32',action:'MISSION_CYCLE',profile:'AUTO_BUILD',projectPath:relativePath(b.draft?.projectPath)||'.',allowedDomains:b.draft?.allowedDomains||[],steps:v.steps,targetDeviceId:target.id,status:'QUEUED',confirmed:true,queuedAt:now(),inputFingerprint:await sha256({missionId,steps:v.steps})};jobs.push(job);const mission={id:missionId,objective:text(b.objective).slice(0,3000),threadId:text(b.threadId),status:'ACTIVE',targetDeviceId:target.id,allowedOps:Array.isArray(b.allowedOps)?b.allowedOps.filter(x=>HYBRID_OPS.includes(x)):[],maxCycles:clamp(b.maxCycles,2,8),cycle:1,currentJobId:job.id,currentJob:job,createdAt:now()};missions.push(mission);await Promise.all([this.put('jobs',jobs.slice(-120)),this.put('missions',missions.slice(-40))]);await this.event('MISSION_STARTED',`Governed mission ${missionId} started from an approved envelope.`,{missionId,jobId:job.id});return json({ok:true,mission})}
  if(path.startsWith('/missions/')&&request.method==='POST'){const parts=path.split('/'),id=safeId(parts[2],''),action=parts[3];let missions=await this.get('missions',[]),m=missions.find(x=>x.id===id);if(!m)return json({ok:false,code:'MISSION_NOT_FOUND'},404);if(action==='pause')m={...m,status:'PAUSED'};else if(action==='resume')m={...m,status:'ACTIVE'};else return json({ok:false,code:'UNKNOWN_MISSION_ACTION'},404);missions=missions.map(x=>x.id===id?m:x);await this.put('missions',missions);await this.event('MISSION_CONTROL',`Mission ${id} ${m.status.toLowerCase()}.`,{missionId:id,status:m.status});return json({ok:true,mission:m})}
  if(path==='/thread'&&request.method==='GET'){const thread=await this.get('thread',null);return json({ok:true,thread,persistence:'DURABLE_RUNTIME',routeBeforeGeneration:true})}
  if(path==='/turn'&&request.method==='POST'){const b=await request.json().catch(()=>({})),prompt=text(b.prompt).slice(0,16000),execution=intent(prompt).execution,plan=safePlan(prompt),old=await this.get('thread',null),thread={id:old?.id||('thr_'+now().toString(36)+'_'+randomToken(4)),turnCount:Number(old?.turnCount||0)+1,updatedAt:now(),createdAt:old?.createdAt||now()};await this.put('thread',thread);await this.event(execution?'AI_ACTION_PREPARED':'AI_CONVERSATION',execution?'SAI prepared a governed action draft.':'SAI completed a conversational turn.',{threadId:thread.id});return json({ok:true,thread,turn:{kind:execution?'ACTION':'CONVERSATION',assistantMessage:execution?'I translated your intent into a bounded, reviewable action sequence. Native execution still waits for your explicit approval and a proved paired host.':'I kept this turn conversational; no native action was queued.',requiresExecution:execution,nextPromptHint:execution?'Review the visible action sequence, pair a host if needed, then approve it.':'Continue the same persistent thread.'},draft:execution?{schema:'OMEGA_GOVERNED_ACTION_DRAFT_R32',state:'DRAFT_NOT_QUEUED',projectPath:plan.projectPath,allowedDomains:plan.allowedDomains,steps:plan.steps}:null})}
  return json({ok:false,code:'DO_ROUTE_NOT_FOUND'},404)
 }
}

function sessionId(request){return safeId(request.headers.get('x-omega-session-id'),'anon')}
function bridgeId(request,body){return safeId(request.headers.get('x-omega-bridge-id')||body?.bridgeId||sessionId(request),'anon')}
function runtimeStub(env,id){return env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(id))}
async function proxy(env,id,path,request,body){const headers=new Headers(request.headers);headers.set('content-type','application/json');const init={method:request.method,headers};if(body!==undefined&&request.method!=='GET')init.body=JSON.stringify(body);return runtimeStub(env,id).fetch(new Request('https://omega-runtime.internal'+path,init))}
async function baseJson(request,env){const r=await r27.fetch(request,env),ct=r.headers.get('content-type')||'';if(!ct.includes('application/json'))return{response:r,data:null};const raw=await r.clone().json().catch(()=>null);return{response:r,data:raw}}
async function aiReply(env,prompt,stateContext,execution){if(!env.AI)return execution?'I prepared only deterministic, allow-listed steps because the synthesis provider is unavailable.':'The durable OMEGA thread is live, but synthesis is temporarily unavailable.';try{const system=`You are OMEGA's synthesis layer. Be concise and operational. Separate source/runtime evidence from interpretation. Never claim a PC action occurred unless host proof is supplied. The system already decided whether this turn requires governed execution: ${execution}. Do not invent shell commands or credentials. If execution is required, explain the intent and what the bounded plan should accomplish; the deterministic action compiler, not you, chooses executable operations.`;const result=await env.AI.run(WORKERS_AI_MODEL,{messages:[{role:'system',content:system},{role:'user',content:`STATE CONTEXT\n${JSON.stringify(stateContext||{})}\n\nREQUEST\n${prompt}`}],max_tokens:900,temperature:.25,chat_template_kwargs:{enable_thinking:false}});return modelText(result)||'OMEGA synthesis returned no text; the governed runtime did not fabricate a replacement.'}catch(e){return `OMEGA synthesis is degraded (${e instanceof Error?e.message:String(e)}). The governed runtime state remains available.`}}

async function fetchR32(request,env){const url=new URL(request.url),path=url.pathname;
 if(!env.OMEGA_RUNTIME){if(path.startsWith('/api/runtime/')||path.startsWith('/api/hybrid/pair')||path.startsWith('/api/hybrid/agent/'))return json({ok:false,code:'RUNTIME_STATE_BINDING_UNAVAILABLE'},503);return r27.fetch(request,env)}
 const sid=sessionId(request),bid=bridgeId(request,{});
 if(path==='/api/runtime/snapshot'&&request.method==='GET')return proxy(env,sid,'/snapshot',request);
 if(path==='/api/runtime/events'&&request.method==='GET')return proxy(env,sid,'/events',request);
 if(path==='/api/hybrid/pair'&&request.method==='POST'){const b=await request.json().catch(()=>({}));const r=await proxy(env,sid,'/pair',request,b);const data=await r.clone().json().catch(()=>({}));if(data.secret)return json({...data,bridgeId:sid,pairingCode:`${sid}.${data.secret}`,agentPath:'/api/hybrid/agent-download'});return r}
 if(path.startsWith('/api/hybrid/agent/')){const b=request.method==='POST'?await request.json().catch(()=>({})):{};const bid=bridgeId(request,b),suffix=path.replace('/api/hybrid','');return proxy(env,bid,suffix,request,b)}
 if(path==='/api/hybrid/status'&&request.method==='GET')return proxy(env,bid,'/status',request);
 if(path==='/api/hybrid/jobs'&&request.method==='POST'){const b=await request.json().catch(()=>({}));return proxy(env,bid,'/jobs',request,b)}
 if(path.startsWith('/api/hybrid/jobs/')&&path.endsWith('/analyze')&&request.method==='POST'){const b=await request.json().catch(()=>({}));return proxy(env,bid,path.replace('/api/hybrid',''),request,b)}
 if(path==='/api/missions'&&request.method==='GET')return proxy(env,bid,'/missions',request);
 if(path==='/api/missions'&&request.method==='POST'){const b=await request.json().catch(()=>({}));return proxy(env,bid,'/missions',request,b)}
 if(path.startsWith('/api/missions/')&&request.method==='POST'){const b=await request.json().catch(()=>({}));return proxy(env,bid,path.replace('/api',''),request,b)}
 if(path==='/api/orchestrator/thread'&&request.method==='GET')return proxy(env,sid,'/thread',request);
 if(path==='/api/orchestrator/turn'&&request.method==='POST'){const b=await request.json().catch(()=>({})),prompt=text(b.prompt).slice(0,16000),execution=intent(prompt).execution,plan=safePlan(prompt),assistantMessage=await aiReply(env,prompt,b.stateContext,execution),r=await proxy(env,sid,'/turn',request,b),data=await r.json();data.turn.assistantMessage=assistantMessage;data.draft=execution?{schema:'OMEGA_GOVERNED_ACTION_DRAFT_R32',state:'DRAFT_NOT_QUEUED',projectPath:plan.projectPath,allowedDomains:plan.allowedDomains,steps:plan.steps}:null;return json(data)}
 if(path==='/api/status'&&request.method==='GET'){const base=await baseJson(request,env);if(!base.data)return base.response;const rt=await (await proxy(env,bid,'/status',request)).json();return json({...base.data,hybridLink:{state:rt.state,missionControlSurface:'ENACTED_RUNTIME',nativeExecutionClaimed:rt.nativeExecutionClaimed,paired:rt.paired,onlineDevices:rt.devices?.filter(x=>x.online).length||0},enactedRuntime:{state:'LIVE_DURABLE',activeJobs:rt.activeJobs,lastEvent:rt.lastEvent||null,threadPersistence:'DURABLE_RUNTIME'}})}
 return r27.fetch(request,env)
}
export default{fetch:fetchR32};
