import r33,{OmegaRuntime as OmegaRuntimeR33} from './workerR33.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const text=v=>String(v??'').trim();
const now=()=>Date.now();
const safeId=(v,fallback='')=>{const s=text(v).slice(0,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:fallback};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bridgeId(request){return safeId(request.headers.get('x-omega-bridge-id')||request.headers.get('x-omega-session-id'),'')}
function runtimeStub(env,id){return env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(id))}
async function runtimeFetch(env,id,path,request,body){const headers=new Headers(request.headers);headers.set('content-type','application/json');return runtimeStub(env,id).fetch(new Request('https://omega-runtime.internal'+path,{method:request.method,headers,body:body===undefined?undefined:JSON.stringify(body)}))}

function federationOrigin(request){const origin=text(request.headers.get('origin'));if(!origin)return null;try{const u=new URL(origin),h=u.hostname.toLowerCase();if(u.protocol!=='https:')return null;if(h==='omegav6.jeffdeweyeljefe.workers.dev'||h==='omega-genesis-v1.jeffdeweyeljefe.workers.dev'||h==='omega-optical-cloud-woven2.vercel.app'||(/^omega-optical-cloud-[a-z0-9-]+-woven2\.vercel\.app$/).test(h))return origin}catch{}return null}
function withCors(response,request){const origin=federationOrigin(request);if(!origin)return response;const headers=new Headers(response.headers);headers.set('access-control-allow-origin',origin);headers.set('vary','Origin');headers.set('access-control-allow-methods','GET,POST,PUT,OPTIONS');headers.set('access-control-allow-headers','content-type,x-omega-bridge-id,x-omega-bridge-secret,x-omega-session-id');headers.set('access-control-max-age','600');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function preflight(request){const origin=federationOrigin(request);if(!origin)return new Response(null,{status:403});const headers=new Headers({'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-methods':'GET,POST,PUT,OPTIONS','access-control-allow-headers':'content-type,x-omega-bridge-id,x-omega-bridge-secret,x-omega-session-id','access-control-max-age':'600'});return new Response(null,{status:204,headers})}

function boundedRefs(value,limit){return Array.isArray(value)?value.slice(-limit).map(x=>typeof x==='string'?x.slice(0,180):x&&typeof x==='object'?JSON.parse(JSON.stringify(x)):null).filter(Boolean):[]}
function continuityProject(value){const id=safeId(value?.id);if(!id)return null;return{id,name:text(value?.name).slice(0,120)||'Untitled OMEGA project',created:clamp(value?.created,0,Number.MAX_SAFE_INTEGER),updated:clamp(value?.updated,0,Number.MAX_SAFE_INTEGER),address:clamp(value?.address,0,20735),stateId:clamp(value?.stateId,1,20736),status:value?.status==='ARCHIVED_LOCAL'?'ARCHIVED_LOCAL':'ACTIVE_LOCAL',note:text(value?.note).slice(0,4000),memoryRefs:boundedRefs(value?.memoryRefs,80),evidenceRefs:boundedRefs(value?.evidenceRefs,80),workflowRefs:boundedRefs(value?.workflowRefs,80),operationRefs:boundedRefs(value?.operationRefs,188),sha256:text(value?.sha256).slice(0,80),continuityHash:text(value?.continuityHash||value?.sha256).slice(0,80),lastIntent:text(value?.lastIntent).slice(0,120),lastWorkflowStatus:text(value?.lastWorkflowStatus).slice(0,80),authority:'DURABLE_RUNTIME_PROJECT_CONTINUITY_R97'}}
async function probeJsonService(url,headers={}){const started=now();try{const response=await fetch(url,{headers:{accept:'application/json','cache-control':'no-cache',...headers},cache:'no-store',cf:{cacheTtl:0},redirect:'manual',signal:AbortSignal.timeout(10000)}),contentType=response.headers.get('content-type')||'',redirected=response.status>=300&&response.status<400,html=contentType.includes('text/html'),authGate=response.status===401||response.status===403;if(redirected||html||authGate)return{state:'ACCESS_GATED',httpStatus:response.status,contentType,latencyMs:now()-started,jsonVerified:false};const body=await response.json().catch(()=>null);return{state:response.ok&&body&&(body.ok!==false||body.status==='OK')?'LIVE':'DEGRADED',httpStatus:response.status,contentType,latencyMs:now()-started,jsonVerified:Boolean(body&&typeof body==='object'),service:text(body?.service||body?.runtime||body?.name).slice(0,120)||null,version:text(body?.version||body?.build?.version).slice(0,80)||null}}catch(error){return{state:'UNREACHABLE',httpStatus:0,latencyMs:now()-started,jsonVerified:false,error:text(error instanceof Error?error.message:error).slice(0,180)}}}
async function probeGenesis(env){const canonical='https://omega-genesis-v1.jeffdeweyeljefe.workers.dev/api/health?omega_federation_probe=r97',configured=text(env.OMEGA_GENESIS_HEALTH_URL)||canonical,first=await probeJsonService(configured);if(first.state==='LIVE'||configured===canonical)return first;const fallback=await probeJsonService(canonical);return fallback.state==='LIVE'?{...fallback,recoveredFromConfiguredEndpoint:true}:first}

function materialOk(model){return model&&['n_incident','n_feature','n_background','n_substrate'].every(k=>Number.isFinite(Number(model[k]))&&Number(model[k])>0)}
function geometryOk(g){if(!g)return false;const p=Number(g.pitch_nm),w=Number(g.width_nm),l=Number(g.length_nm),h=Number(g.height_nm);return [p,w,l,h].every(Number.isFinite)&&p>0&&w>0&&l>0&&h>0&&w<=p&&l<=p}
function validateFullwaveJob(job){const errors=[];if(job?.schema!=='OMEGA_FULLWAVE_QUEUE_v1')errors.push('schema must be OMEGA_FULLWAVE_QUEUE_v1');if(String(job?.solver).toLowerCase()!=='rcwa')errors.push('R34 accepts RCWA jobs only');if(!safeId(job?.source_packet_id))errors.push('source_packet_id required');if(!geometryOk(job?.geometry))errors.push('valid bounded geometry required');if(!Number.isFinite(Number(job?.wavelength_nm))||Number(job.wavelength_nm)<=0)errors.push('wavelength_nm required');if(!materialOk(job?.material_model))errors.push('numeric material_model refractive indices required');if(job?.proof?.gate!=='STAY')errors.push('Mode-188 gate must be STAY');if(Number(job?.proof?.mode188_score)<1.05)errors.push('Mode-188 score below 1.05');if(Number(job?.proof?.contradiction??1)>=0.75)errors.push('contradiction must remain below 0.75');return{ok:errors.length===0,errors}}

export class OmegaRuntime extends OmegaRuntimeR33 {
 async fullwaveWorkers(){const rows=await this.get('fullwaveWorkers',[]),t=now();return rows.map(x=>({...x,online:t-Number(x.lastSeen||0)<30000}))}
 async fullwaveState(){const jobs=await this.get('fullwaveJobs',[]),workers=await this.fullwaveWorkers();const counts={queued:0,running:0,complete:0,held:0,failed:0};for(const j of jobs){if(j.status==='QUEUED')counts.queued++;else if(j.status==='RUNNING')counts.running++;else if(j.status==='COMPLETE')counts.complete++;else if(j.status?.startsWith('HELD'))counts.held++;else if(j.status==='FAILED')counts.failed++}return{schema:'OMEGA_FULLWAVE_RUNTIME_R34',workers,counts,totalJobs:jobs.length,lastJobs:jobs.slice(-20).map(j=>({id:j.id,source_packet_id:j.source_packet_id,status:j.status,solver:j.solver,targetWorkerId:j.targetWorkerId,queuedAt:j.queuedAt,completedAt:j.completedAt,resultSha256:j.result?.result_sha256||null}))}}
 async federationState(){const hybrid=await this.state(),rcwa=await this.fullwaveState(),bridgeCreatedAt=await this.get('bridgeCreatedAt',null),continuity=await this.get('continuitySnapshot',null),proofTimes=[...(hybrid.devices||[]).map(x=>Number(x.lastSeen)||0),...(rcwa.workers||[]).map(x=>Number(x.lastSeen)||0)].filter(Boolean);return{schema:'OMEGA_FEDERATION_RUNTIME_R97',hybrid,rcwa,pairing:{paired:Boolean(hybrid.paired),createdAt:bridgeCreatedAt,lastAuthenticatedProof:proofTimes.length?Math.max(...proofTimes):null,historicalProofPresent:proofTimes.length>0},continuity:continuity?{savedAt:continuity.savedAt,projectCount:continuity.projects?.length||0,activeProjectId:continuity.activeProjectId||null,receiptSha256:continuity.receiptSha256||null,state:'DURABLE'}:{savedAt:null,projectCount:0,activeProjectId:null,receiptSha256:null,state:'EMPTY'}}}
 async fetch(request){const u=new URL(request.url),path=u.pathname;
  if(path==='/federation/state'&&request.method==='GET')return json({ok:true,...await this.federationState()});
  if(path==='/continuity'&&request.method==='GET'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const snapshot=await this.get('continuitySnapshot',null);return json({ok:true,snapshot,persistence:'DURABLE_OBJECT',authority:'AUTHENTICATED_BRIDGE'});}
  if(path==='/continuity'&&request.method==='PUT'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),projects=(Array.isArray(b.projects)?b.projects:[]).slice(-80).map(continuityProject).filter(Boolean),activeProjectId=safeId(b.activeProjectId),savedAt=now(),core={schema:'OMEGA_CONTINUITY_SNAPSHOT_R97',projects,activeProjectId:projects.some(x=>x.id===activeProjectId)?activeProjectId:null,savedAt,sourceSavedAt:clamp(b.sourceSavedAt,0,Number.MAX_SAFE_INTEGER),authority:'AUTHENTICATED_DURABLE_RUNTIME'};const snapshot={...core,receiptSha256:await sha256(core)};await this.put('continuitySnapshot',snapshot);await this.event('CONTINUITY_SNAPSHOT_SAVED',`Saved ${projects.length} durable project continuity record${projects.length===1?'':'s'}.`,{projectCount:projects.length,receiptSha256:snapshot.receiptSha256});return json({ok:true,snapshot,persistence:'DURABLE_OBJECT'});}
  if(path==='/fullwave/register'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.workerId);if(!id)return json({ok:false,code:'WORKER_ID_REQUIRED'},400);let rows=await this.get('fullwaveWorkers',[]);const row={id,name:text(b.name||'OMEGA Sovereign RCWA').slice(0,120),version:text(b.version||'unknown').slice(0,80),platform:text(b.platform||'unknown').slice(0,160),capabilities:['rcwa'],solverBackend:text(b.solverBackend||'grcwa').slice(0,80),workerSha256:text(b.workerSha256).slice(0,80),lastSeen:now(),revoked:false};rows=[...rows.filter(x=>x.id!==id),row].slice(-12);await this.put('fullwaveWorkers',rows);await this.event('FULLWAVE_WORKER_REGISTERED',`${row.name} registered for RCWA queue work.`,{workerId:id,version:row.version});return json({ok:true,worker:row})}
  if(path==='/fullwave/heartbeat'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.workerId);let rows=await this.get('fullwaveWorkers',[]),found=false;rows=rows.map(x=>x.id===id?(found=true,{...x,lastSeen:now(),version:text(b.version||x.version)}):x);if(!found)return json({ok:false,code:'FULLWAVE_WORKER_NOT_REGISTERED'},404);await this.put('fullwaveWorkers',rows);return json({ok:true,at:now()})}
  if(path==='/fullwave/poll'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),id=safeId(b.workerId);const workers=await this.fullwaveWorkers(),worker=workers.find(x=>x.id===id&&x.online&&!x.revoked);if(!worker)return json({ok:false,code:'FULLWAVE_WORKER_OFFLINE'},503);let jobs=await this.get('fullwaveJobs',[]),job=jobs.find(x=>x.status==='QUEUED'&&x.targetWorkerId===id);if(job){jobs=jobs.map(x=>x.id===job.id?({...x,status:'RUNNING',startedAt:now()}):x);job=jobs.find(x=>x.id===job.id);await this.put('fullwaveJobs',jobs);await this.event('FULLWAVE_JOB_CLAIMED',`RCWA job ${job.id} claimed.`,{jobId:job.id,workerId:id})}return json({ok:true,job:job||null})}
  if(path==='/fullwave/result'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const b=await request.json().catch(()=>({})),workerId=safeId(b.workerId),jobId=safeId(b.jobId),result=b.result;let jobs=await this.get('fullwaveJobs',[]),target=jobs.find(x=>x.id===jobId&&x.targetWorkerId===workerId);if(!target)return json({ok:false,code:'FULLWAVE_JOB_NOT_FOUND'},404);const valid=result?.schema==='OMEGA_RESULT_v1'&&result?.worker==='omega-sovereign'&&result?.solver==='rcwa'&&result?.source_packet_id===target.source_packet_id&&typeof result?.converged==='boolean'&&result?.convergence_metrics&&result?.observables;const status=!valid?'FAILED':result.converged?'COMPLETE':'HELD_NOT_CONVERGED';jobs=jobs.map(x=>x.id===jobId?({...x,status,completedAt:now(),result:valid?result:null,workerLog:text(b.log).slice(-12000),resultValidation:valid?'SCHEMA_AND_LINEAGE_PASS':'RESULT_SCHEMA_OR_LINEAGE_FAILED'}):x);await this.put('fullwaveJobs',jobs);await this.event('FULLWAVE_JOB_RETURNED',`RCWA job ${jobId} returned ${status}.`,{jobId,workerId,status,resultSha256:valid?result.result_sha256||null:null});return json({ok:valid,job:jobs.find(x=>x.id===jobId)},valid?200:400)}
  if(path==='/fullwave/queue'&&request.method==='POST'){if(!await this.authorized(request))return json({ok:false,code:'DEVICE_PROOF_REQUIRED',reply:'Authenticated Hybrid pairing is required before full-wave work can queue.'},503);const b=await request.json().catch(()=>({})),job=b.job||b,targetWorkerId=safeId(b.targetWorkerId||job.targetWorkerId),v=validateFullwaveJob(job);if(!v.ok)return json({ok:false,code:'FULLWAVE_JOB_REJECTED',errors:v.errors},400);const workers=await this.fullwaveWorkers(),worker=workers.find(x=>x.id===targetWorkerId&&x.online&&!x.revoked);if(!worker)return json({ok:false,code:'FULLWAVE_WORKER_REQUIRED',reply:'A proving Sovereign RCWA worker must be online before this job can queue.'},503);let jobs=await this.get('fullwaveJobs',[]);const fingerprint=await sha256({source_packet_id:job.source_packet_id,geometry:job.geometry,wavelength_nm:job.wavelength_nm,polarization:job.polarization,material_model:job.material_model,numerics:job.numerics});const duplicate=jobs.find(x=>x.inputFingerprint===fingerprint&&['QUEUED','RUNNING','COMPLETE'].includes(x.status));if(duplicate)return json({ok:true,deduplicated:true,job:duplicate});const row={...job,id:'fw_'+now().toString(36)+'_'+fingerprint.slice(0,10),job_id:job.job_id||('fw_'+fingerprint.slice(0,20)),targetWorkerId,status:'QUEUED',queuedAt:now(),inputFingerprint:fingerprint,priority:clamp(job.priority??.5,0,1),lineage:[...(job.lineage||[]),'omega-v6:fullwave-queue:R34']};jobs.push(row);jobs.sort((a,b)=>Number(b.priority||0)-Number(a.priority||0)||Number(a.queuedAt)-Number(b.queuedAt));await this.put('fullwaveJobs',jobs.slice(-240));await this.event('FULLWAVE_JOB_QUEUED',`Proof-admissible RCWA job ${row.id} queued.`,{jobId:row.id,sourcePacketId:row.source_packet_id,workerId:targetWorkerId,inputFingerprint:fingerprint});return json({ok:true,deduplicated:false,job:row})}
  if(path==='/fullwave/state'&&request.method==='GET')return json({ok:true,...await this.fullwaveState()});
  if(path.startsWith('/fullwave/result/')&&request.method==='GET'){if(!await this.authorized(request))return json({ok:false,code:'PAIR_AUTH_FAILED'},401);const source=safeId(decodeURIComponent(path.slice('/fullwave/result/'.length))),jobs=await this.get('fullwaveJobs',[]),job=[...jobs].reverse().find(x=>x.source_packet_id===source);if(!job)return json({ok:false,code:'FULLWAVE_RESULT_NOT_FOUND'},404);return json({ok:true,job})}
  return super.fetch(request)
 }
}

async function serveAsset(request,env,assetPath,filename,marker,kind){if(!env?.ASSETS?.fetch)return json({ok:false,code:'ASSET_BINDING_UNAVAILABLE'},503);const asset=await env.ASSETS.fetch(new Request(new URL(assetPath,request.url),{headers:{'cache-control':'no-cache'}}));if(!asset.ok)return json({ok:false,code:'ASSET_NOT_FOUND',assetPath,status:asset.status},503);const source=await asset.text();if(source.length<500||!source.includes(marker))return json({ok:false,code:'ASSET_INVALID',assetPath},503);const digest=await sha256(source);return new Response(source,{status:200,headers:{'content-type':'text/x-python; charset=utf-8','content-disposition':`attachment; filename="${filename}"`,'cache-control':'no-store, max-age=0',[`x-omega-${kind}-sha256`]:digest,'x-omega-canonical-origin':'https://omegav6.jeffdeweyeljefe.workers.dev'}})}

async function fetchR34(request,env){const u=new URL(request.url),path=u.pathname;
 if(path.startsWith('/api/federation/')&&request.method==='OPTIONS')return preflight(request);
 if(path==='/api/federation/rcwa/agent-download'&&request.method==='GET')return withCors(await serveAsset(request,env,'/omega-rcwa-agent.py','omega-rcwa-agent.py','OMEGA Sovereign RCWA transport agent','rcwa-agent'),request);
 if(path==='/api/federation/rcwa/worker-download'&&request.method==='GET')return withCors(await serveAsset(request,env,'/omega-rcwa-worker.py','omega-rcwa-worker.py','OMEGA Sovereign RCWA Worker R3','rcwa-worker'),request);
 if(path==='/api/federation/capabilities'&&request.method==='GET'){if(!env?.ASSETS?.fetch)return withCors(json({ok:false,code:'ASSET_BINDING_UNAVAILABLE'},503),request);return withCors(await env.ASSETS.fetch(new Request(new URL('/omega-capabilities.json',request.url),{headers:{'cache-control':'no-cache'}})),request)}
 if(path==='/api/federation/run/status'&&request.method==='GET'){if(!env?.OMEGA_RUNTIME)return withCors(json({ok:false,code:'DURABLE_RUNTIME_UNAVAILABLE'},503),request);const id=bridgeId(request);if(!id)return withCors(json({ok:false,code:'BRIDGE_ID_REQUIRED'},400),request);const opticalHeaders={};if(env.OMEGA_OPTICAL_SERVICE_TOKEN){opticalHeaders.authorization=`Bearer ${env.OMEGA_OPTICAL_SERVICE_TOKEN}`;opticalHeaders['x-omega-federation-token']=env.OMEGA_OPTICAL_SERVICE_TOKEN}if(env.OMEGA_OPTICAL_BYPASS_TOKEN)opticalHeaders['x-vercel-protection-bypass']=env.OMEGA_OPTICAL_BYPASS_TOKEN;const [runtimeResponse,genesis,optical]=await Promise.all([runtimeFetch(env,id,'/federation/state',request),probeGenesis(env),probeJsonService(env.OMEGA_OPTICAL_HEALTH_URL||'https://omega-optical-cloud-woven2.vercel.app/api/health',opticalHeaders)]);const runtime=await runtimeResponse.json().catch(()=>null);return withCors(json({ok:Boolean(runtime?.ok),schema:'OMEGA_FEDERATION_RUN_STATUS_R97',checkedAt:now(),nodes:{omegaV6:{state:'LIVE',canonicalOrigin:'https://omegav6.jeffdeweyeljefe.workers.dev',runtime:'CLOUDFLARE_WORKER'},genesis,optical,sovereign:{state:(runtime?.hybrid?.devices||[]).some(x=>x.online&&!x.revoked)?'PC_ONLINE':runtime?.pairing?.historicalProofPresent?'PREVIOUSLY_PAIRED_OFFLINE':runtime?.pairing?.paired?'PAIRED_AWAITING_HEARTBEAT':'PAIRING_REQUIRED',rcwaState:(runtime?.rcwa?.workers||[]).some(x=>x.online&&!x.revoked)?'RCWA_ONLINE':(runtime?.rcwa?.workers||[]).length?'RCWA_PREVIOUSLY_SEEN_OFFLINE':'RCWA_NOT_STARTED'}},runtime:runtime||null,truthBoundary:'LIVE means a current JSON health or authenticated heartbeat. PREVIOUSLY_PAIRED_OFFLINE preserves historical proof without claiming the PC is online. Optical ACCESS_GATED means the protected site did not expose a machine-readable health response to this Worker.'}),request)}
 if(path==='/api/federation/continuity'&&(request.method==='GET'||request.method==='PUT')){if(!env?.OMEGA_RUNTIME)return withCors(json({ok:false,code:'DURABLE_RUNTIME_UNAVAILABLE'},503),request);const id=bridgeId(request);if(!id)return withCors(json({ok:false,code:'BRIDGE_ID_REQUIRED'},400),request);const body=request.method==='PUT'?await request.json().catch(()=>({})):undefined;return withCors(await runtimeFetch(env,id,'/continuity',request,body),request)}
 if(path.startsWith('/api/federation/rcwa/')){if(!env?.OMEGA_RUNTIME)return withCors(json({ok:false,code:'DURABLE_RUNTIME_UNAVAILABLE'},503),request);const id=bridgeId(request);if(!id)return withCors(json({ok:false,code:'BRIDGE_ID_REQUIRED'},400),request);const map={register:'/fullwave/register',heartbeat:'/fullwave/heartbeat',poll:'/fullwave/poll',result:'/fullwave/result',queue:'/fullwave/queue',status:'/fullwave/state'};const suffix=path.slice('/api/federation/rcwa/'.length);if(suffix.startsWith('result/'))return withCors(await runtimeFetch(env,id,'/fullwave/result/'+encodeURIComponent(suffix.slice(7)),request),request);const internal=map[suffix];if(!internal)return withCors(json({ok:false,code:'FEDERATION_ROUTE_NOT_FOUND'},404),request);const body=request.method==='POST'?await request.json().catch(()=>({})):undefined;return withCors(await runtimeFetch(env,id,internal,request,body),request)}
 return r33.fetch(request,env)
}

export default{fetch:fetchR34};
