import baseWorker from './worker.js';

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
const text=v=>String(v??'').trim();
async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function fetchJson(url){const started=Date.now();try{const r=await fetch(url,{headers:{'accept':'application/json','user-agent':'OMEGAv6/1.0'},cf:{cacheTtl:0,cacheEverything:false}}),raw=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);return{ok:true,data:JSON.parse(raw),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:url}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:url}}}
function haversineKm(aLat,aLon,bLat,bLon){const R=6371.0088,toRad=x=>x*Math.PI/180,dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),s=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(s)))}
const NOAA_COVERAGES=Object.freeze({
 'G19-CONUS':{label:'GOES-19 CONUS',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/CONUS/GEOCOLOR/latest.jpg'},
 'G19-FD':{label:'GOES-19 Full Disk',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/FD/GEOCOLOR/latest.jpg'},
 'G18-FD':{label:'GOES-18 Full Disk',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/FD/GEOCOLOR/latest.jpg'},
 'G19-CAR':{label:'GOES-19 Caribbean',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/car/GEOCOLOR/latest.jpg'},
 'G19-CAM':{label:'GOES-19 Central America',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/cam/GEOCOLOR/latest.jpg'},
 'G19-TAW':{label:'GOES-19 Tropical Atlantic',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/taw/GEOCOLOR/latest.jpg'},
 'G19-CAN':{label:'GOES-19 Canada / N. U.S.',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/can/GEOCOLOR/latest.jpg'},
 'G18-WUS':{label:'GOES-18 U.S. Pacific Coast',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/SECTOR/wus/GEOCOLOR/latest.jpg'},
 'G18-TPW':{label:'GOES-18 Tropical Pacific',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/SECTOR/tpw/GEOCOLOR/latest.jpg'}
});
async function noaaCatalog(){const rows=[];for(const [id,c] of Object.entries(NOAA_COVERAGES)){let state='UNVERIFIED',lastModified=null,contentType=null;try{const r=await fetch(c.url,{method:'HEAD',cf:{cacheTtl:0,cacheEverything:false}});contentType=r.headers.get('content-type');lastModified=r.headers.get('last-modified');state=r.ok&&String(contentType||'').startsWith('image/')?'CURRENT_VERIFIED_LATEST_ALIAS':'UNAVAILABLE'}catch{}rows.push({id,...c,state,lastModified,contentType,truth:'LATEST_ALIAS_DIRECT_IMAGE'});}return{schema:'OMEGA_EARTH_NOAA_CATALOG_V1',verifiedAt:new Date().toISOString(),coverages:rows,truthBoundary:'CURRENT_VERIFIED_LATEST_ALIAS means the first-party image alias answered as an image during this request. It is not an immutable historical filename.'}}
async function earthEvidence(url){const lat=clamp(Number(url.searchParams.get('lat')||0),-90,90),lon=clamp(Number(url.searchParams.get('lon')||0),-180,180);
 const weatherUrl=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,cloud_cover&timezone=UTC`;
 const [eq,eonet,kp,weather]=await Promise.all([
  fetchJson('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson'),
  fetchJson('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=100'),
  fetchJson('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json'),
  fetchJson(weatherUrl)
 ]);
 let eqSummary={count:null,maxMagnitude:null,nearest:null};if(eq.ok){const features=Array.isArray(eq.data?.features)?eq.data.features:[],usable=features.map(f=>({mag:Number(f?.properties?.mag),place:f?.properties?.place||'unknown',time:f?.properties?.time?new Date(f.properties.time).toISOString():null,lat:Number(f?.geometry?.coordinates?.[1]),lon:Number(f?.geometry?.coordinates?.[0])})).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));const nearest=usable.sort((a,b)=>haversineKm(lat,lon,a.lat,a.lon)-haversineKm(lat,lon,b.lat,b.lon))[0];eqSummary={count:usable.length,maxMagnitude:usable.reduce((m,x)=>Number.isFinite(x.mag)?Math.max(m,x.mag):m,0),nearest:nearest?{...nearest,distanceKm:Number(haversineKm(lat,lon,nearest.lat,nearest.lon).toFixed(1))}:null}}
 let eonetSummary={count:null,categories:[],nearest:null};if(eonet.ok){const events=Array.isArray(eonet.data?.events)?eonet.data.events:[],cats=[...new Set(events.flatMap(e=>(e.categories||[]).map(c=>c.title)).filter(Boolean))];const points=[];for(const e of events){for(const g of e.geometry||[]){if(g?.type==='Point'&&Array.isArray(g.coordinates)){const lo=Number(g.coordinates[0]),la=Number(g.coordinates[1]);if(Number.isFinite(la)&&Number.isFinite(lo))points.push({title:e.title||'event',category:e.categories?.[0]?.title||'event',date:g.date||null,lat:la,lon:lo,distanceKm:haversineKm(lat,lon,la,lo)})}}}points.sort((a,b)=>a.distanceKm-b.distanceKm);eonetSummary={count:events.length,categories:cats,nearest:points[0]?{...points[0],distanceKm:Number(points[0].distanceKm.toFixed(1))}:null}}
 let kpSummary={kp:null,observationTime:null};if(kp.ok&&Array.isArray(kp.data)){const rows=kp.data.slice(1).filter(r=>Array.isArray(r)&&r.length>=2),last=rows.at(-1);if(last){kpSummary={observationTime:last[0]||null,kp:Number(last[1])}}}
 const w=weather.ok?weather.data?.current:null,weatherSummary=w?{time:w.time??null,temperatureC:Number(w.temperature_2m),windKph:Number(w.wind_speed_10m),cloudPct:Number(w.cloud_cover)}:{temperatureC:null,windKph:null,cloudPct:null,time:null};
 const normalized={quake:Math.min(1,Number(eqSummary.maxMagnitude||0)/8),kp:Math.min(1,Number(kpSummary.kp||0)/9),wind:Math.min(1,Number(weatherSummary.windKph||0)/120),events:Math.min(1,Number(eonetSummary.count||0)/100)},contextIndex=Number(((normalized.quake+normalized.kp+normalized.wind+normalized.events)/4).toFixed(4));
 const sources={usgs:{ok:eq.ok,verifiedAt:eq.verifiedAt,source:eq.source},eonet:{ok:eonet.ok,verifiedAt:eonet.verifiedAt,source:eonet.source},swpc:{ok:kp.ok,verifiedAt:kp.verifiedAt,source:kp.source},openMeteo:{ok:weather.ok,verifiedAt:weather.verifiedAt,source:weather.source}};
 const payload={schema:'OMEGA_EARTH_EVIDENCE_V1',target:{lat,lon,crs:'WGS84 / EPSG:4326'},verifiedAt:new Date().toISOString(),seismic:eqSummary,naturalEvents:eonetSummary,spaceWeather:kpSummary,localConditions:weatherSummary,derivedContext:{index:contextIndex,components:normalized,truth:'DERIVED_DISPLAY_CONTEXT_ONLY'},sources,truthBoundary:'External values are returned-source evidence or unavailable. The context index is a normalized display summary, not empirical proof, not a physical law, not a forecast, and never mutates canonical OMEGA state.'};payload.evidenceHash=await sha256(payload);return payload}

const HYBRID_OPERATIONS=Object.freeze(['INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','SAFE_IMPORT','WORKBOOK_AUDIT','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','OPEN_URL','WAIT','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO','TRAIN_LOCAL']);
const HYBRID_PROFILES=Object.freeze(['AUTO_BUILD','NODE_BUILD','PYTHON_TEST','DOTNET_BUILD']);
function classifyHybridDraft(prompt){const t=text(prompt).toLowerCase(),ops=[];if(/index|scan|project|folder|root/.test(t))ops.push({op:'INDEX'});if(/search|find/.test(t))ops.push({op:'SEARCH_TEXT'});if(/hash|fingerprint/.test(t))ops.push({op:'HASH_TREE'});if(/workbook|excel|xlsx|csv/.test(t))ops.push({op:'WORKBOOK_AUDIT'});if(/patch|repair|fix|edit/.test(t))ops.push({op:'APPLY_PATCH'});if(/build|compile/.test(t))ops.push({op:'BUILD',profile:'AUTO_BUILD'});if(/test|qa|verify/.test(t))ops.push({op:'TEST',profile:'AUTO_BUILD'});if(/package|zip|installer/.test(t))ops.push({op:'PACKAGE'});if(/train|learning|learn locally/.test(t))ops.push({op:'TRAIN_LOCAL'});if(/open (?:url|site|browser)|https?:/.test(t))ops.push({op:'OPEN_URL'});if(/click/.test(t))ops.push({op:'CLICK'});if(/type|enter text/.test(t))ops.push({op:'TYPE_TEXT'});if(/macro.*record|record.*macro/.test(t))ops.push({op:'RECORD_MACRO'});if(/macro.*replay|replay.*macro/.test(t))ops.push({op:'REPLAY_MACRO'});if(!ops.length)ops.push({op:'INDEX'},{op:'HASH_TREE'});return ops.slice(0,24).map((x,i)=>({step:i+1,...x}))}
async function hybridDraft(body){const prompt=text(body?.prompt||body?.text),root=text(body?.root||'.')||'.',requested=classifyHybridDraft(prompt),broadRoot=root==='.'||root==='';let operations=requested;if(broadRoot&&operations.some(x=>x.op==='BUILD'||x.op==='TEST'))operations=[{step:1,op:'INDEX'},{step:2,op:'HASH_TREE'},...operations.filter(x=>x.op!=='BUILD'&&x.op!=='TEST').map((x,i)=>({...x,step:i+3}))];const draft={schema:'OMEGA_HYBRID_DRAFT_V3',state:'DRAFT_ONLY_NOT_QUEUED',prompt,root,operations,confirmed:false,deviceId:null,limits:{steps:24,sourceFiles:25000,sourceBytes:2147483648,generatedBytes:536870912,changedFiles:80,missionCycles:[2,8]},truthBoundary:'Draft generation cannot pair a device, queue work, mutate HostState, bypass confirmation, execute a shell, read passwords, cross the approved root, or claim native execution.'};draft.fingerprint=await sha256(draft);return draft}
function validateHybridPlan(body){const plan=body?.plan||body,errors=[];if(!Array.isArray(plan?.operations)||plan.operations.length<1||plan.operations.length>24)errors.push('operations must contain 1-24 steps');for(const [i,row] of (plan?.operations||[]).entries()){if(!HYBRID_OPERATIONS.includes(row?.op))errors.push(`step ${i+1}: unsupported operation ${row?.op}`);if(row?.profile&&!HYBRID_PROFILES.includes(row.profile))errors.push(`step ${i+1}: unsupported build/test profile`);if(row?.path&&(String(row.path).startsWith('/')||/^[A-Za-z]:[\\/]/.test(String(row.path))||String(row.path).includes('..')))errors.push(`step ${i+1}: path must remain root-relative`);if(row?.url&&!String(row.url).startsWith('https://'))errors.push(`step ${i+1}: URL must use HTTPS`)}return{schema:'OMEGA_HYBRID_PLAN_VALIDATION_V1',valid:errors.length===0,errors,operationRegistry:HYBRID_OPERATIONS,profiles:HYBRID_PROFILES,execution:'DEVICE_PROOF_REQUIRED'}}

async function omegaR8(request,env){const url=new URL(request.url);
 if(url.pathname==='/api/earth/evidence'&&request.method==='GET')return json(await earthEvidence(url));
 if(url.pathname==='/api/earth/noaa/catalog'&&request.method==='GET')return json(await noaaCatalog());
 if(url.pathname==='/api/earth/noaa/image'&&request.method==='GET'){const id=text(url.searchParams.get('coverage')),c=NOAA_COVERAGES[id];if(!c)return json({ok:false,code:'UNKNOWN_COVERAGE'},404);try{const r=await fetch(c.url,{cf:{cacheTtl:60,cacheEverything:false}});const ct=r.headers.get('content-type')||'';if(!r.ok||!ct.startsWith('image/'))return json({ok:false,code:'NOAA_IMAGE_UNAVAILABLE',coverage:id,status:r.status},502);return new Response(r.body,{status:200,headers:{'content-type':ct,'cache-control':'public, max-age=60','x-omega-source':'NOAA-STAR-LATEST-ALIAS','x-omega-last-modified':r.headers.get('last-modified')||''}})}catch(e){return json({ok:false,code:'NOAA_IMAGE_FETCH_FAILED',error:e instanceof Error?e.message:String(e)},502)}}
 if(url.pathname==='/api/hybrid/capabilities'&&request.method==='GET')return json({ok:true,schema:'OMEGA_HYBRID_V90_MIGRATION_CONTRACT_V1',state:'CLOUD_DRAFT_AND_VALIDATION_LIVE_NATIVE_EXECUTION_DEVICE_PROOF_REQUIRED',operations:HYBRID_OPERATIONS,profiles:HYBRID_PROFILES,missionCycles:{min:2,max:8},workspaceGovernor:{sourceFiles:25000,sourceBytes:2147483648,generatedBytes:536870912,changedFiles:80},trainLocal:{operation:'TRAIN_LOCAL',foundationWeightsChanged:false,requiredProof:'OMEGA_SAI_LOCAL_TRAINING_RECEIPT_V1 + active model fingerprint'},boundaries:['NO_ARBITRARY_SHELL','ROOT_CONFINED','EXPLICIT_CONFIRMATION_REQUIRED','NO_PASSWORD_CAPTURE','NO_UAC_OR_SECURE_DESKTOP','HOSTSTATE_NOT_MUTATED_BY_DRAFT']});
 if(url.pathname==='/api/hybrid/plan'&&request.method==='POST'){const body=await request.json().catch(()=>({}));return json({ok:true,draft:await hybridDraft(body)})}
 if(url.pathname==='/api/hybrid/validate'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const result=validateHybridPlan(body);return json({ok:result.valid,...result},result.valid?200:400)}
 return baseWorker.fetch(request,env)
}
export default{fetch:omegaR8};
