import r114,{OmegaRuntime as OmegaRuntimeR114} from './workerR114.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-runtime-successor':'R115'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const text=v=>String(v??'').trim();
const now=()=>Date.now();
const safeId=(v,fallback='')=>{const s=text(v).slice(0,180);return /^[A-Za-z0-9._:-]+$/.test(s)?s:fallback};
const bridgeId=(request,body={})=>safeId(request.headers.get('x-omega-bridge-id')||body?.bridgeId||request.headers.get('x-omega-session-id'),'r115_federation_observer');
const runtimeStub=(env,id)=>env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(id));
async function runtimeFetch(env,id,path,request,method='GET',body){const headers=new Headers(request.headers);headers.set('content-type','application/json');const init={method,headers};if(body!==undefined&&method!=='GET')init.body=JSON.stringify(body);return runtimeStub(env,id).fetch(new Request('https://omega-runtime.internal'+path,init))}
function packetCandidate(body){return body?.packet||body?.proposal||body?.screened_packet||body?.result||body}
function validProposal(packet){return packet?.schema==='OMEGA_PACKET_v1'&&packet?.source_node==='omega-genesis'&&Boolean(safeId(packet?.packet_id))&&Boolean(safeId(packet?.state_id))&&packet?.geometry&&Number(packet?.wavelength_nm)>0&&Array.isArray(packet?.lineage)}
function validScreen(packet){return packet?.schema==='OMEGA_PACKET_v1'&&packet?.source_node==='omega-optical'&&Boolean(safeId(packet?.packet_id))&&packet?.geometry&&Number(packet?.wavelength_nm)>0&&packet?.scalar_metrics&&packet?.proof&&Array.isArray(packet?.lineage)}
function validJob(job,screen){return job?.schema==='OMEGA_FULLWAVE_QUEUE_v1'&&String(job?.solver).toLowerCase()==='rcwa'&&job?.source_packet_id===screen?.packet_id&&job?.proof?.gate==='STAY'&&Number(job?.proof?.mode188_score)>=1.05&&job?.material_model&&['n_incident','n_feature','n_background','n_substrate'].every(k=>Number.isFinite(Number(job.material_model[k]))&&Number(job.material_model[k])>0)}
async function machineCall(binding,url,payload){const started=now();if(!binding?.fetch)return{ok:false,state:'BINDING_MISSING',httpStatus:0,latencyMs:0,body:null};try{const response=await binding.fetch(new Request(url,{method:'POST',headers:{'content-type':'application/json','accept':'application/json','cache-control':'no-cache'},body:JSON.stringify(payload)})),raw=await response.text();let body=null;try{body=JSON.parse(raw)}catch{}return{ok:response.ok&&Boolean(body),state:response.ok?'RETURNED':'UNAVAILABLE',httpStatus:response.status,latencyMs:now()-started,body}}catch(error){return{ok:false,state:'UNREACHABLE',httpStatus:0,latencyMs:now()-started,error:text(error instanceof Error?error.message:error).slice(0,220),body:null}}}
async function machineHealth(binding,url,label){const started=now();if(!binding?.fetch)return{state:'BINDING_MISSING',service:label,httpStatus:0,latencyMs:0,jsonVerified:false};try{const response=await binding.fetch(new Request(url,{headers:{accept:'application/json','cache-control':'no-cache'}})),body=await response.json().catch(()=>null);return{state:response.ok&&body?.ok===true?'LIVE':'DEGRADED',service:body?.service||label,version:body?.version||null,httpStatus:response.status,latencyMs:now()-started,jsonVerified:Boolean(body&&typeof body==='object'),authority:body?.authority||null}}catch(error){return{state:'UNREACHABLE',service:label,httpStatus:0,latencyMs:now()-started,jsonVerified:false,error:text(error instanceof Error?error.message:error).slice(0,180)}}}
async function orchestrateStrictR115(request,env){const body=await request.json().catch(()=>({})),id=bridgeId(request,body),intent=text(body.intent||body.text).slice(0,4000);if(!intent)return json({ok:false,code:'INTENT_REQUIRED'},400);if(!env.OMEGA_GENESIS_MACHINE?.fetch||!env.OMEGA_OPTICAL_MACHINE?.fetch)return r114.fetch(new Request(request.url,{method:'POST',headers:request.headers,body:JSON.stringify(body)}),env);let response=await runtimeFetch(env,id,'/ceremony/start',request,'POST',{bridgeId:id,intent,kind:'STRICT_FULL_FEDERATION'}),opened=await response.clone().json().catch(()=>null);if(!response.ok)return response;const run=opened.run;
 const genesis=await machineCall(env.OMEGA_GENESIS_MACHINE,'https://omega-genesis-machine-r115.internal/api/federation/propose',{schema:'OMEGA_FEDERATION_PROPOSE_REQUEST_R115',ceremony_id:run.ceremonyId,intent,canonical_authority:'omega-v6',worker_authority:'PROPOSE',expected_output:'OMEGA_PACKET_v1'}),proposal=packetCandidate(genesis.body);if(!genesis.ok||!validProposal(proposal)){await runtimeFetch(env,id,'/ceremony/block',request,'POST',{ceremonyId:run.ceremonyId,stage:'PROPOSE',code:'GENESIS_MACHINE_PROPOSAL_REQUIRED',observation:{state:genesis.state,httpStatus:genesis.httpStatus,latencyMs:genesis.latencyMs,transport:'CLOUDFLARE_SERVICE_BINDING_R115'}});return runtimeFetch(env,id,'/ceremony/status',request,'GET')}
 response=await runtimeFetch(env,id,'/ceremony/proposal/service',request,'POST',{ceremonyId:run.ceremonyId,proposal,observation:{state:'RETURNED',httpStatus:genesis.httpStatus,latencyMs:genesis.latencyMs,transport:'CLOUDFLARE_SERVICE_BINDING_R115',service:'omega-genesis-machine-r115'}});if(!response.ok)return response;
 const optical=await machineCall(env.OMEGA_OPTICAL_MACHINE,'https://omega-optical-machine-r115.internal/api/federation/screen',{schema:'OMEGA_FEDERATION_SCREEN_REQUEST_R115',ceremony_id:run.ceremonyId,proposal,worker_authority:'SCREEN',expected_output:['OMEGA_PACKET_v1','OMEGA_FULLWAVE_QUEUE_v1']}),screen=packetCandidate(optical.body),job=optical.body?.tier2_job||optical.body?.queue_job||optical.body?.job||null;if(!optical.ok||!validScreen(screen)){await runtimeFetch(env,id,'/ceremony/block',request,'POST',{ceremonyId:run.ceremonyId,stage:'SCREEN',code:'OPTICAL_MACHINE_SCREEN_REQUIRED',observation:{state:optical.state,httpStatus:optical.httpStatus,latencyMs:optical.latencyMs,transport:'CLOUDFLARE_SERVICE_BINDING_R115'}});return runtimeFetch(env,id,'/ceremony/status',request,'GET')}
 response=await runtimeFetch(env,id,'/ceremony/screen/service',request,'POST',{ceremonyId:run.ceremonyId,screen,job:validJob(job,screen)?job:null,observation:{state:'RETURNED',httpStatus:optical.httpStatus,latencyMs:optical.latencyMs,transport:'CLOUDFLARE_SERVICE_BINDING_R115',service:'omega-optical-machine-r115',screeningEngine:screen.screening_engine||null}});if(!response.ok)return response;if(!validJob(job,screen)){await runtimeFetch(env,id,'/ceremony/block',request,'POST',{ceremonyId:run.ceremonyId,stage:'SCREEN',code:'R115_TIER2_JOB_NOT_ADMISSIBLE',observation:{gate:screen?.proof?.gate||null,mode188_score:screen?.proof?.mode188_score??null,contradiction:screen?.proof?.contradiction??null,requested_solver:screen?.requested_solver||null}});return runtimeFetch(env,id,'/ceremony/status',request,'GET')}
 response=await runtimeFetch(env,id,'/ceremony/queue',request,'POST',{ceremonyId:run.ceremonyId,job});return response.ok?runtimeFetch(env,id,'/ceremony/status',request,'GET'):response}
async function machineStatusR115(env){const [genesis,optical]=await Promise.all([machineHealth(env.OMEGA_GENESIS_MACHINE,'https://omega-genesis-machine-r115.internal/api/health','omega-genesis-machine-r115'),machineHealth(env.OMEGA_OPTICAL_MACHINE,'https://omega-optical-machine-r115.internal/api/health','omega-optical-machine-r115')]);return{ok:genesis.state==='LIVE'&&optical.state==='LIVE',schema:'OMEGA_FEDERATION_MACHINE_STATUS_R115',runtimeRevision:'R115',canonicalAuthority:'omega-v6',nodes:{genesis,optical},truthBoundary:'R115 machine adapters implement the existing PROPOSE and SCREEN roles only. They do not create additional federation authorities, claim Sovereign execution, or mutate CanonState.'}}
async function fetchR115(request,env){const path=new URL(request.url).pathname;if(path==='/api/federation/machine/status'&&request.method==='GET')return json(await machineStatusR115(env));if(path==='/api/federation/ceremony/start'&&request.method==='POST')return orchestrateStrictR115(request,env);const response=await r114.fetch(request,env),headers=new Headers(response.headers);headers.set('x-omega-runtime-successor','R115');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
export class OmegaRuntime extends OmegaRuntimeR114 {}
export default{async fetch(request,env){return fetchR115(request,env)}};
