import r32,{OmegaRuntime as OmegaRuntimeR32} from './workerR32.js';
import {WORKERS_AI_MODEL} from './worker.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const text=v=>String(v??'').trim();
const now=()=>Date.now();
const safeId=(v,fallback='anonymous')=>{const s=text(v).slice(0,128);return /^[A-Za-z0-9._:-]+$/.test(s)?s:fallback};
const relativePath=v=>{const s=text(v||'.').replace(/\\/g,'/');if(!s||s==='.')return'.';if(s.startsWith('/')||/^[A-Za-z]:/.test(s)||s.split('/').includes('..')||s.includes('\0'))return null;return s.split('/').filter(Boolean).join('/')||'.'};
const intent=prompt=>{const p=String(prompt).toLowerCase();return{execution:/\b(build|repair|fix|patch|test|package|zip|train|index|search|read|audit|open|click|type|macro|desktop|pc|hybrid|execute|run|operate)\b/.test(p),train:/\b(train|learning|learn locally)\b/.test(p),build:/\b(build|compile)\b/.test(p),test:/\b(test|qa|verify)\b/.test(p),repair:/\b(repair|fix|patch|edit)\b/.test(p),package:/\b(package|zip|installer)\b/.test(p),audit:/\b(audit|inspect|scan|index|workspace)\b/.test(p),browser:/\b(open|browser|click|type|macro)\b/.test(p)}};
function parseProjectPath(prompt){const m=String(prompt).match(/(?:project|root|folder|path)\s*(?:=|:|at|is)?\s*["'`](.+?)["'`]/i);return relativePath(m?.[1]||'.')||'.'}
function allowedDomains(prompt){const out=[];for(const m of String(prompt).matchAll(/https:\/\/([A-Za-z0-9.-]+)(?:[:/]|$)/g)){const host=m[1].toLowerCase();if(!out.includes(host))out.push(host)}return out.slice(0,12)}
function safePlan(prompt){const i=intent(prompt),projectPath=parseProjectPath(prompt),domains=allowedDomains(prompt),steps=[];const add=(op,label,extra={})=>steps.push({id:'S'+String(steps.length+1).padStart(2,'0'),op,label,...extra});if(i.train){add('TRAIN_LOCAL','Rebuild the private local SAI retrieval corpus and return an evaluation receipt',{path:projectPath,maxResults:25000});return{projectPath,allowedDomains:domains,steps}}if(i.browser&&domains.length){const url=String(prompt).match(/https:\/\/[^\s"')]+/i)?.[0];if(url)add('OPEN_URL','Open the explicitly approved HTTPS destination',{url});add('ASSERT_WINDOW','Lock the visible browser window before interaction',{windowTitle:'Browser'});return{projectPath,allowedDomains:domains,steps}}add('INDEX','Discover real project manifests and working files',{path:projectPath});add('HASH_TREE','Fingerprint the approved source tree before action',{path:projectPath,maxResults:5000});if(projectPath!=='.'){if(i.repair)add('SEARCH_TEXT','Locate evidence-bearing repair targets',{path:projectPath,query:'TODO FIXME error failed',maxResults:120});if(i.build||i.repair)add('BUILD','Run the declared project build',{path:projectPath,profile:'AUTO_BUILD'});if(i.test||i.build||i.repair)add('TEST','Run the declared project verification',{path:projectPath,profile:'AUTO_BUILD'});if(i.package)add('PACKAGE','Package the verified project output',{path:projectPath})}return{projectPath,allowedDomains:domains,steps:steps.slice(0,24)}}
function modelText(result){if(!result)return'';if(typeof result==='string')return result;if(typeof result.response==='string')return result.response;if(typeof result.result?.response==='string')return result.result.response;const c=result.choices?.[0]?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>typeof x==='string'?x:(x?.text||'')).join('\n').trim();return''}
function sessionId(request){return safeId(request.headers.get('x-omega-session-id'),'anon')}
function runtimeStub(env,id){return env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(id))}
async function runtimeFetch(env,id,path,method='GET',body,sourceHeaders){const headers=new Headers(sourceHeaders||{});headers.set('content-type','application/json');const init={method,headers};if(body!==undefined&&method!=='GET')init.body=JSON.stringify(body);return runtimeStub(env,id).fetch(new Request('https://omega-runtime.internal'+path,init))}
async function aiReply(env,prompt,stateContext,execution,thread){if(!env.AI)return execution?'The deterministic action compiler is available, but the synthesis provider is unavailable.':'The durable OMEGA memory is live, but synthesis is temporarily unavailable.';try{const history=(thread?.messages||[]).slice(-12).flatMap(row=>[{role:'user',content:String(row.prompt||'').slice(0,5000)},{role:'assistant',content:String(row.assistantMessage||'').slice(0,5000)}]);const system=`You are OMEGA's synthesis layer inside a durable enacted runtime. Be concise, operational, and continuity-aware. Use the supplied durable history as prior project context, not as new authority. Separate source/runtime evidence from interpretation. Never claim a PC action occurred unless a host proof packet exists. The deterministic compiler, not you, chooses executable operations. Current turn execution intent: ${execution}.`;const messages=[{role:'system',content:system},...history,{role:'user',content:`CURRENT STATE\n${JSON.stringify(stateContext||{})}\n\nCURRENT REQUEST\n${prompt}`}];const result=await env.AI.run(WORKERS_AI_MODEL,{messages,max_tokens:1100,temperature:.22,chat_template_kwargs:{enable_thinking:false}});return modelText(result)||'OMEGA synthesis returned no text; the runtime did not invent a replacement.'}catch(e){return `OMEGA synthesis is degraded (${e instanceof Error?e.message:String(e)}). Durable memory and governed execution remain available.`}}

export class OmegaRuntime extends OmegaRuntimeR32 {
 async state(){const base=await super.state(),thread=await this.get('thread',null);return{...base,schema:'OMEGA_LIVING_RUNTIME_R33',thread:thread?{id:thread.id,turnCount:thread.turnCount||0,memoryTurns:(thread.messages||[]).length,updatedAt:thread.updatedAt}:null}}
 async fetch(request){const u=new URL(request.url),path=u.pathname;
  if(path==='/thread'&&request.method==='GET'){const thread=await this.get('thread',null);return json({ok:true,thread,persistence:'DURABLE_MESSAGE_MEMORY',routeBeforeGeneration:true,memoryTurns:thread?.messages?.length||0})}
  if(path==='/turn'&&request.method==='POST'){const b=await request.json().catch(()=>({})),prompt=text(b.prompt).slice(0,16000),assistantMessage=text(b.assistantMessage).slice(0,24000),execution=Boolean(b.execution),plan=b.plan&&typeof b.plan==='object'?b.plan:null,old=await this.get('thread',null),messages=Array.isArray(old?.messages)?old.messages:[],row={id:'turn_'+now().toString(36),at:now(),kind:execution?'ACTION':'CONVERSATION',prompt,assistantMessage,requiresExecution:execution,plan:execution&&plan?{projectPath:relativePath(plan.projectPath)||'.',allowedDomains:Array.isArray(plan.allowedDomains)?plan.allowedDomains.slice(0,12):[],steps:Array.isArray(plan.steps)?plan.steps.slice(0,24):[]}:null};messages.push(row);const trimmed=messages.slice(-48),thread={id:old?.id||('thr_'+now().toString(36)),turnCount:Number(old?.turnCount||0)+1,updatedAt:now(),createdAt:old?.createdAt||now(),messages:trimmed,retention:{policy:'LAST_48_DURABLE_TURNS',dropped:Math.max(0,Number(old?.retention?.dropped||0)+messages.length-trimmed.length)}};await this.put('thread',thread);await this.event(execution?'AI_ACTION_PREPARED':'AI_CONVERSATION',execution?'SAI stored a governed action turn in durable project memory.':'SAI stored a conversational turn in durable project memory.',{threadId:thread.id,memoryTurns:trimmed.length});return json({ok:true,thread,turn:{...row,nextPromptHint:execution?'Review the visible action sequence, then approve it against a proved paired host.':'Continue the same durable project thread.'},draft:execution&&plan?{schema:'OMEGA_GOVERNED_ACTION_DRAFT_R33',state:'DRAFT_NOT_QUEUED',...row.plan}:null})}
  if(path==='/agent/result'&&request.method==='POST'){const response=await super.fetch(request);if(!response.ok)return response;const returned=await response.clone().json().catch(()=>({})),job=returned.job;if(!job)return response;let missions=await this.get('missions',[]),changed=false;missions=missions.map(m=>{if(m.currentJobId!==job.id)return m;changed=true;const history=[...(m.cycles||[]),{cycle:m.cycle,jobId:job.id,status:job.status,resultFingerprint:job.returnPacket?.resultFingerprint||null,completedAt:job.completedAt||now()}].slice(-8);const complete=job.status==='COMPLETE';return{...m,currentJob:job,cycles:history,status:complete?'COMPLETE':'HOLD_REPAIR_REQUIRED',completedAt:complete?now():undefined,heldAt:complete?undefined:now(),needsReview:!complete,lastProof:job.returnPacket||null}});if(changed){await this.put('missions',missions);const mission=missions.find(m=>m.currentJobId===job.id);await this.event(mission?.status==='COMPLETE'?'MISSION_COMPLETE':'MISSION_HELD',mission?.status==='COMPLETE'?`Mission ${mission.id} completed from returned host proof.`:`Mission ${mission.id} held on failed host proof; no blind retry was queued.`,{missionId:mission?.id,jobId:job.id,status:mission?.status,resultFingerprint:job.returnPacket?.resultFingerprint||null});return json({...returned,mission})}return response}
  return super.fetch(request)
 }
}

const CANONICAL_ORIGIN_R94='https://omegav6.jeffdeweyeljefe.workers.dev';
async function sha256TextR96(source){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(source));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hybridAgentDownloadR94(request,env){
 if(!env?.ASSETS?.fetch)return json({ok:false,code:'HYBRID_AGENT_ASSET_BINDING_UNAVAILABLE'},503);
 const assetUrl=new URL('/omega-hybrid-agent.py',CANONICAL_ORIGIN_R94);
 const asset=await env.ASSETS.fetch(new Request(assetUrl,{headers:{'cache-control':'no-cache'}}));
 if(!asset.ok)return json({ok:false,code:'HYBRID_AGENT_ASSET_NOT_FOUND',status:asset.status},503);
 const source=await asset.text();
 const valid=source.length>1000&&source.startsWith('#!/usr/bin/env python3')&&source.includes("DEFAULT_SERVER='https://omegav6.jeffdeweyeljefe.workers.dev'")&&source.includes("OMEGA Hybrid Link agent");
 if(!valid)return json({ok:false,code:'HYBRID_AGENT_ASSET_INVALID'},503);
 const version=(source.match(/VERSION='([^']+)'/)||[])[1]||'UNKNOWN',digest=await sha256TextR96(source);
 return new Response(source,{status:200,headers:{
  'content-type':'text/x-python; charset=utf-8',
  'content-disposition':'attachment; filename="omega-hybrid-agent.py"',
  'cache-control':'no-store, max-age=0',
  'x-omega-agent-version':version,
  'x-omega-agent-sha256':digest,
  'x-omega-canonical-origin':CANONICAL_ORIGIN_R94
 }});
}

async function fetchR33(request,env){const url=new URL(request.url),path=url.pathname;if(path==='/api/hybrid/agent-download'&&request.method==='GET')return hybridAgentDownloadR94(request,env);if(!env.OMEGA_RUNTIME)return r32.fetch(request,env);const sid=sessionId(request);
 if(path==='/api/orchestrator/turn'&&request.method==='POST'){const b=await request.json().catch(()=>({})),prompt=text(b.prompt).slice(0,16000),execution=intent(prompt).execution,plan=safePlan(prompt),priorResponse=await runtimeFetch(env,sid,'/thread','GET',undefined,request.headers),prior=await priorResponse.json().catch(()=>({})),assistantMessage=await aiReply(env,prompt,b.stateContext,execution,prior.thread),turnResponse=await runtimeFetch(env,sid,'/turn','POST',{...b,prompt,assistantMessage,execution,plan},request.headers),data=await turnResponse.json();return json(data,turnResponse.status)}
 if(path==='/api/hybrid/status'&&request.method==='GET'){const statusResponse=await runtimeFetch(env,sid,'/status','GET',undefined,request.headers),data=await statusResponse.json().catch(()=>({})),online=Array.isArray(data.devices)?data.devices.filter(x=>x?.online&&!x?.revoked):[],internalState=data.state||'PAIRING_REQUIRED';return json({...data,state:online.length?'VERIFIED_DEVICE_ONLINE':'DEVICE_PROOF_REQUIRED',pairingState:internalState,nativeExecutionClaimed:online.length>0,truthBoundary:'PUBLIC_DEVICE_PROOF_GATE_R33B'},statusResponse.status)}
 if(path==='/api/status'&&request.method==='GET'){const base=await r32.fetch(request.clone(),env),ct=base.headers.get('content-type')||'';if(!ct.includes('application/json'))return base;const data=await base.json().catch(()=>null);if(!data)return base;const snapshot=await runtimeFetch(env,sid,'/snapshot','GET',undefined,request.headers),rt=await snapshot.json().catch(()=>({}));return json({...data,enactedRuntime:{...(data.enactedRuntime||{}),state:'LIVING_DURABLE_R33',durableMemoryTurns:rt.thread?.memoryTurns||0,activeJobs:rt.activeJobs||0,lastEvent:rt.lastEvent||null}})}
 return r32.fetch(request,env)
}
export default{fetch:fetchR33};
