import r8 from './workerR8.js';

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
const txt=v=>String(v??'').trim();
async function hash(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getJson(url,headers={}){const started=Date.now();try{const r=await fetch(url,{headers:{accept:'application/json','user-agent':'OMEGAv6/1.0 (+bounded Earth evidence)',...headers},cf:{cacheTtl:0,cacheEverything:false}}),raw=await r.text();if(!r.ok)throw Error(`HTTP ${r.status}`);return{ok:true,data:JSON.parse(raw),source:url,verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e),source:url,verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started}}}
function nearestKarta(raw,lat,lon){const lists=[raw?.result?.data,raw?.result,raw?.data,raw?.photos,raw?.result?.photos].filter(Array.isArray);const rows=(lists[0]||[]).map(x=>{const d=x?.data||x,la=Number(d?.lat??d?.latitude??d?.matchLat),lo=Number(d?.lng??d?.lon??d?.longitude??d?.matchLng);return{raw:d,lat:la,lon:lo}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));const dist=(a,b,c,d)=>{const R=6371008.8,p=Math.PI/180,q1=a*p,q2=c*p,dq=(c-a)*p,dl=(d-b)*p,s=Math.sin(dq/2)**2+Math.cos(q1)*Math.cos(q2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(s)))};rows.sort((a,b)=>dist(lat,lon,a.lat,a.lon)-dist(lat,lon,b.lat,b.lon));const x=rows[0];if(!x)return null;const d=x.raw,id=d?.id??d?.photoId??d?.sequenceIndex??null,file=d?.fileurlProc??d?.fileurlLTh??d?.fileurlTh??d?.fileUrl??d?.imageUrl??null;return{id,lat:x.lat,lon:x.lon,distanceM:Number(dist(lat,lon,x.lat,x.lon).toFixed(1)),shotDate:d?.shotDate??d?.date??null,heading:Number.isFinite(Number(d?.heading))?Number(d.heading):null,sequenceId:d?.sequenceId??d?.sequence?.id??null,projection:d?.projection??null,imageUrl:typeof file==='string'&&/^https:/.test(file)?file:null,truth:'RETURNED_KARTAVIEW_METADATA'}}
function epqsElevation(raw){const candidates=[raw?.value,raw?.elevation,raw?.USGS_Elevation_Point_Query_Service?.Elevation_Query?.Elevation,raw?.USGS_Elevation_Point_Query_Service?.Elevation_Query?.Elevation_Data_Source].filter(v=>v!==undefined);const n=Number(candidates.find(v=>Number.isFinite(Number(v))));return Number.isFinite(n)?n:null}
function osmSummary(raw){const rows=Array.isArray(raw?.elements)?raw.elements:[],roads=rows.filter(x=>x.tags?.highway),buildings=rows.filter(x=>x.tags?.building),places=rows.filter(x=>x.tags?.place);return{elements:rows.length,roadElements:roads.length,buildingElements:buildings.length,placeElements:places.length,roadNames:[...new Set(roads.map(x=>x.tags?.name).filter(Boolean))].slice(0,20),placeNames:[...new Set(places.map(x=>x.tags?.name).filter(Boolean))].slice(0,12)}}
async function groundEvidence(url){const lat=clamp(Number(url.searchParams.get('lat')||0),-90,90),lon=clamp(Number(url.searchParams.get('lon')||0),-180,180),radius=clamp(Number(url.searchParams.get('radius')||750),100,2000);
 const kartaUrl=`https://api.openstreetcam.org/2.0/photo/?lat=${lat}&lng=${lon}&radius=${radius}&join=sequence&orderBy=id&orderDirection=desc`;
 const epqsUrl=`https://epqs.nationalmap.gov/v1/json?x=${lon}&y=${lat}&wkid=4326&units=Meters&includeDate=false`;
 const reverseUrl=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=18&addressdetails=1`;
 const q=`[out:json][timeout:12];(way(around:${Math.round(radius)},${lat},${lon})[highway];way(around:${Math.round(radius)},${lat},${lon})[building];node(around:${Math.round(radius)},${lat},${lon})[place];);out tags center 300;`;
 const overpassUrl=`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`;
 const [karta,epqs,reverse,osm]=await Promise.all([getJson(kartaUrl),getJson(epqsUrl),getJson(reverseUrl),getJson(overpassUrl)]);
 const address=reverse.ok?{displayName:reverse.data?.display_name||null,road:reverse.data?.address?.road||reverse.data?.address?.pedestrian||null,neighbourhood:reverse.data?.address?.neighbourhood||reverse.data?.address?.suburb||null,city:reverse.data?.address?.city||reverse.data?.address?.town||reverse.data?.address?.village||null,state:reverse.data?.address?.state||null,country:reverse.data?.address?.country||null,countryCode:reverse.data?.address?.country_code||null}:null;
 const elevation=epqs.ok?epqsElevation(epqs.data):null,kartaPhoto=karta.ok?nearestKarta(karta.data,lat,lon):null,osmContext=osm.ok?osmSummary(osm.data):null;
 const payload={schema:'OMEGA_EARTH_GROUND_EVIDENCE_V1',target:{lat,lon,radiusM:radius,crs:'WGS84 / EPSG:4326'},verifiedAt:new Date().toISOString(),levels:{EARTH:{state:'WGS84_TARGET'},REGION:{state:address?'RETURNED_OSM_REVERSE':'UNAVAILABLE',address},CITY:{state:address?.city?'RETURNED_OSM_REVERSE':'UNAVAILABLE',name:address?.city||null},STREET:{state:kartaPhoto?'RETURNED_KARTAVIEW_PHOTO':'UNAVAILABLE',photo:kartaPhoto,road:address?.road||null},GROUND:{state:elevation!==null?'RETURNED_USGS_ELEVATION':'UNAVAILABLE',elevationM:elevation,osm:osmContext}},sources:{kartaView:{ok:karta.ok,source:karta.source,verifiedAt:karta.verifiedAt,error:karta.error||null},usgsEpqs:{ok:epqs.ok,source:epqs.source,verifiedAt:epqs.verifiedAt,error:epqs.error||null},osmReverse:{ok:reverse.ok,source:reverse.source,verifiedAt:reverse.verifiedAt,error:reverse.error||null},osmOverpass:{ok:osm.ok,source:osm.source,verifiedAt:osm.verifiedAt,error:osm.error||null}},truthBoundary:'Earth→Region→City→Street→Ground is a navigation/evidence hierarchy. Street imagery is shown only when KartaView returned an actual geotagged image. Elevation is shown only when USGS EPQS returned a numeric value. Missing ground evidence is never generated or inferred.'};payload.evidenceHash=await hash(payload);return payload}
function gibsDate(value){const m=txt(value).match(/^\d{4}-\d{2}-\d{2}$/);if(m)return m[0];const d=new Date(Date.now()-86400000);return d.toISOString().slice(0,10)}
async function gibsImage(url){const lat=clamp(Number(url.searchParams.get('lat')||0),-90,90),lon=clamp(Number(url.searchParams.get('lon')||0),-180,180),date=gibsDate(url.searchParams.get('date')),span=clamp(Number(url.searchParams.get('span')||4),.25,20),width=Math.round(clamp(Number(url.searchParams.get('width')||900),256,1400)),height=Math.round(clamp(Number(url.searchParams.get('height')||600),256,1000));
 const minLon=Math.max(-180,lon-span),maxLon=Math.min(180,lon+span),minLat=Math.max(-90,lat-span*.65),maxLat=Math.min(90,lat+span*.65);
 const params=new URLSearchParams({SERVICE:'WMS',REQUEST:'GetMap',VERSION:'1.1.1',LAYERS:'VIIRS_SNPP_CorrectedReflectance_TrueColor',STYLES:'',FORMAT:'image/jpeg',TRANSPARENT:'FALSE',SRS:'EPSG:4326',BBOX:`${minLon},${minLat},${maxLon},${maxLat}`,WIDTH:String(width),HEIGHT:String(height),TIME:date});
 const source=`https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?${params}`;try{const r=await fetch(source,{cf:{cacheTtl:300,cacheEverything:false}}),ct=r.headers.get('content-type')||'';if(!r.ok||!ct.startsWith('image/'))return json({ok:false,code:'GIBS_IMAGE_UNAVAILABLE',date,status:r.status,contentType:ct,truth:'NO_SYNTHETIC_SUBSTITUTE'},502);return new Response(r.body,{status:200,headers:{'content-type':ct,'cache-control':'public,max-age=300','x-omega-source':'NASA-GIBS-VIIRS-SNPP-TRUECOLOR','x-omega-date':date,'x-omega-crs':'EPSG:4326'}})}catch(e){return json({ok:false,code:'GIBS_FETCH_FAILED',date,error:e instanceof Error?e.message:String(e),truth:'NO_SYNTHETIC_SUBSTITUTE'},502)}}
async function fetchR9(request,env){const url=new URL(request.url);if(url.pathname==='/api/earth/ground/evidence'&&request.method==='GET')return json(await groundEvidence(url));if(url.pathname==='/api/earth/gibs/image'&&request.method==='GET')return gibsImage(url);return r8.fetch(request,env)}
export default{fetch:fetchR9};
