import baseWorker from './worker.js';
import {sarCatalogR285} from './sarLiveCatalogR285.js';
import {sarAssetProbeR325} from './sarAssetProbeR325.js';
import {sarNativeRasterR326} from './sarNativeRasterR326.js';
import {sarMeasurementRasterR337} from './sarMeasurementRasterR337.js';
import {sarAnnotationR343} from './sarAnnotationR343.js';

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
const text=v=>String(v??'').trim();
async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const EXTERNAL_JSON_TIMEOUT_MS=8000;
async function fetchJson(url,timeoutMs=EXTERNAL_JSON_TIMEOUT_MS){const started=Date.now();let timer;try{const pending=fetch(url,{headers:{'accept':'application/json','user-agent':'OMEGAv6/1.0'},cf:{cacheTtl:0,cacheEverything:false},signal:AbortSignal.timeout(timeoutMs)}).then(async r=>({r,raw:await r.text()})),deadline=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`PROVIDER_DEADLINE_${timeoutMs}MS`)),timeoutMs)}),{r,raw}=await Promise.race([pending,deadline]);if(!r.ok)throw new Error(`HTTP ${r.status}`);return{ok:true,data:JSON.parse(raw),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:url}}catch(e){return{ok:false,error:e instanceof Error?e.message:String(e),verifiedAt:new Date().toISOString(),latencyMs:Date.now()-started,source:url}}finally{clearTimeout(timer)}}
async function fetchPrimaryWeatherJson(url){const attempts=[];for(let attempt=1;attempt<=2;attempt++){const result=await fetchJson(url);attempts.push({attempt,ok:result.ok,verifiedAt:result.verifiedAt,latencyMs:result.latencyMs,error:result.error||null});if(result.ok)return{...result,attemptCount:attempts.length,retried:attempts.length>1,attempts};if(attempt<2)await new Promise(resolve=>setTimeout(resolve,250))}const last=attempts.at(-1);return{ok:false,error:last?.error||'PRIMARY_FORECAST_UNAVAILABLE',verifiedAt:last?.verifiedAt||new Date().toISOString(),latencyMs:attempts.reduce((sum,row)=>sum+Number(row.latencyMs||0),0),source:url,attemptCount:attempts.length,retried:attempts.length>1,attempts}}
function haversineKm(aLat,aLon,bLat,bLon){const R=6371.0088,toRad=x=>x*Math.PI/180,dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),s=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(s)))}
const NOAA_COVERAGES=Object.freeze({
 'G19-CONUS':{label:'GOES-19 CONUS',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/CONUS/GEOCOLOR/latest.jpg'},
 'G19-FD':{label:'GOES-19 Full Disk',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/FD/GEOCOLOR/latest.jpg'},
 'G18-FD':{label:'GOES-18 Full Disk',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/FD/GEOCOLOR/latest.jpg'},
 'G19-CAR':{label:'GOES-19 Caribbean',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/car/GEOCOLOR/latest.jpg'},
 'G19-CAM':{label:'GOES-19 Central America',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/cam/GEOCOLOR/latest.jpg'},
 'G19-TAW':{label:'GOES-19 Tropical Atlantic',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/taw/GEOCOLOR/latest.jpg'},
 'G19-CAN':{label:'GOES-19 Canada / N. U.S.',url:'https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/can/GEOCOLOR/latest.jpg'},
 'G18-WUS':{label:'GOES-18 U.S. Pacific Coast',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/SECTOR/wus/GEOCOLOR/latest.jpg'},
 'G18-TPW':{label:'GOES-18 Tropical Pacific',url:'https://cdn.star.nesdis.noaa.gov/GOES18/ABI/SECTOR/tpw/GEOCOLOR/latest.jpg'}
});
async function noaaCatalog(){const rows=[];for(const [id,c] of Object.entries(NOAA_COVERAGES)){let state='UNVERIFIED',lastModified=null,contentType=null;try{const r=await fetch(c.url,{method:'HEAD',cf:{cacheTtl:0,cacheEverything:false}});contentType=r.headers.get('content-type');lastModified=r.headers.get('last-modified');state=r.ok&&String(contentType||'').startsWith('image/')?'CURRENT_VERIFIED_LATEST_ALIAS':'UNAVAILABLE'}catch{}rows.push({id,...c,state,lastModified,contentType,truth:'LATEST_ALIAS_DIRECT_IMAGE'});}return{schema:'OMEGA_EARTH_NOAA_CATALOG_V1',verifiedAt:new Date().toISOString(),coverages:rows,truthBoundary:'CURRENT_VERIFIED_LATEST_ALIAS means the first-party image alias answered as an image during this request. It is not an immutable historical filename.'}}
async function earthEvidence(url){const lat=clamp(Number(url.searchParams.get('lat')||0),-90,90),lon=clamp(Number(url.searchParams.get('lon')||0),-180,180);
 const weatherUrl=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m,cloud_cover&timezone=UTC`;
 const [eq,eonet,kp,weather]=await Promise.all([
  fetchJson('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson'),
  fetchJson('https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=100'),
  fetchJson('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json'),
  fetchJson(weatherUrl)
 ]);
 let eqSummary={count:null,maxMagnitude:null,nearest:null};if(eq.ok){const features=Array.isArray(eq.data?.features)?eq.data.features:[],usable=features.map(f=>({mag:Number(f?.properties?.mag),place:f?.properties?.place||'unknown',time:f?.properties?.time?new Date(f.properties.time).toISOString():null,lat:Number(f?.geometry?.coordinates?.[1]),lon:Number(f?.geometry?.coordinates?.[0])})).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));const nearest=usable.sort((a,b)=>haversineKm(lat,lon,a.lat,a.lon)-haversineKm(lat,lon,b.lat,b.lon))[0];eqSummary={count:usable.length,maxMagnitude:usable.reduce((m,x)=>Number.isFinite(x.mag)?Math.max(m,x.mag):m,0),nearest:nearest?{...nearest,distanceKm:Number(haversineKm(lat,lon,nearest.lat,nearest.lon).toFixed(1))}:null}}
 let eonetSummary={count:null,categories:[],nearest:null};if(eonet.ok){const events=Array.isArray(eonet.data?.events)?eonet.data.events:[],cats=[...new Set(events.flatMap(e=>(e.categories||[]).map(c=>c.title)).filter(Boolean))];const points=[];for(const e of events){for(const g of e.geometry||[]){if(g?.type==='Point'&&Array.isArray(g.coordinates)){const lo=Number(g.coordinates[0]),la=Number(g.coordinates[1]);if(Number.isFinite(la)&&Number.isFinite(lo))points.push({title:e.title||'event',category:e.categories?.[0]?.title||'event',date:g.date||null,lat:la,lon:lo,distanceKm:haversineKm(lat,lon,la,lo)})}}}points.sort((a,b)=>a.distanceKm-b.distanceKm);eonetSummary={count:events.length,categories:cats,nearest:points[0]?{...points[0],distanceKm:Number(points[0].distanceKm.toFixed(1))}:null}}
 let kpSummary={kp:null,observationTime:null};if(kp.ok&&Array.isArray(kp.data)){const rows=kp.data.slice(1).filter(r=>Array.isArray(r)&&r.length>=2),last=rows.at(-1);if(last){kpSummary={observationTime:last[0]||null,kp:Number(last[1])}}}
 const w=weather.ok?weather.data?.current:null,weatherSummary=w?{time:w.time??null,temperatureC:Number(w.temperature_2m),windKph:Number(w.wind_speed_10m),cloudPct:Number(w.cloud_cover)}:{temperatureC:null,windKph:null,cloudPct:null,time:null};
 const normalized={quake:Math.min(1,Number(eqSummary.maxMagnitude||0)/8),kp:Math.min(1,Number(kpSummary.kp||0)/9),wind:Math.min(1,Number(weatherSummary.windKph||0)/120),events:Math.min(1,Number(eonetSummary.count||0)/100)},contextIndex=Number(((normalized.quake+normalized.kp+normalized.wind+normalized.events)/4).toFixed(4));
 const sources={usgs:{ok:eq.ok,verifiedAt:eq.verifiedAt,source:eq.source},eonet:{ok:eonet.ok,verifiedAt:eonet.verifiedAt,source:eonet.source},swpc:{ok:kp.ok,verifiedAt:kp.verifiedAt,source:kp.source},openMeteo:{ok:weather.ok,verifiedAt:weather.verifiedAt,source:weather.source}};
 const payload={schema:'OMEGA_EARTH_EVIDENCE_V1',target:{lat,lon,crs:'WGS84 / EPSG:4326'},verifiedAt:new Date().toISOString(),seismic:eqSummary,naturalEvents:eonetSummary,spaceWeather:kpSummary,localConditions:weatherSummary,derivedContext:{index:contextIndex,components:normalized,truth:'DERIVED_DISPLAY_CONTEXT_ONLY'},sources,truthBoundary:'External values are returned-source evidence or unavailable. The context index is a normalized display summary, not empirical proof, not a physical law, not a forecast, and never mutates canonical OMEGA state.'};payload.evidenceHash=await sha256(payload);return payload}

const metric=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const mean=values=>{const rows=values.filter(Number.isFinite);return rows.length?rows.reduce((a,b)=>a+b,0)/rows.length:null};
function localForecastEpoch(value,offsetSeconds=0,noon=false){const s=String(value||'');if(!s)return NaN;const stamp=s.length===10?s+(noon?'T12:00:00Z':'T00:00:00Z'):s.length===16?s+':00Z':s.endsWith('Z')?s:s+'Z';const raw=Date.parse(stamp);return Number.isFinite(raw)?raw-Number(offsetSeconds||0)*1000:NaN}
function sourceContinuity(row,prev){if(!prev)return 1;const parts=[];const add=(a,b,scale)=>{if(Number.isFinite(a)&&Number.isFinite(b))parts.push(Math.min(1,Math.abs(a-b)/scale))};add(row.temperatureC,prev.temperatureC,6);add(row.surfacePressureHpa,prev.surfacePressureHpa,10);add(row.windKph,prev.windKph,35);add(row.precipProbabilityPct,prev.precipProbabilityPct,65);if(Number.isFinite(row.windDirectionDeg)&&Number.isFinite(prev.windDirectionDeg)){const d=Math.abs(row.windDirectionDeg-prev.windDirectionDeg)%360;parts.push(Math.min(1,Math.min(d,360-d)/150))}return Number((1-(mean(parts)??0)).toFixed(4))}
function parseNwsWindKph(value){const m=String(value||'').match(/(\d+(?:\.\d+)?)(?:\s+to\s+(\d+(?:\.\d+)?))?\s*mph/i);if(!m)return null;return Number(((Number(m[2]||m[1]))*1.609344).toFixed(2))}
async function nwsHourlyContext(lat,lon){const points=await fetchJson('https://api.weather.gov/points/'+lat.toFixed(4)+','+lon.toFixed(4));if(!points.ok)return{ok:false,error:points.error||'NWS point lookup unavailable',source:points.source};const p=points.data?.properties||{},hourlyUrl=p.forecastHourly;if(!hourlyUrl)return{ok:false,error:'NWS hourly forecast URL unavailable',source:points.source};const hourly=await fetchJson(hourlyUrl);if(!hourly.ok)return{ok:false,error:hourly.error||'NWS hourly forecast unavailable',source:hourly.source,office:p.cwa||null};const periods=Array.isArray(hourly.data?.properties?.periods)?hourly.data.properties.periods.map(x=>{const t=metric(x?.temperature),unit=String(x?.temperatureUnit||'F').toUpperCase();return{startTime:x?.startTime||null,temperatureC:t===null?null:Number((unit==='F'?(t-32)*5/9:t).toFixed(2)),windKph:parseNwsWindKph(x?.windSpeed),precipProbabilityPct:metric(x?.probabilityOfPrecipitation?.value),shortForecast:x?.shortForecast||null}}):[];return{ok:periods.length>0,office:p.cwa||null,gridId:p.gridId||null,gridX:p.gridX??null,gridY:p.gridY??null,source:hourly.source,verifiedAt:hourly.verifiedAt,periods}}
async function satelliteWeatherContext(lon){let id=null;if(lon>=-180&&lon<-105)id='G18-FD';else if(lon>=-105&&lon<=-20)id='G19-FD';if(!id)return{ok:false,id:null,label:null,source:null,error:'Target is outside the bounded GOES-18/19 weather-context footprint used by R375.',truth:'SATELLITE_CONTEXT_UNAVAILABLE_NO_SYNTHETIC_SUBSTITUTE'};const c=NOAA_COVERAGES[id];try{const r=await fetch(c.url,{method:'HEAD',cf:{cacheTtl:60,cacheEverything:false}}),lastModified=r.headers.get('last-modified'),ct=r.headers.get('content-type')||'',lastMs=Date.parse(lastModified||'');return{ok:r.ok&&ct.startsWith('image/'),id,label:c.label,source:c.url,lastModified:lastModified||null,ageMinutes:Number.isFinite(lastMs)?Number(Math.max(0,(Date.now()-lastMs)/60000).toFixed(1)):null,truth:'HEMISPHERIC_OBSERVATION_FRESHNESS_ONLY_NO_LOCAL_PIXEL_ASSIMILATION'}}catch(e){return{ok:false,id,label:c.label,source:c.url,error:e instanceof Error?e.message:String(e),truth:'SATELLITE_CONTEXT_UNAVAILABLE_NO_SYNTHETIC_SUBSTITUTE'}}}
function openMeteoNwsAgreement(hourly,nws,offsetSeconds){if(!nws?.ok||!Array.isArray(nws.periods))return{agreement:null,samples:0};const floor=Date.now()-60*60*1000,future=hourly.filter(row=>localForecastEpoch(row.time,offsetSeconds)>=floor).slice(0,24),scores=[];for(const row of future){const epoch=localForecastEpoch(row.time,offsetSeconds),match=nws.periods.map(x=>({x,d:Math.abs(Date.parse(x.startTime||'')-epoch)})).sort((a,b)=>a.d-b.d)[0];if(!match||!Number.isFinite(match.d)||match.d>45*60000)continue;const parts=[];const add=(a,b,scale)=>{if(Number.isFinite(a)&&Number.isFinite(b))parts.push(Math.min(1,Math.abs(a-b)/scale))};add(row.temperatureC,match.x.temperatureC,8);add(row.windKph,match.x.windKph,40);add(row.precipProbabilityPct,match.x.precipProbabilityPct,70);if(parts.length)scores.push(1-(mean(parts)??1))}return{agreement:scores.length?Number((mean(scores)??0).toFixed(4)):null,samples:scores.length}}
async function weatherForecast(url){const lat=clamp(Number(url.searchParams.get('lat')||0),-90,90),lon=clamp(Number(url.searchParams.get('lon')||0),-180,180);
 const hourlyVars='temperature_2m,apparent_temperature,relative_humidity_2m,precipitation_probability,precipitation,rain,showers,snowfall,weather_code,cloud_cover,visibility,wind_speed_10m,wind_gusts_10m,wind_direction_10m,surface_pressure';
 const dailyVars='weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,showers_sum,snowfall_sum,precipitation_hours,precipitation_probability_max,sunrise,sunset,daylight_duration,sunshine_duration,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant';
 const currentVars='temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,showers,snowfall,weather_code,cloud_cover,visibility,wind_speed_10m,wind_gusts_10m,wind_direction_10m,surface_pressure';
 const source='https://api.open-meteo.com/v1/forecast?latitude='+lat+'&longitude='+lon+'&current='+currentVars+'&hourly='+hourlyVars+'&daily='+dailyVars+'&forecast_days=8&timezone=auto';
 const [om,nws,satellite]=await Promise.all([fetchPrimaryWeatherJson(source),nwsHourlyContext(lat,lon),satelliteWeatherContext(lon)]);
 if(!om.ok)return{ok:false,schema:'OMEGA_EARTH_WEATHER_R375',state:'ERROR',target:{lat,lon,crs:'WGS84 / EPSG:4326'},error:om.error||'Primary forecast unavailable',sources:{openMeteo:om,nws},satellite,canonicalMutation:false,truthBoundary:'No forecast is fabricated when the primary returned forecast is unavailable.'};
 const h=om.data?.hourly||{},d=om.data?.daily||{},c=om.data?.current||{},offset=Number(om.data?.utc_offset_seconds||0);
 const times=Array.isArray(h.time)?h.time:[],hourly=times.map((time,i)=>({time,isoTime:Number.isFinite(localForecastEpoch(time,offset))?new Date(localForecastEpoch(time,offset)).toISOString():null,temperatureC:metric(h.temperature_2m?.[i]),apparentC:metric(h.apparent_temperature?.[i]),humidityPct:metric(h.relative_humidity_2m?.[i]),precipProbabilityPct:metric(h.precipitation_probability?.[i]),precipMm:metric(h.precipitation?.[i]),rainMm:metric(h.rain?.[i]),showersMm:metric(h.showers?.[i]),snowfallCm:metric(h.snowfall?.[i]),weatherCode:metric(h.weather_code?.[i]),cloudPct:metric(h.cloud_cover?.[i]),visibilityM:metric(h.visibility?.[i]),windKph:metric(h.wind_speed_10m?.[i]),gustKph:metric(h.wind_gusts_10m?.[i]),windDirectionDeg:metric(h.wind_direction_10m?.[i]),surfacePressureHpa:metric(h.surface_pressure?.[i])}));
 for(let i=0;i<hourly.length;i++)hourly[i].continuity=sourceContinuity(hourly[i],hourly[i-1]);
 const dates=Array.isArray(d.time)?d.time:[],daily=dates.map((date,i)=>({date,isoTime:Number.isFinite(localForecastEpoch(date,offset,true))?new Date(localForecastEpoch(date,offset,true)).toISOString():null,weatherCode:metric(d.weather_code?.[i]),tempMaxC:metric(d.temperature_2m_max?.[i]),tempMinC:metric(d.temperature_2m_min?.[i]),apparentMaxC:metric(d.apparent_temperature_max?.[i]),apparentMinC:metric(d.apparent_temperature_min?.[i]),precipitationMm:metric(d.precipitation_sum?.[i]),rainMm:metric(d.rain_sum?.[i]),showersMm:metric(d.showers_sum?.[i]),snowfallCm:metric(d.snowfall_sum?.[i]),precipitationHours:metric(d.precipitation_hours?.[i]),precipProbabilityMaxPct:metric(d.precipitation_probability_max?.[i]),sunrise:d.sunrise?.[i]||null,sunset:d.sunset?.[i]||null,daylightSeconds:metric(d.daylight_duration?.[i]),sunshineSeconds:metric(d.sunshine_duration?.[i]),windMaxKph:metric(d.wind_speed_10m_max?.[i]),gustMaxKph:metric(d.wind_gusts_10m_max?.[i]),windDirectionDeg:metric(d.wind_direction_10m_dominant?.[i])}));
 for(let i=0;i<daily.length;i++){const prev=daily[i-1];if(!prev){daily[i].transitionBurden=0;continue}const parts=[];const add=(a,b,scale)=>{if(Number.isFinite(a)&&Number.isFinite(b))parts.push(Math.min(1,Math.abs(a-b)/scale))};add(daily[i].tempMaxC,prev.tempMaxC,10);add(daily[i].tempMinC,prev.tempMinC,10);add(daily[i].precipProbabilityMaxPct,prev.precipProbabilityMaxPct,70);add(daily[i].windMaxKph,prev.windMaxKph,45);daily[i].transitionBurden=Number((mean(parts)??0).toFixed(4))}
 const current={time:c.time||null,isoTime:c.time&&Number.isFinite(localForecastEpoch(c.time,offset))?new Date(localForecastEpoch(c.time,offset)).toISOString():null,temperatureC:metric(c.temperature_2m),apparentC:metric(c.apparent_temperature),humidityPct:metric(c.relative_humidity_2m),precipMm:metric(c.precipitation),rainMm:metric(c.rain),showersMm:metric(c.showers),snowfallCm:metric(c.snowfall),weatherCode:metric(c.weather_code),cloudPct:metric(c.cloud_cover),visibilityM:metric(c.visibility),windKph:metric(c.wind_speed_10m),gustKph:metric(c.wind_gusts_10m),windDirectionDeg:metric(c.wind_direction_10m),surfacePressureHpa:metric(c.surface_pressure)};
 const forwardHourly=hourly.filter(row=>Number.isFinite(Date.parse(row.isoTime||''))&&Date.parse(row.isoTime)>=Date.now()-60*60*1000),agreement=openMeteoNwsAgreement(hourly,nws,offset),keys=['temperatureC','apparentC','humidityPct','precipProbabilityPct','windKph','surfacePressureHpa'],sample=(forwardHourly.length?forwardHourly:hourly).slice(0,48),expected=Math.max(1,sample.length*keys.length),present=sample.reduce((n,row)=>n+keys.filter(k=>Number.isFinite(row[k])).length,0),dataCompleteness=Number((present/expected).toFixed(4));
 const scars=[];if(!satellite.ok)scars.push({code:'SATELLITE_CONTEXT_UNAVAILABLE',detail:satellite.error||'Returned GOES freshness proof unavailable.'});if(!nws.ok)scars.push({code:'SECONDARY_FORECAST_UNAVAILABLE',detail:nws.error||'NWS cross-check unavailable outside supported U.S. forecast grids or during provider failure.'});if(agreement.agreement!==null&&agreement.agreement<.65)scars.push({code:'FORECAST_SOURCE_DISAGREEMENT',detail:'NWS and Open-Meteo differ materially across the next 24 hours; disagreement is retained rather than averaged away.'});if(dataCompleteness<.98)scars.push({code:'FORECAST_FIELD_GAPS',detail:'One or more returned hourly fields are missing and remain missing.'});
 const payload={ok:true,schema:'OMEGA_EARTH_WEATHER_R375',target:{lat,lon,crs:'WGS84 / EPSG:4326'},verifiedAt:new Date().toISOString(),timezone:om.data?.timezone||'UTC',timezoneAbbreviation:om.data?.timezone_abbreviation||null,utcOffsetSeconds:offset,elevationM:metric(om.data?.elevation),current,hourly,daily,satellite,quality:{dataCompleteness,sourceAgreement:agreement.agreement,agreementSamples:agreement.samples},derived:{continuityMean24h:Number((mean((forwardHourly.length?forwardHourly:hourly).slice(0,24).map(x=>x.continuity))??0).toFixed(4)),continuityMean7d:Number((mean(daily.slice(0,7).map(x=>1-Number(x.transitionBurden||0)))??0).toFixed(4)),dayToDayBurden:Number((mean(daily.slice(1,7).map(x=>Number(x.transitionBurden||0)))??0).toFixed(4)),truth:'RELATIONAL_FORECAST_STRUCTURE_ONLY_NOT_A_CALIBRATED_SKILL_SCORE'},scarLedger:scars,sources:{openMeteo:{ok:true,verifiedAt:om.verifiedAt,source:om.source,generationTimeMs:metric(om.data?.generationtime_ms),attemptCount:om.attemptCount||1,retried:om.retried===true,attempts:om.attempts||[]},nws:{ok:nws.ok,verifiedAt:nws.verifiedAt||null,source:nws.source||null,office:nws.office||null,gridId:nws.gridId||null,error:nws.error||null}},canonicalMutation:false,truthBoundary:'Returned meteorological values remain source evidence. GOES freshness is observation context, not local pixel assimilation. NWS comparison is cross-source agreement, not forecast skill probability. Woven continuity and transition burden are derived relational diagnostics and cannot overwrite source values or mutate CanonState.'};payload.evidenceHash=await sha256(payload);return payload}


const HYBRID_OPERATIONS=Object.freeze(['INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','SAFE_IMPORT','WORKBOOK_AUDIT','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','SAR_R344_CLOSURE','OPEN_URL','WAIT','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO','TRAIN_LOCAL']);
const HYBRID_PROFILES=Object.freeze(['AUTO_BUILD','NODE_BUILD','PYTHON_TEST','DOTNET_BUILD']);
function classifyHybridDraft(prompt){const t=text(prompt).toLowerCase(),ops=[];if(/index|scan|project|folder|root/.test(t))ops.push({op:'INDEX'});if(/search|find/.test(t))ops.push({op:'SEARCH_TEXT'});if(/hash|fingerprint/.test(t))ops.push({op:'HASH_TREE'});if(/workbook|excel|xlsx|csv/.test(t))ops.push({op:'WORKBOOK_AUDIT'});if(/patch|repair|fix|edit/.test(t))ops.push({op:'APPLY_PATCH'});if(/build|compile/.test(t))ops.push({op:'BUILD',profile:'AUTO_BUILD'});if(/test|qa|verify/.test(t))ops.push({op:'TEST',profile:'AUTO_BUILD'});if(/package|zip|installer/.test(t))ops.push({op:'PACKAGE'});if(/train|learning|learn locally/.test(t))ops.push({op:'TRAIN_LOCAL'});if(/open (?:url|site|browser)|https?:/.test(t))ops.push({op:'OPEN_URL'});if(/click/.test(t))ops.push({op:'CLICK'});if(/type|enter text/.test(t))ops.push({op:'TYPE_TEXT'});if(/macro.*record|record.*macro/.test(t))ops.push({op:'RECORD_MACRO'});if(/macro.*replay|replay.*macro/.test(t))ops.push({op:'REPLAY_MACRO'});if(!ops.length)ops.push({op:'INDEX'},{op:'HASH_TREE'});return ops.slice(0,24).map((x,i)=>({step:i+1,...x}))}
async function hybridDraft(body){const prompt=text(body?.prompt||body?.text),root=text(body?.root||'.')||'.',requested=classifyHybridDraft(prompt),broadRoot=root==='.'||root==='';let operations=requested;if(broadRoot&&operations.some(x=>x.op==='BUILD'||x.op==='TEST'))operations=[{step:1,op:'INDEX'},{step:2,op:'HASH_TREE'},...operations.filter(x=>x.op!=='BUILD'&&x.op!=='TEST').map((x,i)=>({...x,step:i+3}))];const draft={schema:'OMEGA_HYBRID_DRAFT_V3',state:'DRAFT_ONLY_NOT_QUEUED',prompt,root,operations,confirmed:false,deviceId:null,limits:{steps:24,sourceFiles:25000,sourceBytes:2147483648,generatedBytes:536870912,changedFiles:80,missionCycles:[2,8]},truthBoundary:'Draft generation cannot pair a device, queue work, mutate HostState, bypass confirmation, execute a shell, read passwords, cross the approved root, or claim native execution.'};draft.fingerprint=await sha256(draft);return draft}
function validateHybridPlan(body){const plan=body?.plan||body,errors=[];if(!Array.isArray(plan?.operations)||plan.operations.length<1||plan.operations.length>24)errors.push('operations must contain 1-24 steps');for(const [i,row] of (plan?.operations||[]).entries()){if(!HYBRID_OPERATIONS.includes(row?.op))errors.push(`step ${i+1}: unsupported operation ${row?.op}`);if(row?.profile&&!HYBRID_PROFILES.includes(row.profile))errors.push(`step ${i+1}: unsupported build/test profile`);if(row?.path&&(String(row.path).startsWith('/')||/^[A-Za-z]:[\\/]/.test(String(row.path))||String(row.path).includes('..')))errors.push(`step ${i+1}: path must remain root-relative`);if(row?.url&&!String(row.url).startsWith('https://'))errors.push(`step ${i+1}: URL must use HTTPS`);if(row?.op==='SAR_R344_CLOSURE'){const s=row?.sarClosure||{},required=['masterPath','slavePath','masterOrbitPath','slaveOrbitPath','demPath','outputPath','coregProofPath','interferogramPath','coherencePath','correctedInterferogramPath','geometricPhaseProofPath','receiptPath'];for(const key of required){const p=String(s[key]||'');if(!p||p==='.'||p.startsWith('/')||/^[A-Za-z]:[\\/]/.test(p)||p.split(/[\\/]/).includes('..'))errors.push(`step ${i+1}: SAR closure requires explicit safe ${key}`)}if(!Number.isFinite(Date.parse(String(s.masterAcquired||''))))errors.push(`step ${i+1}: SAR closure master acquisition time invalid`);if(!Number.isFinite(Date.parse(String(s.slaveAcquired||''))))errors.push(`step ${i+1}: SAR closure slave acquisition time invalid`);if(!['VV','VH','HH','HV'].includes(String(s.polarization||'').toUpperCase()))errors.push(`step ${i+1}: SAR closure polarization invalid`);if(!['IW1','IW2','IW3'].includes(String(s.subswath||'').toUpperCase()))errors.push(`step ${i+1}: SAR closure subswath invalid`);const fb=Number(s.firstBurst),lb=Number(s.lastBurst);if(!Number.isInteger(fb)||fb<1||!Number.isInteger(lb)||lb<fb||lb>999)errors.push(`step ${i+1}: SAR closure burst range invalid`)}}return{schema:'OMEGA_HYBRID_PLAN_VALIDATION_V1',valid:errors.length===0,errors,operationRegistry:HYBRID_OPERATIONS,profiles:HYBRID_PROFILES,execution:'DEVICE_PROOF_REQUIRED'}}

async function omegaR8(request,env){const url=new URL(request.url);
 if(url.pathname==='/api/earth/evidence'&&request.method==='GET')return json(await earthEvidence(url));
 if(url.pathname==='/api/earth/weather'&&request.method==='GET'){const result=await weatherForecast(url);return json(result,result.ok?200:502)}
 if(url.pathname==='/api/earth/noaa/catalog'&&request.method==='GET')return json(await noaaCatalog());
 if(url.pathname==='/api/earth/sar/catalog'&&request.method==='GET'){const result=await sarCatalogR285(url);return json(result,result.ok?200:502)}
 if(url.pathname==='/api/earth/sar/asset-probe'&&request.method==='GET'){const result=await sarAssetProbeR325(url);const status=result.state==='INVALID_REQUEST'?400:result.state==='PROBE_FAILED'?502:200;return json(result,status)}
 if(url.pathname==='/api/earth/sar/native-raster'&&request.method==='GET'){const result=await sarNativeRasterR326(url);const status=result.state==='INVALID_REQUEST'?400:result.state==='NATIVE_DECODE_HELD'&&String(result.error||'').startsWith('RANGE_HTTP_5')?502:200;return json(result,status)}
 if(url.pathname==='/api/earth/sar/measurement-raster'&&request.method==='GET'){const result=await sarMeasurementRasterR337(url);const status=result.state==='INVALID_REQUEST'?400:/DECODE_HELD$/.test(String(result.state||''))&&String(result.error||'').startsWith('RANGE_HTTP_5')?502:200;return json(result,status)}
 if(url.pathname==='/api/earth/sar/annotations'&&request.method==='GET'){const result=await sarAnnotationR343(url);const status=result.state==='INVALID_REQUEST'?400:result.state==='ANNOTATION_FETCH_FAILED'?502:200;return json(result,status)}
 if(url.pathname==='/api/earth/noaa/image'&&request.method==='GET'){const id=text(url.searchParams.get('coverage')),c=NOAA_COVERAGES[id];if(!c)return json({ok:false,code:'UNKNOWN_COVERAGE'},404);try{const r=await fetch(c.url,{cf:{cacheTtl:60,cacheEverything:false}});const ct=r.headers.get('content-type')||'';if(!r.ok||!ct.startsWith('image/'))return json({ok:false,code:'NOAA_IMAGE_UNAVAILABLE',coverage:id,status:r.status},502);return new Response(r.body,{status:200,headers:{'content-type':ct,'cache-control':'public, max-age=60','x-omega-source':'NOAA-STAR-LATEST-ALIAS','x-omega-last-modified':r.headers.get('last-modified')||''}})}catch(e){return json({ok:false,code:'NOAA_IMAGE_FETCH_FAILED',error:e instanceof Error?e.message:String(e)},502)}}
 if(url.pathname==='/api/hybrid/capabilities'&&request.method==='GET')return json({ok:true,schema:'OMEGA_HYBRID_V90_MIGRATION_CONTRACT_V1',state:'CLOUD_DRAFT_AND_VALIDATION_LIVE_NATIVE_EXECUTION_DEVICE_PROOF_REQUIRED',operations:HYBRID_OPERATIONS,profiles:HYBRID_PROFILES,missionCycles:{min:2,max:8},workspaceGovernor:{sourceFiles:25000,sourceBytes:2147483648,generatedBytes:536870912,changedFiles:80},trainLocal:{operation:'TRAIN_LOCAL',foundationWeightsChanged:false,requiredProof:'OMEGA_SAI_LOCAL_TRAINING_RECEIPT_V1 + active model fingerprint'},boundaries:['NO_ARBITRARY_SHELL','ROOT_CONFINED','EXPLICIT_CONFIRMATION_REQUIRED','NO_PASSWORD_CAPTURE','NO_UAC_OR_SECURE_DESKTOP','HOSTSTATE_NOT_MUTATED_BY_DRAFT']});
 if(url.pathname==='/api/hybrid/plan'&&request.method==='POST'){const body=await request.json().catch(()=>({}));return json({ok:true,draft:await hybridDraft(body)})}
 if(url.pathname==='/api/hybrid/validate'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const result=validateHybridPlan(body);return json({ok:result.valid,...result},result.valid?200:400)}
 return baseWorker.fetch(request,env)
}
export default{fetch:omegaR8};
