const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const RESTORATION=Object.freeze({branch:"full-restore",state:"FULL_WORKSTATION_CANDIDATE",lineageClassification:"MERGE_CANDIDATE_NOT_YET_PROMOTED",donor:"hosted B058/V90",releaseAuthority:"Google Drive LATEST_OMEGA_UPDATE.json -> B015 R1",sourceRuntime:{stateSpace:20736,sourceAlgebraModes:179,embeddedCorpus:"MIGRATED_EXACT",unifiedCalculus:"MIGRATED_EXACT",atlas:"MIGRATED_EXACT",calculusTraversal:"MIGRATED_ADAPTED"},workstation:{routesRegistered:44,assistantFirst:"LIVE_SOURCE",localContinuity:"LIVE_BROWSER",projects:"LIVE_BROWSER",renderQueue:"LIVE_BROWSER",proofLedger:"LIVE_BROWSER",memory:"LIVE_BROWSER",routeForecast:"LIVE_SOURCE",systemValidation:"LIVE_SOURCE_AND_WORKER",hybridLink:"DEVICE_PROOF_REQUIRED",earthExternalFeeds:"EXTERNAL_DEGRADED"},preserved:["B020_ROUTE_BEFORE_GENERATION","PUBLIC_HEALTH","TRUTHFUL_STATUS","WORKERS_DEV_ROUTE","LOCAL_DRAFT_CONTINUITY","SINGLE_FLIGHT","RESPONSIVE_CONTAINMENT","AUTH_CONTINUITY","DRIVE_RELEASE_AUTHORITY"],mergeGate:"CURRENT_HEAD_CI_PASS_AND_LIVE_POST_MERGE_VERIFICATION_REQUIRED",fullRestoreClaimed:false});
const BUILD=Object.freeze({product:"OMEGAv6 Sovereign Cloud Runtime",deploymentLineage:"OMEGA B015 sovereign chain + hosted B058/V90 donor merge",acceptedDescendant:"R7 contextual continuity + source-bound cloud workstation candidate",publicAdapter:"R18 source-bound workstation candidate",releaseAuthority:"Google Drive LATEST_OMEGA_UPDATE.json",deployBridge:"GitHub -> Cloudflare Workers",restorationBranch:RESTORATION.branch,restorationState:RESTORATION.state,appDeploy:false,generatedAt:"2026-08-28"});
function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS})}
function isBoundedRuntimeQuery(text){const t=String(text||"").trim();return /^(?:status|health|version|build status|runtime status|provider status|bridge status|hybrid link status|heartbeat status|restoration status)\??$/i.test(t)||/^(?:what(?:'s| is)|show|check|get)\s+(?:the\s+)?(?:status|health|version|build status|runtime status|provider status|bridge status|hybrid link status|heartbeat status|restoration status)\??$/i.test(t)}
function classify(text){const t=String(text||"").trim();if(!t)return{route:"FAST_DETERMINISTIC",reason:"empty-input",modelInvocations:0};if(/\b(all modes|full modes|activate all modes)\b/i.test(t))return{route:"ROUTED_MODEL_FULL",reason:"explicit-all-modes",modelInvocations:0};if(isBoundedRuntimeQuery(t))return{route:"FAST_DETERMINISTIC",reason:"bounded-runtime-query",modelInvocations:0};if(/\b(repair|design|forecast|train|compare|analy[sz]e|deep|full|build|code|program|create|make|implement|upgrade|fix)\b/i.test(t))return{route:"ROUTED_MODEL",reason:"synthesis-required",modelInvocations:0};return{route:"ROUTED_MODEL",reason:"conversational-synthesis",modelInvocations:0}}
function statusPayload(env){return{ok:true,build:BUILD,cloud:{worker:"LIVE",staticAssets:"BRANCH_BUILD_DEPENDENT",mergeTarget:"main"},canonicalAuthority:{source:"Google Drive",release:"B015 R1",state:"EXTERNAL_AUTHORITY",promotion:"POINTER_CONTROLLED"},modelProvider:env.OMEGA_MODEL_ENDPOINT?"CONFIGURED_EXTERNAL":"NOT_CONFIGURED",hybridLink:{state:"DEVICE_PROOF_REQUIRED",missionControlSurface:"LIVE_PLANNER",nativeExecutionClaimed:false},earth:{state:"SOURCE_VISUALIZATION_LIVE",liveFeeds:"EXTERNAL_DEGRADED_UNTIL_BOUND"},restoration:RESTORATION,truthBoundary:"The workstation candidate contains the real embedded source runtime and cloud-native functional surfaces, but full public restoration is not claimed until merge/deploy/live verification. No native/device/provider/live-feed capability is claimed without evidence."}}
async function api(request,env,url){
 if(url.pathname==="/api/health"&&request.method==="GET")return json({ok:true,service:BUILD.product,build:BUILD,restoration:{state:RESTORATION.state,fullRestoreClaimed:false},now:new Date().toISOString()});
 if(url.pathname==="/api/status"&&request.method==="GET")return json(statusPayload(env));
 if(url.pathname==="/api/restoration"&&request.method==="GET")return json({ok:true,...RESTORATION,build:BUILD.publicAdapter,provider:env.OMEGA_MODEL_ENDPOINT?"CONFIGURED_EXTERNAL":"NOT_CONFIGURED",nativeHost:"DEVICE_PROOF_REQUIRED",earthFeeds:"EXTERNAL_DEGRADED_UNTIL_BOUND"});
 if(url.pathname==="/api/hybrid/status"&&request.method==="GET")return json({ok:true,state:"DEVICE_PROOF_REQUIRED",controller:"LIVE_PLANNER",devices:[],jobs:[],nativeExecutionClaimed:false,message:"Cloud mission planning is live; no verified native heartbeat is bound yet."});
 if(url.pathname==="/api/hybrid/desktop-update"&&request.method==="GET")return json({ok:true,state:"DEVICE_PROOF_REQUIRED",nativeUpdate:"NOT_TESTABLE_WITHOUT_HOST",message:"A paired Windows host must prove its current version before an update decision can be made."});
 if(url.pathname==="/api/missions"&&request.method==="GET")return json({ok:true,missions:[],state:"DEVICE_PROOF_REQUIRED"});
 if(url.pathname==="/api/orchestrator/thread"&&request.method==="GET")return json({ok:true,thread:null,persistence:"LOCAL_BROWSER",routeBeforeGeneration:true});
 if(url.pathname==="/api/orchestrator/turn"&&request.method==="POST"){if(!env.OMEGA_MODEL_ENDPOINT)return json({ok:false,code:"MODEL_PROVIDER_NOT_CONFIGURED",reply:"ENACT requires synthesis. No model provider is bound, so no command plan was fabricated or queued."},503);return json({ok:false,code:"ORCHESTRATOR_EXTERNAL_ADAPTER_REQUIRED",reply:"A provider endpoint is configured, but governed plan translation still requires the external adapter contract."},503)}
 if((url.pathname==="/api/hybrid/jobs"||url.pathname.startsWith("/api/hybrid/jobs/")||url.pathname==="/api/missions")&&request.method==="POST")return json({ok:false,code:"DEVICE_PROOF_REQUIRED",reply:"Native mission execution requires a verified paired-host heartbeat and proof channel."},503);
 if(url.pathname.startsWith("/api/missions/")&&request.method==="POST")return json({ok:false,code:"DEVICE_PROOF_REQUIRED",reply:"Mission control execution is unavailable until a verified paired host is bound."},503);
 if((url.pathname==="/api/subscriptions"||url.pathname==="/api/subscriptions/remove")&&request.method==="POST")return json({ok:true,state:"LOCAL_BROWSER_ONLY",realtime:"NOT_BOUND"});
 if(url.pathname==="/api/route-preview"&&request.method==="POST"){const body=await request.json().catch(()=>({})),text=String(body.text||body.message||"").slice(0,16384);return json({ok:true,...classify(text)})}
 if(url.pathname==="/api/chat"&&request.method==="POST"){const body=await request.json().catch(()=>({})),text=String(body.text||body.message||"").slice(0,16384),routing=classify(text);if(routing.route==="FAST_DETERMINISTIC"){if(/\brestoration\b/i.test(text))return json({ok:true,routing,reply:`Restoration is ${RESTORATION.state} on ${RESTORATION.branch}. The embedded 20,736-state runtime and 44-route source-bound workstation are present; public full-restore claim remains merge/deploy/live-verification gated.`});if(/\bhealth\b/i.test(text))return json({ok:true,routing,reply:"Cloud Worker health is live. The source-bound workstation candidate is build-gated; native Hybrid Link still requires verified device proof."});if(/\b(status|version|build status)\b/i.test(text))return json({ok:true,routing,reply:`${BUILD.product}; ${BUILD.publicAdapter}; restoration ${RESTORATION.state}; release authority B015 R1.`});return json({ok:true,routing,reply:"Bounded deterministic route completed."})}if(!env.OMEGA_MODEL_ENDPOINT)return json({ok:false,routing,code:"MODEL_PROVIDER_NOT_CONFIGURED",reply:"This request requires synthesis. OMEGA will not fabricate a model response until a provider binding is configured."},503);const upstream=await fetch(env.OMEGA_MODEL_ENDPOINT,{method:"POST",headers:{"content-type":"application/json",...(env.OMEGA_MODEL_AUTH?{authorization:env.OMEGA_MODEL_AUTH}:{})},body:JSON.stringify({text,route:routing.route})}),payload=await upstream.text();return new Response(payload,{status:upstream.status,headers:{"content-type":upstream.headers.get("content-type")||"application/json","cache-control":"no-store"}})}
 return json({ok:false,code:"NOT_FOUND"},404)
}
export{classify,RESTORATION};export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return api(request,env,url);return env.ASSETS.fetch(request)}};
