import r115,{OmegaRuntime as OmegaRuntimeR115} from './workerR115.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-runtime-successor':'R116'};
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:JSON_HEADERS});
const CANONICAL_ORIGIN='https://omegav6.jeffdeweyeljefe.workers.dev';
const OBSOLETE_SOVEREIGN_PREVIEW='https://omega-sovereign-convergence.foundasound.chatgpt.site';
const now=()=>Date.now();
const text=v=>String(v??'').trim();
async function machineHealth(binding,url,label){const started=now();if(!binding?.fetch)return{state:'BINDING_MISSING',service:label,httpStatus:0,latencyMs:0,jsonVerified:false};try{const response=await binding.fetch(new Request(url,{headers:{accept:'application/json','cache-control':'no-cache'}})),body=await response.json().catch(()=>null);return{state:response.ok&&body?.ok===true?'LIVE':'DEGRADED',service:body?.service||label,version:body?.version||null,httpStatus:response.status,latencyMs:now()-started,jsonVerified:Boolean(body&&typeof body==='object'),authority:body?.authority||null}}catch(error){return{state:'UNREACHABLE',service:label,httpStatus:0,latencyMs:now()-started,jsonVerified:false,error:text(error instanceof Error?error.message:error).slice(0,180)}}}
async function machineStatus(env){const [genesis,optical]=await Promise.all([machineHealth(env.OMEGA_GENESIS_MACHINE,'https://omega-genesis-machine-r115.internal/api/health','omega-genesis-machine-r115'),machineHealth(env.OMEGA_OPTICAL_MACHINE,'https://omega-optical-machine-r115.internal/api/health','omega-optical-machine-r115')]);return{ok:genesis.state==='LIVE'&&optical.state==='LIVE',schema:'OMEGA_FEDERATION_MACHINE_STATUS_R116',runtimeRevision:'R116',canonicalAuthority:'omega-v6',nodes:{genesis,optical},truthBoundary:'R116 observes the R115 machine adapters. PROPOSE and SCREEN service health is distinct from protected human-surface reachability, Sovereign host proof, full-wave execution, and OMEGAv6 admission.'}}
function normalizeFederationStatus(base,machine){if(!base||typeof base!=='object')return base;const out={...base,runtimeRevision:'R116',experienceRevision:'R116',machine};const nodes={...(base.nodes||{})};if(nodes.genesis&&machine?.nodes?.genesis?.state==='LIVE')nodes.genesis={...nodes.genesis,machineState:'LIVE',machineService:machine.nodes.genesis.service,machineVersion:machine.nodes.genesis.version||null};if(nodes.optical&&machine?.nodes?.optical?.state==='LIVE'){const legacyState=nodes.optical.state;nodes.optical={...nodes.optical,state:'LIVE',machineState:'LIVE',machineService:machine.nodes.optical.service,machineVersion:machine.nodes.optical.version||null,humanSurfaceState:legacyState,humanSurfaceTruth:'Protected human UI state is observational only; internal SCREEN service health is the execution state used by the canonical fabric.'}}out.nodes=nodes;out.truthBoundary='R116 distinguishes human surfaces, machine service bindings, current Sovereign heartbeat, solver execution, and final canonical admission. Historical pairing and obsolete preview hosts never count as current execution proof.';return out}
async function fetchR116(request,env){const url=new URL(request.url),path=url.pathname;
 if(path==='/api/federation/machine/status'&&request.method==='GET')return json(await machineStatus(env));
 if(path==='/api/hybrid/current-link'&&request.method==='GET')return json({ok:true,schema:'OMEGA_CURRENT_HOST_LINK_R116',runtimeRevision:'R116',canonicalOrigin:CANONICAL_ORIGIN,launcherName:'START_OMEGA_PC_LINK.cmd',federationLauncherName:'START_OMEGA_FEDERATION.cmd',obsoleteOrigins:[OBSOLETE_SOVEREIGN_PREVIEW],freshLauncherRequired:true,recovery:['Open the canonical OMEGAv6 Hybrid surface.','Create or rotate the browser pairing if the existing credential is stale or rejected.','Download a fresh launcher from that canonical surface; do not reuse an older download that names an obsolete host.','Run it from the approved Windows root and keep the heartbeat window open.','PC ONLINE is admitted only after a current authenticated heartbeat returns.'],truthBoundary:'The browser credential is not PC proof. A launcher file is not PC proof. Only a current authenticated heartbeat can release native capability.'});
 if(path==='/api/federation/run/status'&&request.method==='GET'){const [response,machine]=await Promise.all([r115.fetch(request,env),machineStatus(env)]);const raw=await response.text();let body=null;try{body=JSON.parse(raw)}catch{}if(!response.ok||!body)return new Response(raw,{status:response.status,statusText:response.statusText,headers:response.headers});return json(normalizeFederationStatus(body,machine),response.status)}
 const response=await r115.fetch(request,env),headers=new Headers(response.headers);headers.set('x-omega-runtime-successor','R116');return new Response(response.body,{status:response.status,statusText:response.statusText,headers})
}
export class OmegaRuntime extends OmegaRuntimeR115 {}
export default{async fetch(request,env){return fetchR116(request,env)}};
