import {corpusState} from './corpusRuntime';
import {evaluateAdmissibility248832} from './admissibility248832Runtime';
export const WORLD_MODEL_ACTIVE_VERSION='OMEGA_WORLD_MODEL_ADAPTED_V3' as const;
export const WORLD_MODEL_PREDECESSOR_VERSION='OMEGA_WORLD_MODEL_ADAPTED_V2' as const;
const cl=(x:number)=>Math.max(0,Math.min(1,Number.isFinite(x)?x:0));
export type WorldCandidate={kind:'SOURCE_NEXT'|'HOURGLASS'|'OPPOSITE_DOMAIN'|'PREVIOUS';address:number;stateId:number;score:number;closure:number;continuity:number;plasticity:number;contradiction:number;burden:number;evidence:number;memoryBias:number;decision:string;admissibilityScore:number;admissibilityPass:boolean;gatePassCount:number};
function readExplicitMemory(){if(typeof localStorage==='undefined')return[] as any[];try{return JSON.parse(localStorage.getItem('omega.world.learning.ledger')||'[]')}catch{return[]}}
function readObservedHits(){if(typeof localStorage==='undefined')return[] as number[];try{const rows=JSON.parse(localStorage.getItem('omega.pc.spine.ledger')||'[]') as any[],hits:number[]=[];for(let i=1;i<rows.length;i++){const prev=rows[i-1],next=rows[i];if(prev?.address!==next?.address&&Number.isFinite(prev?.worldBest)&&next?.address===prev.worldBest)hits.push(next.address)}return hits}catch{return[]}}
function scoreAddress(address:number,kind:WorldCandidate['kind']){const r=corpusState(address),m=r.metrics,p=r.predict,adm=evaluateAdmissibility248832(address),base=.24*cl(Number(m.continuity))+.18*cl(Number(m.plasticity))+.16*cl(Number(m.evidence))+.12*cl(Number(p.reconstructability))+.10*cl(Number(m.geometry))+.08*cl(Number(m.rsc))+.07*(1-cl(Number(m.contradiction)))+.05*(1-cl(Number(m.burden)));const memory=readExplicitMemory(),hits=memory.filter(x=>x?.selectedAddress===address&&x?.accepted===true).length+readObservedHits().filter(x=>x===address).length,miss=memory.filter(x=>x?.selectedAddress===address&&x?.accepted===false).length,memoryBias=Math.max(-.08,Math.min(.08,.012*(hits-miss))),kindPrior=kind==='SOURCE_NEXT'?.03:kind==='HOURGLASS'?.015:kind==='OPPOSITE_DOMAIN'?0:-.01,admissibilityFactor=adm.admissible?.08*adm.score:-.10*(1-adm.score),score=cl(base+memoryBias+kindPrior+admissibilityFactor),closure=cl(.34*Number(m.continuity)/(1+Number(m.burden)+Number(m.contradiction))+.24*Number(m.evidence)+.18*(1-Number(m.contradiction))+.14*(1-Number(m.burden))+.10*Number(p.reconstructability));return{address,stateId:address+1,score,closure,continuity:Number(m.continuity),plasticity:Number(m.plasticity),contradiction:Number(m.contradiction),burden:Number(m.burden),evidence:Number(m.evidence),memoryBias,decision:String(m.decision),admissibilityScore:adm.score,admissibilityPass:adm.admissible,gatePassCount:adm.passCount}}
export function compileWorldModel(address:number){const r=corpusState(address),a=r.autoPing,raw:[WorldCandidate['kind'],number][]=[['SOURCE_NEXT',Number(a.dataNext)],['HOURGLASS',Number(a.hourglassMirror)],['OPPOSITE_DOMAIN',Number(a.oppositeDomain)],['PREVIOUS',Number(a.previous)]],seen=new Set<number>(),candidates=raw.flatMap(([kind,x])=>{const n=Math.max(0,Math.min(20735,Math.floor(x)));if(seen.has(n))return[];seen.add(n);return[{kind,...scoreAddress(n,kind)}]}).sort((x,y)=>Number(y.admissibilityPass)-Number(x.admissibilityPass)||y.score-x.score),best=candidates.find(x=>x.admissibilityPass)??candidates[0];return{version:WORLD_MODEL_ACTIVE_VERSION,predecessorVersion:WORLD_MODEL_PREDECESSOR_VERSION,source:'canon_phase7_world_model + canon_predictive_engine + canon_persistent_learning_engine + admissibility_integration_248832d adapted to canonical AutoPing candidates',address,stateId:address+1,candidates,best,admissible:Boolean(best?.admissibilityPass),boundary:'World-model output is a governed internal candidate ranking over existing source-linked states. 248,832 admissibility is represented as 12 gates × 20,736 addresses and constrains recommendations; it is not a physical dimension claim. Learning rewards only explicit outcomes or later observed operator transitions; unchosen candidates are not silently treated as failures. No candidate executes without an explicit application commit.'}}
export function recordWorldModelOutcome(sourceAddress:number,selectedAddress:number,accepted:boolean,note=''){if(typeof localStorage==='undefined')return;const key='omega.world.learning.ledger',old=readExplicitMemory(),entry={ts:new Date().toISOString(),sourceAddress,selectedAddress,accepted,note};localStorage.setItem(key,JSON.stringify([...old,entry].slice(-188)))}
export function worldModelMemorySummary(){const rows=readExplicitMemory(),observed=readObservedHits(),accepted=rows.filter(x=>x?.accepted===true).length,rejected=rows.filter(x=>x?.accepted===false).length;return{count:Math.min(188,rows.length+observed.length),accepted,rejected,observedMatches:observed.length,boundary:'Local browser learning memory only; no claim of cross-device or server persistence.'}}
