import {appendWorldEventR134,continuityOperationRefR134,sha256R134} from './world/canonicalWorldContinuityR134.js';

export const R143_REVISION='R143';
export const R143_SCHEMA='OMEGA_WOVEN_EXECUTION_GRAPH_R143';
export const R143_LAWS=Object.freeze([
 'ONE_OBJECTIVE_MAY_DECOMPOSE_INTO_MANY_BOUNDED_TASKS',
 'PARALLEL_NATIVE_EXECUTION_REQUIRES_CURRENT_AUTHENTICATED_DEVICE_PROOF',
 'MULTI_DEVICE_EXECUTION_REQUIRES_HASH_MATCHED_WORKSPACE_REPLICAS',
 'DEPENDENCY_EDGES_ADVANCE_ONLY_FROM_VERIFIED_R141_CLOSURE',
 'VERIFIED_R141_EDGE_IS_RECORDED_AS_R142_CAPABILITY_LIFECYCLE_VERIFIED',
 'REPLICA_DRIFT_BECOMES_SCAR_AND_HOLD_NOT_SILENT_MERGE',
 'READY_TASK_WITHOUT_LAWFUL_EXECUTOR_BECOMES_EXPLICIT_HOLD',
 'SAME_PASS_SCHEDULING_COUNTS_JOBS_IT_JUST_QUEUED',
 'CONCURRENT_MUTATION_ON_ONE_DEVICE_REQUIRES_DISJOINT_DECLARED_WRITESETS',
 'GRAPH_JOIN_IS_R134_PROOF_CONTINUITY_NOT_CANONSTATE',
 'R139_R140_R141_R142_AUTHORITIES_ARE_PRESERVED',
 'R125_REMAINS_CANONICAL_ADMISSION_AUTHORITY'
]);

const OPS=Object.freeze(['TRAIN_LOCAL','INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','SAFE_IMPORT','WORKBOOK_AUDIT','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','WRITE_TEXT','OPEN_URL','WAIT','LIST_WINDOWS','FOCUS_WINDOW','SCREEN_CAPTURE','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO']);
const PROFILES=Object.freeze(['AUTO_BUILD','NODE_BUILD','PYTHON_TEST','DOTNET_BUILD','WINDOWS_AUTOMATION','BROWSER_AUTOMATION']);
const MUTATING=new Set(['TRAIN_LOCAL','SAFE_IMPORT','BUILD','PACKAGE','APPLY_PATCH','WRITE_TEXT','OPEN_URL','FOCUS_WINDOW','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','RECORD_MACRO','REPLAY_MACRO']);
const WINDOW_OPS=new Set(['FOCUS_WINDOW','SCREEN_CAPTURE','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO']);
const TERMINAL_GRAPH=new Set(['COMPLETE','FAILED','HELD','CANCELLED']);
const text=(v,n=4000)=>String(v??'').trim().slice(0,n);
const safeId=(v,f='')=>{const s=text(v,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:f};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const now=()=>Date.now();
const uid=p=>{const a=new Uint8Array(6);crypto.getRandomValues(a);return `${p}_${now().toString(36)}_${[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}`};
const isHex64=v=>/^[0-9a-f]{64}$/i.test(String(v||''));
function rel(v){const s=text(v||'.',260).replace(/\\/g,'/');if(!s||s==='.')return'.';if(s.startsWith('/')||/^[A-Za-z]:/.test(s)||s.split('/').includes('..')||s.includes('\0'))return null;return s.split('/').filter(Boolean).join('/')||'.'}
function uniq(v,limit=64){return [...new Set((Array.isArray(v)?v:[]).map(x=>safeId(x)).filter(Boolean))].slice(0,limit)}
function writes(v){return [...new Set((Array.isArray(v)?v:[]).map(rel).filter(Boolean))].slice(0,80)}
function overlap(a,b){if(!a.length||!b.length)return true;return a.some(x=>b.some(y=>x===y||x.startsWith(y+'/')||y.startsWith(x+'/')))}
function opsFor(t){return [...new Set(t.steps.map(s=>s.op))]}
function covers(d,t){const caps=new Set(Array.isArray(d?.capabilities)?d.capabilities:[]);return opsFor(t).every(op=>caps.has(op))}
function normalStep(raw,i,project){const op=text(raw?.op,40).toUpperCase(),errors=[];if(!OPS.includes(op))errors.push(`step ${i+1}: unsupported op ${op||'EMPTY'}`);const profile=raw?.profile?text(raw.profile,40).toUpperCase():undefined;if(profile&&!PROFILES.includes(profile))errors.push(`step ${i+1}: unsupported profile ${profile}`);const path=raw?.path===undefined?undefined:rel(raw.path);if(raw?.path!==undefined&&!path)errors.push(`step ${i+1}: unsafe path`);const url=raw?.url===undefined?undefined:text(raw.url,1000);if(url&&!url.startsWith('https://'))errors.push(`step ${i+1}: HTTPS required`);const windowTitle=raw?.windowTitle===undefined?undefined:text(raw.windowTitle,240);if(WINDOW_OPS.has(op)&&!windowTitle)errors.push(`step ${i+1}: window title lock required`);if(op==='APPLY_PATCH'&&(!isHex64(raw?.expectedSha256)||!Array.isArray(raw?.replacements)||raw.replacements.length<1||raw.replacements.length>24))errors.push(`step ${i+1}: hash-bound replacements required`);if(op==='WRITE_TEXT'&&!raw?.createOnly&&!isHex64(raw?.expectedSha256))errors.push(`step ${i+1}: existing write requires preimage hash`);const step={...raw,id:safeId(raw?.id,`S${String(i+1).padStart(2,'0')}`),op};if(profile)step.profile=profile;if(path!==undefined)step.path=path||project;if(url!==undefined)step.url=url;if(windowTitle!==undefined)step.windowTitle=windowTitle;return{step,errors}}
function normalTask(raw,i,project){const id=safeId(raw?.id,`T${String(i+1).padStart(2,'0')}`),rawSteps=Array.isArray(raw?.steps)?raw.steps:[],errors=[];if(rawSteps.length<1||rawSteps.length>24)errors.push(`${id}: 1-24 steps required`);const steps=[];for(let j=0;j<rawSteps.length;j++){const n=normalStep(rawSteps[j],j,project);steps.push(n.step);errors.push(...n.errors.map(e=>`${id}: ${e}`))}const task={id,label:text(raw?.label||raw?.name||id,180),dependsOn:uniq(raw?.dependsOn,24),writeSet:writes(raw?.writeSet),steps,profile:text(raw?.profile||'AUTO_BUILD',40).toUpperCase(),preferredDeviceId:safeId(raw?.preferredDeviceId),priority:clamp(raw?.priority??1,0,1),mutates:steps.some(s=>MUTATING.has(s.op)),state:'PENDING',jobId:null,assignedDeviceId:null,closureRef:null,scarIds:[]};if(task.mutates&&!task.writeSet.length)errors.push(`${id}: mutating task requires declared writeSet`);if(!PROFILES.includes(task.profile))errors.push(`${id}: unsupported task profile ${task.profile}`);return{task,errors}}
function serial(steps,project){return(Array.isArray(steps)?steps:[]).map((s,i)=>({id:`T${String(i+1).padStart(2,'0')}`,label:s.label||s.op||`Task ${i+1}`,dependsOn:i?[`T${String(i).padStart(2,'0')}`]:[],writeSet:MUTATING.has(String(s?.op||'').toUpperCase())?[rel(s.path)||project]:[],steps:[s]}))}
function topo(tasks){const ids=new Set(tasks.map(t=>t.id)),incoming=new Map(tasks.map(t=>[t.id,0])),out=new Map(tasks.map(t=>[t.id,[]]));for(const t of tasks)for(const dep of t.dependsOn){if(!ids.has(dep))return{ok:false,error:`${t.id}: unknown dependency ${dep}`};incoming.set(t.id,incoming.get(t.id)+1);out.get(dep).push(t.id)}const q=tasks.filter(t=>incoming.get(t.id)===0).map(t=>t.id),order=[];while(q.length){const id=q.shift();order.push(id);for(const n of out.get(id)){incoming.set(n,incoming.get(n)-1);if(incoming.get(n)===0)q.push(n)}}return order.length===tasks.length?{ok:true,order}:{ok:false,error:'task dependency cycle detected'}}
function publicGraph(g){if(!g)return null;return{...g,tasks:g.tasks.map(t=>({...t,steps:t.steps.map(s=>({...s,content:s.content!==undefined?'[bounded content omitted]':undefined,replacements:s.replacements?`[${s.replacements.length} hash-bound replacements]`:undefined}))}))}}
function active(g){return g.tasks.filter(t=>['QUEUED','RUNNING'].includes(t.state))}
function depsDone(g,t){return t.dependsOn.every(id=>g.tasks.find(x=>x.id===id)?.state==='COMPLETE')}
function activeCompatible(g,t,deviceId){for(const other of active(g)){if(other.assignedDeviceId!==deviceId||!t.mutates||!other.mutates)continue;if(overlap(t.writeSet,other.writeSet))return false}return true}
function proofIds(g){return g.tasks.map(t=>t.closureRef?.fingerprint).filter(isHex64).slice(-64)}
function sourceIds(g){return [...new Set(g.tasks.map(t=>t.assignedDeviceId).filter(Boolean))].slice(-64)}
function extractTree(c){for(const p of c?.input?.core?.stepProofs||[]){const r=p?.result||{};for(const v of[r.treeSha256,r.tree_sha256,r.rootSha256,r.root_sha256])if(isHex64(v))return String(v).toLowerCase()}return null}

export async function compileWovenExecutionGraphR143(runtime,input={}){
 const objective=text(input.objective||input.intent),projectPath=rel(input.projectPath||'.'),policy=input.replicaPolicy==='HASH_MATCHED_REPLICAS'?'HASH_MATCHED_REPLICAS':'SINGLE_HOST',maxParallel=clamp(input.maxParallel??(policy==='HASH_MATCHED_REPLICAS'?4:1),1,8),raw=Array.isArray(input.tasks)&&input.tasks.length?input.tasks:serial(input.steps,projectPath||'.'),errors=[];
 if(!objective)errors.push('objective required');if(!projectPath)errors.push('safe relative projectPath required');if(raw.length<1||raw.length>24)errors.push('1-24 graph tasks required');const tasks=[];for(let i=0;i<raw.length;i++){const n=normalTask(raw[i],i,projectPath||'.');tasks.push(n.task);errors.push(...n.errors)}if(new Set(tasks.map(t=>t.id)).size!==tasks.length)errors.push('task ids must be unique');const topology=topo(tasks);if(!topology.ok)errors.push(topology.error);
 const live=(await runtime.devices()).filter(d=>d?.online===true&&d?.revoked!==true),requested=uniq(input.deviceIds,20),pool=live.filter(d=>!requested.length||requested.includes(d.id));let candidates=[];
 if(policy==='SINGLE_HOST')candidates=pool.filter(d=>tasks.every(t=>covers(d,t)));else candidates=pool.filter(d=>d.capabilities?.includes('HASH_TREE')&&tasks.some(t=>covers(d,t)));
 if(!candidates.length)errors.push(policy==='SINGLE_HOST'?'no current authenticated device advertises every graph operation':'no current authenticated HASH_TREE-capable replica can execute graph tasks');
 for(const t of tasks){const possible=candidates.filter(d=>covers(d,t)&&(!t.preferredDeviceId||d.id===t.preferredDeviceId));if(!possible.length)errors.push(`${t.id}: no candidate executor advertises the required operations${t.preferredDeviceId?' on preferred device '+t.preferredDeviceId:''}`)}
 const core={schema:R143_SCHEMA,revision:R143_REVISION,objective,projectPath,allowedDomains:(Array.isArray(input.allowedDomains)?input.allowedDomains:[]).map(x=>text(x,180).toLowerCase()).filter(Boolean).slice(0,12),replicaPolicy:policy,maxParallel,tasks:tasks.map(({state,jobId,assignedDeviceId,closureRef,scarIds,...t})=>t),candidateDeviceIds:candidates.map(d=>d.id),topology:topology.order||[],canonicalMutation:false,canonicalAdmissionAuthority:'R125'};const graphDigest=await sha256R134(core);return{ok:!errors.length,errors,graphCore:core,graphDigest,candidateDevices:candidates,truthBoundary:'R143 compilation validates bounded operations, dependency topology, authenticated device capabilities, preferred executors and replica policy only. It queues nothing.'};
}
async function save(runtime,g){await runtime.put('r143Graph:'+g.id,g);const ids=await runtime.get('r143GraphIndex',[]);await runtime.put('r143GraphIndex',[...ids.filter(x=>x!==g.id),g.id].slice(-80));return g}
async function read(runtime,id){return runtime.get('r143Graph:'+safeId(id),null)}
async function queueJob(runtime,g,t,d,kind='TASK'){const jobs=await runtime.get('jobs',[]),id=uid(kind==='ATTEST'?'job_r143_attest':'job_r143_task'),steps=kind==='ATTEST'?[{id:'S01',op:'HASH_TREE',label:'Prove replica workspace identity before distributed execution',path:g.projectPath,maxResults:5000}]:t.steps,inputFingerprint=await sha256R134({schema:'OMEGA_WOVEN_GRAPH_JOB_INPUT_R143',graphId:g.id,taskId:t.id,graphDigest:g.graphDigest,workspaceSha256:g.replicaInvariant?.workspaceSha256||null,steps,targetDeviceId:d.id,projectPath:g.projectPath});const job={id,schema:'OMEGA_WOVEN_GRAPH_JOB_R143',action:kind==='ATTEST'?'ATTEST_REPLICA':'WOVEN_TASK',profile:t?.profile||'AUTO_BUILD',projectPath:g.projectPath,instructions:kind==='ATTEST'?`R143 replica attestation for ${g.id}`:`R143 graph ${g.id} task ${t.id}: ${t.label}`,allowedDomains:g.allowedDomains||[],steps,targetDeviceId:d.id,targetCapabilityRevision:d.capabilityRevision||'LEGACY',status:'QUEUED',confirmed:true,queuedAt:now(),inputFingerprint,graphRef:{schema:R143_SCHEMA,graphId:g.id,taskId:t.id,kind,graphDigest:g.graphDigest,canonicalMutation:false}};jobs.push(job);await runtime.put('jobs',jobs.slice(-180));await runtime.event(kind==='ATTEST'?'R143_REPLICA_ATTESTATION_QUEUED':'R143_TASK_QUEUED',kind==='ATTEST'?`Replica ${d.id} attestation queued for graph ${g.id}.`:`Graph ${g.id} task ${t.id} queued on ${d.id}.`,{graphId:g.id,taskId:t.id,deviceId:d.id,jobId:id});return job}
async function worldEvent(runtime,g,kind,scarIds=[]){const previous=await runtime.get('r141WorldHead',null),p=proofIds(g),head=await appendWorldEventR134(previous,{eventId:`${g.id}:${kind.toLowerCase()}`,kind,sequence:(previous?.count||0)+1,eventTime:now(),observerId:'r143-woven-execution-graph',projection:'HYBRID_EXECUTION',missionId:g.id,sourceIds:sourceIds(g),proofIds:p,scarIds,payloadDigest:g.graphDigest,metrics:{continuity:kind==='PROOF'?1:.35,plasticity:kind==='PROOF'?.45:.1,contradiction:kind==='PROOF'?0:1,burden:Math.min(1,g.tasks.length/24),evidence:p.length?1:0,uncertainty:kind==='PROOF'?.05:1,scar:kind==='PROOF'?.1:1},claim:{publicDeploymentProved:false,pcOnlineProved:false,solverValidityProved:false,computedPhotorealRealityProved:false}});await runtime.put('r141WorldHead',head);return{head,ref:continuityOperationRefR134(head)}}
async function hold(runtime,g,code,detail,scarIds=[]){g.state='HELD';g.hold={code,detail,at:now()};g.updatedAt=now();const w=await worldEvent(runtime,g,'SCAR',scarIds.length?scarIds:[g.id]);g.joinReceipt={schema:'OMEGA_WOVEN_GRAPH_JOIN_R143',state:'HELD',code,worldHeadSha256:w.head.headSha256,continuity:w.ref,canonicalMutation:false,canonicalAdmissionAuthority:'R125'};await save(runtime,g);await runtime.event('R143_GRAPH_HELD',`Graph ${g.id} held: ${code}.`,{graphId:g.id,code,detail});return g}
async function complete(runtime,g){const w=await worldEvent(runtime,g,'PROOF',g.tasks.flatMap(t=>t.scarIds||[]));g.state='COMPLETE';g.completedAt=now();g.updatedAt=now();g.joinReceipt={schema:'OMEGA_WOVEN_GRAPH_JOIN_R143',state:'VERIFIED_JOIN',graphDigest:g.graphDigest,workspaceSha256:g.replicaInvariant?.workspaceSha256||null,taskCount:g.tasks.length,verifiedTaskCount:g.tasks.filter(t=>t.closureRef?.fingerprintVerified===true&&t.closureRef?.capabilityState==='VERIFIED').length,sourceDeviceIds:sourceIds(g),proofIds:proofIds(g),worldHeadSha256:w.head.headSha256,continuity:w.ref,capabilityLifecycleRevision:'R142',canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R143 joins only dependency paths already verified by R141 and classified VERIFIED in the admitted R142 capability lifecycle. The join is continuity evidence, not CanonState promotion.'};await save(runtime,g);await runtime.event('R143_GRAPH_JOIN_VERIFIED',`Graph ${g.id} joined ${g.tasks.length} verified task paths.`,{graphId:g.id,worldHeadSha256:w.head.headSha256});return g}
async function schedule(runtime,g){if(g.state!=='RUNNING')return g;const devices=(await runtime.devices()).filter(d=>d?.online===true&&!d?.revoked&&(g.admittedDeviceIds||[]).includes(d.id)),jobs=await runtime.get('jobs',[]),load=new Map(devices.map(d=>[d.id,jobs.filter(j=>j.targetDeviceId===d.id&&['QUEUED','RUNNING'].includes(j.status)).length]));for(const t of active(g))load.set(t.assignedDeviceId,(load.get(t.assignedDeviceId)||0)+1);let slots=Math.max(0,g.maxParallel-active(g).length),queued=0;
 for(const t of g.tasks){if(slots<=0)break;if(t.state!=='PENDING'||!depsDone(g,t))continue;const candidates=devices.filter(d=>covers(d,t)&&(!t.preferredDeviceId||d.id===t.preferredDeviceId)&&activeCompatible(g,t,d.id)).sort((a,b)=>(load.get(a.id)||0)-(load.get(b.id)||0)||a.id.localeCompare(b.id));if(!candidates.length)continue;const d=candidates[0],job=await queueJob(runtime,g,t,d);t.state='QUEUED';t.jobId=job.id;t.assignedDeviceId=d.id;t.queuedAt=job.queuedAt;load.set(d.id,(load.get(d.id)||0)+1);slots--;queued++}
 g.updatedAt=now();if(g.tasks.every(t=>t.state==='COMPLETE'))return complete(runtime,g);const ready=g.tasks.filter(t=>t.state==='PENDING'&&depsDone(g,t));if(!queued&&ready.length&&!active(g).length)return hold(runtime,g,'NO_LAWFUL_EXECUTOR_FOR_READY_TASK',`Ready tasks cannot be assigned under current heartbeat, capability, preferred-device or write-set constraints: ${ready.map(t=>t.id).join(', ')}`,ready.map(t=>t.id));await save(runtime,g);return g}
async function attest(runtime,g){const ds=(await runtime.devices()).filter(d=>g.candidateDeviceIds.includes(d.id)&&d.online&&!d.revoked);for(const d of ds){const fake={id:`ATTEST:${d.id}`,label:'Replica attestation',steps:[{op:'HASH_TREE'}],profile:'AUTO_BUILD'};const job=await queueJob(runtime,g,fake,d,'ATTEST');g.attestations.push({deviceId:d.id,jobId:job.id,state:'QUEUED',treeSha256:null,closureHead:null})}g.state='ATTESTING';g.updatedAt=now();return save(runtime,g)}

export async function createWovenExecutionGraphR143(runtime,input={},ownerId=''){if(input.confirmedGraph!==true)return{ok:false,code:'GRAPH_CONFIRMATION_REQUIRED',reply:'Preview is non-executing. Creation requires explicit confirmedGraph=true.'};const c=await compileWovenExecutionGraphR143(runtime,input);if(!c.ok)return{ok:false,code:'GRAPH_REJECTED',errors:c.errors,compiled:c};const id=uid('graph_r143'),g={...c.graphCore,id,graphDigest:c.graphDigest,ownerId:safeId(ownerId),state:'PLANNED',createdAt:now(),updatedAt:now(),candidateDeviceIds:c.candidateDevices.map(d=>d.id),admittedDeviceIds:[],replicaInvariant:{state:'UNPROVED',workspaceSha256:null,deviceCount:0},attestations:[],tasks:c.graphCore.tasks.map(t=>({...t,state:'PENDING',jobId:null,assignedDeviceId:null,closureRef:null,scarIds:[]})),joinReceipt:null,capabilityLifecycleRevision:'R142',canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R143 advances only an explicitly confirmed bounded DAG. R141 exact proof plus R142 lifecycle VERIFIED is required on each returned dependency edge; multi-device execution is blocked until workspace hashes agree.'};await save(runtime,g);await runtime.event('R143_GRAPH_CREATED',`Woven execution graph ${id} created with ${g.tasks.length} bounded tasks.`,{graphId:id,replicaPolicy:g.replicaPolicy,maxParallel:g.maxParallel});if(g.replicaPolicy==='HASH_MATCHED_REPLICAS')return{ok:true,graph:publicGraph(await attest(runtime,g))};const d=c.candidateDevices[0];g.admittedDeviceIds=[d.id];g.replicaInvariant={state:'SINGLE_HOST',workspaceSha256:null,deviceCount:1};g.state='RUNNING';await save(runtime,g);return{ok:true,graph:publicGraph(await schedule(runtime,g))}}

export async function advanceWovenGraphsR143(runtime,jobId,closure){const ids=await runtime.get('r143GraphIndex',[]);for(const id of [...ids].reverse()){const g=await read(runtime,id);if(!g||TERMINAL_GRAPH.has(g.state)||g.state==='PAUSED')continue;const a=g.attestations.find(x=>x.jobId===jobId);if(a){if(closure?.fingerprint?.verified!==true||closure?.state!=='VERIFIED_EXECUTION_RETURN'){a.state='HELD';a.closureHead=closure?.finalHeadSha256||null;return hold(runtime,g,'REPLICA_ATTESTATION_PROOF_FAILED',`Device ${a.deviceId} did not return verified R141 attestation.`,[jobId])}const hash=extractTree(closure);if(!hash){a.state='HELD';a.closureHead=closure.finalHeadSha256;return hold(runtime,g,'REPLICA_HASH_MISSING',`Device ${a.deviceId} returned proof without HASH_TREE identity.`,[jobId])}a.state='COMPLETE';a.treeSha256=hash;a.closureHead=closure.finalHeadSha256;g.updatedAt=now();if(g.attestations.every(x=>x.state==='COMPLETE')){const hashes=[...new Set(g.attestations.map(x=>x.treeSha256))];if(hashes.length!==1)return hold(runtime,g,'REPLICA_DRIFT',`Replica workspace hashes disagree: ${hashes.join(', ')}`,g.attestations.map(x=>x.jobId));g.replicaInvariant={state:'HASH_MATCH_VERIFIED',workspaceSha256:hashes[0],deviceCount:g.attestations.length,attestedAt:now()};g.admittedDeviceIds=g.attestations.map(x=>x.deviceId);g.state='RUNNING';await runtime.event('R143_REPLICA_INVARIANT_VERIFIED',`Graph ${g.id} admitted ${g.admittedDeviceIds.length} hash-matched replicas.`,{graphId:g.id,workspaceSha256:hashes[0],deviceIds:g.admittedDeviceIds});await save(runtime,g);return schedule(runtime,g)}await save(runtime,g);return g}
 const t=g.tasks.find(x=>x.jobId===jobId);if(!t)continue;const verified=closure?.fingerprint?.verified===true&&closure?.state==='VERIFIED_EXECUTION_RETURN';t.closureRef={schema:closure?.schema||null,state:closure?.state||null,fingerprintVerified:closure?.fingerprint?.verified===true,fingerprint:closure?.fingerprint?.supplied||null,headSha256:closure?.finalHeadSha256||null,continuity:closure?.continuity||null,deviceId:t.assignedDeviceId,capabilityLifecycleRevision:'R142',capabilityState:verified?'VERIFIED':'FAILED',canonicalMutation:false};if(!closure?.fingerprint?.verified){t.state='HELD';t.scarIds=[...(t.scarIds||[]),jobId];return hold(runtime,g,'TASK_PROOF_FAILED',`Task ${t.id} returned without verified R141 exact-payload proof.`,[jobId])}if(closure.state!=='VERIFIED_EXECUTION_RETURN'){t.state='FAILED';t.scarIds=[...(t.scarIds||[]),jobId];g.state='FAILED';g.updatedAt=now();await save(runtime,g);await worldEvent(runtime,g,'SCAR',[jobId]);await runtime.event('R143_TASK_FAILED',`Graph ${g.id} task ${t.id} returned verified failure evidence.`,{graphId:g.id,taskId:t.id,jobId});return g}t.state='COMPLETE';t.completedAt=now();await runtime.event('R143_TASK_PROOF_ACCEPTED',`Graph ${g.id} task ${t.id} advanced from R141 proof and R142 lifecycle VERIFIED.`,{graphId:g.id,taskId:t.id,jobId,headSha256:closure.finalHeadSha256});await save(runtime,g);return schedule(runtime,g)}return null}

export async function listWovenExecutionGraphsR143(runtime){const ids=await runtime.get('r143GraphIndex',[]),graphs=[];for(const id of [...ids].reverse().slice(0,40)){const g=await read(runtime,id);if(g)graphs.push(publicGraph(g))}return{ok:true,schema:'OMEGA_WOVEN_EXECUTION_GRAPH_LIST_R143',revision:R143_REVISION,graphs,canonicalMutation:false}}
export async function readWovenExecutionGraphR143(runtime,id){return publicGraph(await read(runtime,id))}
export async function controlWovenExecutionGraphR143(runtime,id,action){const g=await read(runtime,id);if(!g)return null;if(action==='pause'&&['RUNNING','ATTESTING'].includes(g.state)){g.state='PAUSED';g.updatedAt=now();await save(runtime,g);await runtime.event('R143_GRAPH_PAUSED',`Graph ${g.id} paused; already queued work is not silently cancelled.`,{graphId:g.id});return publicGraph(g)}if(action==='resume'&&g.state==='PAUSED'){g.state=g.replicaPolicy==='HASH_MATCHED_REPLICAS'&&!g.replicaInvariant?.workspaceSha256?'ATTESTING':'RUNNING';g.updatedAt=now();await save(runtime,g);return publicGraph(await schedule(runtime,g))}if(action==='cancel'&&!TERMINAL_GRAPH.has(g.state)){g.state='CANCELLED';g.updatedAt=now();await save(runtime,g);await runtime.event('R143_GRAPH_CANCELLED',`Graph ${g.id} cancelled; no new tasks will queue.`,{graphId:g.id});return publicGraph(g)}return publicGraph(g)}
export async function previewWovenExecutionGraphR143(runtime,input){const c=await compileWovenExecutionGraphR143(runtime,input);return{...c,graphCore:c.graphCore?{...c.graphCore,tasks:c.graphCore.tasks.map(t=>({...t,steps:t.steps.map(s=>({...s,content:s.content!==undefined?'[bounded content omitted]':undefined,replacements:s.replacements?`[${s.replacements.length} hash-bound replacements]`:undefined}))}))}:null}}
export function manifestR143(){return{ok:true,schema:R143_SCHEMA,revision:R143_REVISION,laws:R143_LAWS,executorAuthority:{native:'CURRENT_AUTHENTICATED_R32_R141_HYBRID_DEVICES_ONLY',replicaAdmission:'HASH_TREE_SHA256_EQUALITY',dependencyProof:'R141_VERIFIED_CLOSURE',capabilityLifecycle:'R142_VERIFIED',worldJoin:'R134_APPEND_ONLY_PROOF_OR_SCAR',canonicalAdmission:'R125'},limits:{tasks:24,stepsPerTask:24,maxParallel:8,graphHistory:80},preserves:{capabilityRouting:'R139',livingOperation:'R140',hostReturnProof:'R141',capabilityLifecycle:'R142',worldContinuity:'R134'},canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R143 is a real bounded native execution DAG over authenticated Hybrid devices. It can parallelize independent work only after replica workspace hashes agree; dependencies advance only from R141 exact proof and are classified R142 VERIFIED. Its join is evidence continuity, not CanonState promotion.'}}
