import {appendWorldEventR134,continuityOperationRefR134,sha256R134} from './world/canonicalWorldContinuityR134.js';

export const R142_REVISION='R142';
export const R142_SCHEMA='OMEGA_WOVEN_EXECUTION_GRAPH_R142';
export const R142_LAWS=Object.freeze([
 'ONE_OBJECTIVE_MAY_DECOMPOSE_INTO_MANY_BOUNDED_TASKS',
 'PARALLEL_NATIVE_EXECUTION_REQUIRES_CURRENT_AUTHENTICATED_DEVICE_PROOF',
 'MULTI_DEVICE_EXECUTION_REQUIRES_HASH_MATCHED_WORKSPACE_REPLICAS',
 'DEPENDENCY_EDGES_ADVANCE_ONLY_FROM_VERIFIED_R141_CLOSURE',
 'REPLICA_DRIFT_BECOMES_SCAR_AND_HOLD_NOT_SILENT_MERGE',
 'CONCURRENT_MUTATION_ON_ONE_DEVICE_REQUIRES_DISJOINT_DECLARED_WRITESETS',
 'TASK_CAPABILITY_MUST_BE_ADVERTISED_BY_THE_ASSIGNED_DEVICE',
 'GRAPH_JOIN_IS_R134_PROOF_CONTINUITY_NOT_CANONSTATE',
 'R139_CAPABILITY_R140_WORLD_R141_RETURN_PROOF_ARE_PRESERVED',
 'R125_REMAINS_CANONICAL_ADMISSION_AUTHORITY'
]);

const ALLOWED_OPS=Object.freeze(['TRAIN_LOCAL','INDEX','READ_TEXT','SEARCH_TEXT','HASH_TREE','SAFE_IMPORT','WORKBOOK_AUDIT','BUILD','TEST','PACKAGE','SUPPORT_BUNDLE','APPLY_PATCH','WRITE_TEXT','OPEN_URL','WAIT','LIST_WINDOWS','FOCUS_WINDOW','SCREEN_CAPTURE','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO']);
const ALLOWED_PROFILES=Object.freeze(['AUTO_BUILD','NODE_BUILD','PYTHON_TEST','DOTNET_BUILD','WINDOWS_AUTOMATION','BROWSER_AUTOMATION']);
const MUTATING_OPS=new Set(['TRAIN_LOCAL','SAFE_IMPORT','BUILD','PACKAGE','APPLY_PATCH','WRITE_TEXT','OPEN_URL','FOCUS_WINDOW','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','RECORD_MACRO','REPLAY_MACRO']);
const WINDOW_OPS=new Set(['FOCUS_WINDOW','SCREEN_CAPTURE','MOUSE_MOVE','CLICK','KEY','TYPE_TEXT','SCROLL','ASSERT_WINDOW','READ_VISIBLE_TEXT','RECORD_MACRO','REPLAY_MACRO']);
const TERMINAL_TASK=new Set(['COMPLETE','FAILED','HELD','CANCELLED']);
const text=(v,n=4000)=>String(v??'').trim().slice(0,n);
const safeId=(v,fallback='')=>{const s=text(v,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:fallback};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Number(v):a));
const now=()=>Date.now();
const randomId=(prefix)=>{const a=new Uint8Array(6);crypto.getRandomValues(a);return `${prefix}_${now().toString(36)}_${[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}`};
function relativePath(v){const s=text(v||'.',260).replace(/\\/g,'/');if(!s||s==='.')return'.';if(s.startsWith('/')||/^[A-Za-z]:/.test(s)||s.split('/').includes('..')||s.includes('\0'))return null;return s.split('/').filter(Boolean).join('/')||'.'}
function uniq(values,limit=64){return [...new Set((Array.isArray(values)?values:[]).map(x=>safeId(x)).filter(Boolean))].slice(0,limit)}
function isHex64(v){return /^[0-9a-f]{64}$/i.test(String(v||''))}
function normalizeWriteSet(v){return [...new Set((Array.isArray(v)?v:[]).map(x=>relativePath(x)).filter(Boolean))].slice(0,80)}
function taskMutates(task){return task.steps.some(s=>MUTATING_OPS.has(s.op))}
function writeSetsOverlap(a,b){if(!a.length||!b.length)return true;return a.some(x=>b.some(y=>x===y||x.startsWith(y+'/')||y.startsWith(x+'/')))}
function stepOps(task){return [...new Set(task.steps.map(x=>x.op))]}
function deviceCovers(device,task){const caps=new Set(Array.isArray(device?.capabilities)?device.capabilities:[]);return stepOps(task).every(op=>caps.has(op))}
function normalizeStep(raw,index,projectPath){
 const op=text(raw?.op,40).toUpperCase(),errors=[];if(!ALLOWED_OPS.includes(op))errors.push(`step ${index+1}: unsupported op ${op||'EMPTY'}`);
 const profile=raw?.profile?text(raw.profile,40).toUpperCase():undefined;if(profile&&!ALLOWED_PROFILES.includes(profile))errors.push(`step ${index+1}: unsupported profile ${profile}`);
 const path=raw?.path===undefined?undefined:relativePath(raw.path);if(raw?.path!==undefined&&!path)errors.push(`step ${index+1}: unsafe path`);
 const url=raw?.url===undefined?undefined:text(raw.url,1000);if(url&&!url.startsWith('https://'))errors.push(`step ${index+1}: HTTPS required`);
 const windowTitle=raw?.windowTitle===undefined?undefined:text(raw.windowTitle,240);if(WINDOW_OPS.has(op)&&!windowTitle)errors.push(`step ${index+1}: window title lock required`);
 if(op==='APPLY_PATCH'&&(!isHex64(raw?.expectedSha256)||!Array.isArray(raw?.replacements)||raw.replacements.length<1||raw.replacements.length>24))errors.push(`step ${index+1}: hash-bound replacements required`);
 if(op==='WRITE_TEXT'&&!raw?.createOnly&&!isHex64(raw?.expectedSha256))errors.push(`step ${index+1}: existing write requires preimage hash`);
 const clean={...raw,id:safeId(raw?.id,`S${String(index+1).padStart(2,'0')}`),op};if(profile)clean.profile=profile;if(path!==undefined)clean.path=path||projectPath;if(url!==undefined)clean.url=url;if(windowTitle!==undefined)clean.windowTitle=windowTitle;
 return{clean,errors};
}
function normalizeTask(raw,index,projectPath){
 const id=safeId(raw?.id,`T${String(index+1).padStart(2,'0')}`),label=text(raw?.label||raw?.name||id,180),dependsOn=uniq(raw?.dependsOn,24),writeSet=normalizeWriteSet(raw?.writeSet),stepsRaw=Array.isArray(raw?.steps)?raw.steps:[],errors=[];
 if(stepsRaw.length<1||stepsRaw.length>24)errors.push(`${id}: 1-24 steps required`);
 const steps=[];for(let i=0;i<stepsRaw.length;i++){const n=normalizeStep(stepsRaw[i],i,projectPath);steps.push(n.clean);errors.push(...n.errors.map(x=>`${id}: ${x}`))}
 const task={id,label,dependsOn,writeSet,steps,profile:text(raw?.profile||'AUTO_BUILD',40).toUpperCase(),preferredDeviceId:safeId(raw?.preferredDeviceId),priority:clamp(raw?.priority??1,0,1),mutates:false,state:'PENDING',jobId:null,assignedDeviceId:null,closureRef:null,scarIds:[]};
 task.mutates=taskMutates(task);if(task.mutates&&!task.writeSet.length)errors.push(`${id}: mutating task requires declared writeSet`);if(task.profile&&!ALLOWED_PROFILES.includes(task.profile))errors.push(`${id}: unsupported task profile ${task.profile}`);
 return{task,errors};
}
function serialTasksFromSteps(steps,projectPath){return (Array.isArray(steps)?steps:[]).map((step,index)=>({id:`T${String(index+1).padStart(2,'0')}`,label:step.label||step.op||`Task ${index+1}`,dependsOn:index?[`T${String(index).padStart(2,'0')}`]:[],writeSet:MUTATING_OPS.has(String(step?.op||'').toUpperCase())?[relativePath(step.path)||projectPath]:[],steps:[step]}))}
function acyclic(tasks){const ids=new Set(tasks.map(x=>x.id)),incoming=new Map(tasks.map(x=>[x.id,0])),out=new Map(tasks.map(x=>[x.id,[]]));for(const task of tasks)for(const dep of task.dependsOn){if(!ids.has(dep))return{ok:false,error:`${task.id}: unknown dependency ${dep}`};incoming.set(task.id,incoming.get(task.id)+1);out.get(dep).push(task.id)}const q=[...tasks.filter(x=>incoming.get(x.id)===0).map(x=>x.id)],seen=[];while(q.length){const id=q.shift();seen.push(id);for(const next of out.get(id)){incoming.set(next,incoming.get(next)-1);if(incoming.get(next)===0)q.push(next)}}return seen.length===tasks.length?{ok:true,order:seen}:{ok:false,error:'task dependency cycle detected'}}
function requiredOps(tasks){return [...new Set(tasks.flatMap(stepOps))]}
function activeJobsForDevice(jobs,deviceId){return (Array.isArray(jobs)?jobs:[]).filter(x=>x?.targetDeviceId===deviceId&&['QUEUED','RUNNING'].includes(x?.status)).length}
function graphPublic(graph){if(!graph)return null;return{...graph,tasks:graph.tasks.map(x=>({...x,steps:x.steps.map(s=>({...s,replacements:s.replacements?`[${s.replacements.length} hash-bound replacements]`:undefined,content:s.content!==undefined?'[bounded content omitted]':undefined}))}))}}

export async function compileWovenExecutionGraphR142(runtime,input={}){
 const objective=text(input.objective||input.intent,4000),projectPath=relativePath(input.projectPath||'.'),replicaPolicy=input.replicaPolicy==='HASH_MATCHED_REPLICAS'?'HASH_MATCHED_REPLICAS':'SINGLE_HOST',maxParallel=clamp(input.maxParallel??(replicaPolicy==='HASH_MATCHED_REPLICAS'?4:1),1,8),rawTasks=Array.isArray(input.tasks)&&input.tasks.length?input.tasks:serialTasksFromSteps(input.steps,projectPath||'.'),errors=[];
 if(!objective)errors.push('objective required');if(!projectPath)errors.push('safe relative projectPath required');if(rawTasks.length<1||rawTasks.length>24)errors.push('1-24 graph tasks required');
 const tasks=[];for(let i=0;i<rawTasks.length;i++){const n=normalizeTask(rawTasks[i],i,projectPath||'.');tasks.push(n.task);errors.push(...n.errors)}
 if(new Set(tasks.map(x=>x.id)).size!==tasks.length)errors.push('task ids must be unique');const topology=acyclic(tasks);if(!topology.ok)errors.push(topology.error);
 const devices=(await runtime.devices()).filter(x=>x?.online===true&&x?.revoked!==true),requested=uniq(input.deviceIds,20),candidates=devices.filter(d=>(!requested.length||requested.includes(d.id))&&(replicaPolicy==='SINGLE_HOST'?requiredOps(tasks).every(op=>d.capabilities?.includes(op)):d.capabilities?.includes('HASH_TREE')&&tasks.some(t=>deviceCovers(d,t))));
 if(replicaPolicy==='SINGLE_HOST'&&!candidates.length)errors.push('no current authenticated device advertises every graph operation');if(replicaPolicy==='HASH_MATCHED_REPLICAS'&&!candidates.length)errors.push('no current authenticated HASH_TREE-capable replica can execute graph tasks');
 const graphCore={schema:R142_SCHEMA,revision:R142_REVISION,objective,projectPath,allowedDomains:(Array.isArray(input.allowedDomains)?input.allowedDomains:[]).map(x=>text(x,180).toLowerCase()).filter(Boolean).slice(0,12),replicaPolicy,maxParallel,tasks:tasks.map(({state,jobId,assignedDeviceId,closureRef,scarIds,...x})=>x),candidateDeviceIds:candidates.map(x=>x.id),topology:topology.order||[],canonicalMutation:false,canonicalAdmissionAuthority:'R125'};
 const graphDigest=await sha256R134(graphCore);return{ok:!errors.length,errors,graphCore,graphDigest,candidateDevices:candidates,truthBoundary:'R142 compilation validates bounded task operations, dependency topology, device capability claims and replica policy only. Compilation never queues native work.'};
}

async function persistGraph(runtime,graph){await runtime.put('r142Graph:'+graph.id,graph);const index=await runtime.get('r142GraphIndex',[]);await runtime.put('r142GraphIndex',[...index.filter(x=>x!==graph.id),graph.id].slice(-80));return graph}
async function readGraph(runtime,id){return runtime.get('r142Graph:'+safeId(id),null)}
async function queueRawJob(runtime,graph,task,device,kind='TASK'){
 const jobs=await runtime.get('jobs',[]),jobId=randomId(kind==='ATTEST'?'job_r142_attest':'job_r142_task'),steps=kind==='ATTEST'?[{id:'S01',op:'HASH_TREE',label:'Prove replica workspace identity before distributed execution',path:graph.projectPath,maxResults:5000}]:task.steps,inputFingerprint=await sha256R134({schema:'OMEGA_WOVEN_GRAPH_JOB_INPUT_R142',graphId:graph.id,taskId:task.id,graphDigest:graph.graphDigest,workspaceSha256:graph.replicaInvariant?.workspaceSha256||null,steps,targetDeviceId:device.id,projectPath:graph.projectPath});
 const job={id:jobId,schema:'OMEGA_WOVEN_GRAPH_JOB_R142',action:kind==='ATTEST'?'ATTEST_REPLICA':'WOVEN_TASK',profile:task?.profile||'AUTO_BUILD',projectPath:graph.projectPath,instructions:kind==='ATTEST'?`R142 replica attestation for ${graph.id}`:`R142 graph ${graph.id} task ${task.id}: ${task.label}`,allowedDomains:graph.allowedDomains||[],steps,targetDeviceId:device.id,targetCapabilityRevision:device.capabilityRevision||'LEGACY',status:'QUEUED',confirmed:true,queuedAt:now(),inputFingerprint,graphRef:{schema:R142_SCHEMA,graphId:graph.id,taskId:task.id,kind,graphDigest:graph.graphDigest,canonicalMutation:false}};
 jobs.push(job);await runtime.put('jobs',jobs.slice(-160));await runtime.event(kind==='ATTEST'?'R142_REPLICA_ATTESTATION_QUEUED':'R142_TASK_QUEUED',kind==='ATTEST'?`Replica ${device.id} attestation queued for graph ${graph.id}.`:`Graph ${graph.id} task ${task.id} queued on ${device.id}.`,{graphId:graph.id,taskId:task.id,deviceId:device.id,jobId});return job;
}
function extractTreeHash(closure){const proofs=closure?.input?.core?.stepProofs||[];for(const proof of proofs){const r=proof?.result||{};for(const value of [r.treeSha256,r.tree_sha256,r.rootSha256,r.root_sha256])if(isHex64(value))return String(value).toLowerCase()}return null}
function depsComplete(graph,task){return task.dependsOn.every(id=>graph.tasks.find(x=>x.id===id)?.state==='COMPLETE')}
function activeTasks(graph){return graph.tasks.filter(x=>['QUEUED','RUNNING'].includes(x.state))}
function taskCompatibleWithActive(task,deviceId,graph){for(const other of activeTasks(graph)){if(other.assignedDeviceId!==deviceId)continue;if(!task.mutates||!other.mutates)continue;if(writeSetsOverlap(task.writeSet,other.writeSet))return false}return true}
function taskProofIds(graph){return graph.tasks.map(x=>x.closureRef?.fingerprint).filter(isHex64).slice(-64)}
function taskSourceIds(graph){return [...new Set(graph.tasks.map(x=>x.assignedDeviceId).filter(Boolean))].slice(-64)}
async function appendGraphWorldEvent(runtime,graph,kind,scarIds=[]){const previous=await runtime.get('r141WorldHead',null),proofIds=taskProofIds(graph),event=await appendWorldEventR134(previous,{eventId:`${graph.id}:${kind.toLowerCase()}`,kind,sequence:(previous?.count||0)+1,eventTime:now(),observerId:'r142-woven-execution-graph',projection:'HYBRID_EXECUTION',missionId:graph.id,sourceIds:taskSourceIds(graph),proofIds,scarIds,payloadDigest:graph.graphDigest,metrics:{continuity:kind==='PROOF'?1:0.35,plasticity:kind==='PROOF'?.45:.1,contradiction:kind==='PROOF'?0:1,burden:Math.min(1,graph.tasks.length/24),evidence:proofIds.length?1:0,uncertainty:kind==='PROOF'?.05:1,scar:kind==='PROOF'?.1:1},claim:{publicDeploymentProved:false,pcOnlineProved:false,solverValidityProved:false,computedPhotorealRealityProved:false}});await runtime.put('r141WorldHead',event);return{head:event,operationRef:continuityOperationRefR134(event)}}
async function holdGraph(runtime,graph,code,detail,scarIds=[]){graph.state='HELD';graph.hold={code,detail,at:now()};graph.updatedAt=now();const world=await appendGraphWorldEvent(runtime,graph,'SCAR',scarIds.length?scarIds:[graph.id]);graph.joinReceipt={schema:'OMEGA_WOVEN_GRAPH_JOIN_R142',state:'HELD',code,worldHeadSha256:world.head.headSha256,continuity:world.operationRef,canonicalMutation:false,canonicalAdmissionAuthority:'R125'};await persistGraph(runtime,graph);await runtime.event('R142_GRAPH_HELD',`Graph ${graph.id} held: ${code}.`,{graphId:graph.id,code,detail});return graph}
async function completeGraph(runtime,graph){const world=await appendGraphWorldEvent(runtime,graph,'PROOF',graph.tasks.flatMap(x=>x.scarIds||[]));graph.state='COMPLETE';graph.completedAt=now();graph.updatedAt=now();graph.joinReceipt={schema:'OMEGA_WOVEN_GRAPH_JOIN_R142',state:'VERIFIED_JOIN',graphDigest:graph.graphDigest,workspaceSha256:graph.replicaInvariant?.workspaceSha256||null,taskCount:graph.tasks.length,verifiedTaskCount:graph.tasks.filter(x=>x.closureRef?.fingerprintVerified===true).length,sourceDeviceIds:taskSourceIds(graph),proofIds:taskProofIds(graph),worldHeadSha256:world.head.headSha256,continuity:world.operationRef,canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'The R142 join proves deterministic completion of the pre-approved graph from verified R141 host returns. It does not mutate CanonState.'};await persistGraph(runtime,graph);await runtime.event('R142_GRAPH_JOIN_VERIFIED',`Graph ${graph.id} joined ${graph.tasks.length} task paths into one deterministic proof receipt.`,{graphId:graph.id,worldHeadSha256:world.head.headSha256});return graph}

async function queueReady(runtime,graph){
 if(!['RUNNING','ATTESTING'].includes(graph.state))return graph;if(graph.state==='ATTESTING')return graph;
 const devices=(await runtime.devices()).filter(x=>x?.online===true&&x?.revoked!==true&&(graph.admittedDeviceIds||[]).includes(x.id)),jobs=await runtime.get('jobs',[]),capacity=Math.max(0,graph.maxParallel-activeTasks(graph).length);if(!capacity)return graph;
 let queued=0;for(const task of graph.tasks){if(queued>=capacity)break;if(task.state!=='PENDING'||!depsComplete(graph,task))continue;const candidates=devices.filter(d=>deviceCovers(d,task)&&(!task.preferredDeviceId||d.id===task.preferredDeviceId)&&taskCompatibleWithActive(task,d.id,graph)).sort((a,b)=>activeJobsForDevice(jobs,a.id)-activeJobsForDevice(jobs,b.id)||a.id.localeCompare(b.id));if(!candidates.length)continue;const device=candidates[0],job=await queueRawJob(runtime,graph,task,device,'TASK');task.state='QUEUED';task.jobId=job.id;task.assignedDeviceId=device.id;task.queuedAt=job.queuedAt;queued++}
 graph.updatedAt=now();if(!queued&&graph.tasks.every(x=>x.state==='COMPLETE'))return completeGraph(runtime,graph);await persistGraph(runtime,graph);return graph;
}
async function queueAttestations(runtime,graph){const devices=(await runtime.devices()).filter(x=>graph.candidateDeviceIds.includes(x.id)&&x.online&&!x.revoked);for(const device of devices){const fake={id:`ATTEST:${device.id}`,label:'Replica attestation',steps:[{op:'HASH_TREE'}],profile:'AUTO_BUILD'};const job=await queueRawJob(runtime,graph,fake,device,'ATTEST');graph.attestations.push({deviceId:device.id,jobId:job.id,state:'QUEUED',treeSha256:null,closureHead:null})}graph.state='ATTESTING';graph.updatedAt=now();return persistGraph(runtime,graph)}

export async function createWovenExecutionGraphR142(runtime,input={},ownerId=''){
 if(input.confirmedGraph!==true)return{ok:false,code:'GRAPH_CONFIRMATION_REQUIRED',reply:'R142 compilation may be previewed without execution, but graph creation requires explicit confirmedGraph=true.'};const compiled=await compileWovenExecutionGraphR142(runtime,input);if(!compiled.ok)return{ok:false,code:'GRAPH_REJECTED',errors:compiled.errors,compiled};
 const id=randomId('graph_r142'),graph={...compiled.graphCore,id,graphDigest:compiled.graphDigest,ownerId:safeId(ownerId),state:'PLANNED',createdAt:now(),updatedAt:now(),maxParallel:compiled.graphCore.maxParallel,candidateDeviceIds:compiled.candidateDevices.map(x=>x.id),admittedDeviceIds:[],replicaInvariant:{state:'UNPROVED',workspaceSha256:null,deviceCount:0},attestations:[],tasks:compiled.graphCore.tasks.map(x=>({...x,state:'PENDING',jobId:null,assignedDeviceId:null,closureRef:null,scarIds:[]})),joinReceipt:null,canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R142 may advance only the explicitly confirmed bounded task graph. Every native dependency edge requires a verified R141 return; multi-device execution remains blocked until workspace hashes agree.'};await persistGraph(runtime,graph);await runtime.event('R142_GRAPH_CREATED',`Woven execution graph ${id} created with ${graph.tasks.length} bounded tasks.`,{graphId:id,replicaPolicy:graph.replicaPolicy,maxParallel:graph.maxParallel,candidates:graph.candidateDeviceIds});
 if(graph.replicaPolicy==='HASH_MATCHED_REPLICAS')return{ok:true,graph:graphPublic(await queueAttestations(runtime,graph))};
 const device=compiled.candidateDevices[0];graph.admittedDeviceIds=[device.id];graph.replicaInvariant={state:'SINGLE_HOST',workspaceSha256:null,deviceCount:1};graph.state='RUNNING';await persistGraph(runtime,graph);return{ok:true,graph:graphPublic(await queueReady(runtime,graph))};
}

export async function advanceWovenGraphsR142(runtime,jobId,closure){
 const ids=await runtime.get('r142GraphIndex',[]);for(const graphId of [...ids].reverse()){const graph=await readGraph(runtime,graphId);if(!graph||TERMINAL_TASK.has(graph.state)||['PAUSED','CANCELLED'].includes(graph.state))continue;const att=graph.attestations.find(x=>x.jobId===jobId);if(att){if(closure?.fingerprint?.verified!==true||closure?.state!=='VERIFIED_EXECUTION_RETURN'){att.state='HELD';att.closureHead=closure?.finalHeadSha256||null;return holdGraph(runtime,graph,'REPLICA_ATTESTATION_PROOF_FAILED',`Device ${att.deviceId} did not return verified R141 attestation.`,[jobId])}const treeSha256=extractTreeHash(closure);if(!treeSha256){att.state='HELD';att.closureHead=closure?.finalHeadSha256||null;return holdGraph(runtime,graph,'REPLICA_HASH_MISSING',`Device ${att.deviceId} returned proof without a HASH_TREE identity.`,[jobId])}att.state='COMPLETE';att.treeSha256=treeSha256;att.closureHead=closure.finalHeadSha256;graph.updatedAt=now();if(graph.attestations.every(x=>x.state==='COMPLETE')){const hashes=[...new Set(graph.attestations.map(x=>x.treeSha256))];if(hashes.length!==1)return holdGraph(runtime,graph,'REPLICA_DRIFT',`Replica workspace hashes disagree: ${hashes.join(', ')}`,graph.attestations.map(x=>x.jobId));graph.replicaInvariant={state:'HASH_MATCH_VERIFIED',workspaceSha256:hashes[0],deviceCount:graph.attestations.length,attestedAt:now()};graph.admittedDeviceIds=graph.attestations.map(x=>x.deviceId);graph.state='RUNNING';await runtime.event('R142_REPLICA_INVARIANT_VERIFIED',`Graph ${graph.id} admitted ${graph.admittedDeviceIds.length} hash-matched replicas.`,{graphId:graph.id,workspaceSha256:hashes[0],deviceIds:graph.admittedDeviceIds});await persistGraph(runtime,graph);return queueReady(runtime,graph)}await persistGraph(runtime,graph);return graph}
 const task=graph.tasks.find(x=>x.jobId===jobId);if(!task)continue;if(closure?.fingerprint?.verified!==true){task.state='HELD';task.scarIds=[...(task.scarIds||[]),jobId];task.closureRef={fingerprintVerified:false,headSha256:closure?.finalHeadSha256||null};return holdGraph(runtime,graph,'TASK_PROOF_FAILED',`Task ${task.id} returned without verified R141 proof.`,[jobId])}task.closureRef={schema:closure.schema,state:closure.state,fingerprintVerified:true,fingerprint:closure.fingerprint.supplied,headSha256:closure.finalHeadSha256,continuity:closure.continuity,deviceId:task.assignedDeviceId};if(closure.state!=='VERIFIED_EXECUTION_RETURN'){task.state='FAILED';task.scarIds=[...(task.scarIds||[]),jobId];graph.state='FAILED';graph.updatedAt=now();await persistGraph(runtime,graph);await appendGraphWorldEvent(runtime,graph,'SCAR',[jobId]);await runtime.event('R142_TASK_FAILED',`Graph ${graph.id} task ${task.id} returned verified failure evidence.`,{graphId:graph.id,taskId:task.id,jobId});return graph}task.state='COMPLETE';task.completedAt=now();await runtime.event('R142_TASK_PROOF_ACCEPTED',`Graph ${graph.id} task ${task.id} advanced from verified R141 closure.`,{graphId:graph.id,taskId:task.id,jobId,headSha256:closure.finalHeadSha256});await persistGraph(runtime,graph);return queueReady(runtime,graph)}return null;
}

export async function listWovenExecutionGraphsR142(runtime){const ids=await runtime.get('r142GraphIndex',[]),rows=[];for(const id of [...ids].reverse().slice(0,40)){const graph=await readGraph(runtime,id);if(graph)rows.push(graphPublic(graph))}return{ok:true,schema:'OMEGA_WOVEN_EXECUTION_GRAPH_LIST_R142',revision:R142_REVISION,graphs:rows,canonicalMutation:false}}
export async function readWovenExecutionGraphR142(runtime,id){const graph=await readGraph(runtime,id);return graphPublic(graph)}
export async function controlWovenExecutionGraphR142(runtime,id,action){const graph=await readGraph(runtime,id);if(!graph)return null;if(action==='pause'&&['RUNNING','ATTESTING'].includes(graph.state)){graph.state='PAUSED';graph.updatedAt=now();await persistGraph(runtime,graph);await runtime.event('R142_GRAPH_PAUSED',`Graph ${graph.id} paused; already-queued host work is not silently cancelled.`,{graphId:graph.id});return graphPublic(graph)}if(action==='resume'&&graph.state==='PAUSED'){graph.state=graph.replicaPolicy==='HASH_MATCHED_REPLICAS'&&!graph.replicaInvariant?.workspaceSha256?'ATTESTING':'RUNNING';graph.updatedAt=now();await persistGraph(runtime,graph);return graphPublic(await queueReady(runtime,graph))}if(action==='cancel'&&!TERMINAL_TASK.has(graph.state)){graph.state='CANCELLED';graph.updatedAt=now();await persistGraph(runtime,graph);await runtime.event('R142_GRAPH_CANCELLED',`Graph ${graph.id} cancelled; no new tasks will queue.`,{graphId:graph.id});return graphPublic(graph)}return graphPublic(graph)}
export async function previewWovenExecutionGraphR142(runtime,input){const compiled=await compileWovenExecutionGraphR142(runtime,input);return{...compiled,graphCore:compiled.graphCore?{...compiled.graphCore,tasks:compiled.graphCore.tasks.map(x=>({...x,steps:x.steps.map(s=>({...s,content:s.content!==undefined?'[bounded content omitted]':undefined,replacements:s.replacements?`[${s.replacements.length} hash-bound replacements]`:undefined}))}))}:null}}
export function manifestR142(){return{ok:true,schema:R142_SCHEMA,revision:R142_REVISION,laws:R142_LAWS,executorAuthority:{native:'CURRENT_AUTHENTICATED_R32_R141_HYBRID_DEVICES_ONLY',replicaAdmission:'HASH_TREE_SHA256_EQUALITY',dependencyProof:'R141_VERIFIED_CLOSURE',worldJoin:'R134_APPEND_ONLY_PROOF_OR_SCAR',canonicalAdmission:'R125'},limits:{tasks:24,stepsPerTask:24,maxParallel:8,graphHistory:80},preserves:{capability:'R139',livingOperation:'R140',hostReturnProof:'R141',worldContinuity:'R134'},canonicalMutation:false,canonicalAdmissionAuthority:'R125',truthBoundary:'R142 is a real bounded native execution DAG over authenticated Hybrid devices. It can parallelize independent work only after replica workspace hashes agree and it advances dependencies only from verified R141 closure. Its final join is evidence continuity, not CanonState promotion.'}}
