export const R181_CALIBRATION_GATEWAY_REVISION='R181';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-calibration-runtime':'R181'};
const APPROVED_ORIGINS=new Set(['https://omegav6.jeffdeweyeljefe.workers.dev','https://omega-genesis-v1.jeffdeweyeljefe.workers.dev','https://omega-living-light-etching-private-woven2.vercel.app','https://omega-optical-cloud-woven2.vercel.app']);
const safeId=v=>{const s=String(v??'').trim().slice(0,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:''};
const json=(value,status=200,extra={})=>new Response(JSON.stringify(value,null,2),{status,headers:{...JSON_HEADERS,...extra}});
function cors(request){const origin=request.headers.get('origin');if(!origin)return{};return APPROVED_ORIGINS.has(origin)?{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-omega-session-id,x-omega-bridge-id,x-omega-bridge-secret,cache-control','access-control-expose-headers':'x-omega-calibration-runtime'}:{}}
function withCors(response,request){const headers=new Headers(response.headers);headers.set('x-omega-calibration-runtime','R181');headers.set('cache-control','no-store');for(const[k,v]of Object.entries(cors(request)))headers.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function calibrationRoot(env){if(!env?.OMEGA_SWARM_AUTONOMIC)return null;return env.OMEGA_SWARM_AUTONOMIC.get(env.OMEGA_SWARM_AUTONOMIC.idFromName('omega-autonomic-root-r125'))}
async function bridgeAuthorized(request,env){const bridgeId=safeId(request.headers.get('x-omega-bridge-id')||request.headers.get('x-omega-session-id')),secret=String(request.headers.get('x-omega-bridge-secret')||'').trim();if(!bridgeId||!secret||!env?.OMEGA_RUNTIME)return false;try{const stub=env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(bridgeId)),headers=new Headers(request.headers);headers.set('x-omega-bridge-id',bridgeId);const response=await stub.fetch(new Request('https://omega-runtime.internal/continuity',{method:'GET',headers}));return response.ok}catch{return false}}
function internalPath(url){const tail=url.pathname.slice('/api/calibration/r181'.length);return `/calibration/r181${tail}`}
const finite=v=>Number.isFinite(Number(v))?Number(v):null;
function fusedValue(state,names){const metrics=state?.fusedMetrics||{};for(const name of names){const row=metrics[name],v=finite(row?.value);if(v!==null)return v}return null}
function calibrationPlanInput(state,input={}){const derived={continuity:fusedValue(state,['continuity','COmega','CΩ']),plasticity:fusedValue(state,['plasticity','Phi','Φ']),contradiction:fusedValue(state,['contradiction','q']),burden:fusedValue(state,['burden','Lambda','Λ']),evidence:fusedValue(state,['evidence']),uncertainty:fusedValue(state,['uncertainty']),scar:fusedValue(state,['scar'])},calibrationMetrics=Object.fromEntries(Object.entries(derived).filter(([,v])=>v!==null)),explicit=input?.metrics&&typeof input.metrics==='object'?input.metrics:{},metrics={...calibrationMetrics,...explicit},existingEvidence=Array.isArray(input?.evidence)?input.evidence:[],fingerprint=String(state?.fingerprint||''),calibrationEvidence={id:'r181-calibration-state',type:'CALIBRATION_STATE',sha256:/^[a-f0-9]{64}$/i.test(fingerprint)?fingerprint:null,summary:`R181 fused calibration · ${state?.packetCount||0} packets · ${state?.sourceCount||0} sources · ${state?.residual?.highUncertaintyCount||0} high-uncertainty metrics`,authority:'R181_EVIDENCE_WEIGHTED_ESTIMATE_NOT_CANON'};return{...input,metrics,evidence:[...existingEvidence,calibrationEvidence].slice(-16),calibrationContext:{revision:'R181',fingerprint:state?.fingerprint||null,packetCount:state?.packetCount||0,sourceCount:state?.sourceCount||0,domains:state?.domains||[],weakestMetrics:state?.planningHints?.weakestMetrics||[],appliedOnlyToMissingMetrics:true,explicitOperatorMetricsOverride:true,automaticFullEscalation:false,canonicalMutation:false}}}
async function currentCalibration(root){const stateResponse=await root.fetch(new Request('https://autonomic.internal/calibration/r181/state',{method:'GET'})),stateBody=await stateResponse.json().catch(()=>({})),state=stateBody?.state||null;return{ok:stateResponse.ok&&Boolean(state),state,status:stateResponse.status}}
async function calibratedPlan(root,input){const current=await currentCalibration(root);if(!current.ok)return{response:json({ok:false,code:'R181_CALIBRATION_STATE_UNAVAILABLE',canonicalMutation:false},503),state:null};const planInput=calibrationPlanInput(current.state,input),planResponse=await root.fetch(new Request('https://autonomic.internal/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(planInput)})),planBody=await planResponse.json().catch(()=>({}));return{response:json({...planBody,calibrationContext:planInput.calibrationContext,truthBoundary:'R181 fills only missing planning metrics and attaches its state fingerprint as evidence. Explicit operator metrics/mode remain authoritative inputs; calibration does not set FULL, authorize R147 dispatch, or mutate CanonState.'},planResponse.status),state:current.state}}
async function calibratedMission(root,input){const current=await currentCalibration(root);if(!current.ok)return json({ok:false,code:'R181_CALIBRATION_STATE_UNAVAILABLE',canonicalMutation:false},503);const missionInput=calibrationPlanInput(current.state,input),response=await root.fetch(new Request('https://autonomic.internal/missions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(missionInput)})),body=await response.json().catch(()=>({}));return json({...body,calibrationContext:missionInput.calibrationContext,truthBoundary:'This operator-confirmed request creates an R125 autonomic mission using the exact R181 calibration fingerprint as evidence. It may execute bounded swarm work through R125, but it does not authorize R147 device dispatch, prove returned external execution, or mutate CanonState.'},response.status)}
export async function calibrationGatewayR181(request,env,url=new URL(request.url)){
 if(!url.pathname.startsWith('/api/calibration/r181'))return null;
 if(request.method==='OPTIONS'){const headers=cors(request);return Object.keys(headers).length?new Response(null,{status:204,headers:{...headers,'x-omega-calibration-runtime':'R181'}}):new Response(null,{status:403,headers:{'x-omega-calibration-runtime':'R181'}})}
 const root=calibrationRoot(env);if(!root)return withCors(json({ok:false,code:'R181_CALIBRATION_ROOT_UNAVAILABLE',canonicalMutation:false},503),request);
 const isPlan=request.method==='POST'&&url.pathname==='/api/calibration/r181/plan',isMission=request.method==='POST'&&url.pathname==='/api/calibration/r181/mission',readOnly=request.method==='GET';
 if(!readOnly&&!isPlan&&!isMission&&request.method!=='POST')return withCors(json({ok:false,code:'METHOD_NOT_ALLOWED',allowed:['GET','POST'],canonicalMutation:false},405),request);
 let body=null;if(!readOnly)body=await request.json().catch(()=>({}));
 if(isPlan){const out=await calibratedPlan(root,body||{});return withCors(out.response,request)}
 if(isMission){if(body?.confirmCalibratedMission!==true)return withCors(json({ok:false,code:'R181_EXPLICIT_CALIBRATED_MISSION_CONFIRMATION_REQUIRED',canonicalMutation:false},409),request);if(!await bridgeAuthorized(request,env))return withCors(json({ok:false,code:'R181_AUTHENTICATED_BRIDGE_REQUIRED',reply:'Creating a calibration-driven autonomic mission requires the current paired bridge credential. No mission was created.',canonicalMutation:false},401),request);const{confirmCalibratedMission,...missionInput}=body||{};return withCors(await calibratedMission(root,missionInput),request)}
 if(!readOnly){const confirmed=url.pathname.endsWith('/ingest')?body?.confirmCalibrationIngest===true:url.pathname.endsWith('/recompute')?body?.confirmCalibrationRecompute===true:false;if(!confirmed)return withCors(json({ok:false,code:'R181_EXPLICIT_CALIBRATION_CONFIRMATION_REQUIRED',canonicalMutation:false},409),request);if(!await bridgeAuthorized(request,env))return withCors(json({ok:false,code:'R181_AUTHENTICATED_BRIDGE_REQUIRED',reply:'Persistent calibration changes require the current paired bridge credential. Calibration remains non-canonical and does not dispatch execution.',canonicalMutation:false},401),request)}
 const allowedRead=/^\/api\/calibration\/r181\/(manifest|state|packets(?:\/[A-Za-z0-9._:-]+)?)$/.test(url.pathname),allowedWrite=/^\/api\/calibration\/r181\/(ingest|recompute)$/.test(url.pathname);if((readOnly&&!allowedRead)||(!readOnly&&!allowedWrite))return withCors(json({ok:false,code:'R181_CALIBRATION_ROUTE_NOT_FOUND',canonicalMutation:false},404),request);
 const payload=readOnly?undefined:url.pathname.endsWith('/ingest')?(body?.packet||body):{};const headers=new Headers({'content-type':'application/json'});const internal=await root.fetch(new Request(`https://autonomic.internal${internalPath(url)}`,{method:request.method,headers,body:payload===undefined?undefined:JSON.stringify(payload)}));return withCors(internal,request)
}
export const R181_CALIBRATION_GATEWAY_BOUNDARY='Public R181 reads and calibrated-plan previews are non-mutating. Persistent ingest/recompute and calibrated mission creation require explicit confirmation plus the existing authenticated bridge credential. R181 may drive bounded R125 swarm computation; it never self-authorizes R147 device dispatch or CanonState admission.';
