export const R181_CALIBRATION_GATEWAY_REVISION='R181';
const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-omega-calibration-runtime':'R181'};
const APPROVED_ORIGINS=new Set(['https://omegav6.jeffdeweyeljefe.workers.dev','https://omega-genesis-v1.jeffdeweyeljefe.workers.dev','https://omega-living-light-etching-private-woven2.vercel.app','https://omega-optical-cloud-woven2.vercel.app']);
const safeId=v=>{const s=String(v??'').trim().slice(0,160);return /^[A-Za-z0-9._:-]+$/.test(s)?s:''};
const json=(value,status=200,extra={})=>new Response(JSON.stringify(value,null,2),{status,headers:{...JSON_HEADERS,...extra}});
function cors(request){const origin=request.headers.get('origin');if(!origin)return{};return APPROVED_ORIGINS.has(origin)?{'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-omega-session-id,x-omega-bridge-id,x-omega-bridge-secret,cache-control','access-control-expose-headers':'x-omega-calibration-runtime'}:{}}
function withCors(response,request){const headers=new Headers(response.headers);headers.set('x-omega-calibration-runtime','R181');headers.set('cache-control','no-store');for(const[k,v]of Object.entries(cors(request)))headers.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
function calibrationRoot(env){if(!env?.OMEGA_SWARM_AUTONOMIC)return null;return env.OMEGA_SWARM_AUTONOMIC.get(env.OMEGA_SWARM_AUTONOMIC.idFromName('omega-autonomic-root-r125'))}
async function bridgeAuthorized(request,env){const bridgeId=safeId(request.headers.get('x-omega-bridge-id')||request.headers.get('x-omega-session-id')),secret=String(request.headers.get('x-omega-bridge-secret')||'').trim();if(!bridgeId||!secret||!env?.OMEGA_RUNTIME)return false;try{const stub=env.OMEGA_RUNTIME.get(env.OMEGA_RUNTIME.idFromName(bridgeId)),headers=new Headers(request.headers);headers.set('x-omega-bridge-id',bridgeId);const response=await stub.fetch(new Request('https://omega-runtime.internal/continuity',{method:'GET',headers}));return response.ok}catch{return false}}
function internalPath(url){const tail=url.pathname.slice('/api/calibration/r181'.length);return `/calibration/r181${tail}`}
export async function calibrationGatewayR181(request,env,url=new URL(request.url)){
 if(!url.pathname.startsWith('/api/calibration/r181'))return null;
 if(request.method==='OPTIONS'){const headers=cors(request);return Object.keys(headers).length?new Response(null,{status:204,headers:{...headers,'x-omega-calibration-runtime':'R181'}}):new Response(null,{status:403,headers:{'x-omega-calibration-runtime':'R181'}})}
 const root=calibrationRoot(env);if(!root)return withCors(json({ok:false,code:'R181_CALIBRATION_ROOT_UNAVAILABLE',canonicalMutation:false},503),request);
 const readOnly=request.method==='GET';
 if(!readOnly&&request.method!=='POST')return withCors(json({ok:false,code:'METHOD_NOT_ALLOWED',allowed:['GET','POST'],canonicalMutation:false},405),request);
 let body=null;
 if(!readOnly){body=await request.json().catch(()=>({}));const confirmed=url.pathname.endsWith('/ingest')?body?.confirmCalibrationIngest===true:url.pathname.endsWith('/recompute')?body?.confirmCalibrationRecompute===true:false;if(!confirmed)return withCors(json({ok:false,code:'R181_EXPLICIT_CALIBRATION_CONFIRMATION_REQUIRED',canonicalMutation:false},409),request);if(!await bridgeAuthorized(request,env))return withCors(json({ok:false,code:'R181_AUTHENTICATED_BRIDGE_REQUIRED',reply:'Persistent calibration changes require the current paired bridge credential. Calibration remains non-canonical and does not dispatch execution.',canonicalMutation:false},401),request)}
 const allowedRead=/^\/api\/calibration\/r181\/(manifest|state|packets(?:\/[A-Za-z0-9._:-]+)?)$/.test(url.pathname),allowedWrite=/^\/api\/calibration\/r181\/(ingest|recompute)$/.test(url.pathname);if((readOnly&&!allowedRead)||(!readOnly&&!allowedWrite))return withCors(json({ok:false,code:'R181_CALIBRATION_ROUTE_NOT_FOUND',canonicalMutation:false},404),request);
 const payload=readOnly?undefined:url.pathname.endsWith('/ingest')?(body?.packet||body):{};const headers=new Headers({'content-type':'application/json'});const internal=await root.fetch(new Request(`https://autonomic.internal${internalPath(url)}`,{method:request.method,headers,body:payload===undefined?undefined:JSON.stringify(payload)}));return withCors(internal,request)
}
export const R181_CALIBRATION_GATEWAY_BOUNDARY='Public R181 reads are inspection-only. Persistent ingest/recompute requires explicit confirmation plus the existing authenticated bridge credential; calibration changes estimates and residuals only, never R147 dispatch or CanonState.';
